- lib/common_test/doc/src/basics_chapter.xml
Clarify and avoid misunderstandings. In the previous sentence,
it is written that "the test case is the smallest unit...". To me
it was confusing when I read the following sentence: "Subsets of
test cases, ...". The key part of the paragraph is that test cases
can be grouped, not that they are subsets.
> Rewords one sentence in common_test documentation

- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/dtls_packet_demux.erl
- lib/ssl/src/dtls_socket.erl
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/tls_socket.erl
- lib/ssl/test/ssl_basic_SUITE.erl
<s>There's probably missing stuff for DTLS, and the documentation is also missing, but this is a good time to get a first review. The added tests pass and check the option with listen, server and client sockets. I'll probably need some guidance about DTLS.</s>
All functionality is there and tests pass! Documentation and possibly some refactoring remains.
> ssl: Add support for {active,N}

- lib/kernel/src/inet_db.erl
- lib/kernel/test/inet_SUITE.erl
If .hosts file does not exist when kernel application starts, it will never get reloaded.
> inet_db: fix a bug when .hosts file is never reloaded

- lib/erl_docgen/priv/css/otp_doc.css
- lib/erl_docgen/priv/xsl/db_html.xsl
with indentation and one function argument per line.
Example
Before: http://erlang.org/doc/man/erl_nif.html#enif_open_resource_type
After: http://erlang.org/~sverker/prettify_cfunc_doc/html/erl_nif.html#enif_open_resource_type
> Make C function documentation more readable

- erts/etc/unix/to_erl.c
Symptom: to_erl garbles anything beyond 7-bit ASCII received on STDIN
Solution: Remove setting of ISTRIP flag on input terminal which strips off the eighth bit.
> Remove 7-bit ASCII limitation in to_erl

- erts/emulator/beam/arith_instrs.tab
- erts/emulator/beam/beam_emu.c
- erts/emulator/beam/beam_load.c
- erts/emulator/beam/bif_instrs.tab
- erts/emulator/beam/bs_instrs.tab
- erts/emulator/beam/instrs.tab
- erts/emulator/beam/ops.tab
- erts/emulator/beam/sys.h
- erts/emulator/utils/beam_makeops
This pull request tunes more BEAM instructions to better suit the code generated by the new SSA-based compiler. I have based it on instruction frequencies when Dialyzer builds a small PLT.
> Tune BEAM instructions for the new compiler (part 2)

- lib/kernel/doc/src/kernel_app.xml
- lib/kernel/src/kernel.erl
- lib/kernel/test/kernel_config_SUITE.erl
Sometimes you may want to start Erlang without any
of its distribution services. This commit adds an
environment configuration that allows so.
Because the servers we don't start here are a subset
of the servers not started on minimal mode, we do
have a guarantee that the system can still operate
as the system operates without those apps on minimal
mode.
> Add start_distribution to kernel environment

- erts/doc/src/erl_nif.xml
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_nif.h
- erts/emulator/beam/erl_nif_api_funcs.h
- erts/emulator/test/nif_SUITE.erl
- erts/emulator/test/nif_SUITE_data/nif_SUITE.c
This helps avoid long sequences of `enif_is_xxx` in code that serializes terms (such as JSON encoders) by letting the user switch on the type.
Thanks to @dhull for pointing out the need for this!
https://github.com/erlang/otp/pull/2143#issuecomment-464379596
> erts: Add enif_term_type

- erts/emulator/beam/beam_load.c
This is particularly important in case insensitive filesystems,
where attempting to invoke a module with the wrong case leads
to confusing error messages:
1> erlpress_core:foo().
beam/beam_load.c(1428): Error loading module 'erlpress_core':
module name in object code is erlPress_core
Loading of erlPress_core.beam failed: :badfile
This commit replaces object code by BEAM file and improves
the readability of the message.
> Clarify beam_load error message on file/module mismatch

- erts/emulator/beam/bif.c
- erts/emulator/beam/bif_instrs.tab
- erts/emulator/beam/ops.tab
- erts/emulator/test/trace_local_SUITE.erl
- lib/compiler/test/beam_except_SUITE.erl
BEAM currently does not call BIFs at the end of a function in a
tail-recursive way. That is, when calling a BIF at the end of a
function, the BIF is first called, and then the stack frame
is deallocated, and then control is transferred to the caller.
If there is no stack frame when a BIF is called in the tail position,
the loader will emit a sequence of three instructions: first an
instruction that allocates a stack frame and saves the continuation
pointer (`allocate`), then an instruction that calls the BIF
(`call_bif`), and lastly an instruction that deallocates the stack
frame and returns to the caller (`deallocate_return`).
The old compiler would essentially allocate a stack frame for each
clause in a function, so it would not be that common that a BIF was
called in the tail position …
> Optimize tail-recursive calls of BIFs

- erts/doc/src/alt_dist.xml
Noticed the typo when reading http://erlang.org/doc/apps/erts/alt_dist.html.
> retranspissions -> retransmissions

- lib/stdlib/doc/src/beam_lib.xml
- lib/stdlib/src/beam_lib.erl
- lib/stdlib/test/beam_lib_SUITE.erl
This allows other BEAM languages to specify additional chunks that should be preserved.  The immediate need is 'Attr' for Elixir.
See https://github.com/whitfin/cachex/issues/205 for full details on the original issue.
> Allow list of chunks to be given to strip*()

- lib/erl_interface/src/prog/ei_fake_prog.c
- lib/erl_interface/src/prog/erl_call.c
- lib/erl_interface/src/prog/erl_start.c
- lib/erl_interface/test/Makefile
- lib/erl_interface/test/erl_call_SUITE.erl
Previously erl_call relied on the implicit initialization made of the ei-lib if no explicit initialization had been done. This implicit initialization was utterly broken and was removed in erl_interface-3.11 (OTP 21.3) since it has been documented for a very long time that an explicit initialization is required.
> Fix erl_call

- lib/public_key/asn1/OTP-PKIX.asn1
Some certificate issuers like Apple use USA instead of US as a country
name. This makes handshake with a server not possible as this considered
as not valid certificate. This commit eases that requirement to allow
both 2 and 3 letters country names.
> public_key: allowed 3 letters country code to be valid

- erts/emulator/beam/beam_debug.c
- erts/emulator/beam/beam_load.c
- erts/emulator/beam/instrs.tab
- erts/emulator/beam/map_instrs.tab
- erts/emulator/beam/ops.tab
- erts/emulator/utils/beam_makeops
This pull request tunes more BEAM instructions.
There are also a few bug fixes for the BEAM disassembler and a refactoring of `beam_load.c` to make it immediately noticeable if an instruction gets the wrong arity.
> Tune BEAM instructions for the new compiler (part 3)

- lib/kernel/src/application_controller.erl
- lib/kernel/test/application_SUITE.erl
Erlang/OTP 21.3 warned on those cases and now we will
raise on Erlang/OTP 22.0.
> Error on duplicated config apps/keys in -config

- .gitignore
This file shouldn't be ignored:
```
/lib/asn1/test/asn1_SUITE.erl
```
These files don't exist any longer:
```
/lib/asn1/test/asn1_bin_SUITE.erl
/lib/asn1/test/asn1_bin_v2_SUITE.erl
```
> Remove asn1/test items from .gitignore

- lib/asn1/src/asn1ct_check.erl
- lib/asn1/test/Makefile
- lib/asn1/test/asn1_SUITE.erl
- lib/asn1/test/asn1_SUITE_data/ChoExtension.asn1
- lib/asn1/test/asn1_SUITE_data/DefaultOctetString.asn
- lib/asn1/test/asn1_SUITE_data/SeqOfChoExt.asn1
- lib/asn1/test/testChoExtension.erl
- lib/asn1/test/testDefaultOctetString.erl
- lib/asn1/test/testSeqOfChoExt.erl
This PR fixes problems with ASN.1 modules that define values (as well as, or instead of, types):
- ~~Fix simple value in SEQUENCE OF SEQUENCE~~
- Fix compiling value of SEQUENCE OF CHOICE with extensions
- Fix compiling value of CHOICE with extensions
- Fix for DEFAULT used with OCTET STRING
> ASN.1: fix various problems with value definitions

- lib/crypto/c_src/atoms.c
- lib/crypto/c_src/atoms.h
- lib/crypto/c_src/cipher.c
- lib/crypto/src/crypto.erl
- lib/crypto/test/crypto_SUITE.erl
Fix for https://bugs.erlang.org/browse/ERL-890
I'm not sure about the ASN1 type set to `undefined` for `aes_ige256`. It may have a type defined  in OpenSSL but I'm not sure where to find this information. Though I'm fine with `undefined` for now personally.
I'm also not sure about returning `ige_mode` for the cipher mode.
> Make crypto:cipher_info work for all ciphers and aliases

- erts/emulator/beam/beam_load.c
- erts/emulator/beam/ops.tab
Fix the unsafe load-time optimization introduced in 07bdbb3a1edc.
https://bugs.erlang.org/browse/ERL-899
> Fix unsafe optimization made by the loader

- lib/tools/emacs/erlang-test.el
- lib/tools/emacs/erlang.el
- lib/tools/test/emacs_SUITE.erl
Fetch and present arity in the *xref* window (unless too many hits).
If we are reasonably sure which definition the user wants to go to
then jump there directly instead of popping to the *xref* window.
> Emacs: Refine xref etags matches

- erts/emulator/beam/ops.tab
Measurements show that i_minus instructions (subtraction) are
frequent enough to warrant creating specialized i_minus instructions.
Thanks to José Valim for doing instruction counting on
Elixir code.
> Optimize the i_minus instruction

- erts/emulator/beam/beam_emu.c
- erts/emulator/beam/global.h
- erts/emulator/beam/sys.h
- erts/include/internal/ethr_internal.h
- erts/include/internal/ethread_inline.h
Fabio Coatti reported elixir build failure in https://bugs.gentoo.org/681778.
The minimal reproducer looks like that (from otp git tree):
$ ./configure CFLAGS='-O2 -flto' LDFLAGS='-O2 -flto=8'
$ make
$ ERL_TOP=$PWD \
PATH=$ERL_TOP/bin:$PATH \
\
bin/erl \
\
-noshell -eval 're:replace("a","b","c",[{return,list}]).' \
-s erlang halt
{"init terminating in do_boot",{badarg,[{re,replace,["a","b","c",[{return,list}]],
[{file,"re.erl"},{line,362}]},
{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,680}]},
{init,start_it,1,[]},
{init,start_em,1,[]},
{init,do_boot,3,[]}]}}
init terminating in do_boot ({badarg,[{re,replace,[[_],[_],[_],[_]],[{_},{_}]},
{erl_eval,do_apply,6,[{_},{_}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
Crash dump is being written to: …
> stdlib: fix re:replace on LTO builds

- .gitignore
- erts/emulator/beam/arith_instrs.tab
- erts/emulator/test/Makefile
- erts/emulator/test/small_SUITE.erl
This PR improves the performance of small integer arithmetic by replacing manual overflow checks with compiler intrinsics. Combined with earlier optimizations, small integer performance is now up about 25% compared to OTP 21;
(The bump near April 5th is when this branch was included in our nightly builds, and the perfectly flat sections are when benchmarks didn't run for one reason or another.)
> erts: Optimize arithmetic ops using overflow intrinsics

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
`record_info/2` is a pseudo-function that requires literal arguments
known at compile time. Therefore, the following usage is illegal:
f() -> fun record_info/2.
However, `erl_lint` did not issue a compilation error for this usage,
and the compiler would crash in a later pass.
https://bugs.erlang.org/browse/ERL-907
> Issue an error for improper use of record_info/2 in a fun

- lib/os_mon/src/cpu_sup.erl
Since `dummy_result/1` returns integers (i.e. `0`) not floats, `util/0,1` specs should account for that.
> Fix specs and type definitions in cpu_sup

- lib/public_key/doc/src/public_key.xml
Added actual usage of `pem_decode` to doc example.
> `public_key:pem_decode` example wasn't using `pem_decode`

- lib/kernel/doc/src/gen_tcp.xml
Taken almost verbatim from @RaimoNiskanen's comment from [10 years ago](http://erlang.2086793.n4.nabble.com/strange-behaviour-of-gen-tcp-connect-tp2113918p2113920.html).
> Add a note about timeouts on gen_tcp:connect/3,4

- erts/doc/src/erl.xml
- lib/kernel/src/user_drv.erl
The -name option already computes a default
hostname if none is given. This PR adds the
same behaviour to -remsh. Now we can run:
erl -name foo -remsh bar
erl -sname foo -remsh bar
This simplifies deployment scripts as otherwise
they have to compute the hostname by hand or
start an Erlang VM instance only to do so.
> Add hostname to -remsh if none is given

- erts/preloaded/src/erlang.erl
The spawn_executable option in open_port supports
binaries so we update its typespec accordingly.
> Use file:name_all() on spawn_executable

- lib/compiler/src/beam_ssa_dead.erl
- lib/compiler/test/beam_ssa_SUITE.erl
- lib/compiler/test/guard_SUITE.erl
The `beam_ssa_dead` pass is supposed to eliminate tests that are
determined to be redundant based on the outcome of a previous test.
For example, in the following example that repeats a guard test,
the second clause can never be executed:
foo(A) when A >= 42 -> one;
foo(A) when A >= 42 -> two;
foo(_) -> three.
`beam_ssa_dead` should have eliminated the second clause, but
didn't:
{test,is_ge,{f,5},[{x,0},{integer,42}]}.
{move,{atom,one},{x,0}}.
return.
{label,5}.
{test,is_ge,{f,6},[{x,0},{integer,42}]}.
{move,{atom,two},{x,0}}.
return.
{label,6}.
{move,{atom,three},{x,0}}.
return.
Correct the optimization of four different combinations of relational
operations that were too conservative. To ensure the correctness of the
optimization, also add an exhaustive test of all combinations of …
> Improve optimization of redundant tests

- lib/compiler/src/v3_core.erl
- lib/compiler/test/fun_SUITE.erl
Code such as the following would crash the compiler in OTP 22:
[some_atom = fun some_function/1]
The reason is that the fun would be copied (used both in the match
operation and as a value in the list), and the copy of the fun would
create two wrapper functions with the same name for calling
some_function/1. In OTP 21, the duplicate functions happened not to
cause any harm (one of the wrappers functions would be unused and
ultimately be removed by beam_clean). In OTP 22, the new beam_ssa_type
pass would be confused by the multiple definitions of the wrapper
function.
> Fix compiler crash when funs were matched

- lib/stdlib/doc/src/binary.xml
Proposed documentation fix for
https://bugs.erlang.org/browse/ERL-914
> Improve example for binary:referenced_byte_size/1

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/receive_SUITE.erl
Certain complex receive statements would result in an internal
compiler failure. That would happen when the compiler would fail
to find the common exit block following a receive. See the added
test case for an example.
https://bugs.erlang.org/browse/ERL-950
> Eliminate compiler crash when compiling complex receive statements

- erts/emulator/nifs/common/prim_file_nif.c
- erts/emulator/nifs/common/prim_file_nif.h
- erts/emulator/nifs/unix/unix_prim_file.c
- erts/emulator/nifs/win32/win_prim_file.c
- lib/kernel/doc/src/file.xml
- lib/kernel/src/file.erl
- lib/kernel/test/file_SUITE.erl
This is useful mainly to ensure that a new file has been persisted to disk by calling file:sync/1 or file:datasync/1 on file's parent directory.
Note: I haven't been able to test on Windows, though I believe the changes are correct according to the [docs for CreateFileW](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilew).
> file: allow open/2 to work on directories

- erts/lib_src/common/ethr_aux.c
As Hygon Dhyana(Family 18h) share similar arch with AMD Family 17h,
add Hygon Dhyana support  to enable cmpxchg and sse2 support for erlang
> add Hygon Dhyana support to enable cmpxchg and sse2 support.

- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/sys_core_fold.erl
This pull request simplifies the `sys_core_fold` pass by moving a few optimizations that `beam_ssa_type` didn't do to `beam_ssa_type`, but some optimizations will also be more effective because `beam_ssa_type` has better type information.
> Move type-based optimizations from Core Erlang passes to SSA passes

- erts/emulator/beam/bif.c
- erts/emulator/beam/erl_alloc.types
- erts/emulator/beam/erl_utils.h
- erts/emulator/beam/sys.h
- erts/emulator/beam/utils.c
- erts/emulator/test/Makefile
- erts/emulator/test/emulator.spec
- erts/emulator/test/emulator_bench.spec
- erts/emulator/test/hash_SUITE.erl
- erts/emulator/test/hash_property_test_SUITE.erl
- erts/emulator/test/property_test/phash2_properties.erl
The erlang:phash2 functions did not yield even if the input was very
large and a call to one of the functions did only consume a single
reduction. This commit fixes these problems.
> Make erlang:phash2/1 and erlang:phash2/2 yield

- lib/compiler/src/beam_except.erl
- lib/compiler/test/beam_except_SUITE.erl
The compiler would crash in `beam_except` while compiling this
function:
bar(Req) ->
ok = case Req of
"POST" -> {error, <<"BAD METHOD ", Req/binary>>, Req};
_ -> ok
end.
https://bugs.erlang.org/browse/ERL-954
> Fix compiler crash in beam_except

- lib/compiler/src/beam_ssa_dead.erl
- lib/compiler/test/guard_SUITE.erl
A repeated test could be optimized away. Example:
bar(A) ->
if is_bitstring(A) ->
if is_binary(A) ->
binary;
true ->
bitstring
end;
true ->
other
end.
In the example, the `is_binary/1` test would be optimized away,
basically turning the example into:
bar(A) ->
if is_bitstring(A) ->
bitstring;
true ->
other
end.
Thanks user Marcus Kruse in the Elixir forum for noticing this bug.
> Fix unsafe optimizations where guard tests could be removed

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/test/core_SUITE.erl
- lib/compiler/test/core_SUITE_data/get_map_element.core
The following Core Erlang code could not be loaded:
'f'/1 = fun (_1) ->
case <_1> of
<~{'foo':='foo'}~> when 'true' ->
_1
end
Loading would fail with the following message:
beam/beam_load.c(2314): Error loading function example:f/1: op i_get_map_element_hash p x a u x:
no specific operation found
https://bugs.erlang.org/browse/ERL-955
> Fix loading of Core Erlang code for extracting a map element

- erts/emulator/beam/bif.c
- erts/emulator/beam/dist.c
- erts/emulator/beam/erl_bif_trace.c
- erts/emulator/beam/erl_message.c
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process.h
- erts/emulator/beam/erl_trace.c
- erts/emulator/beam/erl_trace.h
- lib/kernel/doc/src/seq_trace.xml
- lib/kernel/src/seq_trace.erl
- lib/kernel/test/seq_trace_SUITE.erl
- lib/observer/test/ttb_SUITE.erl
Trace tokens can be lost when a process delegates message sending to a child process, which can be pretty surprising and limits the usefulness of seq tracing. One example of this is `gen_statem:call/4` which uses a child process to implement timeouts without the risk of a late reply arriving to the caller.
This PR attempts to fix this by propagating the trace token to spawned processes, and adds optional tracing for process spawning as well.
https://bugs.erlang.org/browse/ERL-700
> Propagate seq_trace tokens to spawned processes

- erts/emulator/beam/erl_sched_spec_pre_alloc.h
Without this I wasn't able to compile the debug emulator, the compilation
would fail with "section attribute is specified on redeclared variable" errors.
> Add missing attribute to debug variable

- erts/configure.in
In https://bugs.gentoo.org/686786 gcc-9.1.0 exposed
a bug in erts/configure: if compiler does not support
PGO flags the configure process calls 'yes = yes'
(indefinite loop) instead of 'test yes = yes'.
The change does not fix gcc-9.1.0 PGO detection but
fixes ./configure termination.
Reported-by: Dennis Schridde
Bug: https://bugs.gentoo.org/686786
> erts: don't loop indefinitely on --enable-pgo

- lib/ssl/src/ssl_connection.erl
- lib/ssl/test/ssl_test_lib.erl
Internal data was accidental leaked by refactorization. Fix the return value to be as documented.
> ssl: Fix broken return value

- lib/kernel/src/logger_std_h.erl
- lib/kernel/test/logger_std_h_SUITE.erl
If the log file name was given as a relative path, logger_std_h
erroneously tried to create a new file in a new location if the
current working directory of the node was changed. This is now
corrected.
> Store file name as absolute path in logger_std_h

- lib/ssl/src/ssl.erl
After upgrading to OTP 22 from OTP 21 the DTLS server would throw this error (I removed the unnecessary parts of the stack trace, and we are operating from Elixir just as a heads up):
```
22:49:50.135 [error] GenServer #PID<0.1720.0> terminating
** (FunctionClauseError) no function clause matching in :dtls_packet_demux.handle_info/2
(ssl) dtls_packet_demux.erl:150: :dtls_packet_demux.handle_info({:udp_passive, #Port<0.248>}, 
(stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
(stdlib) gen_server.erl:711: :gen_server.handle_msg/6
(stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:udp_passive, #Port<0.248>}
State: {:state, 100, 41230, #Port<0.248>, {:gen_udp, :udp, :udp_close, :udp_error, :udppassive}, ... }
```
After looking at: [dtls_packet_demux - …
> Fix SSL cb_info missing underscore in default

- lib/erl_docgen/priv/bin/specs_gen.escript
The warning message was using input file, not output file:
Example:
could not write file '../src/alarm_handler.erl': no such file or directory
Which is the input file, the correct message is:
could not write file '../specs/alarm_handler.specs': no such file or directory
> [trivial] specs_gen script fix error message

- lib/wx/c_src/wxe_driver.c
Looks like I accidentally deleted my last PR. Anyways, driver_realloc works just like regular realloc and expects the caller to match pointers to the allocation with the return value, otherwise undefined behaviour ensues.
> Fix wxe_driver improper realloc call

- lib/kernel/src/erts_debug.erl
The code contains a call to the erts_debug:get_internal_state/1 BIF with
an atom that is not specified in the allowed arguments of this BIF.
> Add lc_graph in the allowed arguments of get_internal_state/1

- lib/dialyzer/doc/src/dialyzer.xml
- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_cl.erl
- lib/dialyzer/src/dialyzer_cl_parse.erl
- lib/dialyzer/src/dialyzer_options.erl
Invoking Dialyzer through the function dialyzer:run/1 instead of from
the command line activates "Erlang mode", meaning that warnings are
returned instead of printed, and that HiPE compilation of modules does
not take place.  With this change, HiPE compilation can optionally be
enabled in this situation by passing the option {native, true}.
Caching of natively compiled modules is enabled by default, but can be
turned off using the option {native_cache, false}.
> Allow native compilation when calling Dialyzer from Erlang

- lib/inets/src/http_server/httpd_request.erl
- lib/inets/test/http_format_SUITE.erl
RFC2616 section 19.3 specifies that LF only can be used as terminator.
The line terminator for message-header fields is the sequence CRLF.
However, we recommend that applications, when parsing such headers,
recognize a single LF as a line terminator and ignore the leading CR.
httpd_request:parse_headers(...) only partly honored this.
The parse_headers function clause matching two LF as end of headers did not allow any previously parsed headers.
> inets: httpd_request - honor RFC2616 LF only as header line terminator

- erts/emulator/drivers/common/inet_drv.c
- lib/kernel/test/gen_tcp_misc_SUITE.erl
When a close is detected on windows, we need to keep track of it as it will not trigger again.
Reported in: https://bugs.erlang.org/browse/ERL-960
> Fix {active,N} close race condition on windows

- erts/doc/src/alt_dist.xml
See https://github.com/erlang/otp/pull/2259#issuecomment-498305226 
I resorted to `amount of data` because that doesn't put too much intent on what the function should do compared to what `dist_util` uses this value for, so that the patch I sent at https://github.com/erlang/otp/pull/2270 is still in line with the documentation.
> alt_dist docs: Correct the mf_getstat description

- erts/emulator/beam/dist.c
- erts/preloaded/src/erlang.erl
Only the dist_util code is using this function and it already
is compatible with a non-boolean value.
We are interested in using this value as a metric to know
how large the distribution output queue is when we encounter
distribution-related issues.
/cc @gerhard
> Return real pend value in erlang:dist_get_stat/1

- erts/aclocal.m4
- erts/configure.in
- erts/emulator/beam/sys.h
- erts/emulator/beam/utils.c
- erts/emulator/nifs/common/socket_nif.c
- erts/emulator/sys/unix/erl_child_setup.c
- erts/emulator/sys/unix/sys.c
- erts/etc/unix/run_erl.c
- lib/erl_interface/include/ei.h
- lib/erl_interface/src/connect/ei_resolve.c
- lib/erl_interface/src/misc/ei_portio.c
This gets OTP building on AIX and able to run readymade Elixir builds; support was present, but subtly broken. I plan to check if some other stuff works (RabbitMQ and Pleroma make good real-world applications on my radar.) but this is a surprisingly far start for little work.
Points ranging from what I do on my environment to non-specific AIX-specific tweaks:
* I fixed the AIX checks in the configure script to work for modern AIX, and work on PASE. (I haven't tested this, but it's next on my agenda.)
* 32-bit build seems broken; it causes the assembler to throw up. Not sure why; you can set a 64-bit build with `OBJECT_MODE=64 CC="gcc -maix64"` during configure (because GCC doesn't respect the magic environment variable AIX uses for bitness of toolchain, grr) and `OBJECT_MODE=64` during …
> Wake AIX up from coma

- erts/emulator/beam/dist.c
- erts/emulator/beam/erl_message.c
- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/external.c
- erts/emulator/beam/external.h
* Move the copy of fragmented payload to the receiving process in order for the copying of multiple messages to be done in parallel.
* Don't copy large binary data when doing decode of an external term from the distribution.
> Optimize dist data shuffling

- lib/crypto/c_src/Makefile.in
The refactoring of the crypto library seems to have broken the static build of the crypto nifs. This PR fixes the issue.
> crypto: Fix the build of static crypto nifs

- lib/ssh/src/ssh.hrl
While working on the `ssh` application I noticed one record and one macro definition that apparently are not used anywhere in the codebase.
Should this be based on top of the `master` or the `maint` branch?
Just let me know and I can rebase if needed and update the PR to point to the correct one 🙂 
Cheers
> Remove unused SSH definitions

- lib/stdlib/src/ordsets.erl
`ordsets:union/1` is not especially efficient when calculating the
union of many ordsets. Rewrite it to use the highly optimized
`lists:umerge/1`.
> Optimize ordsets:union/1

- lib/kernel/src/inet.erl
Before:
```erlang
1> gen_udp:open(0, [local, {ip, {local, "unixdomainfile"}}]).
{ok,#Port<0.6>}
2> inet:i().
in function  integer_to_list/1
called as integer_to_list(<<"unixdomainfile">>)
in call from inet:fmt_port/2 (inet.erl, line 1646)
in call from inet:fmt_addr/2 (inet.erl, line 1642)
in call from inet:'-i_line/3-lc$^0/1-0-'/3 (inet.erl, line 1547)
in call from inet:'-i_line/3-lc$^0/1-0-'/3 (inet.erl, line 1547)
in call from inet:'-info_lines/3-lc$^0/1-0-'/3 (inet.erl, line 1546)
in call from inet:ii/3 (inet.erl, line 1531)
in call from inet:i/0 (inet.erl, line 1515)
```
After:
```erlang
2> inet:i().
Port Module    Recv Sent Owner      Local Address           Foreign Address State Type
4160 local_udp 0    0    <0.1747.0> local:unixdomainfile    *:* …
```
> Support local sockets with inet:i/0

- lib/inets/test/httpc_SUITE.erl
[https://bugs.erlang.org/browse/ERL-989](https://bugs.erlang.org/browse/ERL-989)
> ERL-989: Fix typo in httpc_SUITE:content_length/1

- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_kernel_to_ssa.erl
- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa.hrl
- lib/compiler/src/beam_ssa_bsm.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_ssa_share.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/src/beam_types.hrl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_types_SUITE.erl
- lib/compiler/test/beam_validator_SUITE.erl
- lib/compiler/test/property_test/beam_types_prop.erl
While reasonably effective, our current type representation doesn't allow us to express union types such as `atom() | integer()`; they're reduced to their lowest upper bound which turns out to be `term()` more often than not. This is especially annoying for functions following the `{ok, Value} | {error, Reason}` idiom, as they will be flattened down to `{ok | error, term()}` making it next to impossible to propagate types on the happy path.
This PR solves that problem by introducing union types, letting us express types like `{ok, Value} | {error, Reason}` directly, and adds a few minor optimizations to take better advantage of them.
Having better type information uncovered a bunch of crashes when optimizing unreachable code, necessitating the removal of impossible branches (ec35aa9), …
> Extend the compiler's type representation

- lib/crypto/c_src/atoms.c
- lib/crypto/c_src/atoms.h
- lib/crypto/c_src/crypto.c
- lib/crypto/c_src/evp.c
- lib/crypto/src/crypto.erl
- lib/crypto/test/crypto_SUITE.erl
This pull request adds `ed25519` & `ed448` curve support to `crypto:generate_key/2` & `/3`.
It adds them under the `eddsa` Type:
```erlang
1> {Pub, Priv} = crypto:generate_key(eddsa, ed25519).
{<<1,...>>, <<2,...>>}
2> {Pub, Priv} = crypto:generate_key(eddsa, ed25519, Priv).
{<<1,...>>, <<2,...>>}
```
It also fixes a [bug](https://bugs.erlang.org/browse/ERL-1008) where `x25519` key generation fails for `crypto:generate_key/3`:
```erlang
1> {Pub, Priv} = crypto:generate_key(ecdh, x25519).
{<<3,...>>, <<4,...>>}
2> {Pub, Priv} = crypto:generate_key(ecdh, x25519, Priv).
{<<3,...>>, <<4,...>>}
```
> Add ed25519 & ed448 support to crypto:generate_key

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/compile.erl
- lib/compiler/test/Makefile
- lib/compiler/test/test_lib.erl
If the `no_type_opt` option was given, the compiler would crash when
attempting to compile containing with a `try`...`after` construct,
such as this code:
foo() ->
try
make_ref()
after
ok
end.
To avoid having this bug re-appear, test the `no_type_opt` option
in the test suites.
> Fix compiler crash when compiling with +no_type_opt

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_ssa_SUITE.erl
When matching a map, the compiler could fail to generate code that
would initialize all stack slots (Y registers) properly. Here is a
general outline of code that *could* cause this problem:
foo(Key, Map) ->
Res = case Map of
#{Key := Val} ->
%% Do something with Val here.
.
.
.
#{} ->
[]
end,
%% The stack slot for Val might not have been initialized
%% here if the key was not present in the map.
.
.
.
%% Use Res.
.
.
.
The code generator would wrongly assume that the map matching would
always initialize the stack slot, and if nothing else happened to
force that stack slot to be initialized, it would remain
uninitialized, which would likely crash the runtime system at the next
garbage collection.
`beam_validator` is supposed to find these kind of problems, but a bug
in `beam_validator` …
> Ensure that the stack slots are initialized when matching maps

- erts/lib_src/pthread/ethread.c
Ask compiler to generate unique label name. Using named label has implications
on optimizer, that may lead to the compilation errors as the following:
pthread/ethread.c: Assembler messages:
pthread/ethread.c:213: Error: symbol `no_cpuid' is already defined
pthread/ethread.c:213: Error: symbol `no_cpuid' is already defined
pthread/ethread.c:213: Error: symbol `no_cpuid' is already defined
Please, note, that I faced this build issue in a wild when tried to build Erlang for i686 platform using gcc 9.1.0 with LTO enabled. I suppose that LTO decided to inline function ethr_x86_cpuid__() in the other compilation unit.
> erts: Do not use named no_cpuid label in asm

- lib/kernel/doc/src/logger_disk_log_h.xml
Fix syntax error in logger_disk_log_h.xml
```erl
logger:add_handler(my_disk_log_h, logger_disk_log_h,
#{config => #{file => "./my_disk_log",
type => wrap,
max_no_files => 4,
max_no_bytes => 10000},
filesync_repeat_interval => 1000}}).
```
should be
```erl
logger:add_handler(my_disk_log_h, logger_disk_log_h,
#{config => #{file => "./my_disk_log",
type => wrap,
max_no_files => 4,
max_no_bytes => 10000,
filesync_repeat_interval => 1000}}).
```
> Fix syntax error in logger_disk_log_h.xml

- lib/os_mon/c_src/cpu_sup.c
For instance, musl does not recognize the %L modifier.
See https://bugs.erlang.org/browse/ERL-1012
> Fix sscanf to use %llu instead of gnu specific %Lu

- erts/emulator/beam/erl_printf_term.c
- erts/emulator/test/fun_SUITE.erl
This PR fixes a bug where funs like `fun 'escaped-mod':'escaped-fun'/1` would be erroneously printed as `"fun escaped-mod:escaped-fun/1"`
https://bugs.erlang.org/browse/ERL-1009
> Escape module/function names in erlang:fun_to_list/1

- lib/mnesia/src/mnesia_controller.erl
- lib/mnesia/src/mnesia_schema.erl
- lib/mnesia/test/mnesia_isolation_test.erl
If add_table_copy was called when a node was starting it could deadlock
waiting for mnesia_controller, when schema was not merged.
Abort if that is the case.
> mnesia: Fix deadlock caused by add_table_copy

- lib/observer/src/cdv_html_wx.erl
When looking at an "expanded term" in Observer, such as the state term
of a supervisor process, all pids are turned into clickable links.
However, without this change, you could only follow one such link; any
further clicks would be ignored.  Fix that by ensuring that the
cdv_html_wx process holds on to its state.
> Handle clicking links more than once in Observer's "Expanded term"

- lib/mnesia/doc/src/Mnesia_chap7.xmlsrc
I see in OTP 20 & 21 in the eshell:
```erl
Eshell V10.0  (abort with ^G)
1> mnesia:system_info(dump_log_write_threshold).
1000
```
But the documentation says that the default log wirte threshold is 100.
Looks like a missing `0`!
> Correct documentation on dump_log_write_threshold default value

- erts/doc/src/erlang.xml
This function is allowed to be used in guards.
> Fix documentation for erlang:is_map_key/2

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/receive_SUITE.erl
The compiler would crash when compiling the following code:
do(Acc) ->
receive
{Pid, abc} ->
ok;
{Pid, []} ->
ok;
{Pid, _Res} ->
exit(_Res)
end,
do([Pid | Acc]).
The last clause that always raises an exception would confuse the
compiler so that it would think that the `receive` statement was at the
end of the function and it would generate incorrect code for the `do/1`
call following the `receive`.
https://bugs.erlang.org/browse/ERL-1022
> Fix compiler crash when compiling some receive statements

- lib/kernel/doc/src/file.xml
The documentation states that file:open/2 is linked to
the owner process but that's not true. A monitor is used
instead (it has been so for a while).
> Document file:open/2 monitors the owner process

- lib/stdlib/src/ms_transform.erl
- lib/stdlib/test/ms_transform_SUITE.erl
Code such as `ets:fun2ms(fun({"foo" ++ X}) -> X end)` works fine in
compiled code.  Let's make it work when fun2ms is invoked from the
shell as well.
> fun2ms: accept ++ in function head when called from shell

- lib/eunit/src/eunit_surefire.erl
- lib/eunit/test/Makefile
- lib/eunit/test/eunit_SUITE.erl
- lib/eunit/test/tc0.erl
Without this, test cases which output control codes, or with names or
descriptions containing control codes, would cause the generated XML files to be
invalid.
> ERL-991 Strip control codes from eunit_surefire output

- lib/kernel/src/logger_std_h.erl
Fix file descriptor leak in logger when logrotate used for log management. This bug also exists in maint-22 and master branches.
> Close log files properly in case of inode change

- lib/edoc/src/edoc.app.src
- lib/edoc/src/edoc.erl
- lib/edoc/src/edoc_lib.erl
The feature that depended on inets was not used
in practice since Edoc automatically includes all
references to projects in your code path. Plus
you can always link to an external document
directly.
Finally, as we move towards EEP 48, we will likely
rely more on the chunk information rather than
precompiled edoc-info.
/cc @richcarl
> Remove inets dependency from edoc

- erts/emulator/beam/beam_bif_load.c
- erts/emulator/beam/beam_bp.c
- erts/emulator/beam/beam_emu.c
- erts/emulator/beam/bif.c
- erts/emulator/beam/bif_instrs.tab
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_db_util.c
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/erl_nfunc_sched.c
- erts/emulator/beam/erl_nfunc_sched.h
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process.h
- erts/emulator/beam/erl_trace.h
- erts/emulator/beam/instrs.tab
- erts/emulator/beam/macros.tab
- erts/emulator/beam/ops.tab
- erts/emulator/beam/trace_instrs.tab
- erts/emulator/hipe/hipe_debug.c
- erts/emulator/hipe/hipe_instrs.tab
- erts/emulator/hipe/hipe_mode_switch.c
- erts/emulator/test/bif_SUITE.erl
- erts/emulator/test/hibernate_SUITE.erl
- erts/etc/unix/etp-commands.in
The BEAM instructions for calling a function don't save the
continuation pointer (return address) on the stack, but to a special
BEAM register called CP. It is the responsibility of the called
function to save CP to the stack frame before calling other functions.
In the earlier implementations of BEAM on Sparc, CP was located in a
CPU register. That meant that the continuation pointer was never
written to memory when calling simple functions that didn't call
other functions at all or ended in a tail-call to another function.
The modern BEAM no longer keeps CP in CPU register. Instead, it is
kept in the `process` struct (in `p->cp`). That means the continuation
pointer must be written to the memory on every call, and if the called
function will call other functions, it will must read the …
> Optimize continuation pointer management

- lib/kernel/src/logger.erl
- lib/kernel/src/logger_internal.hrl
- lib/kernel/test/logger_SUITE.erl
SASL won;'t boot when it compares log level (when one is all); it seems like a mistake as all is a valid log level as defined by the all levels macro. 
**Example:**
```
logger:compare_levels(info,all). 
in function  logger:compare_levels/2
called as logger:compare_levels(info,all)
```
Example of SASL not starting. 
```=INFO REPORT==== 25-Jun-2019::10:53:19.643029 ===
application: sasl
exited: {bad_return,
{{sasl,start,[normal,[]]},
{'EXIT',
{badarg,
[{logger,compare_levels,
[info,all],
[{file,"logger.erl"},{line,614}]},
{sasl,allow_progress,0,
[{file,"sasl.erl"},{line,171}]},
{sasl,add_error_logger_mf,1,
[{file,"sasl.erl"},{line,158}]},
{sasl,start,2,[{file,"sasl.erl"},{line,40}]},
{application_master,start_it_old,4,
[{file,"application_master.erl"}, …
```
> Start up of SASl when compared log level is all

- erts/emulator/beam/erl_bif_port.c
- erts/emulator/beam/erl_fun.c
- erts/emulator/beam/export.c
- erts/emulator/beam/hash.c
- erts/emulator/beam/hash.h
- erts/emulator/beam/index.c
- erts/emulator/beam/register.c
- erts/emulator/beam/register.h
- erts/emulator/beam/sys.h
- erts/emulator/sys/common/erl_osenv.h
- erts/emulator/sys/unix/erl_child_setup.c
- erts/emulator/sys/unix/sys_drivers.c
- erts/emulator/sys/win32/sys.c
- erts/emulator/sys/win32/sys_env.c
This PR updates the internal hash table implementation to use a Fibonacci hash.
The internal hash is used for things like; the process registry, executing `erlang:apply/2`, executing `M:func(test).` and more.
The old implementation used `hashvalue % size` to map the values and made sure that the `size` was always a prime number so that even if the hash value provided used a bad hash function, it would give a somewhat good spread in the hash. However, the problem with this approach is that `%` is a relatively expensive operation and has been seen to pop up when running linux perf on production systems.
The new implementation instead uses a constant derived from the golden ratio to make the mapping function better without needing the `size` of the hash table to be a prime. So instead we can …
> Change internal hash table implementation

- lib/kernel/src/net_kernel.erl
We've got a few similar stacktraces once. See the following one for
example:
** Reason for termination ==
** {badarg,
[{ets,next,[sys_dist,'rabbitmq-cli-42@host.example.com'],[]},
{net_kernel,get_nodes,2,[{file,"net_kernel.erl"},{line,1025}]},
{net_kernel,get_nodes,2,[{file,"net_kernel.erl"},{line,1019}]},
{net_kernel,get_nodes_info,0,[{file,"net_kernel.erl"},{line,1439}]},
{rabbit_mgmt_external_stats,cluster_links,0,
[{file,"src/rabbit_mgmt_external_stats.erl"},{line,252}]},
{rabbit_mgmt_external_stats,emit_node_node_stats,1,
[{file,"src/rabbit_mgmt_external_stats.erl"},{line,366}]},
{rabbit_mgmt_external_stats,handle_info,2,
[{file,"src/rabbit_mgmt_external_stats.erl"},{line,347}]},
{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]}]}
The problem is that when we're trying …
> Nodes info improvements

- lib/kernel/examples/gen_tcp_dist/src/gen_tcp_dist.erl
Here are small changes to fix/improve the documentation of gen_tcp_dist. Thanks
> kernel: Fix typo in gen_tcp_dist documentation

- lib/common_test/src/ct_property_test.erl
In cases the user does not want ct_property_test to compile properties init_tool/1 can be used to set the property_test_tool config value.
---
Another option would be to have an argument of options to `init_per_suite`, so `init_per_suite/2`, to tell it not to compile.
> ct_property_test: add init_tool/1

- lib/stdlib/doc/src/ets.xml
Since OTP 20.0 it's not guaranteed term_to_binary will break
a compiled match spec.
> Correct ETS documentation about compiled match specs

- erts/configure.in
- erts/emulator/hipe/hipe_x86_signal.c
From https://git.alpinelinux.org/aports/tree/community/erlang 
Without it the build fails on alpine 3.10. I can't really explain it beyond that at this time and do not know if it is a proper long term fix.
> fix build on alpine 3.10 musl libc 1.1.22

- lib/kernel/doc/src/inet.xml
This is the same value as `erlang:port_info(Port, queue_size)` as noted in https://bugs.erlang.org/browse/ERL-930 however that fact should probably not be documented if we are moving toward a non-port socket implementation, I suppose.
> inet: Remove non-existing send_dvi; document send_pend

- lib/runtime_tools/src/dbg.erl
- lib/runtime_tools/test/dbg_SUITE.erl
dbg:stop_clear should clear trace pattern events.
Also make sure that the dbg_SUITE cleans up after itself so that it does not interfere with the lttng suite coming next.
> Fix dbg:stop_clear to remove trace events as well

- lib/mnesia/src/mnesia.erl
According to the docs and other `{aborted, _}` return values, the form should be `{aborted, Reason}`, where `Reason` is a single term.
This fix makes `mnesia:create_table/2` consistent with that expectation.
For instance, `mnesia:error_description` would work with this change:
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Eshell V10.4.4  (abort with ^G)
1> mnesia:error_description(badarg).
"Bad or invalid argument, possibly bad type"
2> mnesia:error_description({aborted,badarg,foo,bag}).
{aborted,badarg,foo,bag}
3> mnesia:error_description({aborted,{badarg,foo,bag}}).
{"Bad or invalid argument, possibly bad type",foo,bag}
```
> Ensure create_table aborted reason is expected format

- erts/emulator/nifs/unix/unix_prim_file.c
- lib/kernel/test/file_SUITE.erl
https://bugs.erlang.org/browse/ERL-1042
> Fix efile_allocate for Mac

- lib/stdlib/doc/src/erl_tar.xml
- lib/stdlib/src/erl_tar.erl
The first argument for `create/3` and `create/4` can be either a `string()` or `binary()` but the typespec says `file:filename()` which is only `string()`. This switches it to `file:filename_all()`.
I noticed `erl_tar` also defines `filename()`, but in most places it uses `file:filename()`. Maybe we can make it more consistent by changing the definition to `-type filename() :: file:filename().` and using it everywhere? And also defining `filename_all()` with `-type filename_all() :: file:filename_all().`
Finally the documentation page doesn't define what `filename()` is, which took me a while to figure out. Some pages, like `ets`, define data types early on. That might be useful here too. Maybe a different PR?
> erl_tar: Fix typespec for create

- lib/compiler/src/beam_kernel_to_ssa.erl
- lib/compiler/src/cerl_sets.erl
- lib/compiler/src/v3_core.erl
- lib/compiler/src/v3_kernel.erl
- lib/compiler/src/v3_kernel.hrl
- lib/compiler/src/v3_kernel_pp.erl
The main purpose of this pull request it to clean up and simplify the `v3_kernel` pass. Details are described in the individual commit messages.
A few inefficiencies were fixed along the way. For example, when compiling a version of elixir's `String.Unicode` module, the time for running the `v3_kernel` pass was reduced from about 1.5 seconds down to less than a second on my computer.
> Clean up and simplify the v3_kernel compiler pass

- lib/stdlib/doc/src/proplists.xml
- lib/stdlib/src/proplists.erl
- lib/stdlib/test/Makefile
- lib/stdlib/test/proplists_SUITE.erl
According to the documentation, the following call:
proplists:substitute_negations([{no_foo, foo}], [{no_foo, false}]).
should return `[{foo, true}]`. The actual return value is `[foo]`.
The implementation of `proplists:substitute_negations/2` calls
`proplists:property/2` to reduce the substituted items to their
minimal representation. That seems to be the intention of the
author and it makes sense.
Therefore, the documentation should be corrected.
While at it, add a minimal `proplists_SUITE` that tests all examples
in the documentation.
> Correct the documentation for proplists:substitute_negations/2

- erts/doc/src/erl_nif.xml
It's `ErlNifIOVec` not `ErlNifIOvec`.
> Fix enif_free_iovec documentation

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
The `beam_ssa_opt` pass could do an unsafe optimization for code that
looked like code in a guard. Correct it by verifying potentially unset
variables more thoroughly.
https://bugs.erlang.org/browse/ERL-1054
> Correct an internal compiler error

- erts/emulator/beam/atom.names
- erts/emulator/beam/erl_alloc.types
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_db_hash.c
- erts/emulator/beam/erl_db_hash.h
- erts/emulator/beam/erl_db_tree.c
- erts/emulator/beam/erl_db_util.h
- erts/emulator/beam/erl_flxctr.c
- erts/emulator/beam/erl_flxctr.h
- erts/emulator/beam/erl_process.h
- lib/stdlib/doc/src/ets.xml
- lib/stdlib/src/ets.erl
- lib/stdlib/test/ets_SUITE.erl
This pull request contains two commits. The first commit (ad2ce60) adds support for using decentralized counters to count the number of items and the memory consumption in the ETS table types that are implemented with hashing (`set`, `bag` and `duplicate_bag`). All tables with the `write_concurrency` option activated use decentralized counters by default after this commit has been applied. The second commit (efe06e4) in this pull request adds an ETS table option that can be used to turn off decentralized counters in tables. Such an option can be useful in applications that frequently call `ets:info(T)`, `ets:info(T,size)` or `ets:info(T,memory)` because such calls are substantially slower with decentralized counters compared to with centralized counters.
[This pull request has been …
> Decentralized counters for all ETS table types and an option to disable decentralized counters

- lib/kernel/src/logger.erl
- lib/kernel/src/logger_config.erl
- lib/kernel/src/logger_olp.erl
- lib/kernel/src/logger_olp.hrl
- lib/kernel/src/logger_server.erl
- lib/kernel/src/logger_std_h.erl
- lib/kernel/test/logger_SUITE.erl
Move the primary and module-level checks into `persistent_term`.
I would also like to move the handler level checks (and possibly config) into `persistent_term`, but that is not done yet.
Also did some other small improvements/bug-fixes.
> Change logger to use persistent_term for level checks

- erts/emulator/beam/erl_bif_re.c
- erts/emulator/beam/global.h
- erts/emulator/beam/utils.c
Fix the bug with failure to build from the source on HP PA-RISC
architecture where stack grows upwards. See
https://bugs.erlang.org/browse/ERL-1043 for details.
> Implement a separate test for stack direction for the re module

- erts/emulator/test/beam_SUITE.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
The compiler would repeat some optimization passes a fixed number of times. For example, the type optimization pass would be run three times on all functions in a module. That could be too much for some functions (wasting compilation time) or too little (missing some possible optimizations).
This commit updates `beam_ssa_opt` to run the repeated passes to a fixpoint. Only functions that could potentially be improved by additional optimizations will be optimized again.
The type optimization pass will be run twice for all functions.
It will then be repeated for functions that would benefit from it because better type information is available or because its code was changed in the previous iteration.
This pull request also adds a commit to limit the depth of the type information to avoid a …
> Repeat optimization passes until a fixpoint is reached

- lib/public_key/src/pubkey_crl.erl
- lib/ssl/src/ssl_crl_cache.erl
- lib/ssl/src/ssl_crl_cache_api.erl
- lib/ssl/src/ssl_crl_hash_dir.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/test/make_certs.erl
- lib/ssl/test/ssl_crl_SUITE.erl
SSL is failing to handle a populated 'cRLIssuer' entry in a CRL distribution point extension in a certificate.
Specifically, ssl_crl_hash_dir:lookup/3 confuses the structure of 'CertIssuer' with 'CRLIssuer' which is potentially a list.
Fix by using the existing pubkey_crl:dp_crlissuer_to_issuer/1 to unwrap the CRLIssuer.
Added test to repro the problem.
> ERL-1030 SSL failing to handle a 'cRLIssuer' entry in a CRL distribution point extension

- erts/emulator/nifs/common/socket_nif.c
- erts/preloaded/src/socket.erl
fix handling some UNIX socket cmsg_type values from erlang code:
* timestamp <-> SCM_TIMESTAMP
* rights <-> SCM_RIGHTS
* credentials <-> SCM_CREDENTIALS or SCM_CREDS
'rigths' type allows passing file descriptors to another process,
which allows passing TCP sockets too, E.g.:
```
% Sender code, FD is an integer file descriptor
Ctrl = [#{level => socket, type => rights, data => <<FD:32/native>>}],
ok = socket:sendmsg(USock, #{iov => [<<"hello">>], ctrl => Ctrl}),
```
```
% Receiver side (other process)
{ok, Msg} = socket:recvmsg(U),
{ctrl := [#{level := socket, type := rights, data := Data}]} = Msg,
<<FD:32/native, Rest/binary>> = Data, % On MacOS Rest contains garbage
```
> socket_nif: improve support for sendmsg ctrl types

- erts/configure.in
The build of Erlang/OTP crashes on macOS Catalina (10.15).
The reason is that the default for stack checks have changed. Stack
checks are now on by default (when the target is macOS 10.15 or
later). They used to be off by default. There seems to be some
pre-existing bug in Clang so that it could generate code that crashes
when stack checks are turned on. If stack checks are turned on when
compiling for macOS 10.14 (Mojave), the build will crash in the same
way.
This commit turns off stack checks when building Erlang/OTP on
macOS Catalina.
Here are some useful links I found while investigating this issue:
https://forums.developer.apple.com/thread/121887
https://code.videolan.org/videolan/libbluray/issues/20
https://bugs.erlang.org/browse/ERL-1063
> Fix failure to build OTP on macOS Catalina (10.15)

- lib/compiler/src/compile.erl
- lib/compiler/test/core_SUITE_data/fun_letrec_effect.core
When compiling directly from Core Erlang code, run the `core_lint`
pass and abort if errors are found in the Core Erlang code.
https://bugs.erlang.org/browse/ERL-1065
> Always run the core_lint pass when compiling from Core Erlang

- erts/preloaded/src/erts.app.src
Some tools rely on the fact that the `modules` section of the .app file contains all modules. For example Elixir's `dialyxir`. Let's add the missing `persistent_term` to `erts.app.src`.
> erts: Fix missing persistent_term from erts.app

- lib/tools/emacs/erlang-eunit.el
- lib/tools/emacs/erlang-flymake.el
- lib/tools/emacs/erlang.el
The Emacs erlang-mode has a feature that lets the user open the documentation for an Erlang/OTP function in an Emacs buffer. This functionality has not worked correctly with recent versions of Emacs and Erlang. The wrong path was searched for man pages, and the Emacs buffer with the man page would often not scroll to the description of the function automatically. This change fixes these issues and makes this functionality more convenient by asking the user if the man pages should be downloaded automatically by Emacs when they can't be found on the system. To try out this functionality, put the cursor over the function name in a call to an Erlang/OTP function (e.g., "io:format("arg")") and type C-c C-d (i.e., Ctrl-key and c-key and then Ctrl-key and d-key). There is also a new menu item …
> Emacs erlang-mode: Improve functionality for displaying an Erlang/OTP function's documenation

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/beam_ssa_SUITE.erl
When compiling a `receive` inside a `try`, `beam_ssa_pre_codegen`
could mistake the landing pad block of the `try` as the common
exit block from the `receive` and fail to find the common variables.
The resulting code would not pass `ssalint`, but might compile
and pass `beam_validator`.
> beam_ssa_pre_codegen: Improve determination of the common exit block

- erts/emulator/beam/beam_bp.c
- erts/emulator/beam/beam_bp.h
- erts/emulator/beam/trace_instrs.tab
- erts/emulator/test/trace_call_time_SUITE.erl
https://bugs.erlang.org/browse/ERL-1027
The active call_time traced function for a process
was not reset correctly when returning from a call_time traced function.
> Fix return from call_time traced function

- erts/emulator/beam/bif.c
- erts/emulator/beam/dist.c
- erts/emulator/beam/dist.h
- lib/kernel/doc/src/seq_trace.xml
- lib/kernel/test/seq_trace_SUITE.erl
Send operation
`{ToName, ToNode} ! Message`
was sequence traced as
`{seq_trace, Label, {send, Serial, From, ToName, Message}}`
and is now traced as
`{seq_trace, Label, {send, Serial, From, {ToName, ToNode}, Message}`
> Fix seq_trace named remote send trace message

- lib/stdlib/src/erl_scan.erl
- lib/stdlib/test/erl_scan_SUITE.erl
- lib/tools/emacs/erlang.el
- system/doc/reference_manual/data_types.xml
Just draft to get some feedback. Can update docs, erlang-mode.el and tests if we are ok to proceed.
This is to make long numeric literals more readable. The idea is [borrowed from Rust language](https://doc.rust-lang.org/rust-by-example/primitives/literals.html) ([rust spec](https://doc.rust-lang.org/reference/tokens.html#numbers))
Examples:
* `123_456_789` vs `123456789`
* `123_456.789_123` vs `123456.789123`
* `16#123_ABC` vs `16#123ABC`
* `2#1100_0011_0101` vs `2#110000110101`
<del>One minor problem with current implementation is that `erl_scan:string("123_456", text)` will return `{integer,[{text,"123456"},<..>],123456}` - so, text will be "123456" and not original "123_456", but this can be fixed, if it's important.</del>
> Allow underscores in numeric literals

- lib/kernel/src/global.erl
- lib/stdlib/doc/src/gen_server.xml
- lib/stdlib/src/gen_server.erl
Related to  [discussion](https://github.com/erlang/otp/pull/2375#issuecomment-539514080) we had about adding type specs to `gen_server`.
> fix: gen_server:reply/2

- lib/stdlib/src/pool.erl
- lib/stdlib/test/Makefile
- lib/stdlib/test/pool_SUITE.erl
If a short running function is spawned with a link it can terminate before the link is done which will cause the link to fail. Instead, we just request a node from the pool and then do the spawn in the calling process using the spawn_link primitive to get an atomic spawn and link operation.
Need to add some tests before merging.
See https://bugs.erlang.org/browse/ERL-1071
Edit: Tests added
> stdlib: Make pool:pspawn_link atomic

- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_bif_persistent.c
- erts/emulator/beam/global.h
- erts/emulator/test/Makefile
- erts/emulator/test/erts_test_destructor.erl
- erts/emulator/test/persistent_term_SUITE.erl
- erts/emulator/test/persistent_term_SUITE_data/Makefile.src
- erts/emulator/test/persistent_term_SUITE_data/erts_test_destructor.c
by avoiding copy the entire hash table if possible and instead write directly into the active table.
This is mostly an optimization wrt CPU and maybe memory fragmentation. The latency of both `put/2` and `erase/1` in a busy VM will still be significant as they have to wait for _thread progress_ before return to guarantee read consistency without expensive memory barriers in `get/1`.
> Optimize persistent_term:put/2 and erase/1

- erts/etc/common/erlexec.c
- erts/test/erlexec_SUITE.erl
Before this fix any double space ('a  b') would be stripped to a single space even if quoted.
> erts: Fix so that quotes are respected in erlexec args files

- lib/compiler/src/beam_a.erl
- lib/compiler/src/beam_ssa_recv.erl
- lib/compiler/test/receive_SUITE.erl
- lib/compiler/test/receive_SUITE_data/ref_opt/no_6.erl
- lib/compiler/test/receive_SUITE_data/ref_opt/yes_15.erl
- lib/compiler/test/receive_SUITE_data/ref_opt/yes_16.erl
Fix a problem where a receive marker would be set even if it
was not guaranteed that execution would reach a receive statement.
This optimization bug caused the problem for the `socket` module
reported here:
http://erlang.org/pipermail/erlang-questions/2019-October/098591.html
https://bugs.erlang.org/browse/ERL-1076
> Fix unsafe optimization of receives

- .gitignore
- HOWTO/INSTALL-ANDROID.md
- xcomp/erl-xcomp-arm64-android.conf
Here is a branch refreshing the Android cross compilation with:
- an updated configuration supporting newer Android NDK toolsets
- corresponding modifications to the documentation, now detailed in a more step-by-step way
These changes have been tested with the current stable Android NDK: 20.0.5594570 on Linux x86_64.
Thanks,
Jérôme
> Update and fix Android cross compilation to support newer Android NDK versions

- erts/emulator/sys/unix/erl_child_setup.c
On systems without closefrom(), such as Linux, iterating over all
possible file descriptors and calling close() for each is inefficient.
This is markedly so when the maximum number of file descriptors has
been tuned to a large number.
Instead, walk the open descriptors under /dev/fd and close only those
which are open.
> erl_child_setup: reduce number of calls to close()

- lib/eunit/doc/overview.edoc
- lib/eunit/include/eunit.hrl
- lib/eunit/src/eunit_proc.erl
- lib/eunit/src/eunit_tests.erl
To be able to test programs or functions producing output on
standard output and to verify this output in an EUnit test
case, a new macro ?capturedOutput is defined in eunit.hrl.
> eunit: Allow test cases to retrieve output captured by EUnit

- lib/stdlib/doc/src/erl_pp.xml
- lib/stdlib/src/erl_pp.erl
- lib/stdlib/test/erl_pp_SUITE.erl
This gives a bit of flexibility and control to the
formatted code. For example, Erlang official docs
uses 3 spaces when indenting types, with this patch
we can reproduce this effect elsewhere.
> Allow linewidth and indent to be given to erl_pp

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/src/v3_core.erl
- lib/compiler/test/warnings_SUITE.erl
When functions can be generated dynamically, we may
have multiple functions defined in the same line, which
makes the shadow clause warning a bit hard to debug.
This patch addresses this by using the a function
annotation, if available, and including that in the
printed message.
> Add function/arity to shadow clauses warnings when possible

- erts/emulator/beam/erl_map.c
- lib/stdlib/test/maps_SUITE.erl
If merging two maps that are precisely the same
in memory, we can avoid the whole merge operation
and simply return the given map.
This can reduce memory allocation and CPU work for
algorithms that may be updating a map and merging
into a previous value. The check is also very cheap,
which means the downsides are minimal.
The commit also adds coverage for a similar behaviour
already implemented for maps:put/3.
> Do not merge maps when the value is the same

- lib/ssh/src/ssh_xfer.erl
To use openssh rename extension it use the same logic as openssh scp client and verify if extension exists and choose that first.
> Add openssh vendor extension to sftp rename.

- lib/inets/src/http_client/httpc.erl
- lib/inets/test/httpc_SUITE.erl
Fixes crashing part of ERL-1083.
> httpc: do not pass error tuple to uri_string:parse/1

- lib/kernel/doc/src/rpc.xml
OTP Technical Board decided that we will not change the
the behavior of `rpc:call/4` and friends in order to
preserve backward compatibility. Since the some of the
details of the return values can be surprising, update
the documentation without detailed description of
the return values.
https://bugs.erlang.org/browse/ERL-1066
> Document the return value details for rpc:call/4 and friends

- erts/emulator/test/process_SUITE.erl
- lib/compiler/src/Makefile
- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_digraph.erl
- lib/compiler/src/beam_jump.erl
- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_opt.hrl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/src/beam_types.hrl
- lib/compiler/src/beam_validator.erl
- lib/compiler/src/compile.erl
- lib/compiler/src/compiler.app.src
- lib/compiler/test/beam_types_SUITE.erl
- lib/compiler/test/beam_validator_SUITE.erl
- lib/compiler/test/match_SUITE.erl
- lib/compiler/test/property_test/beam_types_prop.erl
- lib/stdlib/test/string_SUITE.erl
The cross-function type optimization introduced in PR #2100 removed a lot of redundant type checks, but the implementation was very naive and often lost type information in recursive functions which greatly limited its effectiveness. For example, it couldn't figure out that the following always produced a proper list:
```erlang
foo([A | As]) -> [A | foo(As)];
foo([]) -> [].
```
This PR improves the compiler's understanding of recursive functions and leverages that to keep track of types inside lists, allowing us to remove more type tests in loops.
I'm still waiting for the benchmarks to finish running, but until then [here's an assembly diff](https://github.com/erlang/otp/files/3858858/improved_type_inference_diff.txt) showing the impact this PR has on OTP and parts of Elixir.
> compiler: Improve type inference

- erts/doc/src/alt_dist.xml
- erts/emulator/beam/dist.c
- erts/emulator/beam/dist.h
- erts/emulator/beam/external.c
- lib/kernel/examples/gen_tcp_dist/src/gen_tcp_dist.erl
- lib/kernel/src/dist_util.erl
- lib/kernel/test/erl_distribution_SUITE.erl
Fix the Erlang distribution to handle the scenario when a node connects that can handle message fragmentation but can not handle the atom cache. This bug only affects users that have implemented a custom distribution carrier. It has been present since OTP-21.
This fix will only be merged to master as solving it in maint is not trivial due to other refactorings.
Thanks @essen for reporting
> Fix erl dist with no atom cache

- lib/stdlib/doc/src/uri_string.xml
Must be from a bad copy pasta.
> Fix uri_string:recompose/1 example in docs

- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_db_hash.c
- erts/emulator/beam/erl_db_util.h
- erts/emulator/beam/external.c
- lib/stdlib/test/ets_SUITE.erl
* Remove table locking when using +S 1
* Optimize meta table lock to not be taken when using +S 1
* Optimize dec_term for atoms when used by ets compressed
Together these changes can significantly reduce the CPU usage of applications using only one scheduler.
> ETS Optimizations (for +S 1)

- lib/kernel/src/group.erl
net:call/4 simply redirects to rpc:call/4.
> Remove deprecated call to net:call/4

- lib/kernel/src/application_controller.erl
- lib/kernel/src/error_logger.erl
- lib/kernel/src/logger.erl
- lib/kernel/src/logger_formatter.erl
- lib/kernel/src/logger_handler_watcher.erl
- lib/kernel/test/application_SUITE.erl
- lib/kernel/test/logger_formatter_SUITE.erl
- lib/kernel/test/logger_legacy_SUITE.erl
- lib/sasl/test/sasl_report_SUITE.erl
- lib/stdlib/src/erl_error.erl
- lib/stdlib/src/gen_event.erl
- lib/stdlib/src/gen_fsm.erl
- lib/stdlib/src/gen_server.erl
- lib/stdlib/src/gen_statem.erl
- lib/stdlib/src/proc_lib.erl
- lib/stdlib/src/supervisor.erl
- lib/stdlib/src/supervisor_bridge.erl
- lib/stdlib/test/gen_event_SUITE.erl
- lib/stdlib/test/gen_fsm_SUITE.erl
- lib/stdlib/test/gen_server_SUITE.erl
- lib/stdlib/test/gen_statem_SUITE.erl
- lib/stdlib/test/proc_lib_SUITE.erl
- lib/stdlib/test/supervisor_SUITE.erl
- lib/stdlib/test/supervisor_bridge_SUITE.erl
The `report_cb` used for `gen_server` terminate reports is originally written for multi-line logging. Setting `single_line=>true` in the `logger_formatter` configuration causes newlines to be replaced by ", " and the result of this is not very good for `gen_server` terminate reports.
This pull request changes this `report_cb` to behave differently for multi-line vs single-line logging. See examples:
Multi-line:
```
=ERROR REPORT==== 28-May-2019::16:37:48.922225 ===
** Generic server <0.87.0> terminating 
** Last message in was {a,message,which,is_not,handled}
** When Server state == {state,<0.85.0>,
[some,data,in,stored,in,my,state],
<<"and a binary as well">>}
** Reason for termination ==
** {{badmatch,{a,message,which,is_not,handled}},
[{gs,handle_call,3,[{file,"gs.erl"},{line,32}]}, …
```
> Improve some log events from OTP

- lib/stdlib/src/uri_string.erl
~~Also remove an unnecessary try/catch in uri_string:normalize/1.~~
> uri_string:normalize/2 may return error()

- lib/stdlib/doc/src/uri_string.xml
- lib/stdlib/src/uri_string.erl
- lib/stdlib/test/uri_string_SUITE.erl
Please consider including them in OTP directly. For some backstory:
I was looking for this function because as part of implementing the parsing for the Link HTTP header it's necessary to resolve potentially relative URIs according to https://tools.ietf.org/html/rfc3986#section-5
After asking it turns out @darkling already needed this function in https://github.com/darkling/lagra/blob/30bba5322630382f046decb9bb83fd4ea75e058c/src/lagra_parser_turtle_parser.erl#L585
I asked him about license but I needed it before I got a response so I reimplemented it in Cowlib here: https://github.com/ninenines/cowlib/blob/master/src/cow_link.erl#L261
This is this implementation that I submit here as a PR, which is more or less the algorithm from https://tools.ietf.org/html/rfc3986#section-5.2.2
The …
> Add uri_string:resolve/2,3

- lib/ssl/src/dtls_socket.erl
- lib/ssl/src/ssl.erl
- lib/ssl/src/tls_connection.erl
- lib/ssl/src/tls_socket.erl
- lib/ssl/test/dtls_api_SUITE.erl
Solve ERL-1110
Closing a DTLS listen socket using UDP will not actually do much
as the connection is emulated and there is no low level socket
to close.
Also better follow tls/dtls-socket abstraction
> ssl: Correct close handling for DTLS

- lib/common_test/src/ct_framework.erl
Depending on what was given as an argument to erlang:error(),
parts would not be printed. Specifically two-tuples of atom and
something, would cause only the atom to be printed.
Also remove now redundant clause of exempting {'ERROR', _} from this.
> ct: Don't hide error reasons from user

- lib/ssh/src/ssh_sftpd.erl
file_handler is a callback module, tupled optionally with a state.
Fix that modules tend to be atoms.
Introduce ssh_sftpd_file_api:state() :: term() and use that,
but let the default state remain an empty list for compatibility.
> ssh: fix typespec in ssh_sftpd

- lib/kernel/doc/src/gen_sctp.xml
Everywhere else the error field in the SCTP record is an integer.
The default value for this field is '0'.
> sctp_assoc_change record have incorrect type in documentation

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/beam_except_SUITE.erl
Consider the following example:
-module(whatever).
-export([foo/0]).
foo() ->
foobar(1, 2, 3).
foobar(A, B, C) ->
foobar(A, B, C, []).
foobar(A, B, C, D) -> ...
The type optimization pass will find out that `A`, `B`, and `C` have constant
values and do constant folding, rewriting `foobar/3` to:
foobar(A, B, C) ->
foobar(1, 2, 3, []).
That will result in three unecessary `move` instructions.
This was an issue already in OTP 22, but it has got worse in the
upcoming OTP 23 release because of the improved type optimizations.
This commit adds an `unfold_literals` sub pass in `beam_ssa_opt` that
undoes the constant folding optimization, rewriting code to use the
original variable instead of the constant if the original variable is
known to be in an x register.
This optimization sub pass also …
> Unfold literals to avoid unnecessary move instructions

- erts/emulator/beam/beam_load.c
- erts/emulator/beam/ops.tab
- erts/emulator/utils/beam_makeops
The BEAM loader has a transformation engine that can do peephole optimizations while loading code: combining, splitting, and deleting instructions.
This pull request optimizes the transformation engine.
When loading a huge BEAM module (`NBAP-PDU-Contents` from the asn1 test suite) from a binary, the loading time is about 90 per cent of the loading time before this pull request.
> Optimize the transformation engine in the BEAM loader

- lib/syntax_tools/src/erl_prettypr.erl
- lib/syntax_tools/src/erl_tidy.erl
- lib/syntax_tools/src/prettypr.erl
I have a goal to fix erl_prettypr so that I can start using it in the projects I work on. Readability of some of the outputs is the biggest issue and this patch improves the situation a lot.
To see what the second commit does, compare output for [sep (new)](https://gist.github.com/Zalastax/4fafbc38e96197defa4e242cfc3b918d) with [par (old)](https://gist.github.com/Zalastax/d4bcd47a1eaef760bc301332c001889e). 
I also want to start preserving newlines that are used for grouping the code. It's something we see in tools for other languages and it's really useful. Consider
```Erlang
f() ->
oneaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
twoaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, threeaaaaaaaaaaaaaaaaaaaaaa,
later.
```
I would like it to format to
```Erlang
f() -> …
```
> Tidier erl

- erts/preloaded/src/socket.erl
Some OSes (for example Linux) allow "non-standard" pairs and we should just pass them as is to the BIFs. That will make OS test whether given combination is allowed or not.
> Do not check Type/Proto combination

- lib/erl_interface/doc/src/ei_connect.xml
- lib/erl_interface/doc/src/erl_call.xml
- lib/erl_interface/include/ei.h
- lib/erl_interface/src/connect/ei_connect.c
- lib/erl_interface/src/prog/erl_call.c
- lib/erl_interface/test/ei_connect_SUITE.erl
- lib/erl_interface/test/ei_connect_SUITE_data/ei_connect_test.c
- lib/erl_interface/test/erl_call_SUITE.erl
This pull request adds the flag `-address` to the `erl_call` program. This flag makes it possible for the user to use `erl_call` to interact with a node even if no EPMD instance is running on the node's host.
This pull request also adds a family of new functions to the `erl_interface` API (that are needed implement the new `erl_call` flag and similar types of functionality) and extends the documentation of `erl_call` and `erl_interface` with descriptions of the new flag and functions.
> Extend erl_call with a new flag to access a node at HOSTNAME:PORT

- lib/dialyzer/doc/src/typer.xml
in the usage the description is correct
> fixed a typo

- HOWTO/INSTALL-ANDROID.md
- erts/emulator/nifs/common/prim_net_nif.c
- erts/emulator/sys/common/erl_poll.h
- xcomp/erl-xcomp-arm-android.conf
- xcomp/erl-xcomp-arm64-android.conf
This pull request fixes Android cross compilation to make it work across all versions currently supported by the Android NDK, which are:
- API level 21 (Android 5.0 Lollipop) for 64-bit ARM
- API level 16 (Android 4.1 Jelly Bean) for 32-bit ARM
Thanks,
Jérôme
> Expand Android cross compilation compatibility

- erts/emulator/beam/erl_utils.h
- erts/emulator/beam/instrs.tab
- erts/emulator/beam/ops.tab
Optimize the `is_lt`, `is_ge`, `is_eq`, and `is_ne` instructions (used
to implement the Erlang operators `<`, `=<`, `>=`, `>`, `==`, and
`!=`).
The main optimization comes from the observation that when one of the
operands for `is_lt` or `is_ge` is a literal, that literal is almost
always an integer and almost never an atom. Therefore, it is a waste
of time and code space to compare atoms before calling the general
comparison function.
While at it, also slightly optimize the `is_eq` and `is_ne` instructions.
> Optimize relational tests

- lib/kernel/doc/src/code.xml
- lib/kernel/src/code.erl
- lib/kernel/test/code_SUITE.erl
This allows checking the statuses of a large number of modules without
performing an excessive amount of file system operations.
> Add module_status/0 and make module_status/1 accept a list of modules

- lib/erl_interface/src/misc/ei_portio.h
Noticed as a build failure against fresh gcc-master:
```
LD otp/lib/erl_interface/bin/x86_64-unknown-linux-gnu/erl_call
ld: otp/lib/erl_interface/obj/x86_64-unknown-linux-gnu/libei.a(eirecv.o):otp/lib/erl_interface/src/misc/ei_portio.h:50: multiple definition of `ei_default_socket_callbacks'; otp/lib/erl_interface/obj/x86_64-unknown-linux-gnu/libei.a(ei_connect.o):otp/lib/erl_interface/src/misc/ei_portio.h:50: first defined here
ld: otp/lib/erl_interface/obj/x86_64-unknown-linux-gnu/libei.a(send.o):otp/lib/erl_interface/src/misc/ei_portio.h:50: multiple definition of `ei_default_socket_callbacks'; otp/lib/erl_interface/obj/x86_64-unknown-linux-gnu/libei.a(ei_connect.o):otp/lib/erl_interface/src/misc/ei_portio.h:50: first defined here
ld: …
```
> ei_portio.h: avoid ODR violation of 'ei_default_socket_callbacks'

- erts/aclocal.m4
- erts/configure.in
- lib/erl_interface/configure.in
Use `-fno-common` for gcc, that is link error if multiple definitions of global variables are encountered. This is ISO C compliant.
Until version 10, gcc has had `-fcommon` as default, which allows and merges such dubious duplicates.
> Add gcc option -fno-common to detect name conflicts of global variables

- lib/ssl/src/ssl_cipher.erl
https://bugs.erlang.org/browse/ERL-1145
> @IngelaAndin: OpenSSL considers  RC4 and DES legacy and not default supported. They still support RSA. The not anonymous  PSK and SRP are prioritized over RSA.   So  you are welcome to make a PR that prioritizes  RSA over DES and RC4  in "all-list" and we will accept it.
> ssl: Prioritise rsa_suites above rc4 and des

- .travis.yml
- lib/kernel/test/inet_SUITE.erl
As Travis CI [officially supports](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) s390x builds, adding support for same.
> Add s390x support in travis build

- erts/doc/src/init.xml
Demo:
```
HOME="silly_value" /path/to/erl
> init:get_argument(home).
{ok,[["silly_value"]]}
```
> `init:get_argument(home).` uses `$HOME`

- lib/crypto/c_src/api_ng.c
This PR fixes potential memory leaks involving calls to the ng nifs.
Following along with the original PR in this file: https://github.com/erlang/otp/commit/98feb2577dc64a622f51dac6562135aa4c60274c
> crypto: fix ng mem leak

- erts/emulator/beam/utils.c
Teach `=:=` to immediately return `false` when comparing two maps
of different sizes. That can be much faster for huge maps.
Reported in the elixir forum:
https://elixirforum.com/t/erlang-2-does-not-seem-to-check-map-sizes-before-performing-the-thoroughful-comparison/28910
> Optimize =:= when comparing maps

- lib/kernel/src/dist_util.erl
- lib/kernel/src/net_kernel.erl
net_kernel contains several function intended only for debugging. For example,
node_info/1,2 and nodes_info(). While undocumented, these functions provide
extremely valuable monitoring information.
This patch fixes several issues. First, get_status call was monitoring node,
and not distribution process. It was a subject to race condition, when
'nodedown' message was never delivered. With erlang:monitor/2, race does
not happen. Also it allowed to remove unneeded flush_down from dist_util.
Second, nodes_info/0 was implemented sequentially, being quite slow. Now
it is concurrent enough to complete within a second even with thousands
nodes in a cluster.
Third, nodes_info/0 was traversing the same sys_dist table two times,
where one was enough.
Fourth, dialyzer specs are somewhat helpful too …
> net_kernel: improve performance of debugging functions, and fix race

- lib/asn1/src/Makefile
The build failure is reproducible on a 4-core CPU when using
massive parallelism:
```
$ make -j21 -l4
...
GEN    asn1ct_eval_ext.erl
{"init terminating in do_boot",
{undef,[{asn1ct_func,start_link,[],[]},
{prepare_templates,gen_asn1ct_eval,1,
[{file,"prepare_templates.erl"},{line,58}]},
{init,start_it,1,[]},{init,start_em,1,[]}]}}
init terminating in do_boot ()
Crash dump is being written to: erl_crash.dump...done
make[2]: *** [Makefile:139: asn1ct_eval_ext.erl] Error 1
```
Here `asn1ct_eval_ext.erl` attempts to load `asn1ct_func.beam`
via `prepare_templates.erl` before it's compiled into `.beam` file.
The change pulls in a dependency on `asn1ct_func.beam`.
Reported-by: WGH
Bug: https://github.com/NixOS/nixpkgs/pull/51644
Bug: https://bugs.gentoo.org/705500
Signed-off-by: Sergei …
> lib/asn1: add missing build dependency to 'asn1ct_eval_ext.erl'

- erts/emulator/nifs/common/prim_net_nif.c
* There was a typo in the error declaration, which lacked the e in enotsup.
* PASE has a getifaddrs, but it has a different name because AIX lacks the API. Handle this with some light ifdef.
Example:
```
1> inet:getifaddrs().
{ok,[{"127.0.0.1",
[{flags,[up,loopback,running,multicast]},
{addr,{127,0,0,1}},
{netmask,{255,0,0,0}}]},
{"<redacted>",
[{flags,[up,broadcast,running,multicast]},
{addr,{<redacted>}},
{netmask,{255,255,255,0}},
{broadaddr,{<redacted>}}]},
{"<redacted>",
[{flags,[up,broadcast,running,multicast]},
{addr,{<redacted>}},
{netmask,{255,255,252,0}},
{broadaddr,{<redacted>}}]}]}
2> os:type().
{unix,os400}
```
> Fix compile on systems without getifaddrs, add PASE getifaddrs

- lib/stdlib/doc/src/gen_statem.xml
- lib/stdlib/src/gen_statem.erl
- lib/stdlib/test/gen_statem_SUITE.erl
- lib/stdlib/test/gen_statem_SUITE_data/oc_statem.erl
- system/doc/design_principles/statem.xml
This is a new feature, proposed for `gen_statem`, that does not exist in e.g `gen_server`.
By returning the action `{change_callback_module, NewModule}` the `gen_statem` engine changes the callback module.  Simple as that!
We have not figured out any hairy implications other than that the *callback mode* has to be read for `NewModule` before calling any callback function in it, which was not very hairy.  Also, changing the callback module has to be regarded as orthogonal to changing the state.  I have furthermore made it not possible to change callback module from a *state enter call* since that would be just too weird.
The inception is our work on TLS 1.3.  This protocol has evolved so much that the state machines for TLS 1.3 has so little in common with the one for TLS 1.2, so it makes …
> gen_statem: change callback module

- lib/stdlib/src/ms_transform.erl
Although historically interesting, I think it's ok to remove this code snippet as package support was removed in OTP R16.
> Remove package support from ms_transform

- lib/tools/src/cover.erl
- lib/tools/test/cover_SUITE.erl
- lib/tools/test/cover_SUITE_data/otp_16476/obvious_booleans.erl
The cover tool translates andalso/orelse to a case in the instrumented
code. For example:
both_ok(A, B) ->
A =:= ok andalso B =:= ok.
Is translated to:
both_ok(A, B) ->
case A =:= ok of
true  -> B =:= ok;
false -> false;
_1    -> error({badarg, _1})
end.
Since the expression `A =:= ok` clearly is a boolean expression, the
final clause can't possibly match, so the compiler issues a
warning. If the `warnings_as_errors` option is set in the environment
or in the module itself, compilation will fail.
Eliminate the warning by letting cover mark the final clause as compiler
generated to suppress the warning.
https://bugs.erlang.org/browse/ERL-1147
> cover: Suppress compilation warnings when instrumenting andalso/orelse

- lib/hipe/icode/hipe_icode_primops.erl
- lib/hipe/test/basic_SUITE_data/basic_exceptions.erl
The native code compiler would crash when attempting to compile
code such as the following:
ignore_value_of_try_catch(X) ->
try
X + 1
catch
C:E:Stk ->
erlang:raise(C, E, Stk)
end,
ok.
https://bugs.erlang.org/browse/ERL-1175
> Eliminate crash in compilation of native code

- lib/kernel/src/inet_db.erl
- lib/kernel/src/inet_hosts.erl
- lib/kernel/test/inet_SUITE.erl
Avoid re-parsing changed file over and over, also fix race condition
when ETS table with IP <-> name mappings is first deleted, then
re-created.
> inet_db, inet_hosts: improve inet_db behaviour when .hosts file changes

- lib/stdlib/src/proplists.erl
Current edoc crashes xmerl parser with
```
14:49:01.064 [error] 2557- fatal: {:endtag_does_not_match, {:was, :"code.", :should_have_been, :code}}
/Users/lukaszsamson/.asdf/installs/erlang/22.2.6/lib/stdlib-3.11.2/src/proplists.erl, function substitute_negations/2: at line 408: error in XML parser: {fatal,
{{endtag_does_not_match,
{was,'code.',should_have_been,code}},
{file,file_name_unknown},
{line,422},
{col,64}}}.
```
> Fix invalid xml closing tag in proplists.erl edoc

- lib/kernel/doc/src/Makefile
- lib/kernel/doc/src/erpc.xml
- lib/kernel/doc/src/ref_man.xml
- lib/kernel/doc/src/rpc.xml
- lib/kernel/doc/src/specs.xml
- lib/kernel/src/Makefile
- lib/kernel/src/erpc.erl
- lib/kernel/src/kernel.app.src
- lib/kernel/src/rpc.erl
- lib/kernel/test/Makefile
- lib/kernel/test/erpc_SUITE.erl
- lib/kernel/test/global_SUITE.erl
- lib/kernel/test/rpc_SUITE.erl
- lib/kernel/test/seq_trace_SUITE.erl
- lib/observer/test/crashdump_helper.erl
- lib/sasl/test/release_handler_SUITE_data/lib/many_mods-1.0/src/m.erl
- lib/sasl/test/release_handler_SUITE_data/lib/many_mods-1.1/src/m.erl
- lib/sasl/test/release_handler_SUITE_data/lib/many_mods-2.0/src/m.erl
Rpc calls (and friends) utilizing the newly introduced distributed `spawn_request()` BIF when possible instead of communicating via the `rex` server. This removes `rex` as a scalability bottleneck for calls. It also removes the extra copying of the (potentially large) argument list via `rex` to the (by `rex` spawned) process actually executing the call.
<s>A number of new call functions (identified by the name ecall) has been added. The main purpose of this is making it easier to differentiate between returned result, uncaught exceptions, none-trapped exit signals, and rpc failures. The `rpc:ecall_send_request()`/`rpc:ecall_*_response()` functions also makes it possible to asynchronously handle call request/reply in situations which are not possible with the …
> Improvements of the rpc module

- erts/doc/src/init.xml
- erts/preloaded/src/init.erl
- lib/kernel/test/init_SUITE.erl
In order for Elixir developers to configure their
systems using Elixir syntax, the Elixir application
must be started. However, in order to start the
Elixir application, kernel and stdlib need to be
started, which means we can't configure those
applications.
Elixir addresses this by booting twice. First, the
system boots with a minimal set of apps started, then
it executes the configuration files, writes them to
disk and restarts the system, which will pick up the
new configuration.
The problem with such approach is that, when running
in embedded mode, starting and shutting down the system
takes a long period of time, due to the loading and
purging of all modules.
This PR addresses the problem by allowing the mode to
be changed to embedded on init:restart/1. This allows
Elixir to first …
> Allow changing the -mode when the system restarts

- erts/doc/src/erlang.xml
- erts/emulator/beam/beam_emu.c
- erts/emulator/beam/bif.c
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/instrs.tab
- erts/emulator/hipe/hipe_bif2.c
- erts/emulator/test/code_SUITE_data/call_purged_fun_tester.erl
- erts/emulator/test/exception_SUITE.erl
- erts/emulator/test/hipe_SUITE.erl
- erts/emulator/test/hipe_SUITE_data/trycatch_1.erl
- erts/emulator/test/trace_local_SUITE.erl
- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/trycatch_SUITE.erl
- lib/debugger/src/dbg_ieval.erl
- lib/debugger/src/dbg_iload.erl
- lib/debugger/test/exception_SUITE.erl
- lib/debugger/test/int_eval_SUITE_data/stacktrace.erl
- lib/debugger/test/line_number_SUITE.erl
- lib/dialyzer/test/small_SUITE_data/results/stacktrace
- lib/dialyzer/test/small_SUITE_data/src/stacktrace.erl
- lib/hipe/icode/hipe_beam_to_icode.erl
- lib/inets/test/httpd_SUITE.erl
- lib/inets/test/httpd_test_lib.erl
- system/doc/reference_manual/errors.xml
The `erlang:get_stacktrace/0` BIF retrieves the stacktrace from
the previous error in the process. The problem is that the very
existence of `erlang:get_stacktrace/0` means that the stacktrace
and potentially function arguments must be kept indefinitely.
Therefore, in OTP 21, the `erlang:get_stacktrace/0` BIF was deprecated
and the syntax of try/catch extended to allow matching out the
stacktrace directly.
This commit changes `erlang:get_stacktrace/0` for OTP 23 to always
return an empty list (`[]`) and eliminates the need to keep the
stacktrace forever.
`erlang:get_stacktrace/0` is scheduled for removal in OTP 24.
> Don't keep stacktraces forever

- lib/compiler/src/beam_ssa_bool.erl
This speeds up the pass in roughly 20%.
Before:
FUNCTION                                         CALLS        %     TIME  [uS / CALLS]
--------                                         -----  -------     ----  [----------]
gen:'-call/4-fun-0-'/4                               1     0.00        0  [      0.00]
gen:call/4                                           1     0.00        1  [      1.00]
gen:do_for_proc/2                                    1     0.00        1  [      1.00]
beam_ssa_bool:module/2                               1     0.00        1  [      1.00]
beam_ssa:uses/1                                      9     0.00        1  [      0.11]
erlang:whereis/1                                     1     0.00        1  [      1.00]
erlang:make_tuple/2                                  9 …
> Use cerl_sets where appropriate in beam_ssa_bool

- erts/doc/src/alt_disco.xml
- erts/doc/src/notes.xml
- lib/kernel/doc/src/erl_epmd.xml
- lib/kernel/doc/src/notes.xml
Discovery of "nodes" instead of "services" seems a more common description for Erlang distribution
> Rename Service Discovery into Node Discovery in documentation

- lib/eunit/src/eunit.erl
- lib/eunit/src/eunit_lib.erl
- lib/eunit/src/eunit_tty.erl
It can be set to change the max print depth of exceptions generated by eunit test suites. Current hardcoded limit of 20 can be considered too small in many cases and for some situations (like `?assertEqual` macro) this truncation can just easily hide the difference that we are trying to find with unit tests.
Example of such frustration: https://stackoverflow.com/questions/10952767/showing-full-expected-and-value-information-when-assertequal-fails
How it looks now:
I added `?_assertEqual(#{}, lists:seq(1, 5000))` to `eunit/examples/fib.erl`
```erlang
> cd("lib/eunit/examples").
> c("fib.erl").
> eunit:test(fib).
fib:19: fib_test_...*failed*
in function fib:'-fib_test_/0-fun-16-'/0 (fib.erl, line 19)
<..>
in call from eunit_proc:run_group/2 (eunit_proc.erl, line 561) …
```
> Add tty_exception_print_depth option to eunit:test

- scripts/diffable
This patch adds a new `--deterministic` command line flag to the
diffable script. When enabled, diffable compiles files with the
`deterministic` compiler option enabled. As deterministic compilation
results in line directives only containing the basename of module
files, this greatly reduces the size of diffs when comparing the
results from different build and source trees.
> scripts/diffable: Add option for compiling with +deterministic

- lib/compiler/src/beam_ssa_opt.erl
This patch fixes a bug in which beam_ssa_opt:is_safe_without_try/2 in
some cases reverses the order of the instructions in a basic block.
beam_ssa_opt:is_safe_without_try/2 is called from
beam_ssa_opt:do_opt_try/2 to traverse the instructions of a basic
block. During its in-order traversal, it accumulates the visited (and
kept) instructions in an accumulator. When the traversal encounters a
kill_try_tag instruction, the instruction is removed, traversal is
halted, and the modified list of instructions is returned. To preserve
the order among the instructions, the not yet traversed instructions
should be appended to the reversed accumulator. This patch fixes a
mixup of the arguments to lists:reverse/2 which resulted in a reversal
of the instruction order.
Unfortunately this patch comes …
> compiler: Fix instruction order reversal in ssa_opt_try

- lib/compiler/src/compile.erl
- lib/compiler/test/compile_SUITE.erl
Some tools may store v3_core and feed into the compiler,
in those cases, there is no need to prepare it.
> Allow sys_core_prepare to be skipped

- lib/sasl/doc/src/systools.xml
- lib/sasl/src/systools_make.erl
- lib/sasl/test/systools_SUITE.erl
I'm unable to compile OTP in order to run tests so I have not confirmed these changes yet. But because that has been taking so long to figure out I'm opening this as a draft for comment. I know that documentation still needs to be updated.
`make_script` now accepts the name of the boot file to create, it is not restricted to only `RelName.boot` or `start.boot`. This is because after talking to @josevalim he pointed out that Elixir releases need to create a `start_clean.boot`. With relx we just copy the one that is found in the Erlang install but they can't do that because it needs to include iex and elixir libs.
`make_tar` will take a list the same as the list of tuples you can pass to `erl_tar`, `{From, To}`.
> systools: support creating start.boot in make_script and adding files to make_tar

- lib/kernel/doc/src/logger_std_h.xml
- lib/kernel/src/logger_std_h.erl
- lib/kernel/test/logger_std_h_SUITE.erl
This is needed for simpler integration with Elixir logger which allows any device to be set as an output device. It also provides greater flexibility when needed to integrate with log catchers.
> Allow using custom IO devices in logger_std_h

- lib/kernel/doc/src/file.xml
- lib/kernel/src/file.erl
- lib/kernel/test/file_SUITE.erl
This adds file:del_dir/2, a variant of file:del_dir/1 taking a list of options to extend its behaviour.  Available options are:
- recursive: recursively delete the contents of a directory before deleting the directory itself
- force: ignore errors when accessing or deleting files or directories
- keeptop: the top-most directory is not deleted
file:del_dir(Dir, [recursive, force]) is equivalent to "rm -rf Dir" in a Unix shell.
file:del_dir(Dir, [recursive, force, keeptop]) is similar to "rm -rf Dir/\*" in a Unix shell, but will also remove "."-files not expanded by "\*".
file:del_dir(Dir, []) is equivalent to file:del_dir(Dir).
Symbolic links are not followed.
In recursive and non-force mode, if there is an error accessing or deleting a file, the error return specifies both the error and …
> add file:del_dir/2

- lib/kernel/src/pg.erl
Hi,
Looking through the new pg module that was recently merged in (https://github.com/erlang/otp/pull/2524), I came across something that might be unintended.
https://github.com/erlang/otp/blob/8eefeda8d81996bfe8249017fa0be2595eb64cff/lib/kernel/src/pg.erl#L130
There appear to be two issues here. One is that in the list case the (in)comprehension deals in dark arts, and two, that in the pid case, it is never ensured in the caller to be a pid.
The intent in join/3 when PidOrPids is a list seems to be to ensure that each entry is a pid and that it is local to the node, otherwise throw an error.
Unfortunately, the filters in comprehensions treat functions that can be guards as guards would be treated in clause heads ([read more](http://erlang.org/pipermail/erlang-questions/2010-October/053649 …
> pg: ensure argument is expected local pid(s)

- erts/emulator/nifs/unix/unix_prim_file.c
In most situations effective and real IDs will match, but in theory
someone can create NIF that will change the effective IDs to other one.
In such cases the returned value could be different from the expected.
> Use effective UID and GID in checks

- lib/erl_docgen/priv/css/otp_doc.css
When viewed on a smaller screen the content can be scrolled not only up
and down, but also left and right. More specifically it can be scrolled
back over the navigation menu to the left.
This prevents that, and as an bonus it fixes the scrolling to the right
where there is no content.
---
Compare:
With:
---
I wasn't sure if this is to be merged to master or maint. I mean the bug is in master, but the file hasn't been touched since 2015.
I can easily rebase on maint and update the PR if needed.
> Prevent left nav overlapping content during scroll

- lib/debugger/src/dbg_wx_win.erl
Fix to_string/1 to handle all kind of lists.
> Fix crash in string printing

- erts/doc/src/erl_cmd.xml
- lib/kernel/doc/src/kernel_app.xml
- lib/kernel/src/net_kernel.erl
- lib/kernel/src/user_drv.erl
- lib/stdlib/doc/src/shell.xml
Add documentation for `-dist_listen` and `-[s]name undefined`.
Also changed `-remsh` to assume that shortnames are used unless otherwise specified.
> Document dynamic node names and dist_listen false

- lib/ssl/src/ssl.erl
... restoring it to its intended value before e042afe547 that planted
the type for using it in the doc.
> ssl: fix documentation of option `crl_cache`

- lib/ssl/test/openssl_npn_SUITE.erl
Fix misspelling in calls to ssl_test_lib:check_sane_openssl_renegotiate/2
> Fix misspelling in ssl test cases

- lib/ssl/doc/src/ssl.xml
Relevant past commits:
- [Code re `valid`](https://github.com/erlang/otp/commit/6cced538abd4f8053c009b163efa8c6d568b9580?diff=split&w=1#diff-79b520311347e34fac9cffbc4ea373f9R539)
- [Code (and doc) re `valid_peer`](https://github.com/erlang/otp/commit/e501709bec61bf8813cab741b0e39c211c73c89e?diff=split&w=1#diff-79b520311347e34fac9cffbc4ea373f9R541).
----
This is similar to #2592 though I kept it as separate PR as I see some ongoing testing effort on that.
> ssl: fix documentation of option verify_fun

- erts/emulator/beam/ops.tab
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_trim.erl
- lib/compiler/test/beam_ssa_SUITE.erl
This PR fixes two issues in the compiler that made `lists:mapfoldl/3` slow. See the commit messages for further details.
https://bugs.erlang.org/browse/ERL-1216
> Fix slow lists:mapfoldl/3

- erts/emulator/nifs/common/prim_socket_nif.c
When passing a string into setsockopt we have to use the pointer to
the string, not a pointer to a pointer.
Affects the socket bindtodevice and tcp congestion option.
> socket-nif: Fix string argument passing for setsockopt

- lib/ssh/doc/src/ssh.xml
- lib/ssh/src/ssh.hrl
- lib/ssh/src/ssh_auth.erl
- lib/ssh/src/ssh_options.erl
Hi,
When using 'keyboard-interactive' SSH authentication we need access to the user state to be able to generate prompts. This to be able to integrate with e.g. https://duo.com/
This patch adds a (backwards compatible) 'keyboard-interactive' fun/4 that has access to the user state.
> Added a fun/4 with State access for keyboard-interactive

- lib/erl_interface/doc/src/erl_call_cmd.xml
- lib/erl_interface/src/prog/erl_call.c
- lib/erl_interface/test/erl_call_SUITE.erl
This PR makes erl_call work out of the box on systems like OS X where the computer's hostname can't always be resolved.
> erl_call: Assume localhost if own hostname resolution fails

- erts/emulator/beam/erl_hl_timer.c
Proposed fix to https://bugs.erlang.org/browse/ERL-1105.
> Fix SEGV while printing cancelled timer to crash dump

- erts/emulator/beam/bs_instrs.tab
- erts/emulator/beam/erl_bits.c
- erts/emulator/beam/erl_bits.h
- erts/emulator/test/bs_construct_SUITE.erl
When constructing binaries using the binary syntax, there would
not be any cost in terms of reductions for copying large binaries,
and a process could copy many large binaries before being scheduled
out.
Add a cost of 1 reduction per 1 KiB of binary data copied in
binary construction.
> Add a cost for copying binaries with the binary syntax

- lib/edoc/src/edoc_data.erl
- lib/edoc/src/edoc_extract.erl
- lib/edoc/src/edoc_layout.erl
- lib/edoc/src/edoc_specs.erl
- lib/erl_docgen/src/docgen_edoc_xml_cb.erl
Putting this up again...
I'm getting nowhere fast in cleaning this up (and starting to question how much that is needed).
As we all know, the best way to know what the proper solution would be is being wrong on the internet.
Purpose: render specs with multiple clauses in edoc.
> edoc: support multiple clauses in -spec

- erts/Makefile
- erts/emulator/test/port_bif_SUITE.erl
- erts/etc/common/Makefile.in
- erts/etc/unix/Install.src
- erts/etc/win32/Install.c
- lib/erl_interface/src/Makefile.in
- lib/sasl/doc/specs/.gitignore
- lib/sasl/doc/src/Makefile
- lib/sasl/doc/src/specs.xml
- lib/sasl/doc/src/systools.xml
- lib/sasl/src/systools.erl
- lib/sasl/src/systools_make.erl
- lib/sasl/test/systools_SUITE.erl
This PR makes the executable `erl_call` to be part of erts when building Erlang so that tools can rely on it being present and not have to include all of `erl_interface`.
Also, any tool binaries in erts are now filtered away when creating the release tar using `systools:make_tar/1,2`.
> Copy erl_call to erts and filter tools from systools:make_tar

- erts/etc/common/erlexec.c
Stop the assumption that every operating system or setup has a HOME directory
available (or a similar notion) with a corresponding environment variable set.
This assumption is not always accurate as raised in ERL-476, for example on
Android with its stricter model of sandboxed applications.
As suggested in https://bugs.erlang.org/browse/ERL-476 here is a first pull
request to get comments on whether this is going in a right direction or not.
I've found 18 occurrences of init:get_argument(home). There seems to
be very few cases where it is actually required :
- in dialyzert_plt.erl on line 239, but the DIALYZERL_PLT env can bet set
- in dbg_wx_settings.erl on line 77
- in observer_wx.erl on line 647
In practice, Dialyzer and graphical user interfaces won't be run in the
scenarios that …
> [RFC] Make the HOME environment variable optional

- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/standards_compliance.xml
- lib/ssl/src/dtls_connection.erl
- lib/ssl/src/dtls_handshake.erl
- lib/ssl/src/dtls_record.erl
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/ssl_connection.hrl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/ssl_handshake.hrl
- lib/ssl/src/ssl_internal.hrl
- lib/ssl/src/ssl_record.erl
- lib/ssl/src/ssl_record.hrl
- lib/ssl/src/tls_connection.erl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_handshake.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/src/tls_record.erl
- lib/ssl/src/tls_record_1_3.erl
- lib/ssl/test/Makefile
- lib/ssl/test/ssl_mfl_SUITE.erl
- lib/ssl/test/ssl_session_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
- lib/ssl/test/tls_1_3_record_SUITE.erl
This PR implements the max_fragment_length extension specified in RFC 6066, allowing a client to negotiate a smaller plaintext.
Support is provided for DTLS/TLS 1, 1.1 & 1.2 as well as TLS 1.3
> Implement RFC 6066 extension max_fragment_length

- lib/stdlib/examples/erl_id_trans.erl
- lib/stdlib/src/erl_expand_records.erl
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/src/erl_pp.erl
This removes remnants of Joe Armstrong's experiment with "proper structs".
> Drop commented-out code for the experimental "structs"

- lib/asn1/test/asn1_SUITE.erl
- lib/asn1/test/asn1_test_lib.erl
- lib/asn1/test/testMegaco.erl
Running the asn1 tests in parallel requires a lot of memory, and if
there is crash or multiple half-hour time trap timeouts, we won't know
which test case that caused the problem. Besides, it has always been
tricky to run tests in parallel because some test cases use the same ASN.1
specs and these test cases must not be run in parallel.
In this commit we will stop running asn1 test cases in parallel.
Not running test cases in parallel means that several more minutes
will be needed to run the entire asn1 test suite. Note that
`asn1_test_lib:compile_all/3`, which is used by some test cases, will
compile the given ASN.1 specs in parallel. We can shave off some time
by using `compile_all/1` in more places, for example by combining
test cases that test similar things.
> Reduce memory consumption and improve debuggability of asn1 tests

- lib/kernel/src/dist_util.erl
Recent commits in dist_util.erl have broken compilation when tracing is enabled in dist_util.hrl
This PR fixes the few impacted ?trace and ?debug lines
> Fix compilation when enabling tracing in dist_util.hrl

- lib/stdlib/src/digraph.erl
- lib/stdlib/test/digraph_SUITE.erl
This patch fixes a bug in the digraph module where in_edges/2 and
out_edges/2 return false edges in the case they are called for a
vertex which has a '_' in its name term. The following example shows
the problem:
G = new([acyclic]),
A = add_vertex(G, 'A'),
B = add_vertex(G, '_'),
AB = add_edge(G, A, B),
0 = out_degree(G, B), %% ok
[] = out_edges(G, B), %% Fails as [AB] is returned
An edge, E, emanating from and incident on a vertex is stored in the
ntab-ets table as a record of the form {{out, V}, E} and {{in, V}, E}
respectively. As out_edges/2 and in_edges/2 use ets:select/2 to look
up the relevant edges, a vertex with a '_' somewhere a in the term
used as its name will trigger ets to do a wildcard match. In the
example above, this will return all out-edges in the whole graph. This …
> digraph: Avoid false edges for vertices with names containing a '_'

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
The optimization of 'not' in a guard by the beam_ssa_bool pass was
broken. It turns out that this optimization was very seldom triggered
and therefore was not well-tested. Fix the problem by removing the
optimization of 'not'.
https://bugs.erlang.org/browse/ERL-1246
> Fix incorrect compilation of guard expressions with 'not'

- lib/stdlib/src/erl_parse.yrl
This is one of the changes in the parser done during development of the flexible parser for the formatter.  It will probably benefit the mainline parser as well. I'm exploring possibilities of upstreaming more changes.
> Simplify erl_parse.yrl using operator precedence

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
When a guard expression referenced another boolean expression, the
`beam_ssa_bool` pass could drop tests from the guard. Here is an
example:
Bool = Z =:= false,
if
X =:= Y orelse Bool -> ok;
true -> error
end.
The compiler would essentially rewrite this example to:
_ = X =:= Y,
if
Z =:= false -> ok;
true -> error
end.
See the comments in the code for more details.
https://bugs.erlang.org/browse/ERL-1253
> Avoid unsafe optimization of guards

- lib/kernel/src/application_controller.erl
ets:filter dies with badarg if there is a delete, while it is walking through the table
I've found that if an application uses `application:loaded_applications()` while live upgrade/downgrade is running, it throws badarg errors
it is fairly easy to reproduce:
```
2> [spawn(fun() -> application:loaded_applications(),application:unset_env(kernel,shell_history),application:set_env(kernel,shell_history,enabled) end) || _<-lists:seq(1,10000)].
=ERROR REPORT==== 21-Apr-2020::10:31:10.959539 ===
Error in process <0.732.0> with exit value:
{badarg,[{ets,next,[ac_tab,{env,kernel,shell_history}],[]},
{ets,do_filter,5,[{file,"ets.erl"},{line,775}]},
{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,684}]},
{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,126}]}]}
=ERROR REPORT==== …
```
> use ets:select instead of ets:filter in application:loaded_applications/0

- lib/public_key/doc/src/public_key.xml
- lib/public_key/src/public_key.erl
- lib/public_key/test/public_key_SUITE.erl
This PR aims at giving user possibility to generate custom TLS alert for path validation errors.
Previously, no matter what user defined verify_fun returned, the alert was always Bad Certificate.
The changes allow user to control TLS alert in similar way that is done for certificates with valid paths.
> User defined tls alert for selfsigned cert

- erts/emulator/beam/external.c
- erts/emulator/test/distribution_SUITE.erl
Proposed fix to https://bugs.erlang.org/projects/ERL/issues/ERL-1254
Provoked by sending export funs (eg `fun lists:reverse/1`) on a not yet established connection.
Bug exists since OTP-23.0.
> ERL-1254: Fix bug encoding export fun on pending connection

- lib/kernel/src/inet_tcp_dist.erl
Backlog of 128 was hardcoded into inet_tcp_dist, ignoring any setting coming
from inet_dist_listen_options. This change allows to configure backlog as
expected.
> inet_tcp_dist: honour {backlog, NNN} setting from inet_dist_listen_options

- lib/inets/doc/src/httpc.xml
This is a proposed solution for ERL-1215.
> httpc: clarify the handling of the percent ("%") character in URIs

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/src/erl_scan.erl
In the case of deprecation warnings erl_lint:format_error/1 would include the word `use` while all `-deprecated/1` calls included the word `use` resulting in `use use` in the warning message.
I'd be happy to write a test but it didn't look like there were any tests concerned with this level of detail and assumed it's probably unwanted.
Before : 
```
src/mod.erl:line_no: Warning: crypto:block_encrypt/4 is deprecated and will be removed in OTP 24; use use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or crypto:crypto_(dyn_iv)?_init + crypto:crypto_(dyn_iv)?_update + crypto:crypto_final instead
```
After:
```
src/mod.erl:line_no:  Warning: crypto:block_encrypt/4 is deprecated and will be removed in OTP 24; use crypto:crypto_one_time/5, crypto:crypto_one_time_aead/6,7 or …
```
> Fixup erl_lint:format_error/1 deprecation clause

- lib/kernel/doc/src/file.xml
- lib/kernel/src/file.erl
- lib/kernel/test/file_SUITE.erl
As dicussed in [ERL-1244](https://bugs.erlang.org/browse/ERL-1244), here is a PR implementing  file:delete/2 supporting the 'raw' option.
Let me know if this is going in the right direction, then I'll add a corresponding documentation update in a second commit.
Thanks, Jérôme
> Introduce file:delete/2 supporting 'raw' option

- .gitignore
- erts/doc/src/alt_dist.xml
- lib/kernel/examples/Makefile
- lib/kernel/examples/erl_uds_dist/src/Makefile
- lib/kernel/examples/erl_uds_dist/src/erl_uds_dist.erl
- lib/kernel/test/Makefile
- lib/kernel/test/erl_distribution_SUITE.erl
Update `uds_dist.erl`, the alternative distribution protocol example using Unix Domain Sockets which was originally using a port driver written in C, by switching to distribution controllers implemented by Erlang processes instead, so with the code now written entirely in Erlang.
Add support for recent distribution features as well, such as dynamic node names and 32-bit big Creation numbers.
EDIT: The updated pull request now creates a new `uds2_dist.erl` module instead of replacing the original one.
> New erl_uds_dist.erl example entirely in Erlang

- erts/etc/win32/nsis/erlang20.nsi
Prevent redist from restarting the system and thus aborting the
installation when installing in silent mode.
> Fix system restart when installing in silent mode

- erts/emulator/beam/bif_instrs.tab
Preliminary proposed fix for https://bugs.erlang.org/browse/ERL-1273.
Bug only exists since OTP 23.0.
The problem is in instruction i_load_nif when it fails to seize code_write_permission. When yielding it does not save the arguments reg[0] and reg[1].
> Fix bug in erlang:load_nif/2 sometimes throwing badarg

- erts/emulator/test/exception_SUITE.erl
- lib/compiler/src/beam_ssa_codegen.erl
If the update of a map using the syntax `Map#{Key := Value}` failed,
the line number in the stack backtrace could be wrong.
https://bugs.erlang.org/browse/ERL-1271
> Fix line number for failing map update

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/test/beam_ssa_SUITE.erl
Eliminate a compiler crash when there are repeated calls to `is_map_key/2`
with the same arguments.
https://bugs.erlang.org/browse/ERL-1276
> Eliminate compiler crash for repeated is_map_key/2 calls

- erts/lib_src/common/erl_misc_utils.c
Fixes https://bugs.erlang.org/browse/ERL-1280
With this, if CPU quota is less than 1, we will try to use `1` as the quota. Without this, cores number will be used.
> erts: set quota to 1 if cpu quota is less than 1

- lib/erl_docgen/priv/css/otp_doc.css
- lib/erl_docgen/priv/xsl/db_html.xsl
- system/doc/top/templates/index.html.src
This PR tries to fix two problem
The html documentation horizontal scroll "bug" initially address by #2571 and the disappearing "since" versions which was a side effect of the same PR.
PR #2637 is an earlier simpler attempt at fixing the disappearing "since" versions, but it did not retain the layout, which this PR hopefully does. 
The resulting HTML docs can be reviewed here:
http://erlang.org/~sverker/since-margin/doc/index.html
> Refix doc overlapping during horizontal scroll 

- CONTRIBUTING.md
We want it to be as easy as possible to review a pull request without
breaking the possibility to use bisect.
The need for improvement was discovered due to PR-1968 and a first
enhancement proposal made in PR-2652, but we discovered it needed to
be reworded to fulfill our whole requirement.
> Clarify how to make contributions

- lib/ssl/doc/src/using_ssl.xml
The return value does not match the pattern on the preceding line.
> Fix small typo in using_ssl.xml

- erts/doc/src/erlang.xml
Avoid "billion" as it can be ambiguous depending on language.
> erts: Revert small doc change

- lib/syntax_tools/src/erl_syntax.erl
Patch made via online editor, I hope the formatting is correct and acceptable.
> Fix typo in edoc for erl_syntax:operator/1

- lib/stdlib/doc/src/unicode_usage.xml
> unicode_usage: fix typo in docs

- system/doc/reference_manual/expressions.xml
The documentation already spells out how all other data types are
compared, so let's mention how bit strings are compared as well.
Also add two examples.
---
I *think* this is how it works, but please correct me if not!
> Spell out how bit strings are compared

- lib/erl_interface/doc/src/ei.xml
- lib/erl_interface/src/misc/get_type.c
- lib/erl_interface/test/ei_decode_SUITE_data/ei_decode_test.c
- lib/erl_interface/test/ei_decode_encode_SUITE_data/ei_decode_encode_test.c
as documented.
Proposed fix for https://bugs.erlang.org/projects/ERL/issues/ERL-1288
> Fix ei_get_type to set *size to zero for floats, pids, ports and refs

- lib/compiler/src/sys_core_alias.erl
The goal of the sys_core_alias pass is to optimize
code like this:
foo({ok, Val}) ->
{ok, Val}.
into:
foo({ok, Val} = Var) ->
Var.
To do so, we need to find all patterns and find all
tuples and lists that may mirror their patterns.
Previously, we would compute the keys for each data
structure even if no pattern was stored. This optimizes
it so we only compute the keys if we have a pattern
so far.
> Only compute vars and keys if we have patterns

- lib/ssh/src/ssh_agent.erl
Attempting to request a user key from the ssh agent may fail because `unpack/1` assumes
that the received packet contains the full response, but in some cases it doesn't and one might
get a match error as seen below:
```erlang
> Options = [{key_cb, ssh_agent}, {key_cb_private, []}, {user_dir, '/home/jonjon/.ssh'}].
[{key_cb,ssh_agent},
{key_cb_private,[]},
{user_dir,'/home/jonjon/.ssh'}]
> ssh_agent:user_key("ssh-rsa", Options).
** exception error: no function clause matching ssh_agent:unpack(<<0,0,9,249,12,0,0,0,5,0,0,2,23,0,0,0,7,
115,115,104,45,114,115,97,0,0,0,3,...>>) (ssh_agent.erl, line 177)
in function  ssh_agent:send/2 (ssh_agent.erl, line 168)
in call from ssh_agent:user_key/2 (ssh_agent.erl, line 110)
```
`unpack/1` uses the first 4 bytes of the message to determine how much …
> Fix getting data from ssh-agent

- erts/configure.in
Compilation is failing on macOS Big Sur due to `in6addr_any` and `in6addr_loopback` being redeclared. The underlying issue is that the tests for these are failing due to missing include statements:
```sh
conftest.c:197:1: error: implicitly declaring library function 'printf' with type 'int (const char *, ...)' [-Werror,-Wimplicit-function-declaration]
printf("%d", in6addr_any.s6_addr[16]);
^
conftest.c:197:1: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
```
ERL-1306
> Add missing include statements in in6addr tests

- lib/ssl/doc/src/using_ssl.xml
- lib/ssl/src/tls_server_session_ticket.erl
- lib/ssl/test/ssl_session_ticket_SUITE.erl
The window is passed as an integer, not as tuple.
Sorry I did not include a test with this PR. There are so many moving parts in ssl. I checked this PR by using Chrome and Firefox and connect it to an erlang web server using TLS 1.3 with stateless tickets with bloomfilter replay detection.
> Fix stateless ticket window check. ERL-1316

- bootstrap/lib/stdlib/include/erl_bits.hrl
- lib/stdlib/include/erl_bits.hrl
Removing macros and the record bitdefault - they are never used.
> erl_bits.hrl cleanup

- lib/kernel/src/file.erl
A first step for inet_backend socket to support sendfile - use a fallback.
The finished implementation needs to call C lib sendfile() from prim_inet_nif.c, later...
> Implement fallback for inet_backend socket sendfile

- erts/emulator/sys/common/erl_check_io.c
- lib/kernel/test/gen_tcp_misc_SUITE.erl
This commit fixes a race condition, which can be reproduced
with running a large amount of bidirectional TCP streams.
When the system is fully loaded, it is possible that socket migrated
to scheduler pollset still fires EPOLLIN event. In this case
active_events field of ErtsDrvEventState structure will desynchronise
from the actual state (with EPOLLIN requested via scheduler pollset).
This, in turn, leads to all ERTS_POLL_EV_IN events disregarded. All
reads from the socket will be stopped.
This can only happen for {active, N} mode of a TCP socket, where
fd migrates back and forth to/from scheduler pollset.
> erl_check_io: do not discard ERTS_POLL_EV_IN from active_events

- lib/observer/src/observer_app_wx.erl
- lib/observer/src/observer_perf_wx.erl
Avoid flickering graphs (on windows) by using wxBG_STYLE_PAINT,
i.e. telling wx that observer code handles the drawing the window.
> Use wxBG_STYLE_PAINT instead of STYLE_SYSTEM

- lib/kernel/src/erl_epmd.erl
`wait_for_port_reply/2` will return `closed` in the `tcp_closed` case, and this is propagated as the return value of port_please
Reported in the RabbitMQ public slack channel:
https://rabbitmq.slack.com/archives/C1EDN83PA/p1588166195464400
> port_please/2 and port_please/3 can return closed

- lib/runtime_tools/src/appmon_info.erl
This PR tries to fix the following crash we observed on our verification testing VM:
`2020-05-02 11:33:33 =ERROR REPORT====
** Generic server appmon_info terminating
** Last message in was {do_it,{app,mhs,<0.2732.0>}}
** When Server state == {state,<0.7060.0>,[],#Ref<0.3033159193.3255697412.174888>,[<0.7060.0>]}
** Reason for termination ==
** {badarg,[{appmon_info,format,1,[{file,"appmon_info.erl"},{line,716}]},{appmon_info,format,1,[{file,"appmon_info.erl"},{line,706}]},{appmon_info,format,1,[{file,"appmon_info.erl"},{line,706}]},{appmon_info,calc_app_tree,2,[{file,"appmon_info.erl"},{line,454}]},{appmon_info,do_work,2,[{file,"appmon_info.erl"},{line,308}]},{appmon_info,handle_info,2,[{file,"appmon_info.erl"},{line,276}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{ …
> Fixing crash in appmon_info:format for a closed port

- erts/doc/src/erlang.xml
- erts/doc/src/erts_alloc.xml
- erts/emulator/beam/atom.names
- erts/emulator/beam/erl_bif_info.c
- erts/etc/common/erlexec.c
- erts/preloaded/src/erlang.erl
- lib/hipe/cerl/erl_bif_types.erl
- lib/observer/test/crashdump_viewer_SUITE_data/old_format.dump
- lib/runtime_tools/src/system_information.erl
- lib/runtime_tools/test/system_information_SUITE_data/information_test_report.dat
While working on https://github.com/erlang/otp/pull/2627, I found that this elib_malloc stuff was still in there even though the docs said it was to be removed in R15. See https://github.com/erlang/otp/blob/master/erts/doc/src/notes.xml#L16543
> Drop remnants of elib_malloc (removed in R15)

- erts/emulator/beam/break.c
This is intended mostly as a starting point for a discussion – checking if the powers that be are open to tweaking this text at all.
I've found the "Eh?" prompts a little grating – the tone comes across to me as the system being annoyed.
Also, this prompt could help the user out by clarifying what it's after. I seem to remember getting stuck in this state once or twice as a newcomer to the ecosystem.
I considered repeating the options ("Sorry? Please enter one of these options: …"), but figured the options will usually still be on screen, so it would add noise to the output and slight complexity to the code, keeping them in sync.
What do you think?
> break.c: Rephrase "Eh?"

- erts/emulator/drivers/common/ram_file_drv.c
- lib/kernel/src/ram_file.erl
- lib/kernel/test/ram_file_SUITE.erl
This commit removes the following unused private APIs:
* ram_file:open/2 with deprecated file modes
(it is now equivalent to raw_file_io:open/2)
* ram_file:set_file/2 and ram_file:get_file_close/1
which are private and not used anywhere in Erlang/OTP
* ram_file:uuencode/1 and ram_file:uudecode/2 which
which are private and not used anywhere in Erlang/OTP
Note that ram_file:get_size/1 also fits the criteria above
but it was kept because there is some usage in the wild.
> Remove unused and private ram_file functions

- erts/emulator/beam/erl_db_util.c
Howdy!
This is a fix for segfaults happening on Apple ARM64. The segfaults are caused by differences in how Apple ARM64 treats variadic functions. x86 will only use the stack when necessary, after filling the available registers; while, 🍎 ARM64 will always places variadic arguments onto the stack regardless of many registers are available. The segfault manifests as what look like errors in bif functions (e.g. `is_integer_1`) and do not leave an erl crash dump (only available logs were from the system's crash report).
This was originally developed against to `master` (otp-24) but has been back-ported here to `maint`. The updated build configuration provided by #2700 is required so it's currently included in this branch.
I'm running the tests now and will get back with the results when they …
> Fix: Variadic function cast causing segfaults on Apple ARM64

- lib/ssl/doc/src/notes.xml
- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/using_ssl.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_cipher.erl
- lib/ssl/src/tls_record.erl
- lib/ssl/test/ssl_ECC.erl
- lib/ssl/test/ssl_ECC_SUITE.erl
They are referenced as "cipher suites" most of the time, but as "cipher suits" in a few places. This change turns these remaining occurences into "cipher suites". Also fixes typo: chipher -> cipher.
> Name cipher suites consistently across ssl docs

- lib/stdlib/src/supervisor.erl
- lib/stdlib/test/supervisor_SUITE.erl
When a temporary child of a `simple_one_for_one` supervisor died, the  internal state of the supervisor would be corrupted in a way that would cause the supervisor to retain the start arguments for subsequent children started by the supervisor, causing unnecessary growth of the supervisor's heap.
This bug was introduced in 59d418205486.
Thanks to Zeyu Zhang (@zzydxm) for noticing this bug and to Maxim Fedorov for making it known to me.
> supervisor: Eliminate a subtle internal state corruption

- lib/dialyzer/src/dialyzer_dep.erl
- lib/dialyzer/test/plt_SUITE.erl
Fixed dialyzer plt build breaking on code that compiles to letrec nested within a multi-value values node.
The code sample in plt_SUITE: letrec_rvals contains the following (cleaned up) extract:
```
<(letrec('lc$^0'/1 ) =
(...(let (_6) = (apply('lc$^0'/1)((_3))) in ([('ok') | (_6)]))...) in (...)),
(_Res)>
```
While traversing the tree:
1. letrec node would (incorrectly) inherit num_rvals from values (here: 2)
2. then apply would incorrectly duplicate output
3. then let would call bind_list on two lists of differing length (list of 1 corresponding to _6; list of 2 returned by apply)
4. resulting in function_clause error for bind_list1
The fix updates values handler to recurse into children with num_rvals = 1 (as each child corresponds to a single slot of a values node)
> Fix: ERL-1307 - dialyzer handling of letrec nested in values

- erts/emulator/sys/win32/sys_time.c
If resolution is good enough use QueryPerformanceTimer on windows,
which with thread compensation gives an ~0.1ms resolution instead of 15ms.
The cost is ~30% higher for QPC than for GetTickCound64
and the thread compensation cost adds another 0.5% amortized cost.
> win32: Use QPC timer on Windows

- erts/emulator/beam/beam_emu.c
The x86 and AMD64 optimization guides recommend that branch targets
are paragraph aligned (16 bytes). Neither GCC nor Clang align the
addresses of first class labels as used by the OpCase construction
when the jump table is enabled. Aligning the OpCase labels looks like
a worthwhile optimization, but despite the recommendation in the
optimization guides, forcing alignment leads to a ~5% slowdown of the
emulator. Therefore alignment of OpCase labels are not attempted.
As at least two OTP developers have independently attempted this
optimization and measured the same slowdown, this patch adds a comment
documenting this fact. The comment is placed where the OpCase macro is
defined, as a person trying to implement alignment will likely look
there.
> emulator: Document the futility of aligning opcode labels

- lib/stdlib/src/epp.erl
- lib/stdlib/test/epp_SUITE.erl
Referencing an undefined preprocessor symbol in an `-if` directive
would return an invalid error term not recognized by
`epp:format_error/1`.
https://bugs.erlang.org/browse/ERL-1310
> epp: Fix error return for an incorrect preprocessor -if directive

- erts/doc/src/erl_cmd.xml
- erts/emulator/sys/common/erl_sys_common_misc.c
- lib/kernel/doc/src/file.xml
- lib/stdlib/doc/src/unicode_usage.xml
UTF-8 is used for filename encoding on Android, for reference from the official documentation:
https://developer.android.com/reference/java/io/File#interoperability-with-java.nio.file-package
> On Android strings are converted to UTF-8 byte sequences when sending filenames to the operating system, and byte sequences returned by the operating system (from the various list methods) are converted to strings by decoding them as UTF-8 byte sequences.
Cheers,
Jérôme
> Default to Unicode for filename encoding on Android

- erts/preloaded/src/erlang.erl
`dialyzer` grumbles that `label` needs to be `non_neg_integer()` but since 06ed628dfd013010dd6e182508c1137b9f4ba09b (PR #1760) this constraint has been lifted and is now `term()`.
As things are at the moment the following:
```
ok = case seq_trace:get_token(label) of
{label,{_TraceId,_Bag,undefined}} ->
ok;
{label,{_TraceId,_Bag,_SpanExportable}} ->
span_orphan;
[] ->
ok
end
```
Causes `dialyzer` to grumble with:
```
27: The pattern {'label', {_TraceId, _Bag, 'undefined'}} can never match the type {'label' | 'print' | 'receive' | 'send' | 'serial' | 'strict_monotonic_timestamp' | 'timestamp',boolean() | non_neg_integer() | {non_neg_integer(),non_neg_integer()}}
```
This (untested!) commit should hopefully fix this, though only changing spec's it is not 100% clear to me as we are in …
> seq_trace: fix label spec missed in PR #1760

- lib/stdlib/src/lists.erl
- lib/stdlib/test/lists_SUITE.erl
lists:sublist/3 fails when Start (the 2nd argument) was greater than
len(List)+1, due to nthtail/2 throwing an exception. This change
replaces the use of nthtail/2 with a recursive function definition.
This fixes [ERL-1334](https://bugs.erlang.org/browse/ERL-1334).
> stdlib: fix lists:sublist/3 if Start>length(L)+1 

- lib/compiler/src/beam_peep.erl
- lib/compiler/test/map_SUITE.erl
Because of an unsafe optimization, the following expression would
fail to match:
#{ <<"result">> := #{<<"foo">> := <<"6">> } } =
#{ <<"result">> => #{<<"foo">> => <<"6">> } }
> Correct an unsafe optimization of nested map matching

- lib/kernel/doc/src/application.xml
Before this change, the documentation incorrectly describes the
case of running application:ensure_all_started for an application
which is started, but has unstarted dependencies.
> Updated documentation for application:ensure_all_started

- lib/kernel/src/pg.erl
- lib/kernel/test/pg_SUITE.erl
When distribution is started dynamically (via net_kernel:start/1),
pg incorrectly forms an overlay network with local node. Then,
every local process is counted twice (once as local, once as
remote).
This commit also contains tests for the case above, and test
case for local process check.
> pg: fix doubling for local processes with dynamic distribution

- HOWTO/INSTALL-ANDROID.md
- erts/Makefile
- erts/etc/common/Makefile.in
This patch replaces /bin/sh into /system/bin/sh in the Release target for Android to adjust the various Erlang/OTP release scripts. I've updated the Android documentation accordingly.
I'm not totally sure to see the purpose of the local_setup target in erts/Makefile when cross compiling for Android but I've adjusted it as well.
Cheers, Jérôme
> Adjust the shell path in installation scripts for Android

- lib/crypto/src/crypto.erl
Found this while upgrading old code, correct replacement should be `rand:uniform/1`, the current warning points to a non-existant function.
> Fix deprecation warning message

- erts/doc/src/erl_ext_dist.xml
The LongAtoms flag fields does not always follow
the atom cache references on the wire.
The original wording is confusing because the fields are only "after" conceptually, but not always on the wire due to the atom cache refs being encoded out of order on the wire (`<<Flags2:4, Flags1:4, Flags4:4, Flags3:4, LongAtomsFields:4, Flags5:4>>` for example).
> erl_ext_dist: Clarify the location of LongAtoms

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_validator_SUITE.erl
- lib/compiler/test/bs_match_SUITE.erl
https://bugs.erlang.org/browse/ERL-1340
> beam_validator: Track the unit of saved bs match positions

- lib/ssl/src/tls_sender.erl
- lib/ssl/test/inet_crypto_dist.erl
Distribution over TLS may exhibit livelock-like behaviour when
there is a constant stream of distribution messages. Limit
TLS record to "distribution buffer busy limit" to avoid this
behaviour.
This commit also recovers ssl_dist_bench_SUITE accidentally
broken when adding "erl_epmd callback listen_port_please".
> tls_sender: avoid livelock timeout for distribution data

- lib/tools/src/xref_base.erl
- lib/tools/test/xref_SUITE.erl
Xref incorrectly reported functions called exclusively from an on_load
function as being unused.
> Xref: Fix local calls from on_load being reported as unused

- erts/aclocal.m4
Apple Clang 12 included in Xcode 12 reports an error when a
function without a declaration is used. That change causes
the configure test for jump table support to wrongly assume
that jump table support is missing, and therefore a `switch`
would be used, degrading the performance of BEAM.
> Undo perform degradation on macOS

- erts/emulator/beam/erl_process_dict.c
Modern versions of Clang emit a warning that the array size calculation
in erl_process_dict.c is wrong. Only half of the array would be used.
That would lead to a performance degradation if many items were stored in
the process dictionary.
> Fix performance degradation for many items in process dictionary

- erts/emulator/beam/jit/beam_asm.hpp
- erts/emulator/beam/jit/instr_bs.cpp
- erts/emulator/beam/jit/instr_common.cpp
- erts/emulator/beam/jit/instr_guard_bifs.cpp
- erts/emulator/beam/jit/instr_select.cpp
- erts/emulator/beam/jit/ops.tab
- erts/emulator/beam/jit/predicates.tab
When two words that are consecutive (or reverse consecutive), SSE and AVX can be used to move two words at once, shrinking the code size.
> Use SSE/AVX to shrink code generated by the JIT

- .github/workflows/sync-github-releases.yaml
- scripts/sync-github-releases.sh
This commit adds a github workflow that periodically syncs the contents of http://erlang.org/download with https://github.com/erlang/otp/releases.
This is done for any release > OTP-21.
> Add github release sync

- erts/emulator/test/driver_SUITE_data/peek_non_existing_queue_drv.c
- erts/emulator/test/driver_SUITE_data/thr_msg_blast_drv.c
- erts/emulator/test/estone_SUITE_data/estone_cat.c
- erts/emulator/test/mtx_SUITE_data/mtx_SUITE.c
- erts/emulator/test/port_bif_SUITE_data/port_test.c
- erts/emulator/test/trace_SUITE_data/slow_drv.c
- lib/erl_interface/test/all_SUITE_data/ei_runner.c
- lib/erl_interface/test/ei_connect_SUITE_data/einode.c
- lib/erl_interface/test/ei_format_SUITE_data/ei_format_test.c
- lib/erl_interface/test/ei_tmo_SUITE_data/ei_tmo_test.c
- lib/inets/test/httpd_SUITE_data/cgi_echo.c
- lib/kernel/test/os_SUITE_data/my_fds.c
Apple Clang 12 in Xcode 12 reports an error for the use of a function without a declaration. This pull request updates C code in test suites to ensure that all functions are declared.
> Eliminate warnings for undeclared functions in C code in test suites

- lib/stdlib/src/filename.erl
- lib/stdlib/test/filename_SUITE.erl
Previously, filename:extension(".gitignore") would
return ".gitignore" as an extension while ".gitignore"
is actually part of the filename. Similarly,
filename:rootname("foo/.gitignore") would return "foo/".
One argument for .gitignore to be treated as filename
is that we should expect this property to hold:
length(filename:split(Path)) =:=
length(filename:split(filename:rootname(Path)))
But that was violated for dotfiles prior to this commit.
Another point of discussion is filenames such as "..ext".
This commit takes the approach that the rootname is "."
and the extension is ".ext".
> Do not consider dotfiles to be an extension

- lib/ssh/src/ssh_cli.erl
- lib/ssh/test/ssh_basic_SUITE.erl
Make sure that ssh_cli module always send exit-status message,
so SSH clients can use it to check for successful command execution.
[https://bugs.erlang.org/browse/ERL-1349](https://bugs.erlang.org/browse/ERL-1349)
> Send exit status from ssh_cli

- lib/stdlib/doc/src/gen_server.xml
The conditions for when an exit signal is emitted by a terminating
gen_server are added in various sections of the gen_server manual:
* In the Description section
* Under start_link/3,4
* Under stop/1,3
* Under Module:init/1
* Under Module:terminate/2
> Documentation of when exit signals are emitted by gen_server

- erts/etc/win32/wsl_tools/w32_path.sh
Add missing quotes.
Caused redist files to not be included in the win32 installers.
> Handle paths with spaces

- lib/tools/src/xref_reader.erl
- lib/tools/test/xref_SUITE.erl
- lib/tools/test/xref_SUITE_data/lib_test/bi.erl
- lib/tools/test/xref_SUITE_data/lib_test/no_bi.erl
This is a special (albeit optional) case - `behaviour_info`, generated internally by Erlang, so should not be part of the analysis' output.
Tools depending on the analysis output (like e.g. `rebar3 xref`) will force the consumer to add exceptions to them, when otherwise not required.
> Suppress `xref` output for "unused export" on behaviour module's `behaviour_info/1`

- lib/compiler/src/Makefile
- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_throw.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/src/compile.erl
- lib/compiler/src/compiler.app.src
- lib/compiler/test/trycatch_SUITE.erl
The runtime scans the stack twice when exceptions are raised; once to build a stack trace, and again to find the appropriate handler (see `handle_error` in `beam_common.c` for an explanation why). While the first scan finishes as soon as it has gathered enough frames (8 by default), it de-duplicates adjacent entries which makes `throw/1` more expensive than just returning up the stack in some scenarios.
This PR improves the performance of `throw/1` by skipping the stack trace if we can prove that it will never be needed. It doesn't do much on its own, but opens up for further optimizations that will eliminate stack scanning altogether.
> compiler: Suppress stack traces for throw/1 when they're not used

- .github/workflows/main.yaml
- Makefile.in
- erts/emulator/Makefile.in
- erts/emulator/beam/jit/beam_asm.hpp
- erts/emulator/beam/jit/instr_common.cpp
- make/run_make.mk
Rename the `clang_format` make target to `format` and add a makefile target called `format-check` that can be used to only check the format without changing anything.
Added call to `make format-check` as part of the github actions workflow.
Ran and committed the changes after running `make format`.
> Add format checks to CI

- lib/stdlib/src/erl_lint.erl
Make the pattern variable tracking in erl_lint somewhat intelligible by removing unused parameters, changing misleading names, and correcting and improving comments.
Note that the Bvt0 argument to pattern_bin() was always [], so there was no point in passing it around the main pattern() loop.
> Simplify lint vts

- lib/ssl/src/dtls_socket.erl
- lib/ssl/src/ssl_connection.erl
- lib/ssl/test/ssl_api_SUITE.erl
Fix for [ERL-1341](https://bugs.erlang.org/browse/ERL-1341).
> Fix ssl:peername/1 (DTLS client sockets)

- lib/common_test/src/ct_run.erl
* When using `release_shell` option, the return is a pid, instead of the usual test return.
* For those cases, just skip that entry and continue result accumulation as usual
As requested in https://bugs.erlang.org/browse/ERL-1335
> Fixes ERL-1335

- lib/os_mon/src/disksup.erl
This PR is resolving issue https://bugs.erlang.org/browse/ERL-1370 and related to https://github.com/NixOS/nixpkgs/issues/99387
Retrieving some details of available disks is implemented via regular `df` command with a hardcoded path to it for all the OSs the Erlang does support.
https://github.com/erlang/otp/blob/master/lib/os_mon/src/disksup.erl#L242
In NixOS the location of `df` command differs from the defined location in [FHL](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). 
Solution: replace the hardcoded path to `df`command with a more flexible way via `env`.
> Fix os_mon application (disksup). replace hardcoded path for 'df' command in linux environment

- lib/stdlib/src/escript.erl
- lib/stdlib/test/escript_SUITE.erl
Fixes [https://bugs.erlang.org/browse/ERL-1338](url)
It's awkward to get the stderr from a spawned executable, so for now escript_SUITE simply merges stderr of the spawned executable with its stdout, which means there's no real change as far as the suite is concerned.  (There's less bogus quoting in one case though.)
All solutions I've seen to retrieving a spawned executable's stderr have involved I/O redirection to a temporary file.  I didn't think Windows would support that, but some searches indicate it does, so I'll investigate that possibility next.
> Escript errors to stderr

- configure.src
- erts/configure.in
- lib/crypto/configure.in
- lib/odbc/configure.in
- lib/wx/configure.in
As discussed in [ERL-1173](https://bugs.erlang.org/browse/ERL-1173).
I'm sure I skipped some duplicates but don't have a consistent way to figure out which ones, so this is on a trial-and-error basis.
---
I did try to skip, for example, the whole `wx` configuration step, but am unable to obtain `--without-wx`. My trial meant I'd skip the whole file since if you don't want `wx` there's no need to configure it (this is my very limited world view of the configuration process, though). Is this a valid approach?
> Fix configuration procedure log

- lib/kernel/src/erl_epmd.erl
The spec for erl_epmd:listen_port_please/2 is overly strict, resulting in
dialyzer errors for the valid snippet:
[Name, Host] = string:split(atom_to_list(node()), "@"),
R = erl_epmd:port_please(Name, Host),
This commit relaxes the spec for listen_port_please to match that of port_please
> Expand the spec for erl_epmd:listen_port_please/2

- erts/emulator/beam/bif.tab
- erts/emulator/beam/erl_bif_os.c
- lib/kernel/doc/src/os.xml
- lib/kernel/src/os.erl
- lib/kernel/test/os_SUITE.erl
https://bugs.erlang.org/browse/ERL-1332
`os:env/0` returns all environment variables in a tuple list `[{VarName, Value}]`
The same as the undocumented `os:list_env_vars/0`, but with a better name.
A nicer format than the existing os:getenv/0 which returns a list of strings `"VarName=Value"`.
> Add os:env/0

- lib/stdlib/doc/src/supervisor.xml
Obvious typo, "childrens" is not a word
> Typo fix in supervisor.xml

- erts/doc/src/escript_cmd.xml
Escript allows the user to use the (undocumented) `ESCRIPT_EMULATOR`
environment variable to specify which emulator binary to use, but
there is no corresponding way to select the emulator flavor. This
patch adds support for selecting the flavor by setting the
`ESCRIPT_FLAVOR` environment variable. Setting `ESCRIPT_FLAVOR` to
`<flavor>` will add `-emu_flavor <flavor>` to the emulator command
line when running escripts.
> escript: Allow the user to request a particular emulator flavor

- erts/emulator/nifs/common/prim_file_nif.c
- lib/kernel/test/prim_file_SUITE.erl
file:read_file/1 and prim_file:read_file/1 retrieve the file size before opening the file, and then only read as much data as that file size stated.  Between the file size retrieval (stat() on Unix) and the open, the file may get renamed to a different, larger one.  This causes read_file to return truncated data.  Fixed by retrieving the file size from the open file handle instead.
Fixes https://bugs.erlang.org/browse/ERL-1376.
> Read file rename race

- lib/stdlib/src/uri_string.erl
- lib/stdlib/test/uri_string_SUITE.erl
This change fixes the handling of deep lists in the path component when using ```uri_string:recompose/1```.
```erlang
"//example.com/foo" =
uri_string:recompose(#{host => "example.com",
path => ["/", "foo"]}),
```
> Fix handling of deep lists in path component (uri_string:recompose/1)

- lib/dialyzer/src/dialyzer_dataflow.erl
Function was included twice, no change in behavior to test
> remove duplicated t_inf_list/3 from include

- lib/stdlib/src/erl_tar.erl
- lib/stdlib/test/tar_SUITE.erl
While one could argue that given an uncompressed binary with the compressed flag should fail, earlier OTP versions implicitly supported this behaviour, so this commit adds it back.
This fixes a regression from #2802. /cc @jhogberg 
Thanks @wojtekmach for the report.
> Handle uncompressed binaries given as compressed to erl_tar

- lib/stdlib/doc/src/Makefile
- lib/stdlib/doc/src/part.xml
- lib/stdlib/doc/src/uri_string.xml
- lib/stdlib/doc/src/uri_string_usage.xml
- lib/stdlib/src/uri_string.erl
- lib/stdlib/test/property_test/uri_string_recompose.erl
- lib/stdlib/test/uri_string_SUITE.erl
This PR intends to improve the API of the ```uri_string``` module and adds a new chapter (Uniform Resource Identifiers) to stdlib's Users' Guide.
- ```uri_string:normalize/1``` is changed to only decode those percent-encoded triplets that correspond to a character in the unreserved set.
```
unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~" 
```
- A new function ```uri_string:percent_decode/1``` is added for decoding percent-encoded triplets in URI components.
- New utility function ```uri_string:allowed_characters()``` added for listing the allowed characters in each major URI component, and also in the most important characters sets.
```erlang
1> uri_string:allowed_characters().
[{scheme,"+-.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"}, …
```
> stdlib: Improve API and documentation of uri_string

- lib/stdlib/src/gen_statem.erl
- lib/stdlib/test/gen_statem_SUITE.erl
The previous solution was flawed because it immediately inserted
a zero time-out in the event queue, and tried to compensate for
when and how they would not fire due to state changes and other
events.
That implementation did not cut it e.g when combining a state
time-out with inserting an event, and in the new state, with
the state time-out, changing states.  Then the state time-out
was not cancelled because it was already in the event queue,
and it arrived in a later state.
This commit changes the implementation into having a dedicated
queue for zero time-outs, from which events are extracted
as from the process mailbox, but before the process mailbox.
Now when cancelling a time-out, for any reason, automatic
or explicit, a zero time-out can be removed from this queue
as it would have …
> Implement zero time-outs with dedicated queue

- lib/kernel/include/logger.hrl
- lib/kernel/test/logger_SUITE.erl
When a module has local apply/3 function, logging macros
do not work correctly due to "ambiguous call of overridden pre
R14 auto-imported BIF apply/3"
> logger.hrl: use fully qualifier call to erlang:apply

- erts/emulator/beam/erl_alloc.c
- erts/emulator/beam/erl_drv_thread.c
- erts/emulator/beam/erl_init.c
- erts/emulator/sys/unix/sys_time.c
- erts/etc/common/erlexec.c
- erts/lib_src/common/ethr_aux.c
- lib/erl_interface/src/connect/ei_connect.c
- lib/tools/c_src/erl_memory.c
This is just a very minor issue.
erlang contains some calls to strerror where the result is assigned to a char *. However, according to the strerror specification, the
string returned by strerror should never be changed, so I think it would be better to use const char * instead.
Philipp
> Since the string from strerror should never be modified, use const.

- lib/wx/api_gen/wx_gen.erl
- lib/wx/api_gen/wx_gen_erl.erl
So we can diff the API with future re-writes.
> Write the api footprint

- lib/wx/c_src/wxe_ps_init.c
While implementing #2808  I've adapted the same process used in wxe_ps_init.c for macos but there is a bug in that macos code:
```
int res = erl_drv_getenv("WX_APP_TITLE", app_title_buf, &app_len);
if (res >= 0) {
app_title = app_title_buf;
} else {
app_title = NULL;
}
```
and it should just be `if (res == 0)` because when res > 0 the `app_title_buf` variable is being used uninitialized. According to this impl of `erts_osenv_get_native()` in erl_osenv.c
```
int erts_osenv_get_native(const erts_osenv_t *env,
const erts_osenv_data_t *key,
erts_osenv_data_t *value) {
env_rbtnode_t *node = env_rbt_lookup(env->tree, *key);
if(node != NULL) {
if(value != NULL) {
if(node->value.length > value->length) {
return -1;
}
sys_memcpy(value->data, node->value.data, node->value.length);
value->length = …
```
> Fixed using unitialized variable when environment var is too big

- lib/wx/c_src/wxe_main.cpp
For additional windows in GTK this replaces the default "Erlang" displayed title when the environment variable WX_APP_TITLE is specified. In the current version this happens already on macOS but is not effective on GTK. This change adds the same effect for GTK by changing the initial parameter of wxEntry() based on the environment variable.
@dgud fyi wxWidgets maintenance fix
> Using WX_APP_TITLE for wxEntry()

- lib/compiler/src/compile.erl
If you tried to use a {listing, Fun} pass, it would be consumed by the {listing, Ext} clause before it reached the generic {_, Fun} clause further below (and similar for any other case where the name would match even though the second element is a fun).
> compile: make select_passes clause order match the comment text

- lib/compiler/src/v3_core.erl
- lib/compiler/src/v3_kernel.erl
Prior to this patch, v3_core would expand each
character in a string to an integer. This made
patterns with large strings to become large and
expensive ASTs. For example, this file:
https://gist.github.com/josevalim/694c1799143fcf25e43aa27e3e11e4c1
would grow its representation in more than 10x!
This commit makes it so we squeeze strings into
large integers also when building patterns,
mimicking an optimization that we already did for
strings outside of patterns.
Before this patch:
expand_records   :  0.077 s   19988.7 kB
core             :  2.552 s  373294.0 kB
sys_core_fold    :  0.868 s  370212.9 kB
sys_core_alias   :  0.237 s  370212.9 kB
core_transforms  :  0.000 s  370212.9 kB
sys_core_bsm     :  0.677 s  370212.9 kB
v3_kernel        :  2.662 s  169439.0 kB
After this patch:
core …
> Also collapse strings in patterns

- lib/stdlib/doc/src/queue.xml
- lib/stdlib/src/queue.erl
- lib/stdlib/test/queue_SUITE.erl
The first commit in this PR introduces a `fold/3` function for the `queue` module. Up to now, this had to be done by converting a queue to a list and folding over that, which is both cumbersome and more performance-intensive (`O(length(Rear))` for the conversion, and `O(length(List))` for the fold over that list) than a fold over the internal lists making up the `Rear` and `Front`, inside the `queue` module (`O(len(Queue))`, roughly equivalent to only `O(length(List))`). The queue is traversed in queue order (front to rear), which is what would be expected.
<hr />
The second commit in this PR addresses a "glitch" in the `filter/2` function, namely that while returning `true` or `false` from the filter function is semantically equivalent to returning `[Item]` or `[]` respectively, the …
> Fold over queues

- lib/stdlib/doc/src/gen_statem.xml
Exit signals are described in various sections of the gen_statem manual where stopping is documented:
* In the Description section, including a link to Receiving Exit Signals in the Reference Manual
* Under Types: state_callback_result (stop, stop_and_reply)
* Under start_link/3,4
* Under stop/1,3
* Under Module:terminate/3
This is a follow-up on #2771.
> Documentation of exit signals emitted by gen_statem

- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/src/beam_ssa_bsm.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_ssa_recv.erl
Many functions in beam_ssa would receive labels
and compute the rpo from labels. This lead to
multiple calls to rpo which can be inefficient
in some scenarios.
This commit changes these functions to receive
the rpo as argument and shares them in the most
trivial cases found so far.
beam_ssa:fold_po/2 was removed as it is not used
anywhere. The remaining functions will be converted
in another PR.
> Expliticly pass in rpo as arguments

- lib/compiler/src/cerl_trees.erl
- lib/compiler/src/sys_core_alias.erl
- lib/compiler/src/v3_core.erl
Skip literals on v3_core and sys_core_alias
When compiling code with large amount of literals,
there was a performance degradation between Erlang/OTP
22.3 and 23.1.
For example, the gisted code below takes 10 extra seconds:
https://gist.github.com/josevalim/694c1799143fcf25e43aa27e3e11e4c1
In particular, the v3_core pass went from 1.8 seconds to 3.2
seconds. When profiling the pass, we could see a lot of time
was was spent on the new lowering pass in v3_core. In particular,
cerl_trees:mapfold/3 would show up in profilers:
cerl_trees:mapfold/4   3220377    19.14   2447684  [0.76]
Which is quite curious, as the linked code does not trigger
any of the lowering optimizations.
Under further analysis, this happened because cerl_trees would
traverse literals, which is a waste given there is no …
> Skip literals on v3_core and sys_core_alias

- erts/etc/unix/cerl.src
RR version >= 5.4 has replaced the `--ignore-nested` flag with
`--nested=ignore`. Make cerl autodetect the new flag and fall back on
the old `--ignore-nested` flag if it is not supported.
> cerl: Support RR >= 5.4

- lib/compiler/doc/src/compile.xml
- lib/compiler/src/compile.erl
This is a very localised enhancement (i.e. I didn't improve the whole `compile.xml`). If there's anything not "too out of context" that you'd like me to fix in the same pull request, let me know.
> Improve compile:forms/2 doc with newly exported type

- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/src/beam_ssa_bsm.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
This patch finishes the work started on 0ce3fb91
by explicitly passing RPO to the remaining functions
in beam_ssa. This commit avoids the double RPO
computation in 4 other occasions.
> Explicit pass RPO to beam_ssa functions (cont)

- erts/emulator/beam/erl_term.h
- erts/emulator/test/erts_debug_SUITE.erl
Fixes regression introduced by ccfc6b3. offsetof returns value in bytes, while EXTERNAL_THING_HEAD_SIZE is expected to be in words.
> erl_term.h: correct size of ExternalThing

- erts/emulator/beam/beam_emu.c
- erts/emulator/test/trace_call_time_SUITE.erl
Since 25fe3fb23c594d735cb6ebae120910e44f0cdae4, trace parameters always live next to their CP so we don't need to skip any "stack frame variables." This was generally harmless since the first argument was usually a CP anyway, but we'd skip too much when it wasn't. For example when return time tracing was used, and we didn't have any prev_info:
```
E -= 2;
E[1] = prev_info ? make_cp(erts_codeinfo_to_code(prev_info)) : NIL;
E[0] = (Eterm) beam_return_time_trace;
c_p->stop = E;
```
The loop to skip stack frame variables would thus skip the trace CP (which is OK) and then skip the `prev_info` (which is `[]`), and then we'd add one to skip what we thought was `prev_info`, ruining the scan.
> erts: Fix exception handling during tracing

- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/ssl_internal.hrl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/ssl_api_SUITE.erl
This commit provides the ability to retreive keylog information that
can be used by tools (e.g. Wireshark) to decrypt TLS connections.
The information returned by the keylog connection_information item is
a list of keylog items that can be written to a file or otherwise
communicated to a tool understanding keylog.
For example:
```
{ok, [{keylog, KeylogItems}]} = ssl:connection_information(S, [keylog]).
file:write_file("/tmp/key.log", [[KeylogItem,$\n] || KeylogItem <-KeylogItems]).
```
For TLSv1.3 connections more information must be stored in the connection state. In this case the initial `ssl:listen` or `ssl:connect` call must include the option `{keylog, true}`
For TLSv1.2 connections, the required information could be obtained from the existing `master_secret` and `client_random` …
> Implement NSS-style keylog in ssl:connection_information/2

- erts/doc/src/erlang.xml
- erts/emulator/Makefile.in
- erts/emulator/beam/atom.names
- erts/emulator/beam/dist.c
- erts/emulator/beam/erl_alloc.c
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/external.c
- erts/emulator/sys/unix/sys_drivers.c
- erts/emulator/test/mtx_SUITE.erl
- erts/epmd/src/Makefile.in
- erts/etc/common/Makefile.in
- erts/etc/unix/cerl.src
- erts/include/internal/ethread.h
- erts/include/internal/i386/ethr_dw_atomic.h
- erts/lib_src/Makefile.in
- erts/preloaded/src/erlang.erl
- erts/preloaded/src/init.erl
- erts/test/utils/gccifier.c
- lib/erl_interface/src/Makefile
- lib/erl_interface/src/Makefile.in
- lib/erl_interface/test/all_SUITE_data/gccifier.c
- lib/tools/c_src/Makefile.in
- lib/tools/c_src/erl_memory.c
- lib/tools/test/emem_SUITE.erl
- make/run_make.mk
Purify has not been used on the emulator for a decade and is now just cluttering make files and some source code.
Build targets removed: purify, quantify and purecov.
> otp: Remove all purify support

- erts/doc/src/erlang.xml
- erts/emulator/beam/dist.c
The `monitor_node/2` BIF raises a `badarg` exception when the
node is not alive. This commit changes `monitor_node/2` to
instead raise a `notalive` exception in that situation.
Specification
-------------
Currently, `monitor_node/2` raises a `badarg` exception when
the node is not distributed (not alive):
1> monitor_node(node@host, true).
in function  monitor_node/2
called as monitor_node(node@host,true)
Change that to raise a `notalive` exception:
1> monitor_node(node@host, true).
** exception error: the node cannot be part of a distributed system
in function  monitor_node/2
called as monitor_node(node@host,true)
2> catch monitor_node(node@host, true).
{'EXIT',{notalive,[{erlang,monitor_node,[node@host,true],[]}, …
> monitor_node/2: Raise 'notalive' instead of 'badarg'

- lib/compiler/src/v3_core.erl
- lib/compiler/test/warnings_SUITE.erl
- system/doc/reference_manual/expressions.xml
Compiler warnings for unused variables can be suppressed by prefixing
the variable name with an underscore (`_`). Other kind of warnings
(such as ignoring the result of an expression without side effects)
can only be ignored by assigning (or, strictly speaking, matching) the
result of the expression to the anonymous variable (`_`). This
distinction can be confusing, so this commit teaches the compiler to
suppress all warnings when an expression is assigned to a variable
that begins with an underscore.
Specification
-------------
foobar(A, B, C) ->
{ignore,A},
element(1, B),
ok.
There will be three compiler warnings:
module.erl:4: Warning: variable 'C' is unused
module.erl:5: Warning: a term is constructed, but never used
module.erl:6: Warning: the result of the …
> Allow "underscore variables" to suppress all warnings

- erts/emulator/beam/erl_term.h
- erts/emulator/beam/jit/beam_asm.hpp
- erts/etc/unix/etp-commands.in
This PR shaves off a few bytes here and there by making the empty list constant (`NIL`) positive:
Before:
```
; When NIL is negative, we need to sign-extend it when moving to a 64-bit register,
; which uses 7 bytes:
;
; 48 c7 c0 fb ff ff ff
mov rax, -5
```
After:
```
; When NIL is positive, we can use the fact that a move to the lower 32 bits of any
; 64-bit register implicitly zeroes its upper 32 bits. This uses 5 bytes instead:
;
; b8 3b 00 00 00
mov eax, 0x3b
```
> jit: Make mov_imm(Gp, NIL) shorter

- make/configure.in
This change is needed to ensure that we're able to configure make on macOS 11.0.1.
A smilar fix was applied for 11.0 in #2700 
Main changes:
- Fix the integer macOS version correctly for the build version check
Verified via ./otp_build tests
> Fix the make configuration for macOS 11.0.1

- lib/kernel/src/inet_db.erl
Prior to this patch, if 5 seconds passed and
the resolv_conf or hosts_file were up to date,
we would continue to check for the file update
on every inet_res or inet_hosts operation.
This PR makes sure that the timer is updated
even if the file is up to date, so we check
again only in the next 5 seconds.
This addresses a performance regression on
inet_res which would lookup every 5 seconds
on Erlang/OTP 22 but performs it on every
request after 5 seconds on Erlang/OTP 23.
> Reset inet_db timer even if file is up to date

- lib/kernel/doc/src/code.xml
- lib/kernel/doc/src/eep48_chapter.xml
- lib/stdlib/doc/src/shell_docs.xml
- lib/stdlib/src/shell_docs.erl
- lib/stdlib/test/shell_docs_SUITE.erl
In order to render documentation without the presence of a correctly configured I/O group_leader we have to be able to configure how the shell docs should be rendered.
This problem was reported in https://github.com/erlang-ls/erlang_ls/issues/754
> Add rendering config to shell_docs

- lib/kernel/src/erl_epmd.erl
This is a followup PR to https://github.com/erlang/otp/pull/2616 which fixed the type spec for port_please/3, but missed the incorrect `{ok, _, _}` term in port_please/2 which should be `{port, _, _}`.
> port_please/2 returns {port, _, _}, not {ok, _, _}

- erts/etc/common/erlexec.c
- erts/test/erlexec_SUITE.erl
By specifying `-args_file` in a supplied `vm.args` it is possible to
extend the VM options, the path supplied is relative to the current
working directory. Improve the error message when unable to open such
a file to ease the process.
> erlexec: Improve error message when unable to open included args_file

- lib/kernel/src/logger_formatter.erl
- lib/kernel/test/logger_formatter_SUITE.erl
This small change will simplify integration of Erlang's logger with
Elixir applications where users are more accustomed to usage of binaries
instead of char lists as a "string" type.
> Allow binaries as parts of logger_formatter template

- make/configure.in
There is a version check in one of the configure scripts that
tests the version of macOS to ensure that the executables that
are built can be run on the same computer that built them.
The reason for this test has been lost in the mists of time.
Presumably there was a good reason for the test when it was
first added.
Since the test recently has become more complicated because of the
introduction of macOS 11.0 and 11.0.1, and is incorrect for some
versions of macOS, remove it. If there turns out that the version test
would be useful, it can be added back later (but in a less buggy way,
preferably using `awk` instead of `sed` to make the version parsing
simpler and more accurate).
> macOS: Remove version check in configure script

- erts/doc/src/erlang.xml
- lib/stdlib/src/io_lib_format.erl
- lib/stdlib/test/io_SUITE.erl
- system/doc/reference_manual/data_types.xml
The pretty printer of floats may round the float value before printing
as long as the following property holds (X is a float value):
X=:=erlang:list_to_float(lists:flatten(io_lib:format("~w",[X]))).
This commit makes sure that the rounded digit always appear last, or
just before e if the float is printed using scientific notation. This
is accomplished by always printing using scientific notation if the
number is so large that it might be rounded before the fractional
part.
Before this commit, users could see the following in the Erlang shell:
> 36028797018963970.0.
36028797018963970.0
> 36028797018963970.0 == 36028797018963970.
false
> 36028797018963970.0 == 36028797018963968.
true
36028797018963970.0 is represented as the float value
36028797018963968.0 but the pretty printer rounds it …
> Make printing of floats more user friendly

- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/tls_connection.erl
- lib/ssl/test/tls_api_SUITE.erl
If using active once sockets and the socket is closed and all data is already
delivered it is desirable that ssl:setopts(S, [{active, once}] shall succeed
and an active close message be sent instead of ssl:setopts returning {error, closed}
This how gen_tcp/inet behaves.
Example of client side:
> {ok, S} = ssl:connect("localhost", 9999, [{active, false}]).
{ok,{sslsocket,{gen_tcp,#Port<0.10>,tls_connection,
undefined},
[<0.120.0>,<0.119.0>]}}
> ssl:setopts(S, [{active, once}]).
ok
> flush().
Shell got {ssl,{sslsocket,{gen_tcp,#Port<0.10>,tls_connection,undefined},
[<0.120.0>,<0.119.0>]},
"foo"}
ok
> ssl:setopts(S, [{active, once}]).
ok
> flush().
Shell got {ssl_closed,
{sslsocket,
{gen_tcp,#Port<0.10>,tls_connection,undefined},
[<0.120.0>,<0.119.0>]}}
ok
> ssl:setopts(S, [{active, once}]). …
> ssl: Improve active emulation

- erts/etc/unix/erl.src.src
- erts/etc/unix/start.src
Here is a first step to address [ERL-1323](https://bugs.erlang.org/browse/ERL-1323) by allowing **ROOTDIR** passed as an environment variable in both the _erl_ and _start_ commands. I've followed exactly the same approach and shell syntax as already used for **RELDIR** in [start.src](https://github.com/erlang/otp/blob/master/erts/etc/unix/start.src)
In the context of [ERL-1323,](https://bugs.erlang.org/browse/ERL-1323) this small commit fixes a concrete issue on Android, as it finally allows to run Erlang/OTP on recent OS versions for which it's not possible to know in advance the absolute path of the Erlang runtime anymore. Being able to pass the install location via the **ROOTDIR** environment variable at runtime solves the issue in this case.
I've tested this approach on the following …
> Support ROOTDIR passed as an environment variable in erl and start scripts

- erts/emulator/utils/make_driver_tab
- lib/crypto/c_src/Makefile.in
While investigating the crypto hmac performance loss in [ERL-1400](https://bugs.erlang.org/browse/ERL-1400) I needed to build with crypto and openssl gprof-enabled and statically linked into the VM. That didn't work due to two separate build issues, fixed by this series.
> Allow building VM with static and gprof-enabled crypto NIF

- lib/kernel/src/pg.erl
- lib/kernel/test/pg_SUITE.erl
First two foldl cases keep pids  from removal from gen_server state when they match with whole group.
Fortunately, pg interface APIs get group members from ets, not from nodes in gen_server state, so there's no bugs exposed.
But it makes nodes in gen_server state drift from other nodes, and use unnecessary memory to keep pids which already left.
> pg: fix 'foldl' that keeps remotely left pids from removal.

- lib/stdlib/doc/src/queue.xml
- lib/stdlib/src/queue.erl
- lib/stdlib/test/queue_SUITE.erl
This PR is a follow-up to #2791 which adds 4 new functions to the `queue` module. The new functions perform the same tasks as their counterparts in the `lists` module, but avoid the need to convert queues to lists first, which is both inconvenient and inefficient.
* `queue:all/2`: like `lists:all/2`, checks if all items in a queue satisfy a predicate; processed in queue order to retain the order of side effects of the predicate function
* `any/2`: like `lists:any/2`, checks if at least one item in a queue satisfies a predicate; procesed in queue order to retain the order of side effects of the predicate function
* `delete/2`: like `lists:delete/2`, removes the _first_ occurence of an item from a queue, according to queue order
* `delete_r/2`: there is no counterpart for this in the …
> Add queue:all/2, queue:any/2, queue:delete/2, and queue:delete_r/2

- lib/kernel/src/logger_proxy.erl
Fix bug reported in http://erlang.org/pipermail/erlang-questions/2020-October/100029.html
> Do not crash on late gen_server:call replies

- erts/emulator/beam/erl_term.h
When used as an argument to a variadic function NIL has to have the correct size otherwise it is assumed to be an int which is not what the va_list function expects.
This was broken in: 8b8c7a63030360436f2ee6d6390d120199260823
> erts: Fix NIL to be correct size

- lib/crypto/c_src/otp_test_engine.c
Found with OpenSSL built with address-sanitizer:
ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f848de3b5c4 ...
READ of size 4 at 0x7f848de3b5c4 thread T9 (6_scheduler)
#0 0x7f848fed28ea in engine_table_register crypto/engine/eng_table.c:97
#1 0x7f848fd83dac in ENGINE_register_digests crypto/engine/tb_digest.c:30
#2 0x7f848fd201d1 in engine_register_nif otp/lib/crypto/c_src/engine.c:447
#3 0x556fe2e15de4 in process_main x86_64-unknown-linux-gnu/asan/emu/beam_cold.h:177
#4 0x556fe2db96e7 in sched_thread_func beam/erl_process.c:8496
#5 0x556fe346bd1b in thr_wrapper pthread/ethread.c:122
#6 0x7f8498b886da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
#7 0x7f84988b171e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12171e)
0x7f848de3b5c4 is located 0 bytes to …
> crypto: Fix out-of-bounds read bug in otp_test_engine.c

- lib/stdlib/doc/src/sets.xml
- lib/stdlib/src/sets.erl
- lib/stdlib/test/sets_SUITE.erl
- lib/stdlib/test/sets_test_lib.erl
This pull request adds support for maps in the sets module. According to my [benchmarks](https://github.com/josevalim/sets_bench), using maps is faster in the majority of cases, sometimes by multiple orders of magnitude, and in the few cases it is slower, it is only by 1.1x-1.4x, which can be improved with the steps outlined below. Note that, although we are using maps, the type is still opaque.
---
Fully adopting EEP 50 will require multiple PRs. In particular, following PRs should:
1. Remove cerl_sets
2. ~Incorporate the intersection implementation in #2797~
3. Write intersection, subtract, is_subset, is_disjoint, and from_list as NIFs so `sets` becomes the fastest set implementation in OTP on all possible scenarios
> Initial implementation of EEP 50

- lib/mnesia/src/mnesia_dumper.erl
This PR addresses the very rare but unfortunately existing problem with occassional latencies (up to 250ms) in mnesia operations described in more detail here:
https://bugs.erlang.org/browse/ERL-1423
> Remove potential lag from mnesia_log:log/slog functions

- erts/emulator/sys/win32/erl_win_sys.h
- erts/etc/win32/erl.c
- erts/etc/win32/manifest.xml
- erts/etc/win32/win_erlexec.c
- erts/etc/win32/wsl_tools/vc/ld.sh
Previously only erl werl and beam added the manifest.
Add it to all exe and dll's.
Specificly ./Install.exe that runs after the nsis installer,
needs it if somebody wants to run it manually.
The test runs don't want to elevate to admin for example.
> Add a default manifest for windows

- erts/emulator/beam/emu/arith_instrs.tab
- erts/emulator/beam/emu/ops.tab
- erts/emulator/beam/erl_arith.c
- erts/emulator/beam/global.h
- erts/emulator/beam/jit/beam_asm.hpp
- erts/emulator/beam/jit/instr_arith.cpp
- erts/emulator/beam/jit/ops.tab
- erts/emulator/test/float_SUITE.erl
Before this patch, unary minus "-value" was implemented
as "0 - value" but that is not equivalent for floats when
0.0 is given.
This patch addresses this issue by implementing unary
minus as its own operation and improves the coverage.
> Handle negative zeros on unary minus

- lib/compiler/src/beam_dict.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/test/float_SUITE.erl
There is currently a bug in the compiler where 0.0
is considered a singleton. However, 0.0 can match both
-0.0 and 0.0 which makes this assumption invalid. Here
is a failing test:
float_zero(Config) when is_list(Config) ->
<<16#0000000000000000:64>> = to_fbin(1*0.0),
<<16#8000000000000000:64>> = to_fbin(-1*0.0),
ok.
to_fbin(X = 0.0) -> <<X/float>>.
This commit changes beam_types:get_single_value/1 to not
consider float singletons and therefore not perform constant
propagation.
Furthermore, we also need to instruct beam_asm to encode
0.0 and -0.0 as two distinct literals.
> Do not consider zero floats as singleton

- erts/emulator/sys/common/erl_sys_common_misc.c
- erts/emulator/test/num_bif_SUITE.erl
- lib/stdlib/src/io_lib_format.erl
- lib/stdlib/test/io_SUITE.erl
Both float_to_binary and float_to_list will correctly
print negative zeros when using the scientific mode but
not when using the decimal representation. This patch
makes it consistent to always show negative floats.
This is important because some operations, such as math:atan2,
will return drastically different results if negative zeros
are given compared to positive zeros. Negative zeros also
are encoded differently in bitstrings.
> Fix negative zero to string

- lib/stdlib/doc/src/maps.xml
- lib/stdlib/src/maps.erl
- lib/stdlib/test/maps_SUITE.erl
This PR introduces `filtermap/2` for the `maps` module to combine the common tasks of filtering and mapping a map into one operation.
Compared with two separate calls to `maps:filter/2` and `maps:map/2` as required now, this is both...
* Faster, as the map needs to be "traversed" only once, and there is only one final (internal) `maps:from_list/1` call involved.
* More convenient, as only one call with one filter+map function is needed, instead of two calls with two different functions.
According to a discussion in #2850 ([@IngelaAndin's comment](https://github.com/erlang/otp/pull/2850#issuecomment-733519962)), `filter_map/2` might be a better name in the context of the `maps` module, but I'm really not sure. What do you think?
> Add maps:filtermap/2

- lib/kernel/test/gen_tcp_misc_SUITE.erl
- lib/stdlib/doc/src/rand.xml
- lib/stdlib/src/rand.erl
- lib/stdlib/test/ets_SUITE.erl
- lib/stdlib/test/rand_SUITE.erl
This PR introduces two improvements to the `rand` module:
* The possibility to seed using the current default algorithm, alias `default`
* Two functions that generate binaries: `bytes/1` and `bytes_s/2`
Stating a `default` algorithm has been deemed not needed since when you seed to reproduce a sequence, you must state the algorithm to determine the sequence.  There is at least one scenario, though, when this does not apply; when you _export_ the start seed (to be able to reproduce the sequence) before generating a sequence, and is happy with whatever algorithm that is the default.
This PR makes `seed/1`, `seed/2`, `seed_s/1` and `seed_s/2` accept the algorithm alias `default` for the default algorithm.
The new functions `bytes(N)` and `bytes_s(N, State)` generate a `binary()` of size `N`. …
> rand improvements: seed 'default' and generate binaries

- lib/stdlib/doc/src/ets.xml
https://erlang.org/doc/man/ets.html
From `ets` docs, section **Note**:
```
It should be set to an approximate of the maximum amount of tables used. **This since** an internal table for named tables is sized using this value.
```
Feels like it should be one sentence, or 2 separate, like `This is done since...`.
> fixed typo

- lib/stdlib/doc/src/proplists.xml
- lib/stdlib/src/proplists.erl
- lib/stdlib/test/proplists_SUITE.erl
Converting `proplists` (usually used in older projects/dependencies) from/to `maps` (used in more recent projects) is usually done with `maps:from_list/1`. Generally, you want to use `maps:get/2,3` (or pattern matching) then instead of `proplists:get_value/2,3`.
A conversion via `maps:from_list/1` is fragile in several ways here:
* proplists may contain single atoms as shorthand for `{Atom, true}`. `maps:from_list/1` cannot handle this.
* proplists may even contain _any_ term besides single atoms and key-value 2-tuples. They are accepted and ignored by the proplists API, but `maps:from_list/1` cannot handle those.
* proplists may contain the same keys multiple times with different values, and `proplists:get_value/2,3` will return the _first_ such value for a key. A map created from such a …
> Add map conversion functions to proplists

- erts/emulator/beam/bif.c
- erts/emulator/test/process_SUITE.erl
Calling `process_flag(DeadProcess, Flag, Value)` would leak about 6 words.
However, the only valid `Flag` for proces_flag/3 is `save_calls` which is a tracing/debugging feature.
> erts: Fix small leak in process_flag/3 on dead process

- erts/emulator/beam/erl_message.c
Small memory leak when driver trying to send an invalid term
> erts: Fix leak in erl_drv_send/output_term

- lib/stdlib/doc/src/timer.xml
The Efficiency Guide explains the difference between `timer` and `erlang` timer functions and links to both the modules. It seems likely, though, that somebody looking for timer management will first stumble upon `timer`, which doesn't mention any alternatives. This change links from `timer` to the Efficiency Guide.
> Link from timer module doc to the Efficiency Guide

- erts/emulator/beam/beam_common.c
- erts/emulator/beam/beam_common.h
- erts/emulator/beam/dtrace-wrapper.h
- erts/emulator/beam/jit/instr_bif.cpp
- erts/emulator/beam/jit/instr_msg.cpp
This commit fixes several issues breaking dtrace/systemtap integration.
- beam_common.h: missing assignment operator breaks compilation
- dtrace-wrapper.h: generated erlang_dtrace.h contains #include <sys/sdt.h>,
which has C++ code requiring C++ linkage. However beam_asm.hpp includes
global.h with C linkage, and compilation fails, because <sdt.h> uses C++
templates when __cplusplus is defined. Override linkage to always be
C++ if C++ compiler is used
- debug FLAVOUR could not be built with DTRACE, because beam_common.c and
instr_msg.c do not contain erlang_dtrace.h include, which is needed
for debug builds where inlining is not enabled
- fixed compilation for microstate accounting configured with extra states
> erts: fix dtrace integration and MSACC extras 

- lib/edoc/src/edoc_doclet.erl
`edoc_doclet` has an option `file_suffix` for generating module files with different file extensions than the default `".html"`, e.g. `".htm"`. The generated module index (`modules-frame.html`) did not consider the different file suffix and always used `".html"`, so the links did not work at all. This is fixed by this PR.
<hr />
Judging from `git blame`, this option was introduced in 2009 and has been broken ever since.
Furthermore, the application of this option is incomplete, as only the module files are generated according to this option, but not the overview, the module index itself, and the index (frameset) files. While it appears to be safe to apply the file suffix option to the overview and module index as well, I'm not sure about the index (frameset), as this seems to be used for …
> EDoc: Fix links in module index when using the file_suffix option

- erts/emulator/beam/erl_gc.c
If stack top is changed before calling heap_grow tracepoint,
the stack is not walk-able, because stack bottom points to
old heap, while stack top is already reset to new heap.
> erl_gc: fix dynamic tracepoint for heap_grow

- lib/crypto/configure.in
- lib/megaco/configure.in
- lib/odbc/configure.in
- lib/snmp/configure.in
- make/configure.in
Proposed fix for [ERL-1447](https://bugs.erlang.org/browse/ERL-1447).
Now builds with autoconf version 2.70 although we get lots of warnings for use of obsolete macros. Those will however have to be fixed at a later time.
> Fix uses of AC_CONFIG_AUX_DIRS() in configure scripts

- .github/workflows/main.yaml
See https://marc-stevens.nl/research/md5-1block-collision/ and https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html -- both MD5 and SHA1 are considered "broken" and unsafe for serious use, so this updates the release workflow to also generate SHA256 checksums of the built artifacts.
> Also generate SHA256 checksums for releases

- xcomp/erl-xcomp-x86_64-android.conf
I was fiddling around with [@JeromeDeBretagne's erlanglauncher's fork](https://github.com/JeromeDeBretagne/erlanglauncher) to get a sense of how to use `jinterface` in an Android env. and wanted to use an x86_64 arch. emulator (that project targets ARM but I couldn't get an ARM emulator to work correctly or with a decent performance). I looked at the [OTP doc.](https://github.com/erlang/otp/blob/master/HOWTO/INSTALL-ANDROID.md) and followed it until I figured I didn't have a readily-available `xcomp.conf` for my use case. This pull request presents one, heavily inspired by `erl-xcomp-arm64-android.conf`.
I'm not sure there's a need to add tests for this, or what other elements I'd need changed in the scope of this pull request, but will gladly follow your guidance.
> Simplify configuration of cross-compiling to Android x86_64

- lib/tools/doc/src/fprof.xml
- system/doc/programming_examples/list_comprehensions.xml
- system/doc/programming_examples/records.xml
As proposed in my email from erlang-questions as of 11.12.2020, here is a patch for the documentation.
It replaces usages of the old BIFs without the is_ prefix.
An initial find-grep for the BIFs showed over 300 occurrences, but finally I only found 4 occurrences in the code
examples.
There is no test case, as the patch does not affect real source code. ´
However, I tried the code examples in an erl shell.
dieter
> Replace old test BIFs w/o is_ prefix in documentation code examples

- lib/kernel/doc/src/kernel_app.xml
- lib/kernel/src/group_history.erl
- lib/kernel/test/interactive_shell_SUITE.erl
In addition to 'enabled' or 'disabled' setting, kernel
shell_history variable may be an atom that allows to use
any module as callback module for shell history.
This enabled to fetch shell history from different sources,
for example, cloud-based environment, or other nodes of
a cluster.
This commit also fixes test case that was using -kernel
shell_history 'true' instead of 'enabled'.
> shell history: allow configurable history module

- system/doc/oam/oam_intro.xml
Spotted a typo on https://erlang.org/doc/oam/oam_intro.html#snmp-based-oam(in the last paragraph)
> Typo on https://erlang.org/doc/oam/oam_intro.html#snmp-based-oam

- lib/compiler/test/trycatch_SUITE.erl
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/src/erl_parse.yrl
- lib/stdlib/test/erl_lint_SUITE.erl
Previously, in `try ... catch _:T:T -> ...`, the compiler would treat the two
occurrences of T as separate variables, not adding any check that they have the
same value. Since such a check can be expensive for stacktraces, we don't want
to allow this, just like we don't allow T to be already bound.
This provides a more robust mechanism for handling the stacktrace variable, only
affecting catch-clauses, and sets proper position information on the trace var.
> Detect repeated occurrences of the stacktrace variable in a try clause

- lib/dialyzer/src/dialyzer_dataflow.erl
- lib/dialyzer/test/small_SUITE_data/results/try2
- lib/dialyzer/test/small_SUITE_data/src/try2.erl
In commit 8a9a443a454327cbf17120f63664caa0973e9050 introduced by https://github.com/erlang/otp/pull/2662, a restriction regarding variables in try/catch was lifted, allowing variables bound between `try` and `of` to be used later:
baz() ->
try Bar = 0 of
_ -> Bar
after 0
end.
(In OTP 23 and earlier that would be a compilation error because `Bar` would be considered unsafe.)
The lifted restriction was not properly handled by dialyzer. Attempting to analyze the the following module would crash dialyzer:
-module(dialyzer_bug).
-export([main/0]).
main() ->
try A = foo() of
_ -> A
after ok
end.
foo() -> 1.
https://bugs.erlang.org/browse/ERL-1454
> Eliminate dialyzer crashing when analyzing try/catch

- erts/preloaded/src/init.erl
- lib/kernel/src/logger_simple_h.erl
When the simple logger has been started we are late enough in the boot cycle that we can load any modules that we need in order to handle printing the crash. We wrap the call to logger_formatter in a `try catch` just to make sure that in case we should fail we actually get something printed.
This will effect crash printouts coming in before the kernel application has been successfully started.
> logger: Make logger_simple print pretty reports

- HOWTO/INSTALL-ANDROID.md
Hello,
Here is a proposed update of the Android cross compilation documentation, following the investigations discussed at [ERL-1408](https://bugs.erlang.org/browse/ERL-1408) to support OpenSSL linked statically.
@D4no0 @IngelaAndin @sverker I'm looping you in as you participated in the original discussion, feel free to share your feedback.
Thanks,
Jérôme
> Document how to build for Android with OpenSSL linked statically

- erts/emulator/nifs/win32/win_prim_file.c
This bug was introduced in 7e88dc8e447d46e030971b2f9310c9ee1aa0223a.
> erts: Fix file write error check on windows

- lib/kernel/src/inet_dns.erl
- lib/kernel/test/inet_res_SUITE.erl
The [pointer in the label is 14bit wide](https://tools.ietf.org/html/rfc1035#section-4.1.4) and a typo looks to have used the flag value (3) for the left shift rather than just 1; leading to a limit of 49152 being used rather than 16384.
This bug only shows up for large responses involving several hundred records such as those seen in an AXFR transfer.
This PR resolves this more than 11 year old bug.
> inet_res: fix dns compression encoder for large responses

- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/standards_compliance.xml
- lib/ssl/doc/src/using_ssl.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_cipher.erl
- lib/ssl/src/ssl_connection.hrl
- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/ssl_internal.hrl
- lib/ssl/src/ssl_logger.erl
- lib/ssl/src/ssl_record.erl
- lib/ssl/src/tls_client_ticket_store.erl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/src/tls_handshake_1_3.hrl
- lib/ssl/src/tls_v1.erl
- lib/ssl/test/openssl_session_ticket_SUITE.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
- lib/ssl/test/tls_1_3_record_SUITE.erl
This PR implements the early data feature on the client side. Two new ssl options have been added ```early_data``` and ```max_early_data```. On the client side ```early_data``` is a ```binary()``` to be sent as early_data in a 0-RTT handshake. ```max_early_data``` configures the maximum size of early data accepted by the server. In this early version only the server's session ticket message has been updated to reflect the configured limit on the early data size.
Sample usage with automatic ticket handling:
```shell
openssl s_server -accept 11029 \
-tls1_3 -verify 2 \
-cert certs/server.pem \
-CAfile certs/ca.pem \
-key certs/server.key \
-keylogfile keylog \
-msg -debug \
-early_data \
-no_anti_replay
```
```erlang
early_data_auto() ->
%% First handshake 1-RTT - get session tickets …
```
> Implement early_data for TLS clients

- lib/kernel/doc/src/os.xml
I have done the following changes:
* Deleted the notes about null characters and `=` having been allowed
but are now being rejected. That change happened three years ago.
* Documented that an environment variable name is allowed to contain
`=` as the first character on Windows.
* Removed the vague warnings that "not all invalid characters
necessarily will cause the primitive operations to fail, but may
instead produce invalid results".
* Added a single note to note that the functions will fail with `badarg`
if the arguments contains invalid characters.
> Clarify and simplify documentation for the os module

- scripts/diffable
When testing the JIT code generator it is useful to run it on a large
number of functions. Running `diffable --dis` does just that, but as
disassembly of loaded code is not supported by the JIT, diffable
unfortunately crashes when trying to find labels in the empty output.
This patch changes diffable:find_labels/3 to not crash on empty input,
thus making diffable useful for exercising the JIT's code generator.
> diffable: Stop diffable --dis from crashing when the JIT is used

- erts/emulator/beam/jit/beam_asm.hpp
With this patch, a debug compiled emulator will output a line with
"; CODE_SIZE: <size in bytes>" at the end of the assembler dump files.
> jit: Output size of emitted code in assembly dumps

- lib/crypto/c_src/openssl_config.h
The initial fix for the crypto hmac performance loss (ERL-1400 / PR-2877) added code to automatically disable use of the EVP API for OpenSSL < 1.0.2. However, the EVP API is slow also in 1.0.2 as reported in ERL-1400. This adjusts the limit to < 1.1.0.
Tested on CentOS7 and verified it gives a decent speedup (roughly 30-40%) for the ERL-1400 test case.
> crypto: disable EVP usage also for openssl-1.0.2

- lib/ssl/src/tls_connection.erl
- lib/ssl/src/tls_connection_1_3.erl
When Distribution over TLS is used in large clusters, many
connections are established upfront. All of them have the same
{active_n, 100} setting enabled. When 100 packets are received,
which tends to happen simultaneously for many connections,
a significant spike in RAM and CPU % is observed, due to the way
switching to 'passive' is currently implemented.
Starting with the random number between 1 and 100 helps to spread
the spike and avoid momentarily overload.
This patch also removes unnecessary configuration lookup when
tls_connection is established for Erlang distribution purposes.
> tls_connection: spread RAM/CPU spike induced by flow control

- lib/stdlib/src/erl_abstract_code.erl
- lib/stdlib/test/beam_lib_SUITE.erl
Avoid dialyzer (and other) crash when using -MMD -MF dir/file.d options to generate beam file. Otherwise makedep_side_effect is passed to compiler that tries to create dir/file.d out-of context.
> filter makedep_side_effect

- HOWTO/DEPRECATE.md
- lib/stdlib/scripts/update_deprecations
- system/doc/general_info/DEPRECATIONS
- system/doc/general_info/Makefile
- system/doc/general_info/removed_head.inc
- system/doc/general_info/xmlfiles.mk
This PR adds a page for "Removed Functionality" in the user's guide, listing the things we've removed recently and still raise
warnings about.
> otp: Document previously removed functions

- lib/stdlib/test/stdlib_bench_SUITE.erl
These benchmarks are added to allow a baseline and a benchmarking of #2960
The small digit test should allows to show the discrepancy between ryu and the dragon4 algorithm for "small number of digits in decimal form" doubles. It may be worth to reduce the cutoff to less digits.
> io_lib_format:fwrite_g/1 benchmarks

- lib/erl_docgen/doc/src/doc_storage.xml
- lib/erl_docgen/src/docgen_xml_to_chunk.erl
- lib/kernel/doc/src/application.xml
- lib/stdlib/doc/src/array.xml
- lib/stdlib/doc/src/shell_docs.xml
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/src/shell_docs.erl
- lib/stdlib/test/shell_docs_SUITE.erl
This is needed as edoc (implemented in #2803) can emit such headers.
> Allow h4,h5 and h6 headers in application/erlang+html EEP-48 documentation

- lib/stdlib/src/gen.erl
The atom 'self' is passed instead of the parent's PID, using `self()`
when starting some gen-processes with 'monitor' or 'nolink'.
This patch change so that `self()` is called and the parent argument to
proc_lib will result in a PID instead of the atom 'self'.
I don't know the effect of this change. I assume this is a typo since a
corresponding clause, without `Name`, is using `self()` instead of `'self'`.
> gen: init_it given atom as parent PID

- erts/emulator/sys/common/erl_mmap.h
https://tech.nextroll.com/blog/dev/2020/11/03/chasing-a-perf-regression-erlang.html
> erts: Stop using MADV_DONTNEED when MADV_FREE is unavailable

- lib/tools/src/cover.erl
- lib/tools/test/cover_SUITE.erl
If there was an export in the shape of {clauses, Arity},
cover would attempt to handle it as the {clauses, List}
AST node, leading to the failure below:
```
=ERROR REPORT==== 23-Jan-2021::10:04:20.945556 ===
Error in process <0.159.0> with exit value: {{bad_generator,0},
[{cover,'-patch_code1/2-lc$^0/1-1-',2,[{file,"cover.erl"},{line,2352}]},
{cover,patch_code1,2,[{file,"cover.erl"},{line,2352}]},
{cover,'-patch_code1/2-lc$^1/1-0-',2,[{file,"cover.erl"},{line,2354}]},
{cover,patch_code_tuple,5,[{file,"cover.erl"},{line,2362}]},
{cover,'-patch_code1/2-lc$^1/1-0-',2,[{file,"cover.erl"},{line,2354}]},
{cover,'-patch_code1/2-lc$^1/1-0-',2,[{file,"cover.erl"},{line,2354}]},
{cover,transform,4,[{file,"cover.erl"},{line,1820}]},
{cover,do_compile_beam2,6,[{file,"cover.erl"},{line,1762}]}]}
``` …
> Fix cover bug when there is an export named clauses

- lib/edoc/src/edoc_macros.erl
This makes them equal to the builtin ones, and allows for neat things
like linking to the offical docs page:
```erlang
man_doc_macro(MacroArg, _Line, _Env) ->
{ok, Pattern} = re:compile("([^:]+):([^/]+)/(\\d+)"),
{match, [Module, Function, Arity]} = re:run(
MacroArg, Pattern, [{capture, all_but_first, binary}]
),
lists:flatten(io_lib:format(
"<a href=\"https://erlang.org/man/~ts.html#~ts-~ts\"><code>~ts</code></a>",
[Module, Function, Arity, MacroArg]
)).
```
---
Which allows for:
```erlang
%%% {@man maps:merge/2}
```
To output:
```html
<a href="https://erlang.org/man/maps.html#merge-2"><code>maps:merge/2</code></a>
```
> EDoc: Allow user defined macros to be functions

- lib/compiler/src/beam_kernel_to_ssa.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_ssa_recv.erl
- lib/compiler/test/bs_construct_SUITE.erl
There is a convention in SSA code that an instruction that can fail
must be immediately followed by a `succeeded:Kind` instruction. For
example, a BIF call in a body would look like this:
Result = bif:Bif Arg, ...
Bool = succeeded:body Result
br Bool, ^Success, ^Fail
Because the `bs_put` instruction does not have any return value,
we did not originally follow the failure convention, but instead
made it behave like a guard test:
Bool = bs_put Type, ...
br Bool, ^Success, ^Fail
That saves an instruction, but it necessitates special handling
of `bs_put` in some optimizations. To avoid that special handling,
change the representation of `bs_put` to (in a body):
Result = bs_put Type, ...
Bool = succeeded:body Result
br Bool, ^Success, ^Fail
Or (in a guard):
Result = bs_put Type, ...
Bool = …
> Make the SSA instruction bs_put conform to failure conventions

- lib/jinterface/java_src/com/ericsson/otp/erlang/OtpErlangExternalFun.java
Not being able to access the internals of OtpErlangExternalFun is problematic.
The real use case: performing some analysis of Core Erlang (cerl) from inside java/scala - the construct `fun module:fun/arity` is represented as "itself", and when accessing cerl forms from jinterface - it's represented as OtpErlangExternalFun correspondingly.  Unfortunately, - the internals are private, - which makes some forms of Erlang core not analysable through jinterface.
Also, - since all `module`, `function` and `arity` fields are final/immutable - it doesn't make much sense to hide/incapsulate them.
> jinterface: make OtpErlangExternalFun transparent

- lib/stdlib/doc/src/gen_server.xml
- lib/stdlib/src/gen_server.erl
The value or the usage of `{continue,Continue}` is not explained on the documentation of `Module:init/1`. Although the meaning of `{continue,Continue}` and `handle_continue/2` are explained at the beginning of the gen_server documentation, I believe the context is lost if one is only reading the documentation of the individual functions, instead of reading the documentation for the entire module.
In the same vein, if one is reading the code for `gen_server`, the term `Timeout` might be confusing, because it can also refer to other values (`hibernate` or `continue`).
> Explain {continue,Continue} in gen_server:Module:init/1 doc

- lib/stdlib/scripts/update_deprecations
`./otp_build update_deprecations` only looks for deprecations and removals in applications that have been built, with silly results for those that aren't. This PR makes the script bail out on incomplete builds.
> otp: Require complete build when updating deprecations

- lib/compiler/doc/src/compile.xml
- lib/compiler/src/compile.erl
- lib/stdlib/src/erl_compile.erl
This makes life easier for people implementing languages on top of Erlang, allowing them to easily test things and also skipping the normal linter when they know they already have done their own linting. This removes the need for complicated workarounds.
> Make compiler accept abstract format as input

- lib/compiler/src/compile.erl
- lib/compiler/test/error_SUITE.erl
- lib/compiler/test/warnings_SUITE.erl
- system/doc/general_info/removed_24.inc
- system/doc/general_info/scheduled_for_removal_24.inc
Having an latin-1 encoded Erlang source file without an explicit
"coding: latin-1" comment was deprecated in OTP 23. Turn invalid
encoding into an error.
> Stop allowing latin-1 files without an explicit comment

- lib/stdlib/doc/src/erl_eval.xml
- lib/stdlib/src/erl_eval.erl
- lib/stdlib/test/erl_eval_SUITE.erl
When evaluating snippets with many variables,
sometimes most of the evaluation time is spent
on orddict find, as shown by eprof:
:orddict.find/2  6611650 89.09 1000982    0.15
This patch allows a map to be given to erl_eval,
which is then kept internally as a map and returned
as map. This improves the performance in some cases
by more than 5 times while keeping backwards
compatibility.
> Allow maps as erl_eval bindings

- .github/dockerfiles/Dockerfile.debian-base
- .github/dockerfiles/Dockerfile.ubuntu-base
This adds the `libwxgtk-webview3.0-gtk3-dev` build dependency for wxWebView to the base images. This is a prerequisite to pull in https://github.com/diodechain/otp/tree/letz/wxWebView which only builds if the dependencies are installed. @dgud
> Add wxWebView to base images

- .github/dockerfiles/Dockerfile.debian-base
- .github/dockerfiles/Dockerfile.ubuntu-base
This fixes libwxgtk3.0-dev to be libwxgtk3.0-gtk3-dev and adds the update-alternatives call to the base-image building to select the correct wxWidgets build version. @dgud
> Add libwxgtk-webview3.0-gtk3-dev to base images #2

- erts/doc/src/erl_dist_protocol.xml
- lib/kernel/doc/src/erl_epmd.xml
- lib/kernel/src/erl_epmd.erl
- lib/kernel/test/erl_distribution_SUITE.erl
Currently when the connection from a distributed node to epmd is lost, there is no attempt by the node to reconnect.
This leaves the node invisible to other nodes in the distribution that it is not already connected to.
This PR adds simple reconnect functionality.
If connecting to an epmd without big creation numbers, keep reconnecting until the original creation is received in order to avoid a later invocation of the same node name getting the same creation.
> Reconnect to epmd

- system/doc/top/templates/index.html.src
While at it, also add a blank line after Applications and Modules to
better separate them from Deprecations, Removed Functionality, and
Scheduled for Removal.
> Add link to Removed Functionality on the top page

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/warnings_SUITE.erl
Consider this module:
-module(w).
-export([ll/0, sum/0, tt/0, ignored/2]).
ll() ->
L = {a,b,c},
length(L).
sum() ->
A = a,
B = b,
A + B.
tt() ->
(try nan after whatever end) + 42.
ignored(X, Y) ->
X + Y,
ok.
When compiling this module using https://github.com/erlang/otp/pull/3020,
the following warnings are emitted:
w.erl:6:5: Warning: this expression will fail with a 'badarg' exception
%    6|     length(L).
%     |     ^
w.erl:11:7: Warning: this expression will fail with a 'badarith' exception
%   11|     A + B.
%     |       ^
w.erl:14:34: Warning: this expression will fail with a 'badarith' exception
%   14|     (try nan after whatever end) + 42.
%     |                                  ^
w.erl:17:7: Warning: the result of the expression is ignored (suppress the warning by assigning …
> Reduce confusion by rephrasing some compiler warnings

- erts/doc/src/erlang.xml
Expand and update parts of the erlang module docs
> Erlang doc fixes

- lib/stdlib/src/shell.erl
- lib/stdlib/test/shell_SUITE.erl
Previously the `rr/1` shell function failed with the below error when
called for a module which was loaded from an archive or escript archive,
because `beam_lib:chunks` uses regular `file:open/2` to read from the
file. Now `erl_prim_loader:get_file/1` is used which supports file paths
in archives.
```
{error, beam_lib, {file_error,"<path_to_archive>/test_app.ez/test_app/ebin/test.beam", enotdir}}
```
> shell: read records from module in escript/archive

- erts/test/erlc_SUITE.erl
- lib/compiler/doc/src/compile.xml
- lib/compiler/src/Makefile
- lib/compiler/src/compile.erl
- lib/compiler/src/compiler.app.src
- lib/compiler/src/sys_messages.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/bad_enc.erl
- lib/compiler/test/compile_SUITE_data/col_lat1.erl
- lib/compiler/test/compile_SUITE_data/col_utf8.erl
- lib/debugger/test/int_SUITE.erl
- lib/stdlib/test/escript_SUITE.erl
Provides one or more additional lines of context for compiler messages,  showing the relevant source code with the error position indicated by ^, like this:
```
foo.erl:13:10: variable 'X' is unbound
%   13|     case X of
%     |          ^
foo.erl:18:16: illegal guard expression
%   18| foo(A, B) when is_lit(A), is_list(B) ->
%     |                ^
foo.erl:23:22: function bar/1 undefined
%   23|             {ok, {H, bar(T)}}
%     |                      ^
foo.erl:27:5: record foo undefined
%   26| bar(X, Y) ->
%   27|     #foo{a = baz(X, Y),
%     |     ^
%   28|          b = f(),
%     | ...
%   31|          y = false,
%   32|          z = true}.
```
These long messages can be suppressed with the 'brief' compiler option.
The message formatting code is moved out to a separate module. …
> Quote source as part of error messages

- lib/dialyzer/doc/src/dialyzer.xml
- lib/dialyzer/src/dialyzer.erl
- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_cl.erl
- lib/dialyzer/src/dialyzer_cl_parse.erl
- lib/dialyzer/src/dialyzer_gui_wx.erl
- lib/dialyzer/src/dialyzer_options.erl
- lib/dialyzer/test/line_SUITE_data/dialyzer_options
- lib/dialyzer/test/line_SUITE_data/results/trec
- lib/dialyzer/test/line_SUITE_data/src/trec.erl
- lib/dialyzer/test/small_SUITE_data/dialyzer_options
Since PR 3006 column numbers are by default included in abstract code,
which implies that Dialyzer includes column numbers in warnings. This
can be a problem for tools using Dialyzer, such as Rebar3.
It does not suffice to say that all analyzed files are to be compiled
with `{error_location, line}' (can be set in ERL_COMPILER_OPTIONS)
since Dialyzer can also analyze source code.
Therefore, the `error_location' option is introduced in Dialyzer as
well. The environment variable ERL_COMPILER_OPTIONS is also
recognized.
> dialyzer: Add option 'error_location'

- lib/wx/c_src/wxe_ps_init.c
wxWidgets does it in its init code and it causes harm on newer MacOs's,
i.e. the top-menus doesn't work.
A fix is merged to wxWidgets master branch and will be released as
wxWidgets-3.1.5 until then top menues will not work on mac.
On old macos the old init code in wxWidgets still work and is not
needed in wx driver init.
> Remove old mac init code

- lib/kernel/doc/src/app.xml
- lib/kernel/doc/src/application.xml
- lib/kernel/src/application.erl
- lib/kernel/src/application_controller.erl
- lib/kernel/test/application_SUITE.erl
- lib/reltool/src/reltool.hrl
- lib/reltool/src/reltool_server.erl
- lib/reltool/src/reltool_target.erl
- lib/reltool/test/reltool_server_SUITE.erl
- lib/reltool/test/reltool_server_SUITE_data/sort_apps/z-1.0/ebin/z.app
- lib/sasl/src/systools.hrl
- lib/sasl/src/systools_make.erl
- lib/sasl/test/systools_SUITE.erl
- lib/sasl/test/systools_SUITE_data/d_opt_apps/lib/app1-1.0/ebin/app1.app
- lib/sasl/test/systools_SUITE_data/d_opt_apps/lib/app1-1.0/src/myapp1.erl
- lib/sasl/test/systools_SUITE_data/d_opt_apps/lib/app2-1.0/ebin/app2.app
- lib/sasl/test/systools_SUITE_data/d_opt_apps/lib/app2-1.0/src/myapp2.erl
Both Mix and Rebar allow some applications to be absent
at runtime - sometimes also known as optional dependencies.
However, given optional applications are not stored in .app
resource files, releases do not consider optional applications
in its boot order, leaving it up to chance if an optional app
will be started before its parent.
Users can try to explicitly list optional applications on their
release definition files, but given the order is not enforced,
this manual specification may be reordered when new apps
are added, leaving developers with broken releases.
This PR introduces the "optional_applications" field to .app
resource files. This field must be a subset of the "applications"
field. The reason why it is a subset rather than its own list
of applications is exactly to keep …
> Add optional_applications to .app resource files

- lib/odbc/c_src/odbcserver.c
When a query timeout and makes the client process exit with reason
timeout the odbcserver port pogram is not terminated on port_close/1.
https://bugs.erlang.org/browse/ERL-1448
This happens on CentOS Linux 7.8 x86_64 as well as Red Hat Enterprise Linux 7.8 x86_64
and that is the only platforms I have tested the fix on.
I can reproduce this behaviour with the following code
`
F1 = fun() -> {ok, Ref} = odbc:connect(Conn, Opts),
odbc:sql_query(Ref, SomeQuery, 1)
end,
P1 = spawn_link(F1).
`
And then I run the following command too see that the process is still up
`
ps aux | grep odbcserver
`
> odbc: Fix odbcserver not terminated at timeout

- lib/stdlib/doc/src/maps.xml
- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/src/maps.erl
- lib/stdlib/test/maps_SUITE.erl
This pull request introduces `foreach/2` for the maps module. A basic function to iterate over a map without an accumulator.
> Add maps:foreach/2 function

- lib/ssh/src/ssh_sftpd.erl
- lib/ssh/src/ssh_xfer.erl
I encountered some problems using ssh_sftpd erlang because some sftp clients use the long name field in SSH_FXP_NAME response to display file information in sftp version 3. Looking at documentation ([https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02)), this field is an expanded format for the file name and although not specified by the protocol, the recommended format is similar to what is returned by "ls -l" on Unix systems.
I've made some changes to ssh_xfer and ssh_sftpd modules to add this field in the response for version 3 and it solved the issue for the sftp client I was using, if you could consider taking a look at this PR, I would really appreciate! I tried as much as I could to follow the contribution guide.
> ssh: Add longname field  in sftp version 3

- lib/kernel/doc/src/kernel_app.xml
- lib/kernel/doc/src/logger.xml
- lib/kernel/doc/src/logger_chapter.xml
- lib/kernel/src/logger.erl
- lib/kernel/src/logger_backend.erl
- lib/kernel/src/logger_config.erl
- lib/kernel/src/logger_server.erl
- lib/kernel/test/logger_SUITE.erl
This adds new `kernel` configuration option `logger_default_metadata` that will contain default metadata for processes.  It can be overriden via `logger:set_process_metadata/1`, so if someone is using that form of setting metadata it will remove the defaults.  Changing the defaults after the local process metadata were set will not be reflected in the metadata
Close ERL-1904
> Add support for default metadata to the logger

- lib/kernel/doc/src/logger.xml
- lib/kernel/doc/src/logger_chapter.xml
- lib/kernel/src/logger.erl
- lib/kernel/test/logger_SUITE.erl
This commit allows the logger metadata to be
computed lazily via the logger `msg_fun`.
The `msg_fun` itself can also return `ignore`.
These features are useful when computing the
metadata or if the message should be logged or
not is expensive and you want to do so only
after the log level match.
> Allow metadata and ignore to be computed in logger funs

- lib/stdlib/doc/src/epp.xml
- lib/stdlib/src/epp.erl
- lib/stdlib/src/erl_scan.erl
- lib/stdlib/test/epp_SUITE.erl
epp:scan_erl_form/1 was undocumented, but in use by edoc and there were tests for it.
epp:scan_file/2 can be used to implement e.g. a standalone token level preprocessor pass, like gcc -E.
> Document epp:scan_erl_form/1 and add epp:scan_file/2

- lib/dialyzer/doc/src/dialyzer.xml
- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_cl_parse.erl
- lib/dialyzer/src/dialyzer_options.erl
- lib/dialyzer/test/options1_SUITE_data/results/remote
- lib/dialyzer/test/options1_SUITE_data/src/remote/remotes1.erl
- lib/dialyzer/test/options1_SUITE_data/src/remote/some_known_remote.erl
- lib/stdlib/src/erl_lint.erl
Add option 'no_underspecs'. Fixes GH-4033. Closes GH-3038.
> dialyzer: Add option to be used with attribute -dialyzer

- lib/compiler/src/compile.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/generic_pt.erl
Use of old-style catches in `compile` made some internal errors very
hard to debug. For example, an error in a `format_error/1` function
would result in the following message:
Compiler function compile:compile/3 returned:
{error,function_clause}
This commit revises the error handling to provide more information
when an error occurs. With this change a missing clause in a
`format_error/1` function will printed like this:
*** Internal compiler error ***
exception error: no function clause matching sys_core_fold:format_error(no_clause_match) (sys_core_fold.erl, line 2847)
in function  sys_messages:format_messages/4 (sys_messages.erl, line 43)
in call from sys_messages:format_messages/4 (sys_messages.erl, line 47)
in call from lists:flatmap/2 (lists.erl, line 1254)
in call from …
> compile: Refactor handling of internal errors

- lib/compiler/src/compile.erl
- lib/compiler/src/core_lint.erl
- lib/compiler/src/sys_messages.erl
- lib/compiler/test/core_SUITE.erl
- lib/compiler/test/core_fold_SUITE.erl
- lib/stdlib/doc/src/erl_lint.xml
- lib/stdlib/src/erl_lint.erl
Followup based on https://github.com/erlang/otp/pull/3020.
Makes the compiler use the type declarations in erl_lint as the source of truth for how errors and warnings are represented.
(A minor snag was that the core_lint pass returned a module name (an atom) as the "filename", and the file:filename() type doesn't officially include atoms even if they have always worked.
> Error message types

- erts/emulator/beam/jit/beam_asm.cpp
- erts/emulator/beam/jit/beam_asm.hpp
BeamAssembler::aligned_call() generates a nop (0x90) instruction for
each byte of alignment required. Most modern CPU:s are able to execute
up to four NOP instructions in a cycle [1] during ideal conditions,
but there are no guarantees for the instruction stream generated by
the BEAM loader to be ideal.
Looking at the BEAM code loaded by a typical run of the
`scripts/diffable` benchmark-tool, we find that there are in total
211152 locations requiring alignment. Of those, the number of
alignment bytes needed have the following distribution:
bytes   number
0   43502
1   45703
2  121947
Interesting to note is that almost 80% of the alignments will, without
this patch, issue more than one instruction. Minimizing the number of
issued "useless" instructions is advantageous as it frees up …
> jit: Generate multi-byte NOPs in the way GAS does

- erts/emulator/beam/erl_bif_trace.c
- erts/emulator/beam/erl_process.c
- lib/kernel/test/seq_trace_SUITE.erl
If the seq_trace tuple is on the mature side of the young heap we need to make a copy as otherwise
the tuple will be promited to the old heap before the token which will lead to all kinds of issues.
> erts: Fix seq_trace token gc

- erts/doc/src/erl_cmd.xml
The dots outside `</p>` are rendered in a separate line, which is strange.
> Fix punctuation, wording

- lib/syntax_tools/src/epp_dodger.erl
- lib/syntax_tools/test/syntax_tools_SUITE.erl
- lib/syntax_tools/test/syntax_tools_SUITE_data/epp_dodger_clever.erl
- lib/syntax_tools/test/syntax_tools_SUITE_data/syntax_tools_test.erl
The dodger used to replace a macro with a local function call. That works in
expressions but not in patterns like function heads or catch patterns. Instead
of a function call a tuple syntax is used which works in more places.
This change is motivated by the commonly used `?EXCEPTION` macro
```
try
...
catch
?EXCEPTION(Class, Reason, StackToken) ->
...
end.
```
Open source examples:
https://github.com/devinus/poolboy/commit/5d40cc517edc9bb8ee70756544167b63f66662f0
https://github.com/eproxus/meck/commit/558e925b48ce257b12e381080c851dc49c87d7bb
Fixes ERL-1429
> Handle macros in patterns

- lib/stdlib/src/beam_lib.erl
- lib/stdlib/test/beam_lib_SUITE.erl
- lib/tools/doc/src/cover.xml
- lib/tools/src/cover.erl
- lib/tools/test/cover_SUITE.erl
On a computer without Elixir installed, `beam_lib` would crash when
asked to retrieve the abstract code for a BEAM file produced by the
Elixir compiler. Instead of crashing when the backend module is
missing, return `{error,{missing_backend,BeamFile,Backend}}`.
Also update `cover` to handle the new error from `beam_lib`.
Resolves #4353
> beam_lib, cover: Don't crash when an abstract code backend is missing

- lib/compiler/doc/src/compile.xml
- lib/compiler/src/compile.erl
If the dependency output (generated when the compiler is invoked
with the `makedep` option) contained non-latin1 characters,
the compiler would crash.
To avoid the crash, encode the output in UTF-8.
> Encode generated dependency files in UTF-8

- lib/kernel/src/inet_db.erl
Before this patch, inet_res:getbyname lookups
were centralized through the inet_db process, which
made it a bottleneck on concurrent machines that need
to establish many connections to several hosts quickly.
Since the lookups are now concurrent, the update of
resolve.conf has been changed to use atomic operations
that replace the list of servers and list of names.
The inet_db API has also been cleaned up to no longer
expose operations that delete all searches/namespaces/etc.
Those functions seem safe to remove as they are not
used anywhere within Erlang/OTP. The atomic replace
operations can be made public if desired in the future.
There are also other unused functions which we can
remove in the future.
This is a regen of #2818 and follow up to #2891.
> Do not centralize type/cname lookups through inet_db

- lib/kernel/src/inet6_tcp.erl
- lib/kernel/src/inet_int.hrl
- lib/kernel/src/inet_tcp.erl
- lib/kernel/src/local_tcp.erl
There is no need to bind a socket intended to be used for outgoing
connection. This operation exhaust ephemeral port range, preventing
large number of concurrent outgoing connections.
Omitting bind call also saves an extra trip to kernel.
There is no reliable way to test this, as different platforms have
various limitations on number of file descriptors open, ephemeral
port count and socket allocation mechanisms.
Manual testing can be done using this code:
verify(0) ->
ok;
verify(Remain) ->
receive
{result, {error, Good}} when Good =:= timeout; Good =:= econnrefused ->
verify(Remain - 1);
{result, Any} ->
Any
end.
test_conn() ->
Self = self(),
Expect = 66000, %% this number is guaranteed to be larger than ephemeral port count
[spawn(
fun() ->
Res = catch (gen_tcp:connect(
{10, 20, (Seq …
> inet_tcp, inet6_tcp: do not bind connecting sockets by default

- lib/tools/emacs/erlang-eunit.el
- lib/tools/emacs/erlang-test.el
- lib/tools/emacs/erlang.el
- lib/tools/emacs/erldoc.el
- lib/tools/test/emacs_SUITE.erl
Do not depend on cl. Assume presence of before-save-hook (Emacs 22)
and remove erlang-check-module-name-init. Remove (run-hooks
'erlang-mode-hook) from erlang-mode definition because
define-derived-mode does it already. Replace erlang-caddr with caddr
from Emacs 26.
erlang.el now compiles cleanly in Emacs 24.5, 25, 26, 27.
> tools: Fix emacs compiler warnings (#4451)

- lib/wx/c_src/wxe_memory.h
Missed one in the previous fix.
> Fix C++ 11 extension warning/error

- lib/stdlib/doc/src/re.xml
Issue #4544 pointed out that the `[:ascii:]` character class erroneously matches Latin-1 characters. This PR documents this deficiency since we can't fix it in a backwards-compatible manner.
> re: Document [:ascii:] character class deficiency

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/fun_SUITE.erl
- lib/debugger/test/int_eval_SUITE_data/stacktrace.erl
- lib/stdlib/test/qlc_SUITE.erl
Funs can be used to hide local variables. Example:
a() ->
A = fun() -> A = 21, 2 * A end(),
foo:bar(A).
To avoid the slight runtime cost for such use of funs, teach the
compiler to inline funs that are used only once immediately after
creation.
Resolves #4019
> Inline funs that are immediately used

- lib/kernel/src/error_handler.erl
The `error_handler` module in the Kernel application has a call to the
`int` module in the Debugger application. That call is only there to
make the Debugger work. To avoid that Xref sees Debugger as a
dependency for Kernel, the call to the `int` module is obfuscated in
the following way:
breakpoint(Module, Func, Args) ->
(int()):eval(Module, Func, Args).
int() -> int.
That is, the call will show up as a call to an unknown module in
Xref.
With the improved whole-module type analysis introduced in
294d66a295f6 (#2100), the compiler sees through the obfuscation
and rewrites the code to:
breakpoint(Module, Func, Args) ->
int:eval(Module, Func, Args).
It would be fun to solve this issue by introducing further obfuscations,
but such tricks could stop working in the future when the compiler is …
> Ensure that Xref does not see Debugger as a dependency for Kernel

- lib/kernel/doc/src/inet.xml
The value of the `keepalive` option should be a boolean, but the
documentation states that the default is `disabled` which is not a
boolean.
> Tweak inet keepalive option documentation

- erts/etc/win32/erl.c
Fixed error in buffer size when WSLPATH was available, i.e.
in our test runs.
> Fix erl.exe WSLPATH path addition

- erts/test/otp_SUITE.erl
- lib/erl_docgen/src/erl_docgen.app.src
- lib/ftp/src/ftp.app.src
- lib/kernel/src/kernel.app.src
- lib/ssh/src/ssh.app.src
- lib/ssl/src/ssl.app.src
- lib/tftp/src/tftp.app.src
A test that was supposed to fail when an applications's app file was missing runtime dependencies didn't actually fail when dependencies were missing. (The test case has been broken in exactly five years since 77046ef3d886574.)
This pull request mends the failed test case, and also adds a test case to make sure that the runtime dependencies are correct when Xref is run in the same way as when reltoool runs Xref (that is, in `modules` mode).
When a test case has not been run in five years, some errors have slipped into some app files. This PR adds the missing dependencies. @IngelaAndin and @HansN, could you please take look at the commit that update the app files?
> Fix test of runtime dependencies

- lib/kernel/doc/src/inet_res.xml
- lib/kernel/src/inet_res.erl
This PR changes how the `servfail_retry_timeout` is handled in `inet_res`, so that it is only enforced when a server has answered `servfail`, and only when asking that same server again.
The original implementation was too simplistic and defensive in always waiting for the set time before every retry on the name server list.
> Fix servfail_retry_timeout to only be used when appropriate

- erts/emulator/drivers/common/inet_drv.c
- lib/kernel/test/sendfile_SUITE.erl
Move sendfile dup socker close to stop callback instead of when the read/write error happens.
PR is missing tests for now.
Fixes #4540
> erts: Fix fd leak when an active socket is closed remotely

- lib/kernel/doc/src/disk_log.xml
- lib/kernel/src/disk_log.erl
- lib/kernel/src/disk_log.hrl
- lib/kernel/src/group_history.erl
- lib/kernel/test/disk_log_SUITE.erl
If the value of option 'size' does not match existing wrap log size,
the 'size_mismatch' error is no longer returned, but the size of the
log changed. This applies only if the disk log is not already open.
We have made this incompatible modification to help customers handle
upgrade scenarios.
Fixes GH-4469.
> kernel: Let option 'size' of disk_log:open/1 change size

- lib/ssl/doc/src/ssl.xml
Replace "the the" with a single "the".
> Fix case of doubled word "the"

- lib/crypto/c_src/otp_test_engine.c
This PR fixes the otp_test_engine issue where functions don't depend on the same CPP conditions as their prototypes, leading to broken builds in cases where one is true and the other isn't (#4573).
> Make OpenSSL functions depend on the same conditions as their prototypes

- lib/kernel/src/inet_db.erl
- lib/kernel/test/inet_SUITE.erl
Correct inet:get_rc/0 to return host entries as separate entries
instead of (incorrectly) in a list within the list.  This bug
was introduced by OTP-16487 (fb39f1024) in OTP-23.0-rc1.
This PR fixes the issue GH-4588.
> Fix inet:get_rc/0 host entries

- erts/emulator/beam/erl_bif_trace.c
- erts/emulator/test/trace_SUITE.erl
Leaks a couple of words per erlang:trace/3 call if FlagList argument
- has more than one {tracer, _} in list
- has {tracer, _} followed by invalid option or improper list
- has {tracer, _} in list but fails to seize code write permission
> Fix minor leaks in erlang:trace/3

- lib/kernel/doc/src/inet_res.xml
- lib/kernel/src/inet_res.erl
- lib/kernel/test/inet_res_SUITE.erl
A nxdomain error from a name server does contain the SOA record if
the domain exists at all. This record is usefull to determine a TTL
for negative caching of the failed entry.
> inet_res: add option to include the DNS reply in nxdomain errors

- lib/kernel/src/application_controller.erl
- lib/stdlib/src/ets.erl
The `ets:filter/3` function is undocumented, untested, and broken in the
following ways:
* It only works for named tables.
* It does not fix the table before traversing it.
* It returns a list, not a filtered ETS table. Other `filter`
functions usually return a term of the same type as its input
argument.
Replace its only use in OTP with a call to `ets:foldl/3`.
> Remove undocumented and partially broken ets:filter/3

- lib/stdlib/doc/src/shell_docs.xml
- lib/stdlib/src/c.erl
- lib/stdlib/src/shell_docs.erl
- lib/stdlib/test/shell_docs_SUITE.erl
This pull request augments shell_docs to also
handle any chunk with type of "text". Those will
be rendered as is and allow the Erlang shell to
show the documentation of projects that do not
adhere to the application/erlang+html format.
This is useful because many documentation formats
(Markdown, Asciidoc, etc) are readable in their
native format.
> Show docs from any textual chunk in the shell

- lib/public_key/src/public_key.erl
- lib/public_key/test/public_key_SUITE.erl
Use to_lower_ascii on input.
Fixes #4500
> Make hostname check case insensitive

- lib/mnesia/src/mnesia_loader.erl
This PR optimizes mnesia table loading time (on adding new table copy or just starting another mnesia node) for busy tables (a lot changes per second).
The problem with current implementation is that table receiver first subscribes for table changes, then starts downloading the content of the table from sender and only after receiving whole content of the table handles all the subscribed changes that happened in the meantime. For busy tables this causes receiver message queue to grow very quickly slowing down the downloading process.
The simple solution is to receive all mnesia_table_events that comes during table copying and store them in private ets table for later processing after table is succesfuly downloaded. 
Currently:
After applying changes in this PR:
> Optimise mnesia table loading time for busy tables

- lib/ssl/doc/src/ssl_app.xml
The documentation for the ssl application environment options `protocol_version` and `dtls_protocol_version` was incorrect. They respectively specified `ssl:ssl_tls_protocol()` and `ssl:dtls_protocol()` (which both don't exist) as expected types, and linked both to `ssl:protocol()` (which is `tls | dtls`).
The correct types are `ssl:tls_version()` (or a list thereof) for the `protocol_version` option, and `ssl:dtls_version()` (or a list thereof) for the `dtls_protocol_version` option.
> ssl: fix docs for protocol_version and dtls_protocol_version application environment options

- erts/emulator/sys/unix/sys.c
- erts/emulator/test/os_signal_SUITE.erl
The OTP documentation states that SIGUSR1 causes a crash dump unconditionally.
However, under +B i or +B d, the call to install the SIGUSR1 handler was not
made before this change, causing SIGUSR1 to kill process immediately instead.
Fixes #4552.
> fix: Handle SIGUSR1 even under +B i / +B d

- erts/emulator/beam/utils.c
- erts/emulator/test/map_SUITE.erl
- erts/emulator/test/persistent_term_SUITE.erl
- lib/stdlib/test/ets_SUITE.erl
It is convenient to use erlang:phash2 to determine frag (ETS table)
to use. If salt is the same, both phash2 and ets hashing generate
the same frag/bucket number.
Since ETS hash is not portable, there is no need to keep backwards
compatibility with previous releases.
> ets: use initial salt different from phash2

- erts/doc/src/erl_dist_protocol.xml
- erts/doc/src/erlang.xml
- erts/emulator/internal_doc/NewLinking.tla
- system/doc/reference_manual/processes.xml
Introduce a new link protocol which prevents links from ending up in an inconsistent state where one participant considers itself linked while the other doesn't. This bug has always existed in the distributed case, but has since OTP 21 also existed in the node local case since the distributed link protocol then was adopted also for node local links.
Besides the introduction of the new link protocol, the documentation regarding links and exit signals has also been improved.
* The [new link protocol](https://erlang.org/~rickard/OTP-17127/erts-11.1.8/doc/html/erl_dist_protocol.html#new_link_protocol)
* The [`link/1`](https://erlang.org/~rickard/OTP-17127/erts-11.1.8/doc/html/erlang.html#link-1) BIF
* The [`unlink/1`](https://erlang.org/~rickard/OTP-17127/erts-11.1.8/doc/html/erlang.html#unlin …
> New link protocol

- lib/mnesia/src/mnesia_controller.erl
system_info(is_running) can also return starting and stopping,
error out if that is the case since mnesia is not yet in a state
to connect to new nodes
Fixes #4616
> mnesia: Handle starting and stopping in connect_nodes

- lib/kernel/src/pg.erl
pg:all_local_pids used to use ets:select to scan the entire ets table.
It will be very slow when there is a lot of remote groups.
Changed it to use gen_server state to only scan local groups.
> speed up pg:all_local_pids by using gen_server state

- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/property_test/ssl_eqc_chain.erl
- lib/ssl/test/ssl_eqc_SUITE.erl
> ssl: Correct signature algorithm selection for client certificate verify

- erts/doc/src/erlang.xml
- system/doc/reference_manual/expressions.xml
The documentation for send is missing explanation of aliases in at least the two fixed places.
The Erlang Reference Manual was also missing mention of ports.
Aliases should arguably also be added to the processes section of the reference manual, but this is not included in this PR.
> Add missing documentation for sending to aliases

- lib/stdlib/doc/src/binary.xml
- lib/stdlib/src/binary.erl
- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/test/binary_module_SUITE.erl
- lib/stdlib/test/error_info_lib.erl
I propose to add the `encode_hex/1`, `encode_hex/2` and `decode_hex/1`
functions on the `binary` module.
Dealing with the hex format is frequent in many codebases. At this time,
we all copy-paste similar helpers in our codebases to encode and decode
a hex-encoded binary.
It's why I suggest enriching the binary module with these functions.
I've added these functions on the binary module because it makes sense
to me, and it avoids polluting the global namespace with a new
module. Maybe create a new module called hex, for example, is a better
solution.
I tried as much as possible to follow the contribution guide. Don't
hesitate to tell me if I made a mistake somewhere.
> Add hex encoding fonctions on the binary module

- erts/etc/unix/etp-commands.in
The `etp-aux-work-flags` gdb subroutine had gotten out of sync with the actual
flags defined in erl_process.h.
> etp-commands: fix decoding of aux-work SSI flags

- lib/reltool/src/reltool_target.erl
Remove the current date/time in rel, script and application resource files generated by reltool_target.
Contributes to #4417 (ERL-1445) and #4482 (ERL-1446).
> reltool: Generate files reproducibly

- lib/sasl/src/systools_make.erl
Remove the current date/time in scripts generated by systools_make.
Contributes to #4417 (ERL-1445) and #4482 (ERL-1446).
> sasl: Make release scripts build reproducibly

- lib/kernel/src/net_kernel.erl
Exit was lost in refactoring, causing some errors not to be printed
and the listen loop was aborted.
> Fix lost error handling

- erts/aclocal.m4
This test in the autoconf is both limited, relatively dangerous
(changequote really...) and simply redundant.
If someone built OTP on a machine where perl 4 is the default
they called it on themselves.
Yes i know it will be considered that this test cost "nothing" but it does have a cost. This code is "write only" and that is not a good thing. It is a small change, but i have more coming if this sound like a good idea.
> Remove a test for perl 4

- erts/emulator/beam/erl_init.c
- erts/emulator/beam/global.h
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_perf.cpp
- erts/emulator/beam/jit/x86/instr_bif.cpp
* Flush perf logs after module is added
* This makes `perf top` recognize the correct symbols right away instead of having to wait until the buffer is flushed.
*  Clear msacc state after exiting light bif call
> Perf and msacc JIT fixes

- lib/mnesia/src/mnesia_schema.erl
- lib/mnesia/test/ext_test.erl
- lib/mnesia/test/mnesia_config_test.erl
- lib/mnesia/test/mnesia_test_lib.erl
fixes issue #4525 
The added test case ensures that `backend_init()` is called before `add_alias()` (i.e. it _is_ called the first time), and not called again if another alias is added.
The test case fails if run without the fix in `mnesia_schema.erl`.
> Fix backend_init call check + add test case

- lib/ssl/src/ssl_certificate.erl
- lib/ssl/test/ssl_basic_SUITE.erl
When trying to reconstruct an incomplete chain we must not
use a constructed chain that is a shorter incomplete chain than
the original chain. This might happen if we have a chain that we
will not be able to reconstruct and hence verify. Even though this
is not a problem from a verification point (will fail with unknown_ca anyway)
it could cause different behavior for a verify_fun.
Closes #4682
> ssl: Make sure incomplete chain is a prefix of the new chain candidate

- erts/doc/src/erlang.xml
The `{trace, Pid, exit, Reason}` message is described twice.
> Remove duplicate trace message description

- erts/emulator/beam/beam_bp.c
- erts/emulator/test/trace_call_time_SUITE.erl
Fix #4635
Looks like this bug was "always" there but was exposed by
1f5fb6de3e20cf433606c8d8c33a9813d6337aa2
when E[0] could also be NIL.
The bug only exists in 22.2 <= OTP < 23.0.
> erts: Fix bug in call time tracing

- lib/eunit/src/eunit_surefire.erl
- lib/eunit/test/eunit_SUITE.erl
Hello,
This PR is about eunit, when using surefire reports, creating the output directory if it does not exist. The main use case is for Jenkins or any other CI server.
> eunit: ensure the output directory exist for surefire xml files

- erts/emulator/beam/jit/x86/instr_bif.cpp
8346580b124a recovered extra MSACC states but caused BEAM to dump
core when msacc was switched off due to accidental rewrite of a
variable.
> msacc: fix segfault caused when extra MSACC states are enabled

- lib/stdlib/doc/src/maps.xml
- lib/stdlib/doc/src/proplists.xml
- lib/stdlib/doc/src/queue.xml
In past PRs #2791, #2850, #2900 and #2910, I contributed some new functions to the `queue`, `maps` and `proplists` modules, but forgot to add the `since` information in the documentation.
> queue, maps, proplists: add since information to docs for new functions

- erts/emulator/beam/erl_map.c
- erts/emulator/beam/erl_map.h
- lib/stdlib/test/maps_SUITE.erl
This is the same as 6007bf0f8 but applied to large maps.
> Do not allocate large map when value is the same

- erts/doc/src/erlang.xml
- erts/emulator/beam/bif.c
- erts/emulator/test/process_SUITE.erl
- erts/preloaded/src/erlang.erl
See https://github.com/erlang/otp/pull/4651#issuecomment-806756197
If setting to 0, for example, then the next GC will be fullsweep and the old_heap effectively disabled. An `erlang:garbage_collect()` can force this if necessary.
Would be great to have this in OTP-24.
> Add fullsweep_after support in process_flag/2

- lib/edoc/src/edoc.erl
- lib/edoc/src/edoc.hrl
- lib/edoc/src/edoc_extract.erl
This might happen when `-spec`s are generated conditionally by the preprocessor. EDoc has to be aware of this, so `{preprocess, true}` is required.
> EDoc: suggest {preprocess, true} when redundant spec assertion fails

- erts/doc/src/absform.xml
- lib/compiler/doc/src/compile.xml
- lib/compiler/src/compile.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/column_pt.erl
- lib/compiler/test/compile_SUITE_data/line_pt.erl
- lib/stdlib/examples/erl_id_trans.erl
Fix so that parse_transforms are handed the correct AST without columns if requested by either the user or the parse transform.
Added test to verify that the column stripping works.
> Fix parse transform column handling

- lib/crypto/c_src/atoms.c
- lib/crypto/c_src/atoms.h
- lib/crypto/c_src/cipher.c
- lib/crypto/doc/src/crypto.xml
- lib/crypto/src/crypto.erl
- lib/crypto/test/crypto_SUITE.erl
- changes map returned by cipher_info/1 nif to include an aead attribute
which indictates whether the cipher is AEAD or not
Closes #4491
> Add aead attribute to map from crypto:cipher_info/1

- lib/crypto/configure.in
On Windows, we in rare case try a "last chance" search through the uninstall registry.
This basically reward broken installs and is really brittle code. The crypto configuration code is already complex enough as it is.
> crypto: Remove OpenSSL search through uninstall

- erts/etc/common/erlexec.c
- erts/test/erlexec_SUITE.erl
- lib/kernel/src/erl_distribution.erl
- make/test_target_script.sh
The argument -- is silently added in a number of places in order to seperate arguments from different sources. When checking to see if an argument that erlexec needs to handle is valid we therefore check that it does not start with '-' or '+' which are invalid arguments.
Solves #4624
> erlexec: Add checks that next argument is valid

- .github/workflows/main.yaml
- HOWTO/INSTALL-WIN32.md
- erts/etc/win32/wsl_tools/SetupWSLcross.bat
As per discussion in #3027 @dgud @garazdawi this is adding a windows CI build based on Github Windows image + WSL.
This build skips building the docs intentionally but produces a Windows installer with all apps (including wxWidgets 3.1.4 and WebView2).
It's not signing any of the executables, but it's definitely good enough to see whether everything still compiles and for quick downloading and testing.
Cheers!
> Windows CI build

- erts/doc/src/erlang.xml
The `Object` is always a pid when the target entity is a pid.
It doesn't matter if the pid is local or remote, the `DOWN` message will
always contain the original pid as the `Object` element.
> Correct the `Object` description in `erlang:monitor/2` doc

- erts/emulator/beam/break.c
The **Last calls** section of a crash dump is present, if the `save_calls` process flag is set. If the process sends or receives messages, the section lists events like `send`, `'receive'` or `timeout`. This PR adds '\n' at the end of the line for such events. It helps with parsing it.
In the current version there is [a workaround](https://github.com/erlang/otp/blob/master/lib/observer/src/crashdump_viewer.erl#L1288) for the missing \n characters. After the fix it will only be needed for older versions of the crash dump file.
> Improve the 'Last calls' section included in crash dumps

- erts/etc/unix/etp.py
Improve the functionality of the etp commands for lldb. The most important fix is that continuation pointers on platforms that use GNU-C atomics (such as macOS on M1 Macs) can now be converted to "M:F/A" when printing stack backtraces.
> Improve the etp commands for lldb

- erts/emulator/internal_doc/BeamAsm.md
- erts/emulator/test/Makefile
- erts/emulator/test/perf_SUITE.erl
This only includes some basic tests for perf. In order for the test to run the user running the tests must be allowed to run `perf`.
I also intend to add tests to make sure the stack crawling works using `lbr` (and `fp` when #4676 is merged).
> jit: Add testcases to test perf support

- erts/doc/src/erts_alloc.xml
The flag is `+M<S>cp` as in Carrier Pool (not cg).
> Fix typo in erts_alloc

- lib/ssl/doc/src/ssl.xml
> TLS secrets require the keep_secrets option for TLS 1.3

- lib/stdlib/src/erl_parse.yrl
- lib/stdlib/src/erl_pp.erl
- lib/stdlib/test/erl_pp_SUITE.erl
- system/doc/reference_manual/expressions.xml
See PR-2584, where the parser grammar was partly rewritten using
operator precedence. As a consequence, parentheses are in many cases
no longer required around 'catch' expressions.
System doc: Remove comment and example about parentheses being
necessary around 'catch' in many situations.
Also: Do not write unnecessary parentheses around Expr (the template)
in list comprehensions.
> stdlib: Do not pretty-print parentheses around 'catch'

- erts/doc/src/erl_cmd.xml
- erts/emulator/test/distribution_SUITE.erl
- erts/etc/common/erlexec.c
Hello,
The option is already mentioned in https://erlang.org/doc/apps/erts/alt_dist.html but was not documented in https://erlang.org/doc/man/erl.html until now. I'm proposing this pull request as a follow-up to a recent question on the erlang-questions mailing list.
Cheers,
Jérôme
> Document the -no_epmd option

- lib/stdlib/src/gen.erl
Closes #4725... as per the issue's description and analysis.
> Fix typespec in gen.erl

- .github/workflows/main.yaml
The windows CI worker of github actions changed and does not come with the list of default sources anymore. Adding the source flag to nuget explicitly fixes this issue.
> Windows CI build specify nuget source explicity

- erts/doc/src/erl_nif.xml
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_nif.h
- erts/emulator/beam/erl_nif_api_funcs.h
- erts/emulator/test/nif_SUITE.erl
- erts/emulator/test/nif_SUITE_data/nif_SUITE.c
- erts/emulator/test/nif_SUITE_data/nif_mod.c
As a "safe" way to call NIF code in another module.
Also add `enif_init_resource_type` as a new (and hopefully the final) way to create a resource type with the new callback function `dyncall`.
> Add enif_dynamic_resource_call

- lib/kernel/src/inet_db.erl
Prior to this patch, a client could delete
data which would cause the server to crash.
We now change it so we ask the server to delete
the data in case of TTL=0 and avoid deleting it
altogether in other cases (we wait until the
server eventually purges it when necessary).
We also change the table structure to store
the last access separate from the dns_rr record,
allowing us to update only the latest time without
overriding any potential updated dns_rr entry.
Closes #4631.
/cc @RaimoNiskanen
> Remove race conditions on inet_db access

- HOWTO/BOOTSTRAP.md
- HOWTO/INSTALL-WIN32-OLD.md
- HOWTO/INSTALL-WIN32.md
Scope of changes is restricted to docs only, specifically HOWTO markdown files. Changes are in agreement with Standard American English.
occurances => occurrences
personel => personnel
prefered => preferred
> Typo corrections

- erts/epmd/epmd.mk
The file `epmd.mk` contains comments about the distribution protocol history, this PR simply adds a few words about version 6. Thank you
> epmd: Update comment about distribution protocol version 6

- erts/emulator/test/Makefile
- erts/emulator/test/hello_SUITE.erl
- erts/emulator/test/hello_SUITE_data/hello.erl
When developing a JIT, or a new implementation of Erlang, or a
new compiler for Erlang, one usually writes multiple small test cases
to use during development. Usually all that testing code is discarded
afterwards.
To avoid having to come up with those tests from scratch the next time
such a task is attempted, this commit adds a `hello` module that tests
most constructs that an Erlang implemenation needs to handle. To ensure
that it keeps working, we will embed it into a test suite for the
ERTS application.
> Add the hello module as a test case

- lib/stdlib/src/supervisor.erl
- lib/stdlib/test/supervisor_SUITE.erl
This PR is a follow-up for #4638 (@garazdawi @HansN @IngelaAndin)
It is invalid to combine the child spec flag `significant => true` with the sup flag `auto_shutdown => never` or with the child spec flag `restart => permanent`. The current implementation returns `{invalid_significant, true}` in those cases, which is ambiguous because a similar reason is returned when invalid (ie, non-boolean) values are given for `significant`.
This PR changes and refines the error reasons for the aforementioned cases, as requested in #4638:
* `{bad_combination, [{auto_shutdown, never}, {significant, true}]}` for the first case
* `{bad_combination, [{restart, permanent}, {significant, true}]}` for the second case
* (if both `auto_shutdown => never` _AND_ `restart => permanent` are combined with …
> supervisor: refine error reasons for bad combinations of options

- lib/erl_docgen/priv/xsl/db_html.xsl
The tag `<list type="ordered">` was rendered as an unordered (bulleted instead of numbered) list in the HTML output due to a missing XSL template, as can be seen in [the documentation for the `<list>` tag](http://erlang.org/doc/apps/erl_docgen/block_tags.html#%3Clist%3E---list) itself =^^=
> erl_docgen: fix ordered list rendering in HTML output

- lib/kernel/src/gen_tcp_socket.erl
- lib/kernel/src/socket.erl
Oops!
I just figured out that the return values from all socket functions really would benefit from a unification of the select return value.
Example:
``` erlang
send(Socket, Data, SendRef) ->
ok |
{ok, {RestData, SelectInfo}} |
{select, SelectInfo} |
{error, Reason}
```
The two values with `SelectInfo` have tags `ok` and `select`, respectively.  This gets in the way because for both values with `SelectInfo` you want to do a receive, and you want to do it in the function that calls creates `SendRef` and calls `send/3` to get the receive optimization for the `SendRef`.
So better would be:
``` erlang
send(Socket, Data, SendRef) ->
ok |
{select, SelectInfo} |
{select, {SelectInfo, RestData}} |
{error, Reason}
```
Because then you can:
``` erlang
SendRef = make_ref(),
case send(Socket, Data, …
```
> OTP-17355: socket select return value unification

- lib/stdlib/src/supervisor.erl
- lib/stdlib/test/supervisor_SUITE.erl
The shutdown flag of a supervisor child spec is typed (and documented) as `shutdown()`, which in turn is `brutal_kill | timeout()`. The `timeout()` type includes `0`. However, supervisors will reject child specs with a shutdown value of `0`.
This PR is really just plain cosmetics. There probably is no use case for a shutdown value of `0`, at least I can't imagine one. But rejecting `0` violates the spec.
The relevant test cases now include a check for `0` shutdown, too. While I was at it, I remodeled the `child_specs` test case (for the tuple format) a bit to test all possible combinations of valid child spec flags, like the recent `child_specs_map` test case (for the map format) does.
> supervisor: allow 0 for shutdown

- erts/emulator/beam/erl_afit_alloc.c
- erts/emulator/beam/erl_alloc.c
- erts/emulator/beam/erl_alloc_util.c
- erts/emulator/beam/erl_alloc_util.h
- erts/emulator/beam/erl_ao_firstfit_alloc.c
- erts/emulator/beam/erl_bestfit_alloc.c
- erts/emulator/beam/erl_goodfit_alloc.c
- erts/emulator/beam/erl_process.h
- erts/emulator/sys/common/erl_mmap.h
Allow more fine grained control over memory carrier sizes.
Super alignment is a way to minimize memory overhead per allocated block on 32-bit architectures, but it's not really needed on 64-bit.
> Reduce super alignment on 64-bit

- erts/emulator/test/driver_SUITE.erl
- erts/emulator/test/timer_bif_SUITE.erl
This pull-request fixes some test cases that gave false-positive results on the Erlang/OTP team's PowerPC machine with 64 cores and 32 GB memory.
> Make flaky tests less flaky

- Makefile.in
Before this patch these errors were logged:
$ ./otp_build setup -a --without-jinterface
(...)
MAKE tertiary_bootstrap_copy
cp: lib/jinterface/priv/OtpErlang.jar: No such file or directory
cp: lib/jinterface/priv/com/ericsson/otp/erlang/*: No such file or directory
(...)
> Makefile.in: Skip lib/jinterface/priv if missing

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/src/compile.erl
- lib/compiler/test/guard_SUITE.erl
81bc659e4cf0 switched the order of some optimization passes to
speed up compilation. Unfortunately, in rare circumstances that
would cause the `beam_ssa_bool` pass to do unsafe optimizations.
This commit eliminates the problem by running the `beam_ssa_bool` pass
before the `beam_ssa_share` pass (that is a partial revert of the
problematic commit). On my computer, that increases the compilation
time for the `String.Unicode` module in the Elixir standard library
with about 2 seconds (13 seconds instead of 11 seconds,
approximately).
Closes #4788.
> Correct order of optimization passes

- lib/kernel/src/gen_tcp_socket.erl
These sockets should be already bound for us, otherwise it is pointless to pass them. In the end we are (almost) always able to create sockets on our own (while we can not be able to bind it to some values). This will check if socket is created form existing FD, and if so, it will silently skip bind, assuming that it is already bound.
Fix #4680
> Do not bind sockets created from FDs

- lib/runtime_tools/src/dbg.erl
This fixes GH-4396. The function `dbg:n/1` used a local fun to set up a tracer on a remote node. This works fine as long as the remote node is running exactly the same version of Erlang/OTP but does not work at all otherwise. This is fixed by exporting the relevant function (`dbg:do_relay/2`) and calling this function on the remote node to set up remote tracing.
> GH-4396: exported function instead of fun to set up remote tracing

- erts/doc/src/communication.xml
- erts/doc/src/erl_dist_protocol.xml
- erts/doc/src/erlang.xml
- system/doc/reference_manual/data_types.xml
- system/doc/reference_manual/expressions.xml
- system/doc/reference_manual/processes.xml
Documentation improvements of [signals](https://erlang.org/~rickard/signal-doc-improvements/doc/reference_manual/processes.html#signals) and [process aliases](https://erlang.org/~rickard/signal-doc-improvements/doc/reference_manual/processes.html#process-aliases) in the reference manual.
> Signal doc improvements

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_type_SUITE.erl
Fixes https://github.com/erlang/otp/issues/4774
> beam_validator: Support subtraction in update_container_type/4

- erts/doc/src/crash_dump.xml
- erts/doc/src/driver_entry.xml
- erts/doc/src/erl_driver.xml
- erts/doc/src/erl_nif.xml
- erts/doc/src/erts_alloc.xml
- erts/doc/src/escript_cmd.xml
- lib/stdlib/doc/src/ets.xml
- system/doc/efficiency_guide/commoncaveats.xml
- system/doc/efficiency_guide/processes.xml
The non-SMP emulator was removed in OTP 21.0.
> Remove mentions of non-SMP emulator

- HOWTO/INSTALL-ANDROID.md
As a follow-up to #2963, I've updated the Android build documentation to cover the added x86_64 ABI variant.
I've removed the references to a specific OTP version to simplify the instructions too.
Thanks a lot
> Document how to cross compile for Android x86_64

- lib/common_test/doc/src/ct_run_cmd.xml
- lib/common_test/src/ct_run.erl
- lib/common_test/src/ct_testspec.erl
- lib/common_test/src/test_server_ctrl.erl
- lib/common_test/test/ct_error_SUITE.erl
- lib/common_test/test/ct_error_SUITE_data/error/test/timetrap_9_SUITE.erl
For the `ct_run` option `-multiply_timetraps N`, allow `N` to be a float as well as previously an integer.  This makes it possible to scale down time traps, which can be useful for instance when running locally and the time traps are long to avoid false positives on slower hosts.
Also fix a doc typo while at it.
> Floats for ct multiply timetraps

- erts/doc/src/erlang.xml
- lib/stdlib/doc/src/io.xml
- system/doc/reference_manual/processes.xml
Add a link to signal order guarantees for group_leader and process_info.
Expand io docs to show that standard_io is group leader. This was previously not documented, but it is mentioned in a lot of places that it is the group leader that all I/O is sent to by default. So we can just as well make it explicit that standard_io is just an alias for group_leader() and thus the target of standard_io is changed when the group leader is changed.
> Expand group_leader, process_info and standard_io docs

- lib/ssl/prebuild.skip
- lib/ssl/src/Makefile
This commit fixes two issues.
Firstly it makes it so that the include files that we depend on is not taken from the bootstrap system, which means that the prebuild should work. 
Secondly, it makes sure that if `$ERL_TOP` is something small (like just ), we do not do an overly zealous sed match.
Closes #4823
> ssl: Fix make deps

- lib/observer/src/crashdump_viewer.erl
- lib/observer/test/crashdump_helper.erl
The link entry for monitor_node looks like this:
{to,'node@name',[]}
and before this fix cdv crashed when encountering this.
cc @sirihansen
> observer: Fix parsing of monitor_node/2 in cdv

- lib/wx/c_src/wxe_return.cpp
- lib/wx/c_src/wxe_return.h
Make it compile when wxWidgets is built with "-enable-std".
Fixes GH-4834
> wx: Fix compile error

- lib/stdlib/doc/src/base64.xml
- lib/stdlib/src/base64.erl
Actual implementation allows zeroes.
> base64: fix spec to allow 0 as a character in ASCII string

- lib/compiler/src/compile.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/generic_pt.erl
- lib/compiler/test/error_SUITE.erl
746fb27c38c7e1 (#4528) refactored handling of internal compiler
errors. An unintended consequence was that `exit` and `throw` exceptions
raised by parse transforms or core transforms would be reported as
internal compiler errors. As well as being confusing, the return value
from `compile:file/2` would be the atom `error` even when the `return_errors`
option was given. (The `return_errors` and `return_warnings` options are
intentionally ignored when the compiler has crashed in an unexpected way.)
Change the error handling so that exceptions in parse and core
transforms are reported as an error in the given transform. While at
it, also improve the formatting of the exception reasons and
stacktraces for transforms.
> Improve handling of exceptions from parse transforms

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
- lib/stdlib/test/erl_lint_SUITE_data/format.erl
The following call to `io:format/1`:
t() ->
io:format("~p\n"),
ok.
would produce a warning with line number 0:
t.erl:0: Warning: wrong number of arguments in format call
This commit fixes that issue, and while at it also provides more
information than just "wrong number of arguments in format call" for
other failing calls. For example, given the following function:
t(A) ->
io:format("~p\n"),
io:format("~p\n", []),
io:format("~p ~p\n", [A]),
io:format("\n", [A]),
ok.
the following warnings will be produced:
t.erl:5:15: Warning: the format string requires an argument list with 1 argument, but no argument list is given
%    5|     io:format("~p\n"),
%     |               ^
t.erl:6:23: Warning: the format string requires an argument list with 1 argument, but the argument list is empty
%    6| …
> Improve warnings for failing io:format() calls

- lib/erl_docgen/priv/bin/specs_gen.escript
- lib/erl_docgen/src/docgen_otp_specs.erl
With edoc 1.0 the href links created for modules in
another application now have a complete URI pointing
to that application. So in erl_docgen we have to take
care of this by stripping it and only generating the
module that is needed.
Solves #4849
> erl_docgen: Translate type links in specs

- lib/ssl/src/ssl_certificate.erl
- lib/ssl/src/ssl_crl.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/ssl_internal.hrl
- lib/ssl/src/ssl_manager.erl
- lib/ssl/src/ssl_pkix_db.erl
- lib/ssl/src/tls_dtls_connection.erl
- lib/ssl/test/ssl_cert_SUITE.erl
The asn.1 decoding can be expansive avoid it by keeping both der and the
decoded cert available.
> ssl: avoid decoding certs several times

- lib/wx/c_src/wxe_impl.cpp
- lib/wx/c_src/wxe_impl.h
- lib/wx/src/wx.erl
- lib/wx/src/wxe_master.erl
Until now the `new_file` application event was handled
and there was only an undocumented function to
fetch those events. Now all 5 existing wxApp events are captured
and can be subscribed to from a client application with
a documented call. @dgud
Apps can register a user clicking on the app icon, users
dragging icons on an app icon and users double-clicking
files while the associated app is open.
> Completed list of handled MacOS wxApp events

- erts/doc/src/erl_ext_dist.xml
- erts/emulator/beam/utils.c
- erts/emulator/test/map_SUITE.erl
- erts/etc/unix/etp-commands.in
When 64-bit external pids were introduced in e9ab9a75a, internal
hash function was not adjusted accordingly. This led to a large
amount of hash collisions, ultimately making maps:from_list and
maps:from_keys to crash the emulator (stack overflow, or assertion
in a debug build).
> fix internal hash for external pids

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
There would be no warning for missing specs for functions that
were implicitly exported using `export_all`.
While we are at it, use the helper function `exports/1` in all places
where the lists of functions that are effectively exported should be
retrieved.
Closes #4772
> Make warn_missing_spec warn for functions exported using export_all

- erts/doc/src/erlang.xml
- system/doc/reference_manual/expressions.xml
- system/doc/reference_manual/processes.xml
Clarify message matching order; first all patterns then next message
in queue.
Rename "mailbox" and "mail queue" to message queue.
receive after limit is almost 50 days.
> Improve receive docs

- erts/emulator/beam/erl_lock_check.c
- erts/emulator/beam/jit/x86/beam_asm.cpp
by making the `__jit_debug_descriptor` linked list thread safe with a mutex.
(@garazdawi @jhogberg What is `__jit_debug_descriptor` used for anyway?)
> Seal memory leak of jit_code_entry

- lib/tools/src/cover.erl
The error return is not a 3-tuple but a 2-tuple with another 2-tuple in element 2. This is a typo affecting OTP-24 and master.
> cover:reset/1: correct -spec

- lib/os_mon/src/memsup.erl
On a Mac with Apple Silicon, `memsup:get_os_wordsize/0` would return
32 instead of the correct 64.
> Correct memsup:get_os_wordsize/0 on an M1 Mac

- lib/inets/src/http_client/httpc.erl
From profiling I see we are spending surprisingly much time in uri_string, and to me it seems that the current implementation of parsing and normalizing the URL in httpc does the parse+recompose twice. I cannot see any reason for this, so trying here to just return the map directly from uri_string:normalize.
All existing tests in httpc_SUITE pass, but I don't know if there are any tests that should be added? Any cornercases that might break from this change?
> Skip one extra uri_string:parse for httpc URL

- erts/emulator/test/exception_SUITE.erl
- lib/kernel/src/erl_erts_errors.erl
The extended error information for `binary_to_existing_atom/2` was wrong
when the encoding was `utf8` or `unicode`:
1> binary_to_existing_atom(<<"oops doesnt_really_exist">>, utf8).
in function  binary_to_existing_atom/2
called as binary_to_existing_atom(<<"oops doesnt_really_exist">>,utf8)
*** argument 1: invalid UTF8 encoding
Corrected:
1> binary_to_existing_atom(<<"oops doesnt_really_exist">>, utf8).
in function  binary_to_existing_atom/2
called as binary_to_existing_atom(<<"oops doesnt_really_exist">>,utf8)
*** argument 1: not an already existing atom
Also fixed a similar problem for `list_to_existing_atom/1`.
Closes #4900.
> Correct error message for binary_to_existing_atom/2

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/warnings_SUITE.erl
In OTP 24, there will be a warning for the following code:
foo(X) ->
Y = ".",
fun() ->
X = Y ++ "."  %Warning: a term is constructed, but never used
end(),
ok.
The warning is incorrect, because the built term will be matched to
the previous value of `X`. This commit eliminates the warning.
To explain the bug, I will illustrate how the example program is transformed
by the Core Erlang passes. My illustrative examples will use Erlang instead
of Core Erlang.
The first transformation makes the match `X = Y ++ "."` explicit:
foo(X) ->
Y = ".",
fun() ->
X1 = Y ++ ".",
case X1 =:= X of
true ->
X1;
false ->
error({badmatch,X})
end
end(),
ok.
The variable `X1` is only needed for the matching. It will be
annotated with a `compiler_generated` annotation to ensure that no
compiler warnings will be …
> Eliminate incorrect warning for useless building

- lib/compiler/internal_doc/beam_ssa.md
Document how exception handlers are structured at the the BEAM SSA
level. The material in this patch is based on an email conversation
between the author and Björn Gustavsson <bjorn@erlang.org>.
> compiler: Document exception handling at the BEAM SSA level

- erts/emulator/beam/erl_hl_timer.c
- erts/emulator/test/exception_SUITE.erl
- lib/kernel/src/erl_erts_errors.erl
The extended error information for timer BIFs would be incorrect if a
time value that exceeded the maximum allowed value was given:
1> erlang:send_after(1 bsl 50, self(), whatever).
in function  erlang:send_after/3
called as erlang:send_after(1125899906842624,<0.83.0>,whatever)
2> erlang:send_after(1 bsl 50, self(), whatever, []).
in function  erlang:send_after/4
called as erlang:send_after(1125899906842624,<0.85.0>,whatever,[])
*** argument 4: invalid option in list
For the call to `erlang:send_after/3`, no extended errors information would be
reported, while for the call to `erlang:send_after/4` there would be an incorrect
error message for the fourth argument.
This commit correct the messages, producing:
1> …
> Correct error messages for timer BIFs

- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/tls_dtls_connection.erl
- lib/ssl/test/ssl_api_SUITE.erl
As far as I could discover, it seems to me that in the commit
ec0f8d69a98b08b2effd07121b5f87e327d370ee, when moving around many test
suites, the prf test was left out, and it hasn't been running tests for
a while. Here I re-enable it, fixing also any other changes that seemed
necessary to make the test pass.
@IngelaAndin @peterdmv 
edit: there's a second commit, 8e19af3, removing some duplicated code as well, the prf code was copy&pasted and duplicated.
> Reenable tls prf test

- erts/emulator/beam/jit/x86/beam_asm.cpp
- erts/emulator/beam/jit/x86/beam_asm_perf.cpp
Two asserts can be safely removed. One asserts that code size is
greater than zero (which is not necessarily so), and another one
verifies that dual mapping is enabled (and it's not if we enable
Linux Perf support in either dump or map mode)
> debug emulator build: clean up unused assertions

- lib/dialyzer/src/dialyzer_dataflow.erl
- lib/dialyzer/src/dialyzer_utils.erl
See also GH-4890: https://github.com/erlang/otp/pull/4890.
Commit 04b905d assigned better start locations to messages, but also
sometimes let line number 0 slip through. This is now corrected.
Closes GH-4890.
> dialyzer: Do not expose line number 0 in message locations

- erts/emulator/test/alloc_SUITE.erl
- erts/emulator/test/distribution_SUITE.erl
Distribution suite suffers from the race between logger warning emitted, and "true" printed by the test code. There seems to be no specific order, logger may print before or after test suite outpit.
Alloc may fail when stop_node stops the node really fast, and linked process causes test case to exit with `{'EXIT', noconnection}`
> alloc_SUITE, distribution_SUITE: fix race conditions

- lib/stdlib/src/io_lib_pretty.erl
- lib/stdlib/test/io_SUITE.erl
See GH-4824: https://github.com/erlang/otp/pull/4824.
The fix of ERL-967, see https://github.com/erlang/otp/issues/4307,
proved to be inaccurate.
Thanks to Hareen (kvsrh) for tracking down the bug. The fix in
https://github.com/erlang/otp/pull/4842 is included.
A clause that breaks the infinite loop is also added. It will hide
further bugs, but it is deemed more important not to loop.
Fixes GH-4824. Closes GH-4842.
> stdlib: Fix a loop when using io_lib option 'chars_limit'

- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/erl_process.h
- erts/etc/unix/etp-commands.in
Dirty execution of a process in combination with an unlink signal from a port to the process could cause the signal queue of the process to enter into an inconsistent state. The result of the inconsistency typically caused a crash of the runtime system. This bug was introduced in OTP 23.3 (ERTS version 11.2).
Closes #4885
> Fix signal queue inconsistency

- erts/emulator/beam/erl_bif_port.c
- erts/emulator/test/busy_port_SUITE.erl
A call to `port_command()` could cause a scheduler to end up in an eternal loop if the port was busy and the calling process had incoming signals at the time of the call. This bug was introduced in OTP 23.3.2 (ERTS version 11.2.1), OTP 22.3.4.18 (ERTS version 10.7.2.10), and OTP 21.3.8.23 (ERTS version 10.3.5.18).
Closes #4898
> Fix busy port handling in port_command()

- erts/doc/src/erlang.xml
Tried to describe what this means but without mentioning the undocumented erlang:call_on_load_function/1 and friends.
> Document the on_load result from erlang:load_module/2

- lib/stdlib/src/c.erl
- lib/stdlib/test/c_SUITE.erl
A call to `c:ls/1` with a filename given as an atom would crash.
Example:
1> c:ls('/bin/sh').
in function  length/1
called as length('/bin/sh')
*** argument 1: not a list
in call from c:lengths/2 (c.erl, line 1083)
in call from c:ls_print/1 (c.erl, line 1071)
Closes #4916
> Fix crash in c:ls/1

- lib/stdlib/src/supervisor.erl
Fix missing space causing alternatives in -spec not to line up.
> supervisor: fix missing space in -spec

- erts/emulator/beam/erl_printf_term.c
- lib/observer/src/crashdump_viewer.erl
- lib/observer/src/observer_html_lib.erl
- lib/observer/test/crashdump_helper_unicode.erl
- lib/observer/test/crashdump_viewer_SUITE.erl
Atoms containing Unicode code points greater than 255 would not
be printed correctly in crash dumps.
This commit corrects the printing of Unicode atoms done by the
runtime-internal function `erts_printf()` (used when producing crash
dumps) and also updates `crashdump_viewer` to correctly handle such
atoms in function names in stack backtraces.
> Correct printing of Unicode atoms in crash dumps

- lib/kernel/src/net_kernel.erl
> Fix hanging net_kernel

- lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
After a call to close(), `socket` is set to null which can lead to a NullPointerException in the `receive_loop` still handling tick messages [in AbstractConnection line 568](https://github.com/erlang/otp/blob/master/lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java#L568):
```
567                        synchronized (this) {
568                            OutputStream out = socket.getOutputStream();
569                            out.write(tock);
570                            out.flush();
571                        }
```
Cleanly end the `receive_loop` instead in this case. 
The crash was detected through future changes to the https://github.com/JeromeDeBretagne/erlanglauncher/ project, I have confirmed this change is fixing the issue as expected.
Thanks a lot
> jinterface: Fix a NullPointerException in AbstractConnection

- lib/stdlib/doc/src/timer.xml
- lib/stdlib/src/timer.erl
- lib/stdlib/test/timer_SUITE.erl
- lib/stdlib/test/timer_simple_SUITE.erl
- system/doc/efficiency_guide/commoncaveats.xml
This started as a minor improvement, and gradually grew into, well, _this_... ^^; The `timer` module seems to be getting out of fashion these days, having a reputation for getting clogged when there are many timers. And no wonder, the most recent changes being 6 years ago, but most of it more than 10 years old. But the functionality is actually pretty handy (and I like old stuff ;)), so I went to dust it off a bit.
This is what has been done:
* All validations have been moved into the exported accessor functions, meaning they happen in the calling process and don't bother the timer server.
* An `apply_after` call (and thus, other functions using it, like `send_after`) do the apply (call `do_apply`) immediately without going through the timer server if the timeout is `0`.
* ~The …
> timer: modernization and improvements

- configure
- configure.src
Without this patch, the following error occurs repeatedly:
```
expr: illegal option -- -
expr: usage: expr [-e] expression
```
FreeBSD ports tree has carried a local patch addressing this for a while.
I haven't tested this on other OS but I believe -- is a GNU-ism already.
> fix ./configure script handling of expr(1) on BSD

- lib/stdlib/src/supervisor.erl
This PR is just a micro-optimization and some cleaning =^^= It should be pretty obvious what has been done.
`add_restart/3` was just a customized re-invention of `lists:takewhile/2`, and as such even a misnomer, as it didn't _add_ anything. And by putting the new restart on the list (in `add_restart/1`) _before_ passing it to `add_restart/3` to be filtered caused an unnecessary filter step, as the new restart would never be removed anyway. Finally, the `inPeriod/3` function (used for checking if a restart was in or out of period) did a calculation that could really be replaced by a pre-calculated constant value, as the `Now` and `Period` arguments were always the same over a run of `add_restart/3`, and `Now =< Then + Period` could be rewritten as `Now - Period =< Then`.
This PR …
> supervisor: optimize restart intensity calculation

- erts/emulator/internal_doc/BeamAsm.md
Change wording to be what I think was intended.
> erts: Beam-asm internal documentation fix

- lib/compiler/src/beam_dict.erl
What is returned as the `Function` is not a label index, it is the
index into the atom table for the name of the function. Therefore
change the type from `label()` to `index()`.
> beam_dict: Correct types of local_table/1 and export_table/1

- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_global.cpp
- erts/emulator/beam/jit/x86/instr_bif.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_fun.cpp
- erts/emulator/beam/jit/x86/process_main.cpp
The x86 JIT uses the ud2-instruction to signal a failed assertion in
the generated machine code. Investigating a failed assert is
simplified if the reason for the failure is provided in the assembly
listing produced when running with `+JDdump true`.
> jit-x86: Provide reason for assertion failure in assembly listing

- lib/mnesia/doc/src/mnesia.xml
- lib/mnesia/src/mnesia.erl
- lib/mnesia/src/mnesia_loader.erl
- lib/mnesia/src/mnesia_monitor.erl
- lib/mnesia/test/mnesia_evil_coverage_test.erl
When a table is sent from active node to another one it is done in chunks of N records each, where the N is calculated once based on size in bytes of first record and hard coded `MAX_TRANSFER_SIZE` (`7500`).
```erlang
(?MAX_TRANSFER_SIZE div BinSize) + 1.
```
In practice it means that we are sending a huge number of super small chunks.
It is worth noting that value of `MAX_TRANSFER_SIZE` was not changed at least since 2009 :)
In our production setup by simply changing this hard coded value to `128000` we were able to reduce loading time of all tables from remote active node from 184s to 114s. Combining it with setting `send_compressed` parameter we were able to reduce it further to 70s.
The important thing is that with default  small chunks of max 7500 bytes using `send_compressed` option …
> Make max_transfer_size parameter configurable to optimise mnesia table loading time

- lib/parsetools/src/leex.erl
- lib/parsetools/test/leex_SUITE.erl
> parsetools: Fix compiler warning in generated code

- erts/emulator/beam/erl_init.c
Clean up the help text that the emulator prints when an invalid option is given.
The following errors were fixed:
* The description of `-asmdump` was removed, and the description of the option
under its new name `-JDdump` was added.
* Added description of `-JPperf`.
* Added a few missing newlines.
I also made the following changes to make the style more consistent between
descriptions:
* All descriptions now start with a verb with its initial letter in lowercase.
(For example, "suggested stack size..." was changed to "suggest stack size...".)
* A comma before an independent clause such "valid range is..." was changed to
semicolon.
* The period at the end of each description was removed.
* The clause "see the erl(1) documentation for more info" was removed
as it sort of applies to every …
> Clean up the help text for the emulator

- lib/stdlib/src/epp.erl
- lib/stdlib/test/epp_SUITE.erl
The `?MODULE` pre-defined macro would be considered defined even before
a `-module()` definition had been seen. For example:
-ifdef(MODULE).
-error("?MODULE is incorrectly considered defined").
-endif.
-module(t).
When attempting to compile this module, the following error would
be produced:
t.erl:2:2: -error("?MODULE is incorrectly considered defined").
%    2| -error("?MODULE is incorrectly considered defined").
%     |  ^
The behavior is inconsistent with how an attempt to use ?MODULE before
the `-module()` definition has been seen is handled (there will be
an "undefined macro" error).
This bug matters in practice because Elixir is pre-processing `.hrl`
files containing record declarations in order to build helper
functions. Pre-processing the following header file will fail when …
> epp: Fix inconsistent handling of undefined pre-defined macros

- erts/emulator/beam/beam_file.c
- erts/emulator/beam/beam_file.h
- erts/emulator/beam/beam_load.c
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_module.cpp
- erts/emulator/beam/jit/asm_load.c
- erts/emulator/beam/jit/beam_asm.h
- erts/emulator/beam/jit/beam_jit_main.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_module.cpp
- erts/emulator/test/Makefile
- erts/emulator/test/jit_SUITE.erl
This is a set of patches which improve the readability of the
.asm-dumps, produced when running the emulator with the `+JDump true`
flag, by pretty-printing the labels marking the start of a function
using its <name>/<arity> Erlang name.
If this PR is accepted I can do an Arm-version of the last patch, but
I will require a volunteer to test it.
> Improve the readability of .asm-dumps

- lib/compiler/src/beam_ssa_throw.erl
- lib/compiler/test/trycatch_SUITE.erl
This is a conservative fix for https://github.com/erlang/otp/issues/4953. A more complete fix would avoid entering the offending block as it cannot be reached with the tested value, but that's too big of a change to go out in a patch, so I'll do that later on `master` instead.
> beam_ssa_throw: Remove assertion that caused crashes

- erts/doc/src/erl_dist_protocol.xml
- system/doc/general_info/upcoming_incompatibilities.xml
- system/doc/general_info/xmlfiles.mk
- system/doc/top/templates/index.html.src
Some upcoming changes can be awkward to fit into the "Deprecations" and "Scheduled for Removal" pages. Add a new "Coming Potential Incompatibilities" pages to address that issue.
To that page, add a list of the distribution capabilities that will become mandatory in OTP 25 (see #4972).
Also copy with edits some upcoming changes to the distribution now described in "Scheduled for Removal".
> Add a "Coming Potential Incompatibilities" page to the documentation

- lib/compiler/src/v3_core.erl
- lib/compiler/test/guard_SUITE.erl
- lib/dialyzer/test/indent_SUITE_data/results/guard_warnings
- lib/dialyzer/test/small_SUITE_data/results/guard_warnings
In a guard, `not (X =:= true)` would incorrectly evaluate to `false`
for non-boolean values of `X`.
The reason for the bug is an unsafe transformation in the `v3_core`
pass that transforms `not (X =:= true)` to `X =:= false`. That
transformation is safe only if `not (X =:= true)` was transformed from
`not X` by the compiler itself. (This bug was introduced in OTP R13.)
Eliminate the problem by only doing the transformation when `X =:= true`
is known to have been expanded from `not X` by the compiler.
While at it, also improve the comments.
Fixes #5007.
> Fix code generation in guard for not (X =:= true)

- erts/emulator/beam/beam_common.c
- erts/emulator/beam/emu/instrs.tab
- erts/emulator/beam/jit/x86/instr_common.cpp
After an exception had been caught, the stacktrace (`p->ftrace`) would
be retained in the process until another exception occurred.
While at it, also clear the exception term (`p->fvalue`) in the common
error handling code instead of in the code for `try_case` in each module.
> Don't keep a stacktrace longer than necessary

- Makefile.in
The test system doesn't run because subsystem tests
don't know where ERL_TOP is.
> Fix A Bug That Causes The Test System To Not Run

- lib/ssl/src/ssl_server_session_cache.erl
- lib/ssl/src/tls_server_session_ticket.erl
- lib/ssl/src/tls_socket.erl
- lib/ssl/test/tls_api_SUITE.erl
To be able to fully work with new gen_tcp socket backend.
Also Make sure TLS-1.3 server session ticket handler processes
monitor the listen socket so that it can terminate gracefully.
> ssl: Use new inet:monitor/1 to monitor listen sockets

- erts/doc/src/erl_cmd.xml
Same as #5042 but based on `maint`.
> Doc typo: build_flavor was renamed to emu_flavor  (for maint)

- lib/stdlib/doc/src/lists.xml
- lib/stdlib/src/lists.erl
- lib/stdlib/test/lists_SUITE.erl
This PR introduces `enumerate/1` and `enumerate/2` functions to
the `lists` module in the standard library. Simple unit tests and
documentation for the introduced functions are included.
I am working a lot with ASTs in Erlang and I very often run into a
situation where I need to do something with a list of arguments of
some function definition knowing their index and each time I am doing
so I need to write something like
```
[ ...
|| {I, Arg} <- lists:zip(lists:seq(0, length(Args)), Args)
]
```
This is really annoying and can be expressed with a single function
`enumerate` which does exactly that. The mentioned use case is not
the only one, of course. I run into this pattern really commonly.
Also, many modern languages support this already. The first that come
to my mind are Rust and …
> Add lists:enumerate/1 and lists:enumerate/2

- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/property_test/ssl_eqc_chain.erl
- lib/ssl/test/ssl_cert_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
The signature selection algorithm has been changed to also verify
if the client supports signatures using the elliptic curve of the
server's public/private key pair. This change fixes #4958.
The old algorithm only verified the signature algorithm and the
hash algorithm, not taking into account the elliptic curve of
the key in the server's certificate. This could result in
successful TLS connections with non-standard algorithm combinations
in the CertificateVerify message such as ECDSA with secp256r1 and
SHA512, when the server's certificate had a public key on an
unsupported elliptic curve, signed with a non-ECDSA signature
algorithm and hash algorithm combination e.g. RSA with SHA256.
TODO:
> ssl: Fix signature algorithm selection for ECDSA

- lib/stdlib/doc/src/gen_statem.xml
If no spec is given, dialyzer will complain that `init/1` only terminates with explicit exception.
> Add no_return() spec to gen_statem:init/1 note

- lib/public_key/test/public_key_SUITE.erl
Original test behaves incorrectly: it doesn't check result and testing certificate created for this test is not a proper rsa-pss one.
> Fixing test public_key_SUITE:rsa_pss_sign_verify()

- system/doc/tutorial/c_port.xmlsrc
Without using "./extprg", an error occurs saying:
`sh: line 0: exec: extprg: not found`
> 'extprg' needs to be properly addressed

- lib/compiler/src/beam_listing.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/asm_labels.erl
Looking at BEAM assembly listings, figuring out where a local call
goes requires you to keep track of which `{f,<index>}`-label
corresponds to which function. This patch increases the readability of
the assembly listing by annotating each call instruction with a
comment containing the name of the called function.
Instead of, for example, `{call,1,{f,4}}.`, the listing will now say
`{call,1,{f,4}}. % foo/1`.
> compiler: Comment BEAM assembly with callee names in clear-text

- lib/compiler/src/beam_ssa_pp.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/types_pp.erl
To help compiler developers, the compiler can be asked, during 
compilation, to dump its internal BEAM SSA representation of the
compiled modules to a textual format. In it, type information is
printed as raw terms using the format specifier `~p` which for the
more complex types such as `#t_union{}` and `#t_tuple{}` become
rather hard to read.
This patch extends the BEAM SSA dumper with a pretty-printer for type
information. The BEAM SSA type information is similar to, but not the
same as, the representation used by Dialyzer so we can therefore not
use Dialyzer's type printer. The textual representation of BEAM SSA
types is designed to be as close to the Erlang Type Language as
possible.
Included in this patch is a test which checks that an ssa dump
contains the pretty printed types we …
> compiler: Pretty print types in SSA-dumps

- lib/compiler/test/compile_SUITE.erl
The variable Listings is equivalent to the already created TargetDir,
so remove its definition and use TargetDir instead.
Discovered while developing the test for #5076.
> compiler: Remove duplicated directory name construction in test

- system/doc/reference_manual/expressions.xml
I noticed [`is_map_key/2`](https://erlang.org/doc/man/erlang.html#is_map_key-2) is allowed in guard tests, but the reference documentation currently does not list it, neither the [Maps in Guards](https://erlang.org/doc/reference_manual/expressions.html#maps-in-guards) section, nor the [Guard Expressions](https://erlang.org/doc/reference_manual/expressions.html#guard-expressions) section. This PR adds it to the reference documentation. I added it to the table of type test BIFs since this is where the rest of the `is_...` functions are listed.
> Add is_map_key/2 as a guard BIF to the reference documentation

- lib/stdlib/src/erl_error.erl
- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/src/gen.erl
- lib/stdlib/src/io.erl
- lib/stdlib/test/gen_server_SUITE.erl
- lib/stdlib/test/io_SUITE.erl
This provides early feedback in gen behaviours if a process
attempts to call itself, which is especially important on
infinity timeouts.
The functionality was also implemented for the io module,
which also errors with reason "calling_self" and is handled
by the error formatter accordingly:
1> io:put_chars(self(), "123").
** exception error: calling_self
in function  io:put_chars/2
called as io:put_chars(<0.83.0>,"123")
*** argument 1: process sent a blocking request to itself
Closes #5005.
> Fail early when calling_self

- .github/workflows/main.yaml
This shaves off ~7min from build time.
We cache `~/wxWidgets` instead of `/mnt/c/opt/local64/pgm/wxWidgets-*`. With the latter, restoring the cache silently fails.
> ci: Cache wxWidgets on Windows

- erts/emulator/beam/beam_common.c
The frame pointer is not used by anything after hibernate, but some
ASSERTS assume that it is correct so we set it to the correct value
after the stack has been dropped when we hibernate.
Fault found by Max Federov and can be reproduced by running
hibernate_SUITE with the flags -emu_type debug +JPperf true.
> erts: Fix FRAME_POINTER to be valid when stack adjusted

- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/test/bif_SUITE.erl
- erts/etc/unix/etp-commands.in
With multiple reusable receive markers, marker that is marked
to remove may be followed by process_info signal, which will
also be handled within the loop in erts_proc_sig_handle_incoming.
It is possible that process_info moves messages up to the next
non-message signal from the middle to inner queue. If there was a
receive marker at the very beginning of the middle queue, it
would set save pointer to sig_qs.cont, which will be overwritten
when linking middle queue head into inner queue. This would make
save pointer to skip all messages that were in between of removed
receive marker and process_info request.
To observe this behaviour using a debugger, run the test case
provided with a breakpoint set to handle_process_info part where
it reassigns c_p->sig_qs.cont to the next non-message …
> Fix process_info that can hang waiting for reply

- erts/etc/unix/Install.src
Before this patch:
release$ ./Install -sasl $PWD
release$
> erts: Remove blank line from ./Install script output

- erts/emulator/beam/beam_common.c
- erts/emulator/beam/emu/instrs.tab
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
This commit reduces X register shuffling after an exception has
occurred. This will slightly reduce the size of the JITted code, but
is unlikely to improve speed because is usually rare that execeptions
are raised.
> Reduce the size of the JITted code for try_case

- lib/edoc/src/edoc_extract.erl
The module edoc_tags is an internal module and thus
we cannot refer to a type within it. So instead we
inline the type into edoc_extract so that the user
can view it.
Closes #5058
> edoc: Use local definition of context

- lib/crypto/configure
- lib/crypto/configure.ac
crypto: Format ssl standard locations
crypto: Add /opt/homebrew/opt/openssl to standard locations
This is the default location on Homebrew on M1 Macs.
Before this patch:
$ ./otp_build configure
(...)
*********************************************************************
**********************  APPLICATIONS DISABLED  **********************
*********************************************************************
crypto         : No usable OpenSSL found
jinterface     : No Java compiler found
odbc           : ODBC library - link check failed
ssh            : No usable OpenSSL found
ssl            : No usable OpenSSL found
After this patch:
$ ./otp_build configure
(...)
*********************************************************************
**********************  APPLICATIONS DISABLED …
> crypto: Add /opt/homebrew/opt/openssl to standard locations

- erts/emulator/drivers/unix/ttsl_drv.c
It is possible for lbuf and lbuf+pos to overlap so use memmove
Closes #5116
> erts: Fix memcpy buffer overwrite

- system/doc/efficiency_guide/commoncaveats.xmlsrc
- system/doc/efficiency_guide/efficiency_guide.erl
- system/doc/efficiency_guide/processes.xmlsrc
Add a section about accidental copying and loss of sharing to the
Common Caveats chapter.
While at it, also update information about copying in the Processes
chapter as follows:
* Lift up several sub sections to the top level to make them visible
in the left sidebar.
* Rename the "Constant Pool" to "Literal Pool" (which is the correct
technical term), and also update information about copying and
persistent terms.
Closes #3533.
> Add a section about accidental copying and loss of sharing

- erts/emulator/beam/erl_db_util.c
- erts/emulator/beam/erl_map.c
- erts/emulator/beam/erl_map.h
- erts/emulator/beam/erl_message.c
- erts/emulator/test/match_spec_SUITE.erl
This PR fixes a bunch of problems with having maps in the guard and body part of match specs.
Prior to this PR you could:
* not use `{const,Term}` in values (nor keys) of maps.
* not use any expression in keys of small maps
* not use expressions in keys of large maps unless the map also had expressions in its values
* not use expressions as values in large maps as it would segfault.
After this PR you can now use all expressions as both keys and values in both guards and body parts of match specs.
If you use expressions for keys and those expressions end up creating duplicate keys, the value that is chosen is undefined. That is if you do this: `#{ {const,key} => 1, key => 2}` it is not defined if `key` will have the value 1 or 2.
This PR should help #4915 to work properly.
> Fix maps in match specs

- lib/kernel/src/code.erl
> kernel: Do not crash when getting doc from escript

- lib/runtime_tools/doc/src/dbg.xml
Explain the meaning of acronym function names in dbg module documentation. I am not sure these definitions should be formatted in the documentation so I am happy to adjust things if this format isn't suitable.
See http://erlang.org/pipermail/erlang-questions/2021-August/101275.html for context
I am happy to add this same information to the output of the `dbg:h/0,1` functions if that is also desired.
> Document dbg acronym meanings

- lib/erl_docgen/src/docgen_xml_to_chunk.erl
Before this patch, this XML:
```xml
are also available in the
<seeerl marker="erts:erlang"><c>erlang</c></seeerl>
module under the names
```
Produced this chunk entry:
```erlang
<<" are also available in the ">>,
{a,[{href,<<"stdlib:binary#erts:erlang">>},
{rel,<<"https://erlang.org/doc/link/seeerl">>}],
[{code,[],[<<"erlang">>]}]},
<<" module under the names ">>,
```
Note the `stdlib:binary#erts:erlang` instead of the expected `stdlib:binary`. We'd get similar result for `erlang` becoming `stdlib:binary#erlang`. This patch fixes that.
With this patch we have the following behaviour. Say, we are generating
docs for the app `myapp` and the module `mymod`:
"app:mod#anchor" => "app:mod#anchor"
"mod#anchor"     => "myapp:mod#anchor"
"app:mod"        => "app:mod"
"mod"            => …
> erl_docgen: Fix generating docs chunk entry for `<seeerl>`

- erts/emulator/Makefile
The test target in "$(ERL_TOP)/make/app_targets.mk" that is included
in the end of "erts/emulator/Makefile.in" is not picked up by make
when executing make in the emulator directory. The reason for this is
that the file generated from "erts/emulator/Makefile.in" is executed
by an external make call. Unfortunately, this makes running commands
such as the following not work as intended:
(cd $ERL_TOP/erts/emulator && make ARGS="-suite binary_SUITE -case deep_bitstr_lists" test)
Putting "include $(ERL_TOP)/make/app_targets.mk" in the end of
"erts/emulator/Makefile.in" fixes the problem.
> Fix broken "make test" in erts/emulator

- lib/stdlib/doc/src/gen_statem.xml
- lib/stdlib/src/gen_statem.erl
Add /2 variants of types returning data, so a user can use them to
spec their implementation (parameterized with their own data type)
and thus get validation for it.
**NB**: There is one problem though, the docs doesn't work. [Bug report](https://github.com/erlang/otp/issues/4927)
There seems to be code in the xsl to handle selection with arity, but nobody is using it for types.
Putting both arities in the same datatype block is inspired by function documentation, where it is somewhat commonly used.
Regardless of if i use one of both names, with arity, i get errors like:
`gen_statem:init_result/1: unknown spec`
> gen_statem: Make it possible to spec data

- lib/kernel/src/socket.erl
This changes the `address` key to `interface` which matches what is
wanted for the `add_membership` option.
> Fix ip_mreq spec to match implementation

- lib/kernel/src/inet_dns.erl
For now, when DNS RR is malformed it results in 'parse ok,  however, some records are not parsed':
`3> inet_res:resolve("kinolupa.net", in, aaaa, [], 5000).`
`{ok,#dns_rec{header = #dns_header{id = 1,qr = true,
opcode = query,aa = false,tc = false,
rd = true,ra = true,pr = false,rcode = 0},
qdlist = [#dns_query{domain = "kinolupa.net",type = aaaa,
class = in}],
anlist = [#dns_rr{domain = "kinolupa.net",type = aaaa,
class = in,cnt = 0,ttl = 600,
data = <<171,22,127,201>>,
tm = undefined,bm = [],func = false},
#dns_rr{domain = "kinolupa.net",type = aaaa,class = in,
cnt = 0,ttl = 600,
data = <<171,22,127,201>>,
tm = undefined,bm = [],func = false}],
nslist = [],arlist = []}}
`
As you can see, some broken DNS server returned two malformed (too short) AAAA records that 
erlang was not able to …
> Malformed DNS RRs shall result in parse errors

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
The following example:
valid(Type) -> is_list(mime_to_ext(Type)).
mime_to_ext(<<"application/a2l">>) -> [<<"a2l">>];
mime_to_ext(_Type) -> nil.
would crash `beam_ssa_codegen`:
$ erlc a.erl
Function: valid/1
a.erl: internal error in pass beam_ssa_codegen:
exception error: no function clause matching beam_ssa_codegen:cg_instr(is_nonempty_list,[{x,0}],{x,0})
in function  beam_ssa_codegen:cg_block/3 (beam_ssa_codegen.erl, line 1326)
in call from beam_ssa_codegen:cg_linear/2 (beam_ssa_codegen.erl, line 956)
in call from beam_ssa_codegen:cg_linear/2 (beam_ssa_codegen.erl, line 957)
in call from beam_ssa_codegen:function/3 (beam_ssa_codegen.erl, line 130)
in call from lists:mapfoldl/3 (lists.erl, line 1376)
in call from beam_ssa_codegen:module/2 (beam_ssa_codegen.erl, line 49)
in call from …
> Eliminate a crash in beam_ssa_codegen

- lib/mnesia/src/mnesia_index.erl
- lib/mnesia/test/mnesia_trans_access_test.erl
delete_object(NonExistingRecord) deleted index keys even if the record
didn't exist, in set tables, and nothing was deleted from the real table.
Solve this by doing the same checks as was done for bag tables.
Fixes GH-5040
> mnesia: Do not unconditionally delete index keys

- erts/emulator/beam/external.c
- erts/emulator/test/exception_SUITE.erl
- lib/kernel/src/erl_erts_errors.erl
When `binary_to_term/2` failed with a `badarg` exception, the extended error
information would always blame the second argument even if the error was
in the first argument:
1> binary_to_term(<<"">>, []).
in function  binary_to_term/2
called as binary_to_term(<<>>,[])
*** argument 2: invalid option in list
2> binary_to_term(<<131,100,0,10,97,95,110,101,119,95,97,116,111,109>>, [safe]).
in function  binary_to_term/2
called as binary_to_term(<<131,100,0,10,97,95,110,101,119,95,97,116,111,109>>,
[safe])
*** argument 2: invalid option in list
Correct the extended error information like this:
1> binary_to_term(<<"">>, []).
in function  binary_to_term/2
called as binary_to_term(<<>>,[])
*** …
> Correct extended error for binary_to_term/2

- erts/emulator/beam/erl_bif_re.c
Because small subbinaries can be converted to heapbinaries
during GC, we do not want to have references to those in the
re state, so we copy any binary that is small enough to fit
on the heap.
Closes #5150
> Make re copy small subbinaries 

- erts/emulator/beam/erl_binary.h
- erts/emulator/beam/erl_gc.c
The entire off-heap list (reference counted objects; binaries, funs, external pids/ports/refs) is traversed twice at the end of a GC. The second time by `reset_active_writer()` to reset active writable binaries. This is now instead done during the first and only traversal.
Also some benign bug fixes and code cleanup.
> Optimize off-heap list traversal during GC

- lib/ssh/src/ssh_sftpd.erl
Fixes GH-5014
Handle {error, eacces} the same as {error, enoent} in ssh_sftpd:get_attrs/5 internal function.
This prevents an error while the sftpd answers a client for a request to return a directory contents but a file is deleted in that very directory after the replying is initiated, but before it is ended.
> ssh: Handle eacces like enoent in ssh_sftpd:get_attrs/6

- lib/kernel/src/gen_tcp_socket.erl
- lib/kernel/test/gen_tcp_misc_SUITE.erl
This is a rewrite of the option parsing in `gen_tcp_socket`, a.k.a the implementation module for `inet_backend = socket`.
The intention is to make it a little less messy, and to fix the bug in #5122.
> Improve inet_backend = socket option parsing for gen_tcp (OTP-17580)

- lib/stdlib/src/maps.erl
The helper function `intersect_with_iterate()` used by
`maps:intersect/2` and `maps:intersect_with/3` passes around an
argument that is ultimately never used. Eliminate it.
> Slightly simplify maps intersection functions

- lib/public_key/src/public_key.erl
- lib/public_key/test/public_key_SUITE.erl
RFC8410 Section 7: the private key is wrapped in a CurvePrivateKey
object and wrapped by the OCTET STRING of the "privateKey" field
- unwrap CurvePrivateKey in public_key:der_decode/2
- wrap in CurvedPrivateKey in public_key:der_encode/2
- assert key size in DER decode tests
Fixes #5156
> public_key: Fix EDDSA private key ASN-1 decode/encode

- lib/eunit/src/eunit_lib.erl
- lib/eunit/src/eunit_proc.erl
- lib/eunit/src/eunit_surefire.erl
- lib/eunit/src/eunit_tty.erl
- lib/eunit/test/Makefile
- lib/eunit/test/eunit_SUITE.erl
- lib/eunit/test/ttimesout.erl
In an eunit test, when a test case times out, include a stacktrace. This can be useful when debugging.
In the event of a test timeout, the printout now looks like this:
```
1> eunit:test(tl, [verbose]).
eunit:test(tl, [verbose]).
======================== EUnit ========================
tl: takes_too_long_test (module 'tl')...*timed out*
in function timer:sleep/1 (timer.erl, line 152)
in call from tl:takes_too_long_test/0 (/.../tl.erl, line 6)
in call from eunit_test:'-mf_wrapper/2-fun-0-'/2 (eunit_test.erl, line 273)
in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71)
in call from eunit_proc:run_test/1 (/.../eunit_proc.erl, line 528)
in call from eunit_proc:with_timeout/3 (/.../eunit_proc.erl, line 353)
in call from eunit_proc:handle_test/2 (/.../eunit_proc.erl, line 511)
in …
```
> eunit: Include a stacktrace when a test times out

- erts/emulator/beam/erl_alloc.c
- erts/emulator/beam/erl_alloc.types
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_lock_check.c
- erts/emulator/beam/erl_message.c
- erts/emulator/beam/erl_message.h
- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/erl_proc_sig_queue.h
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process.h
- erts/emulator/beam/erl_process_dump.c
- erts/emulator/beam/erl_process_lock.h
- erts/test/Makefile
- erts/test/parallel_messages_SUITE.erl
- erts/test/parallel_messages_SUITE_data/visualize_throughput.html
Erlang guarantees that signals (i.e., message signals and non-message signals) sent from a single process to another process are ordered in send order. However, there are no ordering guarantees for signals sent from different processes to a particular process. Therefore, several processes can send signals in parallel to a specific process without synchronizing with each other. However, such signal sending was previously always serialized as the senders had to acquire the lock for the outer signal queue of the receiving process. This commit makes it possible for several processes to send signals to a process with the message_queue_data=off_heap setting(1) activated in parallel and without interfering with each other. This parallel signal sending optimization yields much better scalability …
> Optimize signal sending to processes with message_queue_data=off_heap enabled

- lib/kernel/doc/src/kernel_app.xml
- lib/kernel/src/inet_tcp_dist.erl
- lib/kernel/test/erl_distribution_SUITE.erl
- lib/ssl/src/inet_tls_dist.erl
- lib/ssl/test/ssl_dist_SUITE.erl
This change allows user to specify spawn options when dist protocol
starts dist_util:handshake_other_started or handshake_we_started
processes.
These processes will be alive until the connections are down. With
thousands of ssl dist connections it spends quite amount of memory,
and it would be great if we can change garbage collection, as well
as other spawn options for dist_util processes.
> Add dist_util_spawn_options in kernel

- erts/emulator/drivers/win32/registry_drv.c
- lib/stdlib/src/win32reg.erl
- lib/stdlib/test/win32reg_SUITE.erl
Pull request to resolve #5037 and #4702 (issues with win32reg).  I have to be honest, I found it very hard to debug and test this due to the complexity of building OTP on windows.  I managed to build it in WSL, but of course this doesn't help as the code in Q is windows only.
> Fix win32reg issues #5037 and #4702

- lib/inets/src/http_server/httpd_response.erl
- lib/inets/src/http_server/mod_dir.erl
* Replace links to non-existing (Apache) images with text emojis
* Fix column alignment for long filenames
* Fix column alignment for filenames containing &, <, > (length
calculated on the original name rather than entity encoded name)
* Fix title on root directory "Index of " -> "Index of /"
* Fix link to Parent directory missing on the 2nd level
* Don't show link to Parent directory on root level
* Don't encode slash as %2F in links to sub/parent dirs
Fixes #4855, #4677
> [inets] httpd directory listing improvements

- lib/dialyzer/src/dialyzer_contracts.erl
- lib/dialyzer/src/erl_types.erl
- lib/dialyzer/test/overspecs_SUITE_data/results/opaque
- lib/dialyzer/test/overspecs_SUITE_data/src/opaque.erl
- lib/dialyzer/test/underspecs_SUITE_data/results/opaque
- lib/dialyzer/test/underspecs_SUITE_data/src/opaque.erl
Most of the warning checks would look straight through opaque types regardless of whether they belonged to the current module or not, resulting in wonky messages or missing warnings.
https://github.com/erlang/otp/issues/5118
> dialyzer: Fix opaque type handling for `underspecs`/`overspecs`

- lib/dialyzer/doc/src/dialyzer.xml
- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_contracts.erl
- lib/dialyzer/src/dialyzer_options.erl
These warnings are useful on their own, and I think they're worth breaking out from the more chatty `-Wunderspecs`/`-Woverspecs`.
```erlang
-module(t).
-export([t/1, q/1]).
-spec t(integer()) -> odd.
t(N) when N rem 2 =/= 0 ->
odd;
t(_) ->
even.
-spec q(integer()) -> positive | negative | zero.
q(N) when N > 0 ->
positive;
q(N) when N < 0 ->
negative.
```
```
$ dialyzer t.erl -Wextra_range -Wmissing_range
Checking whether the PLT /home/ejohogb/.dialyzer_plt is up-to-date... yes
Proceeding with analysis...
t.erl:4:2: The success typing for t:t/1 implies that the function might also return 
'even' but the specification return is 
'odd'
t.erl:10:2: The specification for t:q/1 states that the function might also return 
'zero' but the inferred return is 
'negative' | 'positive'
done in …
```
> dialyzer: Add options for missing/extra range warnings

- erts/emulator/beam/emu/bs_instrs.tab
When getting the tail of a match context, we create
a heapbin instead of a subbin if the size of the
tail is smaller than the size of a subbin.
This is already done in the JIT.
> erts: Make bs_get_tail create a heapbin if possible

- erts/emulator/pcre/pcre_exec.c
Before this fix, the loop_limit would always end up being 10 for global loops which caused a lot of unnecessary yielding.
> erts: Fix reduction count in re

- lib/stdlib/src/shell_docs.erl
- lib/stdlib/test/shell_docs_SUITE.erl
Prior to this change the rendered signature looks like this:
```
1> h(certifi, cacertfile).
\240\240cacertfile()
CACertFile gives the path to the file with an X.509 certificate list containing the Mozilla CA
...
```
With this fix, i.e. by using an ordinary space for padding instead of a non-breaking space, the signature is rendered as expected:
```
1> h(certifi, cacertfile).
cacertfile()
CACertFile gives the path to the file with an X.509 certificate list containing the Mozilla CA
...
```
My env is iterm2 Build 3.4.9beta1 on macOS Catalina 10.15.7 (19H1323) running Erlang master (85530f5fb3), but the problem appeared at least since 24.0 RC1 (see https://github.com/erlef/build-and-packaging-wg/issues/25). I'm not sure if the NBSP handling behaviour is the same in other environments.
> shell_docs: Fix signature rendering

- erts/emulator/beam/jit/x86/instr_arith.cpp
This moves multiplication for small integers inline with overflow checking, along with specialization for when the left or right hand side are immediates.
The original comments related to clobbering `RDX`, I _think_, are incorrect based on how we're using `imul` in 2-operand form instead of 1-operand form (see [reference docs for `imul`](https://www.felixcloutier.com/x86/imul)):
```
We avoid using ARG2 and ARG3 because multiplication clobbers RDX, which is
ARG2 on Windows and ARG3 on SystemV.
```
As a very non-scientific benchmark: based on some tests involving a pure Erlang version of `MurmurHash3_x86_32` with a 1MB input key, this change alone roughly doubled performance for me (30ms originally down to 15ms).
> Improved inline multiplication in JIT for x86

- lib/kernel/doc/src/logger.xml
- lib/kernel/src/logger.erl
- lib/kernel/test/logger_SUITE.erl
This adds function `logger:reconfigure/0` that allows to reset logger configuration to what is configured in `kernel` application configuration. This function is meant to be used by build/run tools like Rebar3 or Mix to provide "production-like" way to configure logging in reliable way.
This function is obviously not safe to be called during application runtime, as it may cause losing some log messages, but it is by far better solution than what we have now, where Rebar3 tries to reimplement such functionality on their own (risking incompatibilities if `logger` configuration will be expanded one day) or just ignore it, and requires users to configure logging on their own (like Mix does, that just relies that users will use Elixir's Logger). Lack of such functionality prevents Elixir from …
> Allow reconfiguration of logger

- lib/stdlib/src/supervisor.erl
- lib/stdlib/test/Makefile
- lib/stdlib/test/supervisor_4.erl
- lib/stdlib/test/supervisor_SUITE.erl
This PR was prompted by [this thread on the Erlang Questions ML](http://erlang.org/pipermail/erlang-questions/2021-September/101433.html), concerning unexpected `noproc` exit reasons due to a race condition when a supervisor child self-terminates and is at the same time terminated via `supervisor:terminate_child/2`. In the course of the discussion, it was discovered that [there exists a condition](http://erlang.org/pipermail/erlang-questions/2021-September/101441.html) where a child could become orphaned when its supervisor dies at a critical moment.
In a nutshell, in the current implementation, the procedure of shutting down a child is as follows:
1) set a monitor on the child
2) unlink the child
3) try to flush out a possible `'EXIT'` message in case the child just died by itself
4) …
> Keep supervisor children linked during shutdown

- erts/emulator/beam/break.c
- erts/emulator/beam/erl_bits.c
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/erl_message.c
- erts/emulator/beam/erl_message.h
- erts/emulator/beam/erl_nfunc_sched.h
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process.h
Only traverse first part of off-heap list that reside on the new-heap, except for writable binaries that are now kept in a separate list.
Fixes #4424.
Earlier during minor GC, traversing the off-heap list was continued to the end over terms residing on the old-heap. This for two reasons:
1. The BIN_OLD_VHEAP value was calculated by adding the sizes of all `ProcBin`'s on the old-heap.
2. All writable binaries are handled by shrinking (reallocating) binaries that have not been written to since last GC. Even binaries residing on the old-heap.
To optimize and only traverse the first part the off-heap list that reside on the new-heap, we now
1. maintain a correct value of BIN_OLD_VHEAP so it does not have to be recalculated during GC.
2. keep all writable binaries in a separate list …
> Further optimize off-heap traversal during minor GC

- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_dtls_connection.erl
- lib/ssl/test/tls_api_SUITE.erl
If the user process unexpectedly dies the state callback needs to
handle "DOWN messages" to detect that and terminate.
Closes #5239
> ssl: Handle DOWN  messages in all states

- lib/kernel/examples/erl_uds_dist/src/erl_uds_dist.erl
This change allows user to specify extra spawn options for net ticker processes in erl_uds_dist, as introduced with OTP-17617 in #5069.
Thanks,
Jérôme
> kernel: Support net_ticker_spawn_options in erl_uds_dist

- lib/ssl/src/ssl_certificate.erl
- lib/ssl/src/ssl_cipher.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/test/openssl_client_cert_SUITE.erl
- lib/ssl/test/ssl_cert_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
ssl: Fix TLS-1.2 RSASSA-PSS  negotiation
Closes #5255
> Ingela/ssl/interop pss tls 1.2/gh 5255/otp 17688

- erts/emulator/drivers/common/inet_drv.c
- lib/kernel/test/gen_tcp_misc_SUITE.erl
If a socket was in active mode and a write error happened
when a send_delay was triggered the driver would read data
from the deallocated tcp_description and crash.
> erts: Fix use after free for send-delay write error

- erts/emulator/beam/jit/x86/instr_arith.cpp
- lib/compiler/test/guard_SUITE.erl
In x86 rax and RET are the same values, so for rem guards, the
value in RET was overwritten with the content of TMP[1] before
the test was done. This caused the rem to not fail as it should
and instead return the contents of TMP[1] which could be anything.
> jit: Fix rem guard bif segfault

- erts/doc/src/erl_ext_dist.xml
- erts/doc/src/erlang.xml
`binary_to_term/1,2` is still encoding atoms using the old Latin-1 format by default if possible.
> Correct docs about atom encoding by binary_to_term

- erts/doc/src/erlang.xml
- system/doc/general_info/upcoming_incompatibilities.xml
Today `erlang:term_to_binary` and `erlang:term_to_iovec` encodes atoms as Latin-1 if possible by default. This can be overridden with option `{minor_version, 2}` to encode atoms as UTF-8 unconditionally.
The aim of this PR is a step to further phase out the old Latin-1 encoding by documenting a planned change of the default atom encoding to UTF-8  in OTP 26. The default for `minor_version` will thus change from 1 to 2 in OTP 26.
> Document UTF-8 as upcoming default atom encoding in OTP 26

- erts/doc/src/erl_ext_dist.xml
Since OTP 23 the `FUN_EXT` encoding is [not decoded](https://github.com/erlang/otp/blob/f0cf38a32b957d956be4170e24ad72f8fca3e3f6/erts/emulator/beam/external.c#L5667-L5672) by `binary_to_term`. It should be marked deprecated as other no longer used tags.
> Mark FUN_EXT as deprecated

- erts/emulator/drivers/common/inet_drv.c
- lib/kernel/src/gen_udp_socket.erl
- lib/kernel/test/gen_udp_SUITE.erl
For Linux, when connecting; dissolve the current association only if connected, that is; not for the socket's first connection.
I used a simple Erlang-only solution for the `gen_udp_socket` legacy compatibility module, so now a `gen_udp:connect/3` with `inet_backend = socket` calls `os:type/0`, for Linux `socket:peername/1`, and finally `socket:connect/2`.  A faster solution could use a new level `otp` socket option to automatically dissolve before reconnect and then do without the two prelude calls.  But we can take that path if it turns out to be actually needed...
Solves GH #5279.
> Linux dgram reconnect

- lib/compiler/src/compile.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/bigE.erl
- lib/stdlib/doc/src/erl_pp.xml
- lib/stdlib/src/erl_pp.erl
- lib/stdlib/test/erl_pp_SUITE.erl
The Erlang compiler will, when expanding records to tuples, introduce
new variables in the abstract representation. As the expansion is done
on the abstract representation, the compiler can safely name the new
variables with names that are not syntactically valid in Erlang source
code (The name starts with a lowercase letter), thus ensuring the
uniqueness of the new names.
The above strategy leads to problems if a user uses the compiler to
produce the abstract representation (using options `E` and `binary`),
transforms it and intends to use the functions in erl_pp to produce
source code, as the generated variable names will be printed as atoms.
This patch introduces an utility function, `erl_pp:legalize_vars/1`,
which when given the abstract representation of a function, will
return an …
> stdlib: Add helper to support round tripping using erl_pp:form/{1,2}

- lib/kernel/src/inet_dns.erl
- lib/kernel/src/inet_dns.hrl
Classes with mDNS high bit set are implemented with the format
`{Class, unicast_response}` for `#dns_query.class`, and
`{Class, cache_flush}` for `#dns_rr.class`.
Only for known classes.
Solves GH-5327
> Handle classes with mDNS high bit

- erts/emulator/sys/common/erl_poll.c
- erts/lib_src/pthread/ethr_event.c
We previously did not limit the timeout value when calling select()
which could cause select() to fail when passed a huge timeout value
causing a runtime system crash.
We currently only use select() on Darwin which accepts a timeout value
of up to 100 million seconds. However, according to posix, select()
implementations are only required to provide 31 days as max timeout
value. We therefore limit the timeout value to 31 days.
Fixes #5339
> Limit timeout value in calls to select()

- lib/ssl/test/ssl_dist_test_lib.erl
- lib/ssl/test/ssl_dist_test_lib.hrl
- Improve visibilty of log and crash dump paths
- Insert easy to parse paths in console and HTML links in test log
- To troubleshoot errors happening on distributed Erlang nodes
> ssl: ssl_dist_test_lib observability adjustment

- lib/tools/emacs/erlang.el
This is a backwards-incompatible fix for issue #5314. More work will be
necessary to be compatible with both new and old versions of xref.
Xref is a package which is also bundled with emacs:
http://elpa.gnu.org/packages/xref.html
Xref switched its own internally defined classes from EIEIO to CL-lib at
emacs-mirror/emacs@86da812afb2572c7fead2bb07570b976bffd7c55.
Modifications:
- Changes erlang-xref-location to be a struct which "includes"
xref-file-location instead of a class which inherits.
- Avoids calling make-instance to create an object from a class.
- Updates comments that make references to classes.
Testing:
1. Install the latest version of the Xref package in Emacs:
(in emacs) M-x package-install RET xref RET
2. Verify that opening any erlang source file will cause an error.
3. …
> Fix the emacs erlang-mode: port EIEIO to CL-lib

- erts/emulator/beam/atom.names
- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_db_hash.c
- erts/emulator/beam/erl_db_hash.h
- erts/emulator/beam/erl_db_util.h
- lib/stdlib/doc/src/ets.xml
- lib/stdlib/src/ets.erl
- lib/stdlib/test/ets_SUITE.erl
Before the commits in this pull request, ETS tables of types set, bag and duplicate_bag used a fixed number of locks to protect the hash buckets from concurrent access. The number of locks was 64 by default but could be changed up to 256 by setting a special flag when compiling the Erlang run-time system. Unfortunately, this is not enough to provide good scalability on modern multi-core machines. This pull request introduces new ETS table options that let the user configure the number of locks used per table or configure a table to automatically adjust the number of locks based on the detected concurrency level.
* Commit 1 (f6e1cb0) Make it possible to set the number of locks used for an ETS table of type set, bag, or duplicate_bag by configuring the table with {write_concurrency, N}, …
> ETS optimizations: Configurable and automatically adjustable number of locks for set, bag, and duplicate_bag

- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/test/re_SUITE.erl
When re:run and friends fail because the regexp is invalid it would print in the error message that the regexp was of
an invalid type. Now it will instead print the compilation error message gotten from running re:compile.
Before:
> re:run("asd",")").
in function  re:run/2
called as re:run("asd",")")
*** argument 2: neither an iodata term nor a compiled regular expression
After:
> re:run("asd",")").
in function  re:run/2
called as re:run("asd",")")
*** argument 2: could not parse regular expression
unmatched parentheses on character 0
> stdlib: Fix erl_error to print re compile errors

- erts/emulator/beam/bif.c
- erts/emulator/beam/break.c
Crash dump slogan tends to be quite long, and limiting it to
200 characters does not allow to understand the cause even in simple
cases (like read-only HOME directory when `erl -name name` wants to
write a .cookie file). Extending `halt` reason helps to have a longer
slogan.
When SUSPEND signal is available, crash dump thread suspends all other
scheduler threads. It may happen that a scheduler thread suspends in
`malloc` call after taking the arena mutex, therefore all subsequent
malloc calls will hang. There are a few malloc calls made by system
libraries: one in fdopen (allocating locked_FD struct), and another in
ctime. Moving code that suspends schedulers helps to avoid this
deadlock, and also solves the problem when file descriptor cannot be
open and erl_crash_dump_v returns keeping …
> erts: crash dump improvements

- erts/doc/src/match_spec.xml
- erts/emulator/beam/atom.names
- erts/emulator/beam/erl_db_util.c
- erts/emulator/test/match_spec_SUITE.erl
```
Tracing: Add new option `caller_line` for fun match spec body
This is similar to `caller`. `caller` gives you {M, F, Arity} while
`caller_line` gives you {M, F, Arity, {File, Line}} where
File:Line is the source location of the function call site.
If the location cannot be found you will get {M, F, Arity, undefined}.
```
-------
(The description below is the outdated one and can be ignored)
```
Tracing: Add new option `caller_line` for fun match spec body
This is similar to `caller`. `caller` gives you {M, F, Arity} while
`caller_line` gives you {M, F, Arity, Line} where Line is the source
code line number in which module M is located.
```
This is my first attempt at #5297 -- please suggest improvements. 
**BTW thanks for the pointers and tips on how to approach this feature**. 
I was …
> Tracing: Add new option `caller_line` for fun match spec body

- lib/stdlib/doc/src/gen_event.xml
- lib/stdlib/doc/src/gen_server.xml
- lib/stdlib/doc/src/gen_statem.xml
- lib/stdlib/src/gen.erl
- lib/stdlib/src/gen_event.erl
- lib/stdlib/src/gen_server.erl
- lib/stdlib/src/gen_statem.erl
- lib/stdlib/src/sys.erl
- lib/stdlib/test/dummy_h.erl
- lib/stdlib/test/erl_internal_SUITE.erl
- lib/stdlib/test/gen_event_SUITE.erl
- lib/stdlib/test/gen_server_SUITE.erl
- lib/stdlib/test/gen_server_SUITE_data/format_status_server.erl
- lib/stdlib/test/gen_statem_SUITE.erl
- lib/stdlib/test/gen_statem_SUITE_data/format_status_statem.erl
This new format_status callback can also be used to format the messages in the sys logger or crash reports. It is
built-in order to make it possible to extend in the future with more values.
I've opened this PR in order to get some feedback on the new API before starting working on gen_statem/gen_event and tests for all of this.
Example usage: 
```erlang
-spec format_status(Status) -> NewStatus when
Status :: { state => term(),
message => term(),
reason => term(),
logs => [sys:system_event()] },
NewStatus :: Status.
format_status(Status) ->
maps:map(
fun(state,State) ->
maps:remove(private_key, State);
(message,{password, _Pass}) ->
{password, removed};
(_,Value) ->
Value
end, Status).
```
Fixes #4673
> stdlib: Add gen_server:format_status/1

- lib/kernel/doc/src/socket.xml
Hello,
while browsing the `socket` module documentation I noticed a small typo.
Best regards
Libor
> Fix typo in `socket` docs

- erts/emulator/test/hash_property_test_SUITE.erl
- lib/kernel/src/rpc.erl
- lib/kernel/test/Makefile
- lib/kernel/test/erl_distribution_wb_SUITE.erl
- lib/kernel/test/erpc_SUITE.erl
- lib/kernel/test/erpc_SUITE_data/Makefile.src
- lib/kernel/test/erpc_SUITE_data/fwd_node.c
- lib/kernel/test/kernel_SUITE.erl
- lib/kernel/test/rpc_SUITE.erl
- lib/sasl/test/Makefile
- lib/sasl/test/installer.erl
- lib/sasl/test/otp_vsns.erl
- lib/sasl/test/release_handler_SUITE.erl
- lib/sasl/test/release_handler_SUITE_data/lib/installer-1.0/ebin/installer.app
- lib/sasl/test/rh_test_lib.erl
- lib/sasl/test/sasl_SUITE.erl
- lib/sasl/test/test_lib.hrl
- lib/stdlib/test/Makefile
- lib/stdlib/test/stdlib_SUITE.erl
erpc was introduced in OTP 23. That is, a lot of (most) rpc operations against nodes of releases prior to OTP 23 will fail.
> rpc require erpc support as of OTP 25

- .github/scripts/init-pre-release.sh
- HOWTO/OTP-PATCH-APPLY.md
- README.md
- lib/megaco/Makefile
- scripts/build-otp-tar
One commit from @marcellanz (#5311) removing `otp_build autoconf` from various scripts and docs (except README.md). Also thanks to @v0idpwn and @kpy3 for earlier stabs at `otp_build autoconf` in README.md.
Added some comments and a "git checkout" step to the build instructions in README.md,
which can be viewed here:
https://github.com/sverker/otp/tree/sverker/otp_build-autoconf-cleanup
> Remove superfluous "otp_build autoconf" and improve README build instructions

- erts/emulator/beam/erl_bits.c
Avoid remainder (%) op in most common case when unit is 8 bits.
> Micro optimization in bs_append

- erts/doc/src/erl_cmd.xml
- erts/emulator/beam/erl_cpu_topology.c
- erts/emulator/beam/erl_cpu_topology.h
- erts/emulator/beam/erl_init.c
- erts/emulator/test/scheduler_SUITE.erl
- erts/include/internal/erl_misc_utils.h
- erts/lib_src/common/erl_misc_utils.c
Reading CPU topology slows down startup when starting many
parallel instances of ERTS on systems with large amount of cores,
this PR adds the possibility to skip it.
Use new emulator flag +ssrct to skip reading CPU topology.
Reading CPU topology will also be skipped if a user defined topology
is set using the +sct flag.
Fixes #5204
> Enable possibility to skip reading CPU topology at startup

- erts/emulator/beam/predicates.tab
- erts/emulator/test/op_SUITE.erl
The type-based optimizations introduced in 3617610fbc40 (#5316) could
cause `divint` and `rem` instructions to be fused when it was not
safe.
Closes #5401.
> JIT: Fix incorrect code generation for div/rem sequence

- lib/parsetools/test/leex_SUITE.erl
- lib/parsetools/test/yecc_SUITE.erl
Replace test_server:start_node with `?CT_PEER`, providing
test resilience and even allowing running the same test
concurrently on the same host.
> [parsetools] peer-ify parsetools application

- lib/kernel/examples/erl_uds_dist/src/erl_uds_dist.erl
The calls to file:open and file:delete are using the [raw] option to bypass the file server but one call to file:delete was missing the option.
Thanks, Jérôme
> kernel: Add a missing raw option in erl_uds_dist

- lib/stdlib/doc/src/supervisor_bridge.xml
- lib/stdlib/src/supervisor_bridge.erl
Add `{via, Module, ViaName}` that was missing, and correct the `Name` in `{global, Name}` to `term()`.
Without this fix, running dialyzer on a module calling for instance
```erlang
start_link() ->
supervisor_bridge:start_link({via, gproc, {n, l, {x, y}}}, ?MODULE, []).
```
would wrongly lead to this error:
```
$ dialyzer -q --build_plt --output_plt p.plt --apps erts kernel stdlib
$ dialyzer -q --plt p.plt x.beam 
x.erl:34:1: Function start_link/0 has no local return
x.erl:35:34: The call supervisor_bridge:start_link
({'via', 'gproc', {'n', 'l', {'x', 'y'}}},
'x',
[]) breaks the contract 
(SupBridgeName, Module, Args) -> Result
when
SupBridgeName :: {'local', Name} | {'global', Name},
Name :: atom(),
Module :: module(),
Args :: term(),
Result :: {'ok', Pid} | 'ignore' | {'error', Error}, …
```
> Fix spec for name for supervisor_bridge:start_link

- lib/stdlib/src/supervisor.erl
This prevents annoying shutdown_error logs from being printed
in cases both the process and its supervisor started shutting
down at the same time.
See https://github.com/erlang/otp/pull/5201#issuecomment-951004125
> supervisor: Add missing shutdown clauses

- lib/stdlib/test/calendar_SUITE.erl
- lib/stdlib/test/dets_SUITE.erl
- lib/stdlib/test/epp_SUITE.erl
- lib/stdlib/test/erl_pp_SUITE.erl
- lib/stdlib/test/error_logger_h_SUITE.erl
- lib/stdlib/test/ets_SUITE.erl
- lib/stdlib/test/gen_fsm_SUITE.erl
- lib/stdlib/test/gen_server_SUITE.erl
- lib/stdlib/test/io_SUITE.erl
- lib/stdlib/test/pool_SUITE.erl
- lib/stdlib/test/proc_lib_SUITE.erl
- lib/stdlib/test/qlc_SUITE.erl
- lib/stdlib/test/shell_SUITE.erl
- lib/stdlib/test/tar_SUITE.erl
Replace usage of `test_server:start_node` with `?CT_PEER`.
Additionally, disable local_time_to_universal_time_dst when running in
Pacific Time (as it inevitably fails), and fix tar_SUITE test that
fails when `compile` module is taken from the installed system (in
that case compile.beam would be read-only, and after un-tarring
mode will be read-write, making this test fail).
> [stdlib] peer-ify application tests

- lib/ssl/test/ssl_test_lib.erl
Before this patch, run_where and node_to_hostip were returning
different IP addresses, failing large number of tests when /etc/hosts
file was containing
host 127.0.0.1
host.domain 127.0.0.2
It was happening because `node()` was `test_server@host`, while
`net_adm:localhost()` was returning `host.domain`, so they were
returning different IP addresses, subsequently failing in verification
in check_result/4.
> [ssl] fix SSL tests run in specific environment

- erts/include/internal/gcc/ethr_atomic.h
- erts/include/internal/gcc/ethr_dw_atomic.h
This fixes the following error:
```
In file included from ../include/internal/gcc/ethread.h:381,
from ../include/internal/ethread.h:382,
from beam/erl_threads.h:248,
from beam/sys.h:536,
from beam/jit/beam_jit_common.hpp:35,
from beam/jit/beam_jit_common.cpp:21:
../include/internal/gcc/ethr_dw_atomic.h:232:34: error: expected ',' or '...' before 'new'
232 |         ETHR_NATIVE_SU_DW_SINT_T new,
|                                  ^~~
../include/internal/gcc/ethr_dw_atomic.h: In function 'ethr_sint128_t ethr_native_su_dw_atomic_cmpxchg_mb(ethr_native_dw_atomic_t*, ethr_sint128_t)':
../include/internal/gcc/ethr_dw_atomic.h:237:43: error: 'old' was not declared in this scope
237 |     return __sync_val_compare_and_swap(p, old, new);
|                                           ^~~ …
```
> Fix C++ compiler error on Raspberry Pi 4

- erts/etc/darwin/Info.plist
I'm building an `.app` bundle with it's own `Info.plist`. In my plist,
the values I'm putting in seem to be ignored, when running the app,
the app name in the menu bar is always "Erlang".
With this patch, the `CFBundle*` from my app's plist take effect.
One should be able to re-produce this issue by executing this shell
script:
```sh
#!/bin/bash
set -e
rm -rf Example.app
mkdir -p Example.app/Contents/MacOS
cat <<EOF > Example.app/Contents/Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleName</key>
<string>Example</string>
<key>CFBundleDisplayName</key>
<string>Example</string>
</dict>
</plist>
EOF
cat <<EOF > Example.app/Contents/MacOS/Example …
```
> erts: Remove `CFBundle*` fields from `Info.plist`

- lib/compiler/src/v3_core.erl
When running Dialyzer on this example:
-spec foo() -> ok.
foo() ->
case foo of
<<"bar">> -> ok;
_ -> ok
end.
the following error would be generated:
The pattern <<6447474:24>> can never match the type 'foo'
That message is very confusing. Unfortunately, Dialyzer has only
access to Core Erlang version of the code, so there is no easy way to
exactly pretty print code fragments. However, the optimization of
strings that produces those huge numbers can be disabled when Dialyzer
invokes the compiler, producing the following message:
The pattern <<98,97,114>> can never match the type 'foo'
Closes #5429.
> Somewhat improve pretty printing of binaries in Dialyzer

- lib/kernel/src/gen_tcp_socket.erl
This is behaviour exposed by the `inet` backend and also the expected behaviour, as it allows to use `socket` backend together with systemd socket activation where the application receives bound socket with messages already in queue.
Close #4680
> Do not bind on FD with undefined ifaddr

- lib/common_test/src/ct_gen_conn.erl
Add missing option to spec for ct_gen_conn:start/4.
Without it, dialyzer thinks ct_telnet:open would always fail
since it supplies this option.
CC: @tomas-abrahamsson @edvreu
> common_test: fix spec

- lib/common_test/priv/ct_default.css
- lib/common_test/src/ct_logs.erl
This adds "anchor links" to the common_test log output. This enables linking to a particular log entry.
A-tags with an ever-incremented id, and href to that same #id are added after 'hd' parts of logged data.
As suggested/inspired by: @tomas-abrahamsson
> common_test: add anchor links to log

- lib/ssl/src/dtls_record.erl
- lib/ssl/src/ssl_record.erl
- lib/ssl/src/tls_connection.erl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_record.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
- lib/ssl/test/tls_1_3_record_SUITE.erl
In TLS 1.2 and prior, the client and server 32 byte random nonce was
defined as the first 4 bytes being the UTC epoch followed by 28 bytes
random. In TLS 1.3 the client and server random nonce is defined as 32
bytes random.
This commit passes the tls_version() tuple so when the empty security
parameters are initialized and generate client and server random, the
version specific random nonce is generated accordingly.
For further details see:
RFC 5246 The Transport Layer Security (TLS) Protocol Version 1.2,
Section 7.4.1.2. Client Hello
RFC 8446 The Transport Layer Security (TLS) Protocol Version 1.3,
Section 4.1.2. Client Hello
> ssl: 32 bytes random for random nonce for TLS 1.3

- erts/emulator/beam/global.h
In the testcase binary_SUITE:t2b_deterministic a very large hash map is created and encoded. This lead to a WSTACK_RESERVE call with an N value of 4 000 000 which made the pointer wrap around zero and thus the stack was not grown as it should.
As far as I can tell this can only happen in the new deterministic term_to_binary.
> erts: Fix integer overflow problem in WSTACK

- erts/emulator/test/exception_SUITE.erl
- lib/kernel/src/erl_erts_errors.erl
Before this fix the error reason would be "invalid port name",
which is true but not as helpfull as it could be. So now it returns
"must be spawn_executable".
> erts: Fix open_port({spawn,"a"},[{args,[]}]) error info

- make/run_make.mk
Before this commit you had to do 'make -f */Makefile test'
in order to run the erts tests, now you can just run 'make test'.
> erts: Make 'test' PHONY so that make test works
