erlang/otp

- lib/kernel/src/logger.erl
- lib/kernel/test/logger_SUITE.erl
- lib/kernel/test/logger_env_var_SUITE.erl
The variable name in the code was not the same as in the docs. So we fix the code and add a test case to make sure that it works.
Thanks, @sirihansen for reporting this issue.
> logger: Fix logger_metadata app env var

- erts/emulator/test/distribution_SUITE.erl
- lib/kernel/src/dist_util.erl
- lib/kernel/src/inet_tcp_dist.erl
- lib/ssl/src/inet_tls_dist.erl
- lib/ssl/test/ssl_dist_SUITE.erl
- lib/ssl/test/ssl_dist_test_lib.erl
The initial check for ipv4 vs ipv6 did not use the
erl_epmd interface to lookup the address which caused
invalid addresses to not be resolvable by erl_epmd callback
modules.
Closes #5334
> kernel: Fix erl_epmd:address_please

- lib/parsetools/doc/src/yecc.xml
The text already mentions "position (eg. line number)" and the spec also refers to location in 
https://github.com/erlang/otp/blob/master/lib/parsetools/include/yeccpre.hrl#L50,
so this change is only to avoid any misunderstanding that the position must be a line number.
> Update some vars (line to position) in yecc docs

- lib/parsetools/include/yeccpre.hrl
- lib/parsetools/test/yecc_SUITE.erl
The standard prologue file (`yeccpre.hrl`) for yecc could crash while
attempting to report a syntax error involving a token not produced by
the `erl_scan` module.
For example, the token `{string,0,<<"hello">>}` looks like a string
token produced by `erl_scan`, but the string value is a binary instead
of the expected list and the default implementation of
`yecctoken_to_string/1` would crash when asked to print it.
Make `yecctoken_to_string/1` more resilient against crashing by
printing the entire token as is if there is a crash when printing
it in the usual way.
(Note: A parser that uses its own non-standard scanner should use its
own customized prologue file if nicely printed tokens are desired.)
> yeccpre.hrl: Never crash when printing non-standard tokens

- erts/emulator/nifs/common/socket_util.c
iOS doesn't ship <net/if_arp.h> so that file can't be included on that platform. This fix removes the include on iOS.
It seems it was anyway only included to check for additionally defined constants, so no further change here. 
FYI @garazdawi
> Fix iOS build

- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process_dump.c
- lib/observer/src/observer_html_lib.erl
The optimization in #2351 inadvertently changed the way that the first stackframe in crash dumps is displayed. This PR fixes that problem in crash dumps and updates crash dump viewer to be able to read the stackframe of the broken processes.
Problem was also reported in #5459
> Fix process stack in crashdump

- erts/doc/src/erl_cmd.xml
- erts/doc/src/erlang.xml
- erts/doc/src/init.xml
- lib/compiler/test/compile_SUITE.erl
- lib/debugger/src/dbg_wx_settings.erl
- lib/dialyzer/doc/src/dialyzer_chapter.xml
- lib/dialyzer/src/dialyzer_cl.erl
- lib/dialyzer/src/dialyzer_plt.erl
- lib/dialyzer/test/plt_SUITE.erl
- lib/erl_docgen/priv/bin/validate_links.escript
- lib/kernel/src/auth.erl
- lib/kernel/test/erl_distribution_SUITE.erl
- lib/kernel/test/init_SUITE.erl
- lib/observer/src/observer_wx.erl
- lib/stdlib/doc/src/beam_lib.xml
- lib/stdlib/doc/src/filename.xml
- lib/stdlib/src/beam_lib.erl
- lib/stdlib/src/c.erl
- system/doc/reference_manual/distributed.xml
This PR changes so that the location of some system global files can be configured using XDG. The files are:
* $XDG_CONFIG_HOME/erlang
* `.erlang`
* `.erlang.cookie`
* `.erlang.crypt`
* `debugger`
* $XDG_CACHE_HOME/erlang
* `.dialyzer_plt`
In order to keep backward compatibility, the config files are first read from $HOME, and then if they don't exist the $XDG_CONFIG_HOME/erlang directory is checked.
Since the dialyzer plt is a cache than a config file I decided to change the default location for it.
I decided to not do anything about `.erlang.hosts` as that file is hardly used by anyone.
Closes #5016
> Allow some configuration to be read from XDG config

- lib/kernel/doc/src/pg.xml
Some function descriptions in `pg` refer to a parameter named `Name` but it should be `Group`.
An example can be seen at https://www.erlang.org/docs/24/man/pg.html#join-2
Likely happened because those parameters were named `Name` in `pg2`.
> Update pg module docs

- lib/debugger/src/dbg_icmd.erl
- lib/stdlib/src/erl_eval.erl
- lib/stdlib/src/qlc.erl
- lib/stdlib/src/shell.erl
- lib/stdlib/test/qlc_SUITE.erl
The shell relies on an implicit contract
with erl_eval where a value triplet is allowed.
Unfortunately, to support this, evaluating
anonymous functions would require a look-ahead
traversal to hide any value triplet from
erl_lint and this affected performance negatively.
This patch removes this undocumented contract
and removes the look-ahead. To address this,
we took different approaches:
1. v(N) was expanded to a value before evaluated.
Now, we process and validate the arguments,
but communicate with the shell process to get
the value, similar to how history() works
2. References, Ports, and PIDs were converted to
variables and then replaced to values. Now,
we expand `#PID<0.13.0>` into an expression
such as `erlang:list_to_pid("#PID<0.13.0>").`
3. Finally, the prompt evaluation would …
> Remove undocumented {value, Value, Ann} in erl_eval

- lib/dialyzer/src/Makefile
- lib/dialyzer/src/dialyzer.app.src
- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_analysis_callgraph.erl
- lib/dialyzer/src/dialyzer_behaviours.erl
- lib/dialyzer/src/dialyzer_callgraph.erl
- lib/dialyzer/src/dialyzer_cl.erl
- lib/dialyzer/src/dialyzer_contracts.erl
- lib/dialyzer/src/dialyzer_plt.erl
- lib/dialyzer/src/dialyzer_typegraph.erl
- lib/dialyzer/src/erl_types.erl
- lib/dialyzer/test/Makefile
- lib/dialyzer/test/dialyzer_cl_SUITE.erl
- lib/dialyzer/test/dialyzer_cl_SUITE_data/call_to_missing_example.erl
- lib/dialyzer/test/dialyzer_cl_SUITE_data/previously_defined.erl
- lib/dialyzer/test/dialyzer_cl_SUITE_data/unknown_function_example.erl
- lib/dialyzer/test/dialyzer_common.erl
- lib/dialyzer/test/plt_SUITE.erl
- lib/dialyzer/test/plt_SUITE_data/type_deps.erl
Dialyzer now tracks the dependencies between modules induced by
type-level information, such as type definitions & specs, as well
as behaviour callbacks.
Previously, only function calls were considered when computing dependencies.
This was incomplete because changes to types and behaviours can also affect
the result of a Dialyzer analysis.
Aside from the immediate impact of this change, it also serves as a prelude to
adding full incrementality to Dialyzer.
> dialyzer: Track type & behaviour dependencies

- lib/common_test/src/ct_slave.erl
- lib/stdlib/src/otp_internal.erl
- system/doc/general_info/DEPRECATIONS
There is not a single usage for ct_slave within OTP codebase,
proving that replacement is complete.
> [ct_slave] deprecate the module completely

- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/src/lists.erl
Right now, lists:seq performs as documented if you provide bad input.
> Failures:
> - If To < From - Incr and Incr > 0.
> - If To > From - Incr and Incr < 0.
> - If Incr =:= 0 and From =/= To.
However, the current error message is really confusing when it can be a lot better with just a little bit of rejigging.
```
% currently:
> lists:seq(1,5,-1).
** exception error: no true branch found when evaluating an if expression
in function  lists:seq/3 (lists.erl, line 264)
% with this patch:
> seq:seq(1,5,-1).   
** exception error: no function clause matching seq:seq(1,5,-1) (seq.erl, line 32)
```
This error brings your attention to the incorrect input you've provided rather than pointing to some possible internal misbehavings.
The code still behaves as it should with all inputs I quickly …
> Improve error messages for lists:seq/3

- .gitignore
OTP no longer contains HiPE or GS, and no longer supports OSE.
> .gitignore: cleanup no longer relevant ignores

- erts/emulator/nifs/win32/win_prim_file.c
Fixes https://github.com/erlang/otp/issues/5527
> erts: Fix memory leak in efile_read_handle_info on Windows

- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_db_catree.c
- erts/emulator/beam/erl_db_hash.c
- erts/emulator/beam/erl_db_tree.c
- erts/emulator/beam/erl_init.c
- erts/emulator/beam/erl_threads.h
- erts/include/internal/ethr_mutex.h
- erts/lib_src/common/ethr_mutex.c
- lib/stdlib/test/ets_SUITE.erl
The amount of memory used for reader groups can be very
large on systems with many cores, so it needs to be part
of the ets table's memory utilization. We use that memory
to calculate how many tables can be created when testing.
> erts: Fix ets memory calculation for read_concurrency

- lib/ssl/doc/src/ssl.xml
Some typos and language errors fixed.
A note about the changing "users certificate": I'm not sure what was the meaning intended here, I went with a compound noun - "user certificate", but I feel like a possessive - "user's certificate", is equally valid.
As a little disclaimer, I'm not an English native speaker.
> Fix some typos in SSL docs

- lib/stdlib/src/erl_eval.erl
* {value, Value, Binding} was an implicit contract
with shell that is no longer used
* Both record and tuple calls have been deprecated
and removed for quite some time
> Remove unused erl_eval code

- lib/erl_interface/configure.ac
Currently, `AC_CHECK_LIB`  is used for deciding whether to link [Erl_Interface][1] (and therefore [erl_call][2]) against libnsl. This results in linking against libnsl _if possible_, rather than _if necessary_. The Autoconf documentation [says][3]:
> `AC_CHECK_LIB` requires some care in usage, and should be avoided in some common cases. Many standard functions like `gethostbyname` appear in the standard C library on some hosts, and in special libraries like `nsl` on other hosts. On some hosts the special libraries contain variant implementations that you may not want to use. These days it is normally better to use `AC_SEARCH_LIBS([gethostbyname], [nsl])` instead of `AC_CHECK_LIB([nsl], [gethostbyname])`.
Another issue with glibc specifically is that the usual backward compatibility isn't …
> Avoid unnecessary linking against libnsl

- erts/emulator/utils/beam_makeops
Here is another PR, sorting the code generated in beamasm_protos.h, to get closer to deterministic builds.
EDIT: Linked to #4417
> erts: Generate beamasm_protos.h deterministically

- erts/doc/src/erlang.xml
- lib/runtime_tools/doc/src/scheduler.xml
- lib/runtime_tools/src/scheduler.erl
- lib/runtime_tools/test/scheduler_SUITE.erl
- Add `scheduler:get_sample/0` and `scheduler:get_sample_all/0`
- Clarify docs of `scheduler` module regarding system flag `scheduler_wall_time`.
- Clarify docs of `erlang:system_flag(scheduler_wall_time,_)`
- Fix bug in `scheduler:utilization(Seconds)` not always restoring `scheduler_wall_time`.
Closes #5425
> Improve runtime_tools scheduler (utilization) module

- system/doc/reference_manual/expressions.xml
The previous wording may result into false impression that the compiler performs checks to ensure that a filter is "well-formed", while a filter may be any expression.
> Correct wording about filters in comprehensions

- lib/ssh/src/ssh_file.erl
- lib/ssh/src/ssh_message.erl
Encoding of OpenSSH Key V1 is technically listed as an experimental feature so this isn't the most crucial. But in playing with it I discovered the encoding is incorrect when writing the "encrypted" section of Ed25519/Ed448 keys
Currently, we only write the 32 bytes of the Private key. However, the encrypted section is 64 bytes of a "secret" key which includes the private key and public key combined. This is confirmed through a few sources:
* [sshkey.c](https://github.com/openssh/openssh-portable/blob/master/sshkey.c#L3317-L3320) of OpenSSH writes both [public and private when serializing the private section](https://github.com/openssh/openssh-portable/blob/master/sshkey.c#L3207)
* In the current implementation the [32 bytes of the public key was also striped from the return of decoding …
> Fix OpenSSH encoding of Ed25519/Ed448

- HOWTO/INSTALL.md
- erts/configure
- erts/configure.ac
- erts/doc/src/erl_nif.xml
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_nif.h
- erts/emulator/beam/global.h
- erts/emulator/utils/make_driver_tab
or any modules with "exotic" characters in the name (like '.').
* Add STATIC_ERLANG_NIF_LIBNAME macro which is used both to
identify the archive name and create a unique C identifier for
the _nif_init function.
* Run all static *_nif_init functions unconditionally at VM boot to
get the corresponding module names. erlang:load_nif/2 can then
match only against module names and does not have to care about
archive filenames for static nifs.
> Add support for static Elixir NIF modules

- .github/scripts/build-macos-wxwidgets.sh
- .github/scripts/build-macos.sh
- .github/workflows/main.yaml
Another stab at https://github.com/erlang/otp/issues/4487.
We statically link OpenSSL:
% otool -L otp/otp/lib/crypto-5.0.2/priv/lib/crypto.so
otp/otp/lib/crypto-5.0.2/priv/lib/crypto.so:
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
See https://rentzsch.tumblr.com/post/33696323211/wherein-i-write-apples-technote-about-openssl-on for rationale.
We also statically link wxWidgets:
% otool -L otp/otp/lib/wx-2.0.1/priv/wxe_driver.so
otp/otp/lib/wx-2.0.1/priv/wxe_driver.so:
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 164.0.0) …
> gh-actions: Add macOS builds

- lib/stdlib/doc/src/filename.xml
> Fix doc for filename:basedir(user_log,..) on Darwin

- lib/public_key/doc/src/public_key.xml
- lib/public_key/src/public_key.erl
- lib/public_key/test/public_key_SUITE.erl
- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_config.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
- lib/ssl/test/tls_api_SUITE.erl
Implementing password fun option for ssl connect API
This change allows password option to accept as a value
either a string or a fun. Added specific tests and
documentation.
The motivation for this change is to better protect a
private key. If the private key is protected by password the
password may be retreived using user supplied function therefore
enabling storing password in a secure vault or something similar.
This replaces #5320
> public_key,ssl: add password fun for decoding keyfiles

- erts/emulator/beam/bif.c
Since the args of spawn_request may end up in a trace we need to allocate them on the heap of the spawning process.
We cannot use a temporary heap for this as allocates on normal heap and this will lead to stray pointers on the heap during gc. Stray pointers are not always a problem as any dead data is ignored, but if the pointers end up in a heap fragment they are not ignored... so we need to do a proper allocation of the terms.
This bug has existed since OTP-23.0.
> erts: Fix spawn_request trace bug

- erts/emulator/sys/common/erl_check_io.c
- erts/emulator/test/busy_port_SUITE.erl
- erts/emulator/test/driver_SUITE.erl
- erts/emulator/test/port_SUITE.erl
- erts/emulator/test/process_SUITE.erl
- erts/emulator/test/trace_local_SUITE.erl
Some test cases produce 20+ Mb of debug output which does
not help to figure out a problem. This change suppresses
logs, leaving a chance to remove suppression for local runs.
> [erts] reduce console output for Common Test

- lib/compiler/src/beam_kernel_to_ssa.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/src/v3_core.erl
- lib/compiler/src/v3_kernel.erl
- lib/compiler/test/beam_except_SUITE.erl
- lib/compiler/test/bs_match_SUITE.erl
- lib/compiler/test/guard_SUITE.erl
- lib/compiler/test/inline_SUITE.erl
Consider this module:
-module(bug).
-export([foo/0]).
foo() ->
fun(a) -> ok end(b).
The call to the fun will always fail, which will be noted by
the compiler:
1> c(bug).
bug.erl:5:5: Warning: no clause will ever match
%    5|     fun(a) -> ok end(b).
%     |     ^
{ok,bug}
What is unexpected is that the exception that is raised is not
a `function_clause` exception:
2> bug:foo().
** exception error: no case clause matching {b}
in function  bug:foo/0 (bug.erl, line 5)
This confusing `case_clause` exception started to appear in OTP 24
because of 72675baaa9fd30 (#4545) that inlines funs that are
immediately used.
Before OTP 24, when the fun was not inlined, the exception would be:
2> bug:foo().
** exception error: no function clause matching bug:'-foo/0-fun-0-'(b) (bug.erl, line 5)
The reason …
> Eliminate confusing `case_clause` exception

- lib/eldap/src/eldap.erl
- lib/eldap/test/eldap_basic_SUITE.erl
According to the ldap ASN1 the dnAttributes should be a bool, instead it was generated as a string.
Also add a couple of test to verify the filter behaves correctly.
> Fix eldap extensibleMatch dnAttributes option

- lib/stdlib/src/gen_event.erl
- lib/stdlib/test/gen_event_SUITE.erl
Currently we get error messages like the following logged:
```
2021-11-09T09:27:03.949055+00:00 error: Generic event handler ... crashed. Installed: .... Last event: {badarg,[{ets,match_object,[...],[{error_info,#{cause => id,module => erl_stdlib_errors}}]}|...]}. State: {event,...}. Reason: {state,...}.
```
This is very confusing (caused us to go on a rabbit hunt through our own code for transposed `State`/`Reason` in `{stop,...}` return values).
> fix param ordering of gen_event crash

- lib/observer/src/etop_txt.erl
The field widths are calculated depending on what the underlying io
driver reports as max column width.
The fields are allowed to use the column width they need if they column
budget allows it. The field widths are deducted in priority order and if
there is space left the calculated width is used otherwise the default
field width is used.
If the underlying io driver can't give any column width, the default
column width budget of 89 characters is used. This is the legacy hard
coded width, plus two spaces between reductions, memory, and msgq
fields.
Fixes #5080
Signed-off-by: Per Andersson <avtobiff@foo.nu>
> observer/etop: Calculate field width with available columns

- lib/common_test/src/ct_hooks_lock.erl
- lib/common_test/src/cth_surefire.erl
- lib/common_test/test/ct_surefire_SUITE.erl
- lib/common_test/test/ct_surefire_SUITE_data/surefire_SUITE.erl
This PR adds file and line number info to the surefire report so that tools (such as [publish-unit-test-result-action](https://github.com/EnricoMi/publish-unit-test-result-action)) can locate where a failed test case is.
The algorithm for finding the source file is very naive, so most users will most likely need to post-process the XML file in order to get the correct path.
> ct: Add correct file and line to surefire report

- lib/eunit/src/eunit_data.erl
- lib/eunit/src/eunit_lib.erl
There's no documented way to do this, and we can't add one without ripping out some nice optimizations, so this PR removes it altogether.
"Fixes" https://github.com/erlang/otp/issues/5617
> eunit: Remove fun_parent/1

- lib/ssl/src/tls_v1.erl
Before TLS-1.3 cipher suites from previous versions are inclusive.
No rsa suites are included as default values so this function
should list all still possible rsa suites.
> ssl: Do not exclude legacy suite

- lib/kernel/test/socket_SUITE.erl
- lib/kernel/test/socket_test_lib.erl
Before this change, socket_SUITE fails most of IPv4 tests
with IPv4 address available only on loopback adapter. With this
patch:
- IPv4-specific tests will be skipped on IPv6-only nodes
- non-specific tests will utilise either v4 or v6, depending
on availability (with v4 preferred)
- minor cleanup (removed unused suite/doc functions)
> socket_SUITE: do not fail on IPv6-only nodes

- lib/public_key/src/pubkey_pbe.erl
- lib/public_key/src/pubkey_pem.erl
- lib/public_key/src/public_key.erl
- lib/ssl/src/ssl.erl
A user has reported that while `{password, <<"pass">>}` doesn't work, `{password, [<<"pass">>]}` does. It doesn't seem to be useful to restrict the password to a list string.
For context: RabbitMQ has an option that allows encrypting passwords, but decrypted passwords are always returned as binary. It would be good to avoid special casing this.
This is a very early draft of a potential PR. There's a couple more options that could be improved by allowing binary strings as well.
@IngelaAndin What do you think?
> ssl: Allow binary keyfile passwords

- lib/syntax_tools/src/erl_syntax_lib.erl
As per issue #4671:
`erl_syntax_lib:analyze_attribute({attribute,17,mark,mark_1}).`
returns `{mark, {mark, mark_1}}` due to the attribute being wrapped on line 1320:
`{A, analyze_attribute(A, Node)}`
when what would be expected as per the documentation is:
`{mark, mark1}`
Returning *just* the Info from `{_, Info} = analyze_wild_attribute(Node)`
within analyze_attribute/2, this double wrapping does not occur, fixing
the original issue.
This PR is basically a reopening of https://github.com/erlang/otp/pull/5499 (was unable to actually reopen that PR) including a fix that was missed.
> Fixes analysing a wild attribute to return Info

- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
This pull request makes the `beam_ssa_pre_codegen` pass of the compiler about 4 times faster for the example in #5140.
> Reduce compile time for huge straight-line functions

- lib/stdlib/src/c.erl
It should be possible to strat erlang without having a home
and the call to filename:basedir crashes if no home is set.
> stdlib: Allow erlang to be started without HOME set

- lib/inets/src/http_lib/http_request.erl
- lib/inets/test/httpc_SUITE.erl
- lib/stdlib/src/uri_string.erl
- lib/stdlib/test/uri_string_SUITE.erl
- adjust port normalize functionality
- remove port subcomponent if port value is empty or key in URIMap if undefined
> stdlib: normalize empty port in uri_string

- lib/compiler/src/v3_core.erl
- lib/compiler/test/bs_match_SUITE.erl
In both binary construction and matching, literal integer values
are allowed in float segments, and they are automatically coerced
to floats.
Thus, the compiler automatically rewrites code such as the following:
foo() ->
<<0/float-native>> = <<0/float-native>>.
to:
foo() ->
<<0.0/float-native>> = <<0.0/float-native>>.
However, if the order of `native` and `float` were switched like this:
bar() ->
<<0/native-float>> = <<0/native-float>>.
the compiler would fail to coerce the `0` in the binary pattern and would
end up with:
bar() ->
<<0/native-float>> = <<0.0/native-float>>.
which would obviously not match.
> Fix coercion of integer literals to floats in binary matching

- erts/preloaded/src/erlang.erl
- lib/common_test/src/ct.erl
- lib/common_test/src/test_server.erl
- lib/dialyzer/src/erl_bif_types.erl
- lib/dialyzer/test/small_SUITE_data/results/try2
- lib/stdlib/src/unicode.erl
Refine the types for `max/2`, `min/2`, and `erlang:raise/3`.
> Dialyzer: Refine the types for some BIFs

- erts/etc/win32/nsis/erlang20.nsi
- lib/tools/emacs/README
This PR should solve two issues - 
1) When installing a newer version, the old version remains, but uninstalling the older version removes the newer version from the start menu. This is solved by always updating in-place and using a single folder
2) This should write the version and the publisher in the uninstall entry
> Update Install Location and Registry Keys

- erts/preloaded/src/erts_internal.erl
- lib/kernel/src/auth.erl
- lib/kernel/src/code_server.erl
- lib/stdlib/doc/src/ets.xml
- lib/stdlib/src/dets.erl
- lib/stdlib/src/digraph.erl
- lib/stdlib/src/ets.erl
Rename some ets types to clearer name:
* access() -> table_access()
* tab() -> table()
* type() -> table_type()
* comp_match_spec() -> compiled_match_spec()
The exported types have their old variants kept for backward compatibility.
The types `table_access` and `table_type` have been exported.
For consistency, I also renamed all usage of `Tab` to `Table` within the ets module itself.
> ets: Rename and export some types

- lib/erl_docgen/doc/src/Makefile
- lib/erl_docgen/doc/src/block_tags.xmlsrc
- lib/erl_docgen/priv/bin/codeline_preprocessing.escript
- lib/erl_docgen/priv/dtd/common.dtd
The regexp for finding <codeinclude> did not take into
consideration that elements in xml do not need to have
a closing tag. We shouldn't really try parsing xml with
regexp, but we try to make the best of the situation.
This commit also removed codeinclude from the dtd so that
at least in the future if any other codeinclude falls through
the regexp matching the xmllint will catch it.
Closes #5662
> erl_docgen: Fix codeinclude

- erts/emulator/beam/beam_file.c
- erts/emulator/beam/beam_types.c
- erts/emulator/beam/beam_types.h
- erts/emulator/beam/emu/emu_load.c
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_arith.cpp
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/instr_float.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_arith.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_float.cpp
- erts/emulator/beam/jit/x86/ops.tab
- erts/emulator/test/small_SUITE.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_disasm.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/src/beam_types.hrl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_type_SUITE.erl
This pull requests strengthens the type-based optimizations in the JIT that were introduced in #5316.
The compiler has been enhanced to infer ranges for more operations. The ranges are now included in the type information stored in BEAM files.
With the enhanced type information, the JIT can now omit type checks and overflow checks for some arithmetic instructions, and can also omit some redundant tests when constructing binaries using the binary syntax.
> JIT: Strengthen type-based optimizations

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
foo(X) ->
try
{ok, bar(1, [X])}
catch
_:_:_ -> error
end.
Compiled with OTP 24, the first part of the function looks like this:
{allocate,1,1}.
{'try',{y,0},{f,3}}.
{test_heap,2,1}.
{put_list,{x,0},nil,{x,1}}.
{move,{integer,1},{x,0}}.
{line,[{location,"t.erl",6}]}.
{call,2,{f,5}}.
Here there is an `allocate` instruction, and after the `try` a
`test_heap` instruction. d5fb2115710fb7 (in #5652) hoists the
building of the list and combines the `allocate` and `test_heap`
instructions:
{allocate_heap,1,2,1}.
{put_list,{x,0},nil,{x,0}}.
{'try',{y,0},{f,3}}.
{move,{x,0},{x,1}}.           %Extra move instruction.
{move,{integer,1},{x,0}}.
{line,[{location,"t.erl",6}]}.
{call,2,{f,5}}. % bar/2
Unfortunately, an extra `move` instruction is introduced because
the `put_list` …
> Eliminate moves in catches

- erts/emulator/beam/beam_transform_engine.c
- erts/emulator/beam/emu/ops.tab
- erts/emulator/beam/jit/arm/generators.tab
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/x86/generators.tab
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/ops.tab
- erts/emulator/beam/predicates.tab
- erts/emulator/internal_doc/beam_makeops.md
- erts/emulator/utils/beam_makeops
This pull request updates the syntax of `*..tab` files to make it nicer and more explicit.
Repeating variables in patterns is no longer allowed. For example:
```
move R R =>
```
This must now be written:
```
move R1 R2 | equal(R1, R2) => _
```
This examples also illustrates another change. When instructions are to be removed (rather than replaced), the substitution on the right-hand side must now be written as '_'. That makes it clearer, and also enabling automatic continuation of lines that end in `|` or `=>`. For example, a complex transformation such as:
```
is_tuple NotTupleFail Src | \
is_tagged_tuple WrongRecordFail Tuple Arity Atom | \
equal(Src, Tuple) => \
i_is_tagged_tuple_ff NotTupleFail WrongRecordFail Src Arity Atom | \
current_tuple Src
```
can now be written simply as:
``` …
```
> beam_makeops: Make syntax nicer

- erts/etc/win32/wsl_tools/SetupWSLcross.bat
Visual Studio default path has changes in 2022, it is no
longer a 32-bit application.
> [erts] enable Visual Studio 2022 for Windows

- lib/compiler/src/beam_ssa.erl
For the example in #5686, the time for running the `place_frames`
sub pass of `beam_ssa_pre_codegen` is reduced from about 30 seconds
to less than 20 seconds on my computer, and the time for each of
the `beam_ssa_bool` and `ssa_opt_sink` passes is almost halved.
> beam_ssa: Optimize dominator calculation (again)

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
- erts/emulator/test/small_SUITE.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/compile.erl
- lib/compiler/test/test_lib.erl
Building on #5316 and #5664, this pull request annotates more arithmetic instructions with type information to allow the JIT to generate better code.
With this PR, the compiler and the JIT can now optimize a tuple used as a lookup table such as in the following example (similar to real code in the `base64` module):
```
foo(N0) ->
N1 = N0 band 3,
N = N1 + 1,
element(N, {zero,one,two,three}).
```
Because `N` is known to be an integer in the range 1 through 4, the JIT will omit all type and range checks and generate inlined code to fetch the `N`th element of the tuple.
> Further strengthen the type-based optimizations

- erts/preloaded/src/init.erl
When a nifs `on_load` function returns a non-ok value loading fails today silently without showing the returned error reason. 
This is especially sad when the `on_load` callback is calling `erlang:load_nif/2` as it lasts statement which many nif `on_load` callbacks do. `erlang:load_nif/2` typically returns quite helpful error tuples that help to identify the reasons for why the nif failed loading. This change makes the error message appear in the output and in debug messages when debugging is enabled. 
```erlang
-on_load(init/0).
init() ->
SoName = filename:join(code:priv_dir(?APPNAME), ?LIBNAME),
erlang:load_nif(SoName, 0).
```
> Include the error reason when loading a nif fails

- erts/emulator/beam/erl_process.c
If a process is being tracing using 'running' trace and
at the same time polled using erlang:process_info, then
the memory allocated for the tracing will never trigger
a GC as there are no GC tests for when only signals/sys
tasks are run.
This commit moves the GC check so that it is done earlier
in order to catch any memory allocated when executing
signals/sys tasks.
The bug is triggered by running etop towards an idle node.
> erts: Fix trace running memory leak

- erts/emulator/beam/erl_bits.c
- erts/etc/unix/etp-commands.in
When creating a new proc bin because tracing has removed the
writable flag from the proc bin, we must make sure to also
create a new sub binary if the sub binary is on the mature
or old heap. When this is not done, the subbinary can be
promoted to the old heap without the proc bin also being there.
Bug was introduced in #5195, aka e16e545
> erts: Fix proc bin writable trace fixup 

- erts/test/erlc_SUITE.erl
- lib/common_test/src/test_server.erl
- lib/inets/test/httpc_SUITE.erl
- lib/inets/test/httpd_1_1.erl
- lib/inets/test/httpd_SUITE.erl
- lib/inets/test/httpd_all.erl
- lib/inets/test/httpd_basic_SUITE.erl
- lib/inets/test/httpd_mod.erl
- lib/kernel/test/global_SUITE.erl
- lib/kernel/test/heart_SUITE.erl
- lib/kernel/test/ignore_cores.erl
- lib/odbc/test/mysql.erl
- lib/odbc/test/postgres.erl
- lib/os_mon/test/cpu_sup_SUITE.erl
- lib/os_mon/test/disksup_SUITE.erl
- lib/os_mon/test/memsup_SUITE.erl
- lib/os_mon/test/os_mon_SUITE.erl
- lib/os_mon/test/os_sup_SUITE.erl
- lib/snmp/test/snmp_test_lib.erl
Codemod, drops undocumented function in favour of a
documented one.
> [cleanup] Replace test_server:os_type() with os:type()

- lib/eldap/asn1/ELDAPv3.asn1
- lib/eldap/doc/src/eldap.xml
- lib/eldap/include/eldap.hrl
- lib/eldap/src/eldap.erl
- lib/eldap/test/README
- lib/eldap/test/eldap_basic_SUITE.erl
- lib/eldap/test/make_certs.erl
- lib/eldap/test/run_server.sh
Returns the controls from an LDAP search and includes the
PagedResultsControl ASN so that user code can perform paged searches
according to https://www.rfc-editor.org/rfc/rfc2696.txt
> Add support for paged search results to LDAP

- lib/debugger/src/dbg_ieval.erl
- lib/dialyzer/test/opaque_SUITE_data/src/big_external_type.erl
- lib/dialyzer/test/opaque_SUITE_data/src/big_local_type.erl
- lib/dialyzer/test/small_SUITE_data/src/big_external_type.erl
- lib/dialyzer/test/small_SUITE_data/src/big_local_type.erl
- lib/stdlib/doc/src/erl_eval.xml
- lib/stdlib/doc/src/shell.xml
- lib/stdlib/src/erl_eval.erl
- lib/stdlib/src/erl_parse.yrl
- lib/stdlib/src/eval_bits.erl
- lib/stdlib/src/ms_transform.erl
- lib/stdlib/test/erl_eval_SUITE.erl
- lib/stdlib/test/shell_SUITE.erl
- lib/syntax_tools/src/erl_syntax.erl
This allows code using `erl_eval` to provide better
stacktraces if desired. For this purpose, we also
make sure all errors raised from `erl_eval` pass
through the ExternalFunctionHandler.
This PR is broken in two commits to facilitate review.
The first focuses on `erl_eval` and the second also
modifies `eval_bits`. I can squash if desired.
Closes #5526.
> Pass Anno to ExternalFunctionHandler in erl_eval

- lib/diameter/src/info/diameter_dbg.erl
- lib/diameter/src/info/diameter_info.erl
- lib/inets/src/inets_app/inets.erl
- lib/megaco/src/app/megaco.erl
- lib/snmp/src/app/snmp.erl
- lib/stdlib/src/c.erl
Here is a PR inspired by https://github.com/erlang/otp/commit/b58478b9d3e2433ebb20d9af362f174333631bec which removed an occurence of the old `compile time` info.
While preparing #5589 I detected a few more similar leftover cases so I'm proposing to remove those as well to complete the clean-up. I'm not sure if this is a good candidate for `maint` or for `master` though.
> Compile time no longer available

- erts/etc/win32/erlsrv/erlsrv_service.c
Sometimes we want to break out, for example to start programs in another windows session.
https://docs.microsoft.com/en-us/windows/win32/api/jobapi2/nf-jobapi2-createjobobjectw
All processes associated with a job must run in the same session. 
A job is associated with the session of the first process to be assigned to the job.
> JOB_OBJECT_LIMIT_BREAKAWAY_OK

- lib/ssh/src/ssh_message.erl
[Documentation states that the tag is `ed_pri` not `ed_priv` for legacy ED private keys][1].
[1]: https://erlang.org/doc/man/public_key.html#type-ed_private_key
> Improper tag for private ED keys when encoding

- lib/inets/doc/src/inets.xml
Documentation fix for inets:services_info/0, which now describes that Info might
be a Reason term() in case when {error, Reason} is returned as service info.
> inets: services_info doc update

- lib/mnesia/src/mnesia_controller.erl
- lib/mnesia/src/mnesia_loader.erl
- lib/mnesia/src/mnesia_monitor.erl
- lib/mnesia/src/mnesia_tm.erl
- lib/mnesia/test/mnesia_dirty_access_test.erl
- lib/mnesia/test/mnesia_isolation_test.erl
- lib/mnesia/test/mt
Avoid table and schema lock during copying of tables reduces the locks conflicts on large systems
and thus should decrease the startup time.
> Mnesia decrease locks during startup

- erts/emulator/beam/beam_file.c
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/test/small_SUITE.erl
Fixes https://erlangforums.com/t/strange-issue-with-otp-25-rc1-on-osx-with-jit-enabled/1094/5
> jit: Fix integer ranges

- lib/stdlib/src/lists.erl
Only test that `Index` is an integer once, and not once for each
list element.
> Slightly optimize lists:enumerate/1,2

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/guard_SUITE.erl
Fixes https://github.com/erlang/otp/issues/5731
> compiler: Fix type inference for variable is_function/2

- lib/stdlib/doc/src/peer.xml
- lib/stdlib/src/peer.erl
- lib/stdlib/test/peer_SUITE.erl
* `peer:stop()` currently by default stop a peer node, which is supervised over an erlang distribution connection, by closing the connection. This can cause other code on the peer node to react in undesirable ways to broken links, `'DOWN'` messages, and `nodedown` messages before the `peer` code on the peer node is able to take down the node. This PR makes `peer:stop()` first try to stop the node properly before, as a last resort, disconnecting from it.
* `peer:stop()` could return before a potential connection to the peer node had been closed which could cause issues for some test cases. This PR ensures that `peer:stop()` doesn't return until the connection has been closed.
* Added missing license/copyright header in `peer.erl` (reused the same as used on `pg`).
> Peer fixes

- .gitignore
- lib/common_test/src/test_server.erl
- lib/tools/test/cover_SUITE.erl
- lib/tools/test/instrument_SUITE.erl
Make tests more robust - node names can never clash now.
> [tools] replace test_server:start_node with ?CT_PEER()

- lib/stdlib/src/queue.erl
The queue module consists of lists of Rear and Front.
```console
1> queue:new().
{[],[]} % = {Rear, Front}
```
In the queue module, move half is performed when the list of Rear and Front is empty. This is a good way to reduce the complexity when elements are continuously removed from one side.
```console
1> {{value, V}, Q} = queue:out({[4,3,2], [1]}).
{{value,1},{[4,3],[2]}}
2> Q.
{[4,3],[2]}
```
However, when I tried locally, I noticed that the number of elements in Rear and Front after the move half is not equal (of course, this is unavoidable when the total number of elements is odd).
```console
1> {{value, V}, Q} = queue:out({[6,5,4,3,2,1], [0]}).
{{value,0},{[6,5,4,3],[1,2]}}
2> Q.
{[6,5,4,3],[1,2]} % <- I expect {[6,5,4], [1,2,3]}.
```
I fixed the behavior of the queue module to …
> queue: Remove unnecessary '+ 1' for pretty move half

- erts/preloaded/src/erlang.erl
Define list() + list(ContentType) using built-ins
Change the implementation of the `list/0` and `list/1` types exposed in the `erlang`
module to be as documented in https://www.erlang.org/doc/reference_manual/typespec.html
- My motivation for this change is to make it easier
to implement a type checker for Erlang specs,
since then we can remove some hard-coding for
the meaning of `list()` and rely on `erlang.erl`
as the source of truth.
> Define list() + list(ContentType) using built-ins

- erts/.gitignore
- erts/emulator/beam/big.c
- erts/emulator/beam/big.h
- erts/emulator/beam/erl_db.c
When creating a crash dump there is no process available to
allocate terms to the heap. The new write_concurrency option
needs a heap to allocate a tuple on, so it would segfault
in the old code.
So the table_info function now takes a factory that we can use
to allocate all needed term in.
> erts: Fix table info segfault during crash dump

- lib/stdlib/src/lists.erl
Make it easer to get an overview over the function of the `lists`
module by grouping them into (I hope) logical groups.
> Reorganize the exports of the lists module

- erts/emulator/test/bs_construct_SUITE.erl
- lib/kernel/src/erl_erts_errors.erl
- lib/stdlib/src/eval_bits.erl
- lib/stdlib/test/erl_eval_SUITE.erl
- lib/stdlib/test/shell_SUITE.erl
The new options are:
* `override_segment_position` is used by erl_eval/eval_bits
to override the actual binary segment
* `pretty_printer` can be used by other BEAM languages to
customize how values in error messages are printed
Prior to this commit, binary construction errors in the
shell reported the following:
1> A = "foo".
"foo"
2> <<A/integer>>.
in function  eval_bits:eval_exp_field1/6 (eval_bits.erl, line 123)
With this commit:
1> A = "foo".
"foo"
2> <<A/integer>>.
** exception error: construction of binary failed
in function  eval_bits:eval_exp_field/6 (src/eval_bits.erl, line 143)
*** segment 1 of type 'integer': expected an integer but got: "foo"
3> <<0, A/integer>>.
** exception error: construction of binary failed
in function …
> Add options to binary construction error_info formatting

- lib/asn1/src/asn1ct_gen_jer.erl
- lib/asn1/src/asn1rtt_jer.erl
- lib/asn1/test/asn1_SUITE.erl
This solves GH-5129
Added support for the `maps`option in combination with the `jer` backend.
> Add support for option 'maps' in the JER backend

- lib/jinterface/doc/src/jinterface_users_guide.xml
- lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
- lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractNode.java
- lib/jinterface/java_src/com/ericsson/otp/erlang/Makefile
- lib/jinterface/java_src/com/ericsson/otp/erlang/OtpGenericTransportFactory.java
- lib/jinterface/java_src/com/ericsson/otp/erlang/OtpNode.java
- lib/jinterface/java_src/com/ericsson/otp/erlang/OtpSelf.java
- lib/jinterface/java_src/com/ericsson/otp/erlang/java_files
- lib/jinterface/test/jinterface_SUITE.erl
- lib/jinterface/test/jinterface_SUITE_data/GenericTransportFactoryTest.java
- lib/jinterface/test/jinterface_SUITE_data/Makefile.src
- lib/jinterface/test/nc_SUITE_data/Makefile.src
Here is a change I've been working on for quite some time, to expand the Jinterface compatibility to a wider set of  distribution protocols (for instance based on Unix Domain Sockets) and to remove the mandatory dependency on epmd when using a custom transport factory.
The existing Jinterface classes and interfaces have been designed originally for transport protocols using a socket port number and didn't support other protocols working without epmd. I've tried a few approaches, some of them requiring quite a lot of code duplication so I've dropped those. The trickiest part has been to keep a full backwards compatibility with existing custom factories so it was not possible to extend existing interfaces with new abstract methods.
I've settled with the following approach, by creating a new …
> jinterface: Support custom distribution protocols without epmd

- erts/emulator/test/time_SUITE.erl
These tests always fail when running in any timezone other
than Stockholm.
> time_SUITE: skip tz-specific tests when running out of Stockholm

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
This makes Erlang surface syntax more friendly to tooling
like formatters, linters, analyzers.
Currently, the `-dialyzer(...)` attribute is the only annotating
(that is, not affecting semantics) attribute that can be placed
everywhere.
There is no reason to ban other custom attributes
from being placed between functions.
The logic that certain `erlc` attributes cannot be placed
after functions is preserved
This also closes #5689.
> make Erlang more tooling-friendly: allow custom attributes everywhere

- lib/stdlib/src/ms_transform.erl
- lib/stdlib/test/ms_transform_SUITE.erl
- lib/stdlib/test/qlc_SUITE.erl
Before this change only map patterns worked and only in the shell via a
hack in `normalise/1` (It converted a map pattern AST to map, but it did
not convert a map expressions AST).
Now the transformation takes care of map patterns in MS head and map
expressions in MS guards/body and `normalise/1` only does what
`erl_parse:normalise/1`. Checking restrictions on map keys and values is
left to the PAM machine.
> Fully support maps in ms_transform

- lib/kernel/src/group_history.erl
This fixes an infinite loop with group:up_stack/1 that could be
triggered when commandline history is enabled, but it wasn't possible to
create the log file. In this case, an `ok` atom was being stored as the
history which would confuse the history search.
If you pressed CTRL-R and started typing, an infinite loop would be
started that would eventually terminate when out of memory.
To reproduce:
```sh
$ export ERL_AFLAGS="-kernel shell_history enabled -kernel shell_history_path '\"/proc\"'"
$ erl
Type CTRL-R and then press any key
```
> Fix infinite loop triggered using CTRL-R when history file fails to open

- erts/etc/unix/erl.src.src
Quote everything in the `erl` script so that it will be possible to
start Erlang if the installation has been moved to a path with
spaces in its name.
> erl script: Support installation paths with spaces

- lib/stdlib/doc/src/gen_server.xml
- lib/stdlib/src/gen_server.erl
`gen_server` module currently does not check returned timeout from `init` and all other `handle_*` callback functions. IMO in this case it should terminate with a `{bad_return_value, _}` too.  
```erlang
-module(m).
-compile(export_all).
-compile(nowarn_export_all).
start_link(Timeout) ->
gen_server:start_link({local, ?MODULE}, ?MODULE, Timeout, []).
init(Timeout) ->
{ok, undefined, Timeout}.
handle_info(_, S) ->
% Max 'receive' timeout value + 1
{noreply, S, 16#FFFFFFFF+1}.
terminate(_, _) ->
ok.
```
```erlang
1> erlang:process_flag(trap_exit, true).
false
2> m:start_link(-1).
{ok,<0.80.0>} % Dies right after entering the gen_server loop
=CRASH REPORT==== 5-Feb-2022::03:18:40.013997 ===
crasher:
initial call: m:init/1
pid: <0.80.0>
registered_name: m
exception error: bad receive timeout …
```
> fix: handle invalid timeout values returned from gen_server callback functions

- erts/configure.ac
Hello,
This PR fixes an `unsafe for cross-compilation` detected by autoconf when I was trying to cross-compile Erlang/OTP. It seems the erts/configure.ac is trying to find libdlpi in places not used for cross-compilation. However libdlpi is only provided by Solaris (I guess, not 100% sure). So this PR tries to test the host OS before trying to check the libdlpi.
```
builder@8f0f4d978071:/build/tmp/work/arm1176jzfshf-vfp-poky-linux-gnueabi/erlang/25.0-rc1-r0/git$ find -name config.log                                                                                                                                                                                           
./erts/config.log …
```
> erts: Detect libdlpi for cross compilation

- lib/wx/c_src/wxe_impl.cpp
- lib/wx/test/wx_class_SUITE.erl
The idle_processed test was in the wrong place which could cause the
callback handling loop to hang forever.
Also re-write the testcase to hang without this commit, for some reason
it worked previously and the testcode was hard to understand.
Fixes: #5758
> wx: Fix recursing callback calls

- lib/erl_interface/src/Makefile.in
Fix #5781 
Only build dynamic libs if `--enable-ei-dynamic-lib` is given.
Commit 96e8bea9c7f4e6071ae16588a6b2d3bbebff67f8 introduced `--enable-ei-dynamic-lib`, but always built dynamic libs
and only suppressed _installation_ of the libs if not enabled.
> erl_interface: Avoid building dynamic libs by default

- lib/kernel/doc/src/erpc.xml
- lib/kernel/src/erpc.erl
- lib/kernel/test/erpc_SUITE.erl
- lib/stdlib/doc/src/gen_event.xml
- lib/stdlib/doc/src/gen_server.xml
- lib/stdlib/doc/src/gen_statem.xml
- lib/stdlib/src/gen.erl
- lib/stdlib/src/gen_event.erl
- lib/stdlib/src/gen_server.erl
- lib/stdlib/src/gen_statem.erl
- lib/stdlib/test/dummy_h.erl
- lib/stdlib/test/gen_event_SUITE.erl
- lib/stdlib/test/gen_server_SUITE.erl
- lib/stdlib/test/gen_statem_SUITE.erl
`receive_response()`, `wait_response()`, and `check_response()` in `gen_server`, `gen_statem`, `gen_event`, and `erpc` can now take a collection of request identifiers as argument and handle any responses corresponding to a request identifier in the collection.
* `gen_server` - [`send_request/4`](https://erlang.github.io/prs/5792/lib/stdlib-3.17.1/doc/html/gen_server.html#send_request-4), [`receive_response/3`](https://erlang.github.io/prs/5792/lib/stdlib-3.17.1/doc/html/gen_server.html#receive_response-3), [`wait_response/3`](https://erlang.github.io/prs/5792/lib/stdlib-3.17.1/doc/html/gen_server.html#wait_response-3), [`check_response/3`](https://erlang.github.io/prs/5792/lib/stdlib-3.17.1/doc/html/gen_server.html#check_response-3)
* `gen_statem` - …
> Improve response handling for asynchronous gen and erpc requests

- lib/observer/src/cdv_proc_cb.erl
Don't look up port information when we want node information
> crashdump_viewer: Fix remote process info

- lib/kernel/src/code.erl
`code:module_status/1` would always return `modified` for BEAM
file loaded from an archive file.
Closes #5801
> Correct `code:module_status/1` for BEAM files in archives

- erts/preloaded/src/prim_zip.erl
- lib/stdlib/src/zip.erl
Hiding a keyword behind a macro messes up syntax highlighting and
some tools that rely on analysing code without expanding macros.
Additionally the `catch` keyword has a fairly surprising precedence,
wrapping it in a macro with a proper argument makes it less error prone.
Debugging is still possible by changing the macro to just
-define(CATCH(Expr), Expr).
> Make ?CATCH macro "syntactical"

- lib/compiler/src/beam_ssa_share.erl
- lib/compiler/test/beam_ssa_SUITE.erl
72878b61e41e7a introduced `{succeeded,body}` instructions after tail calls. With that change, the `beam_ssa_share` pass would never share blocks ending with tail calls. This pull request mends the optimization.
> beam_ssa_share: Mend sharing optimization for tail calls

- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_type_SUITE.erl
2ea04617d18bc3 introduced a bug in the handling of calls to
`setelement/3`. Consider this module:
-module(bug).
-export([bug/0]).
bug() ->
set(2, {a,b}),
set(3, {a,b}).
set(Pos, Tuple) ->
setelement(Pos, Tuple, something).
The second call to `set/2` will fail because the position is `3` is
beyond the end of the tuple. Because of that failed call, the compiler
would incorrectly assume that the call to `setelement/3` in `set/2`
would always fail, and there would be a very confusing exception:
1> bug:bug().
** exception error: no true branch found when evaluating an if expression
in function  bug:set/2 (bug.erl, line 8)
This pull request fixes the bug. With this bug fix, the exception will look
like:
4> bug:bug().
in function  setelement/3
called as …
> beam_call_types: Correct optimization of setelement/3

- erts/emulator/beam/break.c
- erts/emulator/beam/erl_thr_progress.c
- erts/emulator/test/dump_SUITE.erl
If a crash dump was generated while the VM was supervised
with heart, the debug build would assert because the heart
port was flushed.
This commit moves where erts_is_crash_dumping is set so that
the heart flush works as it should.
More importantly the commit also moves the
erts_thr_progress_fatal_error_block to be earlier so
that multiple threads do not race to create the crash dump.
The thr progress block was incorrectly moved by [#5315](https://github.com/erlang/otp/pull/5315) when
fixing a problem with the suspension of schedulers.
> erts: Fix crash dump assert when heart is set

- erts/doc/src/erlang.xml
- erts/emulator/beam/atom.names
- erts/emulator/beam/break.c
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/erl_process.c
- erts/emulator/test/process_SUITE.erl
- erts/preloaded/src/erlang.erl
Parent process information is available in the VM process structure,
but is not exposed via process_info. Sometimes it is very convenient
to know who spawned processes that are not supporting any OTP
behaviours (where this information is stored in a process dictionary).
In addition to counting reductions, it may also be important to keep
track of total number sent to a process. This allows various monitoring
scenarios. For example, when message_queue_len is draining slowly, is
it because it the process being slow, or is it because it gets more
messages enqueued. Having both message_queue_len and messages_enqueued
provides a way to calculate queue fill rate (or drain rate) over time.
> [erts] Expose parent process via process_info(_, parent) 

- lib/ssl/src/ssl.erl
This includes a small change to fill in the location for all ssl_logger users.
`maybe_client_warn_no_verify` was the only caller that was missing location metadata.
> ssl_logger improvements

- lib/kernel/src/logger_server.erl
- lib/kernel/test/logger_SUITE.erl
logger_backend emits internal debug logs if a handler or a filter
fails. This is done using the ?LOG_INTERNAL macro. Prior to this
commit, these logs would get the meta data from the original failing
log event. This commit instead uses the actual location of the
internal debug log.
The original meta data is still included as a part of the log report,
so no data is lost.
> logger: Don't use original meta data in internal log

- lib/kernel/src/logger_h_common.erl
- lib/kernel/test/logger_disk_log_h_SUITE.erl
- lib/kernel/test/logger_std_h_SUITE.erl
The commit 06cacbc (aka PR #4811) changed where the timer_server
is located in the supervisor tree of Kernel. This change caused
the timer_server to be terminated before logger, which meant that
the calls to timer:cancel from any logger backend would timeout.
We solve this by instead using erlang:start_timer for the repeated
filesync timer.
Closes #5780
> logger: Fix repeated filesync shutdown timeout

- lib/kernel/doc/src/inet_res.xml
- lib/kernel/include/inet.hrl
- lib/kernel/src/inet_res.erl
Closes PR #5412.
Instead of changing the `#hostent{}` record type; correct the return type for `inet_res:getbyname/2,3` by creating a parallel tuple type that defines the peculiar use of the `#hostent{}` record.
> Correct typespec for inet_res:getbyname/2,3 (PR #5412, OTP-17986)

- lib/inets/src/http_client/httpc_handler.erl
- lib/inets/test/httpc_proxy_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
- lib/ssl/test/tls_api_SUITE.erl
- re-use connect_timeout during TLS upgrade of connection over proxy
- connect_timeout test in inets
- TLS upgrade client timeout test in ssl
> inets: re-use connect_timeout option in TLS upgrade

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_arith.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_arith.cpp
- erts/emulator/test/small_SUITE.erl
This pull request optimizes the `bsl` and `bxor` instructions when they have known small operands, and also fix a bug where unsafe code could would be generated for `band`, `bor`, and `bxor` in the x86 JIT.
> JIT: Optimize `bsl` and `bxor` with known small operands

- erts/emulator/beam/copy.c
- erts/emulator/beam/erl_bif_atomics.c
- erts/emulator/beam/erl_term.h
- erts/emulator/beam/utils.c
In the debug emulator hashmaps start being used at maps size 4, so we need to make sure that any maps created in erts are hashmaps when they should be. This PR adds asserts and fixes a couple of places where flatmaps were created when they should not be.
> Fix creation of small hashmaps in debug emulator

- scripts/diffable
When `diffable` is used to evaluate the impact of a compiler
optimization or checking that a compiler refactoring doesn't change
the result in any significant way, the changes to the compiler source
code produce many differences in the output from `diffable`. The sheer
number of changes in line number directives in the output from, for
example, a reformatting which inserts a line early in a module makes
it hard to notice significant changes in the output.
Prior to this patch `diffable` finds the source code to the
applications it compiles by using `code:root_dir/0` and
`code:lib_dir/1`, that is, it assumes that the source code to compile
is the source for the running system. This patch adds a new command
line flag to `diffable`. The flag, `--erltop <path>`, makes diffable
look for the …
> diffable: Allow input from external runtime

- lib/stdlib/doc/src/beam_lib.xml
- lib/stdlib/src/beam_lib.erl
- lib/stdlib/test/beam_lib_SUITE.erl
When stripping BEAM files, be sure to retain the "Type" and "Meta"
chunk types introduced in OTP 25.
Also update the documention to make it clearer what the `strip` functions
do.
> Teach beam_lib:strip/* to retain new chunk types introduced in OTP 25

- lib/compiler/src/Makefile
- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/compiler.app.src
- lib/compiler/test/Makefile
- lib/compiler/test/beam_bounds_SUITE.erl
Refactor and improve bounds calculations for the `band`, `bor`,
and `bxor` operators. That will result in smaller (and possibly
faster) code for `rand`, `base64`, and parts of the `asn1`
application.
> Compiler: Improve bounds calculation for bitwise operators

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_validator_SUITE.erl
Compiling the following code:
foo() ->
try
receive
_ ->
42
end:name()
catch
_:_ ->
error
end.
would cause a validation error because `beam_validator` would not
recognize that `42:name()` would always fail:
t:1: function foo/0+14:
Instruction: {jump,{f,4}}
Error:       {illegal_branch,try_handler,4}:
> beam_validator: Fix validation failure for failing apply

- lib/stdlib/src/supervisor.erl
Because in `gen_server`, line 277 we can find:
```
%%%    Name ::= {local, atom()} | {global, term()} | {via, atom(), term()}
```
The global parameter for `gen_server` is a term and indeed, global is accepting more than only atoms:
```
-spec register_name(Name, Pid) -> 'yes' | 'no' when
Name :: term(),
Pid :: pid().
```
I think it's good to let us use terms when we are registering names for supervisors. And avoid Dialyzer complains about it.
> consistent sup_name() type

- erts/emulator/Makefile.in
- erts/etc/win32/wsl_tools/vc/cc.sh
Change the different depend targets to be dependencies which allow
them to be run in parallel. Also redo cc.sh -MM to use /showIncludes
to list all includes instead of searching through the pre processed
files.
> erts: Optimize make depend, especially on windows

- erts/emulator/nifs/unix/unix_prim_file.c
macOS doesn't really flush buffers to disk during `fsync()` and therefore currently an additional `fcntl()` call is performed to force macOS to do so. Unfortunately that call, known as F_FULLFSYNC, performs more work than an `fsync()` would. This leads to poor I/O performance on macOS (and still doesn't really guarantee data safety according to Apple).
There is another call however, `F_BARRIERFSYNC`, which has more relaxed guarantees than `F_FULLFSYNC` but offers better performance. This PR defaults to `F_BARRIERFSYNC` and still uses `F_FULLFSYNC` if `F_BARRIERFSYNC` is not unavailable for some reason. This is just one way to do it - it could be a compile-time or runtime decision to optimize for data safety or performance. I'm definitely open to suggestions, but I wanted to get feedback …
> erts: on macOS, prefer F_BARRIERFSYNC over of F_FULLFSYNC

- erts/emulator/beam/bif.c
- erts/emulator/beam/erl_fun.h
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/instr_fun.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_fun.cpp
- erts/emulator/test/erts_debug_SUITE.erl
The sum of `arity` and `num_free` cannot exceed 255, so there's no point using a whole word for each.
Note that we will now badarg when passing an arity above 255 to `erlang:make_fun/3`, instead of creating a fun that can never be called and had iffy behavior when sent over the distribution (the arity got truncated down to 8 bits), but it ought to be okay as its spec has always said the valid range is 0..255.
> erts: Shrink ErlFunThing structure

- erts/etc/common/erlexec.c
- lib/runtime_tools/src/system_information.erl
- lib/runtime_tools/test/system_information_SUITE_data/information_test_report.dat
The CERL_DETACHED_PROG code seems to be a relic that is no
longer used. So we delete it doesn't work anyway.
Closes #4323
> erts: Remove unused CERL_DETACHED_PROG code

- erts/emulator/sys/unix/erl_child_setup.c
When calling read it may return a partial result. So we make
sure that all the data is read before returning.
The problem has been observed when reading the ACK message,
but we use the new routine for all reads in the child so that
we know that it will work everywhere.
> erts: Fix child_setup partial read

- lib/stdlib/doc/src/rand.xml
- lib/stdlib/src/rand.erl
- lib/stdlib/test/rand_SUITE.erl
This PR adds two very fast but low quality niche algorithms to the `rand` module, not as part of the plug-in framework, to avoid the overhead.
The algorithms are two Linear Congruential Generators, one purely multiplicative - **`mcg35`**, with a prime modulus and one power of two based - **`lcg35`**.  Both have 35 bits, the multiplicative just short of.  According to state of the art today these are historical toy generators with plenty of statistical shortcomings, but an impressive speed, which is what still might make them relevant for niche applications such as "random" load balancing, routing, etc.
The reason for adding them to the `rand` module is so that users will not need to roll their own and accidentally do some unfortunate mistake that makes their implementation even worse. …
> Implement fast niche PRNGs

- erts/doc/src/erl_cmd.xml
- erts/emulator/beam/erl_bif_trace.c
- erts/emulator/beam/erl_bits.c
- erts/emulator/beam/erl_port_task.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/sys.h
- erts/emulator/sys/common/erl_check_io.c
- erts/emulator/sys/common/erl_check_io.h
- erts/emulator/test/scheduler_SUITE.erl
- erts/etc/common/erlexec.c
Default is true, scheduler thread polling enabled as before.
Scheduler polling has in some cases seen to cause longer read event latency, and can now be disabled at the expense of some increased cpu load.
> Add option +IOs to disable scheduler thread polling

- lib/kernel/doc/src/net_kernel.xml
- lib/kernel/src/net_kernel.erl
- lib/kernel/test/erl_distribution_SUITE.erl
The implementation #5623 was already merged to master for OTP-25.0-rc1.
[`net_kernel:get_state/0`](https://erlang.github.io/prs/5735/lib/kernel-8.2/doc/html/net_kernel.html#get_state-0)
> Document new net_kernel:get_state

- lib/wx/c_src/wxe_gl.cpp
- lib/wx/configure
- lib/wx/configure.in
On win32 "windows.h" can not be included before wxWidgets headers with
wxWidgets-3.1.6.
Remove them they doesn't seem to be needed anymore.
Fixes #5883
> wx: Fix configure on win32 with newer wxWidgets

- erts/etc/unix/etp-commands.in
Example:
```
(gdb) etp-dist
--- visible
Name: b@sovrum.
State: CONNECTED
Creation: 1648029258
Queue Flags: BUSY PORT_CTRL 
Queue Size: 29666139
Suspended: <0.85.0> 
Flags: PUBLISHED EXTENDED_REFERENCES DIST_MONITOR FUN_TAGS DIST_MONITOR_NAME NEW_FUN_TAGS EXTENDED_PIDS_PORTS EXPORT_PTR_TAG BIT_BINARIES NEW_FLOATS UNICODE_IO DIST_HDR_ATOM_CACHE SMALL_ATOM_TAGS UTF8_ATOMS MAP_TAG BIG_CREATION SEND_SENDER BIG_SEQTRACE_LABELS EXIT_PAYLOAD FRAGMENTS HANDSHAKE_23 UNLINK_ID MANDATORY_25_DIGEST SPAWN V4_NC ALIAS 
Pointer: (DistEntry*)0x555555c90558
--- not connected
Name: a@sovrum.
State: IDLE
Creation: 1648042989
Queue Flags: 
Queue Size: 0
Suspended: 
Flags: 
Pointer: (DistEntry*)0x7fffb1d55e10
```
> erts: Add etp-dist for listing all dist entries

- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/test/ssl_packet_SUITE.erl
packet_size is an emulated option and would work if set as an initial
socket option in connect or listen, but was missing from
setops and getopts
> ssl: packet_size was not handled by ssl:setopts and ssl:getopts

- lib/crypto/c_src/cipher.c
- lib/crypto/doc/src/algorithm_details.xml
- lib/crypto/src/crypto.erl
- lib/crypto/test/crypto_SUITE.erl
Add Output Feedback mode support for AES encryption / decryption for key
sizes of 128, 192 and 256 bits.
> Add OFB mode support for AES

- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_bounds_SUITE.erl
The main purpose of this pull request is to improve the test of the value type analysis for integer arithmetic operations. To achieve that, all bounds checking for arithmetic instructions have been moved from `beam_call_types` to `beam_bounds`. Along the way, a bug for the bounds of `bsr` has been fixed. I have also moved the handling of guard BIFs from `beam_ssa_type` to the more appropriate `beam_call_types` module (because it handles all other BIFs).
> compiler: Refactor type analysis and improve tests

- erts/emulator/beam/atom.c
> Eliminate crash when creating more than 33554431 atoms

- lib/stdlib/src/erl_parse.yrl
This syntax is later rejected by `erl_lint` in:
* https://github.com/erlang/otp/blob/738b597ff5a9489981a71102ae90d05276e1333f/lib/stdlib/src/erl_lint.erl#L1694-L1752
* https://github.com/erlang/otp/blob/738b597ff5a9489981a71102ae90d05276e1333f/lib/stdlib/src/erl_lint.erl#L1886-L1899
This commit short-circuits the case where such syntax is encountered to reject it in `erl_parse` early. This simplifies `erl_parse` slightly and generates less code for it.
It's also consistent with types in `erl_parse` that don't allow the 4-element `map` tuple in patterns:
https://github.com/erlang/otp/blob/738b597ff5a9489981a71102ae90d05276e1333f/lib/stdlib/src/erl_parse.yrl#L834-L835
> Don't parse map update syntax in patterns

- lib/kernel/src/file_io_server.erl
- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/test/io_SUITE.erl
Makes sure that io:puts_char/2 emits a no_translation error
when called with an incomplete binary and adds detail to the
resulting error message.
Follow up of https://groups.google.com/g/elixir-lang-core/c/RR7nbeHsluQ  
Related to https://github.com/elixir-lang/elixir/pull/11756
Since this slightly changes the behavior of the function (although in a way that I think is intended), I opened the PR for the `master` branch and not for `maint`. If that is a miscalculation, I'll rebase this onto `maint`.
This is my first PR to OTP and I tried to follow all guidelines. If something is not up to the usual standards, please let me know :)
> kernel|stdlib: Fix io:puts_char error with invalid binary

- lib/dialyzer/src/typer_core.erl
This is (I think?) the last of the refactoring work we (@elbrujohalcon and @pablocostass) did on typer core in the course of making
the rebar3_typer plugin.
> Change from using dicts in typer_core to using maps

- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_gen_connection.erl
The special case handled by the tls_gen_connection:effective_version
function is only valid in the hello and wait_sh state.
Closes #5835
> ssl: Fix version mismatch

- lib/wx/c_src/wxe_impl.cpp
- lib/wx/c_src/wxe_impl.h
- lib/wx/c_src/wxe_nif.h
Some macOS apps only run in the background and thus have no GUI. Some apps only live in the "menu bar" (top-right corner) and thus don't have the traditional GUI either. In both cases, we don't want the application to show up in the Dock (and thus show up when switching apps with cmd+tab, etc)
A standard way to do this to set `LSUIElement` to `true`. See:
https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement
Here's an example script that builds such app:
#!/bin/sh
set -eo pipefail
cat <<EOF > app1.swift
import Cocoa
_ = NSApplication.shared
let window = NSWindow(
contentRect: NSMakeRect(800, 600, 320, 200),
styleMask: [.titled, .closable],
backing: .buffered,
defer: true
)
window.orderFrontRegardless()
window.title = "Example"
let menuItemOne = …
> wx: Overload `OSXIsGUIApplication` with our own check

- lib/compiler/test/record_SUITE.erl
- lib/stdlib/src/erl_expand_records.erl
- lib/stdlib/test/erl_expand_records_SUITE.erl
The compiler would crash when attempting to compile the
following code:
-record(r, {a}).
foo() ->
R = #r{a = [], _ = V = 42},
{R,V}.
The reason is that when all fields in the record had been explicitly
initialized, the `erl_expands_records` pass would rewrite the code
to:
foo() ->
R = {[]},
{R,V}.
This pull request eliminates that bug by updating `erl_expand_records`
to ensure that the initializing expression is still executed even
when all records fields are explicitly initialized:
foo() ->
begin
V = 42,
R = {[]}
end,
{R,V}.
> Fix multi-init record initialization edge case

- erts/emulator/beam/erl_time_sup.c
- erts/emulator/sys/unix/erl_unix_sys.h
- erts/emulator/sys/unix/sys.c
- erts/emulator/sys/win32/erl_win_sys.h
According to POSIX, localtime_r does not have to update the process
internal tz data when called. So if time went from winter to
summertime erts is running localtime_r may return an incorrect time.
So we need to make sure to call tzset before each call to localtime_r.
localtime is guaranteed to update the tz information, so no need to
call it when using localtime.
> erts: Fix localtime_r summer/winter-time change bug

- erts/emulator/beam/erl_gc.c
- erts/emulator/test/message_queue_data_SUITE.erl
When a process is changing from on heap to off heap
message queue data, there may still be messages in the
external queue with data on the heap. So we need to move
all signals in the external queue to the internal queue
before doing the GC.
Closes #5933
> erts: Fix gc to fetch sig queue at mqd change

- lib/public_key/Makefile
- lib/public_key/c_src/Makefile
- lib/public_key/c_src/public_key.c
- lib/public_key/doc/src/public_key.xml
- lib/public_key/src/Makefile
- lib/public_key/src/pubkey_os_cacerts.erl
- lib/public_key/src/public_key.app.src
- lib/public_key/src/public_key.erl
- lib/public_key/test/public_key_SUITE.erl
- lib/ssl/src/ssl.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
API: load/0 load/1 and get/0
Writes to persistent_term to cache the results,
user can re-load cache with load/0 and load/1 functions.
load/1 is made for users with an unsupported OS, or if they
want to load the cache with data from another file.
Currently works on linux (ubuntu) and win32
> Prototype API for fetching os cacerts

- erts/epmd/src/epmd_srv.c
Backporting e8c9e12 (#5762) to v23.
When specifying bind address(es) via ERL_EPMD_ADDRESS or the -address
option, epmd will bind to the IPv4/IPv6 loopback intefaces in addition
to the user-supplied address(es).
However, it is possible that one of the loopback interfaces does not
exist.  For example, if the host system has ipv6 disabled via the
disable_ipv6 sysctl, there will be no loopback interface "::1", and
attmepting to bind to "::1" will fail.
Under these circumstances, log the failure but do not consider the
failure to bind to the loopback interface as fatal.
If any of the user-supplied addresses fail to bind, however, that is
still considered fatal and epmd will terminate.
> Backport: epmd: don't fail if non-critical interfaces fail to bind

- lib/erl_docgen/src/docgen_xml_to_chunk.erl
If a type does not use the typespec notation in docs
we should not include the AST signature in the chunks,
otherwise the incorrect docs will be printed by shell_docs.
> docgen: Fix signature for types

- lib/stdlib/src/peer.erl
- lib/stdlib/test/peer_SUITE.erl
When calling `peer:start_link` with option `peer_down=>crash`, the controlling process should exit abnormally if peer node disconnects. This did not work with alternative `connection=>0` option.
> Fix peer options peer_down=>crash with connection=>0

- lib/stdlib/doc/src/gen_server.xml
The late reply issue should not exist anymore because gen:call uses process aliases for reply routing.
I also fix one trivial typo elsewhere in the file.
> Revise note on late replies from gen_server.xml

- system/doc/efficiency_guide/functions.xml
Followup to https://github.com/erlang/otp/pull/5831#issuecomment-1118371747
Make it more explicit that caching would be benefitial for callback modules.
Also fixes a small error at the same time (Module:function is changed into apply, not apply into Module:function, I believe).
> Efficiency caching callbacks

- lib/stdlib/src/peer.erl
`peer:start_link/0` returns 3-tuple `{ok,Pid,Node}`.
Other peer issues:
- A lot of functions accept type `Dest :: gen_statem:server_ref()` as identifier of the peer node to communicate with. But nowhere is a  `gen_statem:server_ref()` returned. Why? Whether the controlling process is a gen_statem server or not, seems to me as an implementation issue. 
- I carelessly wrote `peer:start().` in the shell and got strange ERROR REPORT followed by a _frozen shell prompt_. It turns out that `start/0` is not part of the API but must be exported to satisfy the user.erl I/O interface. This is unfortunate, as it's an easy lets-try-this mistake to do.
> Fix spec for peer:start_link/0

- lib/inets/doc/src/httpd.xml
- lib/inets/src/http_server/httpd_sup.erl
- remove reference to Apache-like config file which is not supported anymore
- fixes #5276 (doc update only)
> inets: remove apache config ref from manual

- lib/ssl/src/tls_gen_connection.erl
- lib/ssl/src/tls_handshake.erl
- lib/ssl/test/ssl_handshake_SUITE.erl
- lib/ssl/test/ssl_npn_hello_SUITE.erl
I think this should solve #5961  The problem seems to be that an optimization bug happened to not show itself until some other unrelated things happened to expose it. This has to do with how handshake messages are packed into TLS records. I will try to write a withe-box test to test it. I would also appreciate @michaelklishin, and @lukebakken  if you could also try it out.
> Ingela/ssl/tls record handling/gh 5961/otp 18087

- lib/stdlib/doc/src/peer.xml
- lib/stdlib/src/peer.erl
To replace gen_statem:server_ref().
I gave peer its own `server_ref()` type, currently only specified as `pid()` to
- not expose current gen_server implementation unnecessarily.
- make it expandable in future independent of used implementation.
@max-au Thoughts?
> Add type peer:server_ref()

- erts/preloaded/src/erlang.erl
Per documentation (and implementation): it returns a **list** of tuples `{Node, ControllingEntity}`
> erlang:system_info(dist_ctrl) - fix spec

- lib/kernel/doc/src/gen_sctp.xml
- lib/kernel/doc/src/inet.xml
- lib/kernel/src/gen_sctp.erl
- lib/kernel/src/inet.erl
SCTP Socket options have some weird[^1] semantics that this PR fixes.
Specifically:
- two options are read-only (see `prim_inet:type_opt/2`)
- many options for getopts require a  `#sctp_...` record to specify the association
Previously, the same type specification was used for both getopts and setopts which caused dialyzer to barf on perfectly valid code like this:
```erlang
inet:getopts(Sock, [{sctp_status, #sctp_status{assoc_id = AssocId}}])
```
[^1]: Weird, as in not like TCP or UDP but perfectly fine for SCTP!
> SCTP: Fix type specs for inet:getopts/2 and inet:setopts/2

- lib/stdlib/test/Makefile
- lib/stdlib/test/base64_property_test_SUITE.erl
- lib/stdlib/test/property_test/base64_prop.erl
As the title says, this PR introduces property-based tests for the `base64` module.
Test coverage is around ~95%, looks like some obscure edge cases that may occur in relation to `mime_decode` are rarely created by the generators. However, those are covered by the normal CT suite.
<hr />
Some things I noticed while working on this:
* The decoding functions may fail in a variety of ways on malformed input. There is `badarg` which is fine and expected, but there is also `badarith`, `function_clause`, `case_clause` etc bubbling up from internal functions. This multitude of error reasons makes handling them tedious (and so, lazy as I am, I settled on catching `error:_` after hitting three different error reasons). What (I guess) I'm trying to say is, they essentially all boil down to the …
> Property-based tests for the base64 module

- lib/compiler/test/property_test/compile_prop.erl
- lib/compiler/test/record_SUITE.erl
- lib/stdlib/src/erl_expand_records.erl
- lib/stdlib/test/erl_expand_records_SUITE.erl
Revert to the pre-OTP-25 behaviour when binding to `_` when all other fields had already been initialised.
> Revert bug fix that caused much more problems than it solved

- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_dtls_connection.erl
- lib/ssl/src/tls_handshake.erl
- lib/ssl/test/tls_api_SUITE.erl
If upgrading a TCP socket to a TLS socket and in the same
time changing the supported protocol version in the
sni_fun callback, so that it does not match the default, care must
be applied to make sure correct decoding of hello information is used.
Closes #5985
> ssl: Handle protocol version change in sni_fun

- bootstrap/lib/stdlib/ebin/stdlib.appup
- erts/emulator/test/tuple_SUITE_data/get_two_tuple_elements.S
- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_ssa_pp.erl
- lib/compiler/src/beam_ssa_throw.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/src/beam_types.hrl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_bounds_SUITE.erl
- lib/compiler/test/beam_type_SUITE.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/property_test/beam_types_prop.erl
Refactor the type analysis modules in the Erlang compiler to
be able to derive type information from relational operators
in guards.
f(A) when is_integer(A), 0 =< A, A =< 1000 ->
A + 1.
From the guard, a human can easily figure out that `A` must be
an integer in the range 0 through 1000. The compiler in OTP 25
cannot:
{test,is_integer,{f,1},[{x,0}]}.
{test,is_ge,{f,1},[{tr,{x,0},{t_integer,any}},{integer,0}]}.
{test,is_ge,{f,1},[{integer,1000},{tr,{x,0},{t_integer,any}}]}.
{gc_bif,'+',{f,0},1,[{tr,{x,0},{t_integer,any}},{integer,1}],{x,0}}.
With this pull request, the compiler generates the following code:
{test,is_integer,{f,1},[{x,0}]}.
{test,is_ge,{f,1},[{tr,{x,0},{t_integer,any}},{integer,0}]}.
{test,is_ge,{f,1},[{integer,1000},{tr,{x,0},{t_integer,{0,'+inf'}}}] …
> Improve the type analysis

- lib/stdlib/doc/src/ets.xml
This sentence needs singular "specification" not plural.
> ets.xml: fix grammar in is_compiled_ms/1 doc

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/ops.tab
- erts/emulator/test/op_SUITE.erl
- lib/compiler/src/beam_jump.erl
Optimise the generated code for common combinations of relational operators such as in the following examples:
```
f(A) when is_integer(A), 0 =< A, A =< 1000 ->
A + 1.
g(A) when 0 =< A, A =< 1000 ->
A + 1.
```
> JIT: Optimise common combinations of relational operators

- lib/kernel/src/erl_erts_errors.erl
`Cause` defaults to `none`, not `true`.
A catch-all was used for consistency with
the remaining of the file.
> Fix case clause errors in erl_erts_errors

- lib/mnesia/src/mnesia_loader.erl
- lib/mnesia/test/mnesia_evil_coverage_test.erl
Hi, 
I found a rare mnesia bug that could occure when a node ("A") executes `mnesia:add_table_copy/3` to send a table data to another node ("B").
If node B terminated during the sending process, node A could hold a read lock forever because that waits for an already received message `{copier_done, node()}` again in a transaction after acquiring a read lock.
This PR fixes the redundant `receive`s to prevent the problem.
Because this problem is inherently timing dependent, it's difficult to write a deterministic reproducing code. However, the following example code can reproduce the issue with almost 100% probability on my laptop.
```erlang
-module(mnesia_debug).
-export([run/0]).
%% For RPC.
-export([init_node0/0, init_node1/0, add_table_copy/2]).
-record(table, {foo, bar, baz}).
run() -> …
```
> Fix a bug that `mnesia:add_table_copy/3` could hold a read lock forever

- erts/emulator/beam/emu/bs_instrs.tab
- erts/emulator/beam/erl_bits.c
- erts/emulator/beam/erl_bits.h
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/arm/generators.tab
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/beam_jit_args.hpp
- erts/emulator/beam/jit/beam_jit_common.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/x86/generators.tab
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_construct_SUITE.erl
In the JIT, improve the code generation for binary construction for segments of fixed widths of no more than 64 bits and for variable width segments that are a set to 0.
I have run the benchmark linked to from https://github.com/erlang/otp/issues/5639.
On my Intel iMac from 2017, the result without this pull request was:
== Testing with 1 MB ==
fun base64:encode/1: 1000 iterations in 16264 ms: 61 it/sec
fun base64:decode/1: 1000 iterations in 18597 ms: 53 it/sec
With this pull request:
== Testing with 1 MB ==
fun base64:encode/1: 1000 iterations in 10955 ms: 91 it/sec
fun base64:decode/1: 1000 iterations in 10629 ms: 94 it/sec
On my M1 MacBook Pro from 2020 the result before was:
== Testing with 1 MB ==
fun base64:encode/1: 1000 iterations in 12299 ms: 81 it/sec
fun base64:decode/1: 1000 …
> JIT: Optimize creation of binaries

- lib/mnesia/doc/src/mnesia.xml
From what I understand, the default value is 1000, not 100: https://github.com/erlang/otp/blob/master/lib/mnesia/src/mnesia_monitor.erl#L719.
This is in line with what's written in the Mnesia User's Guide: https://github.com/erlang/otp/blob/maint/lib/mnesia/doc/src/Mnesia_chap7.xmlsrc#L298.
> Correct default for dump_log_write_threshold in Mnesia docs

- erts/doc/src/time_correction.xml
- erts/emulator/beam/erl_init.c
- system/doc/general_info/upcoming_incompatibilities.xml
As announced when OTP 25 was released, multi time warp mode is now enabled by default. This assumes that all code executing on the system is time warp safe.
If you have old code in the system that is not time warp safe, you now explicitly need to start the system in no time warp mode (or singe time warp mode if it is partially time warp safe) in order to avoid problems. When starting the system in no time warp mode, the system behaves as it did prior to the introduction of the extended time functionality introduced in OTP 18.
If you have code that is not time warp safe, you are strongly encouraged to change this so that you can use multi time warp mode. Compared to no time warp mode, multi time warp mode improves scalability and performance as well as accuracy and precision of time …
> Use multi time warp mode by default

- erts/doc/src/erlang.xml
- erts/emulator/beam/erl_proc_sig_queue.c
A `spawn_reply` signal from a remote node could be delayed and delivered after other signals from the newly spawned process.
When this bug trigger the connection to the node where the process was spawned might be taken down and the following error message might be logged:
```
Missing 'spawn_reply' signal from the node <RemoteNode> detected by <Pid>
on the node <LocalNode>. The node <RemoteNode>; probably suffers from the
bug with ticket id OTP-17737.
```
This bug only affects processes which has enabled [`off_heap` `message_queue_data`](https://www.erlang.org/doc/man/erlang.html#process_flag_message_queue_data) when also parallel reception of signals has been automatically enabled.
This bug was introduced in OTP 25.0, ERTS version 13.0.
> Fix spawn_reply signal order

- lib/common_test/src/test_server.erl
- lib/common_test/test/ct_error_SUITE.erl
- lib/common_test/test/ct_test_support.erl
this commit fixes #5719 
New Stacktrace with thrown is:
```
===> Running Common Test suites...
%%% db_data_type_SUITE: 
%%% db_data_type_SUITE ==> init_per_suite: FAILED
%%% db_data_type_SUITE ==> {thrown,
{foo,
[{db_data_type_SUITE,init_per_suite,1,
[{file,
"/home/adamsbd/src/infratracks/common_tests/db_data_type_SUITE.erl"},
{line,44}]},
{test_server,ts_tc,3,[{file,"test_server.erl"},{line,1782}]},
{test_server,run_test_case_eval1,6,
[{file,"test_server.erl"},{line,1379}]},
{test_server,run_test_case_eval,9,
[{file,"test_server.erl"},{line,1223}]}]}}
```
no change to without Thrown and Normal Error:
```
===> Running Common Test suites...                                                                                                          
%%% db_data_type_SUITE: …
```
> 5719 - Adding Stacktrace to thrown

- lib/stdlib/scripts/update_deprecations
- system/doc/general_info/DEPRECATIONS
The `public_key:ssh_*` functions were removed in Erlang/OTP 25, but were not labeled with the correct version in the DEPRECATIONS file.
> Fix public_key removed version

- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_type_SUITE.erl
> beam_call_types: Fix type inference for erlang:min/2,max/2

- lib/stdlib/src/timer.erl
- lib/stdlib/test/timer_simple_SUITE.erl
This PR introduces some new tests to cover more of the `timer` module. Test coverage has risen from 84 to 93%. The remaining 7% are IMO not coverable.
A side issue that I found with the new tests is related to starting the timer server. If the child spec is present in `kernel_sup` but not started, the current implementation fails with `{error, already_present}`. This was fixed so it would restart the child.
A more general change contained in this PR is turning messages to be sent around by the test cases from enumerated atoms into references, which makes them automatically unique. The same approach is used when registering a process (mostly, the test process itself), which was previously done by turning the pid into an atom.
Finally, I took the opportunity to change all tabs to spaces in …
> Extend timer tests

- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_cl_parse.erl
- lib/dialyzer/test/extra_return_SUITE_data/dialyzer_options
- lib/dialyzer/test/extra_return_SUITE_data/results/extra_return
- lib/dialyzer/test/extra_return_SUITE_data/src/extra_return.erl
- lib/dialyzer/test/missing_return_SUITE_data/dialyzer_options
- lib/dialyzer/test/missing_return_SUITE_data/results/missing_return
- lib/dialyzer/test/missing_return_SUITE_data/src/missing_return.erl
- lib/stdlib/src/erl_lint.erl
When `extra_return` and `missing_return` were added in https://github.com/erlang/otp/pull/5214, the values weren't added to warn_options. This caused the following error when I try to skip any of the errors with `-dialyzer()`.
I used the same code as https://github.com/erlang/otp/pull/5214.
```erlang
-module(t).
-export([t/1, q/1]).
-dialyzer({no_missing_return, t/1}).
-spec t(integer()) -> odd.
t(N) when N rem 2 =/= 0 ->
odd;
t(_) ->
even.
-dialyzer({no_extra_return, q/1}).
-spec q(integer()) -> positive | negative | zero.
q(N) when N > 0 ->
positive;
q(N) when N < 0 ->
negative.
```
```
$ dialyzer t.erl -Wextra_return -Wmissing_return                                                                                                
Checking whether the PLT …
```
> dialyzer: Add no_extra_return and no_missing_return to warn_options type

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/beam_ssa_SUITE.erl
When compiling the following code with optimization passes disabled:
foo() ->
([<<bad/utf8>>] =
try
[whatever]
catch
_:_ when false ->
ok
end) ! (some_atom ++ <<>>).
`beam_validator` rejects the code with the following message:
some_module:1: function foo/0+11:
Instruction: {get_hd,{literal,[whatever]},{x,0}}
Error:       {literal_not_allowed,{literal,[whatever]}}:
All optimization passes are supposed to be optional, so this crash is
not acceptable even though the code is nonsensical. Eliminate the
crash by having `beam_ssa_pre_codegen` re-run its code cleaning
pass until there are no more unreachable blocks.
> Eliminate crash when optimization passes are disabled

- erts/emulator/beam/beam_file.c
- erts/emulator/beam/beam_types.c
- erts/emulator/beam/beam_types.h
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_arith.cpp
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_arith.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
- erts/emulator/test/small_SUITE.erl
- lib/compiler/src/Makefile
- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_disasm.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/src/beam_types.hrl
- lib/compiler/test/beam_bounds_SUITE.erl
- lib/compiler/test/compile_SUITE.erl
Introduce a new version of the type information store in BEAM files. (The loader can still load and take advantage of type information in BEAM files produced by the compiler in OTP 25.) The new format differs from the previous format in the following ways:
* Ranges are included for numbers as well as for integers.
* Ranges can go from minus infinity to an integer value that fits in a small, or from a small value to positive infinity.
* The size unit are included for bitstrings.
* The size of the type information as stored in BEAM files varies from 2 to 19 bytes depending on the types (instead of having a fixed size of 18 bytes).
Using the new type information, do the following new optimizations in the JIT:
* Eliminate redundant tests when appending to binaries by using the new information …
> Improve the type-based optimizations

- lib/compiler/src/beam_block.erl
- lib/compiler/test/map_SUITE.erl
When compiling the following code with the SSA-based optimization
passes disabled:
foo(#{{tag,whatever} := true,
#{} := <<bad_integer,0:(is_integer(a))>>} =
#{[something] := 42}) ->
ok.
The `beam_validator` pass rejects the code with the following message:
t:1: function foo/1+6:
Instruction: {get_map_elements,
{f,1},
{x,0},
{list,
[{literal,[something]},
{x,2},
{literal,#{}},
{x,2},
{literal,{tag,whatever}},
{x,1}]}}
Error:       conflicting_destinations:
All optimization passes are supposed to be optional, so this crash is
not acceptable even though the code is nonsensical.
> Eliminate another crash when optimization passes are disabled

- lib/observer/src/observer_lib.erl
The current code does the conversion from bytes to kibibyte (KiB), mebibyte(MiB) and gibibyte(GiB), that is dividing by 1024.
However, when the units are printed, the units are in kilobytes (KB), megabytes (MB) and gigabytes (GB), so the bytes should be divided by 1000 instead of 1024.
We realised about the error when we were discussing in [erlang forum](https://erlangforums.com/t/ets-memory-occupy-the-erl-shell-query-occupies-more-than-2m-memory-but-the-observer-query-occupies-more-than-18m-memory/1525/5), and I couldn't explain why it was a difference between calculating the ets memory footprint in the shell and looking in `observer` (I must say that I wasn't very awake so I didn't think it could be in KiB).
The change is not a big deal but I think it will show more precise values.
> observer: correct the units shown for memory data

- .github/workflows/main.yaml
This fixes issue with
The process 'C:\hostedtoolcache\windows\Ubuntu\18.4.0\x64\ubuntu1804.exe' failed with exit code 1
> gh: Bump Vampire/setup-wsl version

- erts/emulator/beam/erl_db_catree.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process.h
Fixes #5981.
Crash dump of ETS table with options `ordered_set` and `{write_concurrency,true}` could lead the segmentation violation crash if the crash dumping happens to not be done on behalf of an Erlang process running thread (current_process==NULL).
> Fix SEGV while crash dumping ETS ordered_set

- erts/emulator/sys/unix/sys_time.c
Mac OS X 10.6 and earlier produce a segmentation fault due to a condition mismatch between calls to `host_get_clock_service` and `mach_clock_getres`. This change brings consistency to the conditionals and fixes the segfault.
> Call `mach_clock_getres` only on initialized clocks

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/bs_init_writable.erl
The SSA instruction bs_init_writable is not known to the SSA type
analysis pass, nor is its result type known to the BEAM
validator. This patch adds type information for bs_init_writable and
as it allows the SSA type pass to elide is_bitstring tests, it also
extends the BEAM validator to consider the result of bs_init_writable
to be a bitstring.
> compiler: Add type info for bs_init_writable

- lib/kernel/doc/src/pg.xml
- lib/kernel/src/pg.erl
- lib/kernel/test/pg_SUITE.erl
This PR consists of multiple commits for review convenience:
- internal refactoring (does not change logic) to bring consistency for record and function naming
- scope-level monitor implementation
- group-level monitor implementation
I believe that first two commits are self-explanatory, with the only question I can think about is naming. I named the function to monitor the entire scope as `monitor_scope/0,1` to avoid clashes with the `monitor` function implemented in the third commit. If we end up scratching the third commit, the name can be changed to just `monitor/0,1`.
As for the third commit, it is debatable whether a new API `monitor/1,2` (starts monitoring for a specific group membership updates) belongs to `pg` or not. It is possible to implement per-group monitoring using a …
> [pg] Implement group membership monitoring

- lib/stdlib/src/array.erl
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/src/erl_scan.erl
- lib/stdlib/src/filename.erl
- lib/stdlib/src/gb_sets.erl
- lib/stdlib/src/gb_trees.erl
- lib/stdlib/src/io_lib.erl
- lib/stdlib/src/string.erl
- lib/stdlib/test/erl_scan_SUITE.erl
- lib/stdlib/uc_spec/gen_unicode_mod.escript
Add `is_integer/1` guard tests (and some range tests) to a few of the important modules in STDLIB.
This change will make sure that floats are rejected for functions that should only accept integers. It will also enable the JIT to generate more compact code.
> Add integer guard tests to some modules in STDLIB

- lib/stdlib/doc/src/calendar.xml
- lib/stdlib/src/calendar.erl
- lib/stdlib/test/calendar_SUITE.erl
RFC3339 declares the minutes part of the timezone diff as optional,
which is now enabled with this commit.
E.g.: 2022-06-25 11:04:00+02 is now possible.
> Allow the timezone part of the string to contain only an hour

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/ops.tab
- erts/emulator/test/op_SUITE.erl
The recent pull request #6090 (f44ea5cf1e902c) made the following type
of instruction sequence much more common (about 1000 occurrences in
unicode_util alone):
is_ge Fail1 Src IntegerLiteral1
is_ge Fail2 Src IntegerLiteral2
which now makes it worth combining and optimizing such sequences.
While at it, also optimize the `is_ge` instruction when one operand
is a small integer literal.
> JIT: Improve code generation for the is_ge instruction

- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_bounds_SUITE.erl
- lib/compiler/test/beam_type_SUITE.erl
* Do range analysis for the unary `-` operator and the `bnot` operator
* Improve range analysis for `min/2`, `max/2`, `+/2`, and `-/2`
* Derive types from a few more BIFs
* Improve combination of literals in integer expressions such as `H - $A + $a`
* Eliminate `band` operations without effect
> Slightly improve the compiler's type analysis and optimisations

- lib/inets/doc/src/http_client.xml
- lib/inets/doc/src/httpc.xml
- lib/inets/src/http_client/httpc.erl
- lib/inets/src/inets_app/inets.app.src
- lib/inets/test/httpc_SUITE.erl
httpc:ssl_verify_host_options/1 returns ssl client options
to verify the host.
Added as a helper function to 25.1 to be added as the default option
in 26.
> inets: Add a helper function for client ssl connections

- lib/compiler/src/beam_ssa.erl
The missing bs_create_bin operation has probably remained undiscovered
as the Dialyzer limit mentioned in the comment preceding the prim_op()
type definition collapses the effective type to atom().
> compiler: Add missing bs_create_bin prim_op() to type definition

- erts/etc/common/erlexec.c
- lib/common_test/src/test_server.erl
- lib/kernel/src/user_sup.erl
- lib/stdlib/doc/src/peer.xml
- lib/stdlib/src/peer.erl
- lib/stdlib/test/peer_SUITE.erl
In order to test interactive shells, peer nodes sometimes need to be started without detaching the shell. This PR adds two mechanism that help when testing such systems:
1. The `detached` option can be set to false which causes the peer when running using distributed or tcp connection to not close its terminal.
2. The `post_process_args` option can be set to a fun which allows the peer to process all arguments before the peer node is started, this notably includes any arguments that `peer` itself has added.
These two changes in combination allows a peer node to be started in a screen/tmux session, or using run_erl/to_erl.
This PR also contains some changes to how cover is started when peer is running in CT so that cover is started earlier in the boot sequence allowing for better code …
> peer: Add detached and post_process_args

- erts/emulator/beam/dist.c
- erts/emulator/beam/erl_node_tables.c
- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/erl_proc_sig_queue.h
- erts/emulator/beam/erl_process.c
- erts/emulator/test/process_SUITE.erl
Distributed exit signals could be lost under the following conditions:
*   An exit signal from a parent process to a child process was lost if:
* the parent process terminated before the spawn request that created the child had completed,
* the spawn request set up a link between parent and child
* the spawn request was distributed, and
* the exit reason was larger than one machine word.
* Loss of a connection over which a not yet completed spawn request was ongoing could cause loss of exit signals. Such loss of exit signals was very rare. Besides the above described connection loss also the following
conditions had to be satisfied:
* The spawn request that was interrupted by the connection loss also had to set up a link between the parent process and the child process.
* The parent …
> Fix distributed spawn_request() bug

- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/io.c
- erts/emulator/test/process_SUITE.erl
- erts/emulator/test/signal_SUITE.erl
An unlink operation made by a process that terminated before the unlink operation completed, i.e., before it had received an unlink-ack signal from the linked process, caused an exit signal to erroneously be sent from the terminating process to the process being unlinked. This exit signal would most often be ignored by the receiver, but if the receiver of the exit signal concurrently set up a new link, it could receive the exit signal with the actual exit reason of the terminating process instead of a noproc exit reason. It is however very hard to detect that this has happened and has no obvious negative consequences, so it should be considered harmless.
A distributed unlink-ack signal received by a terminating process was also not properly removed which could cause a minor memory leak.
> Unlink issues

- erts/emulator/beam/erl_process.c
Fixed reduction counting for handling process system tasks.
> Fix reds counting in execute_sys_tasks()/cleanup_sys_tasks()

- erts/emulator/beam/erl_bif_info.c
- erts/emulator/test/process_SUITE.erl
A race could cause `process_info(Pid, message_queue_len)` on other processes to return invalid results.
> Fix process_info(Pid, message_queue_len) on other process

- erts/emulator/beam/erl_process.c
Priority elevation of terminating processes did not work which could cause execution of such processes to be delayed.
> Fix permanent prio elevation at process termination

- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/using_ssl.xml
- lib/ssl/src/tls_server_session_ticket.erl
- lib/ssl/test/ssl_session_ticket_SUITE.erl
- lib/ssl/test/tls_server_session_ticket_SUITE.erl
If a stateless ticket is older than the WindowSize of the bloom filter
then it will be rejected. By subtracting the ReportedAge from the
RealAge we have the drift time, which should become too large during
a replay. Previously the absolute age of the ticket was being used.
Fixes #6014
> ssl: Fix stateless ticket in_window comparison

- lib/compiler/src/beam_ssa.erl
This patch adds BEAM SSA operations that are produced by the compiler,
but are not in the beam_ssa:prim_op() type.
> compiler: Add missing operations to beam_ssa:prim_op() type

- lib/inets/examples/httpd_load_test/hdlt_ctrl.erl
- lib/inets/examples/httpd_load_test/hdlt_slave.erl
- lib/ssh/src/ssh_sftp.erl
- fix dialyzer warnings in inets/httpd examples folder
- fix related spec in ssh_sftp module
> inets: fix dialyzer warnings for inets/httd examples

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/float_SUITE.erl
> Fix internal consistency error

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/map_SUITE.erl
The expression:
#{assoc := V} = #{key => self()}, V.
is supposed to raise a `badmatch` exception, but because of an
overeager common subexpression elimination optimization, it
returned `#{}`.
> Correct bug in CSE optimization

- lib/ssh/doc/src/ssh.xml
- lib/ssh/src/ssh.hrl
- lib/ssh/src/ssh_auth.erl
- lib/ssh/src/ssh_fsm_userauth_server.erl
- lib/ssh/src/ssh_options.erl
- lib/ssh/test/ssh_options_SUITE.erl
Proposed fix #6021 
Introduces the boolean server option `no_auth_needed` which makes the server always accept a login request.
> Option to skip SSH authentication for some niche cases

- lib/dialyzer/src/dialyzer.erl
- lib/dialyzer/src/dialyzer_behaviours.erl
- lib/dialyzer/test/behaviour_SUITE_data/results/gen_server_not_exported
- lib/dialyzer/test/behaviour_SUITE_data/src/gen_server_not_exported.erl
Fix two bugs in Dialyzer's behaviour checking:
* When a mandatory callback function is present but not exported,
Dialyzer would not complain about a missing callback. However, it
would complain if the arguments and/or return values were
incompatible.
* When an optional callback function was not exported and had
incompatible arguments and/or return values were incompatible,
Dialyzer would complain. This has been changed to suppress the
warning, because the function might not be intended to be a callback
function, for instance if a release added a new optional callback
function (such as `format_status/1` for the `gen_server` behaviour
added in OTP 25).
> Dialyzer: Fix checking of behaviours

- lib/tools/doc/src/eprof.xml
Just a small typo I noticed reading the docs.
Thanks for all the work y'all are doing!
> fix typo in :eprof docs: prifile --> profile

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
> Eliminate crash in beam_ssa_bool

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/cerl.erl
- lib/compiler/test/map_SUITE.erl
An optimization in the loader was added in: https://github.com/erlang/otp/pull/1498
When a small map is created where all keys are literals, the key tuple
is created as a literal. That means that the key tuple can be shared
for all instances of the map created by the same code.
However, that does not always work, for example for code such
as:
decimal(Int) ->
#{type => decimal, int => Int, exp => 0}.
The compiler would try to be smart and rewrite the code to:
decimal(Int) ->
(#{type => decimal, exp => 0})#{int => Int}.
Expressed in that way, the loader optimization cannot be applied and
a new key tuple will be created every time `decimal/1` is called.
This pull request removes that problematic transformation. The implementation
is based on José Valim's suggested implementation.
Fixes #6139
> Enhance creation of maps with literal keys

- erts/emulator/beam/beam_common.c
- erts/emulator/beam/erl_map.c
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
When doing comparisons, be sure to avoid calling the quite expensive
generic comparison routine for equal tagged values.  In particular,
the generic comparison function for atoms, `erts_cmp_atoms()`, will
always call `memcmp()` for equal atoms longer than 4 characters, so we
want to avoid that.
> Optimize comparison of equal terms

- lib/compiler/src/v3_core.erl
- lib/compiler/test/core_SUITE.erl
- lib/compiler/test/core_SUITE_data/nif.erl
Since OTP 25 the `nifs` attribute can be used to declare which
functions are nifs. When the `nifs` attribute is present, the runtime
system will ensure that only functions listed in the attribute are
replaced by a native implementation when `erlang:load_nif/2` is
called. Functions listed in the `nifs` attribute are flagged by
emitting a `nif_start` operation as the first instruction in the
function.
Due to backwards compatibility, the `nifs` attribute is not required,
so when a module containing a call to `erlang:load_nif/2` is
encountered, the compiler is forced to conservatively assume that in
such a module, all functions are potential nifs. Currently most of the
more powerful compiler optimizations (beam_ssa_opt.erl) are completely
disabled when a module contains a call to …
> compiler: Start all potential nif functions with a nif_start

- lib/crypto/src/crypto.erl
Since 6ca05d934 two crypto related NIFs were updated:
* ensure_engine_loaded_nif - arity was changed from 3 to 2
* ensure_engine_unloaded_nif - was removed
this commit adjusts NIFs list in crypto.erl to avoid errors:
```
crypto.erl:138:2: nif ensure_engine_loaded_nif/3 undefined
%  138| -nifs([info_nif/0, info_lib/0, info_fips/0, enable_fips_mode_nif/1,
%     |  ^
crypto.erl:138:2: nif ensure_engine_unloaded_nif/2 undefined
%  138| -nifs([info_nif/0, info_lib/0, info_fips/0, enable_fips_mode_nif/1,
%     |  ^
```
> crypto: adjust list of nifs

- lib/stdlib/src/gen_event.erl
Perform a non-selective receive with timeout, and pass the
message to factored-out decode_msg/7, similar to gen_server.
One of our more heavily used `gen_event` servers got into a state of extreme memory consumption and slow processing a couple of times this summer. When I looked into it recently I discovered that `gen_event`'s fetch-and-dispatch loop performs a _selective_ receive looking for `system` and `EXIT` messages (without using the ref trick), which could explain the issues. `gen_server` always picks the first message, and I strongly believe `gen_event` should do the same.
This bug seems to have been there "for ever" -- even R6B0 has this difference between `gen_event` and `gen_server`.
> gen_event: eliminate selective-receive in fetch_msg/6

- lib/inets/doc/src/mod_esi.xml
Was removed in OTP-23 and also in 22.3.1
Closes #6122
> inets: Remove documentation of no longer supported callback

- lib/ssh/doc/src/ssh.xml
- lib/ssh/src/ssh.erl
- lib/ssh/src/ssh_options.erl
- lib/ssh/src/ssh_system_sup.erl
- lib/ssh/test/ssh_options_SUITE.erl
This PR makes it possible to change the Options in a running SSH server.  Established connections are not affected, only those created after the call to `ssh:daemon_replace_options/2`.
Example usage:
```
{ok,Dref} = ssh:daemon(1234, [{system_dir,"..."}]).
ssh:daemon_replace_options(Dref, [{preferred_algorithms,[{kex,['diffie-hellman-group1-sha1']}]}]).
```
> Change SSH options in a running server

- lib/crypto/c_src/cipher.c
This should fix #6146. It turned out that Blowfish in CFB/OFB modes is also not detected as supported.
Tested with OpenSSL 3.0.5. Corresponding groups for AES and Blowfish in crypto_SUITE are not skipped and pass.
> crypto: Fix AES and Blowfish names for OpenSSL 3.0

- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/ssl_cert_SUITE.erl
- lib/ssl/test/ssl_cert_tests.erl
In TLS-1.3 if chain certs are missing (so server auth domain adherence
can not be determined) send peer cert and hope the server is able to
recreate a chain in its auth domain.
Closes #6105
> ssl: Enhance client certificate selection

- lib/ssl/src/ssl_crl_cache.erl
- lib/ssl/src/ssl_pkix_db.erl
- lib/ssl/test/ssl_crl_SUITE.erl
Currently, if one uses `ssl_crl_cache:insert/2` providing the URI of
the distribution point of a CRL, when a connection is attempted, it
fails with a `{unexpected_error,function_clause}`.
This traces to [`ssl_handshake:dps_and_crls/3`](https://github.com/erlang/otp/blob/8c182956e1bde761ea1541fd1d061b208356cb48/lib/ssl/src/ssl_handshake.erl#L2244), which eventually ends
up calling `public_key:der_decode/2` with a list-wrapped CRL DER
binary instead of simply the DER binary.
> fix(crl): insert the CRLs individually when an URI is provided

- lib/crypto/c_src/engine.c
- lib/crypto/c_src/info.c
- lib/crypto/c_src/otp_test_engine.c
Signed-off-by: Rosen Penev <rosenp@gmail.com>
Compile with -DOPENSSL_API_COMPAT=0x10100000L to simulate.
> otp: fix compilation - deprecated OpenSSL APIs

- lib/dialyzer/src/dialyzer_iplt.erl
- lib/dialyzer/src/dialyzer_utils.erl
- lib/dialyzer/test/Makefile
- lib/dialyzer/test/dialyzer_utils_SUITE.erl
Unlike with classic Dialyzer, incremental Dialyzer doesn't just hash a
`.beam` as a binary blob - it first filters out some non-deterministic
data, such as absolute file paths. For historical reasons, we did this
serially, but running it in parallel seems to make a fully cached
analysis about 2x faster in the cases that I have tried.
For longer analyses, the module hashing is proportionally a much smaller
amount of the elapsed time, so the saving in time spent hashing isn't
material.
> dialyzer: Parallelise hashing of source files

- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/test/opaque_SUITE_data/src/recrec/dialyzer.hrl
Adds the `incremental` analysis mode into the appropriate option types.
This was causing Dialyzer warnings for users that consumed the
incremental API to Dialyzer itself (e.g. erlang/rebar3#2736), since the `incremental`
option was available at runtime, but not declared in `dial_option()`.
> dialyzer: Fix missing incremental analysis type option

- lib/dialyzer/src/dialyzer_iplt.erl
The incremental data portion of incremental PLTs was previously
uncompressed, contributing to the considerable size of the PLT files
which can accrue for big projects. This change compresses that field
(whilst staying able to read PLTs whose file is uncompressed), which
should help us save disk space and bandwidth when reusing incremental
PLT files between users/hosts/commits.
This change also increases how hard Dialyzer "tries" to compress the
contents, trading off speed for smaller file size. In practice, time
spent doing compression/de-compression is negligable whatever the
compression level, but with this higher compression level, PLT files
work out ~5% smaller for projects I have experimented with.
> dialyzer: Use more compression in incremental PLTs

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_match_tail_SUITE.erl
On AArch64 (ARM64), the JIT would generate incorrect code for the
following binary match:
huge_tail_1(<<B:8,_:16#1001>>) -> B.
On x86_64, the JIT would generate incorrect code for the
following binary match:
huge_tail_2(<<B:8, _:16#8000_0000>>) -> B.
While at it, fix a potential problem in two helper functions
used on AArch64.
> JIT: Correct code generation for huge match in binary tail

- erts/emulator/beam/bif.c
- erts/emulator/beam/break.c
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_monitor_link.c
- erts/emulator/beam/erl_monitor_link.h
- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/global.h
- erts/emulator/test/monitor_SUITE.erl
The `monitor/3` BIF did not apply options to the created monitor if the target process or port did not exist. That is, the corresponding down message would get a `DOWN` tag even if a custom tag had been set, and the returned reference was not an alias even if the `alias` option had been passed.
Fixes #6185
> Fix monitor/3 BIF in noproc scenarios

- lib/kernel/src/net_kernel.erl
- lib/kernel/test/erl_distribution_SUITE.erl
A call to `net_kernel:setopts(new, Opts)` at the same time as a connection was being set up could cause a deadlock between the `net_kernel` process and the process setting up the connection.
Fixes #6129
> Fix deadlock caused by net_kernel:setopts(new, _)

- xcomp/erl-xcomp-arm-android.conf
- xcomp/erl-xcomp-arm64-android.conf
- xcomp/erl-xcomp-x86_64-android.conf
* Update the cross compilation for newer versions of the Android NDK
* Use the static version of libc++ on Android
Remove the runtime dependency on libc++_shared.so for the JIT flavor of beam.smp. This simplifies Erlang deployment on Android as libc++ is not provided as a system library. See https://developer.android.com/ndk/guides/cpp-support
* Switch to deterministic builds for Android
> Update Android cross compilation

- lib/stdlib/doc/src/ets.xml
Document badarg when Pos is larger than the tuple the element it to be extracted from.
This came up when testing cases in the discussion on adding support for ets:lookup_element/4
https://erlangforums.com/t/proposal-adding-ets-lookup-element-as-list-3/1743/11
> ets:lookup_element badarg for Pos

- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_construct_SUITE.erl
In the master branch, the new bs_create instruction would build
little-endian segments of a non-byte size incorrectly. This bug
is not present in Erlang/OTP 25 or earlier.
> JIT: Correct building of non-byte-sized little-endian segments

- lib/jinterface/doc/src/Makefile
This fixes the following issues during javadoc file processing stage:
```
(cd ../../java_src;javadoc -sourcepath . -d ../doc/html/java \
-windowtitle 'Java-Erlang Interface Library' com.ericsson.otp.erlang)
Loading source files for package com.ericsson.otp.erlang...
./com/ericsson/otp/erlang/OtpGenericTransportFactory.java:2: error: unmappable character (0xC3) for encoding US-ASCII
* Copyright 2022 J??r??me de Bretagne
^
./com/ericsson/otp/erlang/OtpGenericTransportFactory.java:2: error: unmappable character (0xA9) for encoding US-ASCII
* Copyright 2022 J??r??me de Bretagne
^
./com/ericsson/otp/erlang/OtpGenericTransportFactory.java:2: error: unmappable character (0xC3) for encoding US-ASCII
* Copyright 2022 J??r??me de Bretagne
^ …
```
> Specify encoding when running javadoc

- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/test/binary_SUITE.erl
An unsafe type-based optimization in the JIT could cause the
`is_binary/1` guard test to succeed when its argument was a bignum.
Closes #6239
> Ensure that is_binary(BigNum) does not return true

- lib/stdlib/doc/src/re.xml
- lib/stdlib/src/re.erl
- lib/stdlib/test/re_SUITE.erl
I rarely use regular expressions with Erlang. But when I do, I often would need a function to process matches and create replacements.
This PR extends `re:replace/3,4` to accept a 2-ary function for the replacement. This function will be called with the entire match as the first and a list of subexpression matches as second argument. The value returned from the function will be inserted into the result.
A problem exists in case of regular expressions like this:
```
".(x)?(y)?"
```
When applied to a string like `"axy"`, the function will be called with arguments `<<"axy">>` and `[<<"x">>, <<"y">>]`.
When applied to `"ax"`, the arguments will be `<<"ax">>` and `[<<"x">>]`, ie the subexpression match list _does not_ contain the optional-ish match related to `(y)`.
When applied to `"ay"`, the …
> Regular expression replacement with a function

- lib/common_test/src/cth_surefire.erl
This bug was introduced in #5581
> ct: Fix surefire without debug_info

- lib/kernel/src/logger_formatter.erl
- lib/kernel/test/logger_formatter_SUITE.erl
I have encountered a somewhat strange behavior of [`logger_formatter`](https://www.erlang.org/doc/man/logger_formatter.html) about `msg` in templates. This pull request attempts to remedy it.
The behavior is exemplified by the following application:
- https://github.com/gfngfn/a_strange_behavior_of_logger_formatter
In summary, `msg`s occurring at conditional branching `{metakey(), template(), template()}` in templates will not be formatted as intended.
Looking into the implementation of `logger_formatter:format`, I have found that the implementation presumably assumes that given templates are of the form `[Elem_1, …, Elem_{i - 1}, msg, Elem_{i + 1}, …, Elem_n]` or do not contain `msg`. According to [the definition of `logger_formatter:template()`](https://www.erlang.org/doc/man/logger_form …
> Fix `logger_formatter` about `msg` by making templates linear before split

- lib/kernel/src/logger_std_h.erl
If we cannot print to standard_io we try to instead print
to standard_error just to make sure that the error log message
is printed.
We know that group_leader will always point to the kernel application
master and thus we will be forwarded to 'user' eventutally, so we
can short circuit there. As a bonus we also now get to know if
user or user_drv has crashed and the io:put_chars call can fail.
> logger: Print to stderr if printing to stdout failed

- lib/kernel/src/logger_internal.hrl
- lib/kernel/test/logger_SUITE.erl
Log event check performed in `logger_backend:do_apply_filters/4` doesn't tolerate atoms and binaries as message format strings.  This may cause a filter to be removed
> logger:notice(<<"hello">>, []).
Logger - error: {removed_failing_filter,no_domain}
For atom format strings it was partially fixed in OTP 25 by forcing atoms to strings before filters are applied (17c8fcf).
> kernel: Fix Logger filter removal if message format is atom or binary

- lib/reltool/doc/src/reltool.xml
- lib/reltool/src/reltool.app.src
- lib/reltool/src/reltool.hrl
- lib/reltool/src/reltool_server.erl
- lib/reltool/src/reltool_target.erl
- lib/stdlib/src/beam_lib.erl
The debug_info option can now take a list of chunk ids to keep.
Chunk ids are as per beam_lib:chunkid().
For example, {debug_info, ["Attr"]} will keep only the attributes
in the beam files and strip the rest.
---
Why?
We have some code that introspects itself for some declarative use-cases (mainly "wild" attributes), and recently we started needing to be able to deliver stripped binaries.
> reltool: Add option for selective beam stripping

- erts/emulator/drivers/common/inet_drv.c
Fixing problem in inet_drv.c where code is crashing due to infinite loop while searching interfaces
Also updated code to avoid use of uninitialised pointer and updated macro to set variable to NULL after free.
For more details refer rabbitMQ thread: https://groups.google.com/g/rabbitmq-users/c/FJgf_Pp1O4c?pli=1
> changes to fix erlang hung issue on IPv6 setup

- erts/emulator/beam/erl_nif.c
- erts/emulator/nifs/unix/unix_prim_file.c
- lib/kernel/test/file_SUITE.erl
On macOS there is an (as far as I can tell) undocumented limitation
for read and write that the size is not allowed to be greater than
2GB. So if we get an EINVAL from read/write and the size is > 2GB
we try again with a smaller size.
Closes https://github.com/erlang/otp/issues/6242
> erts: Fix large read/writes on macOS 

- lib/eunit/src/eunit.erl
- lib/eunit/src/eunit_data.erl
- lib/eunit/src/eunit_internal.hrl
- lib/eunit/src/eunit_proc.erl
- lib/eunit/src/eunit_server.erl
- lib/eunit/test/Makefile
- lib/eunit/test/eunit_SUITE.erl
- lib/eunit/test/eunit_test_listener.erl
- option for avoiding automatic execution of a module with "_tests" suffix
> eunit: exact execution option

- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_handshake.hrl
- lib/ssl/src/ssl_session.erl
- lib/ssl/src/tls_connection.erl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_dtls_connection.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/tls_1_3_version_SUITE.erl
> ssl: Correct middle_box negotiation

- erts/emulator/beam/erl_init.c
(Unless I am mistaken) the `ERTS_(MIN|MAX)_` constants for `PROCESSES` and `PORTS` have the same value, so this change is purely cosmetic.
> Fix typo of min/max for +Q option

- lib/ssl/src/tls_gen_connection.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_basic_SUITE.erl
If the "User" process, the process starting the TLS connection, gets
killed in the middle of spawning the dynamic connection tree make sure
we do not leave any processes behind.
Close #6244
> ssl: Avoid partial connection trees

- lib/dialyzer/src/dialyzer.erl
- lib/dialyzer/src/dialyzer_contracts.erl
- lib/dialyzer/test/cplt_SUITE.erl
- lib/dialyzer/test/dialyzer_common.erl
- lib/dialyzer/test/incremental_SUITE.erl
- lib/dialyzer/test/indent_SUITE_data/results/contracts_with_subtypes
- lib/dialyzer/test/indent_SUITE_data/results/record_update
- lib/dialyzer/test/indent_SUITE_data/results/simple
- lib/dialyzer/test/iplt_SUITE.erl
- lib/dialyzer/test/map_SUITE_data/results/contract_violation
- lib/dialyzer/test/map_SUITE_data/results/opaque_key
- lib/dialyzer/test/opaque_SUITE_data/results/int
- lib/dialyzer/test/opaque_SUITE_data/results/multiple_wrong_opaques
- lib/dialyzer/test/opaque_SUITE_data/results/para
- lib/dialyzer/test/opaque_SUITE_data/results/simple
- lib/dialyzer/test/small_SUITE_data/results/binary_nonempty
- lib/dialyzer/test/small_SUITE_data/results/binary_redef2
- lib/dialyzer/test/small_SUITE_data/results/chars
- lib/dialyzer/test/small_SUITE_data/results/contract5
- lib/dialyzer/test/small_SUITE_data/results/contracts_with_subtypes
- lib/dialyzer/test/small_SUITE_data/results/empty_list_infimum
- lib/dialyzer/test/small_SUITE_data/results/invalid_spec_2
- lib/dialyzer/test/small_SUITE_data/results/invalid_specs
- lib/dialyzer/test/small_SUITE_data/results/maps_sum
- lib/dialyzer/test/small_SUITE_data/results/predef
- lib/dialyzer/test/small_SUITE_data/results/record_update
- lib/dialyzer/test/small_SUITE_data/results/tuple_set_crash
- lib/dialyzer/test/small_SUITE_data/results/types_arity
Invalid spec messages now include the spec side-by-side with the inferred type, and explicitly call out which parts of the types don't overlap.
`invalid_contract` tends to be one of the more common Dialyzer signals that I see in practice. For big function signatures, working out precisely why the spec and inferred types don't overlap can be awkward and error prone in itself, and often require the user to start searching through the codebase just to work out what the difference is, let alone how it arose. This change attempts to make it easier to compare the two side-by-side at the point the error is reported, making it easier for the user to locate and resolve the issue.
**Non-overlapping return types**
```
contract_violation.erl:16:2: Invalid type specification for function …
```
> dialyzer: Improve error messages for invalid specs

- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_manager.erl
- lib/ssl/src/ssl_pem_cache.erl
- lib/ssl/src/ssl_pkix_db.erl
- lib/ssl/test/ssl_pem_cache_SUITE.erl
- perform conversions before loading cert data from file
- convert relative path to absolute for avoiding collisions
- convert symlink to actual file path
> ssl: adjust cacertfile option

- erts/emulator/beam/dist.c
Proposed fix for #6247.
Two commits.
1. Assert the invariant that seems to fail. Must be CONNECTED to enter EXITING.
2. Fix. Don't hook a PENDING DistEntry into controlling port.
> Fix DistEntry corruption at node shutdown

- lib/ssl/Makefile
- lib/ssl/src/inet_tls_dist.erl
- lib/ssl/test/ssl_dist_SUITE.erl
Moving the invocation of init:on_load_handlers/0 from kernel:init(safe) to code:do_start/0.
init:on_load_handlers/0 has been added as part of https://github.com/erlang/otp/commit/7f82edd and it was implemented in such a way that it will be invoked, quoting, "after having started most servers in the kernel application", problem is that some of those servers, under specific configurations (see #6085), need the on load handlers in order for them to properly start.
As mentioned, this should fix #6085.
> kernel: invoke init:run_on_load_handlers/0 after code_server start

- lib/stdlib/doc/src/base64.xml
- lib/stdlib/src/base64.erl
- lib/stdlib/test/base64_SUITE.erl
- lib/stdlib/test/base64_property_test_SUITE.erl
- lib/stdlib/test/property_test/base64_prop.erl
In #5639 an addition to the `base64` module to support an alternative, URL-safe encoding alphabet (`base64url`) was suggested. In the alternative encoding, the characters `+` and `/` ([RFC 4648 Section 4](https://www.rfc-editor.org/rfc/rfc4648#section-4)), which may be problematic in URLs and file names, are replaced with `-` and `_` ([RFC 4648 Section 5](https://www.rfc-editor.org/rfc/rfc4648#section-5)), respectively.
This PR adds the new functions `encode/2`, `encode_to_string/2`, `decode/2`, `decode_to_string/2`, `mime_decode/2` and `mime_decode_to_string/2` as supplements of the respective existing 1-ary functions of the same names. The second parameters may be one of the atoms `standard` (meaning the section 4 alphabet; default for the 1-ary functions) and `urlsafe` (the section 5 …
> Add selectable alphabets (standard vs urlsafe) to base64

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_module.cpp
- erts/emulator/beam/jit/arm/generators.tab
- erts/emulator/beam/jit/arm/instr_bif.cpp
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_module.cpp
- erts/emulator/beam/jit/x86/generators.tab
- erts/emulator/beam/jit/x86/instr_arith.cpp
- erts/emulator/beam/jit/x86/instr_bif.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_fun.cpp
- erts/emulator/beam/jit/x86/instr_map.cpp
- erts/emulator/beam/jit/x86/ops.tab
This PR improves the code generation of the JIT in several ways.
The most important is eliminating reading from a BEAM register written by the previous BEAM instructions if the contents is already available in a CPU register.
For example, consider:
```
foo(<<X:16>>) ->
(X band 7) bor 1.
```
The BEAM code for the expression body looks like this:
```
{gc_bif,'band',
{f,0},
3,
[{tr,{x,2},{t_integer,{0,65535}}},{integer,7}],
{x,0}}.
{gc_bif,'bor',{f,0},1,[{tr,{x,0},{t_integer,{0,7}}},{integer,1}],{x,0}}.
```
The result of the `band` operand is written X-register 0 (`{x,0}`). The `bor` operation then reads X-register 0.
The JIT in Erlang/OTP 25 generates the following code:
```
mov rsi, qword ptr [rbx+16]
mov eax, 127
and rax, rsi
mov qword ptr [rbx], rax
mov rsi, qword ptr [rbx]
mov eax, 31 …
```
> JIT: Minor optimizations

- lib/common_test/src/test_server.erl
A bug when using the compile server together with a unicode path causes compilation of peer to fail for old nodes. So we don't allow the compile server for peer compilation.
> ct: Don't use compile server for peer compilation

- erts/emulator/beam/jit/beam_jit_common.cpp
The symbols for erts_beamasm did not take into consideration that there was not prologue for functions in that jit internal module. This causes perf to show `$erts_beamasm:normal_exit/0-CodeInfoPrologue` instead of `$erts_beamasm:normal_exit/0` for the top frame of all processes, which is incorrect and possibly confusing.
> jit: Fix erts_beamasm symbols

- lib/dialyzer/doc/src/dialyzer_chapter.xml
Add a section in Dialyzer's docs to expand on how specs are checked and used to refine Dialyzer's inferred types, since this is often a point of confusion.
> dialyzer: Document the meaning of specs

- lib/dialyzer/src/dialyzer_dataflow.erl
- lib/dialyzer/test/typer_SUITE.erl
A missing translation of a literal atom from a record name to the corresponding atom type meant Dialyzer/TypEr would crash due to trying to pattern match on a `c_literal` value, where a type was expected.
I suspect this hasn't been noticed yet because it requires specs to be set explicitly to be ignored (which results in the table of records being empty, activating this codepath where the first literal atom in a tuple corresponding to the record name is not converted into a type, and is instead erroneously left as a value-level literal).
> dialyzer: Fix literal value being used instead of type

- lib/stdlib/doc/src/timer.xml
- lib/stdlib/src/timer.erl
- lib/stdlib/test/timer_simple_SUITE.erl
This PR was inspired and is competing (to a degree) with #6145.
With the current (old) implementation, the apply messages resultingh from interval timers were handled by the timer server process itself, which may lead to its congestion. Specifically, it has been noticed that, with many short-interval timers running, starting as cancelling of timers takes longer and longer, stalling the calling process.
The changes in this PR run each interval timer in a separate process, so their apply messages don't compete with other (start/cancel/etc) messages. This reduces the load of the timer server, and at the same time reduces the tendency of interval timers to lag.
> Improve interval timer handling

- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/ssl_cert_SUITE.erl
Fixes #6106
/cc @IngelaAndin 
Based on the discussion from the issue (and #6204), it was decided that adding the
ability to disable the `certificate_authorities` extension on the server would be
the fitting resolution for situations where you do not want that extension forced
in TLS 1.3.
This adds that ability to specify as a server option and defaults to `true` to keep
with existing expected functionality.
> Allow disabling `certificate_authorities` extension on server with `verify_peer`

- lib/eunit/src/eunit_data.erl
- lib/eunit/test/eunit_SUITE.erl
Hi,
After updating to OTP 25.1, `$ rebar3 eunit` became failed as follows:
```console
// Erlang/OTP version
$ erl
Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Eshell V13.1  (abort with ^G)
1> q().
//  rebar3 version
$ rebar3 version
rebar 3.19.0 on Erlang/OTP 25 Erts 13.1
// Create an empty project
$ rebar3 new app foo
$ cd foo/
// Execute eunit
$ rebar3 eunit
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling foo
===> Performing EUnit tests...
=ERROR REPORT==== 22-Sep-2022::12:02:30.980278 ===
Error in process <0.182.0> with exit value:
{function_clause,[{proplists,get_bool,
[exact_execution,undefined],
[{file,"proplists.erl"},{line,307}]},
{eunit_data,extract_module_tests,3,
[{file,"eunit_data.erl"},{line,581}]}, …
```
> eunit: Fix `$ rebar3 eunit` error on OTP 25.1

- lib/observer/src/observer_wx.erl
- Also include connected, hidden nodes ([Observer User Guide](https://www.erlang.org/doc/apps/observer/observer_ug.html#getting-started) uses a hidden node as example)
- Always include current node. If dist_listen is false it won't show up
in epdm names
- If the default epmd module `erl_epmd` is used and `erl_epmd_port` is set
to `DistPort` then it is only possible to connect to the node listening
on `DistPort` (if any), so exclude other nodes registered in EPMD
The last change is controversial, maybe it should be implemented elsewhere (in net_adm or erl_epmd?) and it's not the responsibility of observer to know about this detail. Or the exclusion should not happen at all (Observer shows a nice error dialogue when connection fails and maybe that's good enough)
> Improve observer nodes list menu

- lib/wx/c_src/wxe_impl.cpp
We cannot depend on `is_packaged_app()` check because it is not a perfect way of checking if app is bundled.
It would return true when the app is bundled with a launcher like this:
```swift
import AppKit
let task = Process()
task.launchPath = "/Users/wojtek/src/otp/bin/erl"
task.arguments = ["-noshell", "-eval", "wx:new(), timer:sleep(5000), halt()"]
try task.run()
task.waitUntilExit()
```
It would return false for this launcher, however:
```swift
import AppKit
class AppDelegate: NSObject, NSApplicationDelegate {
func applicationDidFinishLaunching(_ aNotification: Notification) {
let task = Process()
task.launchPath = "/Users/wojtek/src/otp/bin/erl"
task.arguments = ["-noshell", "-eval", "wx:new(), timer:sleep(5000), halt()"]
try! task.run()
}
}
let app = NSApplication.shared
let delegate …
```
> wx: Add `WX_MACOS_NON_GUI_APP`

- system/doc/design_principles/statem.xml
- Change can not to should not and give a brief explanation of why one should not use a receive in a gen_* process.
I suspect this will go through a few revisions. We may want to provide examples or simply expand on all this in another chapter (the dos and donts of gen_*) and link to that. However, I didn't think letting perfect be the enemy of good here was ideal.
> Adjust language around the usage of receive in a gen_statem.

- lib/stdlib/src/rand.erl
Recent improvements in the compiler (92611e5d2d75) and the JIT (f8a9ccda6c4a) allows us to write more natural code using guard tests instead of `band` operations to establish ranges for integers. This also happens to be slightly faster.
> rand: Slightly optimize the mwc59 family of functions

- lib/kernel/src/kernel.app.src
- lib/kernel/src/kernel.erl
- lib/stdlib/src/peer.erl
- lib/stdlib/src/stdlib.app.src
- lib/stdlib/test/peer_SUITE.erl
`peer` nodes failed to halt when the process supervising the control connection crashed. When an alternative control connection was used, this supervision process also quite frequently crashed when the `peer` node was stopped by the node that started it which caused the `peer` node to linger without ever halting.
> [stdlib, kernel] Ensure that peer node halts

- .github/workflows/main.yaml
- erts/emulator/Makefile.in
- erts/emulator/beam/erl_lock_count.h
- erts/lib_src/Makefile.in
- lib/public_key/c_src/Makefile
Currently OMIT_OMIT_FP is set to true in erts/emulator/Makefile.in
when JIT is enabled, but not necessarily in erts/lib_src/Makefile.in.
This change factors out OMIT_OMIT_FP computation to be shared between
those two builds to apply this flag consistently to them.
Note that this bug was confirmed by @garazdawi in an Erlang forum post: https://erlangforums.com/t/unify-builds-for-otp-erts-targets/1419/3
> erts: Apply -fno-omit-frame-pointer to erts/lib_src when JIT is enabled

- erts/etc/common/erlc.c
- erts/test/erlc_SUITE.erl
- erts/test/erlc_SUITE_data/src/😀/erl_test_unicode.erl
- lib/kernel/src/erl_compile_server.erl
- lib/stdlib/test/edlin_expand_SUITE.erl
Updates compilation server so that it supports input arguments in binary format, and converting them to unicode lists.
More information in https://github.com/erlang/otp/issues/6255
> erts: support unicode cmdline in compilation server

- erts/emulator/beam/break.c
- lib/kernel/src/group.erl
- lib/kernel/src/kernel.app.src
- lib/kernel/src/prim_tty.erl
- lib/kernel/src/user_drv.erl
- lib/kernel/test/interactive_shell_SUITE.erl
- lib/kernel/test/rtnode.erl
- lib/ssh/src/ssh_cli.erl
- lib/stdlib/doc/src/stdlib_app.xml
- lib/stdlib/src/edlin.erl
- lib/stdlib/src/edlin_expand.erl
- lib/stdlib/test/peer_SUITE.erl
- lib/stdlib/test/shell_SUITE.erl
This PR changes the tab-completion location to be after the current cursor instead of before. It is possible to configure the behaviour to work as it did before by setting the `stdlib` application parameter `shell_expand_location` to either `above` or `below`.
[![asciicast](https://asciinema.org/a/4tDMbPksWndZ6vApbsOUl1viL.svg)](https://asciinema.org/a/4tDMbPksWndZ6vApbsOUl1viL)
> kernel: Add support for expand after current line

- lib/inets/doc/src/httpd_util.xml
- lib/inets/src/http_client/httpc_response.erl
- lib/inets/src/http_server/httpd_util.erl
- lib/inets/test/httpc_SUITE.erl
- lib/inets/test/httpd_poll.erl
- lib/inets/test/httpd_time_test.erl
Fixes #6290 
Adds support for the 308 Permanent Redirect HTTP status code to `inets`, as described in [RFC 9110](https://datatracker.ietf.org/doc/rfc9110/).
> inets: Implement HTTP 308 Permanent Redirect

- erts/emulator/asan/suppress
- erts/emulator/beam/erl_async.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_thr_progress.c
- erts/emulator/beam/erl_thr_progress.h
Running "erl -emu_type asan -eval "erlang:halt()." shows several minor issues straight away. First, init_misc_aux_work is called twice (and first allocation is made orphan), second, when shutting down, async threads don't clean up thread progress data, and - an expected leak, even documented - signal stack.
> minor memory leaks fixes

- erts/doc/src/erl_cmd.xml
- erts/emulator/beam/erl_init.c
- erts/emulator/beam/jit/beam_asm.h
- erts/emulator/beam/jit/beam_jit_main.cpp
- erts/emulator/test/jit_SUITE.erl
- erts/etc/common/erlexec.c
Running the JIT with single-mapped RWX memory for JIT:ed machine code is needed for `perf` support. But as it is also useful for running under QEMU user mode emulation [1] this patch adds a new flag `+JMsingle bool` which controls the use of single-mapped RWX memory without triggering the output of perf-related metadata.
The naming of the flag is intended to follow the (perceived) pattern introduced by the `+JPperf`-flag, that is, `J` is a JIT-related option and `M` stands for memory related things.
Personally I use the additional patch below in order to use the same file system image for development on an amd64 build host and for deployment to an aarch64-target board. The patch detects when the VM is running using QEMU and if so, enables single-mapped memory. As the patch only works on …
> erts: Decouple use of single-mapped memory from `perf` support

- erts/emulator/beam/bif.tab
- erts/emulator/beam/erl_db.c
- lib/stdlib/doc/src/ets.xml
- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/src/ets.erl
- lib/stdlib/test/ets_SUITE.erl
Originally proposed in https://erlangforums.com/t/proposal-adding-ets-lookup-element-as-list-3/1743/4.
lookup_element/3 tends to be faster than lookup/2 when the key is always found, and is also a bit more ergonomic.
Unfortunately, when the key is absent, it throws an exception which is both somewhat slow and
less ergonomic to catch than matching the [] returned by lookup.
LeonardB suggested that a simple solution would be to offer an alternate version of lookup_element that takes an
extra argument, and returns that argument if the key is not found. This matches several other functions in the
standard library such as maps:get and proplists:get_value.
I confirmed the theory with some very simple microbenchmark: https://gist.github.com/RobinMorisset/62030c8fcb7376e16291904a9098e342
Code …
> Add lookup_element/4, which takes a default value

- lib/compiler/doc/src/compile.xml
- lib/dialyzer/src/dialyzer_utils.erl
- lib/dialyzer/test/small_SUITE_data/results/redefine_builtins
- lib/dialyzer/test/small_SUITE_data/src/redefine_builtin_type.erl
- lib/dialyzer/test/small_SUITE_data/src/redefine_builtins/a.erl
- lib/dialyzer/test/small_SUITE_data/src/redefine_builtins/b.erl
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
- system/doc/reference_manual/typespec.xml
If a module defines a type and a new built-in type is added with the same name, Dialyzer will allow the redefinition of that particular release for one release only. That makes it difficult to write code that is supposed to work for multiple releases of OTP.
For example, the OTP 24 release introduced the `nonempty_binary` type. Modules that had their own definition would continue to work in OTP 24 but not in OTP 25.
Always allow the name of a built-in type to be reused locally, in the same way that a definition of a function with the same name as a BIF will take precedence over the BIF. Starting from OTP 25, the built-in types belong to the erlang module, so it will always be possible to get the built-in definition if needed by prefixing the name with `erlang:`.
Closes #6132
> Allow local redefinition of built-in types

- system/doc/reference_manual/typespec.xml
Fix an error in the documentation from `make xmllint`
> documentation: fix XML linter error

- erts/emulator/beam/atom.names
- erts/emulator/beam/erl_db.c
- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/test/ets_SUITE.erl
Adds extra information in `erl_db.c` before returning the error for already used table name. The error is only returned if the option `named_table` is give and the name is already in use.
The extra information is used later to format the error message.
Closes #6252
> ets: improve ets:new/2 already_exists named_table error

- lib/kernel/doc/src/pg.xml
A tiny note to point how it can be used without the distributed features.
> pg: Note for local-only use cases

- lib/kernel/src/prim_tty.erl
- lib/kernel/test/interactive_shell_SUITE.erl
The column calculation was incorrect when the line where we want the completion was longer that the current screen size.
Fixes bug in #6260
> kernel: Fix expand below for long lines

- lib/kernel/src/pg.erl
Part of pg.erl in the stdlib has the following pattern: 
```
[{Key, Value1, Value2}] = ets:lookup(Table, Key)
```
Because Key appears on the left side, and is already bound, it results in an equality check between the Key
that is returned by lookup and the one that was passed to lookup. This is pointless since they are guaranteed to match.
I verified on a small example, and this results in 3 bytecode instructions and 19 (!) x86 instructions, all unnecessary.
It can be trivially avoided by using an unbound variable such as _Key:
```
[{_Key, Value1, Value2}] = ets:lookup(Table, Key)
```
I don't expect the performance win to be significant, but it is so simple that I think it worthwhile to land.
> Avoid redundant checks of the key returned by ets:lookup in pg.erl

- lib/asn1/src/asn1_db.erl
- lib/kernel/src/application.erl
- lib/kernel/src/application_controller.erl
- lib/kernel/src/inet_db.erl
- lib/kernel/src/pg.erl
- lib/stdlib/src/beam_lib.erl
When only one field of an ETS record is needed, using ets:lookup_element is usually faster than ets:lookup. This patch makes sure that we do so when possible in various erlang files in OTP, taking advantage of the recently landed ets:lookup_element/4 (https://github.com/erlang/otp/pull/6234) in places.
> Replace some uses of ets:lookup by ets:lookup_element in the stdlib

- lib/kernel/src/group.erl
- lib/kernel/test/interactive_shell_SUITE.erl
- lib/stdlib/doc/src/edlin_expand.xml
- lib/stdlib/src/edlin_expand.erl
- lib/stdlib/src/edlin_type_suggestion.erl
- lib/stdlib/test/edlin_expand_SUITE.erl
- lib/stdlib/test/edlin_expand_SUITE_data/complete_function_parameter.erl
* strip newlines after format_matches, we only want one
* find_type should recognize {type, any, []} as the any type
* functions with arity 0 and multiple other arities but
without typespecs should output the function/0
> stdlib: fix some autocompletion bugs

- erts/doc/src/erts_alloc.xml
- erts/emulator/beam/erl_alloc.c
- erts/emulator/beam/erl_alloc_util.c
- erts/emulator/beam/erl_alloc_util.h
- erts/emulator/sys/common/erl_mmap.c
- erts/emulator/sys/common/erl_mmap.h
- erts/etc/common/erlexec.c
This limit can be used to let erts_alloc know that it should
use MADV_FREE on any pages within a carrier that are currently
unused.
Before this change we have tried to have this as default, but that
caused performance issues as carriers oscillated in and out of the
migration pool. So in 25 we decided to remove it. However, this caused
MemAvailable from /proc/meminfo to become significantly lower and thus
machines that have a tight memory budget need this option.
So the solution is to add a new config option where the user can set
at which utilization limit that free pages in a carrier should be placed
in MemAvailable.
The option is by default set to 0, to mimic the behaviour of OTP 25.
> erts: Add acful, abandon carried free utilization limit

- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_db_hash.c
- erts/emulator/beam/erl_db_hash.h
- erts/emulator/beam/erl_db_util.h
- lib/stdlib/test/ets_SUITE.erl
A concurrent call to `ets:rename` could cause `ets:delete_all_objects` to fail halfway through with badarg and "the table identifier does not refer to an existing ETS table".
> Fix ets:rename during ets:delete_all_objects

- .github/scripts/build-base-image.sh
- .github/scripts/get-pr-number.es
- .github/workflows/main.yaml
- .github/workflows/pr-comment.yaml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I noticed this in the following build:
https://github.com/erlang/otp/actions/runs/3304563740/jobs/5454076885
"Build BASE image" step
> Convert from `::set-output` to `GITHUB_OUTPUT`

- lib/common_test/doc/src/write_test_chapter.xml
This` PR adds a missing case on how to write test case groups.
The missing case is that one can perform function calls at any point of the test case group as long as the result of the function call returns a `GroupsAndTestCases` ([Syntax for the Erlang TestCaseGroup docs](https://www.erlang.org/docs/23/apps/common_test/write_test_chapter.html#test-case-groups)).
The following example follows, which is also used in the OTP code:
```erlang
groups() ->
[
{http, [], real_requests()}
]
```
Closes #6342
> doc: add missing syntax case to Test Case Groups

- erts/emulator/beam/beam_load.c
- erts/preloaded/src/init.erl
- lib/kernel/test/init_SUITE.erl
Today if there is a crash during boot or eval,
because a more recent Erlang/OTP version is
required, the user is prompted with this message:
$ erl -noshell -s oops
{"init terminating in do_boot",{undef,
[{oops,start,[],[]},{init,start_em,1,[]}
,{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{oops,
start,[],[]},{init,start_em,1,[]},{init,
do_boot,3,[]}]})
Crash dump is being written to:
erl_crash.dump...done
Unfortunately, this message gives little indication
of what is wrong besides the "undef" atom. This
particularly problematic when users are running
a system software (Rebar, Elixir, etc) against an
old system version of Erlang/OTP.
This commit improves the boot error messages
such that:
1. It removes the double reports from erlang:display/1 and crash dump
2. Validates the …
> Improve boot and code loading error messages

- lib/sasl/src/sasl.app.src
- lib/sasl/src/systools_make.erl
- lib/sasl/test/systools_SUITE.erl
Fixes bug reported in GH-6368
This PR adds functionality to **systools:make_script**, to check .app parameters for duplicates.
The parameters that will be checked are **modules**, **applications** and **registered**.
> sasl: add error for duplicate atoms in app parameters

- erts/emulator/beam/break.c
On windows, the escapse sequence is \033[J, try if that works.
> erts: on windows \E[J does not work after we called break

- lib/stdlib/src/gen_server.erl
Cache callback functions handle_call, handle_cast and handle_info in a tuple when initializing the gen_server. This "should" give us a minor speed up by skipping lookups in export entry.
> stdlib: optimize gen_server by caching callback functions

- lib/compiler/src/beam_ssa_bsm.erl
- lib/compiler/test/bs_match_SUITE.erl
> compiler: Eliminate crash in the beam_ssa_bsm pass

- erts/emulator/beam/erl_bits.c
- erts/emulator/beam/erl_bits.h
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_utf_SUITE.erl
Currently, encoding a Unicode code point as UTF-8 in the binary syntax is done by calling a helper function written in C.
Optimize this by inlining all code for handling the ASCII subset of Unicode (code points less than 128). Handle other code points by calling a helper fragment implemented in native code. Calling a fragment has less overhead than calling a function implemented in C.
> Optimize encoding of utf8 segments in the binary syntax

- erts/doc/src/erl_nif.xml
- erts/doc/src/erlang.xml
- erts/emulator/beam/break.c
- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_init.c
- erts/emulator/beam/erl_lock_check.c
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_nif.h
- erts/emulator/beam/erl_nif_api_funcs.h
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process.h
- erts/emulator/beam/global.h
- erts/emulator/beam/io.c
- erts/emulator/test/dirty_nif_SUITE.erl
- erts/emulator/test/dirty_nif_SUITE_data/Makefile.src
- erts/emulator/test/dirty_nif_SUITE_data/dirty_nif_SUITE.c
- erts/emulator/test/dirty_nif_SUITE_data/on_halt_a.c
- erts/emulator/test/dirty_nif_SUITE_data/on_halt_b.c
- erts/emulator/test/dirty_nif_SUITE_data/on_halt_c.c
- erts/emulator/test/dirty_nif_SUITE_data/on_halt_d.c
- erts/emulator/test/dirty_nif_SUITE_data/on_halt_e.c
- erts/emulator/test/dirty_nif_SUITE_data/on_halt_f.c
- erts/emulator/test/dirty_nif_SUITE_data/on_halt_nif.c
- erts/preloaded/src/erlang.erl
[**`ErlNifOnHaltCallback`**](https://erlang.github.io/prs/6370/erts-13.1.2/doc/html/erl_nif.html#ErlNifOnHaltCallback)
`typedef void ErlNifOnHaltCallback(void *priv_data);`
The function prototype of an *on halt* callback function.
An *on halt* callback can be installed using `enif_set_option()`. Such an installed callback will be called when the runtime system is halting.
[**`ErlNifOption`**](https://erlang.github.io/prs/6370/erts-13.1.2/doc/html/erl_nif.html#ErlNifOption)
An enumeration of the options that can be set using `enif_set_option()`.
Currently valid options:
* `ERL_NIF_OPT_DELAY_HALT`
Enable delay of runtime system halt with flushing enabled until all calls to NIFs in the NIF library have returned
* `ERL_NIF_OPT_ON_HALT`
Install a callback that will be called when the runtime …
> On-halt and delayed halt support for NIFs

- lib/mnesia/src/mnesia_tm.erl
- lib/mnesia/test/mnesia_trans_access_test.erl
This is a pull request for idea #6376. A simple and light way for obtaining the active mnesia transactions counters for monitoring purposes
> [MnesiaTM] Lightweight method for obtaining an active mnesia transactions counters

- lib/dialyzer/src/dialyzer_dataflow.erl
- lib/dialyzer/src/dialyzer_typesig.erl
- lib/dialyzer/test/small_SUITE_data/results/bs_fail_constr
- lib/dialyzer/test/small_SUITE_data/src/bs_fail_constr.erl
> Eliminate Dialyzer crash for ill-typed code

- lib/compiler/src/beam_types.erl
This change increments the unit in the `#t_bitstring` type while decoding the type in `beam_types:decode_fix/2`. The unit is decremented while being encoded in `beam_types:encode_unit/1`.
This fixes a discrepancy between the types created when compiling to asm and the type decoded by `beam_disasm`.
For example, with the following snippet:
```erl
-module(enc).
-export([encode/1]).
encode(Bool) when is_boolean(Bool) ->
<<(encode_bool(Bool))/bitstring>>.
encode_bool(true)  -> <<1:1>>;
encode_bool(false) -> <<0:1>>.
```
Prior to this change, when `enc.erl` is compiled with `erlc -S enc.erl`, within the `bs_create_bin/6` the register is tagged as `#t_bitstring{size_unit=1}`. When compiled to beam and read with `beam_disasm:file/1` though, the register is tagged as `#t_bitstring{size_unit=0}`. …
> beam_types: Increment `#t_bitstring.size_unit` in decode

- lib/compiler/src/beam_disasm.erl
The `bs_create_bin/6` instruction was previously not fully translated by `beam_disasm`. This change resolves some of the args in the instruction (unwrapping `u` tags) and resolves the operation list to satisfy the checks in `beam_validator:verify_create_bin_list/2`.
> beam_disasm: Fix bs_create_bin/6 resolution

- erts/emulator/test/mtx_SUITE.erl
mtx_SUITE runtime limit is to low on machines with 100+ cores. This commit makes the runtime limit scale based on online schedulers.
> emulator: scale limit in mtx_SUTIE for machines with many cores

- lib/dialyzer/src/erl_types.erl
- lib/dialyzer/test/small_SUITE_data/src/list_none.erl
- lib/dialyzer/test/small_SUITE_data/src/stack.erl
Given the following module:
-module(list_none).
-export([new/0]).
-spec new() -> list(none()).
new() -> [].
dialyzer emits the following warning:
list_none.erl:4:2: Invalid type specification for function list_none:new/0. The success typing is
() -> []
No warning is expected, since `list(Type)` means a list containing zero or more elements. Even if `Type` is impossible, the empty list is still possible. Therefore, the success typing and the spec are consistent with each other.
Closes #6333
> dialyzer: Correct interpretation of [none()]

- lib/os_mon/doc/src/disksup.xml
- lib/os_mon/src/disksup.erl
- lib/os_mon/test/disksup_SUITE.erl
- Expanded type of `disk_space_check_interval` to `number()`
```
1> disksup:set_check_interval(0.5).
```
Fix #6283
> os_mon: allow check intervals smaller than 1 minute

- lib/os_mon/doc/src/disksup.xml
- lib/os_mon/src/disksup.erl
- lib/os_mon/test/disksup_SUITE.erl
References #6156
https://github.com/erlang/otp/issues/6156#issuecomment-1208010552
This PR adds support for a function that will immediately fetch total and available disk space for all local drives, or for a specific path.
> Add support for `disksup:get_disk_info/[0,1]`

- erts/doc/src/erlang.xml
* State that it only returns true when module is loaded as current code
* Remove warning about usage from other processes than code-server
> Adjust documentation of erlang:module_loaded()

- lib/compiler/src/beam_disasm.erl
`beam_validator:bs_integer_type/2` expects field flags to be a list of atoms (little, signed, native, etc.). This change reverses the bitflag encoding done in `beam_asm:flag_to_bit/1` and `beam_asm:encode_arg/2` to decode the field flags in `beam_disasm` as `beam_validator` expects.
> beam_disasm: Decode field flags

- lib/kernel/src/logger_h_common.erl
Noticed this in a log entry today. It's harmless but looks untidy.
> logger_common_h: remove extraneous space in mode_change msg

- lib/stdlib/src/beam_lib.erl
`beam_lib:all_chunks/1` returns the module contained in the given beam file/binary rather than the `beam_lib` atom if successful. Also see [`beam_lib:scan_beam/2`](https://github.com/erlang/otp/blob/54e4353c70fc4eb6ddc8fefd1475ca60366ffeeb/lib/stdlib/src/beam_lib.erl#L579-L581) which originally returns the module.
> beam_lib: Fix spec for all_chunks/1

- erts/emulator/beam/utils.c
- erts/emulator/test/bif_SUITE.erl
Negative values could either be accepted as some code point
```
1> list_to_atom([-3900]).
'Ä'
```
or cause an exception with an incorrect reason
```
2> catch list_to_atom([-1]).
{'EXIT',{[],[]}}
```
> Make list_to_atom reject all negative code points

- lib/wx/c_src/egl_impl.h
Currently the build of wx fails if `GL/gl.h` is present but `GL/glu.h` is not. This may happen, for example, in macOS if the homebrew `mesa` package is installed.
This change ensures that both `GL/gl.h` and `GL/glu.h` are present before including them.
> wx: fix build issue when GL/glu.h is not present

- lib/ssh/src/ssh_connection_handler.erl
graceful shutdown of ssh_conection_handler when connection is closed by peer
> graceful shutdown of ssh_conection_handler when connection is closedv

- lib/ftp/src/ftp.erl
- lib/ftp/test/ftp_SUITE.erl
This PR adds a missing pattern match case to the function `handle_ctrl_result` where the `caller` record attribute has 2 arguments instead of 3 arguments. When `caller` has 2 arguments and the data necessary to return it, we will return it. It seems like due to the timing of events, sometimes the `state` record may have the `caller` set with a 2-tuple or 3-tuple value.
Without the case added in here, one gets spurious results as `ok` , when one expects `{ok, "foobar\r\nbaz"}`
Closes #5823
> ftp: add missing case nlist

- lib/compiler/src/beam_disasm.erl
This PR builds on some prior work in #6447, #6451, #6452 for resolving instructions in `beam_disasm` so that they mirror `beam_asm` and are accepted by `beam_validator`. Each commit is a separate fix and the commit messages explains each change. (I can break these into separate PRs if that is desired.)
Thank you!
> Fix mistranslations in beam_disasm

- system/doc/design_principles/sup_princ.xml
> Fix typo in code snippet for supervisor example

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
Calling functions in guards is forbidden, but the compiler would fail to reject a function call from a default record initializer used in a guard. For example:
-record(test, {a = mk_a()}).
mk_a() -> 1.
test_rec(Rec) when Rec =:= #test{} ->
true.
Before this pull request, the compiler would fail to reject the illegal call to `mk_a/0`, and crash in a later pass. The compiler will now give the following error message:
t.erl:7:36: call to local/imported function mk_a/0 is illegal in guard
%    7|         test_rec(Rec) when Rec =:= #test{} ->
%     |                                    ^
Closes #6465
Closes #6466
> Don't allow local calls from record init in guards

- erts/emulator/beam/erl_process.c
- erts/emulator/test/process_SUITE.erl
Sending to a not fully spawned process (pid returned from `erlang:processes/0`) could crash the VM.
Bug exists since OTP-25.0 when parallel receive buffers were introduced.
Seen when system process literal_area_collector sends signals to all processes as part of a module purge operation. The VM was started with `+Meamin` (no custom erts allocators), which increases the probability of this crash.
> Fix sending bug to infant process

- erts/doc/src/erlang.xml
- lib/erl_docgen/priv/css/otp_doc.css
- lib/erl_docgen/priv/dtd/application.dtd
- lib/erl_docgen/priv/dtd/book.dtd
- lib/erl_docgen/priv/dtd/chapter.dtd
- lib/erl_docgen/priv/dtd/common.dtd
- lib/erl_docgen/priv/dtd/common.refs.dtd
- lib/erl_docgen/priv/dtd/part.dtd
- lib/erl_docgen/priv/xsl/db_html.xsl
- lib/erl_docgen/priv/xsl/db_man.xsl
- lib/erl_docgen/priv/xsl/db_pdf.xsl
- lib/erl_docgen/src/docgen_xml_to_chunk.erl
Just like `<note>` boxes but with a different color and label. To make it easier to find (or ignore) talk about semantic differences between OTP versions.
For demonstration, the `erlang` module has been updated with `<change>` tags.
Example: https://erlang.github.io/prs/6408/erts-13.1.2/doc/html/erlang.html#binary_to_atom-2
> Add new XML tag <change>

- lib/common_test/doc/src/ct.xml
- lib/common_test/src/ct.erl
We:
1. expose a new type (`ct:handle/0`) as per the current doc.
- alternatively we can just _spec_ this as `pid()` and remove the newly added type
2. export (existing, though private) type `ct:conn_log_option/0` as per the current doc
- same alternative approach (see 1.) applies
3. typespec all the functions in a very lazy approach (basically copy-paste from the doc. and then fix any Dialyzer issues/missing bits)
4. refer (in the .xml) to the newly added specs for ease of maintenance
- `make dialyzer` shows no issues
- `make xmllint` shows no issues
- local result for `make release_docs` seems to yield good result
- I've targeted the `erlang:master` branch, but maybe this can be released sooner (?)
- I followed https://github.com/erlang/otp/wiki/Documentation and got a note stating that …
> ct: prevent documentation errors and ease maintenance

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/bs_match_SUITE.erl
The following code:
f(_, X) ->
(case X of
<<_, 0>> ->
f();
_ ->
true
end),
X.
f() ->
ok.
would be rejected with this message:
consistency:1: function f/2+12:
Instruction: {bs_match,{f,0},{y,1},{commands,[{skip,8}]}}
Error:       throws_exception:
Reported by Robin Morisset in #6458.
> Fix internal consistency failure

- lib/stdlib/src/erl_expand_records.erl
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_expand_records_SUITE.erl
> Fix compiler crash when using a record as LC filter

- lib/kernel/doc/src/inet.xml
The following will be changed on Windows by this change:
We refuse usage of `SO_REUSEADDR` on non-UDP sockets since it mostly (perhaps only) opens up for socket collisions and probably hasn't got any useful use-cases. There are useful use-cases for multicast sockets, though. For more information see: https://learn.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse
Prior to OTP 25 we also refused to use `SO_REUSEADDR` on any sockets on Windows. See 2a6ac6f3f027fcab6d607599e82714e930d9fde2
We certainly do not want to use it for the Erlang distribution TCP sockets since we can end up reusing our own active sockets as demonstrated in the issue: #6461 
We probably want to expose the Windows specific `SO_EXCLUSIVEADDRUSE` in the API as well...
-----
Issue #4819 …
> Refuse usage of SO_REUSEADDR on non-UDP sockets on Windows

- lib/stdlib/src/erl_scan.erl
- lib/stdlib/test/erl_scan_SUITE.erl
- system/doc/reference_manual/data_types.xml
It is documented that `$\^X` is the code point (ASCII code) for Control X, where X is an uppercase or lowercase letter.
It turns out that it works for **all** characters:
1> $\^@.
0
2> $\^_.
31
3> $\^Γ.
19
4> $\*.
42
5> $\^😀.
0
6> $\^?.
31
Some of those are reasonable. `^@` and `^_` are allowed in Emacs and most other tools that support the caret notation.
It is reasonable to allow `^?`, but the value of it should be 127 (Delete) as in all other tools.
Allowing arbitrary letters and symbols does not make sense.
Therefore, this pull request modifies the rules for the caret notation to allow all characters in the range `16#40` through `16#4F` as well as lowercase `a` through `z`. That is, the following characters are allowed: `@`, `A`-`Z`, `[`, `\`, `]`, `^`, `_`, and `a`-`z`.  That makes …
> Reject invalid use of caret notation

- lib/inets/doc/specs/.gitignore
- lib/inets/doc/src/Makefile
- lib/inets/doc/src/httpc.xml
- lib/inets/doc/src/httpd.xml
- lib/inets/doc/src/specs.xml
- lib/inets/src/http_client/httpc.erl
- lib/inets/src/http_lib/http_transport.erl
- lib/inets/src/http_server/httpd.erl
- lib/inets/src/http_server/httpd_conf.erl
- lib/inets/src/http_server/httpd_sup.erl
- lib/inets/test/httpc_SUITE.erl
- lib/inets/test/httpd_SUITE.erl
This PR adds type specs to the API of the http_client app, file httpc.erl.
I have updated the XML documentation to use the type specs from httpc.erland this fixes https://github.com/erlang/otp/issues/6245
For some addressed comments, see #6300
Closes #6245
>  Add missing type specs in http library and replace `essl` option by `ssl`

- lib/ssl/src/tls_gen_connection.erl
- lib/ssl/src/tls_sender.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
- add process hibernation in tls_sender module
- hibernate_after option is expected to work sending process
- Fixes #6373
> Kuba/ssl/hibernate tls sender/otp 18314

- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/test/ssl_cert_SUITE.erl
In some cases the user may want the original der cert as input to the verify fun.
Allow the user to supply VerifyFun/4 as verify_fun option.
In later releases one can think that this should be enabled in public_key functions as well.
> ssl: VerifyFun can now get the der cert as argument

- .github/workflows/pr-comment.yaml
- .github/workflows/sync-github-releases.yaml
- https://github.com/actions/runner-images/issues/6673
- some jobs failed with ubuntu-22.04 which does not have rebar3
> gh: temporarily use 20.04 for some jobs

- lib/kernel/src/inet_db.erl
- lib/kernel/src/pg.erl
In https://github.com/erlang/otp/pull/6359, I used the new ets:lookup_element/4 in various places in the standard library.
In particular, I replaced a try/catch wrapping a call to lookup_element/3 in 3 places. Unfortunately, this catch was also catching the case where the table does not exist at all, and this breaks some applications.
This patch just restores the 3 try/catches.
> Fix bug introduced in PR 6359

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_type_SUITE.erl
When compiling the following code:
f1({X}) when X; (X orelse false) ->
(X orelse {}),
[
{X}#{
f2() orelse X => []
}
|| _ <- []
].
f2() ->
0.
the `beam_validator` pass rejects it:
call_only:1: function f1/1+27:
Instruction: {call_only,3,{f,16}}
Error:       {bad_arg_type,
{x,1},
{t_tuple,1,true,#{1 => {t_atom,[false,true]}}},
{t_union,none,none,none,
[{{1,{t_atom,[false]}},
{t_tuple,1,true,#{1 => {t_atom,[false]}}}},
{{1,{t_atom,[true]}},
{t_tuple,1,true,#{1 => {t_atom,[true]}}}}],
none}}:
What happens here is that when types are updated in different ways, the result will be different. That is not supposed to happen; there should be one canonical type representation regardless how it's reached.
This pull request resolves the bug …
> beam_validator: Eliminate type mismatch

- lib/stdlib/doc/src/string.xml
There is minor mistake in documentation of the string module. After docs generation it is visible as follows (split/2 is repeated twice and links to incorrect function):
'''
Grapheme clusters for codepoints of class prepend and non-modern (or decomposed) Hangul is not handled for performance reasons in find/3, replace/3, split/2, split/2 and trim/3.
'''
> Reference to split/3 function corrected

- lib/compiler/src/v3_kernel.erl
- lib/compiler/test/warnings_SUITE.erl
The pattern matching compiler conservatively assumed that binary patterns can never be re-ordered. Actually it is safe to re-order clauses that match binaries if the first segment in each clause match the same number of bits. Re-ordering clauses can help generating better code and also help detect redundant clauses.
For the following code:
word(<<"AND">>) -> <<"and">>;
word(<<"AS">>) -> <<"as">>;
word(<<"A">>) -> <<"a">>;
word(<<"AS">>) -> <<"as">>.
the compiler will now generate the following warning:
t.erl:6:1: Warning: this clause cannot match because a previous clause at line 5 always matches
%    6| word(<<"AS">>) -> <<"as">>;
%     | ^
The compiler will also generate slightly better code for the same example without the redundant clause:
word(<<"AND">>) -> <<"and">>;
word(<<"AS">>) …
> Improve optimization of binary matching

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/v3_core.erl
- lib/compiler/test/bs_match_SUITE.erl
- lib/compiler/test/map_SUITE.erl
- lib/compiler/test/match_SUITE.erl
- lib/compiler/test/warnings_SUITE.erl
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_eval_SUITE.erl
- lib/stdlib/test/erl_lint_SUITE.erl
- lib/stdlib/test/qlc_SUITE.erl
- system/doc/reference_manual/expressions.xml
Lift restrictions for matching of binaries and maps
There has always been an implementation limitation for matching
of binaries (for technical reasons). For example:
foo(Bin) ->
<<A:8>> = <<X:4,Y:4>> = Bin,
{A,X,Y}.
This would fail to compile with the following message:
t.erl:5:5: binary patterns cannot be matched in parallel using '='
%    5|     <<A:8>> = <<X:4,Y:4>> = Bin,
%     |     ^
This commit lifts this restriction, making the example legal.
A restriction for map matching is also lifted, but before we can
describe that, we'll need a digression to talk about the `=` operator.
The `=` operator can be used for two similar but slightly differently
purposes.
When used in a pattern in a clause, for example in a function head,
both the left-hand and right-hand side operands must be …
> Lift restrictions for matching of binaries and maps

- lib/compiler/src/beam_ssa_pre_codegen.erl
Starting from 4f0ec73674b5c0 (binary matching optimizations), the compiler could emit redundant `bs_get_position` and `bs_set_position` instructions.
> Remove redundant binary matching instructions

- erts/emulator/beam/erl_printf_term.c
- erts/emulator/test/map_SUITE.erl
The formatting of large maps done by erlang:display/1 used to reveal interesting information about the map internals, but was difficult to read, compared to the formatting of small maps. This commit aims at a similar (but still not sorted) display of large maps as for small maps.
This is important to those of us who regularly try to understand the state of our system from erlang:process_info(...,backtrace) or erlang:system_info(procs).
Pull request submitted based on issue #5585 discussion.
> [erts] Display large maps similarly to small maps

- lib/kernel/doc/src/os.xml
This patch adds a `and standard error` piece of (important?) information to the `os.cmd/1` docs.
See also http://erlang.org/pipermail/erlang-questions/2016-June/089640.html
```
Eshell V12.2.1  (abort with ^G)
1> os:cmd('echo foo >&2').
"foo\n"
```
> Mention that os.cmd/1 captures stderr as well.

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/bs_bincomp_SUITE.erl
> beam_ssa_pre_codegen: Eliminate crash in sub pass sanitize

- lib/compiler/src/beam_disasm.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/bs_match_SUITE.erl
`beam_validator` and `beam_disasm` assumed that there could only be one `get_tail` command in a `bs_match` instruction. That assumption is wrong. In rare circumstances, there can be more than one.
Closes #6551
> Eliminate internal error in beam_validator

- system/doc/reference_manual/expressions.xml
* Change "priority" to the standard terminology "precedence".
* Document the changed precedence of the `catch` operator.
* Mention the restrictions of `?=` in a note after the operand table.
* Mark the non-associative binary operators as such in the operand table.
> Correct some details in the operator table

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/core_fold_SUITE.erl
The `sys_core_fold` pass does a fixpoint iteration, limited to at most 20 iterations. One of the optimizations (coalescing two `let` constructs) would temporarily generate unsafe code, which would eventually be corrected, **unless** the 20 iteration limit was reached.
Closes #6572
> Eliminate crash in beam_kernel_to_ssa

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_type_SUITE.erl
Fixes #6552. The corresponding change for `'or'` requires a bit of refactoring and will be done in a later PR.
> compiler: Infer types through 'and' BIF

- erts/emulator/beam/erl_bif_info.c
- erts/emulator/test/bs_construct_SUITE.erl
When writable binaries were moved to a separate list `proc->wrt_bins`, they weren't added to the output of `process_info(Pid, binary)`. It led to interesting effects of binaries suddenly disappearing after running implicit GC caused by BIF calls, including `process_info` itself. Effectively, running `process_info(self(), binary)` twice in a row resulted in different lists, because first call triggers GC clearing out original binary from the off-heap list:
start() ->
OffHeapBin = crypto:strong_rand_bytes(1024 * 1024),
Bin = <<OffHeapBin/binary, "a">>,
Before = erlang:process_info(self(), [binary]),
After = erlang:process_info(self(), [binary]),
Before =/= After andalso erlang:display({wtf, Before, After}),
Bin.
Fixes #6573
> [erts] report writable binaries as off-heap binaries

- lib/kernel/test/os_SUITE.erl
- lib/kernel/test/os_SUITE_data/my_fds.c
* os_SUITE_data/my_fds.c: `read(stdin, buff, 1)` is invalid because stdin is a FILE* and not an fd, will become an error by default in clang 16.
* os_SUITE.erl: my_fds program now returns 0 bytes read instead of -1 for error, update assertion.
***
```
my_fds.c:11:20: error: incompatible pointer to integer conversion passing 'FILE *' (aka 'struct _IO_FILE *') to parameter of type 'int' [-Wint-conversion]
int res = read(stdin, buff, 1);
^~~~~
```
> kernel: os_SUITE: fix close_stdin test

- lib/stdlib/doc/src/math.xml
- lib/stdlib/src/math.erl
- lib/stdlib/test/math_SUITE.erl
https://tauday.com/tau-manifesto
Tau constant is already present and available in some prominent languages and libraries
- [.NET](https://learn.microsoft.com/en-us/dotnet/api/system.math.tau?view=net-7.0)
- [Rust](https://doc.rust-lang.org/std/f64/consts/constant.TAU.html)
- [Java](https://docs.oracle.com/en/java/javase/19/docs/api/java.base/java/lang/Math.html#TAU)
- [Python](https://docs.python.org/3/library/math.html#math.tau)
- [Boost](https://www.boost.org/doc/libs/1_38_0/boost/units/systems/si/codata/tau_constants.hpp)
> Add Tau constant to math module

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
We can't skip meeting literals since we may have to bail out when the result is 'none'. We still don't need to store the result however.
Fixes #6578
Fixes #6568
> beam_ssa_type: Don't filter out literals in meet_types/2

- lib/debugger/src/dbg_wx_view.erl
- lib/dialyzer/src/dialyzer_contracts.erl
- lib/dialyzer/src/dialyzer_dataflow.erl
- lib/dialyzer/src/dialyzer_typesig.erl
- lib/dialyzer/src/erl_bif_types.erl
- lib/dialyzer/src/erl_types.erl
- lib/dialyzer/test/user_SUITE_data/results/gh6580
- lib/dialyzer/test/user_SUITE_data/src/gh6580.erl
- lib/reltool/src/reltool_app_win.erl
- lib/stdlib/src/peer.erl
`?unit` can't be bound any more than `?none` can.
While we're at it, rename `t_is_none_or_unit/1` to `t_is_impossible/1` because the former is as silly as saying `t_is_integer_or_float/1` instead of `t_is_number/1`.
Fixes #6580
> dialyzer: Fix bug in bind_checked_inf/4

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
> beam_ssa_type: Fix size/unit estimation for literal binaries

- lib/public_key/src/pubkey_cert.erl
- lib/public_key/test/Makefile
- lib/public_key/test/pkits_SUITE.erl
- lib/public_key/test/pubkey_cert_SUITE.erl
This PR re-writes the validity algorithm to use the sliding window algorithm (see #6403 ), allowing certificates with the property `notAfter` to be accepted from the current date + 49 years in advanced. Certificates with `notBefore` date will work from current date - 50 years.
For example, certificates with `notBefore` and `notAfter` dates between [1972, 2071] (included both years) are valid. 
The sliding window works on old format certificates where the `notBefore` and `notAfter` values use the old format `YYMMDDHHMMSSZ`. New certificates should remove the `YY` (two digit year) ambiguity and use instead `YYYY`.
Closes #6403
> Improve `public_key:pkix_path_validation` to allow certificates that expire after 2050 

- lib/common_test/doc/src/ct_hooks_chapter.xml
- lib/tools/emacs/erlang-skels.el
Problem
======
When I copied the example hook from the Common Test User's Guide to use as a base for making a new hook
my editor complained about the code.
The example code has a syntax error (missing a period), and uses the deprecated erlang:now/0 function.
Fix
==
I followed the suggestions in ["How to Work with the New API"] to replace the `erlang:now/0` calls.
["How to Work with the New API"]: https://www.erlang.org/doc/apps/erts/time_correction.html#how-to-work-with-the-new-api
> Fix example code in ct_hooks_chapter.xml

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/test/bs_match_SUITE.erl
The `prefer_xregs` subpass sometimes mixed which registers were used for `bs_checked_xyz` psuedo-instructions, making the `bs_translate` subpass generate bogus code.
There's nothing wrong with mixing _per se_ though, so we probably want to teach the `bs_translate` pass how to handle this in the future.
```
{bs_match,{f,42},{y,1},{commands,[{ensure_at_least,16,1}]}}.
{bs_match,{f,0},{x,0},{commands,[{skip,8}]}}.
{bs_match,{f,42},{x,0},{commands,[{'=:=',nil,8,0},{ensure_exactly,0}]}}.
```
Fixes #6613
> beam_ssa_codegen: Don't break bs_match sequences by mixing registers

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/core_fold_SUITE.erl
> sys_core_fold: Eliminate crash in beam_kernel_to_ssa, again

- lib/syntax_tools/src/erl_syntax_lib.erl
- lib/syntax_tools/test/syntax_tools_SUITE.erl
Attempt to fix the behavior of `erl_syntax_lib:annotate_bindings/1-2` described in #4733 (labeled with "help wanted").
Issue is also mentioned in `erlang_ls` repo, so potential fix may also allow better UX while using it.
Description:
My plan was to include a case in `vann/2` function to handle `named_fun_expr`nodes correctly. Annotation process is almost identical to the one of `fun_expr`, obviously with the difference of handling `named_fun_expr`'s name. Name of the function is set into the environment for each of the clause patterns, because patterns can shadow the function name.
I included one concrete example for the testing purpose.
GitHub actions passed successfully on the fork repo.
> named_fun_expr annotate bindings fix

- lib/compiler/src/beam_bounds.erl
- lib/compiler/test/beam_bounds_SUITE.erl
> beam_bounds: Don't choke on division by zero

- erts/emulator/beam/dist.c
Could potentially cause memory leaks as well as double free crashes.
Have not been seen to cause problem other then `ASSERT(... (dep->dflags & DFLAG_SEND_SENDER) ...)` failing on debug built beam.
> Fix race receiving fragmented messages on terminating connection

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/core_fold_SUITE.erl
Third time's the charm?
Fixes #6630
> sys_core_fold: Always optimize bodies in move_let_into_expr

- erts/emulator/beam/bif.c
- erts/emulator/beam/dist.c
- erts/emulator/beam/erl_bif_guard.c
- erts/emulator/beam/erl_map.c
- erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
- erts/emulator/beam/jit/x86/ops.tab
- erts/emulator/test/bif_SUITE.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/src/beam_types.hrl
- lib/compiler/test/property_test/beam_types_prop.erl
The `node/1` BIF is frequently called by code in `gen_server`, `gen_statem`, `proc_lib`, and other standard library functions. This pull request optimizes it by producing inlined native code instead of calling the BIF code. There also some improvements in the compiler of the type analysis for `node/1` and `self/0`.
> Optimize the `node/1` BIF in the JIT

- lib/crypto/configure.ac
This commit fixes an issue wherein old versions of autoconf will misgenerate the configure script due to a missing comma an in AS_IF macro.
> lib/crypto: autoconf: Add missing ',' in an AC_IF

- lib/stdlib/doc/src/maps.xml
- lib/stdlib/src/maps.erl
I found the documentation for the recently introduced functions `maps:groups_from_list/2,3` particularly lacking:
* The purpose of the functions was present only in the `fsummary`, but not in the actual description.
* The word "split", commonly used in the sense of "chop into pieces", was IMO misleading. I replaced it with "partition" therefore.
* Some of the example lines were too long and overflowed the code display box of my browser.
* I improved the examples grouping on the 2-remainder of numbers to group on `even` and `odd` instead. I think this is nicer to the eye.
* I improved the wording of how the result map is constructed.
* I also changed the specs of the functions a bit to be more expressive.
Something I would like to put up for discussion is whether the statement "The order …
> Improve specs and docs for maps:groups_from_list/2,3

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/bs_construct_SUITE.erl
> beam_ssa_opt: Don't optimize constants larger than 1<<24 bits

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/core_fold_SUITE.erl
The optimization of nested lets was unsafe if the number of iterations for `sys_core_fold` ran out. There have been several attempts to fix that problem:
5076069ff1278ba7a511f8cdd449d2718abfa278 (#6624)
30d4c453ed6522b95faf771ff54530a513d70a44 (#6631)
ff05beecae2e002914515e94ab59930026dc9a75 (#6575)
It's time to cut the Gordian knot by removing the optimization. While at it, remove all optimizations of nested lets, not only the offending part of the optimization.
Running `scripts/diffable` before and after and diffing, shows changes in 40 modules. Most of them are neutral (the same instructions in a different order). There are few changes where an extra `test_heap` instruction has been introduced, for example in the `compile` module:
-    {test_heap,19,1}.
+    {test_heap,15,1}. …
> sys_core_fold: Remove problematic optimization

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_global.cpp
- erts/emulator/beam/jit/arm/instr_bif.cpp
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/arm/instr_call.cpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/instr_fun.cpp
- erts/emulator/beam/jit/arm/instr_map.cpp
- erts/emulator/beam/jit/arm/instr_msg.cpp
- erts/emulator/beam/jit/arm/instr_trace.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_global.cpp
- erts/emulator/beam/jit/x86/instr_bif.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_call.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_fun.cpp
- erts/emulator/beam/jit/x86/instr_map.cpp
- erts/emulator/beam/jit/x86/instr_msg.cpp
- erts/emulator/beam/jit/x86/instr_trace.cpp
Fix a few more buggy assertions similar to the one in #6646.
To make it easier to do the right thing, introduce new members to enum `Update`. If we are about to call a function that allocates heap space without using the stack pointer, we can now write:
```
emit_enter_runtime<Update::eHeapOnlyAlloc>();
```
which will make sure that both the heap pointer and stack pointer are saved in a debug build, but only the heap pointer in a release build.
For convenience, also introduce a shorthand for saving both the heap and stack pointer (as when doing a normal alloc using `HAlloc()`). We can now write:
```
emit_enter_runtime<Update::eHeapAlloc>();
```
instead of:
```
emit_enter_runtime<Update::eStack | Update::eHeap>();
```
> Fix more buggy assertions

- lib/public_key/test/pubkey_cert_SUITE.erl
There is a test pre2000 that had the year in utc format as follows: `720101000000Z` where the format is `YYMMDDHHMMSSZ` where `YY=Year`, `MM=Month`, `DD=Day`, `HH=Hours`, `MM=Minutes`, `SS=Seconds`. 
The test hits the function [`sliding_year_window`](https://github.com/erlang/otp/blob/maint/lib/public_key/src/pubkey_cert.erl#L686-L695) where the utc date is understood as a certificate option `notAftter` (not valid after). The [`sliding_year_window` ](https://github.com/erlang/otp/blob/maint/lib/public_key/src/pubkey_cert.erl#L686-L695) function takes the current year (2023) and substracts 50 years (`2023 - 50 = 1973`). The valid range of the certificates will be from [1973 - 2073]. 
To avoid depending on the year, I have removed all fixed dates to consider testing with dates calculated …
> public_key: fix pre2000 test with change of year 2023

- lib/dialyzer/src/dialyzer.erl
- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_cl.erl
- lib/dialyzer/src/dialyzer_cl_parse.erl
- lib/dialyzer/src/dialyzer_contracts.erl
- lib/dialyzer/src/dialyzer_options.erl
- lib/dialyzer/test/default_ignore_overlapping_contract_SUITE_data/dialyzer_options
- lib/dialyzer/test/default_ignore_overlapping_contract_SUITE_data/src/default_ignore_overlapping_contract.erl
- lib/dialyzer/test/indent_SUITE_data/dialyzer_options
- lib/dialyzer/test/indent_SUITE_data/results/contract3
- lib/dialyzer/test/overlapping_contract_SUITE_data/dialyzer_options
- lib/dialyzer/test/overlapping_contract_SUITE_data/results/overlapping_contract
- lib/dialyzer/test/overlapping_contract_SUITE_data/src/overlapping_contract.erl
- lib/dialyzer/test/small_SUITE_data/dialyzer_options
- lib/dialyzer/test/small_SUITE_data/results/contract3
- lib/stdlib/src/erl_lint.erl
- This PR makes the overlapping contracts warning of Dialyzer an opt-in flag, instead of considering them active by default.
- The PR also updates the message `"such contracts are currently unsupported and are simply ignored"` to `"such contracts cannot establish a dependency between the overloaded input and output types"`. The types are not really ignored and Dialyzer performs the union of them but it cannot establish a dependency between the input and output types
- Closes #6597 
- Closes #6117 
(Same as #6600 to see if the build system does not break)
> Sets overloaded domains/contracts as an opt-in flag

- lib/ssh/src/ssh_connection_handler.erl
- lib/ssh/src/ssh_transport.erl
Attempting to log reasons `ssh_connection_handler` may fail if the reason is an atom. This is because the `assure_string/1` function will return the original `Reason0` instead of the formatted result and `io_lib.format` can successfully format atoms, returning the original atom reason which then fails in `string:chomp/1`
```erlang
1> io_lib:format("~s", [undef]).
"undef"
2> string:chomp(undef).
** exception error: no function clause matching string:trim_t(undef,0,{["\r\n",10],"\r\n",undefined}) (string.erl, line 885)
3>
```
This changes to return the formatted result rather than the original when attempting to use `assure_string/1`
<details>
<summary>Discovery details</summary>
For reference, this was discovered while trying to implement …
> Fix `ssh_connection_handler` logging of atoms

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/bs_match_SUITE.erl
> Fix unsafe optimization of try...after

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_construct_SUITE.erl
The JIT did not properly check the type of `Something` in code similar to:
b(Something) ->
<<Something/bits>>.
Calling `b/1` with a non-binary argument would most of the time crash the runtime system immediately instead of raising an exception.
This bug was introduced in 976b2a61c86f4d (#6086).
Closes #6655
> Fix crash in binary construction

- erts/emulator/beam/beam_common.c
- erts/emulator/test/map_SUITE.erl
This is a followup to PR #1889 almost 5 years in the making. The optimisation there was implemented for many cases, but somehow `M#{existing_key => same_value}` and `M#{existing_key => new_value}` cases were missed.
This is a bit more complicated since there are two cases to handle:
* the keys and values didn't change, and we can just return the original map
* the keys didn't change, but values did - we return a new map but keeping original keys tuple
This seems to be hit fairly frequently - while I was working on it it wasn't even possible to start the VM successfully.
I'll provide benchmarks at a later time
> Do not allocate a new map when the value is the same encore

- lib/inets/src/http_client/httpc.erl
- lib/inets/src/http_client/httpc_handler.erl
- lib/inets/src/http_client/httpc_request.erl
- lib/inets/src/http_client/httpc_response.erl
- lib/inets/src/http_lib/http_chunk.erl
- lib/inets/src/http_lib/http_transport.erl
- lib/inets/src/http_server/httpd_request.erl
- lib/inets/src/http_server/mod_cgi.erl
- lib/inets/test/httpc_SUITE.erl
- lib/inets/test/httpd_bench_SUITE.erl
- lib/inets/test/httpd_poll.erl
- lib/inets/test/httpd_test_lib.erl
- lib/inets/test/httpd_time_test.erl
Replace calls in the `inets` module from `size/1` to `tuple_size/1` or `byte_size/1`.
This PR is part of issue (PR) #6669
> inets: replace calls `size/1` to `XXX_size/1`

- lib/public_key/src/public_key.erl
Replace calls `size/1` from the `public_key` module
#6672
> public_key: replace calls to `size/1` function by `XXX_size/1`

- lib/xmerl/doc/examples/test_html.erl
Replace calls to `size/1` in `xmerl` app by `XXX_size/1`
#6672
> xmerl: replace calls `size/1` to `XXX_size/1`

- erts/preloaded/src/init.erl
This is a snippet of how it looks like:
```erlang
{progress,preloaded}
{progress,kernel_load_completed}
{progress,modules_loaded}
{start,heart}
{'done_in_µs',17}
{start,logger}
{'done_in_µs',1473}
{start,application_controller}
{'done_in_µs',19451}
{progress,init_kernel_started}
{apply,{application,load,[{application,stdlib,[{description,"ERTS  CXC 138 10"},{vsn,"4.2"},{id,[]},{modules,[array,base64,beam_lib,binary,c,calendar,dets,dets_server,dets_sup,dets_utils,dets_v9,dict,digraph,digraph_utils,edlin,edlin_context,edlin_expand,edlin_type_suggestion,epp,eval_bits,erl_abstract_code,erl_anno,erl_bits,erl_compile,erl_error,erl_eval,erl_expand_records,erl_features,erl_internal,erl_lint,erl_parse,erl_posix_msg,erl_pp,erl_scan,erl_stdlib_errors,erl_tar,error_logger_file_h,error_logger_tty_h,esc …
```
> Include timing on -init_debug to further aid debugging

- lib/stdlib/src/supervisor.erl
Removes unnecessary `undefined` types added to the `supervisor` state record.
> stdlib: remove unnecessary undefined from records

- erts/emulator/beam/erl_trace.c
This closes https://github.com/erlang/otp/issues/6448
> avoid crash when tracer = erts_tracer_nil

- lib/ssl/src/dtls_connection.erl
- lib/ssl/src/dtls_gen_connection.erl
- lib/ssl/src/dtls_packet_demux.erl
- lib/ssl/src/dtls_record.erl
- lib/ssl/test/dtls_api_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
> dtls re-connections

- lib/common_test/src/ct_framework.erl
- lib/common_test/src/ct_groups.erl
- lib/common_test/src/ct_netconfc.erl
- lib/common_test/src/ct_ssh.erl
- lib/common_test/src/ct_testspec.erl
- lib/common_test/src/ct_util.erl
- lib/common_test/test/test_server_SUITE.erl
The `size/1` BIF is not optimized by the JIT, and its use can result in worse types for Dialyzer.
When one knows that the value being tested must be a tuple, `tuple_size/1` should always be preferred.
When one knows that the value being tested must be a binary, `byte_size/1` should be preferred. However, `byte_size/1` also accepts a bitstring (rounding up size to a whole number of bytes), so one must make sure that the call to `byte_size/1` is preceded by a call to `is_binary/1` to ensure that bitstrings are rejected. Note that the compiler removes redundant calls to `is_binary/1`, so if one is not sure whether previous code had made sure that the argument is a binary, it does not harm to add an `is_binary/1` test immediately before the call to `byte_size/1`.
> ct: Replace size/1 with either tuple_size/1 or byte_size/1

- erts/doc/src/erl_dist_protocol.xml
- lib/erl_interface/src/connect/ei_connect.c
- lib/erl_interface/src/epmd/ei_epmd.h
- lib/erl_interface/test/ei_tmo_SUITE.erl
- lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
- lib/kernel/src/dist_util.erl
- lib/kernel/test/erl_distribution_wb_SUITE.erl
Fixes #6595.
Make OTP-25 accept old `send_name` handshake messages used by OTP-22 and older. OTP-23 or OTP-24 nodes, **not using epmd**, may send the old message to us if they do not know our OTP version.
Hence, we accept the old `send_name` and the accompanying `send_complement`, but we do not send them ourself.
This was removed prematurely in OTP-25.0 by commit 722219f211092e0c4b919f3ba4f91df42191c0e7.
Therefore versions 25.0 to 25.2.* are broken in this regard and may reject connection setup from OTP-23 and 24 not using epmd.
> kernel: Accept ver5 distribution connection setup

- lib/stdlib/doc/src/timer.xml
- lib/stdlib/src/timer.erl
- lib/stdlib/test/timer_simple_SUITE.erl
- added a final `erlang:time_unit()` argument to `tc/[1,2,3]`
Tackles #3264. Primarily for systems with worse resolution than a microsecond.
> stdlib/timer: better resolution control

- lib/compiler/src/v3_core.erl
- lib/compiler/test/bs_construct_SUITE.erl
Constructing a binary with an explicit `all` size would crash the compiler.
Closes #6707
> Eliminate compiler crash in binary construction

- erts/doc/src/erl_cmd.xml
- erts/doc/src/erlang.xml
- erts/emulator/beam/atom.names
- erts/emulator/beam/bif.c
- erts/emulator/beam/break.c
- erts/emulator/beam/emu/bs_instrs.tab
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_bits.c
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/erl_gc.h
- erts/emulator/beam/erl_init.c
- erts/emulator/beam/erl_process.h
- erts/emulator/beam/external.c
- erts/emulator/beam/jit/beam_jit_common.cpp
- erts/emulator/test/process_SUITE.erl
- erts/etc/common/erlexec.c
- erts/preloaded/src/erlang.erl
Fixes #5889.
Instead of adding a new limit "max_vheap_size", this PR proposes an option to the existing max_heap_size map:
`#{include_shared_bins => true | false}
`
If set to `true` off-heap binaries ("vheap") is included in the total heap size compared against the `max_heap_size` limit.
Default is false to keep existing semantics.
> Support including off-heap binaries in max_heap_size

- erts/emulator/beam/beam_common.c
- erts/emulator/beam/beam_transform_helpers.c
- erts/emulator/beam/dist.c
- erts/emulator/beam/erl_map.c
- erts/emulator/beam/erl_map.h
- erts/emulator/beam/erl_utils.h
- erts/emulator/beam/external.c
- erts/emulator/beam/utils.c
- erts/emulator/test/map_SUITE.erl
- lib/kernel/test/logger_formatter_SUITE.erl
- lib/stdlib/test/io_SUITE.erl
This should optimize all operations on small maps
that rely on ordering. As an example, creating a
map with 32 keys named 'atom-INDEX', where INDEX
is an integer, is an order of magnitude faster
with this patch.
Before:
from_list      624.32 K        1.60 μs   ±723.44%        1.54 μs        1.71 μs
After:
from_list        6.23 M      160.47 ns ±15898.23%         125 ns         167 ns
It has been verified that the distribution and
ETS will respect the atom ordering of the system
and therefore are backwards compatible.
A potential downside is that the order of atom
fields in maps is no longer deterministic, but
that's already the case for large maps, and having
non-deterministic atom ordering may help avoid
code that accidentally relies on order.
This patch also opens up the possibility for …
> Use in-memory atom ordering for map ordering

- erts/emulator/beam/beam_types.c
- erts/emulator/beam/beam_types.h
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_module.cpp
- erts/emulator/beam/jit/arm/instr_arith.cpp
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/instr_float.cpp
- erts/emulator/beam/jit/arm/instr_fun.cpp
- erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
- erts/emulator/beam/jit/arm/instr_map.cpp
- erts/emulator/beam/jit/arm/instr_select.cpp
- erts/emulator/beam/jit/beam_jit_common.hpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_arith.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_float.cpp
- erts/emulator/beam/jit/x86/instr_fun.cpp
- erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
- erts/emulator/beam/jit/x86/instr_map.cpp
- erts/emulator/beam/jit/x86/instr_select.cpp
We've had a few too many bugs where we used `BEAM_TYPE_INTEGER | BEAM_TYPE_MASK_BOXED` instead of  `BEAM_TYPE_INTEGER | BEAM_TYPE_ALWAYS_BOXED`.
This PR turns that kind of error, and a few other misuses, into compile-time errors.
> jit: Turn various type hint bugs into compile-time errors

- lib/stdlib/test/erl_lint_SUITE.erl
Fix typo: `unkonwn` -> `unknown`
> Fix typo in lib/stdlib/test/erl_lint_SUITE.erl

- lib/observer/src/crashdump_viewer.erl
Fix typo: `unkonwn` -> `unknown`
> Fix typo in lib/observer crashdump_viewer

- erts/emulator/beam/erl_map.c
- erts/preloaded/src/erts_internal.erl
- lib/stdlib/doc/src/io.xml
- lib/stdlib/doc/src/io_lib.xml
- lib/stdlib/doc/src/maps.xml
- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/src/io_lib.erl
- lib/stdlib/src/io_lib_format.erl
- lib/stdlib/src/io_lib_pretty.erl
- lib/stdlib/src/maps.erl
- lib/stdlib/test/io_SUITE.erl
- lib/stdlib/test/maps_SUITE.erl
This PR add support for both term-ordered and custom order of keys for map iterators.  It also includes support for specifying the ordering of maps when printing or formatting.
Summary of changes:
1. New function: `maps:iterator/2`
> Accepts a `map()` as the first argument and `undefined` (the default for `maps:iterator/1`), `ordered`, or a 2-arity comparison function `fun((A :: Key, B :: Key) -> boolean())`.
> 
> For example:
> ```erlang
> %% Ordered
> Iter = maps:iterator(#{a => b, c => d}, ordered),
> {a, b, NextIter} = maps:next(Iter).
> 
> %% Reversed
> Iter = maps:iterator(#{a => b, c => d}, fun(A, B) -> B =< A end),
> {c, d, NextIter} = maps:next(NextIter).
> ```
2. <del>New function: `maps:next_key/1`
> Accepts a `maps:iterator()` and returns `{Key, NextIter}`.  This is the same …
> Add maps:iterator/2 with ~k and ~K format options for printing ordered maps.

- lib/stdlib/doc/src/ets.xml
Resolves some confusing docs due to a slight grammatical mistake
> stdlib: Fix grammar in ETS docs

- lib/stdlib/doc/src/io.xml
- lib/stdlib/doc/src/io_lib.xml
- lib/stdlib/doc/src/maps.xml
- lib/stdlib/src/io_lib_format.erl
- lib/stdlib/src/maps.erl
- lib/stdlib/test/io_SUITE.erl
- lib/stdlib/test/maps_SUITE.erl
This PR is a continuation of #6718 which adds support for `reversed` key order for maps iterators.
Summary:
1. Changed type: `maps:iterator_order/0,1` now supports `reversed`
2. Changed function: `maps:iterator/2` now accepts `reversed`
3. Tests for all of the above in `io_SUITE` and `maps_SUITE`
> ```bash
> make stdlib_test ARGS="-suite io_SUITE"
> make stdlib_test ARGS="-suite maps_SUITE"
> ```
4. Updated `maps.xml`, `io.xml`, and `io_lib.xml` documentation.
> Add reversed iterators for maps

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/test/bs_match_SUITE.erl
See #6623 for a fix to a similar bug reported in #6613.
Closes #6755
> Don't break bs_match sequences by mixing registers (again)

- erts/preloaded/src/prim_file.erl
When requested time format is already posix, we don't need to adjust anything, but the old code would still copy the `#file_info` record, we can skip the adjustments a function earlier and avoid this copy.
Before `prim_file:read_file_info("mix.exs", [raw, {time, posix}])` would allocate 432 bytes, now it only allocates 312 bytes.
This will require bootstrap update to propagate, but I skipped this as usually requested for external contributors.
> prim_file:read_file_info/2 avoid copying the record for posix time read

- lib/kernel/src/error_logger.erl
- lib/kernel/src/group_history.erl
- lib/stdlib/src/shell.erl
Replace some calls to `application:get_env/2` with `application:get_env/3`. This simplifies the code at the call site, and as an additional benefit, `application:get_env/3` is slightly more efficient than `application:get_env/2`.
> Simplify some calls to application:get_env/2

- lib/stdlib/src/maps.erl
- lib/stdlib/test/maps_SUITE.erl
`maps:to_list` for iterators can be written in a much simpler fashion by simply _trying_ the given iterator with `next` (see https://github.com/erlang/otp/pull/6718#discussion_r1091660046).
> Simplify implementation of maps:to_list/1 for iterators

- lib/kernel/src/erl_erts_errors.erl
- lib/kernel/src/erl_kernel_errors.erl
- lib/ssl/src/ssl.erl
- lib/stdlib/src/erl_posix_msg.erl
- lib/stdlib/src/erl_stdlib_errors.erl
Fixes https://github.com/erlang/otp/issues/6748 
I updated the PR in `hex_core` to not leak the `too_big` error down into `erl_posix_msg.erl` but I believe the PR still stands. Someone else may end up in a similar scenario and end up requiring to patch OTP in order to figure out where the error is originating from.
> [#6748] Unknown posix errors should include the error reason

- lib/stdlib/doc/src/base64.xml
- lib/stdlib/src/base64.erl
- lib/stdlib/test/base64_SUITE.erl
- lib/stdlib/test/property_test/base64_prop.erl
This extends base64 encoding and decoding routines to allow skipping emitting final = characters, or to accept encoded data with final = characters skipped. This format is common for some use-cases. Today, parsing it requires appending the missing = characters, which incurs an unnecessary copy of the input data, or re-implementing the entire routine.
This amends the interface in a backwards-incompatible way, since the last change wasn't released yet, so should have no expectation of backwards-compatibility.
Additionally, tests are slightly enhanced to cover more cases directly with simple examples.
If this change is accepted, I will provide documentation.
> base64: allow skipping padding = characters

- erts/preloaded/src/init.erl
This PR may be a bit controversial but I would say it is worth it.
The `init` process has a feature where it tries to preemptively
fix code paths. To do so, it has to traverse all paths and perform
(most commonly) two additional file system lookups.
https://github.com/erlang/otp/blob/bdf564f8ee2ef847a33dded0f30bb9073779ace7/erts/preloaded/src/init.erl#L1125-L1161
While trying to optimize the boot process, I have noticed this
does show up when profiling. 1-2ms on my (fast) local machine
for `erl` and 3-4ms with Elixir (it uses -pa and -pz with increases
the cost for every loaded application).
When trying this on an actual application, such as Livebook which
has 50 dependencies, I got up to 10ms spent on patching paths
on a Linux-like machine typically used for deployment (emulated
with …
> Default -code_path_choice to strict 

- lib/observer/doc/src/observer.xml
- lib/observer/src/observer.erl
- lib/observer/src/observer_wx.erl
- lib/observer/test/observer_SUITE.erl
- Allow starting the observer connected to a node
- Ignore repeated nodedown messages
> Observer Improvements

- lib/compiler/src/beam_ssa_recv.erl
- lib/compiler/test/receive_SUITE.erl
- lib/stdlib/src/gen.erl
`gen_server:call/2,3` uses an optimization where only the messages received after sending the request are searched for the response, greatly speeding up calls inside processes that have very large message queues.
Unfortunately, this optimization doesn't kick in if you split it up into the largely equivalent `gen_server:send_request/2` and `gen_server:receive_response/2` functions. This PR fixes that.
> Optimize gen:send_request/3 + gen:wait_response/2 sequences

- lib/compiler/src/beam_listing.erl
- lib/compiler/src/beam_ssa_check.erl
- lib/compiler/src/beam_ssa_pp.erl
- lib/compiler/src/compiler.app.src
- lib/compiler/src/v3_kernel_pp.erl
This is most important for *.S files because they are often diffed using the [scripts/diffable](https://github.com/erlang/otp/blob/master/scripts/diffable) script.
> compiler: Print map entries in deterministic order

- lib/crypto/src/crypto.erl
When one knows that the value being tested must be a binary, <c>byte_size/1</c> should be preferred.
Links to #6672
> crypto: replace size/1 by byte_size/1

- lib/diameter/src/base/diameter_peer_fsm.erl
- lib/diameter/src/info/diameter_dbg.erl
> diameter: replace size/1 by xxx_size/1

- lib/inets/src/http_server/httpd_request_handler.erl
- lib/inets/src/http_server/httpd_util.erl
> inets: replace size/1 by xxx_size/1

- lib/mnesia/src/mnesia_index.erl
- lib/mnesia/src/mnesia_lib.erl
- lib/mnesia/src/mnesia_loader.erl
- lib/mnesia/src/mnesia_schema.erl
- lib/mnesia/src/mnesia_snmp_hook.erl
> mnesia: replace size/1 by xxx_size/1

- lib/megaco/src/engine/megaco_filter.erl
- lib/megaco/src/engine/megaco_messenger_misc.erl
- lib/megaco/src/engine/megaco_trans_sender.erl
- lib/megaco/src/flex/megaco_flex_scanner.erl
- lib/megaco/src/tcp/megaco_tcp.erl
- lib/megaco/src/tcp/megaco_tcp_connection.erl
- lib/megaco/src/udp/megaco_udp.erl
- lib/megaco/src/udp/megaco_udp_server.erl
> megaco: replace size/1 by xxx_size/1

- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/src/maps.erl
- lib/stdlib/test/maps_SUITE.erl
Follow-up of #6762 (Thanks @bjorng for suggestions made there :smiley:)
The current implementations of `maps` functions that accept iterators (namely, `filter/2`, `filtermap/2`, `fold/3`, `foreach/2` and `map/2`) test if the input is really an iterator by calling `next/1` on it once in a `try`. If this call fails by `next` raising a **`badarg`** error, the calling function catches it and raises a **`badmap`** error instead. However, if the iterator fails later on (eg giving a tuple like `{a, b, c}` as input passes the first call to `next`, but calling it again on the follow-up "iterator" `c` fails), the **`badarg`** error is bubbled up instead of the **`badmap`** error.
Running the entire algorithm (eg. the actual mapping) in a `try` (vs only the first call to `next`) is not feasible, as …
> maps: always raise a `badmap` error if an iterator fails

- lib/kernel/src/file.erl
- lib/kernel/src/file_io_server.erl
- lib/kernel/src/file_server.erl
- lib/kernel/test/file_SUITE.erl
- lib/stdlib/test/error_logger_h_SUITE.erl
~~Accessing a table by reference is [around 10% faster][1] on a quiet system with a lot of named tables since looking up the table name is relatively expensive. It's even worse in a system with a lot of ETS operations, since looking up a table involves locking, which can have high contention.~~
~~This doesn't seem to impact performance of file:open/2 in a measurable way on a quiet system, but it doesn't look detrimental either and logically should be saving some CPU.~~
This table was used to store Pids of files opened through the file server, however this data was never used by OTP itself. We can skip the overhead of storing this information.
[1]: https://gist.github.com/michalmuskala/5e7fc0031048f89f64b6cc4468d124a3
> Remove the file_io_servers ETS table

- lib/ftp/src/ftp.erl
- lib/ftp/src/ftp_response.erl
The size/1 BIF is not optimized by the JIT, and its use can result in worse types for Dialyzer.
When one knows that the value being tested must be a tuple, tuple_size/1 should always be preferred.
When one knows that the value being tested must be a binary, byte_size/1 should be preferred. However, byte_size/1 also accepts a bitstring (rounding up size to a whole number of bytes), so one must make sure that the call to byte_size/ is preceded by a call to is_binary/1 to ensure that bitstrings are rejected. Note that the compiler removes redundant calls to is_binary/1, so if one is not sure whether previous code had made sure that the argument is a binary, it does not harm to add an is_binary/1 test immediately before the call to byte_size/1.
This PR extends #6770 simply in the branch …
> ftp: replace size/1 by XXX_size/1

- lib/crypto/src/crypto.erl
This is a fix to the bug introduced in PR-6768
> crypto: fix error bit_size/1 by byte_size/1

- erts/doc/src/erl_cmd.xml
- erts/emulator/beam/erl_init.c
- erts/emulator/beam/jit/beam_asm.h
- erts/emulator/beam/jit/beam_jit_main.cpp
Supporting `perf record --call-graph=fp` is nice but it does come at a slight cost. This PR adds an option to suppress frame pointers for those who would like to use `--call-graph=lbr` instead.
> erts: Add `+JPperf no_fp` option to suppress frame pointers

- lib/ssh/src/ssh.hrl
- lib/ssh/src/ssh_agent.erl
- lib/ssh/src/ssh_bits.erl
- lib/ssh/src/ssh_client_channel.erl
- lib/ssh/src/ssh_connection.erl
- lib/ssh/src/ssh_connection_handler.erl
- lib/ssh/src/ssh_file.erl
- lib/ssh/src/ssh_sftp.erl
- lib/ssh/src/ssh_transport.erl
- lib/ssh/src/ssh_xfer.erl
> ssh: replace size/1 by xxx_size/1

- lib/xmerl/src/xmerl_eventp.erl
> xmerl: replace size/1 by xxx_size/1

- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_db_catree.c
- erts/emulator/beam/erl_db_hash.c
- erts/emulator/beam/erl_db_tree.c
- erts/emulator/beam/erl_db_tree_util.h
- erts/emulator/beam/erl_db_util.h
- lib/stdlib/doc/src/ets.xml
- lib/stdlib/test/ets_SUITE.erl
Since OTP 23, when inserting a list of values into an ets `bag` table, values for the same key are inserted in reversed order (prior to OTP 22, they were inserted in the order in the list).
Implementing fix suggested by @sverker to build linked list of `DbTerm` values stored against a key by _appending_ (rather than _prepending_ as it had been doing).
Fix for https://github.com/erlang/otp/issues/6730 (see description there for code to reproduce + original correct behaviour on OTP 22, and regression behaviour on OTP >= 23)
> ets:insert/2 insert order preserved when list with same keys for bag table

- lib/ssl/src/ssl_cipher.erl
> ssl: replace size/1 by xxx_size/1

- lib/tftp/src/tftp_binary.erl
- lib/tftp/src/tftp_engine.erl
- lib/tftp/src/tftp_file.erl
- lib/tftp/src/tftp_lib.erl
> tftp: replace size/1 by xxx_size/1

- lib/snmp/src/agent/snmp_generic_mnesia.erl
- lib/snmp/src/agent/snmp_index.erl
- lib/snmp/src/agent/snmpa_local_db.erl
- lib/snmp/src/agent/snmpa_mib_data_ttln.erl
- lib/snmp/src/agent/snmpa_mib_data_tttn.erl
- lib/snmp/src/agent/snmpa_mpd.erl
- lib/snmp/src/manager/snmpm_net_if.erl
- lib/snmp/src/misc/snmp_pdus.erl
> snmp: replace size/1 by xxx_size/1

- lib/compiler/src/v3_core.erl
- lib/compiler/test/mc_SUITE.erl
Fixes the bug reported in https://github.com/erlang/otp/pull/6727#issuecomment-1418853979.
> Fix compiler crash for literal map generator patterns

- erts/doc/src/erlang.xml
- erts/emulator/beam/atom.names
- erts/emulator/beam/beam_bp.c
- erts/emulator/beam/beam_bp.h
- erts/emulator/beam/beam_common.c
- erts/emulator/beam/beam_common.h
- erts/emulator/beam/emu/beam_emu.c
- erts/emulator/beam/emu/ops.tab
- erts/emulator/beam/emu/trace_instrs.tab
- erts/emulator/beam/erl_bif_trace.c
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/erl_message.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process.h
- erts/emulator/beam/erl_trace.h
- erts/emulator/beam/erl_vm.h
- erts/emulator/beam/jit/arm/instr_trace.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/beam_jit_common.cpp
- erts/emulator/beam/jit/beam_jit_main.cpp
- erts/emulator/beam/jit/x86/instr_trace.cpp
- erts/emulator/beam/jit/x86/ops.tab
- erts/emulator/internal_doc/Tracing.md
- erts/emulator/test/Makefile
- erts/emulator/test/trace_call_memory_SUITE.erl
- erts/emulator/test/trace_call_time_SUITE.erl
- erts/etc/unix/etp.py
- erts/preloaded/src/erlang.erl
Similar to call_time, erlang:trace_pattern(..., [call_memory]) accumulates memory allocations, allowing for basic heap profiling.
Inspired by @garazdawi's prototype discussed on Erlang Forums. This PR implements only the underlying mechanism. Heap profiler itself (`hprof`) is in works here: https://github.com/erlang/otp/commit/62b184611779a84fa66d43af3971938e67e80be0
> [erts] Implement call_memory tracing

- lib/kernel/doc/src/code.xml
- lib/kernel/src/code_server.erl
- lib/kernel/test/code_SUITE.erl
- system/doc/general_info/scheduled_for_removal_26.inc
Archives have a feature where both the archive directory and the application directory can co-exist and the contents of the archive will be read as a fallback. This pull request removes this feature as it is implicit behaviour and has a direct impact on each code path added to the code server with two additional file system lookups per code path.
Furthermore, I struggle to see the benefit of this feature:
1. This could be used to provide a fallback `ebin` directory for a given application, but this requires an application without `ebin` to be added to the code path, which is slightly contradictory as the `ebin` directory is the one typically added to the code path in the first place
2. You most likely cannot  add `priv` from an archive because the functions in the `file` module cannot …
> Remove archives fallback in code path

- lib/kernel/src/inet_db.erl
- lib/kernel/src/inet_dns.erl
- lib/kernel/src/inet_dns.hrl
- lib/kernel/src/inet_dns_record_adts.pl
- lib/kernel/src/inet_res.erl
Resolves #6606.
This implements the only bit I noticed was missing for RFC6891 from the original EDNS RFC2671, that is the DNSSEC OK bit (DO) in the OPT RR.  By this we should be able to claim supporting RFC6891.
Still, we do not have any other DNSSEC records implemented, so they will be a possible future improvement.
Has anyone tried to use `inet_res` for DNSSEC records?  I try to set this bit to see if I can get records, but has not succeeded.
`inet_res:resolve("google.com", in, 30, [verbose, {edns, 0}, {dnssec_ok, true}])` does not return any "30" record, which should be NXT RR.  Any pointers?
> Update inet_res et.al. for RFC6891; EDNS with DNSSEC OK bit

- lib/diameter/src/diameter.appup.src
This commit updates the appup file forgotten in PR-6702 and PR-6769 as well as other calls from `size/1` to `byte_size/1`
> diameter: update appup files

- lib/kernel/doc/src/application.xml
- lib/kernel/src/application.erl
- lib/kernel/src/application_master.erl
- lib/kernel/test/application_SUITE.erl
It returns the Pid of the supervisor running at
the root of the given application.
This allows tools for introspection and debugging
to print supervision trees without relying on
private APIs.
> Add application:get_supervisor/1

- lib/dialyzer/doc/src/dialyzer.xml
- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_cl_parse.erl
- lib/dialyzer/src/dialyzer_options.erl
- lib/dialyzer/test/cplt_SUITE.erl
- lib/dialyzer/test/dialyzer_cl_SUITE.erl
- lib/dialyzer/test/dialyzer_common.erl
- lib/dialyzer/test/incremental_SUITE.erl
- lib/dialyzer/test/indent2_SUITE_data/dialyzer_options
- lib/dialyzer/test/indent_SUITE_data/dialyzer_options
- lib/dialyzer/test/iplt_SUITE.erl
- lib/dialyzer/test/line_SUITE_data/dialyzer_options
- lib/dialyzer/test/map_SUITE_data/dialyzer_options
- lib/dialyzer/test/opaque_SUITE_data/dialyzer_options
- lib/dialyzer/test/options1_SUITE_data/dialyzer_options
- lib/dialyzer/test/options2_SUITE_data/dialyzer_options
- lib/dialyzer/test/r9c_SUITE_data/dialyzer_options
- lib/dialyzer/test/small_SUITE_data/dialyzer_options
- lib/dialyzer/test/underspecs_SUITE_data/dialyzer_options
- lib/dialyzer/test/user_SUITE_data/dialyzer_options
- lib/stdlib/src/erl_lint.erl
Prior to this PR, Dialyzer used to have disabled (by default) warnings about unknown types and functions. 
This default value has been overwritten; Dialyzer now warns about unknown types and functions (as requested by the community in GH-5695). Thus, the following two examples are equivalent, i.e., passing the `-Wunknown` function is enabled by default:
```
dialyzer moduler.erl -Wunknown -Wmissing_return
dialyzer moduler.erl -Wmissing_return
```
Dialyzer has a new flag, `-Wno_unknown`. Its purpose is to supress warnings about unknown functions and types.
Users who wish to suppress these warnings can invoke Dialyzer using this flag. Example:
```
dialyzer module.erl -Wno_unknown
```
> dialyzer: make -Wunknown a default; add -Wno_unknown flag

- lib/stdlib/test/io_SUITE.erl
- lib/stdlib/test/maps_SUITE.erl
The `>=/2` sort function is not appropriate for sorting maps with mixed integer and float keys. It happens to work with small maps because `maps:to_list/1` returns a list already correctly sorted. In a debug build, the four-elements maps are large maps and the test case fails.
While at it, also correct `ARevCmpFun`.
> STDLIB tests: Fix falling map iterator tests in debug build

- lib/dialyzer/src/dialyzer.erl
In outlier cases, with ordinals over twenty, the old code would produce strings such as `"21th"`, `"101th"` rather than  `"21st"`, `"101st"`. This resolves a minor grammatical issue in Dialyzer warning messages.
Example results of `ordinal/1`:
```
"1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th","11th","12th",
"13th","14th","15th","16th","17th","18th","19th","20th","21st","22nd","23rd",
"24th","25th","26th","27th","28th","29th","30th","31st","32nd","33rd","34th",
"35th","36th","37th","38th","39th","40th","41st","42nd","43rd","44th","45th",
"46th","47th","48th","49th","50th","51st","52nd","53rd","54th","55th","56th",
"57th","58th","59th","60th","61st","62nd","63rd","64th","65th","66th","67th",
"68th","69th","70th","71st","72nd","73rd","74th","75th","76th","77th","78th", …
```
> dialyzer: Fix ordinal for numbers over twenty

- lib/ssl/src/inet_tls_dist.erl
During shutdown, net_kernel process that is linked to an acceptor, gracefully terminates, triggering
`{EXIT, net_kernel, shutdown}` message sent to the acceptor.
However acceptor does not expect it, and instead of a graceful shutdown logs a confusing warning.
> Do not emit "unexpected" message on shutdown

- lib/ftp/src/ftp.erl
this commit fixes a mistake in GH-6793 where a guard was removed.
> ftp: fix forgotten guard

- lib/kernel/src/code.erl
- lib/kernel/src/code_server.erl
load_file/1, load_abs/2, and load_binary/3 now
perform most of the work on the client.
is_sticky/1 and is_loaded/1 now read directly
from the module database.
PS: I could not move ensure_loaded/1 to the
client for reasons I could not understand yet.
> Reduce contention on the code_server

- lib/kernel/doc/src/application.xml
- lib/kernel/src/application.erl
- lib/kernel/src/application_controller.erl
- lib/kernel/test/application_SUITE.erl
We build a DAG with all application dependencies
and start leaves recursively. As each application
starts, we further traverse the graph looking for
more leaves.
This PR always traverse children applications
concurrently by default. Let me know if there is
an interest in making this setting configurable.
> Start children applications concurrently

- lib/ssl/src/tls_connection_1_3.erl
Always disregard one change_cipher_spec during handshake, even though middlebox mode is not used, to maximize compatibility.
Closes #6772
> ssl: Maximize compatibility

- lib/ssl/src/ssl_handshake.hrl
Lower maximum handshake size to mitigate memory usage with very large certificate chains. Should not effect the normal use cases and is configurable if needed.
> ssl: Mitigate memory usage from large certificate chains

- erts/preloaded/src/erl_prim_loader.erl
- lib/kernel/doc/src/code.xml
- lib/kernel/src/code.erl
- lib/kernel/src/code_server.erl
- lib/kernel/test/code_SUITE.erl
When an application has several entries in its code path, loading modules in interactive mode becomes more expensive because of code path misses.
This commit introduces code path caching, where we can opt-in into caching each directory individually.
This won’t be applied to all paths but a project has several paths that are unlikely to change while a system is running in development or test:
* the paths from Erlang/OTP won’t be written to by most projects
* paths from build tools and other languages
* non-local dependencies, such as the ones from Hex/Git
Loading of the cache happens lazily, as to avoid introducing rehashes, or any upfront cost.
This change brought the boot time of Livebook (the time to start all apps in interactive mode for dev+test) on my machine (MacStudio M1 Max) from …
> Add code path caching

- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_match_bin_SUITE.erl
Code matching out empty binaries such as in the following example:
start() ->
[0 || <<V1:0/bits, V1:0/bitstring, V2:0/bytes, V2:0/bits>> <= <<>>].
could crash the runtime system. (This bug is not present in OTP 25 or earlier.)
Thanks to Robin Morisset for noticing this bug.
> Fix crash when matching out empty binaries

- lib/compiler/src/Makefile
- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_pp.erl
- lib/compiler/src/beam_ssa_private_append.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/src/beam_types.hrl
- lib/compiler/src/compile.erl
- lib/compiler/src/compiler.app.src
- lib/compiler/test/beam_ssa_check_SUITE.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/appendable.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/gen_bs_size_unit_checks.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/ret_annotation.erl
- lib/compiler/test/beam_types_SUITE.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/annotations_pp.erl
- lib/compiler/test/property_test/beam_types_prop.erl
When a binary is grown by appending data to it using `bs_create_bin`,
a considerable performance improvement can be achieved if the append
can be done using the destructive `private_append` instead of
`append`. Using `private_append` flavor of `bs_create_bin` is only
possible when the binary being extended has been created by
`bs_writable_binary` or by another `bs_create_bin` using
`private_append`. As `private_append` is destructive, an additional
requirement is that there is only one live reference to the binary
being being extended.
This set of patches implements the compiler optimization described above together with its dependencies.
> `private_append` optimization for binaries

- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/standards_compliance.xml
- lib/ssl/src/dtls_handshake.hrl
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/ssl_handshake.hrl
- lib/ssl/test/Makefile
- lib/ssl/test/property_test/ssl_eqc_handshake.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
- lib/ssl/test/ssl_use_srtp_SUITE.erl
This PR implements encoding and decoding of use_srtp hello extension (RFC 5764) which is necessary for setting up an SRTP channel. SRTP is used in WebRTC.
This feature was requested in #3771
To add use_srtp to hello extensions, you need to pass 'use_srtp_protection_profiles' option, e.g.
`ssl:connect("localhost", 17423, [{protocol, dtls},
{use_srtp_protection_profiles, [<<0,1>>, <<0,5>>]}, {handshake, hello}]).`
Proper value for use_srtp_protection_profiles option is a list of 2-byte binary profile ids (see section 4.1.2 of RFC 5764)
Optionally you may specify use_srtp_mki option to set srtp_mki field (I don't need it now but someone may need it later).
> ssl: implement use_srtp hello extension with options

- erts/emulator/beam/jit/arm/instr_arith.cpp
- erts/emulator/test/small_SUITE.erl
With the AArch64 (AMD64) JIT, calling `bxor` with non-integer operands in a guard would crash the runtime system.
> AArch64 JIT: Fix crash in bxor/2

- lib/os_mon/c_src/memsup.c
- lib/os_mon/c_src/memsup.h
- lib/os_mon/include/memsup.hrl
- lib/os_mon/src/cpu_sup.erl
- lib/os_mon/src/memsup.erl
Closes #4221
There seems to be a similar issue with memsup. Should I include it here?
> os_mon: Close cpu_sup and memsup port on terminate

- erts/test/erlc_SUITE.erl
erlc_SUITE.erl:494:27: Warning: a term is constructed, but never used
%  494|         {{win32,\_}, _} -> {skip, "Unicode paths not supported on windows"};
%     |                           ^
erlc_SUITE.erl:495:23: Warning: a term is constructed, but never used
%  495|         {\_,latin1} -> {skip, "Cannot interpret unicode filenames when native_name_encoding is latin1"};
%     |
> Fix erts/test/erlc_SUITE.erl testcase warnings

- erts/emulator/beam/erl_bif_info.c
`process_info(Pid, status)` on another process could return an erroneous result.
> process_info(Pid, status) fix

- lib/compiler/src/beam_ssa_private_append.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
[This patch is flawed, will revise it in the morning]
The private-append optimization worked on the assumption that the `private_append` version of `bs_create_bin` checked that the type of the first argument was a bitstring. As it doesn't, the compiler shouldn't do the optimization when it cannot guarantee that the type is and only is a bitstring.
> compiler: Don't generate unsafe code for binary append

- lib/compiler/src/beam_ssa_private_append.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Avoid a crash in the private-append optimization due to attempting to rewrite a literal which isn't a bitstring.
As value tracking is done without type information, it can happen that when following def chains, we encounter literals which are not bitstrings. We should never schedule a literal which isn't a bitstring for rewriting when the complete literal is what we are tracking, i.e. when the element is `self`.
Closes #6847
> compiler: Avoid crash in private-append optimization

- lib/stdlib/src/binary.erl
- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/test/binary_module_SUITE.erl
The code for the `binary:encode_hex/1` and `binary:encode_hex/2` functions has been simplified. The simplified implementation has a more consistent runtime compared to the old implementation. To test the performance, I made a new `hex_bench` benchmark based on the `base64` benchmark:
https://gist.github.com/bjorng/522470f313ac01d16156a597657f97bb
For the old implementation, on my M1 Mac the results for the best case and worst case are as follows:
Size: 1024*1024 (divisible by 8)
fun binary:encode_hex/1: 1000 iterations in 1899 ms: 526 it/sec
Size: 1024*1024 + 1 (not divisible by 2 through 7)
fun binary:encode_hex/1: 1000 iterations in 5984 ms: 167 it/sec
That is, the worst case is about three times slower than the best case.
The simplifed encode function shows much less variation:
Size: …
> binary: Polish the hex encoding and decoding functions

- erts/emulator/beam/emu/bs_instrs.tab
- erts/emulator/beam/emu/instrs.tab
- erts/emulator/beam/emu/macros.tab
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/jit/arm/beam_asm_global.cpp
- erts/emulator/beam/jit/x86/beam_asm_global.cpp
- erts/emulator/test/process_SUITE.erl
Executing receive-related instructions would cause the process to enter a suspended state forever. Avoid that by scheduling out immediately after any GC if the process is exiting.
> Exit process immediately when the max heap size is exceeded

- lib/compiler/src/v3_core.erl
- lib/compiler/test/match_SUITE.erl
- lib/compiler/test/warnings_SUITE.erl
The compiler would generate incorrect code for the following type of expression:
Pattern = BoundVar1 = . . . = BoundVarN = Expression
An exception should be raised if any of the bound variables have different values than `Expression`. The compiler would generate code that would cause the bound variables to be bound to the value of `Expression` whether the value matched or not.
For example:
t() ->
Zero = 0,
One = 1,
Result = One = Zero,
{Result,One,Zero}.
There should be a `badmatch` exception, but instead, the `t/0` function returned `{0,0,0}`.
Closes #6873
> Eliminate "mutable variables"

- lib/compiler/src/beam_ssa_private_append.erl
With the decision to not introduce a private append variant of `bs_create_bin` which gracefully tolerates non-binary string arguments, we can remove many code paths in `beam_ssa_private_append.erl` which are never reached as we will never try to track and patch the tail field of a cons.
> compiler: Remove dead code from private-append optimization

- lib/inets/src/http_client/httpc_handler.erl
- lib/inets/src/http_client/httpc_internal.hrl
This PR adds some type specifications to the `inets` module.
These have been checked by Dialyzer and eqWAlizer. 
Note: Not all types have been added because that would require bigger changes in `stdlib`, but the ones that were possible have been added and are type checked by eqWalizer. The ones that are not possible usually refer to prop lists, because the return type in the spec is always `term()`, which makes eqWAlizer to think that `term()` is the input type to another function. When this other function expects (e.g.,) `integer()`, it reports a mismatch between `term()` and `integer()`.
> inets: add type specifications

- lib/common_test/src/ct_release_test.erl
- lib/kernel/src/wrap_log_reader.erl
- lib/ssl/src/ssl.erl
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
- lib/tools/src/xref.erl
Dialyzer (or `erl_lint.erl`) was accepting code of the following form:
```erlang
-spec run_test(Opts) -> term()
when Opts :: {join_specs, Bool} | {test, Bool}.
run_test(Opts) ->    {error, fail}.
```
But this cannot be ever checked by Dialyzer as the type variable `Bool` is in an union, which means that `Bool` happened only once and thus, `Bool` is an unbound type variable. Essentially, the example above should be rejected by Dialyzer as is the one below:
```erlang
-spec run_test_error(Opts) -> term()
when Opts :: {join_specs, Bool}.
run_test_error(Opts) ->
{error, fail}.
```
This commit fixes GH-6508 and adds a bunch of tests to `erl_lint.erl` so that we can keep track of which singleton type variables should throw an error and which ones are ok.
> dialyzer: fix singleton type var in union types

- lib/syntax_tools/src/erl_syntax_lib.erl
The docs ([example](https://www.erlang.org/doc/man/erl_syntax_lib.html#analyze_function-1)) contain some emphasis tags (within code snippets) which end up visible in the documentation. I fixed these by removing the unwanted tags.
> Removed unnecessary <em> tags

- lib/stdlib/src/supervisor.erl
- lib/stdlib/test/supervisor_SUITE.erl
Static supervisors are very idle processes after they have started so they will now be hibernated after start to improve resource management.
> stdlib: Hibernate static supervisors

- lib/kernel/doc/src/code.xml
- lib/kernel/src/code.erl
- lib/kernel/src/code_server.erl
- lib/kernel/test/code_SUITE.erl
This pull request adds an optional cache/nocache
argument to all `add_path*` functions, `set_path`,
and `replace_path`.
It also adds `del_paths/1` to make it easier to
clear multiple paths and `clear_cache/0` for
clearing the whole code path caching without
disabling it.
To be merged after #6729.
> Add del_paths/1, clear_cache/0, and cache arg 

- system/doc/top/Makefile
Currently release_man_spec for system/doc/top fails on GNU make 4.3
make[3]: Entering directory '/home/dav/.kerl/builds/26.0-rc1-master/otp_src_git/system/doc/top'
make[3]: *** No rule to make target '/home/dav/erlang/26.0-rc1-master/doc/docbuild\', needed by 'release_man_spec'.  Stop.
Due to breaking change done in GNU make sp variable is empty in qs and sq calls (note a `\` after `docbuild`).
Previously appending using `+=` to an empty variable would result in a value starting with a space.  Since 4.3 the initial space is only added if the variable already contains some value.
<https://lists.gnu.org/archive/html/info-gnu/2020-01/msg00004.html>
> Fix release_docs for GNU make 4.3

- lib/ftp/doc/specs/.gitignore
- lib/ftp/doc/src/Makefile
- lib/ftp/doc/src/ftp.xml
- lib/ftp/doc/src/specs.xml
- lib/ftp/src/Makefile
- lib/ftp/src/ftp.app.src
- lib/ftp/src/ftp.erl
- lib/ftp/src/ftp_internal.erl
- lib/ftp/src/ftp_sup.erl
- lib/ftp/test/ftp_SUITE.erl
Fixes some type specs from the ftp module. These have been validated by eqWAlizer.
> ftp: fix types in ftp module

- erts/doc/src/erl_nif.xml
Mention that atoms created in load are available in all environments. The best practice is to pre-create all of them before usage, make sure this best practice is included in the documentation.
Also fixed a "has" that should have been a "have".
> Add best practice for atoms in NIFs

- lib/dialyzer/src/dialyzer_cl.erl
- lib/dialyzer/test/dialyzer_cl_SUITE.erl
The code previously assumed that multiple PLTs would only be used in combination with an analysis, but adding multiple PLTs to another without analysis was not considered.
The existing logic for merging PLTs was used in the context of an analysis, with different data to hand, so here we just validate the merge, then sequentially add each PLT.
Resolves #6850
> dialyzer: Fix crash when adding multiple PLTs

- lib/kernel/src/group.erl
- lib/stdlib/src/io_lib.erl
This PR fixes a bug that `file:read(standard_io, ..)` call in escript could unexpectedly return `eof` if `io:setopts(standard_io, [binary])` is set.
This bug seems introduced by https://github.com/erlang/otp/commit/72a5fc13ffa3370d96844c3cef3268546e8fe7cb that replaced `user` module by `group` module.
Creates an escript file that calls `file:read/2` twice.
```erlang
#!/usr/bin/env escript
%% filename: foo.erl
main([]) ->
ok = io:setopts(standard_io, [binary]),
io:format("1st: ~p", [file:read(standard_io, 3)]),
io:format("2nd: ~p", [file:read(standard_io, 3)]).
```
Starts Erlang shell and invokes the above escript via `open_port/2`.
After `erlang:port_command(P, ["foo"]).` is called, the second `file:read/2` call in the escript file will return falsey `eof`.
```erlang
$ chmod +x foo.erl
$ …
```
> Fix a bug that `file:read(standard_io, ..)` unexpectedly returns `eof`

- erts/emulator/beam/utils.c
- erts/emulator/test/map_SUITE.erl
This fix did not make it into 26.0-rc1, where the bug was introduced by #6151.
_Don't let this bug deter you from trying 26.0-rc1. Even though easy to reproduce with the right maps we judge it row risk to actually cause any problems._ 
```
1> #{aaa => v, true => v} < #{bbb => v, [] => v}.
false
```
should be `true` as `aaa` < `bbb`.
Necessary bug conditions:
* Small map (<= 32 keys)
* Identical number of keys
* Zero or identical numeric keys (integers and floats)
* Different number of atom keys
The bug compares consistent on a node, but can differ on different node instances if the atoms get different internal index (caused by module load order for example).
> Fix map compare bug

- lib/inets/src/http_client/httpc_handler.erl
refactor the code to place variables in header record assignments on the right hand side. for example, the following
```erlang
do_handle_info(..., State=#state{...})
```
should be replaced by
```erlang
do_handle_info(..., #state{...}=State)
```
to keep the code consistent.
> inets: refactor code for consistency

- lib/compiler/test/beam_ssa_check_SUITE.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/alias_non_convergence.erl
Add a test case which exercises the portions of the alias analysis which deals with a non-converging fixpoint iteration.
> compiler: Improve code coverage in alias analysis

- erts/emulator/beam/bif.c
- erts/emulator/beam/big.c
- erts/emulator/beam/big.h
- erts/emulator/test/list_bif_SUITE.erl
- erts/emulator/test/num_bif_SUITE.erl
Let `list_to_integer/1` and `list_to_integer/2` raise a `system_limit` exception when the result doesn't fit in a bignum. Let `string:to_integer/1` return `{error,system_limit}` when the result doesn't fit.
> list_to_integer() & friends: Don't crash for overlong lists

- lib/kernel/src/logger_olp.erl
- lib/kernel/test/logger_SUITE.erl
- lib/stdlib/doc/src/proc_lib.xml
- lib/stdlib/src/gen.erl
- lib/stdlib/src/gen_fsm.erl
- lib/stdlib/src/gen_server.erl
- lib/stdlib/src/gen_statem.erl
- lib/stdlib/src/proc_lib.erl
- lib/stdlib/test/gen_server_SUITE.erl
- lib/stdlib/test/gen_statem_SUITE.erl
- lib/stdlib/test/supervisor_SUITE.erl
- system/doc/design_principles/spec_proc.xml
* Implement a function `proc_lib:init_fail/2,3` to call from `proc_lib` started processes when they fail to initialize instead of `proc_lib:init_ack/1,2`.  The new function sends a `{nack,,}` to the spawner that then uses a process monitor on the spawned process to await the monitor `'DOWN'` message before returning a failure to the spawner.
This avoids a race when using `proc_lib:init_ack/1,2` which
allows the spawner to get and return the failure return value, and restart a new server instance while the old instance not yet has been scheduled for exit and cleanup.  The old server instance may hold a VM resource such as a named ETS table that the new server instance fails to create.
* Use the new init fail function in Kernel and Stdlib.
> Implement synchronous init failure for gen processes

- lib/stdlib/src/lists.erl
- lib/stdlib/test/lists_SUITE.erl
- lib/stdlib/test/lists_property_test_SUITE.erl
- lib/stdlib/test/property_test/lists_prop.erl
This PR addresses a few shortcomings and inconcistencies that I discovered in the `merge` family of functions in the `lists` module.
* if the second (and third, in the variants that take 3 lists) list is empty, the call is fast and returns the first list; however, if the first list is not empty but the second (and third) list is, the call is slow as it does not simply return the other list but runs through the algorithm
* if the second (and third) list is empty, the first argument can really be anything, it does not have to be a list at all; for example, `lists:merge(foo, [])` will happily return `foo`. For `merge/1`/`umerge/1` this will also happen if the list of lists contains only empty lists and a single non-list; for example, `lists:merge([[], foo, []])` will return `foo`
The changes …
> Improve the `lists:merge` family of functions

- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/test/beam_ssa_check_SUITE.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/alias_chain.erl
This is a set of patches which speeds up the alias analysis pass by reducing the number of iterations required to find a fix point and reduces the amount of work in each iteration.
> Compiler: alias analysis speedup

- system/doc/reference_manual/expressions.xml
While at it, reorganize the documentation for the bit syntax into separate sections for each type of segment.
Closes #6706
> Fix factual errors and omissions for the bit syntax

- erts/emulator/beam/copy.c
- erts/emulator/beam/erl_db_hash.c
- erts/emulator/beam/erl_db_tree.c
- erts/emulator/beam/erl_db_util.c
- erts/emulator/beam/erl_db_util.h
- erts/emulator/beam/erl_term.h
- erts/emulator/beam/global.h
- lib/stdlib/test/ets_SUITE.erl
@michalmuskala pointed to me that sometimes ets:lookup_element can be
slower than ets:lookup, even when the value is found. For example:
```
erlperf "ets:lookup(ac_tab, {env, kernel, logger})." "ets:lookup_element(ac_tab, {env, kernel, logger}, 2)."
Code                                                          ||        QPS       Time     Rel
ets:lookup(ac_tab, {env, kernel, logger}).                     1    2859 Ki     349 ns    100%
ets:lookup_element(ac_tab, {env, kernel, logger}, 2).          1    2164 Ki     462 ns     75%
```
The reason for this is that lookup can find the size of the allocation
needed directly in the DbTerm, then copy the whole thing efficiently
with copy_shallow_x, whereas lookup_element must first walk all over the
value to be copied in size_object_x, and then …
> Optimize the copy that occurs in ets:lookup_element

- lib/stdlib/src/ms_transform.erl
- lib/stdlib/test/ms_transform_SUITE.erl
caller_line/0 was added in https://github.com/erlang/otp/pull/5305, while current_stacktrace/0,/1 were added in
https://github.com/erlang/otp/pull/6628
> ms_transform: allow caller_line and current_stacktrace action functions

- system/doc/reference_manual/expressions.xml
* Document that variables bound in a generator expression is not visible outside that expression.
* Document the failure modes for filters.
Closes #6454
> Address a few omissions in documentation of comprehensions

- lib/stdlib/src/edlin_expand.erl
- lib/stdlib/test/edlin_expand_SUITE.erl
It was reported in the OTP 26 rc1 thread that zero arity functions was omitted if there was part of a multi arity function definition, this fixes this issue.
> Fixes bug in shell completion

- lib/kernel/src/code.erl
This was missed when merging commit
eacdabcf8e9fba1b4d32dbd0caf60ea9d9161a38 which removed the native flag from prepared_code()
> Fix multi_load_SUITE, by updating verify_prepared

- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/src/beam_ssa_private_append.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Nick Vatamaniuc reported that the following Erlang snippet:
```
B1 = << <<"x">> || true >>,
B2 = <<B1/binary, "z">>,
```
created identical `B1` and `B2` binaries. The error occurs because the private-append pass was missing the condition that for a transform from `bs_create_bin append, ...` to `bs_create_bin private_append, ...` to be safe, the first fragment must die with the `bs_create_bin` instruction, it is not enough that the fragment is unique and appendable.
The error is avoided by having the alias analysis, which has access to liveness information, annotate `bs_create_bin` instructions with a boolean annotation indicating whether the first fragment dies with the instruction. The later private-append pass can then consult the annotation to determine if the transform is safe. The …
> compiler: Avoid unsafe rewrite to bs_create_bin private_append

- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_type_SUITE.erl
The `beam_validator` pass would reject the following code:
f(X) ->
element(42,
case X of
{_,_} -> X;
_ -> ok
end).
The reason is an inconsistency between the return values of the functions `will_succeed/3` and `types/3` in the `beam_call_types` module. When `types/3` returns `none` (indicating that the call always fails), `will_succeed/3` MUST return `no`. Otherwise, `beam_validator` will reject the code.
In this case, when asked whether the call to `element/2` would succeed, `will_succeed/3` answered `maybe`, while `types/3` returned `none`.
To avoid similar bugs in the future, this commit not only fixes the inconsistency, but also refactors `will_succeed/3` to always let the new helper function `fails_on_conflict/3` handle the `maybe` case, ensuring that whenever `types/3` returns …
> beam_call_types: Fix inconsistency

- erts/emulator/beam/jit/x86/instr_bs.cpp
When matching an `utf8` segment, valgrind could generate a warning stating that a jump or conditional move was based on an uninitialized value. The following instructions were the culprit:
test rax, rax
short jns L107
Those instructions test the most significant bit of the `rax` register and jumps if it is zero. The most significant bit is always initialized when the `test` instruction is executed, but it is possible that some of the lower bits in the register are uninitialized. It seems that valgrind will emit the warning if any part of the register is uninitialized when executing the `test` instruction (presumably because the values of the flags `ZF` and `PF` depend on all bits in the register including the uninitialized bits).
~~We can avoid this warning by making sure that there are …
> Eliminate a valgrind warning

- erts/emulator/beam/erl_bif_info.c
- erts/emulator/test/process_SUITE.erl
Fix #6922.
The 2-tuple {max_heap_size, Map} was accidentally lost.
Introduced by 8d5f5ef0b5bd87a79390fe767cbfed9827ba66fe in OTP 26.0-rc1.
> erts: Fix process_info(_, garbage_collection) for max_heap_size

- lib/stdlib/src/lists.erl
This PR provides performance improvements for `nth/2`, `nthtail/2` ~and `append/1,2`~ in the `lists` module.
* `nth/2` and `nthtail/2`: There was a guard in one of the clauses that would be checked in each step of the recursion. Another drawback was that both functions would accept floats as values for the index, and only crash after having gone through the recursion to the point where it dropped below 1.
I moved this check, augmented to also check for the indexes being integers, plus some shortcuts for common edge cases, in front functions and put the actual work in helper functions that run unchecked. This implementation is (AFAICS) fully equivalent to the old implementation, but performs better, with back-off-a-napkin benchmarks showing the runtime being around 75% of that of the old …
> Improve `lists:nth/2` and `nthtail/2`

- lib/dialyzer/doc/src/dialyzer.xml
- lib/dialyzer/src/dialyzer_cl_parse.erl
- lib/dialyzer/src/dialyzer_options.erl
- lib/dialyzer/src/dialyzer_typegraph.erl
- lib/dialyzer/test/options3_SUITE_data/dialyzer_options
- lib/dialyzer/test/options3_SUITE_data/src/bad_specs.erl
This option is useful for debugging when one suspects that some specs are incorrect.
(Technically, this option is not new, but it was broken and undocumented.)
> dialyzer: Add the --no_spec option for ignoring specs

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/beam_ssa_SUITE.erl
Consider this code:
-module(t).
-export([foo/0, bar/4]).
foo() ->
bar(ok, 0 div 0, node(), [-1]).
bar(_, _, _, _) -> ok.
It fails to compile when some optimizations are turned off:
$ erlc +no_copt +no_ssa_opt t.erl
t:1: function foo/0+7:
Instruction: {test_heap,2,2}
Error:       {{x,0},not_live}:
> Fix compilation error with disabled optimizations

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_validator_SUITE.erl
- lib/compiler/test/beam_validator_SUITE_data/singleton_inference.erl
Type inference with singleton types in registers was weaker than inference on their corresponding literals.
Fixes #6962
> beam_validator: Fix inference on singleton types in registers

- lib/stdlib/src/io_lib.erl
- lib/stdlib/src/io_lib_format.erl
- lib/stdlib/test/io_SUITE.erl
The 'maps_order' key has been added to the public type io_lib:format_spec() in OTP26 RC1, as a required key. Besides, the key presence is assumed in the implementation of io_lib:unscan_format/1. This makes it a breaking change, resulting in unexpected behavior for existing code calling it on a map without the key (returns a list of maps).
- fix the typespec to make the key optional
- don't require the key in io_lib:unscan_format/1
- add a guard to detect we're not building a correct charlist
(same as the added test)
```erlang
Erlang/OTP 26 [RELEASE CANDIDATE 1] [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Eshell V14.0 (press Ctrl+G to abort, type help(). for help)
1> io_lib:unscan_format([
1>     #{
1>       adjust => right,
1>       args => [[<<"1">>]],
1> …
```
> Make maps_order optional in io_lib:format_spec()

- erts/doc/src/erlang.xml
- erts/emulator/beam/beam_file.c
- erts/emulator/beam/beam_file.h
- erts/emulator/beam/emu/emu_load.c
- erts/emulator/beam/emu/generators.tab
- erts/emulator/beam/emu/load.h
- erts/emulator/beam/generators.tab
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_module.cpp
- erts/emulator/beam/jit/arm/generators.tab
- erts/emulator/beam/jit/asm_load.c
- erts/emulator/beam/jit/beam_asm.h
- erts/emulator/beam/jit/beam_jit_main.cpp
- erts/emulator/beam/jit/load.h
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_module.cpp
- erts/emulator/beam/jit/x86/generators.tab
- erts/emulator/test/fun_SUITE.erl
- erts/emulator/test/trace_call_time_SUITE.erl
- system/doc/general_info/upcoming_incompatibilities.xml
The optimization that turned `make_fun2`/`3` instructions of funs lacking an environment into literals was lost during the pre-JIT refactoring of the loader, as creation of fun entries was now (rightly) deferred until the very last stages of module loading.
This commit restores that optimization by creating placeholders in the form of external funs, which are then converted to local funs during the last stages of module loading.
> erts: Reintroduce literal fun optimization

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/beam_except_SUITE.erl
If the code in `?EXCEPTION_BLOCK` is modified in any way, the `beam_ssa_codegen:assert_exception_block/1` function will cause an internal compiler error. Ensure that the literal unfolding optimization in `beam_ssa_opt` will not modify the code in `?EXCEPTION_BLOCK`.
> Eliminate assertion failure in beam_ssa_codegen

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/core_fold_SUITE.erl
Fix an unsafe optimization that would remove a map update operation that is supposed fail. For example:
foo() ->
#{}#{key := value},
ok.
Instead of raising an exception, `foo/0` would return `ok`.
Closes #6960
> Fix lost exception from map update

- erts/doc/src/erlang.xml
- erts/emulator/beam/dist.h
- erts/emulator/beam/external.c
- erts/emulator/test/binary_SUITE.erl
- lib/erl_interface/test/ei_decode_SUITE_data/ei_decode_test.c
- lib/kernel/test/disk_log_SUITE.erl
- system/doc/general_info/upcoming_incompatibilities.xml
The default `minor_version` option is changed from 1 to 2 for `term_to_binary` and `term_to_iovec`.
> Make term_to_binary encode atoms as UTF-8 by default

- lib/kernel/src/inet_dns.erl
- lib/kernel/src/inet_dns.hrl
- lib/kernel/test/inet_res_SUITE.erl
- lib/kernel/test/inet_res_SUITE_data/otptest/otptest.zone
The record data Erlang representation is chosen to be similar to the Master File Format described in RFC section 3, i.e latitude and longitude in degrees, and altitude, size and precision in meters; all as floating point values.
Encoding also supports integers with latitude and longitude in thounsands of an arc second, and alitude, size and precision in centimeters, as the RDATA format in RFC section 2.
Encoding of size and precision encodes the smallest encoding value not less than the input value; e.g 100 encodes as 100, 4711 encodes as 5000, and 90001 encodes as 100000.
> Implement DNS LOC record (RFC 1876)

- lib/compiler/src/sys_core_fold.erl
- lib/stdlib/test/maps_SUITE.erl
- system/doc/efficiency_guide/maps.xml
There's little reason not to do this since we're already inlining `maps:get/2`.
> sys_core_fold: Inline maps:get/3

- lib/stdlib/src/erl_parse.yrl
* The `binary_op()` type was missing the `!` operator.
* The `abstract_expr()` was missing the `maybe` construct.
Closes #6956
> erl_parse: Update types

- HOWTO/INSTALL-RASPBERRYPI3.md
- erts/emulator/zlib/compress.c
- erts/emulator/zlib/crc32.c
- erts/emulator/zlib/deflate.c
- erts/emulator/zlib/deflate.h
- erts/emulator/zlib/inflate.c
- erts/emulator/zlib/inftrees.c
- erts/emulator/zlib/inftrees.h
- erts/emulator/zlib/trees.c
- erts/emulator/zlib/uncompr.c
- erts/emulator/zlib/zconf.h
- erts/emulator/zlib/zlib.h
- erts/emulator/zlib/zutil.c
- erts/emulator/zlib/zutil.h
Official changelog:
```
Version 1.2.13 has these key updates from 1.2.12:
Fix a bug when getting a gzip header extra field with inflateGetHeader(). This remedies [CVE-2022-37434](https://nvd.nist.gov/vuln/detail/CVE-2022-37434).
Fix a bug in block type selection when Z_FIXED used. Now the smallest block type is selected, for better compression.
Fix a configure issue that discarded the provided CC definition.
Correct incorrect inputs provided to the CRC functions. This mitigates a bug in Java.
Repair prototypes and exporting of the new CRC functions.
Fix inflateBack to detect invalid input with distances too far.
Due to the first bug fix, any installations of 1.2.12 or earlier should be replaced with 1.2.13.
```
I believe `inflateGetHeader` is not used anywhere in OTP, so this is just a …
> Update zlib to 1.2.13

- system/doc/general_info/upcoming_incompatibilities.xml
In Erlang/OTP 27, we will stop using the PCRE regular expression library, because it is no longer maintained. It is likely that we will instead use RE2 (https://github.com/google/re2).
> Add note about a new regular expression engine in OTP 27

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
Opaque types are the only part of our "type" system that acts as nominal types (edit: outside the defining module) rather than sets-of-possible-values, so unlike `-type()` attributes they are still meaningful when underspecified.
Fixes #7015
> erl_lint: Stop raising warnings for underspecified opaques

- erts/emulator/beam/erl_map.c
- erts/emulator/test/map_SUITE.erl
Save heap space when any of the maps have all the keys.
- ~~If one of the maps have all the keys we reuse its key tuple.~~
- ~~If both maps have all the keys we prefer a literal key tuple.~~
ok, here is the new deal:
maps:merge(A,B)  % map B has priority and will supersede values in map A
- If only map B has all the keys, return the entire map B as-is.
- If only map A has all the keys, reuse its key tuple.
- If both have all the keys return B, but if A has a literal key tuple and B does not, first **mutate map B** to use A's key tuple.
> Optimize maps:merge/2 of small maps

- .github/dockerfiles/Dockerfile.32-bit
- .github/dockerfiles/Dockerfile.64-bit
- .github/dockerfiles/Dockerfile.clang
- .github/dockerfiles/Dockerfile.cross-compile
- .github/workflows/actions-updater.yaml
- .github/workflows/add-to-project.yaml
- .github/workflows/main.yaml
- .github/workflows/pr-comment.yaml
- .github/workflows/sync-github-releases.yaml
- .github/workflows/update-base.yaml
- HOWTO/DEVELOPMENT.md
- Switch to new Docker container namespace
- Update actions dependencies, and keep them updated with a new action updater action
The new container namespace (`ghcr.io`) now supports `GITHUB_TOKEN` (see https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry), allowing us to migrate. When debugging locally, I found the new namespace was more reliable.
To see more about the migration process in general, visit: https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry
> gh: Update GitHub actions setup

- lib/stdlib/test/property_test/uri_string_recompose.erl
The property test module `uri_string_recompose` in `stdlib` defines a function `map/0`. In current `proper` master (and therefore, in the next release), a generator function with the same name and arity has been added (https://github.com/proper-testing/proper/commit/b4a6374540e7f1aff100e92069124b48e5903da2), which will resulting in a clash in the future.
This PR renames the function `uri_string_recompose:map/0` to `property_map/0` (ie, a map made up from a proplist). It cannot be removed/replaced by `proper`'s `map/0` since the behavior is different.
> Rename function `map/0` in `uri_string_recompose` property test

- lib/stdlib/doc/src/orddict.xml
This PR adds usage examples for `orddict` module. In most cases it handles the erroneous case and a successful care.
> orddict: add examples

- lib/stdlib/doc/src/gen_statem.xml
- lib/stdlib/src/gen_statem.erl
The proxy process was used to prevent late replies from reaching the client at timeout or connection loss. This is no longer needed since process aliases take care of this, are used and supported by all Erlang nodes that an OTP 26 Erlang node can communicate with.
> [stdlib] Remove gen_statem call proxy process

- erts/doc/src/erlang.xml
- lib/kernel/doc/src/erpc.xml
- lib/kernel/doc/src/rpc.xml
- lib/kernel/src/global.erl
- lib/kernel/src/global_group.erl
- lib/kernel/src/net_kernel.erl
- lib/stdlib/doc/src/gen_event.xml
- lib/stdlib/doc/src/gen_server.xml
- lib/stdlib/doc/src/gen_statem.xml
- system/doc/reference_manual/processes.xml
The `net_kernel`, `global`, and `global_group` servers now execute with *fully asynchronous distributed signaling* enabled all the time which prevents them from ever getting blocked on send of distributed signals.
Documentation about blocking distributed signals has also been improved.
> Misc improvements using async_dist

- erts/doc/src/match_spec.xml
- erts/emulator/beam/erl_db_util.c
- erts/emulator/test/match_spec_SUITE.erl
This PR adds a few missing guard BIFs like `is_boolean/1` to the list of functions allowed in match specifications, and adds a test to ensure that all new guard BIFs are added to this list.
Fixes #7045
> erts: Support is_boolean/1 in match specs

- lib/compiler/src/beam_disasm.erl
- lib/compiler/src/beam_types.erl
OTP 26 `beam_disasm` crashes when dissassembling some BEAM files created with the OTP 25 compiler. OTP 26 adds a new version 2 format for the `Type` BEAM chunk. `beam_disasm:beam_disasm_types/1` and `beam_types:decode_ext/1` only handle the chunk successfully if it is in the version 2 format (matching on the `?BEAM_TYPES_VERSION` constant). This change deserializes the version 1 format from OTP 25 as well which fixes the crashes.
<details><summary>A reproduction case for an example crash...</summary>
Create a file `ieq.erl`
```erl
-module(ieq).
-export([eq/2]).
eq(A, B) when is_integer(A) andalso is_integer(B) -> A =:= B.
```
Compile `ieq.erl` with the OTP 25 compiler (`path/to/OTP-25/bin/erlc ieq.erl`). Then use `beam_disasm:file/1` from the OTP 26 compiler app:
```
$ …
```
> beam_disasm: Deserialize the version 1 type table format

- erts/configure
- erts/configure.ac
- erts/lib_src/yielding_c_fun/main_target.mk
- lib/erl_interface/configure
- lib/erl_interface/configure.ac
- lib/megaco/configure
- lib/megaco/configure.ac
- lib/odbc/configure
- lib/odbc/configure.ac
- lib/wx/configure
- lib/wx/configure.ac
- make/configure
- make/configure.ac
- An untested broken feature.
- Can easily be enabled by setting CFLAGS and LDFLAGS.
- Address sanitizer for the emulator has better support by the `asan` build target.
Fix #7031
> Remove --enable-sanitizers configure options

- lib/odbc/c_src/odbcserver.c
In PostgreSQL, the TEXT field can easily have more than 8001 characters and it does return the actual number. The size == 0 would happen in case of some DBs won't return valid value where we would keep the same behavior as of now.
> Allow larger column sizes than 8001 in case DB supports it

- erts/config.h.in
- erts/configure
- erts/configure.ac
- erts/doc/src/erlang.xml
- erts/emulator/beam/packet_parser.c
- erts/emulator/beam/sys.h
- erts/emulator/test/decode_packet_SUITE.erl
> Enable decoding URIs with ipv6 address in host.

- lib/asn1/src/asn1ct_check.erl
- lib/asn1/test/asn1_SUITE_data/ValueTest.asn
- lib/asn1/test/error_SUITE.erl
While trying to compile the ASN.1 specification of the latest version of the ETSI 102 232-2 norm ([EmailPDU.txt](https://github.com/erlang/otp/files/11039662/EmailPDU.txt)), I found a bug in the validation of RELATIVE-OID values. The current ASN.1 compiler rejects RELATIVE-OID values containing other RELATIVE-OID values when it's perfectly valid according to the ASN.1 specification (see https://www.itu.int/rec/T-REC-X.680-202102-I/en, section 33.5). This PR fixes this bug and adds more tests to check the behaviour of the compiler regarding RELATIVE-OID validation.
> asn1: fix RELATIVE-OID validation

- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_float.cpp
- erts/emulator/beam/jit/x86/instr_map.cpp
Mixing AVX and SSE instructions results in performance penalities on many CPUs.
Therefore, if AVX is available, the JIT will always emit AVX instructions instead of SSE instructions (for example, `vmovups` instead of `movups`). The JIT will also emit a `vzeroupper` instruction before calling any BIFs or helper routines in the runtime system to avoid a costly state change in case the runtime system uses SSE instructions.
> JIT: Avoid mixing AVX and SSE instructions

- lib/jinterface/doc/src/jinterface_users_guide.xml
In the Erlang-to-Java-Types table, some spaces were missing.
> jinterface docs: add some missing spaces

- lib/stdlib/src/erl_parse.yrl
This is not used in the `not_string` function
> Remove unused argument

- lib/os_mon/c_src/cpu_sup.c
Free memory allocated for ```cpu_times``` in line 688, see #7070
> os_mon: Plug memory leak in cpu_sup:util/0,1 on FreeBSD

- lib/kernel/src/prim_tty.erl
Printing a long string with ANSI escapes is very slow on Erlang/OTP 26 RC2 which is caused by calling re:run/3 nifs a bunch of times. Compiling the regex did not make it fast enough, so SGR (Select Graphic Rendition) escapes are dealt separately with an erlang function which is what most people use escapes for. See #7040
> kernel: make printing strings with ANSI SGR escapes faster

- erts/emulator/beam/erl_async.c
- erts/emulator/beam/erl_drv_thread.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_threads.h
- erts/emulator/beam/erl_trace.c
- erts/emulator/sys/unix/sys.c
- erts/include/internal/ethread.h
- erts/lib_src/pthread/ethread.c
- erts/test/ethread_SUITE.erl
- erts/test/ethread_SUITE_data/ethread_tests.c
The Erlang runtime gives many of its threads descriptive names.  When those threads are part of a logical group, a unique ID is added to the name for disambiguation.  After construction, many thread names in Erlang have a string length greater than 16 characters.  To fit within operating system limits, Erlang then truncates them from right to left.  To minimize confusion after truncation, the unique ID is always placed at the left of a thread name so its information is not likely to be lost.
The convention used by Erlang presents challenges to the use of thread names as keys when reporting on thread activity at the operating system level.  The more common convention, used by other runtimes, is to have the description followed by a unique ID.  When followed, sorting threads by name places …
> Avoid truncating thread names for better runtime observability

- erts/emulator/beam/hash.c
When assertions are disabled, `offset` is set but not used and Clang warns about it. Add a `(void)object` after the assert to silence the warning.
> erts: Fix warning about set but unused variable

- erts/emulator/beam/erl_term.h
d225fdb5a00424 removed the `TUPLE0` define, but failed to remove the defines `MAP0()` and `MAP0_SZ` that depend on it.
Closes #6723
> Remove obsolete defines

- erts/emulator/beam/beam_file.c
- erts/emulator/beam/code_ix.c
- erts/emulator/beam/erl_arith.c
- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_md5.c
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_posix_str.c
- erts/emulator/beam/erl_trace.c
- erts/emulator/beam/erl_vm.h
- erts/emulator/beam/io.c
- erts/emulator/beam/packet_parser.c
- erts/emulator/beam/utils.c
- erts/emulator/drivers/common/inet_drv.c
- erts/emulator/nifs/common/socket_util.c
- erts/emulator/sys/unix/erl_unix_sys.h
- erts/emulator/sys/unix/sys_env.c
- erts/emulator/utils/make_driver_tab
- erts/epmd/src/epmd_srv.c
- erts/etc/common/heart.c
Clang 16 now warns about functions using K&R syntax. Instead of juggling with compiler warning options, it is better to just bite the bullet and modernize the source code.
> erts: Modernize K&R-style functions

- lib/compiler/Makefile
- lib/stdlib/Makefile
- make/app_targets.mk
The makefiles for lib/compiler/ and lib/stdlib/ both include $(ERL_TOP)/make/app_targets.mk and defines their own `test` target. As this leads to warnings about:
Makefile:48: warning: overriding recipe for target 'test'
$ERL_TOP/make/app_targets.mk:26:warning: ignoring old recipe for target 'test'
which are annoying as even a clean build produces warnings, this patch conditionally avoids defining the default target in app_targets.mk when included from lib/compiler/Makefile and lib/stdlib/Makefile.
> Eliminate make warning about ignored old recipe

- lib/asn1/c_src/asn1_erl_nif.c
As enif_alloc is, in applicable cases, declared with the malloc attribute, recent GCCs complain that: "‘free’ called on pointer returned from a mismatched allocation function". Avoid the warning by freeing the new chunk using enif_free().
> asn1: Fix warning about mismatched allocation function

- lib/stdlib/src/erl_lint.erl
I noticed lists were recursed with the `is_pattern_expr_1/1` function, while tuples were recursed with the more expensive (since it's also doing an eval) `is_pattern_expr/1` function. Since there will be an eval at the end anyway, I don't see a reason for this difference. This makes it so that all internal recursion is using the cheaper function.
> [erl_lint] Recurse with cheaper function in pattern checks

- erts/emulator/internal_doc/BeamAsm.md
Scheduler names changed in OTP26, so we need a different `sed` expresion to merge data from all schedulers. The example is now compatible with versions prior to OTP26 and OTP26+
> Update `perf` workflow for OTP26

- lib/erl_interface/doc/src/ei_users_guide.xml
The ei_* functions accept a `ei_cnode *` argument, the examples were sometimes passing it as a value instead.
> ei_users_guide: fix examples, correctly pass ec as pointer

- lib/crypto/c_src/dh.c
- fix for "Can't do fromdata" observed on Windows builds
- and ssh tests
> crypto: dh.c change len type to ErlNifUInt64

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/beam_ssa_SUITE.erl
> Fix failure to load module with disabled optimizations

- lib/compiler/src/Makefile
4006e3719403d1 broke `make clean && make`.
Closes #7134
> Fix broken `make clean && make`

- lib/kernel/src/inet.erl
- lib/kernel/src/inet_db.erl
- lib/kernel/src/inet_parse.erl
- lib/kernel/src/inet_res.erl
- lib/kernel/test/gen_sctp_SUITE.erl
- lib/kernel/test/gen_tcp_api_SUITE.erl
- lib/kernel/test/gen_udp_SUITE.erl
- lib/kernel/test/inet_SUITE.erl
This PR changes the internal function `inet_parse:visible_string/1` to allow an empty string.
Then it changes an empty target host name to be passed through to the resolver backend, and changes the `inet_res` backend to handle the empty host name in a reasonable way.
It seems the `inet_res` backend was the only one that was not prepared for an empty host name.
The changes in this PR solves #6353 so that `gen_tcp:connect("", Port, Opts)` instead of crashing will return, as indicated by the function's type spec.  Most probably `{error, nxdomain}`, but it depends on the current resolver domain configuration.
> Handle empty target host name

- lib/os_mon/c_src/cpu_sup.c
- lib/os_mon/doc/src/cpu_sup.xml
- lib/os_mon/src/cpu_sup.erl
- lib/os_mon/test/cpu_sup_SUITE.erl
Adds an implementation of cpu_sup:util/0,1 for OpenBSD, based on the already available FreeBSD implementation.
>  os_mon: Implement cpu_sup:util/0,1 for OpenBSD

- lib/tools/src/lcnt.erl
See #7140 
After commit e6074fada29f7ec8a8ffd28e6a3aab75f74199f5, term_to_binary always uses V4_PORT_EXT for port encoding. That led to lcnt crashes in clean_id_creation/1 function.
This PR makes lcnt aware of V4_PORT_EXT syntax.
> LCNT: fix port parser for V4_PORT_EXT

- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_bounds_SUITE.erl
Fixes https://github.com/erlang/otp/issues/7145
> beam_bounds: Make 'bnot' converge faster 

- lib/compiler/src/beam_ssa_private_append.erl
- lib/compiler/test/bs_construct_SUITE.erl
The private append pass didn't expect to append anything to literals other than `<<>>`. Rare interactions with the type or bool passes could sneak in things like atoms in unexpected places, crashing the pass.
@frej
> beam_ssa_private_append: Fix crash on oddly structured code

- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_ssa_SUITE.erl
- lib/compiler/test/beam_type_SUITE.erl
Issue #7147 uncovered two bugs in the compiler.
The first one is in the swapping of operands for commutative operands, which the compiler does to simplify for the JIT. When the operands were swapped, types for the operands in the annotation were not updated.
The second one is in `beam_validator`, which assumed that if the binary construction `<<F/float>>` succeeded, then `F` must be a float. That is not correct, because `F` could also be an integer.
Closes #7147
> Fix two type-related bugs

- lib/dialyzer/doc/src/dialyzer.xml
- lib/dialyzer/src/dialyzer_analysis_callgraph.erl
- lib/dialyzer/src/dialyzer_cl_parse.erl
- lib/dialyzer/src/dialyzer_options.erl
- lib/dialyzer/test/incremental_SUITE.erl
- lib/dialyzer/test/incremental_SUITE_data/extra_modules/ebin/.gitignore
- lib/dialyzer/test/incremental_SUITE_data/extra_modules/src/extra_module.erl
- lib/dialyzer/test/incremental_SUITE_data/extra_modules/src/extra_modules.app.src
The Dialyzer config file previously allowed setting fallback modules to analyse and report warnings for in the absence of explicitly given modules in the arguments.
This change extends the config file to include warnings to toggle and modifications to the beginning and end of the path, allowing users to factor these out of their command line arguments.
This change also fixes apps being in default_warning_apps without being in default_apps causing an inconsistency. Now all warning apps are implicitly added to the apps to analyze.
An example Dialyzer config that makes use of the new options:
```erlang
{incremental,
{default_apps,[stdlib,kernel,erts]},
{default_warning_apps,[stdlib]}
}.
{warnings, [no_improper_lists]}.
{add_pathsa,["/users/samwise/potatoes/ebin"]}. …
```
> dialyzer: Expand Dialyzer config file options

- erts/test/otp_SUITE.erl
- lib/diameter/src/diameter.appup.src
`diameter` should not call or rely on the deprecated function `dbg:stop_clear/0`.
The main reason is that `dbg:stop_clear/0` is simply an alias to `dbg:stop/0`. Thus, `dbg:stop_clear/0` was marked as deprecated in a previous pull request GH-6903 (commit
`861be72c5a1261ee1694ee468540256f6db11e87`), and these are the remains that I forgot to update.
> diameter:  remove optional call to deprecated fn and update appup

- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
- erts/emulator/beam/jit/x86/ops.tab
- lib/compiler/test/bif_SUITE.erl
While we're at it, remove related loader transformations that only kicks in for unoptimized code.
Fixes #7024
> jit: Fix hd/1 and tl/1 BIF specialization

- erts/emulator/beam/erl_process_lock.h
Building the runtime system failed when native atomics support was missing.
Closes #7114
> [erts] Fix build without native atomics

- erts/emulator/beam/dist.c
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_process.c
Clang 16 warns when `&` and `|` are used on boolean operands.
> erts: Fix warning about bitwise operations on booleans

- lib/stdlib/doc/src/gb_sets.xml
- lib/stdlib/doc/src/ordsets.xml
- lib/stdlib/doc/src/sets.xml
The paragraph is misleading, if not outright wrong.
The listed functions are fully compatible with those in the `ordsets` module, that much is true, at least AFAICS.
They are also present and provide the same _functionality_ as those in the `sets` module, but the results may be different since `sets` considers two elements as different iff they do not match (`=:=`), while `gb_sets` and `ordsets` consider two elements as different iff they do not compare equal (`==`).
Examples:
```erlang
1> gb_sets:to_list(gb_sets:from_list([1, 1.0])).
[1]
2> sets:to_list(sets:from_list([1, 1.0])).
[1.0, 1]
3> gb_sets:is_element(1.0, gb_sets:from_list([1])).
true
4> sets:is_element(1.0, sets:from_list([1])).
false
...
```
So, one can _not_ simply swap out the module name `sets` for `gb_sets`/`ordsets` or …
> Remove incorrect compatibility section from `gb_sets` docs

- lib/edoc/test/edoc_SUITE.erl
- lib/edoc/test/edoc_SUITE_data/module_with_feature.erl
- lib/syntax_tools/src/epp_dodger.erl
* Handle the `feature` attribute in `epp_dodger` (by killing the form)
* Add a testcase (failing before the change, passing after)
Testplan:
```
export ERL_TOP=`pwd`
./otp_build setup -a
make syntax_tools
make edoc_test ARGS="-suite edoc_SUITE -case module_with_feature"
```
Fixes #7175 .
> Handle feature attribute in epp_dodger

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
In #6864, it became an error to have unbound variables in a union. Before that, unbound variables in unions were silently ignored.
For compatibility with code that used to compile before Erlang/OTP 26, change the error to a warning. The warning can be disabled with the `nowarn_singleton_typevar` option.
It is expected that unbound variables in unions will again become an error in Erlang/OTP 27.
Closes #7116
> Merely warn for unbound variables in union types

- erts/emulator/beam/dist.c
- erts/emulator/beam/erl_node_tables.c
- erts/emulator/beam/erl_node_tables.h
- erts/emulator/test/distribution_SUITE.erl
Silently reject proposed creation and select another one when a node goes alive if there are external identifiers in the system with the proposed creation and the same node name that are to be used. Such identifiers would not work as expected in various situations, and are not from the instance of the node that are about to go alive.
> Creation fix

- lib/common_test/doc/src/ct_suite.xml
- lib/common_test/doc/src/run_test_chapter.xml
- lib/common_test/doc/src/write_test_chapter.xml
- lib/common_test/src/ct_suite.erl
- fix typo group/0 -> groups/1
- in groups example, wrap result term in a list
- add testcase tuple in type specs for all/0 and groups/0
> ct: various doc fixes

- system/doc/general_info/upcoming_incompatibilities.xml
Add notes about the following incompatibilities:
* In OTP 27, `+0.0 =:= -0.0` will return false.
* Having unbound type variables in a union will become an error.
> Add notes about two upcoming incompatibilities

- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/tls_v1.erl
- lib/ssl/test/ssl_reject_SUITE.erl
- lib/ssl/test/tls_api_SUITE.erl
To make it easier to configure signature algorithms with algorithms that are moved from the default add the API function signature_algs/2 that lists possible values.
Also adjust signature algorithms according to TLS-1.3 RFC. That is TLS-1.3 legacy algorithms are the TLS-1.2 algorithms to be supported in TLS-1.2-TLS-1.3 combination. sha224 is also considered legacy.
> ssl: Add signature_algs/2

- lib/ssl/src/tls_client_connection_1_3.erl
To make it more obvious what the problem is.
> ssl: Improve error information when middlebox assert fails

- otp_build
- scripts/otp_build_check
Perform various basic build checks on the system. This is not a complete set of checks before a change can be introduced into the OTP daily builds. All of these checks need to pass before a change can even be considering for testing in OTP daily builds.
> Introduce otp_build check

- lib/kernel/src/group.erl
- lib/kernel/src/prim_tty.erl
- lib/kernel/src/user_drv.erl
- lib/stdlib/test/io_proto_SUITE.erl
After rewriting the shell, group.erl converts everything to Unicode. However, this is problematic if you want to send raw byte data over stdout which may contain Erlang terms converted to binary that you want to convert back to Erlang term after data transfer. If io:setopts(_, {encoding, latin1}) is set, group.erl will just send the data directly to user_drv.erl which will send the data to prim_tty.erl without converting it to Unicode. Fixes #7132.
> kernel: support sending raw byte data over stdout

- lib/kernel/src/group.erl
- lib/kernel/src/prim_tty.erl
- lib/kernel/src/user_drv.erl
- lib/kernel/test/interactive_shell_SUITE.erl
- lib/stdlib/src/edlin.erl
-Support inputting expressions that span multiple lines
in erl shell.
-Adding new keybindings:
navigate up (ctrl+up)/(alt+up)
navigate down (ctrl+down)/(alt+down)
insert newline in middle of line (alt+enter)
navigate top (alt+<)/(alt+shift+up)
navigate bottom (alt+>)/(alt+shift+down)
clear current expression (alt+c)
cancel search (alt+c)
-Modifies the prompt for new lines to make it clearer
that the prompt has entered multiline mode.
-Modifies the search prompt to support multiline statements.
-Including keybinding for opening editor on mac
(option+o)/(alt+o)
-Redraw the prompt after continuing from jcl menu.
> kernel, stdlib: multiline editing in the shell

- erts/emulator/beam/beam_bp.c
- erts/emulator/beam/beam_debug.c
74eee7564d64091dcf42f9361be5381f9fbec0ab fixed a bug in how we handle code barriers while thread progress is blocked, which manifested when using the debugger to set and clear breakpoints in quick sequence.
It's better not to block thread progress at all though, so this PR makes debug breakpoints yield properly instead.
> erts: Don't block thread progress when setting debug breakpoints

- erts/configure
- erts/configure.ac
- erts/emulator/sys/unix/erl_main.c
- erts/emulator/sys/unix/sys.c
- erts/emulator/sys/unix/sys_signal_stack.c
Erlang code compiled to x86 native code uses `RSP` as its stack pointer. This improves performance in several ways:
- It permits the use of the x86 `CALL` and `RET` instructions, which reduces code volume and improves branch prediction.
- It avoids stealing a callee-save register to act as a stack pointer.
Unix signal handlers are by default delivered onto the current stack, i.e. `RSP`. This is a problem since our native-code stacks are small and may not have room for the Unix signal handler.
There is a way to redirect signal handlers to an "alternate" signal stack by using the `SA_ONSTACK` flag with the `sigaction(2)` system call. Unfortunately this has to be specified explicitly for each signal, and it is impossible to enforce given the presence of libraries.
We used to attempt to …
> jit: Refactor sigaltstack(2) handling

- lib/kernel/doc/src/file.xml
- lib/kernel/src/file.erl
- lib/kernel/test/file_SUITE.erl
Closes #3624. One particular use case is reading many small files.
_As an aside, there seems to be an unintended error in `file:delete(File, [])`. The file server does not handle delete calls with options. This is because there is no `prim_file:delete/2` anyway. Should I open a separate issue or fix it here?_
> kernel/file: Add read_file/2

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/appendable.erl
The beam_ssa_type pass deduces the type of variables from the result of relational operators. In the true-branch following a `A '=:=' B`, the variables `A` and `B` are deduced to be of the type `beam_types:meet(type(A), type(B))` which is not necessarily true for bit strings. Bit strings are special in that nothing about their appendable-status can be deduced from a comparison. The only information gained is the size_unit. The appendable status is unchanged by the comparison.
This patch corrects a type inference bug for bit strings where a comparison would falsely set the appendable flag for non-appendable bit strings in the true-branch. The fix special-cases the type inferring following a `=:=` when one or both arguments are appendable by clearing the appendable status, calculating the …
> compiler: Fix type inference bug for bit strings

- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
The `bif:binary_part/3` is a guard bif which creates a sub-binary (containing a reference to its argument) from its argument, thus aliasing both. Currently this does not produce any errors as the BEAM will only ever append to binaries, but if we ever attempt to do destructive updates of binaries this will give us grief, so we'd better correct it.
> compiler: bif:binary_part/3 should alias its arguments

- lib/ssl/src/ssl.erl
The function ssl_gen_statem:call/2 will return `{error,closed}` when the process is not alive.
https://github.com/erlang/otp/blob/master/lib/ssl/src/ssl_gen_statem.erl#L1318-L1329
Related: https://github.com/ninenines/gun/issues/313
> ssl:negotiated_protocol can return {error,closed}

- lib/ssl/src/ssl.erl
- lib/ssl/test/ssl_api_SUITE.erl
Convert more (and new) option tuples to error strings.
Fixes #7247
> ssl: Improve format_error/1

- system/doc/reference_manual/data_types.xml
The only documentation I managed to find about those values in Erlang is an 11 years-old mailing list message by Sverker:
http://erlang.org/pipermail/erlang-questions/2012-February/064728.html.
This commit just copies that information into the official documentation.
> Document that NaN, +Inf, -Inf are not valid Erlang terms.

- erts/emulator/beam/code_ix.h
- erts/emulator/beam/erl_bif_trace.c
- erts/emulator/beam/erl_process.h
- erts/emulator/beam/erl_ptab.h
- erts/emulator/beam/erl_trace.c
- erts/emulator/beam/erl_trace.h
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_global.cpp
- erts/emulator/beam/jit/arm/beam_asm_module.cpp
- erts/emulator/beam/jit/arm/instr_bif.cpp
- erts/emulator/beam/jit/arm/instr_call.cpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/instr_fun.cpp
- erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
- erts/emulator/beam/jit/arm/instr_msg.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/arm/process_main.cpp
- erts/emulator/beam/jit/beam_jit_common.cpp
- erts/emulator/beam/jit/beam_jit_common.hpp
- erts/emulator/beam/jit/beam_jit_main.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_global.cpp
- erts/emulator/beam/jit/x86/beam_asm_module.cpp
- erts/emulator/beam/jit/x86/instr_bif.cpp
- erts/emulator/beam/jit/x86/instr_call.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_msg.cpp
- erts/emulator/beam/jit/x86/instr_trace.cpp
- erts/emulator/beam/jit/x86/ops.tab
- erts/emulator/beam/jit/x86/process_main.cpp
The process structure is now 32 bytes smaller on 64-bit platforms. Most of it was accomplished by reordering but some changes in data sizes were made, hence the sweeping changes in the JIT.
> erts: Marginally shrink process structure

- erts/doc/src/erts_alloc.xml
- erts/emulator/beam/erl_alloc.c
- erts/emulator/beam/erl_alloc.types
- erts/emulator/beam/erl_alloc_util.c
- erts/emulator/beam/erl_alloc_util.h
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/jit/arm/instr_bif.cpp
- erts/emulator/beam/jit/arm/instr_call.cpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_bif.cpp
- erts/emulator/beam/jit/x86/instr_call.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- lib/runtime_tools/doc/src/instrument.xml
- lib/runtime_tools/src/instrument.erl
- lib/runtime_tools/test/instrument_SUITE.erl
This PR extends the allocation tagging feature with support for tracking allocations on a per-process/port level, as well as another mode (disabling the former) that tracks them on a per-MFA level when the JIT is enabled.
```
$ erl +Muatags true
1> instrument:allocations(#{ flags => [per_process] }).
{ok,{128,0,
#{
%% Registered processes are shown under their registered name
init =>
#{binary => {0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
link => {6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
proc => {0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
reg_proc => {1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
fun_tab => {0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0},
atom_entry => {1084,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
module_entry => {0,112,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0},
fun_entry => {0,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}, …
```
> erts/instrument: Extend allocation tags with per-process/port and code tracking

- erts/emulator/beam/beam_common.c
- erts/emulator/beam/copy.c
- erts/emulator/beam/emu/emu_load.c
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_bif_op.c
- erts/emulator/beam/erl_fun.c
- erts/emulator/beam/erl_fun.h
- erts/emulator/beam/erl_gc.h
- erts/emulator/beam/erl_process_dump.c
- erts/emulator/beam/erl_term.c
- erts/emulator/beam/erl_term.h
- erts/emulator/beam/erl_term_hashing.c
- erts/emulator/beam/external.c
- erts/emulator/beam/generators.tab
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/instr_fun.cpp
- erts/emulator/beam/jit/asm_load.c
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_fun.cpp
- erts/emulator/beam/utils.c
- erts/emulator/test/erts_debug_SUITE.erl
- erts/emulator/test/trace_call_memory_SUITE.erl
This PR shrinks funs by one word through packing the arity, number of free variables, and whether it's external or not into the header word.
As an added bonus, we can now combine function type tests with arity tests, further reducing fun call overhead.
> erts: Shrink and optimize funs (again)

- lib/edoc/test/edoc_SUITE.erl
- lib/syntax_tools/src/epp_dodger.erl
This PR adds a testcase that highlights the issue in #7266 and provides a temporary fix. A proper solution would be to process the feature attributes in the dodger.
> Always consider 'maybe' and 'else' as keywords in epp_dodger

- .github/workflows/main.yaml
Dialyzer failed in CI during testing because we'd run the tests in a Docker image which uses the output of a build of OTP, but that build doesn't include the `scripts/` directory (which contains the script for running Dialyzer) from the main Git repository. This change mirrors that directory into the Docker image used for testing so that it can be run there.
Tested by running the GitHub Actions on my own fork.
> Fix Dialyzer failures in CI

- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/beam_ssa_SUITE.erl
With optimizations disabled, the register allocator in `beam_ssa_pre_codegen` could allocate different variables to the same register if single-valued phi nodes in a try/catch construct were present.
Closes #7248
> Fix register allocation in the presence of singled-valued phi nodes

- lib/compiler/test/record_SUITE.erl
- lib/stdlib/src/erl_expand_records.erl
Calling `is_record/3` with a zero tuple size would crash the compiler. For example:
foo(A) -> is_record(A, a, 0).
Using the same kind of expression in a guard would generate incorrect code that could succeed. For example, given:
bar(A) when is_record(A, a, 0) -> ok.
the call `bar({a})` would succeed.
The compiler would run out of memory or never finish compiling a call to `is_record/3` with a huge tuple size. Example:
foobar(A) when is_record(A, a, 10000000) -> A.
Closes #7298
Closes #7317
> Fix is_record/3 for unreasonable tuple sizes

- lib/stdlib/doc/src/qlc.xml
`qlc:string_to_handle` seems to have worse performance than `qlc:q` with the same input query, presumably because the parse transform is not optimizing `qlc:string_to_handle`.
Benchmarks that showcase this behaviour can be found here: https://elixirforum.com/t/performance-discrepancies-with-using-qlc-queries-written-in-erlang-and-elixir/
> Document performance reduction with QLC string handles

- CONTRIBUTING.md
Via https://github.com/erlang/otp/pull/7293#issuecomment-1568293651, I figured this may be valuable to have in the contributing docs as well.
> Document squashing of smaller changes in CONTRIBUTING

- system/doc/design_principles/release_handling.xml
Additionally, document that `UpFromVsn` and `DownToVsn` can also be a regular expression (explained in detail in the `appup` reference): the current document implies, to me, that previous versions must be a fixed string, whilst the appup file can deal with regular expressions as well.
> Add link to appup manpage in release handling doc

- lib/ssl/src/tls_gen_connection.erl
- lib/ssl/test/ssl_api_SUITE.erl
It hanged since the supervisor re-write, need to catch errors when use spawn on the startup function.
Fixes #7297
> Return error if ssl is not started

- lib/compiler/src/beam_ssa_pp.erl
The assertion in `beam_ssa_pp:format_tuple_set_1/1` is not always true, as the type stored in the `Elems` map doesn't need to be exactly the same type as `Key`, they just have to be compatible.
The assert can be triggered by running `./scripts/diffable --asm --co 'dssaopt' $TMPDIR`.
> compiler: Refine too strict assert in beam_ssa_pp:format_tuple_set_1/1

- lib/compiler/src/beam_clean.erl
- lib/compiler/src/beam_ssa_dead.erl
- lib/compiler/src/compile.erl
- lib/compiler/test/beam_ssa_SUITE.erl
Eliminating a repeated `=:=` test can result in code that `beam_validator` doesn't consider safe. This pull request makes the optimization keep `=:=` if it seems to be significant, that is, if one or both operands will gain type information from it.
That makes it possible to compile code from #6599 such as:
f(X, X) when is_integer(X) ->
ok;
f(Y, Y = #{}) ->
Y#{ok := ok}.
(Six other examples from #6599 can now also be compiled.)
Running `scripts/diffable` shows that this fix prevented the optimization in 14 modules (out of about 1000).
Closes #6599 (the examples that were not fixed by this PR will be transferred to a new issue)
> Avoid optimization that beam_validator might consider unsafe

- HOWTO/DTRACE.md
- lib/common_test/doc/src/run_test_chapter.xml
- lib/inets/doc/src/mod_alias.xml
- lib/megaco/doc/src/megaco_intro.xml
- lib/public_key/doc/src/public_key_app.xml
- scripts/otp_html_check
The new flag for `otp_html_check` can be used for checking external references for validity. A few dead links that have been found were fixed.
> docs: Add --print-external-links to `otp_html_check`, fix some dead links

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/andor_SUITE.erl
The function `beam_ssa_bool:covered/1` ran in exponential time.
The new implementation does not always produce the same list of covered vertices, but the same code is generated for every module compiled by `scripts/diffable`.
Closes #7338
> Fix exponential time algorithm

- lib/compiler/src/beam_ssa_recv.erl
The beam_ssa_recv optimization builds a list of `recv_marker_clear` instructions to insert by using `maps:fold/3` in the function `beam_ssa_recv:plan_clears/2`. The fold iterates over `UsageMap` and concatenates the lists returned by `beam_ssa_recv:plan_clears_1/3`. As the iteration order of `maps:fold/3` is undefined, repeated runs on the same module can produce different results, as the SSA-variables holding the result of inserted `recv_marker_clear` instructions depend on the order they are created.
As a compiler developer interested in the effect of optimizations on the SSA-level (using for example, `erlc +dssaopt`) this produces many non-relevant changes in the SSA output. This patch forces the iteration order to be defined and makes the output for repeated compiler runs stable.
> compiler: Eliminate nondeterminism in beam_ssa_recv optimization

- erts/emulator/test/erts_test_utils.erl
- erts/test/upgrade_SUITE.erl
- lib/common_test/src/test_server_node.erl
- lib/compiler/src/beam_asm.erl
- lib/compiler/src/beam_block.erl
- lib/compiler/src/beam_clean.erl
- lib/compiler/src/beam_core_to_ssa.erl
- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_utils.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/src/beam_z.erl
- lib/compiler/src/compile.erl
- lib/compiler/src/v3_core.erl
- lib/compiler/test/Makefile
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/property_test/compile_prop.erl
- lib/compiler/test/test_lib.erl
- lib/kernel/test/global_SUITE.erl
- lib/kernel/test/kernel_SUITE.erl
- lib/observer/test/crashdump_helper.erl
- lib/sasl/test/sasl_SUITE.erl
- lib/stdlib/test/stdlib_SUITE.erl
The compiler has undocumented options for generating code for older releases, so that we can test that the runtime system can load code compiled for a previous release.
Remove the support for generating code that can be loaded on OTP 22/23. The support in the runtime system for loading code compiled for OTP 22/23 will be dropped in a separate pull request.
> Drop support in the compiler for OTP 22/23

- lib/stdlib/src/supervisor.erl
- lib/stdlib/test/supervisor_SUITE.erl
This fixes a bug where the return type for `supervisor:start_child/2` was not being respected (sort of).
If a supervisor tries to start a child who tries to register the same local name that a running process has already registered, the return value was of the form `{error, {{already_started, pid()}, child_spec()}}` rather than `{error, {already_started, pid()}}`.  
Although `term()` allows that, it can be a bit misleading.
> fix(supervisor): fix return value when process is already registered

- lib/stdlib/src/shell.erl
See also https://github.com/erlang/otp/pull/7063 and https://github.com/erlang/otp/blob/acedc250f06f02d534ba21b8ab1d84b3b830c50b/lib/kernel/src/user_drv.erl#L110-L113 (there `unicode:charlist()` is used instead of `string()` but I don't know what's more correct)
> Fix shell:start_interactive/1 spec

- lib/kernel/doc/src/gen_tcp.xml
The first part of this patch only highlights the word "passive" in the documentation for `gen_tcp:recv/3`, to emphasize that this function only works in passive mode.
The second part adds a note saying that calling `gen_tcp:recv/3` on an active socket returns `{error, einval}`.
The last part of the patch adds a paragraph to the documentation for `gen_tcp:recv/3` mentioning what happens when multiple processes call `recv/3` on the same socket. This was previously not documented.
> Improve documentation for gen_tcp:recv/3

- system/doc/reference_manual/distributed.xml
Fixes a minor typo in the Distributed Erlang documentation.
> Fix typo in Distributed Erlang documentation

- lib/kernel/src/prim_tty.erl
> kernel: Fix starting shell when termcap is not available

- lib/stdlib/doc/src/gb_sets.xml
- lib/stdlib/doc/src/ordsets.xml
- lib/stdlib/doc/src/sets.xml
- lib/stdlib/src/gb_sets.erl
- lib/stdlib/src/ordsets.erl
- lib/stdlib/src/sets.erl
- lib/stdlib/test/sets_SUITE.erl
- lib/stdlib/test/sets_test_lib.erl
This PR provides mapping functionality for sets (`sets`, `ordsets` and `gb_sets`).
Often when I deal with sets, I have the need to map one to another. Currently, this is only possible by folding or by converting to a list, mapping over that, and converting back to a set.
> Add map/filtermap functions to `sets`, `ordsets` and `gb_sets`

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_validator_SUITE.erl
Fixes https://github.com/erlang/otp/issues/6552#issuecomment-1353135450
> beam_validator: Fix logic bug in '=/=' inference

- erts/emulator/beam/beam_bif_load.c
- erts/emulator/test/code_SUITE.erl
- erts/emulator/test/code_SUITE_data/call_purged_fun.erl
- erts/emulator/test/code_SUITE_data/call_purged_fun_altered.erl
- erts/emulator/test/code_SUITE_data/call_purged_fun_tester.erl
Calling a fun defined by a module that had been purged after loading a different version of the same module (and therefore did not inherit the old fun entries) could cause the emulator to crash.
We could retain the optimization by comparing the MD5 of the old and current instances, but it didn't give much so it's better to just get rid of it.
Fixes #7288
> erts: Remove buggy optimization in fun purging

- lib/inets/src/http_server/mod_alias.erl
- lib/inets/test/httpd_SUITE.erl
Fixed functionallity of re_write property (Issue #6074).
Previous code coudn't work because there was "^"++FakeName line,
but FakeName could be MatchPattern so this would fail.
I changed the behaviour to append "^" while storeing the re_write, alias or script_alias proplist.
Also, I included one simple re_write property into test, to make sure everything works correcty.
> fix 6074 (mod_alias failed to handle re_write config)

- erts/doc/src/escript_cmd.xml
- lib/stdlib/src/escript.erl
- lib/stdlib/test/escript_SUITE.erl
The current default when running an escript is to interpret it using the `erl_eval` module. In the ancient times when escript was invented that made sense. Interpretation would be slower and some language constructs would not work, but execution could start immediately without waiting for the compiler to finish.
Nowadays with faster computers it makes less sense.
Therefore, in Erlang/OTP 27, change the default to compile the escript. That will require the escript to be executed by an Erlang system that includes the Erlang compiler.
> Compile escripts by default

- lib/stdlib/doc/src/gb_sets.xml
- lib/stdlib/doc/src/ordsets.xml
- lib/stdlib/doc/src/sets.xml
- lib/stdlib/src/gb_sets.erl
- lib/stdlib/src/ordsets.erl
- lib/stdlib/src/sets.erl
- lib/stdlib/test/sets_SUITE.erl
- lib/stdlib/test/sets_test_lib.erl
This PR adds a function `is_equal/2` to the `sets`, `ordsets` and `gb_sets` modules, to check if two sets contain the same elements with respect to their implementation, `ordsets` and `gb_sets` work by comparing for equality (`==`), `sets` works by matching ( `=:=`).
**Semantics**
If `is_equal/2` returns `true` for two given sets `S1` and `S2`, all operations in the respective modules will return the same value when used on either `S1` or `S2`.
An exception from that rule is `to_list/1`, where the order of elements in the returned list is not guaranteed to be the same to begin with; with `ordsets` and `gb_sets` (but not `sets`), it could also be that the result for `S1` contains a float where `S2` contains an equal-comparing integer and vice versa.
**Performance**
*`sets`*
If both given …
> Add equality check functions to `sets`, `ordsets` and `gb_sets`

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
> Fix miscompilation of guard with `or`

- lib/dialyzer/src/dialyzer_cplt.erl
- lib/dialyzer/src/dialyzer_plt.erl
- lib/dialyzer/src/dialyzer_utils.erl
This simplifies ets:lookup + ets:delete into ets:take calls. Removing one call to ets should be beneficial in terms of performance.
> [dialyzer] Simplify ets usage

- erts/doc/src/absform.xml
The term `Tc_k` was not introduced, and I think `Ec_k` was intended.
> Fix typo for maybe expression abstract form

- lib/mnesia/test/README
Via
https://erlangforums.com/t/compiling-mnesia-with-debugging-settings-enabled/2576, the instructions here were outdated and no longer worked.
> mnesia: Fix test debug compile instructions

- erts/emulator/beam/beam_common.h
- erts/emulator/beam/emu/beam_emu.c
- erts/emulator/beam/emu/bif_instrs.tab
- erts/emulator/beam/emu/bs_instrs.tab
- erts/emulator/beam/emu/instrs.tab
- erts/emulator/beam/emu/msg_instrs.tab
- erts/emulator/beam/emu/trace_instrs.tab
- erts/emulator/utils/beam_makeops
In the BEAM emulator, X register 0 (`x(0)`) used to be specially handled by the macro `r(0)` so that it could be placed in a CPU register.
That made sense for platforms with many registers such as Sparc and PowerPC. For the register-starved x86_64 platform it is not possible to allocate a CPU register for `x(0)`. Therefore, in 1f996cc46a8c93 (part of Erlang/OTP 19), the special handling of `x(0)` was removed. Removing that special case simplified the code in many places.
Get rid of the vestiges of the special handling of `x(0)`. While at it, also re-introduce the `REG_xregs` attribute for the variable holding the pointer to the X registers.
> emulator: Remove vestiges of special handling of x(0)

- lib/inets/doc/src/httpd.xml
Re-reading this, a possible improvement could be trying to load mime types from `/etc/mime.types` as a fallback if it exists, as this seems to be the default location at least on Debian.
https://github.com/erlang/otp/blob/646be911ba326bfffd04042297389ebcb7753fa4/lib/inets/src/http_server/httpd_conf.erl#L347-L371
> Document loading httpd mime_types from file

- .github/dockerfiles/Dockerfile.ubuntu-base
- .github/dockerfiles/init.sh
- make/test_target_script.sh
While following [these instructions](https://github.com/erlang/otp/blob/master/HOWTO/DEVELOPMENT.md#using-docker) on my up-to-date Arch Linux host system, I ran into a couple issues while building the Erlang docker images for testing.
* Linux kernel version issues
My host system is currently using the `5.15.91-4-lts` kernel. The docker build process tries to install the `linux-tools-$(uname -r)` package, which does not exist for Ubuntu 20.04 (obviously). I removed this package from the docker build because it does not seem necessary. All you need to do is install `linux-tools-common` and `linux-tools-generic`, as can be seen in this output from a fresh Ubuntu 20.04 container:
```
root@9eae609bf272:/# apt install linux-tools-common linux-tools-generic
Reading package lists... Done
Building …
```
> Update docker build to work on non-Ubuntu hosts

- lib/compiler/test/error_SUITE.erl
- lib/compiler/test/error_SUITE_data/head_mismatch_same_function_name.erl
- lib/stdlib/src/erl_parse.yrl
Given the following module:
```erl
%% mismatch.erl
-module(mismatch).
-compile([export_all, nowarn_export_all]).
test_it(ok) -> ok;
verify_it(true) -> ok;
verify_it(false) -> {error, was_false}.
verify_it(false, Reason) -> {error, Reason}.
```
On master, running `erlc mismatch.erl`  currently reports:
```erl
mismatch.erl:6:1: head mismatch
%    6| verify_it(true) -> ok;
%     | ^
```
The previous clause that the parser is comparing to may not be obvious:
The current compiler warning points to `verify_it/1`, whose two clauses
are terminated properly. When more code is inbetween these two functions
(think documentation, specs, comments) the time needed to find the
mismatched clause can be a lot higher. I also believe that this will
make the error easier to understand for people new to …
> erl_parse: Provide friendlier "head mismatch" errors

- erts/emulator/beam/erl_alloc.c
- erts/emulator/beam/erl_bits.c
- erts/emulator/beam/erl_bits.h
- erts/emulator/beam/erl_init.c
- erts/emulator/beam/erl_process.c
- erts/emulator/beam/jit/arm/process_main.cpp
- erts/emulator/beam/jit/x86/process_main.cpp
- erts/emulator/valgrind/suppress.patched.3.6.0
In the old non-SMP emulator there was one global temporary buffer. In the SMP emulator, there is one per scheduler thread, which reduces the possibility for reuse and potentially wastes memory.
As well as saving some memory, the rewritten operations are also slightly faster.
> Eliminate the temporary buffer for binary construction

- lib/stdlib/src/filelib.erl
- lib/stdlib/test/filelib_SUITE.erl
Fixes #6460.
The function would return a wrong path if the second argument was a link and the path in the first argument would descend and then ascend again to the top level.
The function would also report a path as unsafe by falsely detecting a link loop if a link would target another link, which in turn would target a file of the same name like `bar` --> `foo/bar` --> (`foo/`)`foo/bar`.
As the link resolving and CWD-breakout and loop detection is pretty tricky, I'm not 100% sure it is correct in every aspect and corner case. Please review carefully.
> Fix `filelib:safe_relative_path/2`

- lib/kernel/src/code.erl
> kernel: code:get_doc/1 return missing, on missing preloaded

- lib/kernel/src/group.erl
- lib/kernel/src/prim_tty.erl
- lib/kernel/src/user_drv.erl
- lib/kernel/test/interactive_shell_SUITE.erl
- lib/ssh/src/ssh_cli.erl
- lib/ssh/test/ssh_basic_SUITE.erl
- lib/ssh/test/ssh_test_lib.erl
- lib/stdlib/src/edlin.erl
Output stdout while editing a prompt in the shell, output appears above the prompt.
Support multiline editing when interacting with the erlang ssh daemon.
Plus a couple of other minor bugs.
Fixes the issues seen in #7312, #7263, #7318
> kernel, stdlib, ssh: fix multiline editing bugs

- lib/common_test/src/test_server.erl
- lib/common_test/src/test_server_gl.erl
- lib/tools/test/cover_SUITE.erl
Wait on the reply by the test server group leader to ensure that by the time we continue running the test case all output is captured.
> common test: Synchronize capture start and stop

- lib/compiler/src/v3_core.erl
- lib/compiler/test/core_SUITE.erl
- lib/compiler/test/core_SUITE_data/nif.erl
Commit 724da95cd04d2bc1d6cb89d1988b58b2096d59cd extended the v3_core-pass to make all functions start with a `nif_start` instruction when the `nifs` attribute isn't present in the module but a call to `erlang:load_nif/2` is. The `nif_start` instruction is used as a flag, allowing later compiler passes to easily identify a NIF.
The initial implementation assumed that a function body could only be a `#c_seq{}` or a `#c_case{}` and never a `#c_letrec{}`. This patch extends the v3_core-pass to handle function bodies consisting of a `#c_letrec{}`. Credits for discovering a test case triggering this omission goes to Matthew Pope.
Closes #7409
> compiler: Fix bug in `nif_start` insertion

- erts/lib_src/common/erl_misc_utils.c
> erts: Allow lack of optional fields when determining cgroup type

- erts/emulator/beam/erl_bits.c
- erts/emulator/test/bs_construct_SUITE.erl
This bug was introduced in 9256aad02f77bc4ca8c2ed5a4b41d5cad834fad1.
> Fix bit syntax creation of a bignum in a short non-aligned segment

- lib/kernel/doc/src/code.xml
In the documentation of the `code` module, the functions are apparently ordered randomly. This PR reorders them alphabetically, as in most other modules.
> `code`: reorder functions in docs

- lib/stdlib/doc/src/orddict.xml
Code example `orddict:store` showed wrong output for c value (99 instead of 100).
> Fixed wrong output for orddict:store code example

- erts/emulator/beam/erl_db_util.c
There are multiple places in erl_db_util.c where a temporary ErlOffHeap is created just to call erts_cleanup_offheap(). This function then extracts the first field, and passes it to erts_cleanup_offheap_list(). Calling that function directly is simpler and removes the need to create the temporary object.
Was tested by doing `make stdlib_test ARGS="-suite ets_SUITE"`
> Minor refactor: use erts_cleanup_offheap_list in erl_db_util.c

- lib/compiler/src/beam_ssa_throw.erl
- lib/compiler/test/trycatch_SUITE.erl
> beam_ssa_throw: Exceptions may escape modules through funs

- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_bounds_SUITE.erl
- lib/compiler/test/bif_SUITE.erl
For this example:
clamped_add(A) when is_integer(A) ->
min(max(A, 0), 10) + 100.
the compiler will now be able to infer the range 1 through 10 for the `A` variable when it is used by the plus operator:
{gc_bif,'+',{f,0},1,[{tr,{x,0},{t_integer,{0,10}}},{integer,100}],{x,0}}.
> Refine types for `min/2` and `max/2`

- lib/crypto/c_src/algorithms.c
- lib/crypto/c_src/algorithms.h
- lib/crypto/c_src/crypto.c
Fixes #7436
Symptom: Different kind of segv crashes seen after crypto is loaded, purged and loaded again.
Problem:
dlclose on musl libc is a no-op.
Mutex 'mtx_init_curve_types' was destroyed by unload (called at module purge) and then not re-created at reload as static variable `library_initialized` in crypto.c was true because musl dlclose is a no-op and dlopen reuses the existing loaded crypto.so library with static variables intact.
> crypto: Fix segv crash after purge and reload of crypto on musl libc

- lib/stdlib/src/gen_statem.erl
Inspired by #5831 (f0874ffb4af5af284fa3f139b2421b4ee93a5659), we want to cache `Mod:handle_event/4` when such is the configured callback mode, to make calling this function faster for state machines.
---
I'm not sure of the names of the newly defined types though, better names are welcomed. The idea is to cache the callback together with the statem params where we store the callback mode.
> stdlib: optimise gen_statem by caching callback function

- lib/stdlib/test/property_test/base64_prop.erl
This PR removes the old manual inclusion of the different libraries and replaces it by including `ct_property_test.hrl`.
> Clean up `base64` property test suite

- erts/emulator/nifs/common/socket_int.h
- erts/emulator/nifs/unix/unix_socket_syncio.c
- erts/emulator/nifs/win32/win_socket_asyncio.c
- lib/kernel/doc/src/socket.xml
This fixes #6152, at least the original OOM problem, by always reallocating the receive buffer binary.  It is thereby up to the VM allocators to copy data or not, and they are somewhat configurable.
Perhaps not the final solution, but a better default behaviour, I hope...
> Socket NIF recv buffer allocation issue

- erts/doc/src/erlang.xml
- erts/doc/src/escript_cmd.xml
- lib/common_test/doc/src/run_test_chapter.xml
- lib/erl_docgen/priv/bin/validate_links.escript
- lib/kernel/doc/src/file.xml
- lib/kernel/doc/src/kernel_app.xml
- lib/kernel/doc/src/logger_chapter.xml
- lib/kernel/doc/src/logger_std_h.xml
- lib/kernel/src/file.erl
- lib/kernel/src/group.erl
- lib/kernel/src/prim_tty.erl
- lib/kernel/src/user_drv.erl
- lib/stdlib/doc/src/io.xml
- lib/stdlib/doc/src/peer.xml
- lib/stdlib/doc/src/sys.xml
- lib/stdlib/doc/src/unicode_usage.xml
- lib/stdlib/src/io.erl
- lib/stdlib/test/io_proto_SUITE.erl
This PR fixes a bug when calling `io:setopts([{encoding,unicode}])` on Windows and also cleans up and documents how to bytewise encoded data should be handled by standard_io.
closes #7459
> Fix deadlock when setting encoding on Windows

- lib/stdlib/doc/src/binary.xml
- lib/stdlib/src/binary.erl
In the `binary` module, the functions `longest_common_prefix/1` and `longest_common_suffix/1` expect the given list of binaries to be non-empty. This is not reflected in the specs of or documentation for those functions.
Also, the functions ` compile_pattern/1`, `match/2,3`, `matches/2,3`, `replace/3,4` and `split/2,3`, if the pattern is given as a list of binaries, expect that list to be non-empty. This is not reflected in the specs of or documentation for those functions.
Also, for those functions, any binary given as pattern must be non-empty. This is mentioned in the documentation, but not reflected in the specs.
> More precise specs for some functions in the `binary` module

- lib/stdlib/src/argparse.erl
- lib/stdlib/test/argparse_SUITE.erl
Currently, the default value is rather ambiguous for choice types, being presented as:
`choice: a, b, c, d, a`
Where it's not entirely clear that the last value, `a`, is the default. This PR attempts to fix that.
> argparse: Make formatting of argument descriptions less ambiguous

- lib/inets/src/http_server/httpd_manager.erl
- lib/inets/src/http_server/httpd_request_handler.erl
- avoid function_clause httpd_request:body_data/2
- happening when httpd is stopped during TLS negotiation
- in such cases Manager process is killed and then continue_init fails
> inets: httpd avoid function_clause during startup

- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/src/beam_ssa_private_append.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
This is a set of patches which fixes a number of errors in the compiler's alias analysis pass which have been there since the code was first merged. [The final commit](https://github.com/erlang/otp/commit/1ed37c62c6ffa6d28dac6b4a471218b18124b359) is unfortunately large, but I have been unable to create a smaller patch, which doesn't disable previously working and correct test cases.
> Fix longstanding errors in the compiler's alias analysis pass

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/test/beam_type_SUITE.erl
> Fix crash when compiling is_list/1 call

- erts/doc/src/erl_cmd.xml
- erts/emulator/beam/erl_process.h
- erts/emulator/test/node_container_SUITE.erl
- system/doc/efficiency_guide/advanced.xml
Increase the default process limit from quite conservative limit that wasn't
changed since ERTS 5.10.1 to value that is more applicable in 2023. It cause
about 9 MiB more memory to be consumed at startup, but with current machines it
shouldn't be much of an issue.
> ft: increase default process limit

- lib/stdlib/test/shell_docs_SUITE_data/unknown_erlang_process_flag_2_func.txt
Tweak wording to be a bit friendlier
> Reword warning around `process_flag/2`

- lib/ssl/src/ssl_gen_statem.erl
If the standard C library call getsockopt(2) returns an error for an option - then no return value is created for that option. There is not check about the socket's state in the call chain; if the inet_drv port is still open, then the getsockopt(2) call is executed.
So it should be possible that inet:getsockopt(Port, [sndbuf]) (or recbuf), for a Port that is not dead yet but the underlying socket is closed, may return {ok,[]}.
Closes 7506
> ssl: Handle that inet:getopts may return {ok, []}

- lib/inets/doc/src/mod_esi.xml
I think this was previously undocumented because of its roots in CGI (https://stackoverflow.com/questions/25800385/how-to-send-response-headers-and-status-from-cgi-scripts), but I figured it would be nice to explicitly mention it in the docs regardless.
A test for this is already done as part of `httpd_SUITE:esi`, line 949:
```erl
ok = http_status("GET /cgi-bin/erl/httpd_example:new_status_and_location ",
Config, [{statuscode, 201},
{header, "location"}]).
```
which calls `src/http_server/httpd_example.erl`, doing:
```erl
new_status_and_location(SessionID, Env, Input) ->
mod_esi:deliver(SessionID, new_status_and_location(Env, Input)).
new_status_and_location(_Env,_Input) ->
"status:201 Created\r\n Location: http://www.yahoo.com\r\n\r\n".
```
> inets: Document sending status with mod_esi

- lib/ssl/src/ssl.erl
- lib/ssl/test/ssl_api_SUITE.erl
> Guard against negative Length in `ssl:recv/3`

- lib/compiler/src/beam_jump.erl
- lib/compiler/test/trycatch_SUITE.erl
> beam_jump: Eliminate unsafe sharing of blocks

- lib/stdlib/doc/src/gen_event.xml
- lib/stdlib/doc/src/gen_server.xml
- lib/stdlib/doc/src/gen_statem.xml
> Clarify `gen_statem:start_link/3,4` semantics

- lib/stdlib/test/property_test/queue_prop.erl
This PR uses the atomlimit-safe generators from `ct_proper_ext` (#7364) in the property tests for the `queue` module.
> Use `ct_proper_ext` generators in `queue` property tests

- lib/compiler/src/beam_ssa_bc_size.erl
- lib/compiler/test/bs_bincomp_SUITE.erl
Consider the following function:
bug() ->
<< <<C:8>> || C <- [], _ <- ok >>.
The first generator is an empty list, so the second generator should never be evaluated, and thus the expected result is an empty binary. That is indeed the result when evaluating the comprehension in the shell:
1> << <<C:8>> || C <- [], _ <- ok >>.
<<>>
(And also when turning off compiler optimizations.)
However, when running compiled code there will be an exception:
2> t:bug().
** exception error: bad generator ok
in function  t:bug/0 (t.erl, line 8)
The reason for the exception is that the compiler as an optimization inserts code to calculate the size of the resulting binary. As part of the size calculation, `length(ok)` is evaluated, which will obviously fail. When the size calculation fails, a …
> Correct evaluation order for binary comprehensions

- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/test/compile_SUITE.erl
Combined with improved kill-set calculation (85454714956f54679ae75ef49d10d7992e31b9e2) and an improved data
structure for describing the alias status of variables (c389665cc991fb8a9d123fe34dc95c12bdf1263f), this patch series provides a substantial reduction of the time required for alias analysis. For the set of modules compiled by `scripts/diffable` the time spent in alias analysis is reduced by approximately 55%. For the [example](https://github.com/erlang/otp/issues/7432) in Issue #7432, provided by José Valim, which has a large number of variables, the reduction is even more dramatic. The time spent in the alias analysis pass is reduced by 97%.
> Speed up alias analysis 

- lib/syntax_tools/src/erl_syntax.erl
Exposed (and documented) at https://www.erlang.org/doc/man/erl_syntax#data-types.
> Export documented and exposed type erl_syntax:annotation_or_location/0

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
As [announced on the forum](https://erlangforums.com/t/in-erlang-otp-27-0-0-will-no-longer-be-exactly-equal-to-0-0/2586), `0.0` will no longer match `-0.0` in OTP 27 and vice versa.
This PR for OTP 26.1 adds a warning in anticipation of that.
> erl_lint: Warn on matching float 0.0

- lib/compiler/src/beam_ssa_private_append.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
The beam_ssa_private_append pass can crash, if it, during initial value tracking, ends up in operations which do not create bit strings. This can happen as the initial value tracking in beam_ssa_private_append doesn't consider types. As the decision to apply the private append transform is using type information, tracking values into not type-compatible execution paths is harmless.
This patch changes the beam_ssa_private_append pass to simply stop tracking a value when it is known that the type is not compatible.
You run Erlfuzz over multiple week-ends without finding any issues, as soon as your branch gets merged, Erlfuzz delivers overnight :)
> compiler: Fix crash in beam_ssa_private_append

- lib/observer/src/observer_trace_wx.erl
> Observer: Fix exit command button to allow window to close correctly; Fix for #7461

- lib/mnesia/src/mnesia_backup.erl
- lib/mnesia/test/mnesia_evil_backup.erl
So that if the backup fails, the old backup still exists.
> mnesia: Delay old backup deletion

- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_bounds_SUITE.erl
> Fix unsafe range calculation for the `bnot` operator

- lib/stdlib/doc/src/proc_lib.xml
- system/doc/reference_manual/expressions.xml
- system/doc/reference_manual/typespec.xml
The former renders proper HTML, the latter renders actual backticks.
References:
* https://www.erlang.org/doc/reference_manual/typespec.html: search for \`dynamic()\`
* https://www.erlang.org/doc/reference_manual/expressions.html: search for \`=\`
* https://www.erlang.org/doc/man/proc_lib.html: search for \`normal\`
> Use <c>...</c> (in xml docs) instead of `...`

- lib/inets/test/httpc_SUITE.erl
- lib/inets/test/httpd_SUITE.erl
- lib/inets/test/httpd_basic_SUITE.erl
- lib/inets/test/inets_SUITE.erl
- lib/inets/test/inets_socketwrap_SUITE.erl
Improve inets test suite runtime from 560s to 435s on my fast local machine, from 595s to 486s on my slow local machine, and from 10m47s to 8m49s on GitHub actions in my fork.
The following was done:
- Some testcases that supported it were just migrated to `parallel` directly
- Global state in tests is either isolated out of parallel groups or only taken when needed (ETS tables, httpc profiles)
- Removed or reduced naptime in some tests depending on shared resources
- Removed debug tracing from `esi_put`, this seemed to hang the tests when running in GH Actions
I've tried to keep the individual changes cleanly separated, let me know if they should be squashed.
> inets: Speed up test suite by ~ 2 minutes

- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_bounds_SUITE.erl
Provide type information for frequently used BIFs (such as `binary_to_list/1`). Also enhance the value range analysis for some of the arithmetic operations.
> Enhance type analysis

- lib/public_key/src/public_key.erl
- lib/public_key/test/public_key_SUITE.erl
> public_key: Add check for duplicate certificates

- lib/common_test/src/ct_framework.erl
- lib/common_test/test/ct_misc_1_SUITE.erl
- lib/common_test/test/ct_misc_1_SUITE_data/bad_groups_SUITE.erl
Hi,
in test case with non-existent group in `all()` , ct prints `Error detected` and FAILED, but set exit code set `0` like there was no error here. If ct_run call in ci(like gitlab ci, etc)  error can be overlooked. 
```erlang
-module(example_SUITE).
-compile(nowarn_export_all).
-compile(export_all).
all() ->
[
{group, exist},
{group, unexist}
].
groups() ->
[
{exist, [], [test1]}
].
test1(_) ->
ok.
```
example ct start
```
$ ct_run -noshell -dir .  -suite example_SUITE || echo $?
Common Test v1.24 starting (cwd is /home/hizel/tmp/err)
Common Test: Running make in test directories...
Recompile: example_SUITE
CWD set to: "/home/hizel/tmp/err/ct_run.ct@core-hizel.2023-07-10_14.34.38"
TEST INFO: 1 test(s), 0 case(s) in 0 suite(s)
Testing tmp.err.example_SUITE: Starting test, 0 test cases
- …
```
> ct: update auto skip stats when error in suite handled

- erts/emulator/beam/jit/arm/instr_arith.cpp
- erts/emulator/test/small_SUITE.erl
The JIT would generate code that calculated the remainder incorrectly for the following example:
bug(Bin) ->
N = byte_size(Bin),
{N rem 128, N div 128}.
Essentially, the JIT would rewrite the code like this:
bug(Bin) ->
N = byte_size(Bin),
Q = N bsr 7,
{Q band 16#7f, Q}.
That is, the remainder would be calculated as `(N div 128) rem 128`.
Fixes #7566
> Fix incorrect fusion of `div` and `rem`

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/bs_match_SUITE.erl
> Eliminate consistency failure for non-matching binary pattern

- lib/stdlib/doc/src/gb_sets.xml
In `gb_sets`, the functions `add_element/2`, `del_element/2` and `is_element/2` are aliases for `add/2`, `delete_any/2` and `is_member/2` respectively, added for compatibility with `sets` and `ordsets`.
While `add_element/2` and `add/2` were grouped together into the same paragraph, `del_element/2`/`delete_any/2` and `is_element/2`/`is_member/2` were in distinct paragraphs (with duplicate content), giving the impression that there was some kind of difference between them.
> `gb_sets`: group aliased functions in documentation

- lib/stdlib/test/Makefile
- lib/stdlib/test/property_test/sets_prop.erl
- lib/stdlib/test/sets_property_test_SUITE.erl
This PR provides property-based tests for the `sets` module.
It does not test `sets:new/0,1`, since there isn't much that could be property-tested there.
> Property-based tests for `sets`, `ordsets` and `gb_sets`

- lib/asn1/src/asn1ct_check.erl
- lib/asn1/test/asn1_SUITE_data/ConstraintEquivalence.asn1
A constraint such as:
(SIZE (1..4), ...)
is supposed to be equivalent to:
(SIZE (1..4, ...))
but the former variant was ignored by the ASN.1 compiler, causing the size to be incorrectly encoded and decoded by PER backends.
> asn1: Fix handling of SIZE constraints

- lib/stdlib/test/Makefile
- lib/stdlib/test/gb_sets_property_test_SUITE.erl
- lib/stdlib/test/property_test/gb_sets_prop.erl
Most of the functions in `gb_sets` are already tested in the property test suite provided in #7256, which tests the functions common to all three existing set implementations.
The functions which are unique to `gb_sets` are tested in the suite in this PR.
> Property-based tests for the `gb_sets` module

- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_db_util.c
- erts/emulator/beam/erl_db_util.h
- erts/emulator/beam/erl_node_tables.c
- erts/emulator/beam/external.c
- erts/emulator/beam/external.h
- lib/stdlib/test/ets_SUITE.erl
Fix #7444
Fixed based on 24.3.4 and then merged forward to 25.3.2 and maint for 26.1
ToDo: Maybe do the same for external pid/port/refs?
> Fix reference counting of magic refs in ETS compressed

- lib/kernel/test/interactive_shell_SUITE.erl
- lib/stdlib/src/edlin.erl
This way it is syntactically correct, as opposed to '..'.
Fixes https://github.com/erlang/otp/issues/7558
I got only one failure in stdlib tests, which was in ssh, and seemed unrelated.
Maybe i missed where it was tested still somehow, or there were no tests.
> Make multiline prompt invert-colored spaces.

- erts/emulator/nifs/common/prim_tty_nif.c
termcap.h contains the prototypes of the functions we need and is available in both curses and GNU termcap.
However, GNU termcap has tputs defined as returning void intead of int, so we handle that by ignoring the return value. tputs cannot fail with the input we give it.
closes #7381
> erts: Fix prim_tty nif to compile with GNU termcap

- erts/emulator/beam/emu/generators.tab
- erts/emulator/beam/erl_bits.c
- erts/emulator/beam/erl_bits.h
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_match_bin_SUITE.erl
The runtime system could underestimate the amount of heap space needed for matching out short bitstrings with a size not divisble by 8. That could lead to the runtime system terminating with an "Overrun heap and stack" error.
Fixes #7292
> Fix heap allocation for matching out short bitstrings

- lib/ssl/doc/src/ssl.xml
> ssl: Document enhancement

- lib/kernel/src/inet_db.erl
The cache ETS table is a bag table that in itself preserves insert order, and when access times in the table are update, it is possible to do the insertion of RRs with updated access time in the same order, which overall preserves insert order.
To preserve the RR order; rewrite the deduplication code to not store the deduplicated result in a map, but instead use a map for deduplication lookup and store the result in a list.
All this to not get in the way of DNS servers that e.g. implement load balancing by returning RRs in some specific order.
Closes #7577
> Rewrite RR cache access time update to preserve table insert order

- lib/stdlib/doc/src/binary.xml
* Many functions in this module are documented as "Same as `same-function-with-different-arity(..., Default)`", which can be grouped together into a single paragraph which mentions the defaults.
* The order of the  `decode_hex`, `decode_unsigned`, `encode_hex` and `encode_unsigned` was mingled, ie not in the usual alphabetical order; it might be debatable whether or not opposing functions should be ordered such that they are grouped together (`decode_hex`, `encode_hex`, `decode_unsigned`, `encode_unsigned` vs `decode_hex`, `decode_unsigned`, `encode_hex`, `encode_unsigned`), but the current order was off in any case.
* The documentation for `copy` explicitly stated that a `badarg` exception will be raised if `N < 0`. As the specs already state that `N = integer() >= 0`, this sentence is …
> Improve documentation of the `binary` module

- lib/dialyzer/src/dialyzer_utils.erl
- lib/dialyzer/test/small_SUITE_data/src/test_product_app.erl
Analyzing a module that defines the type `product/0` could crash Dialyzer. This bug was introduced in 4d08fc95830b650d.
Fixes #7584
> dialyzer: Handle definition of type product/0

- erts/doc/src/erl_cmd.xml
- erts/doc/src/init.xml
- erts/preloaded/src/init.erl
Currently, when wanting to run programs via `-s` or `-run` that take arguments, one has to use the form `-s M F -extra A1 A2 ...`. This is cumbersome to remember and must be documented appropriately. Furthermore, the documentation for `-s` recommends to use `-run` instead, as `-s` passes arguments as atoms.
This commit introduces a new flag, `-S`, which combines `-s`, `-run`, and `-extra`: arguments will be passed as strings, can be passed without the `-extra` flag. Two pieces in Erlang that would benefit from this as is:
- The C sources for dialyzer, escript and typer all use `-extra` to pass additional arguments.
- https://github.com/erlang/otp/pull/7299, if merged, would allow using `erl -S httpd serve --port 1234` instead of `erl -s httpd serve -extra --port 1234`.
**For now, this is …
> init: Introduce -S flag

- erts/emulator/test/small_SUITE.erl
- lib/compiler/src/beam_bounds.erl
- lib/compiler/test/beam_bounds_SUITE.erl
acf3116e55f238 enhanced the range calculation for `rem`, but at the same time introduced a bug. For example:
2 rem X
If the range for `X` was unknown, the compiler would calculate the range for the remainder as `{2,2}`, while the correct range is `{0,2}`. This commit corrects the range calculation for the remainder to ensure that zero is always included in the range.
> Fix incorrect range calculation for operator `rem`

- erts/emulator/beam/erl_bif_binary.c
- lib/stdlib/test/binary_module_SUITE.erl
Several functions in the `binary` module would accept an invalid pattern (such as an atom) if the subject binary was empty or if the `{scope,{0,0}}` option was given. The following functions were affected:
match/{2,3}
matches/{2,3}
replace/{3,4}
split/{2,3}
> binary module: Always detect invalid patterns

- erts/emulator/beam/beam_file.c
When a BEAM file lacks a "Type" chunk, a default `any` type is set up, but all fields in the type was not initialized, which could lead to the JIT removing type tests when it was not safe to do so.
> Properly handle BEAM files without the "Type" chunk

- erts/emulator/test/Makefile
- erts/emulator/test/bs_match_int_SUITE.erl
- erts/emulator/test/bs_utf_SUITE.erl
- lib/compiler/src/compile.erl
Normally, all BEAM files created by OTP 25 and later have a "Type" chunk that contains type information. `beam_lib:strip/1` will not discard the "Type" chunk, but build/release scripts that do their own custom stripping could accidentally delete the chunk.
Make sure to test that loading and executing BEAM files without type information works. Since there was an overrun-heap-and-stack bug (reported in #7292, fixed in #7581) when using the bit syntax, the bit syntax test suites seems to be appropriate to clone to new BEAM files without types.
> Test BEAM files without type information

- lib/kernel/src/inet.erl
- lib/kernel/test/inet_sockopt_SUITE.erl
This should fix the issue in #7569, but I should write some test cases as well...
> Allow missing options in open() calls

- erts/emulator/beam/jit/arm/instr_fun.cpp
- erts/emulator/beam/jit/x86/instr_fun.cpp
In the DEBUG build, the assertion that checks that a fun about to be called is a fun would fail if the type information had been stripped from the BEAM file.
> Don't fail type assertion when BEAM file lacks types

- lib/kernel/src/group.erl
- lib/kernel/test/interactive_shell_SUITE.erl
- lib/stdlib/src/edlin.erl
The default multiline prompt will be "..".
But this can be configurable via environment variable: -stdlib shell_multiline_prompt TERM
where TERM can be:
a string `-stdlib shell_multiline_prompt \"...>\"`.
a module and function tuple `-stdlib shell_multiline_prompt {M,F}`,
which takes the main prompt as only argument, returning a string prompt.
e.g. `{edlin,inverted_space_prompt}`.
Also modifies valid multiline expressions that are submitted so that they no longer have the multiline prompt infront in scrollback.
Related issue: #7558
> stdlib: make the shell multiline prompt configurable

- lib/kernel/src/group.erl
- lib/kernel/src/prim_tty.erl
- lib/kernel/src/user_drv.erl
- lib/kernel/test/interactive_shell_SUITE.erl
- lib/kernel/test/interactive_shell_SUITE_data/invalid_keymap.toml
- lib/kernel/test/interactive_shell_SUITE_data/valid_keymap.toml
- lib/stdlib/doc/src/Makefile
- lib/stdlib/doc/src/edlin.xml
- lib/stdlib/doc/src/ref_man.xml
- lib/stdlib/src/Makefile
- lib/stdlib/src/edlin.erl
- lib/stdlib/src/edlin_key.erl
- lib/stdlib/src/stdlib.app.src
Adds functionality to override existing keybindings in the shell.
Also closes:
#6867 
#7227
> stdlib: custom keybindings for the shell

- lib/kernel/src/code.erl
- lib/kernel/src/code_server.erl
- lib/kernel/test/code_SUITE.erl
With changes in #6736 significant work when code loading was moved away from the code server and shifted into the requesting process. However, there could be a lot of repeated work, especially on system startup, if a lot of similar processes are started, all trying to load the same module at the same time, overwhelming the code server with `get_object_code` requests.
In this change, we add additional synchronisation to `ensure_loaded` that makes sure only one process at a time tries to load the module. In the added test showcasing the worst-case scenario of long load path and many concurrent requests, this changes the runtime (on my local machine) from 8s+ to around 200ms.
Furthermore, the special sync operation can be merged with this and save one round-trip to the code server.
Fixes …
> Reduce repeated work in concurrent code loading situations

- erts/emulator/beam/erl_bif_binary.c
- lib/stdlib/test/binary_module_SUITE.erl
The call `binary:copy(<<1:1>>, 0)` would return an empty binary instead of raising an exception. Similarly, calls to `binary:part/{2,3}` attempting to extract 0 bytes at position 0 of a bitstring would return an empty binary instead of raising an exception.
> binary module: Always reject bitstrings

- erts/emulator/beam/external.c
Fixed minor hashing issue with the `local` option of `term_to_binary()`/`term_to_iovec()`.
> [erts] Fix local_node_hash

- lib/asn1/src/asn1ct_gen.erl
- lib/asn1/src/asn1ct_gen_jer.erl
- lib/asn1/src/asn1rtt_jer.erl
- lib/asn1/test/Makefile
- lib/asn1/test/asn1_SUITE.erl
- lib/asn1/test/asn1_SUITE_data/Containing.asn1
- lib/asn1/test/testContaining.erl
This pull request refactors how type information for ASN.1 is handled for the JER back-end, and is a compatible change for applications that use the documented API. However, for a group of ASN.1 modules that depend on each other (such a `S1AP-PDU-Descriptions`, `S1AP-Contents`, `S1AP-IEs`, and so on), all members of the group must be recompiled if any one of the group members is recompiled.
The internal changes are intended to help tools that need to process type information for ASN.1 specifications, but note that the format of the type information may be updated in a future release. Tool makers must be prepared to update their tools if the format changes.
To explain the changes, I will use this ASN.1 specification as an example:
Containing DEFINITIONS AUTOMATIC TAGS ::=
BEGIN
Config ::= …
> ASN.1 JER: Refactor type-information handling

- .github/dockerfiles/Dockerfile.ubuntu-base
- .github/workflows/main.yaml
- .github/workflows/pr-comment.yaml
The old installed old Erlangs used for compatibility testing would not be updated when the should be. This PR makes sure that they are.
> Fix ubuntu-base cache of old Erlang installs

- lib/stdlib/src/timer.erl
When a timer created by `timer` had expired and it was time to spawn a process to apply a user function, a `system_limit` exception (indicating that the limit for the number of processes in the system had been reached) would be silently ignored.
Since there is not really anything that can be done in this situation, be sure to terminate the system so that the problem is noticed. Note that that other parts of OTP don't attempt to cope with the failure to spawn processes because of a `system_limit` exception.
Fixes #7606
> timer: Don't silently ignore errors when spawning processes

- lib/stdlib/src/binary.erl
Exposed (and documented) at https://www.erlang.org/doc/man/binary.html#type-part.
> Export documented and exposed type binary:part/0
