- lib/mnesia/doc/src/mnesia.xml
> Fix grammar

- system/doc/getting_started/conc_prog.xml
- system/doc/getting_started/records_macros.xml
- system/doc/getting_started/robustness.xml
- system/doc/getting_started/seq_prog.xml
Fixes are in separate commits to improve legibility and ease of review. Most of these should be straightforward, but let me know if any are questionable. Thanks!
> Miscellaneous fixes to documentation

- lib/kernel/src/application_controller.erl
I was going through application_controller.erl looking for why
something was behaving a certain way, saw a comment about removing
this duplicated code one day, and decided to move that a step forward.
> Add helper function to reduce code duplication

- erts/emulator/beam/erl_db_util.c
- erts/emulator/test/match_spec_SUITE.erl
- lib/stdlib/test/ets_SUITE.erl
The only remaining thing is tests for the second commit, of which I have no idea where I should put them.
@psyeugenic
> Fix bugs related to maps in match specs

- lib/kernel/src/inet_tcp_dist.erl
I think those are debugging leftovers.
> Remove erlang:display/1 calls

- lib/stdlib/src/erl_lint.erl
When compiling parser files, because they rely heavily
on inline annotations, retrieving the nowarn_bif_clash
information from the compiler options is expensive.
This patch stores nowarn_bif_clash in the lint record.
By using erlc +'{eprof,lint_module}' when compiling the
erlang parser, we noticed the time spent on
nowarn_function/2 reduced from 30% to 0.01%.
> Cache nowarn_bif_clash functions in erl_lint

- lib/stdlib/src/erl_lint.erl
A lot of time spent on linting is due to eval_file_attribute/2
function that recursively traverses all the AST, annotating
the file name on the AST nodes. This traversal happens so
it is easier to add errors and warnings later on by simply
introspecting the node.
This patch changes eval_file_attribute/2 to only annotate
forms (i.e. attributes and functions) and rely on the #lint
record to keep the proper file information (which it already
did before this patch).
To summarize, both pre scan and pos scan will use the annotate
file attribute in forms, however form/2 already maintains the
proper file in #lint, which we pass around when retrieving the
location information.
After this patch, linting of a regular erlang module with 500LOC
became twice faster when measured with eprof.
> Only annotate forms when linting in the compiler

- lib/debugger/src/dbg_wx_trace.erl
- lib/debugger/src/int.erl
Fix comment on new_process message in int:subscribe/0
> Fix argument to gui_enable_updown in dbg_wx_trace:init/6

- lib/common_test/src/ct_slave.erl
Patch-1: bugfix use application:ensure_all_started to also start asn1 and public_key when starting ssh.
Patch-2: support for ct_slave to pass ssh_port and ssh-options to ssh:connect.
> common_test bugfix&feature

- lib/ssl/test/ssl_to_openssl_SUITE.erl
> ssl: Fix small error in an ALPN test

- lib/stdlib/src/supervisor.erl
- lib/stdlib/test/supervisor_SUITE.erl
This branch has two commits:
320cfc8 Fix supervisor:get_childspec/2 for simple_one_for_one
100d713 Refactor stray code in supervisor.erl left over from previous fix
The first is the important one. Its commit message is:
A bug in supervisor:get_childspec/2 results in
{error, simple_one_for_one} being returned on every call when the
supervisor strategy is simple_one_for_one.
A trivial fix to this problem would have been to just move the handle_call/3
code for the 'get_childspec' msg above:
%%% The requests delete_child and restart_child are invalid for
%%% simple_one_for_one supervisors.
handle_call({_Req, _Data}, _From, State) when ?is_simple(State) ->
{reply, {error, simple_one_for_one}, State};
However, doing so would probably lead to a similar bug the next time someone adds
new …
> Fix supervisor:get_childspec/2 for simple_one_for_one

- system/doc/programming_examples/funs.xmlsrc
> Add the link to Fun expressions manual page

- lib/odbc/doc/src/odbc.xml
- lib/odbc/src/odbc.erl
- lib/odbc/test/odbc_connect_SUITE.erl
fix odbc port timeout for connect
> no hardcoded port accept timeout

- erts/doc/src/absform.xml
Not sure why they're separate, but there's actually two.
> Add missing behavior/behaviours to absform docs

- erts/emulator/beam/dist.c
Repro steps:
- Activate debug on emulator/beam/dist.c
`#if 1
#define ERTS_DIST_MSG_DBG
#endif
#if 1
#define ERTS_RAW_DIST_MSG_DBG
#endif`
> Fix build fail when enabling distribution debug messages

- erts/etc/common/erlexec.c
- lib/tools/src/make.erl
This makes it behave like similar Unix tools.
> Make erl -make return non-zero exit code on failure

- lib/ssl/src/ssl_tls_dist_proxy.erl
- lib/ssl/test/ssl_dist_SUITE.erl
This is the same pull request as #698, but with test cases added.
> Options for TLS distribution

- erts/emulator/hipe/hipe_x86_signal.c
- change #if tests at default Solaris case to explicitly check for __sun__
- add new default case, instantiate it for musl
> hipe_x86_signal: add support for musl libc

- lib/ssl/src/ssl_tls_dist_proxy.erl
As described in the comments in the patch, doing a TLS handshake
requires the crypto module to be loaded.  The crypto module needs the
code server to find its NIF library.  However, there is a time window
between opening the listening ports for distribution and starting the
code server, and if we get an incoming connection in that time window,
the node would believe that it's alive, but it wouldn't actually
accept any more connections.
Also discussed on erlang-bugs: http://erlang.org/pipermail/erlang-bugs/2015-October/005111.html
> Wait for code server before accepting TLS distribution connection

- lib/kernel/doc/src/net_kernel.xml
Make the documentation reflect what the function actually does.
> Fix documentation of net_kernel:allow/1

- lib/erl_interface/src/connect/ei_resolve.c
Fix erl_interface build error on Debian/Hurd and Debian/kFreeBSD.
> ei breakage (Reported-by: Sergei Golovan)

- lib/hipe/icode/hipe_icode_primops.erl
A previous commit introduced a change that exposed dead code in this
module and caused dialyzer warnings.  This dead code was taken out.
While at it, performed some code refactoring in the handling of the
bs_get_integer primop.
> [hipe]: Fix dialyzer warning & some code refactoring

- lib/os_mon/c_src/cpu_sup.c
- lib/os_mon/src/cpu_sup.erl
- lib/os_mon/test/cpu_sup_SUITE.erl
cpu_sup:util/0,1 works on OSX as well.
> os_mon: Implement cpu_sup:util/0,1 on OSX

- lib/stdlib/src/supervisor.erl
Prior to this patch, when the supervisor was unable to
restart a child, it used the timer process to execute
a function later on, allowing other messages in the
supervisor queue to be consumed.
This patch keeps the same idea but bypasses the timer
process by directly sending a message to the supervisor
process itself.
> Avoid potential timer bottleneck on supervisor restart

- otp_build
Please refer to commit message for details.
> Delete dead code in `otp_build` script

- lib/hipe/cerl/cerl_pmatch.erl
The Core Erlang pattern matching compiler was written long ago, at
a time when binaries and bistrings did not really exist in Erlang.
This patch, taken from the code of CutEr where it's used for more
than a year now, extends the transformation for pattern matching
compilation to also include binaries and bistrings.
Some code that was found erroneous and causes errors when compiling
the transformed code to native code was also taken out while at it.
Thanks to @aggelgian for most of the changes in the code.
> hipe: Pattern matching compilation of binaries and bistrings

- system/doc/reference_manual/expressions.xml
It addresses the special case of generator-less LCs.
As a bonus, I fixed a typo :)
> Add clarification on LC semantics (#1)

- system/doc/design_principles/statem.xml
> Fix verb conjugation in statem docs

- erts/emulator/beam/erl_db.c
- erts/emulator/beam/erl_db_hash.c
- erts/emulator/internal_doc/Tracing.md
I was going through the documentation and found these typos. Let me know if I'm wrong, this is little confusing for me.
> Correct typo, atomicity.

- configure.in
- erts/aclocal.m4
- erts/configure.in
Proposed fix for ERL-256 <https://bugs.erlang.org/browse/ERL-256>
> Fix build failure on MacOSX 10.11 using XCode 8

- lib/tools/emacs/Makefile
- lib/tools/emacs/erlang-edoc.el
- lib/tools/emacs/erlang-start.el
- lib/tools/emacs/erlang.el
- EDoc markup font-locking and tag completion
- EDoc comment indentation
> New file erlang-edoc.el to support EDoc in erlang-mode

- lib/compiler/src/beam_bsm.erl
- lib/compiler/test/bs_match_SUITE.erl
The following code causes a compiler failure:
first_after(Data, Offset) ->
case byte_size(Data) > Offset of
false ->
{First, Rest} = {ok, ok},
ok;
true ->
<<_:Offset/binary, Rest/binary>> = Data,
%% 'Rest' saved in y(0) before the call.
{First, _} = match_first(Data, Rest),
%% When beam_bsm sees the code, the following line
%% which uses y(0) has been optimized away.
{First, Rest} = {First, Rest},
First
end.
match_first(_, <<First:1/binary, Rest/binary>>) ->
{First, Rest}.
Here is the error message from beam_validator:
t: function first_after/2+15:
Instruction: {call,2,{f,7}}
Error:       {multiple_match_contexts,[{x,1},0]}:
Basically, what happens is that at time of code generation,
the variable 'Rest' is needed after the call …
> beam_bsm: Eliminate unsafe optimization (ERL-268)

- erts/emulator/beam/bif.tab
- erts/emulator/beam/erl_math.c
- lib/compiler/src/beam_type.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/src/erl_bifs.erl
- lib/compiler/test/float_SUITE.erl
- lib/stdlib/doc/src/math.xml
- lib/stdlib/src/math.erl
A recent erlang-questions [thread](http://erlang.org/pipermail/erlang-questions/2016-October/090690.html) made me realize this is actually quite simple, assuming there's no gotchas I'm not accounting for.
> Add math:fmod/2 BIF

- erts/emulator/beam/dist.c
- lib/kernel/include/dist_util.hrl
- lib/kernel/src/global.erl
- lib/kernel/src/net_kernel.erl
Also update already deprecated calls.
> Allow for easier enabling of distribution debug

- lib/stdlib/doc/src/maps.xml
> fix typo on doc of maps

- lib/tools/emacs/erlang.el
The option makes it possible to customize the indention of if/case/recieve patterns.
Before the change, the indentaion of if/case/recieve patterns is
4 steps and it cannot be changed alone.  Some people prefer other
styles, for example, zero indentation.
case a of
true ->
do_something();
false ->
do_something_else()
end.
This patch just adds an option, which default value is 4 steps.
"(setq erlang-icr-indent 0)" will keep if/case/receive at the same column of
the sub-clauses.
> Add an option erlang-icr-indent

- lib/stdlib/src/error_logger_file_h.erl
- lib/stdlib/src/error_logger_tty_h.erl
- lib/stdlib/test/error_logger_h_SUITE.erl
Found some parts of an old branch that could be usefully salvaged. (The rest collided with Björn's rewrite of error_logger_tty_h.)
> Error logger tty cleanup

- lib/kernel/doc/src/disk_log.xml
- lib/kernel/src/disk_log.erl
- lib/kernel/src/disk_log.hrl
- lib/kernel/src/disk_log_1.erl
- lib/kernel/test/disk_log_SUITE.erl
Found an old branch with cleanups of disk_log and decided to finish it.
- Improves behaviour of internal write cache
- Some small efficiency gains
- Clarifies some points in documentation and types
- Eliminates code duplication and other cleanups
> Disk log tweaks

- lib/stdlib/src/io_lib_format.erl
- lib/stdlib/src/io_lib_pretty.erl
Found an old branch with comments I added separately while I was working on the log message depth problem. Think this could still be useful for the next person trying to understand the io formatting code.
> Add comments for understanding io_lib_pretty

- system/doc/efficiency_guide/myths.xml
- system/doc/efficiency_guide/part.xml
- system/doc/efficiency_guide/retired_myths.xml
I originally started to do those updates for OTP 19, but didn't have time to finish them.
> Update the myths in the Efficiency Guide for OTP 20

- lib/os_mon/src/memsup.erl
> Adding s390x support

- system/doc/design_principles/statem.xml
Base this change on the proper branch this time.
> fix a few statem typos

- lib/stdlib/src/base64.erl
Symptom: Throughput of base64:mime_decode/1 significantly lower than
base64:decode/1.
Problem: tail_contains_more/2 prevents compiler from delaying creation
of sub binaries.
Solution: Restructure mime_decode_binary/2 to use binary matching best
practices from the Efficiency Guide.
See ERL-366
---
Using erlc +bin_opt_info on the base64 module, there is a warning about tail_contains_more/2
> lib/stdlib/src/base64.erl:218: Warning: OPTIMIZED: creation of sub binary delayed
> lib/stdlib/src/base64.erl:220: Warning: NOT OPTIMIZED: called function tail_contains_more/2 does not begin with a suitable binary matching instruction
Based on my testing, I verified that this does pose a problem, at least for large binaries (I used one that is 400000 bytes.
Function               | Avg exec | Throughput …
> stdlib: Fix mime_decode/1 binary matching performance

- lib/stdlib/src/zip.erl
- lib/stdlib/test/zip_SUITE.erl
This PR fixes the following bugs:
[ERL-348](https://bugs.erlang.org/browse/ERL-348)
[ERL-349](https://bugs.erlang.org/browse/ERL-349)
> zip: Fix bugs ERL-348 and ERL-349

- lib/observer/doc/src/observer_ug.xml
- lib/observer/src/observer_alloc_wx.erl
- lib/observer/src/observer_perf_wx.erl
Separate dirty cpu schedulers and normal schedulers by drawing dirty with
dashed lines.
> dgud/observer/max and dirty sched/otp 14137

- lib/common_test/doc/src/write_test_chapter.xml
deleted a <c> tag which was is not allowed inside the <pre> tag
> remove xmllint warning

- lib/compiler/src/beam_type.erl
* kill type information only for affected registers in get_map_elements
* bs_get_utf* will produce integers of unicode range
This optimises code created by Elixir compiler, where:
<<x::utf8,_::binary>> when x in 1..10
will compile the guard to
is_integer(X) andalso X >= 1 andalso X =< 10
This allows us to eliminate the is_integer check.
* bs_get_float will produce a float
* allow carrying type information over other bs instructions killing
only the affected registers
* kill only x registers after call_fun and apply instructions
---
I didn't add tests for this since I wasn't exactly sure what to test here. I'm open to suggestions on how to test the introduced changes.
> Enhance type-driven optimisation in beam_type.erl

- erts/doc/src/absform.xml
> Removes spurious ">"

- lib/inets/src/http_client/httpc_handler.erl
- lib/inets/test/httpc_SUITE.erl
Probably since 6153ba7 (OTP R13B04) the httpc timeout setting does not work for redirects (when autoredirect is true). With this patch a new timer is started for the new (redirected) requests. This means that a simple redirected request could return after 2*timeout milliseconds.
This is the first part to fix https://bugs.erlang.org/browse/ERL-420
> Fix httpc timeout for redirects

- lib/ssl/src/dtls_socket.erl
- lib/ssl/src/dtls_udp_listener.erl
- lib/ssl/src/ssl.erl
- lib/ssl/test/ssl_basic_SUITE.erl
Add test and full implementation of setopts and getopts for DTLS sockets so it will be in time for OTP 20.
> dtls: Handle getopts and setopts for DTLS

- lib/public_key/src/public_key.erl
> Fix typo on line 872

- lib/tools/src/fprof.erl
Print this:
{[{{lists,do_flatten,2},                       20671,    0.000, 1396.391},      
{{lists,flatten,1},                           225, 2627.035,  288.933}],     
{ {lists,do_flatten,2},                       20896, 2627.035, 1685.324},     %
[{{lists,do_flatten,2},                       20671,    0.000, 1396.391},      
{suspend,                                      13,  941.711,    0.000}]}.    
...instead of this:
{[{{lists,do_flatten,2},                       1619,    0.000,  111.092},      
{{lists,do_flatten,2},                       1092,    0.000,   84.075},      
{{lists,do_flatten,2},                       1092,    0.000,   73.996},      
{{lists,do_flatten,2},                        606,    0.000,   49.012},      
{{lists,do_flatten,2},                        606, …
> fprof: Sum callers and callees

- lib/stdlib/src/otp_internal.erl
Pull request for [ERL-456](https://bugs.erlang.org/browse/ERL-459).
> Change crypto:rand_bytes/1 deprecated -> removed

- lib/kernel/doc/src/inet.xml
- lib/kernel/src/inet.erl
Pull request for [ERL-454](https://bugs.erlang.org/browse/ERL-454).
> Improve spec and doc for inet:get_rc/0

- lib/inets/src/http_server/mod_disk_log.erl
- lib/inets/test/httpd_SUITE.erl
This pull request fixes issue ERL-398 and includes a new test case group for logging with test cases covering the repair scenarios for existing mod_disk_log internal format logs.
> HTTP server truncates existing logs

- erts/etc/unix/run_erl.c
Hi,
several functions between sf_read and error reporting can change errno so errno from sf_read needs to be saved.
Also fixed typo in sf_close.
BR,
Marko
> run_erl: Fix error handling in sf_close and during pty master read

- lib/erl_docgen/priv/xsl/db_html.xsl
While reading through the docs I noticed a few typos.
> Change sumary to summary

- lib/tools/emacs/erlang.el
> Tags2 maint

- lib/tools/emacs/erlang.el
The title basically says it all. Just a continuation of my previous work in this direction.
> A few small erlang-mode improvements

- lib/common_test/src/ct_slave.erl
Prior to this patch, stop_timeout was not configurable
and set to 5 seconds. This patch allows this value
to be configurable, maintaining the 5 seconds timeout
as default.
> make stop_timeout in ct_slave:stop configurable

- lib/kernel/src/inet_res.erl
In case of ns server responded with {error, econnrefused} we should close udp connection and start new one for next ns server.
In my case there is `/etc/resolve.conf` with folowing structure
```
nameserver 127.0.0.1
nameserver 8.8.8.8
search ghcg.com
```
and i tried to resolve an srv record, but local dns server (127.0.0.1) crashed on request.
```
$ dig srv _tickdb-qida-ws._tcp.load.ghcg.com
; <<>> DiG 9.10.3-P4-Ubuntu <<>> srv _tickdb-qida-ws._tcp.load.ghcg.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55939
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 7
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;_tickdb-qida-ws._tcp.load.ghcg.com. IN SRV
;; ANSWER SECTION: …
```
> Fixed dns lookup in case of server close connection with econnrefused

- erts/emulator/pcre/README.pcre_update.md
Update PCRE docs to reflect reality
> fix off by one error in docs

- lib/stdlib/doc/src/ets.xml
Grammar corrections in `ets:foldl/3` and `ets:foldr/3` docs
> Fix grammar in 'ets' docs

- lib/compiler/src/v3_codegen.erl
It turns out it was extremely common to have a following sequence:
move 0 D1
byte_size _ D2
bs_add D1 D2 D
Which is equivalent to just:
byte_size _ D
Similarly another sequence:
move S D1
byte_size _ D2
bs_add D1 D2 D
Can be optimised into:
byte_size _ D2
bs_add S D2 D
Both of those optimisations work with byte_size and bit_size instructions.
> Optimise size calculation for binary construction

- erts/doc/src/erlang.xml
> Document the guarantees provided by get_stacktrace

- lib/inets/src/http_client/httpc_response.erl
- lib/inets/test/httpc_SUITE.erl
If a message is received with both a Transfer-Encoding and a
Content-Length header field, it might indicate an attempt to
perform request smuggling or response splitting and must be
handled as an error in default mode (not relaxed mode).
Bug report: https://bugs.erlang.org/browse/ERL-407
> [#ERL-407]: Fix httpc misbehaviour based on RFC7230, section 3.3.3

- lib/stdlib/test/ets_SUITE.erl
This pull request corrects a typo in lib/stdlib/test/ets_SUITE.erl
> Fix typo in test/ets_SUITE.erl

- lib/compiler/src/beam_listing.erl
- lib/compiler/src/compile.erl
- lib/compiler/test/compile_SUITE.erl
- lib/kernel/src/erts_debug.erl
Add possibility for compiler to dump loaded asm of compiled code.
> Add erlc to_dis option that dumps loaded asm

- erts/emulator/hipe/hipe_mkliterals.c
- erts/emulator/hipe/hipe_native_bif.c
- lib/hipe/doc/src/hipe_app.xml
- lib/hipe/icode/hipe_beam_to_icode.erl
- lib/hipe/icode/hipe_icode_primops.erl
- lib/hipe/icode/hipe_icode_range.erl
- lib/hipe/rtl/hipe_rtl_primops.erl
- lib/hipe/test/basic_SUITE_data/basic_receive.erl
With the simplification to this optimisation in BEAM by #1626, it is now almost trivial to implement in HiPE.
> HiPE: Optimise receives matching unique references

- lib/compiler/src/beam_block.erl
The loader has a lot of fused instructions that include move S x0. Placing them
at the end of blocks makes it possible to take advantage of this optimization
more frequently.
> Place move S x0 instructions at the end of blocks

- lib/kernel/src/file_io_server.erl
In general, the new NIF-based file routines are faster than the old
efile driver.
However, on some computers, building the entire OTP system is somewhat
slower. It turns out that it is because `erlc` cheated by turning off
the IO thread pool (using `+A0`) to avoid context switches between
scheduler threads and threads in the IO thread pool. The new file
routines perform IO on dirty IO threads, and there is (by intent) no
way to force the operations to occur on scheduler threads to avoid
the context switches
What we can do to is to use a small (4Kb) read-ahead buffer for files
opened for reading (only) in list mode (which is how the compiler
opens its input files). The buffering reduces the number of context
switches between scheduler threads and dirty IO threads. On my
computer that seems …
> Slightly optimize reading of cooked files in list mode

- lib/compiler/src/v3_codegen.erl
This is an enhancement of the optimization added in 2e5d6201bb044,
where we tried to avoid forcing a stack frame for functions
that don't really need them.
That optimization would not suppress the stack frame for this
function:
```
f(A) ->
Res = case A of
a -> x;
b -> y
end,
{ok,Res}.
```
The reason is that internally the compiler would rewrite
the code to something like this:
```
f(A) ->
Res = case A of
a -> x;
b -> y;
Other -> error({case_clause,Other})
end,
{ok,Res}.
```
The call to `error/1` would force creation of a stack frame,
even though it is not really needed because `error/1` causes
an exception.
Handle calls to exit BIFs specially to allow suppressing the
stack frame.
> v3_codegen: Don't let exit BIFs force a stack frame

- lib/compiler/src/beam_type.erl
#1673 removed the buggy optimizations on `maint` as a conservative fix. This PR reintroduces them on `master` and fixes the bug by keeping track of whether the tuple arity is exactly known or not.
> Reintroduce the tuple arity optimizations removed in PR #1673

- lib/compiler/src/beam_dead.erl
- lib/compiler/src/beam_type.erl
- lib/compiler/test/beam_type_SUITE.erl
- lib/compiler/test/bs_match_SUITE.erl
This pull request contains two commits that do some minor optimizations of binary matching.
> Do some minor optimizations of binary matching

- lib/compiler/src/beam_block.erl
- lib/compiler/src/beam_utils.erl
The more aggressive optimizations of 'allocate_zero' introduced
in cb6fc15c35c7e could produce unsafe code such as the following:
{allocate,0,1}.
{bif,element,{f,0},[{integer,1},{x,0}],{x,0}}.
The code is not safe because if element/2 fails, the runtime
system may scan the stack and find garbage that looks like a
catch tag, and would most probably crash.
Fix the problem by making `beam_utils:is_killed/3` be more conservative
when asked whether a Y register will be killed.
> Fix unsafe use of 'allocate' where 'allocate_zero' should be used

- lib/compiler/src/beam_utils.erl
This pull requests fixes bugs that currently don't cause any problems, but probably will in the future. See the individual commit messages for more details.
> Fix beam_utils bugs that could cause problems in the future

- lib/compiler/src/beam_block.erl
- lib/compiler/src/beam_type.erl
- lib/compiler/test/beam_type_SUITE.erl
This pull requests refactors beam_type and fix some minors bugs. The bugs currently don't cause any problems, but it is expected that they will in the future.
> Refactor and fix minor bugs in beam_type

- lib/common_test/src/test_server_ctrl.erl
- lib/kernel/src/disk_log_1.erl
- lib/xmerl/test/xmerl_SUITE_data/eventp/CMOM.xml
- lib/xmerl/test/xmerl_SUITE_data/eventp/CelloMOM.xml
follow up of https://github.com/erlang/otp/pull/1746
> More typos

- lib/ssh/doc/src/ssh_app.xml
Two drafts have now been RFCs.  Only editorial changes in them from implementation point of view.
> Update SSH(6) documentation

- erts/emulator/sys/common/erl_sys_common_misc.c
Slight performance optimization of the #1770 commit.
> Optimize performance of float_to_list/2

- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/dtls_connection.erl
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/ssl_connection.hrl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/ssl_internal.hrl
- lib/ssl/src/tls_connection.erl
- lib/ssl/test/ssl_basic_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
Allow user to inspect hello extensions and cancel or continue with possible new TLS options.
This aims to implement feature request discussed in ERL-169
> Ingela/ssl/hello pause/erl 169/otp 14372

- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/ssl_connection.hrl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/test/ssl_certificate_verify_SUITE.erl
> ssl: Proper handling of clients that choose to send an empty answer to a certificate request

- lib/stdlib/doc/src/string.xml
I had missed the one in lower section.
> Remove comments about deprecation in OTP-21

- lib/compiler/src/beam_jump.erl
We have found cases where compilation drastically slows down
due to this commit. We are working on a minimal cases and plan
to bring this patch back once we can work our the performance
issues.
This reverts commit f7c9383f4c3d4b6819b5ba4d54c7093df806fe4a.
/cc @michalmuskala
===
We are working on a minimal case, but if we can't make it in time,
we thought it would be important to not include this commit in
OTP 21 since it makes some large modules about to 3x to 4x
slower to compile.
Here is some of the prof data we have:
```
beam_jump: Running eprof
****** Process <0.185.0>    -- 100.00 % of profiled time *** 
FUNCTION                                            CALLS        %      TIME  [uS / CALLS]
--------                                            -----  -------      ----  [----------] …
```
> Revert "Run the sharing optimisation in beam_jump until fixpoint"

- erts/doc/src/erlang.xml
- erts/preloaded/src/erlang.erl
- lib/runtime_tools/src/observer_backend.erl
- lib/stdlib/test/beam_lib_SUITE.erl
- lib/tools/test/xref_SUITE.erl
Made use of the bif in the `observer_backend` and a few tests. Also docs were lacking `ets_count` in some places.
> Use erlang:system_info(ets_count) and improve docs

- lib/syntax_tools/src/erl_syntax.erl
- lib/syntax_tools/test/syntax_tools_SUITE.erl
I targeted maint as if I know correctly there is already a code freeze on 21.0.
> Small fixes in syntax_tools

- lib/compiler/src/beam_utils.erl
- lib/compiler/test/beam_utils_SUITE.erl
https://bugs.erlang.org/browse/ERL-660
> Eliminate a crash in the beam_jump pass

- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/test/ssl_basic_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
> Ingela/ssl/psk hash sign selection/erl 641

- lib/ssl/src/ssl_cipher.erl
- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/test/ssl_ECC_SUITE.erl
- lib/ssl/test/ssl_ECC_openssl_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
> Ingela/ssl/no ca sign restriction tls 1.2/erl 381/otp 15173

- lib/wx/c_src/wxe_driver.c
- lib/wx/c_src/wxe_driver.h
- lib/wx/c_src/wxe_main.cpp
- lib/wx/test/wxt
I've spotted a compilation warning on OS X and went to fix it, also done few misc improvements while checking out the code.
> Wx c_src improvements

- lib/kernel/doc/src/logger.xml
- lib/kernel/src/logger.erl
- lib/kernel/src/logger_server.erl
- lib/kernel/test/logger_SUITE.erl
This function allows the user to easily set a log level filter on all modules in an application.
> Add logger:set_application_level/2

- lib/et/doc/src/et_collector.xml
- lib/et/doc/src/et_selector.xml
- lib/et/src/et_collector.erl
- lib/ftp/doc/src/ftp.xml
- lib/inets/doc/src/mod_security.xml
- lib/mnesia/doc/src/mnesia_frag_hash.xml
- lib/reltool/doc/src/reltool.xml
- lib/tftp/doc/src/tftp.xml
(cherry picked from commit 1b36c8ff81e896f9aa172603962f838d980668a0)
> fix double parenthesis and badly formatter <v> tags

- lib/stdlib/src/dets.erl
- lib/stdlib/test/dets_SUITE.erl
See also ERL-55 and OTP-13229.
> stdlib: Let dets:open_file() crash when given raw file name

- lib/stdlib/doc/src/ets.xml
> ets:new/2 doc update

- .travis.yml
- lib/os_mon/src/memsup.erl
Thanks @CShu12 for starting this.
> fix for ppc64le / add travis test for ppc64le

- lib/erl_docgen/doc/src/doc-build.xml
Signed-off-by: Nils Gillmann <ng0@n0.is>
> Correct a spelling mistake in doc-build.xml.

- lib/ssl/src/ssl_pem_cache.erl
Caught with unit test in ssl_pem_cache_SUITE.
When local timezone is PST (Pacific Standard Time), PEM cache was not evicting
expired entries due to file time converstion was done using
calendar:now_to_datetime, while file modification time is actually in local time.
> ssl: fix timezone-related bug in ssl_pem_cache

- system/doc/design_principles/applications.xml
Since we call them 'Directory Structure' and 'Development Environment' in the
title, this fits more into the title.
> Spell 'Guidelines' in the title for applications with a capital G, in system/doc/design_principles/applications.xml.

- lib/compiler/src/beam_block.erl
- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
This pull request enhances some of the compiler optimizations so that they can be applied in more circumstances. See the commit messages for more details.
> Enhance compiler optimizations

- erts/emulator/beam/erl_node_tables.c
Since OTP R20, there is a possibility for MAJOR garbage collection to
run on dirty scheduler. So DistEntry destructor is being called on
dirty scheduler as well. This, in turn, leads to an attempt to schedule
timer on a dirty scheduler too, which is impossible (and will assert
on debug build, but does succeed for release build, creating an
infinite busy loop, since aux work wakes scheduler up, but dirty
scheduler cannot execute aus work).
There is a similar method in erl_hl_timer, see erts_start_timer_callback.
> erts: fix attempt to start timer when executing on dirty scheduler

- lib/ssl/src/tls_connection.erl
- lib/ssl/test/ssl_payload_SUITE.erl
New internal active N changed timing, and
new check is needed.
> ssl: Gurantee active once data delivery

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/match_SUITE.erl
This pull request improves the type optimizations performed by `beam_ssa_type`. For details, see the commit messages and the comments.
> Improve type optimizations

- erts/emulator/beam/erl_process.c
- erts/emulator/beam/erl_process.h
Fix for the same issue as #2027
> Dirty Scheduler Collapse Fix

- lib/tools/src/tools.app.src
useful when building custom releases.
> adds cprof to list of tools

- erts/emulator/beam/erl_bits.c
- erts/emulator/test/bs_construct_SUITE.erl
Thanks to @michalmuskala for the help in writing this.
> Do not allocate new bitstring/binary on empty append

- lib/tools/priv/styles.css
- lib/tools/src/cover.erl
This will make it easier to send links to other people.
Followup to https://github.com/erlang/otp/pull/721 which was closed due to inactivity.
> Add a link on the line number in cover output

- lib/compiler/src/beam_ssa_opt.erl
This pull request introduces a new optimization on SSA code that essentially rewrites this code:
```
foobar(X) ->
R = case X of
one -> 1;
_ -> X
end,
{ok,R}.
```
to this:
```
foobar2(X) ->
case X of
one -> {ok,1};
_ -> {ok,X}
end.
```
This transformation may lead to more code improvements, for example:
* More stack trimming
* Fewer test_heap instructions
* Smaller stack frames
The commit message has a more technical description of the optimization.
> Introduce optimizations of tail building

- lib/stdlib/doc/src/ets.xml
A documentation answer to https://blog.erlang.org/ets-oddity/
> Add ETS doc note about subtle iteration oddities

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
This pull request fixes two problems discovered when compiling Scalaris, as reported in https://bugs.erlang.org/browse/ERL-840.
> Fix problems compiling Scalaris

- erts/doc/src/erl_nif.xml
- erts/emulator/beam/erl_nif.c
- erts/emulator/beam/erl_nif_api_funcs.h
- erts/emulator/test/nif_SUITE.erl
- erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Primarily for debugging purposes.
> Add enif_make_monitor_term

- lib/compiler/src/v3_core.erl
https://bugs.erlang.org/browse/ERL-851
> Make dialyzer faster for left-associative andalso/orelse expressions

- lib/mnesia/src/mnesia_dumper.erl
The original algorithm first grouped ops in a commit by ext engine type via folding over the list with `orddict:append/3`, that resulted in an `O(n^2)` algorithm.
However, grouping the ops is not needed, the ops can be dispatched to `insert_op/6` one-by-one, after looking up the storage semantics of their respective engine. This is a much cheaper algorithm, assuming looking up the storage semantics is cheap (which should be).
> Optimise ext table dumping

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/erl_bifs.erl
- lib/compiler/src/v3_core.erl
This pull request include minor improvements and improved optimizations.
> Miscellaneous compiler improvements

- lib/edoc/src/edoc.erl
See also https://bugs.erlang.org/browse/ERL-841.
> edoc: Print a helpful message if reading source file fails

- lib/compiler/src/v3_kernel.erl
Prior to this patch, v3_kernel would do multiple
passes on the clauses to group them. This commit
unrolls those passes, making v3_kernel up to 10%
faster in those cases.
> Optimize v3_kernel for thousands of clauses

- HOWTO/INSTALL-RASPBERRYPI3.md
Update instructions for macOS Mojave.
> Update HOWTO for Raspberry Pi3 cross compilation

- lib/stdlib/src/array.erl
I found some small things that could be fixed in the array module. cc @dgud
> Array fixup

- erts/doc/src/tty.xml
Or is it a secret?  Works beautifully.
> tty: document ^] keystroke

- lib/common_test/test/ct_netconfc_SUITE_data/netconfc1_SUITE.erl
- lib/dialyzer/test/r9c_SUITE_data/src/inets/mod_responsecontrol.erl
- lib/inets/src/http_server/mod_responsecontrol.erl
- lib/kernel/src/kernel.erl
- lib/stdlib/test/stdlib_bench_SUITE_data/generic_fsm.erl
- lib/wx/examples/simple/hello2.erl
Fix ERL-541 and various other unreported spelling mistakes.
> Fix various spelling mistakes

- lib/compiler/src/beam_asm.erl
`beam_asm` would encode `{literal,[]}`, `{literal,erlang}`, and
`{literal,42}` in a less efficient way than the equivalent values
`nil`, `{atom,erlang}`, and `{integer,42}`. That would increase the
size of BEAM files and could increase the loaded code size. It would
probably not harm performance, because `literal` was only used this
way in code that generates `badmatch` and `case_clause` exceptions.
> Optimize encoding of simple literals

- lib/dialyzer/src/dialyzer.erl
- lib/dialyzer/src/dialyzer_dataflow.erl
- lib/dialyzer/test/small_SUITE_data/results/fun_app_args
- lib/dialyzer/test/small_SUITE_data/src/fun_app_args.erl
The mismatching argument positions are included.
> dialyzer: Improve the warning tagged 'fun_app_args'

- lib/tools/doc/src/make.xml
> make.xml: Add reference to compile(3)

- lib/stdlib/src/gen_statem.erl
This is a rewrite of timers in `gen_statem` to use synchronous timer cancel, relative to the maint-21 branch, back-ported from the master branch...
Provided for testing by Open Source users.
> Use synchronous timer cancel in gen_statem

- lib/ssl/src/dtls_connection.erl
- lib/ssl/src/ssl_connection.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_connection.erl
- lib/ssl/test/ssl_payload_SUITE.erl
Solve ERL-934 correctly avoiding issue reported in ERL-938
> Ingela/ssl/flow ctrl/erl 934/erl 938

- lib/ssl/doc/src/standards_compliance.xml
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/ssl_logger.erl
- lib/ssl/src/tls_connection.erl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_handshake.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/ssl_basic_SUITE.erl
This PR implements a simple TLS 1.3 client.
> Add basic TLS 1.3 client

- lib/compiler/src/beam_ssa_type.erl
The type optimizer pass (`beam_ssa_type`) could make unsafe
negative inferences. That is, incorrectly infer that a variable
could *not* have a particular type.
This bug was found when adding another optimization. It is not
clear how write a failing test case without that added optimization.
> Fix unsafe negative type inference

- lib/compiler/src/beam_ssa_dead.erl
- lib/compiler/test/beam_ssa_SUITE.erl
The compiler could crash in the `beam_ssa_dead` pass while compiling
complex nested `case` expressions. See the added test case for an
example and explanation.
https://bugs.erlang.org/browse/ERL-956
> Eliminate crash in the beam_ssa_dead compiler pass

- lib/erl_interface/src/decode/decode_fun.c
- lib/erl_interface/src/decode/decode_skip.c
- lib/erl_interface/src/misc/ei_printterm.c
- lib/erl_interface/test/ei_decode_encode_SUITE.erl
- lib/erl_interface/test/ei_decode_encode_SUITE_data/ei_decode_encode_test.c
- lib/erl_interface/test/ei_print_SUITE.erl
- lib/erl_interface/test/ei_print_SUITE_data/ei_print_test.c
Also fix a decoding bug for external funs.
> Support printing of maps and funs in ei_print_term()

- lib/ssl/src/dtls_connection.erl
- lib/ssl/src/dtls_record.erl
Retransmissions mechanism for upd makes it possible for handshakes and possible
alerts to have another record version then the negotiated one in the
states certify and abbreviated without beeing invalid messages.
> ssl: Change check of DTLS record version

- erts/emulator/beam/break.c
https://bugs.erlang.org/browse/ERL-965
> Fix SEGV crash on shell break (p)roc info

- erts/emulator/hipe/hipe_arm.c
https://bugs.erlang.org/browse/ERL-958
Branch based on OTP-19.3.6.
> Fix hipe_flush_icache_range for FreeBSD on ARM

- lib/ssl/doc/src/standards_compliance.xml
- lib/ssl/src/ssl_connection.hrl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/ssl_basic_SUITE.erl
- lib/ssl/test/ssl_certificate_verify_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
This PR implements ALPN in TLS 1.3 and fixes problems when handling certificate related alerts.
> Implement ALPN in TLS 1.3

- lib/kernel/doc/src/logger_chapter.xml
Thanks for all of your amazing work!
> Fix typo in logger_chapter.xml

- lib/compiler/src/beam_ssa.erl
Some huge functions would compile very slowly because of a bottleneck
in `beam_ssa:def_used/2`. One example is the `cuter_binlib` module in
https://github.com/cuter-testing/cuter. On my computer, this commit
reduces the compilatation time for `cuter_binlib` to 45 seconds down
from more than 4 minutes.
Noticed-by: Kostis Sagonas
> Fix slow compilation of huge functions

- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
Previously we would build a large list of used
variables only to compute the intersection. This
commit changes it to compute the unused variables
from given a set which we then subtract from the
original set.
The commit brings the processing time on this
pass from 1.9s to 1.6s in cuter_binlib and it should
use less memory too.
> Collect unused vars instead of used ones

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
https://bugs.erlang.org/browse/ERL-1013
> Eliminate a crash in the type optimizer pass

- lib/compiler/src/beam_ssa_dead.erl
Compiling this example takes less than a second for OTP 21:
-define(B, {?A,?A,?A,?A,?A}).
-define(C, {?B,?B,?B,?B,?B}).
-define(D, {?C,?C,?C,?C,?C}).
-define(E, {?D,?D,?D}).
f() -> ?E = foo:bar().
The compilation time for OTP 22 is about 10 seconds. Most of the
time is spent in `beam_ssa_dead`.
This commit introduces several optimizations to bring the compilation
time down to about a second.
The most important of those optimizations is limiting the effort spent
searching forward for a joining point for the success and failure
labels for a two-way branch. This change is helped by the change of
representation of variable sets from `ordsets` to `cerl_sets`.
https://bugs.erlang.org/browse/ERL-1014
> Avoid extremely long compilation times for huge functions

- lib/compiler/src/cerl_sets.erl
The new implementation use maps iterators and are more
perfomant in banchmarks by roughly 10%. More importantly,
the iterators approach allow us to short-circuit and abort
early.
fold and filter have also been changed to use iterators.
We could simply delegate to the maps' functions, but
inlining the implementation allows us to skip a double
anonymous function dispatch.
> Optimize is_subset and is_disjoint in cerl_sets

- lib/compiler/src/v3_kernel.erl
- lib/compiler/test/bs_match_SUITE.erl
This commit adds two operations when handling literal
integers and literal utf8 segments in the v3_kernel pass.
The first operation is to expand all literal integers with
size more than 8 and literal utf8s into integers with size
of 8 (and potentially an integer with size less than 8 at
the end).
This expansion simplifies the code in other operations
inside v3_kernel and ensure they apply more consistently.
For instance, literal binary matching now applies to both
regular and utf8 strings. Furthermore, we can more
efficiently group clauses.
For instance, the following code:
foo(<<$á/utf8, X/binary>>) -> foo(X);
foo(<<$é/utf8, X/binary>>) -> foo(X);
foo(<<>>) -> ok.
Becomes a bs_get_integer_16 comparing 50089 and 50081,
allowing us to skip the uttf8 conversion at runtime. If there
are …
> Expand and squeeze literal integers/utf8 bin segments

- lib/eldap/doc/src/eldap.xml
> Remove duplicate word in doc.

- lib/compiler/src/beam_except.erl
- lib/compiler/test/beam_except_SUITE.erl
https://bugs.erlang.org/browse/ERL-1026
> Fix an internal consistency check failure caused by beam_except

- erts/doc/src/erlc.xml
Needed a helping verb, added a helping verb.
> Add helping verb

- lib/stdlib/src/filelib.erl
- lib/stdlib/test/filelib_SUITE.erl
`..` was broken and only worked when it was used in the beginning
of the pattern before any wildcard characters. For example:
1> filelib:wildcard("erts/..").
["erts/.."]
Using `..` preceded by wildcard characters would not work:
1> filelib:wildcard("*/..").
[]
`@` is not a wildcard character but is used internally in `filelib` as
an escape character and was not handled as other literal
characters. That could lead to performance degradation as it disabled
an optimization of the matching of the literal prefix of a pattern. It
would also cause the following example to fail:
1> filelib:wildcard("@/..").
[]
This commit corrects the handling `..` and also makes sure that the
use of `@` in a pattern does not degrade performance.
https://bugs.erlang.org/browse/ERL-1029
> Fix filelib:wildcard/1,2 for patterns containing ".." and/or "@"

- lib/stdlib/doc/src/digraph.xml
https://bugs.erlang.org/browse/ERL-1032
> Clarify that digraphs are implemented using ETS tables

- erts/doc/src/erl_nif.xml
Include on_load in the initial "Hello World" example.
> Improve erl_nif documentation about on_load and stubs

- lib/stdlib/src/escript.erl
- lib/stdlib/test/escript_SUITE.erl
- lib/stdlib/test/escript_SUITE_data/bad_io_server
> stdlib: Handle bad I/O server in escripts

- lib/megaco/test/megaco_mess_test.erl
Just found while working on https://github.com/sublimehq/Packages/pull/1878
> Fix syntax error in megaco test file

- lib/kernel/src/group_history.erl
- lib/kernel/test/interactive_shell_SUITE.erl
Because the disk_log is started after the `user` process, there
is a chance for race conditions on shutdown, where disk_log will
terminate before `group`, which will fail to log.
Furthermore, if disk_log terminates BEFORE the shell starts,
then the whole shell will fail to start, which will trigger
another shell recursively, until the system finally shuts down.
This can be reproduced with this command:
$ erl -kernel shell_history true -s init restart
> Do not crash/warn in group_history during disk_log shutdown

- erts/emulator/beam/beam_emu.c
- erts/emulator/beam/erlang_dtrace.d
- erts/emulator/beam/instrs.tab
- lib/runtime_tools/examples/function-calls.d
- lib/runtime_tools/examples/function-calls.systemtap
Some return paths were not going through dtrace
hooks so no function-return probes were being triggered
on dtrace/systemtap.
> Add missing dtrace return invocations

- lib/dialyzer/test/map_SUITE_data/results/maps_remove
- lib/dialyzer/test/map_SUITE_data/src/maps_remove.erl
- lib/hipe/cerl/erl_bif_types.erl
- lib/hipe/cerl/erl_types.erl
- lib/stdlib/src/maps.erl
> dialyzer: Handle maps:remove/2 better

- erts/etc/common/erlexec.c
- lib/kernel/src/application_controller.erl
- lib/kernel/test/application_SUITE.erl
> Handle more config files

- erts/emulator/nifs/unix/unix_prim_file.c
- lib/kernel/doc/src/file.xml
- lib/kernel/test/file_SUITE.erl
> Change efile_allocate in Linux to also change file size

- erts/preloaded/src/socket.erl
> Allow ICMP over DGRAM socket

- erts/emulator/beam/erl_bif_unique.h
- erts/emulator/beam/erl_node_tables.c
- erts/emulator/beam/sys.h
https://bugs.erlang.org/browse/ERL-1044
Branch is based on OTP-21.1 but can be cleanly merged to maint and master.
> Fix write-after-free bug for distribution entry

- .travis.yml
Added changes for s390x in `.travis.yml` file for building erlang/otp for s390x.
> Added s390x support for Travis CI

- HOWTO/SYSTEMTAP.md
> Update SYSTEMTAP.md - Fix typo

- lib/stdlib/src/filelib.erl
The previous implementation would execute file:list_dir/2
twice for every file found in a double star (**) pattern.
This patch changes it so it only calls it once per file,
literally cutting the traversal time in half.
> Optimize filelib:wildcard/2 with double star patterns

- lib/compiler/src/sys_core_fold.erl
- lib/compiler/test/core_fold_SUITE.erl
This pull request fixes [ERL-1170](https://bugs.erlang.org/browse/ERL-1170).
> Fix ERL-1170

- lib/compiler/src/beam_except.erl
- lib/compiler/src/beam_kernel_to_ssa.erl
- lib/compiler/test/beam_except_SUITE.erl
- lib/compiler/test/fun_SUITE.erl
This pull request fixes the compiler crashes reported in [ERL-1166](https://bugs.erlang.org/browse/ERL-1166) and [ERL-1167](https://bugs.erlang.org/browse/ERL-1167).
> Fix two compiler bugs

- system/doc/reference_manual/expressions.xml
- `try_clause` instead of `case_clause`
- `try_clause` is not caught
> Clarify try-of documentation

- lib/tools/emacs/erlang.el
- lib/tools/test/emacs_SUITE.erl
- lib/tools/test/emacs_SUITE_data/type_specs
Fixes [ERL-1140](https://bugs.erlang.org/browse/ERL-1140) and [ERL-1141](https://bugs.erlang.org/browse/ERL-1141).
> Emacs indentation fixes

- lib/stdlib/src/zip.erl
- lib/stdlib/test/zip_SUITE.erl
https://bugs.erlang.org/browse/ERL-1150
> stdlib: Mark zip files as Unix-compatible

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
https://bugs.erlang.org/browse/ERL-1183
> Make sure that 'fail' in a guard makes the guard fail

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/float_SUITE.erl
https://bugs.erlang.org/projects/ERL/issues/ERL-1178
> beam_ssa_opt: Add line numbers to all float conversions

- lib/kernel/src/pg.erl
- lib/kernel/test/pg_SUITE.erl
Handles following sequence:
- nodes A and B share scope S, and were just disconnected
- some process on node B leaves scope S at the same time
- node B processes leave request and (while 'nodedown' from A is in the
mailbox) attempts to send 'leave' broadcast to A
- node A already received and processes 'nodedown' from B, and removed
all processes from scope S
- node B establishes connection to A, and 'leave' message gets sent
- scope S on node A crashes, because it does not expect messages from
B (it is assumed to be down, and not yet participating in the overlay
network)
It also guards against other cases when nodes outside of overlay network
are trying to make changes.
> pg: handle race condition between scope 'DOWN' and processes leaving

- lib/kernel/src/application_master.erl
Fix Mod:stop/1 won't be called if application master exit.
> Fix dead code in application_master

- lib/compiler/src/beam_validator.erl
The split between "safe" and "throwing" instructions is a bit too conservative, and gets rather messy when an instruction that can throw an exception is guaranteed not to under certain circumstances. 
This PR cleans things up by making all exceptions explicit; instructions that branch to `?EXCEPTION_LABEL` throw, and instructions that don't, don't.
> beam_validator: Refactor exception handling

- lib/mnesia/src/mnesia_rpc.erl
Spawn potentially slow operations, i.e. non direct ets lookups
to avoid long msg qeues.
> Modify rpc to spawn non ram lookups

- erts/emulator/beam/bif.c
- erts/emulator/beam/bif.tab
- erts/emulator/beam/instrs.tab
- erts/emulator/beam/ops.tab
- erts/emulator/test/bif_SUITE.erl
http://erlang.org/pipermail/erlang-questions/2020-March/099343.html
@kostis
> erts: Fix external fun application of erlang:apply/3

- erts/configure.in
https://bugs.erlang.org/browse/ERL-1205
> Fix build of OTP with Xcode 11.4

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_validator_SUITE.erl
https://bugs.erlang.org/browse/ERL-1212
> beam_validator: Improve type inference for '=/='

- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_gc.c
- erts/emulator/beam/erl_message.c
- erts/emulator/beam/erl_message.h
- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/erl_process.c
- erts/emulator/test/receive_SUITE.erl
Proposed fix for [`ERL-1199`](https://bugs.erlang.org/browse/ERL-1199).
> Fix handling of receive marker

- lib/ssl/test/ssl_bench_SUITE.erl
It have been broken for a while.
Add more variants.
> ssl: Make benchmarks work again

- erts/doc/src/erl_dist_protocol.xml
- lib/erl_docgen/Makefile
- lib/erl_docgen/doc/src/doc_storage.xml
- lib/erl_docgen/priv/bin/specs_gen.escript
- lib/erl_docgen/priv/dtd/common.dtd
- lib/erl_docgen/src/docgen_xml_to_chunk.erl
- lib/kernel/doc/src/Makefile
- lib/kernel/doc/src/code.xml
- lib/kernel/doc/src/eep48_chapter.xml
- lib/kernel/doc/src/part.xml
- lib/kernel/src/code.erl
- lib/mnesia/doc/src/Mnesia_chap2.xmlsrc
- lib/mnesia/doc/src/Mnesia_chap4.xmlsrc
- lib/stdlib/doc/src/gen_statem.xml
- lib/stdlib/doc/src/shell.xml
- lib/stdlib/doc/src/shell_docs.xml
- lib/stdlib/src/c.erl
- lib/stdlib/src/otp_internal.hrl
- lib/stdlib/src/shell_default.erl
- lib/stdlib/src/shell_docs.erl
- lib/stdlib/test/property_test/shell_docs_prop.erl
- lib/stdlib/test/shell_docs_SUITE.erl
- scripts/build-otp
- scripts/otp_html_check
* Add pagination of shell docs help
* Fix various whitespace trimming bugs
* Add a perl script that checks that links in the html docs are correct
* Add rudimentary property tests for shell docs rendering
> More EEP-48 improvements

- lib/compiler/src/beam_ssa_opt.erl
Sometimes compiler optimizations can make body calls into tail calls.
Here is an example:
bar() ->
{_,_} = foo().
foo() -> {a,b}.
Since `foo/0` returns a tuple of size two, the matching of the
tuple can be eliminated:
bar() ->
foo().
However, the generated code would not be optimal. For this example,
an unnecessary stack frame would be allocated. For other examples,
unnecessary `kill` or `trim` instructions would be emitted.
This commit adds an additional optimization of tail calls created by
other optimizations. For details, see the added comment in
`beam_ssa_opt`.
> Optimize tail calls created during optimization

- lib/observer/src/observer_alloc_wx.erl
Used an undocumented rpc message api which have now changed,
spawn a request instead.
Fixed [ERL-1238](https://bugs.erlang.org/browse/ERL-1238).
> Fix rpc usage (ERL-1238)

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
https://bugs.erlang.org/browse/ERL-1289
> beam_ssa_type: Fix endless loop

- erts/doc/src/absform.xml
> doc: Update The Abstract Format to use ANNO instaed of LINE

- lib/sasl/src/release_handler_1.erl
Proposed fix for https://bugs.erlang.org/browse/ERL-1247
> release_handler more resilient of exiting processes during upgrade

- lib/compiler/src/sys_core_alias.erl
- lib/compiler/test/core_alias_SUITE.erl
https://bugs.erlang.org/browse/ERL-1297
> sys_core_alias: Bail out when expressions get too deep

- lib/kernel/src/disk_log_1.erl
> Fix documentation error

- lib/mnesia/src/mnesia.erl
- lib/mnesia/test/mnesia_trans_access_test.erl
On a set table, if the delete_object doesnt delete (due to no match) at commit
return whatever is (or is not) stored in source table as a result of a read in
the same transaction as the delete_object.
And, if a delete already has been done on Oid in the same transaction do not
record a delete_object operation on the same Oid.
Added delete_object tests on set table and made the existing tests checking more.
Before applying the fix in mnesia.erl one of the added tests (`%% Delete other object than already existing"`) in mnesia_trans_access_test:delete_object_set/1 fail:
`
{mnesia_trans_access_test,delete_object_set},
[{'REASON',"mnesia_trans_access_test.erl",303,
[{aborted,
{{badmatch,[]},
...
`
The other tests are added to cover for the new behaviour.
> Fix for delete_object at read on a set table

- .github/dockerfiles/Dockerfile.32-bit
- .github/dockerfiles/Dockerfile.64-bit
- .github/dockerfiles/Dockerfile.cross-compile
- .github/dockerfiles/Dockerfile.debian-base
- .github/dockerfiles/Dockerfile.documentation
- .github/dockerfiles/Dockerfile.ubuntu-base
- .github/workflows/main.yaml
- .github/workflows/update-base.yaml
- .travis.yml
- prebuild.delete
- scripts/build-otp-tar
- scripts/bundle-otp
- scripts/run-dialyzer
- scripts/run-smoke-tests
Travis seems to have stopped working for some reason that I cannot figure out, so that gave me the opportunity to experiment with github workflows instead.
There are still a couple of things that need to be migrated from travis, but most of the functionality (and more) is there.
> Use github actions instead of travis

- lib/eldap/example/ad_expiring_account.erl
To windows Active Domain,  get user last password attribute is common task, this simple code guide you how to implement via erlang way.
> Initial check in.

- lib/kernel/doc/src/socket.xml
This PR fixes some typos and one grammatical mistake in the socket module.
> Fix some typos and one grammatical mistake in the socket module

- lib/os_mon/c_src/memsup.c
- lib/os_mon/src/memsup.erl
On macOS, `memsup:get_system_memory_data/0` and `memsup:get_memory_data/0` returns
a much too low number for the amount system memory.
The bug is in a function that tried to determine the amount of memory by summing
numbers from the output of the `vm_stat` command.
Instead of trying to fix the summation, we will change approach and use the port
program to retrieve the information. Using the Mach APIs the total amount of memory
can be retrieved directly without any summing.
https://bugs.erlang.org/browse/ERL-1327
> memsup: Return correct amount of total system memory on macOS

- lib/kernel/doc/src/file.xml
https://bugs.erlang.org/browse/ERL-1299
> Clarify file:pwrite/pread documentation about ram mode

- lib/kernel/src/application_controller.erl
- lib/kernel/src/application_master.hrl
I found this while working on another PR.
I was a bit hesitant to send it, as keeping it
doesn't hurt either, but I will let you decide. :)
> Remove unused inc_apps field from #appl_data

- lib/compiler/src/beam_z.erl
Remove all `line` instructions having the same location (filename and
line number) as the previous `line` instruction. It turns out that
such redundant `line` instructions are quite common. Removing them
decreases the size of the BEAM files, but not size of the loaded
code since the loader already removes such redundant `line` instructions.
> Remove redundant line instructions

- lib/compiler/src/v3_core.erl
- lib/compiler/test/trycatch_SUITE.erl
This PR fixes a slowdown in both `dialyzer` and the compiler by inlining small `after` blocks (as in `try/catch`), only emitting wrapper functions when they exceed a certain size. They're still susceptible to it, but it's much harder to trigger by accident now.
https://bugs.erlang.org/browse/ERL-1354
Before:
```
$ time erlc bar.erl
real    0m5,884s
user    0m6,307s
sys     0m0,167s
$ dialyzer --statistics bar.erl
Checking whether the PLT /home/john/.dialyzer_plt is up-to-date... yes
Proceeding with analysis...
compile    (+0.00s):   0.07s (   1 modules)
clean      (+0.00s):   0.00s
remote     (+0.00s):   0.01s
order      (+0.00s):   0.00s
typesig    (+0.00s):   0.24s (      3 SCCs)
order      (+0.00s):   0.01s
refine     (+0.00s):   8.72s (   1 modules)
warning    (+0.00s):   8.83s (   1 …
```
> v3_core: Don't use wrapper functions for small after blocks

- lib/compiler/src/beam_ssa_pre_codegen.erl
The current pass gets very expensive the longer the
code block is. This commit address it. For example,
imagine this code:
-module(bar).
-export([bar/0]).
bar() ->
foo:bar(),
% repeat foo:bar() 999 times
ok.
Prior to this patch, it would take:
find_yregs                 :      0.212 s  73 %
After this patch, it takes:
find_yregs                 :      0.013 s  14 %
Another example is the code in this gist:
https://gist.github.com/josevalim/acac154996e1e61058f367a5b3a161aa
After the patch, find_yregs goes from 3.5s to 0.4s.
This patch is not ready yet for merge, please see comments inline for
places where I would like style-related feedback.
> Optimize find_yregs pass from beam_ssa_pre_codegen

- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_opt.erl
https://bugs.erlang.org/browse/ERL-1359
> beam_ssa_opt: Optimize sinking of get_tuple_element instructions

- lib/compiler/src/beam_ssa_bool.erl
Try to document the conclusions from attempts to simplify or at least
reduce the complexity of the beam_ssa_bool pass in a comment.
> Document result from failed simplification of beam_ssa_bool.erl

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
https://bugs.erlang.org/browse/ERL-1384
> beam_ssa_bool: Fix unsafe literal substitution

- lib/stdlib/src/beam_lib.erl
- lib/stdlib/test/beam_lib_SUITE.erl
https://bugs.erlang.org/browse/ERL-1378
> beam_lib: Fix 'allow_missing_chunks' for named chunks

- HOWTO/DEPRECATE.md
Add a howto describing how to update Erlang/OTP deprecation and removal warnings.
> Add deprecate howto

- erts/doc/src/erl_cmd.xml
- erts/doc/src/erlang.xml
- erts/preloaded/src/erlang.erl
- system/doc/general_info/DEPRECATIONS
- system/doc/reference_manual/data_types.xml
This pull request contains an attempt to improve the documentation for functions in the Erlang module. The pull request adds more examples, fixes errors, and adds more links. Most of the changes are based on comments from @sverker and @rickard-green.
> Improvements to the documentation for the Erlang module

- erts/emulator/beam/jit/instr_bs.cpp
- erts/emulator/test/bs_match_int_SUITE.erl
https://bugs.erlang.org/browse/ERL-1391
> jit: Fix overflow check in 64-bit bs_get_integer

- lib/kernel/doc/src/code.xml
Fairly simple subject-verb agreement.
> Typo fix in code documentation

- erts/doc/src/escript_cmd.xml
Possessive noun should have apostrophe
> Typo fix in escript_cmd

- lib/ftp/doc/src/ftp.xml
- lib/ftp/src/ftp.erl
- lib/ftp/test/ftp_SUITE.erl
- lib/ftp/test/ftp_SUITE_data/vsftpd.conf
https://bugs.erlang.org/browse/ERL-740
> support for FTP over SSL

- erts/doc/src/erl_nif.xml
https://bugs.erlang.org/browse/ERL-1399
> Clarify 'caller_env' arguments in erl_nif doc

- erts/configure.in
https://bugs.erlang.org/browse/ERL-1411
> erts: Disable native stack if we can't make it signal-safe

- lib/compiler/src/beam_ssa_dead.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
This pull request improves the compilation speed of code found in https://bugs.erlang.org/browse/ERL-1302.
> Speed up compilation of sample code from ERL-1302

- erts/emulator/sys/common/erl_poll.c
On macOS 11, the maximum number of file descriptors can be
unlimited.  `erl` refuses to start if it can't read out the
limit.
It is not practical for `erl` to use a huge number such as 134217728
as the default value, because that value is also used as the size of
the port table. (Making the port table's size dynamic is not something
we want do in a maintenance release.)
Therefore we will set it to 24576, which is the value returned by
`sysctl kern.maxfilesperproc`, and which seems to be the practical
limit.  (Raising that limit might be possible, but it can only be done
by disabling System Integrity Protection (SIP) and editing a bunch of
configuration files.  Anyone who has done that will have to set ulimit
explicitly to number of file descriptors they want to use.) …
> Don't crash if the number of file descriptors is unlimited

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_validator_SUITE.erl
https://bugs.erlang.org/browse/ERL-1426
> beam_validator: Update containers when extracted values change

- lib/stdlib/src/gen_server.erl
This PR adds an optimisation in `gen_server:multi_call` function in case when this function is used in a single node environments or more general when the only node that is the target of multi call is the local node.
Note that `gen_server:multi_call` is used in many places (in `global` module, in `pg2` module and indirectly also in `mnesia`), and its disadvantage over `gen_server:call` (in single local node case) is that it does not leverage the recv_mark optimisation.
It means that when caller is under pressure (having big outstanding message queue lenght) it is much slower than normal `call`.
A simple demonstration of effect of lack of this optimisation is here:
```erlang
1> timer:tc(fun() -> global:set_lock({mnesia_adjust_log_writes, self()}, [node()], 1) end).      
{82,true}
2> …
```
> Added gen_server:multi_call optimisation for single local node case.

- lib/stdlib/src/maps.erl
The current implementation is not efficient when
the maps being compared are mostly distinct.
It happens that collecting all keys and building
the map once at the end is the most efficient
way of implementing intersection.
Benchmarks show this approch is often 4x faster in
the mostly distinct cases, otherwise it behaves
within 5-10% of the current implementation. The only
case it is considerably slower is when working with
small sets of integers (~10 elements) but those
are done in nanoseconds anyway.
Benchmaking code and results:
https://gist.github.com/josevalim/759f3a9c2613119d3e38cd4224840d32
> Use maps:from_list/1 on maps:intersect_with/3

- lib/wx/api_gen/wx_extra/wxTaskBarIcon.erl
- lib/wx/examples/simple/menu.erl
- lib/wx/src/gen/wxTaskBarIcon.erl
The API will change to an option list in OTP-24,
so change the API now before it is used.
> Change the taskbar api to be forward compat

- lib/kernel/src/inet_db.erl
This patch is just a refactoring but it should provide
faster operations at the cost of slightly higher storage
(which is acceptable since the table is relatively small).
This will also make it possible to have decentralized
lookups in the future.
This is prep-work for the PR in #2818.
> Convert inet_cache to a set

- lib/compiler/src/beam_ssa_bc_size.erl
- lib/compiler/test/bs_bincomp_SUITE.erl
https://bugs.erlang.org/browse/ERL-1434
> Fix crash when compiling binary comprehension

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
https://bugs.erlang.org/browse/ERL-1440
> beam_ssa_type: Don't subtract the common type on inequality

- lib/public_key/src/pubkey_cert.erl
Fix pubkey_cert:verify_data/1 specs
> Fix pubkey_cert:verify_data/1 specs

- lib/crypto/c_src/engine.c
and robustify the NIFs against faulty usage.
* Add `ctx->is_functional` to know if ENGINE_init has been called  and if ENGINE_finish needs to be called.
* Add cleanup to destructor as fallback if engine_free/finish_nif has not been called.
* Set `ctx->engine=NULL` when freed and check it after all calls to enif_get_resource.
Removed memory leaks reported by address-sanitizer:
Test case `engine_SUITE:ctrl_cmd_string`
Direct leak of 192 byte(s) in 1 object(s) allocated from:
#0 0x7f955fb64b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
#1 0x7f9556c0accb in CRYPTO_malloc crypto/mem.c:222
#2 0x7f9556c0acfe in CRYPTO_zalloc crypto/mem.c:230
#3 0x7f9556bd227e in ENGINE_new crypto/engine/eng_lib.c:34
#4 0x7f9556bd345c in ENGINE_by_id crypto/engine/eng_list.c:301
#5 …
> crypto: Fix ENGINE leaks

- lib/edoc/include/edoc_doclet.hrl
- lib/edoc/src/edoc.erl
- lib/edoc/src/edoc.hrl
- lib/edoc/src/edoc_data.erl
- lib/edoc/src/edoc_doclet.erl
- lib/edoc/src/edoc_extract.erl
- lib/edoc/src/edoc_layout.erl
- lib/edoc/src/edoc_lib.erl
- lib/edoc/src/edoc_macros.erl
- lib/edoc/src/edoc_parser.yrl
- lib/edoc/src/edoc_refs.erl
- lib/edoc/src/edoc_report.erl
- lib/edoc/src/edoc_run.erl
- lib/edoc/src/edoc_specs.erl
- lib/edoc/src/edoc_tags.erl
- lib/edoc/src/edoc_types.erl
- lib/edoc/src/edoc_types.hrl
- lib/edoc/test/edoc_SUITE.erl
- lib/xmerl/src/xmerl_scan.erl
- scripts/otp_html_check
This extracts spec/type changes from #2803 for easier review. No functional changes to EDoc are made in this PR.
> EDoc spec cleanup

- erts/emulator/beam/atom.names
No longer needed as added in #2293
cc @essen
> Remove unused atom from erts

- .github/dockerfiles/Dockerfile.32-bit
- .github/dockerfiles/Dockerfile.64-bit
- .github/dockerfiles/Dockerfile.cross-compile
- .github/dockerfiles/Dockerfile.ubuntu-base
- .github/scripts/init-pre-release.sh
- .github/workflows/main.yaml
- erts/configure.in
- erts/emulator/Makefile.in
- erts/emulator/beam/jit/beam_asm.hpp
- erts/emulator/beam/packet_parser.c
- erts/emulator/beam/sys.h
- erts/emulator/drivers/common/inet_drv.c
- erts/emulator/nifs/common/prim_socket_nif.c
- erts/emulator/nifs/common/socket_int.h
- erts/emulator/nifs/common/socket_util.c
- erts/emulator/nifs/common/socket_util.h
- lib/crypto/c_src/crypto_callback.c
- lib/odbc/c_src/odbcserver.c
- lib/wx/configure.in
This PR does three things:
* Add -Werror to all CFLAGS
* Start using clang to compile 64-bit in order to catch clang warnings
* Fix all warnings in applications that came up along the way
> Add -Werror to github actions C/C++ compilation

- lib/stdlib/src/sets.erl
maps:from_keys/2 speeds up sets creation by avoiding
a list traversal and reducing memory allocation.
Both intersection/2 and subtract/2 operations were
also augmented with a new heuristic that chooses
between creating a set from scratch or deleting some
of the existing keys, in order to reduce memory
allocation and speed up operations.
As of this patch, I would say the guidelines for
choosing between ordsets, gb_sets and sets (v2) is
the following:
1. If you only want to traverse, perform unions,
intersections, or subtractions of values that
are quick to compare (integers, atoms, etc)
and they are up to 1k-10k in size, pick ordsets;
2. If you need take_smallest and take_largest and
you don't want to do external bookkeeping, use
gb_sets;
3. For everything else, choose sets (v2). …
> Use maps:from_keys/2 and heuristics in new sets

- erts/lib_src/common/erl_misc_utils.c
> erts: Support cgroup2 CPU quotas

- HOWTO/BENCHMARKS.md
The formatting was driving me crazy.
Also uh, should we get rid of the "This will hopefully change in the near future."
This is 9 years old and afaict this is still not available...
> Bring HOWTO/BENCHMARKS.md formatting to modern markdown

- erts/doc/src/erlang.xml
> More security recommendations in binary_to_term/2 docs

- lib/wx/api_gen/interface/wx/notifmsg.h
- lib/wx/api_gen/wx_gen_cpp.erl
- lib/wx/api_gen/wx_gen_nif.erl
- lib/wx/api_gen/wxapi.conf
- lib/wx/c_src/gen/wxe_derived_dest.h
- lib/wx/c_src/gen/wxe_events.cpp
- lib/wx/c_src/gen/wxe_func_table.cpp
- lib/wx/c_src/gen/wxe_init.cpp
- lib/wx/c_src/gen/wxe_macros.h
- lib/wx/c_src/gen/wxe_wrapper_1.cpp
- lib/wx/c_src/gen/wxe_wrapper_2.cpp
- lib/wx/c_src/gen/wxe_wrapper_3.cpp
- lib/wx/c_src/gen/wxe_wrapper_4.cpp
- lib/wx/c_src/gen/wxe_wrapper_5.cpp
- lib/wx/c_src/gen/wxe_wrapper_6.cpp
- lib/wx/c_src/gen/wxe_wrapper_7.cpp
- lib/wx/c_src/gen/wxe_wrapper_8.cpp
- lib/wx/doc/src/wxNotificationMessage.xml
- lib/wx/examples/demo/Makefile
- lib/wx/examples/demo/ex_notificationMessage.erl
- lib/wx/include/wx.hrl
- lib/wx/src/gen/wxCommandEvent.erl
- lib/wx/src/gen/wxNotificationMessage.erl
- lib/wx/src/gen/wxe_funcs.hrl
Hey @dgud,
this is my first try on adding a new component to wxWidgets. In the examples/simple/menu.erl I've added in the file menu an option to show the notification. 
Note:
I've done conditional handling of the events since those are only available starting in 3.1.0, have tried that with 3.0.4 and it does seem to deactivate them successfully, haven't yet tried with 3.1.x yet though will do later.
> wxNotificationMessage support

- lib/compiler/src/beam_ssa_recv.erl
- lib/compiler/src/compile.erl
This pull request reduces the compilation time for some huge modules. For example, on my computer this PR reduced the time for compiling `String.Unicode` in the Elixir standard library from almost 30 seconds down to less than 15 seconds.
> Reduce compilation times for some huge modules

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/src/erl_parse.yrl
Eliminate a type violation introduced in 852ba3dcdfd.
> erl_lint: Eliminate type violation

- erts/etc/win32/erlsrv/erlsrv_service.c
> Make emulator terminate if erlsrv does (windows)

- system/doc/reference_manual/typespec.xml
See also https://bugs.erlang.org/browse/ERL-892.
> dialyzer: Clarify how to declare records used in match patterns

- lib/compiler/src/beam_block.erl
- lib/compiler/src/beam_flatten.erl
- lib/compiler/src/beam_jump.erl
- lib/compiler/src/beam_kernel_to_ssa.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_trim.erl
- lib/compiler/src/compile.erl
- lib/compiler/test/Makefile
- lib/compiler/test/beam_ssa_SUITE.erl
- lib/compiler/test/bif_SUITE.erl
- lib/compiler/test/bs_bincomp_SUITE.erl
- lib/compiler/test/bs_match_SUITE.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/bad_core.core
- lib/compiler/test/compile_SUITE_data/bad_core_tokens.core
- lib/compiler/test/compile_SUITE_data/column_pt.erl
- lib/compiler/test/compile_SUITE_data/cover_messages.erl
- lib/compiler/test/compile_SUITE_data/generic_pt.erl
- lib/compiler/test/compile_SUITE_data/line_pt.erl
- lib/compiler/test/compile_SUITE_data/needs_defines.erl
- lib/compiler/test/core_fold_SUITE.erl
- lib/compiler/test/fun_SUITE.erl
- lib/compiler/test/guard_SUITE.erl
- lib/compiler/test/misc_SUITE.erl
- lib/compiler/test/receive_SUITE.erl
- lib/compiler/test/record_SUITE.erl
- lib/compiler/test/trycatch_SUITE.erl
This pull request improves coverage of the compiler application by removing known unreachable lines and by extending the test suites to cover more lines.
> Improve test coverage of the compiler application

- lib/runtime_tools/doc/src/scheduler.xml
> runtime_tools: Clarify scheduler utilization docs

- lib/ssl/src/inet_tls_dist.erl
- lib/ssl/test/ssl_dist_SUITE.erl
TLS handshake may take considerable amount of time, so it should
be done in a different process, not accepting process itself.
Also, there is no need to kill the accepting process if TLS
handshake fails.
Handshake process keeps max priority that original implementation had.
> inet_tls_dist: make TLS handshake concurrent

- lib/tools/src/cover.erl
- lib/tools/test/cover_SUITE.erl
A subtle detail in the semantics of list comprehensions is that
filters will be compiled as guard expressions if possible. That means
that the following list comprehension will never raise an exception as
long as it is passed a proper list:
lc(L) ->
[V || V <- L, V =:= a orelse element(1, V) =:= a].
Thus, the following call:
lc([a, {a,b}, {}, "ignore"])
will return `[a, {a,b}]`. When the calls `element(1, {}` and
`element(1, "ignore")` fail, no exception is raised and the
corresponding list elements are discarded.
The `cover` tools rewrites rewrites `andalso` and `orelse` to `case`
constructions in order to produce better coverage data. For this example,
that rewriting would change the error behavior of the list comprehension:
lc(L) ->
[V || V <- L,
case V =:= a of
true -> true;
false -> …
> cover: Ensure that LC filters are compiled in guard context

- lib/compiler/src/beam_ssa_opt.erl
The `beam_ssa_opt:ssa_opt_try/1` optimization would sometimes fail to
eliminate a redundant `try`/`catch` construct because it only looked
for `new_try_tag` instructions at the beginning of an SSA block. Here
is an example:
foobar({Anno}=T, V) ->
try
setelement(1, T, V)
catch
_Class:_Error:_Stack ->
Anno
end.
In the SSA code, the `get_tuple_element` instruction from the tuple
matching in the function head is at the beginning of the block with the
`new_try_tag` instruction:
8:
_10 = get_tuple_element _0, `0`
@ssa_catch_tag = new_try_tag `'try'`
br @ssa_catch_tag, ^6, ^5
Generalize the optimization to handle this example. While at it,
also make the optimization run faster by eliminating redundant
set update operations.
> Enhance the optimization of the try/catch elimination optimization

- lib/mnesia/src/mnesia.erl
> Fix create_option() spec description error

- lib/compiler/src/beam_ssa_opt.erl
In generated code and in code involving inlining/macros, a newly constructed list or tuple could be matched in the same function.
Here is an example of generated code:
%% : sqrsum  dup *  swap  dup *  + ;
sqrsum(SP_0) ->
[X1|_] = SP_0,
SP_1 = [X1|SP_0],         % dup
[X2,X3|SP_2] = SP_1,
SP_3 = [(X2*X3)|SP_2],    % *
[X4,X5|SP_4] = SP_3,
SP_5 = [X5,X4|SP_4],      % swap
[X6|_] = SP_5,
SP_6 = [X6|SP_5],         % dup
[X7,X8|SP_7] = SP_6,
SP_8 = [(X7*X8)|SP_7],    % *
[X9,X10|SP_9] = SP_8,
[(X9+X10)|SP_9].          % +
Here is the main part of the BEAM code for the function:
{test,is_nonempty_list,{f,5},[{x,0}]}.
{get_list,{x,0},{x,1},{x,0}}.
{gc_bif,'*',{f,0},2,[{x,1},{x,1}],{x,1}}.
{test,is_nonempty_list,{f,4},[{x,0}]}.
{test_heap,4,2}.
{get_list,{x,0},{x,2},{x,0}}. …
> Extend CSE to eliminate list and tuple matching

- system/doc/reference_manual/introduction.xml
> Add a short note on reserved words cond and let

- lib/ssl/src/ssl_certificate.erl
- lib/ssl/src/ssl_crl.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/test/ssl_crl_SUITE.erl
> ssl: Refactor CRL functions to solve GH-4589

- lib/mnesia/src/mnesia.erl
Some where qouted and some not, qoute them all.
> Quote atom in types

- configure.src
> Do not allow mandatory apps to be disabled

- lib/stdlib/doc/src/digraph.xml
- lib/stdlib/doc/src/digraph_utils.xml
This PR fixes a couple of typos I stumbled across in the docs.
> Small documentation fixes in digraph and digraph_utils 

- lib/kernel/src/pg.erl
- lib/kernel/test/pg_SUITE.erl
pg keeps two copies of state: gen_server state and ETS table for
concurrent access. #2866 fixed one potential way to introduce
mismatch between internal state and ETS table, and this patch
completes the fix.
> pg: fix empty group removal from internal pg state

- lib/kernel/src/group_history.erl
- lib/kernel/src/user_drv.erl
- lib/kernel/test/interactive_shell_SUITE.erl
This PR adds tests of shell_history. While adding tests I found a few places that needed to be made a little bit more robust, so I've done that as well.
> Shell history tests

- lib/common_test/doc/src/write_test_chapter.xml
Closes #4617.
cc: @IngelaAndin
> Inform on how an end_per_testcase crash affects test results

- lib/compiler/doc/src/Makefile
- lib/compiler/doc/src/internal.xml
- lib/compiler/internal_doc/beam_ssa.md
- lib/erl_docgen/priv/xsl/db_html.xsl
This documents some BEAM SSA invariants which would have been helpful to know when I started hacking the Erlang compiler.
The patch to docgen to support internal documentation in the form of both chapters and modules feels somewhat hackish, so helpful suggestions on how to improve it are welcome.
> Document BEAM SSA invariants

- erts/etc/unix/cerl.src
- erts/etc/unix/etp.py
The etp macros only work for gdb and Apple has made it almost impossible to install gdb, so in order to debug on OS X we need working lldb macros.
This commit ports the most important macros to lldb so that we can more easily do some basic debugging. The commands ported are:
* etp-processes
* etp-process-info
* etp-stacktrace
* etp-stackdump
* etp (Also lldb's type formatter is used to print Eterm)
Examples:
```
(lldb) bt
* thread #5, name = '1_scheduler', stop reason = step in
* frame #0: 0x00005555556d5257 beam.smp`do_send(p=0x00007fffb4cc0a88, to=0x500b init, 
msg=0x7fffb1e03302 {<0.9.0>,{'set_script_name',{...}}},
return_term=0x7fffb1e03302 {<0.9.0>,{'set_script_name',{...}}},
refp=0x00007fffb1dfacd0, dist_ctx=0x00007fffb1dfacc8, connect=1, suspend=1) at bif.c:2207:9
frame #1: …
```
> erts: Implement some etp macros for lldb

- lib/edoc/include/edoc_doclet.hrl
- system/doc/general_info/deprecations_24.inc
> edoc: Re-instate ?NO_APP and deprecate it

- erts/emulator/beam/jit/x86/beam_asm_perf.cpp
- erts/etc/common/ct_run.c
- erts/etc/common/dialyzer.c
- erts/etc/common/erlc.c
- erts/etc/common/erlexec.c
- erts/etc/common/inet_gethost.c
- erts/etc/common/typer.c
- erts/etc/unix/jit-reader.c
This pull-request fixes a number of problems reported by [codechecker](https://github.com/Ericsson/codechecker).
> Fixes to problems reported by codechecker

- erts/emulator/beam/erl_nif.c
ASSERT_IN_ENV called by debug emulator could incorrectly fail in dirty NIFs if the term was located in a heap fragment or off-heap message.
> Fix ASSERT_IN_ENV for dirty NIFs

- erts/emulator/beam/erl_proc_sig_queue.c
> Fix handling of recv marker when serving a process_info request

- lib/stdlib/src/supervisor.erl
> Fix doc spelling

- erts/emulator/test/exception_SUITE.erl
- lib/kernel/src/erl_erts_errors.erl
For BIFs that only accept a local pid, the extended error information would
state that the argument was not a pid. For example:
(arne@seldon)1> RemotePid = rpc:call(kalle@seldon, erlang, whereis, [code_server]).
<9325.50.0>
(arne@seldon)2> process_info(RemotePid).
in function  process_info/1
called as process_info(<9325.50.0>)
*** argument 1: not a pid
Correct the extended error information for those BIFs to report the argument as
"not a local pid". For example:
(arne@seldon)1> RemotePid = rpc:call(kalle@seldon, erlang, whereis, [code_server]).
<9325.50.0>
(arne@seldon)2> process_info(RemotePid).
in function  process_info/1
called as process_info(<9325.50.0>)
*** argument 1: not a local pid
Similarly, the extended error …
> Correct extended error info for remote pids and ports

- lib/common_test/doc/src/ct_property_test.xml
- lib/crypto/doc/src/crypto.xml
- lib/dialyzer/doc/src/dialyzer.xml
- lib/erl_interface/doc/src/ei_connect.xml
- lib/erl_interface/doc/src/ei_global.xml
- lib/kernel/doc/src/file.xml
- lib/public_key/doc/src/public_key.xml
- lib/snmp/doc/src/snmpa.xml
- lib/snmp/doc/src/snmpm.xml
- lib/ssh/doc/src/ssh.xml
- lib/ssh/doc/src/ssh_agent.xml
- lib/stdlib/doc/src/beam_lib.xml
- lib/stdlib/doc/src/maps.xml
in crypto, common_test, erl_interface, public_key, snmp, ssh and stdlib.
> Fix missing xml since attributes

- erts/emulator/nifs/common/zlib_nif.c
- lib/kernel/test/zlib_SUITE.erl
> zlib: Fix edge case in state flushing

- lib/dialyzer/src/erl_types.erl
- lib/dialyzer/test/indent2_SUITE_data/results/iodata
- lib/dialyzer/test/r9c_SUITE_data/results/asn1
- lib/dialyzer/test/small_SUITE_data/results/binary_nonempty
- lib/dialyzer/test/small_SUITE_data/results/binary_redef2
- lib/dialyzer/test/small_SUITE_data/src/binary_nonempty.erl
- lib/dialyzer/test/small_SUITE_data/src/binary_redef.erl
- lib/dialyzer/test/small_SUITE_data/src/binary_redef2.erl
- lib/dialyzer/test/specdiffs_SUITE_data/results/iodata
- lib/dialyzer/test/user_SUITE_data/results/wsp_pdu
- lib/edoc/src/edoc_types.erl
- lib/stdlib/src/erl_internal.erl
- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
- system/doc/reference_manual/typespec.xml
> Add types nonempty_{binary,bitstring}()

- .github/dockerfiles/Dockerfile.32-bit
- .github/dockerfiles/Dockerfile.64-bit
- .github/dockerfiles/Dockerfile.debian-base
- .github/dockerfiles/Dockerfile.ubuntu-base
- HOWTO/INSTALL.md
- erts/aclocal.m4
- erts/configure.in
- lib/crypto/c_src/Makefile.in
- lib/crypto/configure.in
- make/configure.in
- otp_build
Not all configure arguments in OTP has been checked...
Closes #4230
> Make configure scripts fail on requests that cannot be satisfied

- erts/emulator/beam/erl_proc_sig_queue.c
Summary: build error in erl_proc_sig_queue
Test Plan: configure --with-dynamic-trace=systemtap && make
Reviewers:
Subscribers:
Tasks: #4790
Tags:
> Fix for build issue when USE_VM_PROBES is enabled.

- lib/public_key/doc/src/public_key_records.xml
- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_logger.erl
Enhance documentation and logging of certificate handling.
> Ingela/ssl/public key/cert doc log enhancment/gh 4800/otp 17384

- lib/stdlib/src/io_lib_pretty.erl
- lib/stdlib/test/io_SUITE.erl
> Fix io_lib_pretty:printable_latin1_list/2

- lib/tools/src/cover.erl
- lib/tools/test/cover_SUITE.erl
Fixes https://github.com/erlang/otp/issues/4796
> cover:filter_options/1: preserve tuple_calls

- system/doc/programming_examples/list_comprehensions.xml
- system/doc/reference_manual/expressions.xml
> Clarify the rules for variable shadowing in comprehensions

- lib/ssl/src/ssl.erl
> ssl: Remove duplicate option documentation

- erts/etc/unix/etp-commands.in
- erts/etc/unix/etp-thr.py
Fixed etp-cons and etpf-cons printing.
Added dirty CPU/IO schedulers and poll thread to etp-thr.py.
Fixed outdated comments
> etp-commands: various small fixes

- lib/compiler/src/beam_kernel_to_ssa.erl
- lib/compiler/test/trycatch_SUITE.erl
Like all other instructions that throw, `raw_raise` must have an edge to the current fail block.
Fixes #4859
> compiler: Fix code generation for `raw_raise`

- erts/emulator/beam/erl_gc.c
- erts/emulator/test/gc_SUITE.erl
> Fix GC of alias-signals

- erts/emulator/beam/beam_debug.c
- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_map.c
- erts/emulator/beam/global.h
- erts/emulator/beam/utils.c
- erts/emulator/test/erts_debug_SUITE.erl
> Fix maps internal sorting bug for gcc flag "-flto"

- lib/kernel/src/os.erl
Support when the shell is located in /system/bin/sh on Android, otherwise a call to os:cmd would fail like this:
```
$ erl
Eshell V12.0  (abort with ^G)
1> os:cmd("ls").
"sh: /bin/sh: not found\n"
```
Let me know what you think and if you have suggestions for improvements. Thanks a lot
> Make os:cmd compatible with Android

- lib/stdlib/src/proc_lib.erl
- lib/stdlib/test/proc_lib_SUITE.erl
This PR is a fix for issue #4853 by making sure the terminate message is always sent to the target process. It also removes the proxy process which was (probably) only there to catch late replies. It keeps the current outward behavior in regards to the format of exit messages. The stop test was augmented to make sure that the process eventually exits (ie, that the termination message was sent) even with a timeout of zero.
> Fix race condition in proc_lib:stop/3 with small timeouts

- lib/stdlib/doc/src/lists.xml
> Clarify the Pred function in lists must return booleans

- lib/public_key/src/public_key.erl
- lib/ssl/src/ssl_certificate.erl
- lib/ssl/src/ssl_crl.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/property_test/ssl_eqc_chain.erl
- lib/ssl/test/property_test/ssl_eqc_handshake.erl
- lib/ssl/test/ssl_cert_SUITE.erl
- lib/ssl/test/ssl_pem_cache_SUITE.erl
This PR makes ssl application work the same as OpenSSL s_client  for the provided example in #4877 
Regression tests and possible code documentation is still to be added.
> Ingela/ssl/alt certs/gh 4877/otp 17475

- erts/emulator/beam/erl_process.c
- erts/emulator/test/scheduler_SUITE.erl
> Fix erlang:system_flag(schedulers_online, NewSchedsOnln)

- erts/emulator/beam/erl_bif_unique.h
- erts/emulator/beam/erl_node_tables.c
- erts/emulator/test/distribution_SUITE.erl
> Fix for DistEntry write-after-free bug

- lib/kernel/src/application.erl
- lib/kernel/src/application_controller.erl
_Note: PR #2675 introduced a performance regression on application:ensure_all_started/2. This pull request address it by adding the same check found in `application_controller:start_application/2` This applies to the `maint` branch, as you may want to include this on 24.1._
When optional applications were added in 79146711, ensure_all_started/2 had to take explicit control over the initialization cycle so available optional applications were started properly. However, in doing so, we lost one important optimization, which was to not attempt to start children of a given application if said application was already running.
This commit address this by exporting is_running/1 and skipping the work in case the given app is already running. This change makes it so the time taken to start a deep …
> Do not attempt to start children of running apps

- lib/ssl/src/ssl_connection.hrl
- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/tls_connection.erl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_gen_connection.erl
Solve at least some issues discovered due to  #5009
> Ingela/ssl/downgrade/gh 5009/otp 17517

- lib/observer/src/observer_trace_wx.erl
This is more convenient than finding the right application and tracing its process tree.
Not sure about the button label: `Add all Processes and Ports` is quite wide and might make the buttons overflow the visible part of the window.
Also not sure what to do about trace options. Right now the new button pops up the trace option dialog for processes, which is not strictly correct as `all` includes ports as well.
> observer: add button to trace all processes and ports

- lib/ssl/test/Makefile
- lib/ssl/test/tls_server_session_ticket_SUITE.erl
- test suite added
- enabled coverage verification
> ssl: tls_server_session_ticket unit tests added

- lib/kernel/src/inet.erl
> fix ssl:close with nif sockets

- lib/public_key/src/pubkey_cert.erl
- lib/public_key/src/public_key.erl
- lib/public_key/test/erl_make_certs.erl
- lib/public_key/test/public_key_SUITE.erl
> Fixing #5054, public_key:pkix_sign for RSASSA-PSS signature

- lib/stdlib/src/erl_posix_msg.erl
"protocol not suppored" to "protocol not supported"
> corrected spelling

- erts/preloaded/src/init.erl
Closes #5031.
I did not update the bootstrap code under the assumption you likely
don't want external contributors to change it, regardless of how
trustworthy they are. :)
> Do not unload modules during stop

- lib/kernel/src/logger_disk_log_h.erl
Minor changes:
* Remove `get_default_config/0` and merging with empty `map`
* Update copyright year of `logger_disk_log_h`
* Remove white spaces to try to keep one code style
> Refactoring of logger_disk_log_h

- lib/edoc/src/edoc_layout_chunks.erl
Before this patch:
edoc: warning: 'blockquote' is not allowed - skipping tag, extracting content
After:
telemetry_poller.erl: warning: 'blockquote' is not allowed - skipping tag, extracting content
> edoc: Add source file to the warning on skipped tag

- lib/stdlib/src/erl_pp.erl
- lib/stdlib/test/erl_pp_SUITE.erl
> stdlib: Fix `erl_pp` rendering unary +/- operators

- erts/emulator/beam/erl_bits.c
- erts/emulator/test/hash_SUITE.erl
When a refc binary is very large, it does not make sense to double the size of it anymore when preallocating for more writes. So when it is larger than 64 MB we just increase it by 10%.
@sverker @kjellwinblad what do you think about these limits? I just pulled these ones out guessing what might be reasonable. The Erlang heap grows with 20%, maybe should we do the same for binaries?
> Adjust refc binary growth

- lib/stdlib/src/shell_docs.erl
This commit fixes so that the undocumented function shell_docs:get_type_doc
returns valid values when there is no documentatiion for the type.
Closes #4270
> stdlib: Fix result of shell_docs missing type

- system/doc/design_principles/events.xml
fix callback function arguments error
> design principles doc fix

- lib/ssl/doc/src/ssl.xml
- lib/ssl/src/dtls_v1.erl
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_cipher.erl
- lib/ssl/src/tls_v1.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_basic_SUITE.erl
> Ingela/ssl/psk/gh 4978/otp 17501

- lib/debugger/src/debugger.app.src
Required an update, the copied funcitonality uses a new function from erl_parse
that is new.
> debugger: Update runtime deps

- lib/ssl/src/ssl.erl
> ssl: Correct type spec

- lib/compiler/src/beam_ssa_type.erl
This pull request speeds up the initial type analysis pass by introducing caching of metadata.
On my computer, that reduced the running time of the `beam_ssa_opt` pass when compiling a version of Elixir's `String.Unicode` module by about half a second, from roughly 5 seconds down to 4.5 seconds.
This pull request also includes another minor optimization of the runtime of the type analysis pass.
> Optimize compilation speed

- lib/mnesia/src/mnesia_dumper.erl
> Fix doc typo

- lib/stdlib/src/erl_stdlib_errors.erl
- lib/stdlib/test/maps_SUITE.erl
> Fix incorrect error info for maps:get/2

- lib/ssl/src/ssl_server_session_cache.erl
- lib/ssl/test/ssl_session_SUITE.erl
When a client tries to reuse an expired session the default
server storage handling would crash loosing other session data.
This would cause a error report and possible loss of abbreviated handshakes.
Solves #5192
> ssl: Properly handle default session data storage

- lib/common_test/doc/src/run_test_chapter.xml
- lib/common_test/src/ct_groups.erl
- lib/common_test/src/ct_run.erl
- lib/common_test/test/ct_testspec_1_SUITE.erl
- lib/common_test/test/ct_testspec_1_SUITE_data/groups_1/groups_11_SUITE.erl
CommonTest : Update the grammar for test_spec and add relevant tests as documented in #5088
Update of pull request #5090 with appropriate branch name
> Common_test : Updated grammar for tests specifications

- erts/emulator/beam/bif.c
- erts/emulator/test/monitor_SUITE.erl
> Fix demonitor of an alias

- erts/emulator/beam/erl_monitor_link.c
- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/test/monitor_SUITE.erl
> Fix storage of tags in monitors

- lib/ssl/src/dtls_record.erl
- lib/ssl/test/dtls_api_SUITE.erl
Code was broken and created a larger mask for each
invocation.
Also set REPLAY_WINDOW_SIZE to 58 avoids using bignum,
spec recommends 64 but says it must at least be 32.
Fixes: #5224
> ssl: Fix dtls replay window

- .dir-locals.el
- .editorconfig
- erts/.dir-locals.el
- lib/wx/.dir-locals.el
- lib/wx/.editorconfig
Add .editorconfig for using other editors than Emacs
> Add .editorconfig

- lib/edoc/src/edoc_doclet_chunks.erl
- lib/edoc/src/edoc_layout_chunks.erl
Prior to these adjustments when using ExDoc to generate docs for Erlang projects modules were required to have some top-level docs to be listed in the generated HTML. They could still have function-level docs, but the module wouldn't be listed anyway, so these docs wouldn't be accessible.
With these changes a module will be listed even if it does not have a top-level doc, so that its function docs are available in the generated HTML. This means a module has to be explicitly marked with EDoc `@private` or `@hidden` not to be listed.
See also https://github.com/elixir-lang/ex_doc/issues/1393.
> EDoc: Adjust default/private/hidden doc visibility in chunks

- lib/mnesia/src/mnesia.erl
- lib/mnesia/src/mnesia_checkpoint.erl
- lib/mnesia/src/mnesia_sup.erl
- lib/mnesia/test/Makefile
- lib/mnesia/test/ext_test.erl
- lib/mnesia/test/mnesia_evil_coverage_test.erl
- lib/mnesia/test/mnesia_test_lib.hrl
- lib/mnesia/test/mt.erl
> Flush exit messages

- erts/emulator/beam/dist.c
- erts/emulator/beam/dist.h
- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/beam/erl_process.c
- erts/emulator/test/Makefile
- erts/emulator/test/signal_SUITE.erl
> Fix forced distributed signals

- lib/ssl/test/ssl_session_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
Test what it is documented to test.
> ssl: Fix testcase

- erts/emulator/beam/beam_file.c
- erts/emulator/beam/beam_file.h
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/utils/make_preload
- lib/stdlib/test/beam_lib_SUITE.erl
This bug was introduced in #5316 and was never released.
> erts: Fix loading of code with type chunk

- erts/emulator/beam/erl_init.c
> erts: Fix JPperf usage printout

- lib/parsetools/src/yecc.erl
In code generated by `yecc`, only atoms known to be reserved words
would be quoted. If a generated module is later compiled with a
version of the compiler that has made one of the used atoms a
reserved word, compilation would fail.
Avoid the problem by having `yecc` code quote all atoms in the
generated code.
> yecc: Avoid compilation errors if atoms become reserved words

- lib/ssl/src/ssl_cipher.erl
- lib/ssl/test/property_test/ssl_eqc_cipher_format.erl
- lib/ssl/test/ssl_eqc_SUITE.erl
> ssl: Fix typo of ECC signature name

- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_app.erl
- lib/ssl/test/ssl_api_SUITE.erl
> ssl: Supress warning if verify_none is explicitly set

- lib/observer/test/crashdump_viewer_SUITE.erl
- lib/observer/test/observer_SUITE.erl
- lib/wx/api_gen/gl_gen_doc.erl
- lib/wx/api_gen/gl_gen_erl.erl
- lib/wx/api_gen/gl_gen_nif.erl
- lib/wx/c_src/gen/gl_nif.cpp
- lib/wx/c_src/wxe_impl.cpp
- lib/wx/doc/src/gl.xml
Fixes crashes in testcases on Sunos.
> Improve destroy env

- lib/sasl/src/release_handler_1.erl
Fixes #5387.
Same kind of bug fix in sasl release_handler as #2666.
@zsoci Would be good if you could give this patch a thorough look.
Contributions to test these kinds of fail scenarios are also welcome.
> sasl: Be even more resilient of exiting processes

- lib/jinterface/test/nc_SUITE.erl
Replace test_server:start_node with ?CT_PEER.
Cleanup unused lines while I'm at it.
> [jinterface] peer-ify application

- lib/os_mon/test/memsup_SUITE.erl
Replace test_server:start_node with ?CT_PEER.
> [os_mon] peer-ify application

- lib/crypto/test/crypto_SUITE.erl
Use `?CT_PEER` instead of test_server:start_node.
> [crypto] peer-ify crypto application

- lib/ssh/test/ssh_options_SUITE.erl
Use ?CT_PEER instead of test_server:start_node.
> [ssh] peer-ify application tests

- lib/ssl/src/tls_gen_connection.erl
- lib/ssl/test/Makefile
- lib/ssl/test/openssl_reject_SUITE.erl
- lib/ssl/test/ssl_reject_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
> Ingela/ssl/interop old clients/gh 5380/otp 17761

- erts/emulator/beam/erl_bif_info.c
- erts/emulator/beam/erl_fun.c
- erts/emulator/test/code_SUITE_data/call_purged_fun_tester.erl
> erts: Fix module name reported by fun_info/1,2 on unloaded funs

- lib/mnesia/src/mnesia.appup.src
Include 4.20.* to restart instructions.
> mnesia: Fix appup

- lib/compiler/src/v3_core.erl
- lib/compiler/test/fun_SUITE.erl
Consider this example:
main(_) ->
_ = (X = 42) + fun() -> X = 0 end(),
io:format("~p\n", [X]).
When run as an `escript`, we will get different results depending
on whether we run it using `erl_eval` or using the Erlang compiler.
Here is the result using `erl_eval` (the default):
$ escript t.erl
42
Here is the result using the compiler:
$ escript -c t.erl
escript: exception error: no match of right hand side value 0
At least one of the results must be wrong. Which?
The compiler is wrong.
A binary operator (such as `+`) is allowed to evaluate its operands
in any order. Thus, code that depends on the left hand side of
a binary operator being evaluated before the right hand side is
illegal and will be rejected by the compiler. For example:
bar(A) ->
(X = A) + (2 * X).
Compilation will fail …
> Correct scope of variables

- lib/stdlib/src/erl_lint.erl
Only compute erl_lint:start() if there are records.
> Optimize erl_lint:is_guard_test/2-3

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/beam_asm_global.cpp
- erts/emulator/beam/jit/arm/beam_asm_module.cpp
- erts/emulator/beam/jit/arm/instr_float.cpp
- erts/emulator/beam/jit/beam_jit_common.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_global.cpp
- erts/emulator/beam/jit/x86/beam_asm_module.cpp
- erts/emulator/beam/jit/x86/instr_float.cpp
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
This PR fixes some minor inefficiencies discovered while investigating #5437.
> Minor JIT optimizations

- erts/doc/src/erl_cmd.xml
> Add note for remsh on Windows

- lib/ssl/src/inet_tls_dist.erl
- net_kernel could be leaking processes
- if connection process gets killed due to crash propagation
- crash must come from other connection process which
failed on inet_tcp:accept
Fixes #5332
> ssl: fix process leak with TLS distribution

- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/x86/beam_asm_module.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
This PR makes yield tests slightly cheaper, improving `dialyzer` performance by about 1% on my x64 machine.
> jit: Optimize yield tests

- lib/ssh/src/Makefile
- lib/ssl/src/Makefile
> ssl: Fix sed of ssl/ssh deps file

- lib/runtime_tools/test/dbg_SUITE.erl
- lib/runtime_tools/test/erts_alloc_config_SUITE.erl
Also fix some test cases that may fail due to linked processes
going down when stopping the peer node.
> [runtime_tools] replace test_server:start_node with ?CT_PEER

- lib/ssl/src/dtls_connection.erl
Renegotiating with an Openssl server does not work if the cookie
is not sent.
> Reuse cookie when renegotiating dtls

- erts/emulator/drivers/unix/ttsl_drv.c
- lib/kernel/test/interactive_shell_SUITE.erl
The terminal would incorrectly emit " \b" when the next wrapping character was a \r|\n.
I think this is the correct behaviour, but it is hard to test on all terminals.
Closes #5403
> erts: Fix ttsl driver xn followed by nl

- erts/doc/src/erlang.xml
> Document erlang:display() may print internal info

- lib/stdlib/doc/src/ets.xml
Signed-off-by: Matteo Cafasso <noxdafox@gmail.com>
> Fix typos in ETS doc

- xcomp/erl-xcomp-aarch64-darwin.conf
Based on #5284, thanks @dominicletz!
Below [1] is a script to cross-compile OpenSSL & OTP for aarch64-darwin. I executed it from an Intel Mac.
A couple of notes however:
1. Wx cannot be cross-compiled yet:
> ```
> *********************************************************************
> *********************************************************************
> **********************  APPLICATIONS INFORMATION  *******************
> *********************************************************************
>
> wx             : Cross compilation of the wx driver is not supported yet, wx will NOT be usable
> ```
2. Erlang shell successfully starts:
$ uname -sm
Darwin arm64
$ ./bin/erl
Erlang/OTP 24 [erts-12.1.5] [source-df1294f108] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Eshell V12.1.5  (abort …
> xcomp: Add aarch64-darwin

- system/doc/general_info/upcoming_incompatibilities.xml
> otp: Add warning that default time warp mode will change

- lib/debugger/src/dbg_iload.erl
- lib/debugger/test/record_SUITE.erl
index_expr needs to be translated before returned.
Fixes #5571
> debugger: Fix record index matching

- lib/compiler/src/v3_core.erl
This commit will shave off a few seconds for the `v3_core` pass
for the example in #5140.
> v3_core: Reduce the compile time for functions with many variables

- lib/compiler/src/beam_trim.erl
For a huge function with straight-line code, the `beam_trim` pass
could take forever, mainly because of the ineffcient way of
calculating the use information in the `frame_layout()` function.
This pull request reduces the time for the `beam_trim` of the sample code
in #5140 to about 1 second on my computer (down from at least
5 minutes).
While at it, also add support for new instructions in OTP 25, and
fix a minor bug resulting in some trimming opportunities were being
ignored.
Co-authored-by: John Högberg <john@erlang.org>
> beam_trim: Reduce compile time for huge straight-line functions

- system/doc/reference_manual/opaques.xml
- system/doc/reference_manual/part.xml
- system/doc/reference_manual/typespec.xml
- system/doc/reference_manual/xmlfiles.mk
close  #5240
> I wasn't able to verify this, since the command fails for me locally: make[3]: `*** No rule to make target `../chunks/array.chunk', needed by `chunks'.  Stop.`
> Document opaques - ready for review

- erts/emulator/beam/erl_db_util.c
- erts/emulator/beam/erl_process.c
- erts/emulator/sys/common/erl_mmap.c
> erts: Fix compiler warnings

- lib/kernel/src/auth.erl
- lib/kernel/test/erl_distribution_SUITE.erl
> Fix erlang:get/set_cookie for dynamic node name

- lib/ssh/src/ssh_connection.erl
If an SSH client does not specify what line endings to use, use CRLF.
This fixes the built-in Windows ssh client that currently reports as
"OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2".
The reason for changing the default rather than adding another special
case is that OpenSSH defaults to sending CR characters when unspecified.
See the use of ONLCR at [1]. This mirrors that behavior.
Interestingly, I found ONLCR is normally on with my testing with OpenSSH
SSH to connect between MacOS and Linux, so this may not be an unusual
setting anyway for non-Windows computers. Verification was done by
capturing output and checking `stty -a | grep onlcr`.
Tested on Windows (Putty and commandline ssh in Powershell), Linux and
MacOS.
[1] https://github.com/openssh/openssh-portable/blob/2dc328023f60212cd295 …
> Change default unspecified ssh line ending to CRLF

- lib/compiler/src/beam_trim.erl
- lib/compiler/test/bs_match_SUITE.erl
Fixes https://github.com/erlang/otp/commit/4b0d37bd2ce15208946a1977721515ab2d99bf34#r65741129
@itssundeep
> beam_trim: Fix special case in bs_start_match4

- lib/compiler/src/beam_call_types.erl
Fixes a missed type optimization we discovered during #5690.
> beam_call_types: Improve types of maps:from_list/1 et al

- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
Do miscellaneous minor optimizations, such as removing dead code and redundant tests.
> Some more compiler optimizations

- lib/wx/api_gen/gen_util.erl
- lib/wx/api_gen/wx_gen.erl
- lib/wx/api_gen/wx_gen_doc.erl
- lib/wx/api_gen/wx_gen_nif.erl
- lib/wx/api_gen/wxapi.conf
- lib/wx/c_src/gen/wxe_derived_dest.h
- lib/wx/c_src/gen/wxe_events.cpp
- lib/wx/c_src/gen/wxe_func_table.cpp
- lib/wx/c_src/gen/wxe_wrapper_4.cpp
- lib/wx/doc/src/wxImage.xml
- lib/wx/src/gen/wxGridEvent.erl
- lib/wx/src/gen/wxImage.erl
- lib/wx/src/gen/wxe_funcs.hrl
- lib/wx/test/wx_basic_SUITE.erl
- lib/wx/test/wxt.erl
> wx: Bugfixes

- lib/ssl/src/tls_gen_connection.erl
- lib/ssl/src/tls_sender.erl
> ssl: Use non timing dependent reference to assert ditribution mode

- lib/ssl/src/dtls_gen_connection.erl
- lib/ssl/src/dtls_handshake.erl
- lib/ssl/test/ssl_test_lib.erl
Fix max fragment issues and disable openssl tests for 3.0 gives internal error in openssl.
> dtls max fragment fixes

- lib/compiler/src/beam_call_types.erl
- lib/compiler/src/beam_ssa_dead.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/src/sys_core_fold.erl
`maybe` will (most likely) become a keyword in a future release.
> Quote all occurrences of the `maybe` atom

- lib/asn1/src/asn1ct_constructed_ber_bin_v2.erl
- lib/asn1/src/asn1ct_imm.erl
- lib/dialyzer/src/dialyzer_options.erl
`maybe` will (very likely) be a keyword in a future release.
> Quote atom `maybe` in the `asn1` and `dialyzer` applications

- erts/epmd/src/epmd_srv.c
When specifying bind address(es) via ERL_EPMD_ADDRESS or the -address
option, epmd will bind to the IPv4/IPv6 loopback intefaces in addition
to the user-supplied address(es).
However, it is possible that one of the loopback interfaces does not
exist.  For example, if the host system has ipv6 disabled via the
disable_ipv6 sysctl, there will be no loopback interface "::1", and
attmepting to bind to "::1" will fail.
Under these circumstances, log the failure but do not consider the
failure to bind to the loopback interface as fatal.
If any of the user-supplied addresses fail to bind, however, that is
still considered fatal and epmd will terminate.
> epmd: don't fail if non-critical interfaces fail to bind

- lib/ssl/src/tls_handshake_1_3.erl
> ssl: Handle missing certificate_authorities extension

- lib/stdlib/doc/src/lists.xml
- lib/stdlib/src/lists.erl
- lib/stdlib/test/lists_SUITE.erl
see: https://github.com/erlang/otp/issues/5606
ref: https://erlangforums.com/t/benchmarking-of-maps-and-the-proposed-lists-uniq-1/1118
> Adding lists:uniq/1 and lists:uniq/2

- lib/ssl/test/openssl_ocsp_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
- fix stability of openssl_oscp_SUITE
> ssl: ocsp test cuddle

- lib/kernel/src/logger_std_h.erl
- lib/kernel/test/logger_std_h_SUITE.erl
If the folder(s) for a log file is deleted, we want to
re-create it if possible in order to make sure that we
do our best in getting the log message into the disk.
Closes #5828
> logger: Re-create folders for file logger if deleted

- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/using_ssl.xml
- lib/ssl/src/dtls_connection.erl
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_certificate.erl
- lib/ssl/src/ssl_config.erl
- lib/ssl/src/ssl_connection.hrl
- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/ssl_internal.hrl
- lib/ssl/src/tls_connection.erl
- lib/ssl/src/tls_dtls_connection.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/src/tls_v1.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_cert_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
Addresses the feature request form ERL-1016 and #4143
@essen I tried to have this prioritized for quite a while now, but better late than never. Hope it will be what you wished for.
> Ingela/ssl/select appropriate cert/gh 4143/otp 15993

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/test/bs_match_bin_SUITE.erl
> jit: Fix bs_match_string and an addition helper on ARM

- lib/wx/c_src/gen/wxe_wrapper_5.cpp
Update pushed to wx_api_branch on git@github.com:erlang/wxWidgets.git
and code re-generated.
Fixes #5893
> wx: Fix build problems with wxWidgets-3.1.6

- lib/compiler/test/property_test/compile_prop.erl
- lib/compiler/test/random_code_SUITE.erl
The test case `random_code_SUITE:compile/1` that compiled randomly
generated code could never actually fail.
Extend the test case to test each generated code sample with different
compiler options and also make it possible to pass in the number
of tests to run in the environment variable `ERL_RANDOM_CODE_NUMTESTS`.
> Mend and extend random_code_SUITE

- erts/doc/src/erlang.xml
I need some guidance on the proper syntax to make this link.
> Link to docs on heap sizing

- lib/inets/doc/src/httpc.xml
- with option, it is possible to connect with hostname when IP family is unknown
> inets: document inet6fb4 option for httpc

- erts/emulator/test/op_SUITE.erl
- lib/compiler/test/guard_SUITE.erl
Strengthen tests of relational operators to better test current
and potential future optimizations done by the JIT.
> Strengthen tests of relational operators

- lib/compiler/src/beam_types.erl
- lib/compiler/test/beam_validator_SUITE.erl
> beam_types: Improve meet/2 performance for tuples

- erts/emulator/beam/erl_bif_persistent.c
- erts/emulator/test/persistent_term_SUITE.erl
> erts: Fix a race in persistent_term:get/1,2

- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/using_ssl.xml
Update users guide to use new option and encourage good option choices.
Make default value clarification in refrence manual
> ssl: Enhance documentation

- lib/kernel/src/inet_res.erl
- lib/kernel/test/inet_res_SUITE.erl
> Fix a missing internal {ok,Name} wrapper in inet:resolve/3

- lib/stdlib/doc/src/ets.xml
The sentence talks about a singular function so it needs "updates" not "update".
> ets.xml: fix grammar in update_counter/N doc

- lib/dialyzer/doc/src/dialyzer.xml
> dialyzer: Correct documentation for missing/extra_return

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
When attempting to compile a module named `''` (in the file `.erl`),
the compiler would produce the following error message:
1> c("").
..beam: Module name '' does not match file name '.'
error
Compiling with `erlc` would also fail.
Instead of trying to fix this problem, this pull request forbids nonsensical
module names. Here are the types of module names that are no longer
allowed:
* An empty module name (the atom `''`).
* Names containing control characters (16#00 through 16x1F and 0x7F
through 16#9F).
* Names containing **only** spaces and soft hyphens.
We don't change the rules for function names (yet, anyway), because
they don't have the same fundamental problem that module names have,
namely that a file in the file system must be have the same base name
as the module.
Solves #6026
> Forbid nonsensical module names

- lib/inets/doc/src/httpc.xml
> Missing a curly bracket

- lib/compiler/src/beam_ssa_bsm.erl
- lib/compiler/src/beam_ssa_recv.erl
- lib/compiler/test/warnings_SUITE.erl
> Handle AST nodes without location on *_opt_info

- erts/doc/src/erlang.xml
- erts/preloaded/src/erlang.erl
This also stream lines with the development of the analogous functions in Elixir:
- https://github.com/elixir-lang/elixir/blob/01361af9fe582c71abdb9746c854f6fe59fbf511/lib/elixir/lib/kernel.ex#L550
- https://github.com/elixir-lang/elixir/blob/01361af9fe582c71abdb9746c854f6fe59fbf511/lib/elixir/lib/kernel.ex#L1249-L1250
> Make specs for hd/1 and tl/1 more specific 

- HOWTO/INSTALL.md
> Fix links in Install guide to work with patch releases

- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_type_SUITE.erl
> Eliminate compiler crash in beam_clean

- lib/ssl/test/ssl_pem_cache_SUITE.erl
- variable renames
- adjust test certificate chain building
- adjust verification instructions
> ssl: improve table checks ssl_pem_cache_SUITE

- lib/ssl/src/tls_handshake_1_3.erl
Total nit found while investigating https://github.com/erlang/otp/issues/6106 and figured I'd be at least a little helpful 😄
> Fix certificate_authorities misspelling

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/test/beam_type_SUITE.erl
When attempting to compile the following code:
foo(V) when (V / V < (V orelse true)); V; V ->
(V = (a =/= V)) orelse 0.
the `beam_validator` pass produces the following message:
t:1: function foo/1+12:
Instruction: {test,is_eq_exact,{f,9},[{x,1},{atom,true}]}
Error:       {type_conflict,{t_atom,[true]},{t_atom,[a]}}:
The type conflict mentioned refers to the expression `a =/= V`. At
the point of its evaluation, `V` is known to `beam_validator` to be
the atom `true`; thus, evaluation of `a =/= V` is redundant because the
result is always `false`.
The root cause of the problem is that `beam_validator` has a stronger
type analysis for `=/=` expressions than `beam_ssa_type`. By
strengthening the type analysis for `=/=` in …
> Eliminate internal consistency failure

- lib/kernel/src/application_controller.erl
- lib/kernel/test/application_SUITE.erl
> kernel: Reject .app files with invalid parameters

- lib/observer/src/observer_sys_wx.erl
> observer_sys_wx.erl: fix grammar

- erts/emulator/test/map_SUITE.erl
This was triggered by #6151 which had a map comparison bug not found by existing tests.
> Extend map_SUITE:t_map_compare for atom keys

- HOWTO/TESTING.md
Just a trivial fix to the documentation.
> Update the name of the temporary result file in TESTING.md

- lib/stdlib/doc/src/unicode.xml
Found while working on rabbitmq/rabbitmq-server#5551
> Minor grammatical fix

- erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/arm/instr_map.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl
- erts/emulator/beam/jit/x86/instr_map.cpp
Avoiding calling a helper function improves performance of
map creation.
> Inline creation of small maps with literal keys

- lib/stdlib/src/base64.erl
We will take advantage of the newly introduced performance
improvements of binary matching to speed up Base64 encoding and
decoding.
For decoding, we now attempt to match out four characters at once
because that is faster than matching out one character at the time.
For encoding, we now match out four 6-bit chunks at once, which
allows us to eliminate the bit shifting and masking operations.
(For some more speed, we first try to match out eight 6-bits chunks
at once.)
Fixes #5639
> base64: Optimize encoding and decoding of binaries

- erts/doc/src/erlang.xml
> Fix typo, efter --> after

- lib/os_mon/c_src/win32sysinfo.c
- lib/os_mon/src/os_mon_sysinfo.erl
Fixes #6156
Note: I have not yet been able to build from this branch on Windows to test this out.
> Fix port communication with win32sysinfo.exe

- lib/ssl/src/ssl.erl
> ssl: Clarify warning

- lib/ssl/src/ssl.erl
- lib/ssl/test/ssl_pem_cache_SUITE.erl
> ssl: fix for symlink resolving to relative path with CA certs

- lib/kernel/src/inet_tcp_dist.erl
- lib/kernel/src/net_kernel.erl
- lib/ssl/src/inet_tls_dist.erl
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/ssl_internal.hrl
- lib/ssl/src/tls_connection_1_3.erl
- lib/ssl/src/tls_gen_connection.erl
- lib/ssl/test/inet_crypto_dist.erl
- lib/ssl/test/ssl_dist_SUITE.erl
This could introduce significant performance boost on dist traffic.
More discussion is happening in https://github.com/erlang/otp/pull/5840
> [RFC] Introduce kernel TLS offload in inet_tls_dist

- lib/ssl/doc/src/ssl.xml
> ssl: Clarify doc

- lib/compiler/src/sys_messages.erl
- lib/compiler/test/compile_SUITE.erl
> Fix printing of line numbers greater than 9999

- lib/compiler/src/beam_ssa.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/test/receive_SUITE.erl
> Fix compiler crash for binary matching in receive

- lib/stdlib/src/dets.erl
- lib/stdlib/test/dets_SUITE.erl
Current implementation of `dets:req/2` function in `dets` module is not using receive optimisation.
Module `dets` is used as a backend for `mnesia`'s `disc_only_copies` tables. All dirty operations, or symmetric transactions (`sym_trans`) are executed in context of a single `mnesia_tm` process which means that in case of using `disc_only_copies` tables we are actually vulnerable to non-optimised `dets` calls in case when `mnesia_tm` message queue is busy.
The proposed solution introduces receive optimisation to avoid that potential problem.
> Introduce receive optimisation to dets calls

- lib/inets/doc/src/httpc.xml
- lib/inets/src/http_client/httpc.erl
- lib/inets/test/httpc_SUITE.erl
- lib/inets/test/httpc_proxy_SUITE.erl
Make ssl connections more secure by default.
> inets: Make https requests verify host by default

- system/doc/reference_manual/typespec.xml
Add note and examples about anonymous type variables (#6289)
> docs: add note about anonymous type variables

- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
See the individual commit messages for details.
> Fix/enhance assertions in the DEBUG build

- erts/emulator/beam/emu/bs_instrs.tab
- erts/emulator/beam/emu/generators.tab
- erts/emulator/beam/emu/ops.tab
- erts/emulator/beam/erl_bits.h
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/generators.tab
- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/generators.tab
- erts/emulator/beam/jit/x86/instr_bs.cpp
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_pre_codegen.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/src/genop.tab
- lib/compiler/test/compilation_SUITE.erl
- lib/compiler/test/compilation_SUITE_data/string_table.erl
This pull request builds on the improvements in #6259 to further optimize binary matching. See the individual commit messages for more details.
> Further optimize binary matching

- erts/doc/src/persistent_term.xml
* process -> processes (two places)
* add a missing "the"
* remove an extraneous comma
> persistent_term.xml: fix grammar

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/bs_match_SUITE.erl
> Eliminate compiler crash in the beam_ssa_type pass

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
> compiler: Eliminate crash in beam_ssa_type

- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/beam_type_SUITE.erl
> Eliminate internal error in sub pass ssa_opt_ranges

- lib/compiler/src/beam_disasm.erl
This change is similar to #6447: the command list was not yet resolved when translating the `bs_match/3` instruction. This change decodes the command list into the shape expected by `beam_validator:validate_bs_match/4`.
> beam_disasm: Resolve commands for bs_match/3 instruction

- lib/compiler/src/beam_ssa_bc_size.erl
- lib/compiler/test/bs_bincomp_SUITE.erl
> Eliminate crash in sub pass ssa_opt_bc_size

- lib/compiler/src/beam_ssa_bc_size.erl
- lib/compiler/test/compilation_SUITE_data/infinite_loop.erl
> Eliminate infinite loop in the Erlang compiler

- lib/dialyzer/src/dialyzer_typesig.erl
- lib/dialyzer/test/small_SUITE_data/results/bs_fail_constr
- lib/dialyzer/test/small_SUITE_data/src/bs_fail_constr.erl
> Eliminate crash in dialyzer_typesig

- lib/ssl/src/Makefile
- lib/ssl/src/ssl.app.src
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/ssl_trace.erl
- lib/ssl/test/Makefile
- lib/ssl/test/ssl_test_lib.erl
- lib/ssl/test/ssl_trace_SUITE.erl
- module for enhancing runtime observability in ssl
> ssl: add ssl_trace module

- lib/kernel/test/pg_SUITE.erl
Fix sometimes failing test cases.
@max-au
> Improve pg_SUITE

- lib/compiler/src/v3_core.erl
- lib/compiler/test/fun_SUITE.erl
> Fix compiler crash for named fun expression with convoluted scoping

- erts/emulator/sys/win32/sys.c
> Fix open_port spawn with spaces in PATH on windows

- lib/dialyzer/src/dialyzer_dep.erl
- lib/dialyzer/test/small_SUITE_data/src/gh_6518.erl
> Eliminate crash in dialyzer_dep

- lib/ssl/src/tls_sender.erl
- lib/ssl/test/ssl_key_update_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
> Kuba/ssl/tls sender key update cleanup/otp 18349

- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/tls_handshake_1_3.erl
Quote the `maybe` atoms and functions in the `ssl` application.
> Quote the atom `maybe` in the `ssl` application

- erts/doc/src/erlang.xml
- erts/doc/src/match_spec.xml
- erts/emulator/beam/bif.tab
- erts/emulator/beam/erl_bif_guard.c
- erts/emulator/beam/erl_db_util.c
- erts/emulator/test/bif_SUITE.erl
- erts/preloaded/src/erlang.erl
- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/compile.erl
- lib/compiler/src/v3_kernel.erl
- lib/stdlib/src/erl_internal.erl
- lib/stdlib/src/ms_transform.erl
- lib/stdlib/test/ms_transform_SUITE.erl
- system/doc/reference_manual/expressions.xml
> Allow max/2 and min/2 to be used in guards

- lib/ssl/src/ssl.erl
> ssl: Refactor to avoid confusion of what is the API

- lib/stdlib/src/erl_error.erl
> erl_error: Fix parameter order bug

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_validator_SUITE.erl
> beam_validator: Bail on impossible sizes in bs_get_integer

- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_type_SUITE.erl
> beam_call_types: Handle more boolean ops in will_succeed/3

- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/test/guard_SUITE.erl
> Fix failed assertion in debug build

- CONTRIBUTING.md
Added a new paragraph with instructions for what happens/should be done _after_ submitting a PR.
> Augment CONTRIBUTING.md

- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
> jit: Fix buggy assertion in bs_get_float2

- lib/eunit/src/eunit_data.erl
> eunit: replace call to `size/1` function by `XXX_size/1`

- lib/mnesia/test/mnesia_consistency_test.erl
> mnesia: replace size/1 by XXX_size/1

- lib/dialyzer/test/indent_SUITE_data/src/map_galore.erl
- lib/dialyzer/test/opaque_SUITE_data/src/ewgi/ewgi.hrl
- lib/dialyzer/test/opaque_SUITE_data/src/ewgi2/ewgi.hrl
- lib/dialyzer/test/options1_SUITE_data/src/compiler/cerl.erl
- lib/dialyzer/test/options1_SUITE_data/src/compiler/cerl_inline.erl
- lib/dialyzer/test/user_SUITE_data/src/wsp_pdu.erl
Replaces `size/1` by `XXX_size/1`
#6672
> dialyzer: replace size/1 by XXX_size/1

- lib/kernel/src/group.erl
This addresses a regression on Erlang/OTP 26 master.
> Also normalize expand_fun when set via io:setopts

- lib/compiler/src/beam_bounds.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/src/beam_types.erl
- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_bounds_SUITE.erl
- lib/compiler/test/beam_type_SUITE.erl
- lib/compiler/test/bs_match_SUITE.erl
> compiler: Various type-related fixes and improvements

- lib/kernel/test/gen_udp_SUITE.erl
> kernel: replace calls to size/1 by XXX_size/1

- erts/emulator/beam/emu/float_instrs.tab
- erts/emulator/beam/jit/arm/instr_float.cpp
- erts/emulator/beam/jit/x86/instr_float.cpp
- erts/emulator/test/float_SUITE.erl
> jit: Fix float negation on x64

- erts/emulator/beam/jit/arm/instr_bs.cpp
- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_match_int_SUITE.erl
> Fix failed matching of integer with unoptimized code

- lib/kernel/src/code.erl
The functions load_native_* do not have a
respective implementation in the code_server,
which means they would always fail. They are
also not documented. We removed their
definitions and further dead from callers.
> Remove dead code from code module

- lib/ssh/src/ssh.erl
- lib/ssh/src/ssh_dbg.erl
- lib/ssh/src/ssh_options.erl
- lib/ssh/test/ssh_basic_SUITE.erl
> ssh: replace size/1 by XXX_size/1

- lib/snmp/src/agent/snmpa_net_if.erl
- lib/snmp/test/snmp_agent_SUITE.erl
- lib/snmp/test/snmp_test_lib.erl
- lib/snmp/test/snmp_test_mgr.erl
- lib/snmp/test/snmp_test_mgr_misc.erl
> snmp: replace size/1 by XXX_size/1

- erts/emulator/beam/erl_bif_guard.c
- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/beam/jit/arm/instr_call.cpp
- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
- erts/emulator/beam/jit/arm/ops.tab
- erts/emulator/beam/jit/x86/beam_asm.hpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
- erts/emulator/beam/jit/x86/ops.tab
- erts/emulator/test/bif_SUITE.erl
Optimize `min/2`, `max/2`, and relational operators for both x86_64 and AArch64. Also do a few other optimizations for AArch64.
> JIT: Miscellaneous optimizations

- lib/diameter/src/base/diameter_codec.erl
- lib/diameter/src/base/diameter_lib.erl
- lib/diameter/src/base/diameter_types.erl
- lib/diameter/src/info/diameter_info.erl
- lib/diameter/test/diameter_codec_test.erl
- lib/diameter/test/diameter_gen_tcp_SUITE.erl
> diameter: replace size/1 by XXX_size/1

- erts/doc/src/match_spec.xml
- erts/emulator/beam/erl_db_util.c
- erts/emulator/test/match_spec_SUITE.erl
> erts: Add current stack trace to tracing

- lib/stdlib/doc/src/maps.xml
> Update list of map functions consuming iterators

- lib/stdlib/src/gen_server.erl
- lib/stdlib/test/gen_server_SUITE.erl
Utilize the "new" selective receive optimizations (introduced in OTP 24) and process alias (also introduced in OTP 24) to implement `gen_server:multi_call()` without the use of a middleman process. Also removed support for communication with R6B nodes.
> [stdlib] Optimize gen_server:multi_call()

- erts/etc/common/Makefile.in
- erts/etc/win32/erl.rc
- erts/etc/win32/nsis/Makefile
- erts/etc/win32/nsis/erlang20.nsi
- erts/etc/win32/nsis/vsn_number.escript
- erts/etc/win32/version.h.src
> Update various file and installer properties

- lib/runtime_tools/src/system_information.erl
- lib/runtime_tools/test/system_information_SUITE.erl
I found this by chance. Feel free to close it if for some reason the native entry is still desired in reports.
> Remove HiPE info from system_information.erl

- lib/inets/test/httpc_SUITE.erl
- lib/inets/test/httpc_proxy_SUITE.erl
- lib/inets/test/httpd_SUITE.erl
- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/standards_compliance.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/tls_v1.erl
- lib/ssl/test/openssl_cipher_suite_SUITE.erl
- lib/ssl/test/property_test/ssl_eqc_chain.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_basic_SUITE.erl
- lib/ssl/test/ssl_cert_SUITE.erl
- lib/ssl/test/ssl_cert_tests.erl
- lib/ssl/test/ssl_cipher_suite_SUITE.erl
- lib/ssl/test/ssl_dist_SUITE.erl
- lib/ssl/test/ssl_dist_bench_SUITE.erl
- lib/ssl/test/ssl_pem_cache_SUITE.erl
- lib/ssl/test/ssl_sni_SUITE.erl
- lib/ssl/test/ssl_test_lib.erl
> Ingela/ssl/no sha1 per default and doc enhancments/gh 6679/otp 18438

- system/doc/top/templates/index.html.src
Update index.html.src , removing some text about editors and linking to erlang.org instead
> Update index html

- lib/ssl/src/tls_client_connection_1_3.erl
To ensure interoperability assert middlebox change_cipher_spec after processing an hello_retry_request instead of before.
Closes #6807
> ssl: Adjust assert of middlebox change_cipher_spec for better interop

- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/beam/jit/x86/instr_common.cpp
- erts/emulator/test/op_SUITE.erl
Fixes a bug we noticed while reviewing #6731
> jit: Fix type hint error in emit_is_lt

- lib/compiler/src/beam_ssa_alias.erl
During development alias information was created lazily. This is no longer the case, so all functions accessing alias status can safely assume that alias information is available.
Also refactor aa_join/2 which was only used when the first element in the list is known to be a #b_var{}.
> compiler: Remove dead code from alias analysis pass

- erts/test/otp_SUITE.erl
* There are no longer any calls to the `size/1` function in any OTP application. `size/1` is not formally deprecated, but its use is not recommended, and we should not use it in OTP code. From now on, use of `size/1` in any OTP application will cause the `otp_SUITE:call_to_size_1/1` test to fail.
* The only uses of the deprecated `now/0` function is from the `et` application. From now on, `otp_SUITE:call_to_now_0/1` will forbid calls to `now/0` from any other application than `et`.
> otp_SUITE: Update tests for non-recommended functions

- erts/emulator/beam/jit/arm/instr_guard_bifs.cpp
- erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
- erts/emulator/test/map_SUITE.erl
> Fix bad exception in map_get/2

- system/doc/reference_manual/character_set.xml
- system/doc/reference_manual/code_loading.xml
- system/doc/reference_manual/data_types.xml
- system/doc/reference_manual/distributed.xml
- system/doc/reference_manual/expressions.xml
- system/doc/reference_manual/features.xml
- system/doc/reference_manual/macros.xml
- system/doc/reference_manual/modules.xml
- system/doc/reference_manual/opaques.xml
- system/doc/reference_manual/ports.xml
- system/doc/reference_manual/processes.xml
- system/doc/reference_manual/records.xml
- system/doc/reference_manual/typespec.xml
While at it, fix a few other minor issues.
> Reference Manual: Use the change tag for clarity

- lib/inets/src/http_client/httpc_handler.erl
Added changes requested from closed PR #6661 .
I would have done those changes but the comments were added after the PR was already merged
> inets: refactor code to improve readability

- lib/compiler/src/beam_call_types.erl
> beam_call_types: Infer range of various arithmetic operations

- lib/kernel/src/code.erl
Previously it would prepare modules and then
abandon references to said modules if they had
on_load callbacks. This pull request makes it
so they keep the references around and then
serially load them without having to fetch the
object code and prepare them again.
We also simplify the internal prepared tuples.
The third element is always undefined since the
removal of native code, so we remove it.
> Improvements to ensure_modules_loaded/1

- lib/inets/src/http_client/httpc.erl
- lib/inets/src/http_client/httpc_handler.erl
- lib/inets/src/http_lib/http_internal.hrl
- lib/inets/src/http_lib/http_transport.erl
- lib/inets/src/http_server/httpd.erl
- lib/inets/src/http_server/httpd_conf.erl
- lib/inets/src/http_server/httpd_example.erl
- lib/inets/src/http_server/httpd_request_handler.erl
- lib/inets/src/http_server/httpd_script_env.erl
- lib/inets/src/http_server/httpd_sup.erl
- lib/inets/src/http_server/mod_alias.erl
- lib/inets/test/httpc_SUITE.erl
- lib/inets/test/httpd_SUITE.erl
- lib/inets/test/httpd_bench_SUITE.erl
- lib/inets/test/httpd_time_test.erl
- lib/inets/test/inets_test_lib.erl
I plan to merge the commits so that a  possible future git bisect will be happy, but made it two now for easier review!
> Ingela/inets/remove legacy ssl option handling/gh 6380/otp 18476

- lib/compiler/src/v3_kernel.erl
- lib/compiler/test/bs_match_SUITE.erl
When compiling generated code from forms where the line numbers in the annotations did not correspond to the actual order of the clauses, the compiler could rearrange clauses even when it was not safe. For example:
match_route([<<"prefix">>, <<"action">>]) -> first;  %Line 4
match_route([<<"prefix">>, _Ignore]) -> second.      %Line 2
The compiler would rearrange that to:
match_route([<<"prefix">>, _Ignore]) -> second;      %Line 2
match_route([<<"prefix">>, <<"action">>]) -> first.  %Line 4
which would make the second clause (former first clause) unreachable.
This bug was introduced in cadd19e84478ed (#6538).
Closes #6923
> Correct unsafe optimization of binary matching

- erts/emulator/drivers/common/inet_drv.c
- lib/kernel/test/inet_sockopt_SUITE.erl
- lib/kernel/test/inet_sockopt_SUITE_data/sockopt_helper.c
Fixes broken implementation in #6522 and some test case fixes
> Windows reuseaddr/reuseport fix

- lib/runtime_tools/src/instrument.erl
Allocations should be a list in instrument:carriers spec
> fix instrument:carriers spec

- lib/compiler/src/beam_ssa_alias.erl
Reduce the cost of the alias analysis pass by hoisting the calculation of use and def sets out of the liveness fixpoint iteration using a cache. On the modules compiled by `scripts/diffable` the time spent in the alias analysis pass is reduced by 16%.
> compiler: Cache use/def sets in alias analysis pass

- system/doc/general_info/upcoming_incompatibilities.xml
- system/doc/reference_manual/introduction.xml
> Update the documentation about the maybe feature

- scripts/valgrind_beamasm_update.escript
Hi,
valgrind_beamasm_update script to slow, with my data (5Mb logs and 2Mb perf map) it's works hours. Patched script now works less than minute.
> Speedup valgrind_beamasm_update script

- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/src/tls_sender.erl
- lib/ssl/test/ssl_key_update_SUITE.erl
- fetch application traffic secret from TLS sender process
> ssl: fix keylog mechanism

- lib/compiler/src/beam_ssa_private_append.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Fix #7011 and while at it, remove some dead code.
> Fix compiler crash in beam_ssa_private_append (#7011)

- lib/eldap/doc/src/eldap.xml
- lib/eldap/src/eldap.erl
- lib/eldap/test/eldap_basic_SUITE.erl
- lib/ssl/src/ssl.erl
eldap:info/1 returns information about the LDAP connection (socket and transport protocol)
> New API eldap:info/1

- lib/stdlib/src/sets.erl
> sets: Improve subtract/2 performance for small sets

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
> Eliminate false warning for re-defined and unused type

- erts/preloaded/src/erlang.erl
- lib/dialyzer/src/erl_types.erl
- lib/stdlib/src/erl_internal.erl
- system/doc/reference_manual/typespec.xml
A reference implementation for EEP 61 "Built-in dynamic type".
> EEP 61: Built-in dynamic type

- lib/stdlib/doc/src/queue.xml
Improve module `queue` by adding examples to many of its operations.
> queue: add examples

- lib/inets/src/http_lib/http_transport.erl
Use  a more standard function to format IP addresses
> inets: httpd - Use inet:ntoa to get ip address string format

- lib/kernel/src/application.erl
This commit also trims down the internal graph
by keeping only applications with a mod callback
in concurrent mode.
> Preserve applications order on ensure_all_started

- lib/kernel/doc/src/application.xml
Update application since tag to show which ticket the change came from.
> Fix since tag in application:ensure_all_started/3

- lib/ssl/src/ssl_gen_statem.erl
If a user cancel alert with level warning is received during handshake make it be handled the same regardless of TLS version. If it is received in connection in TLS-1.3 regard it as an error as it is inappropriate.
In TLS-1.3 all error alerts are considered FATAL regardless of legacy alert type. But make sure legacy type is printed in logs to not confuse users that are expecting the same legacy type as sent by peer.
> ssl: Enhance warning alert handling

- system/doc/reference_manual/expressions.xml
> Document the scoping rules for try/catch/of/after expressions

- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/test/bs_construct_SUITE.erl
> beam_ssa_alias: Fix alias analysis for funs

- .github/workflows/main.yaml
remove "-Win64" from source folder in move command
> fix build-windows in main.yaml

- erts/emulator/beam/jit/beam_jit_common.cpp
> jit: Fix metadata registration for empty modules

- lib/dialyzer/src/dialyzer_dataflow.erl
- lib/dialyzer/test/small_SUITE_data/results/bs_segments
- lib/dialyzer/test/small_SUITE_data/src/bs_segments.erl
> dialyzer: Fix crash on weird segment sizes

- lib/compiler/src/beam_validator.erl
- lib/compiler/test/beam_validator_SUITE.erl
> beam_validator: Improve arithmetic range inference

- erts/emulator/beam/code_ix.c
> erts: Fix overlapping blocking code barriers in the same tick

- erts/configure
- erts/configure.ac
- erts/emulator/beam/jit/beam_jit_main.cpp
- lib/erl_interface/configure
- make/autoconf/otp.m4
> erts: Fix ic/dc config tests and usage

- lib/compiler/src/beam_types.erl
- lib/compiler/test/beam_type_SUITE.erl
> Eliminate internal error in beam_types:float_from_range/1

- lib/compiler/src/beam_call_types.erl
- lib/compiler/test/beam_type_SUITE.erl
> Eliminate crash in beam_ssa_type

- lib/compiler/src/beam_jump.erl
- lib/compiler/test/beam_jump_SUITE.erl
> Eliminate unsafe sharing optimization in beam_jump

- lib/compiler/src/beam_types.erl
- lib/compiler/test/beam_type_SUITE.erl
> Eliminate crash in beam_types

- lib/kernel/doc/src/file.xml
- lib/kernel/doc/src/inet.xml
- lib/stdlib/src/erl_posix_msg.erl
Fixes https://github.com/erlang/otp/issues/7213
> stdlib: Fix description of 'exdev' POSIX error

- erts/emulator/beam/jit/x86/instr_bs.cpp
- erts/emulator/test/bs_construct_SUITE.erl
> x86 JIT: Fix error info for failed binary construction

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
> beam_ssa_bool: Fix miscompilation of 'or' guards

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/test/beam_ssa_SUITE.erl
> Eliminate crash in beam_ssa_codegen

- lib/inets/src/http_client/httpc.erl
Avoids crash when using verify_none and the OS does not have a CA cert bundle.
I don't know how to properly test this since the only way I know to produce the reason for this PR is to not have any ca bundles on the system. That is relatively hard to reproduce in normal unit tests.
Fixes #7303
> [httpc] calculate default ssl options on demand

- lib/compiler/src/beam_core_to_ssa.erl
With the fix in #7319 merged to the master branch, the following function would take about half a minute to compile on my computer:
test(Rec) when is_record(Rec, a, 10_000_000) -> Rec.
> Optimize compile time for is_record/3 with huge size

- lib/public_key/src/pubkey_os_cacerts.erl
Fixes #7295
1. Replace a `badmatch` crash with a more descriptive one. `badmatch` feels like a bug to the user. (At least it did to me.)
2. Provide good error detail to the user about the reason of the crash.
I've implemented an extra match of the `load` result to help with 1 and introduced `format_error` which is used in the crash `error_info` for 2.
> [public_key] expose error in public_key:cacerts_get/0 if ca bundle is not found

- lib/stdlib/src/erl_error.erl
> Report an else_clause exception nicely in the shell

- lib/common_test/doc/src/ct_run_cmd.xml
- lib/common_test/priv/Makefile.in
- lib/common_test/priv/vts.tool
- lib/common_test/src/ct_run.erl
This has been mostly removed in 8e5d1b7, the documentation still referenced the options though.
> Drop references to -vts in ct_run

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
> Fix miscompilation of guard with `or`

- erts/emulator/nifs/common/prim_tty_nif.c
Fix https://github.com/erlang/otp/issues/7029
> fix ime not work in windows

- lib/ssl/src/dtls_connection.erl
Hello. 
In case of UDP some packets may be lost. According to RFC (https://datatracker.ietf.org/doc/html/rfc9147#section-5.8.1-7.1) the DTLS handshake participant should re-send content of last flight after timeout but should retain current timer value if no retransmissions happened (https://datatracker.ietf.org/doc/html/rfc9147#section-5.8.2-2, https://datatracker.ietf.org/doc/html/rfc9147#section-5.8.2-5). 
I have observed that retransmission timer value is doubled each time when DTLS state machine entering next state despite there is no retransmission occurred. 
There is code which shows that if state is changed then `retransmit` value is doubled.
```
-module(test).
-include_lib("ssl/src/ssl_connection.hrl").
-compile(export_all).
close(_) -> ok.
start() ->
application:start(crypto), …
```
> Fix incorrect DTLS retransmission timeout

- lib/compiler/src/cerl.erl
- lib/dialyzer/test/small_SUITE_data/results/bs_segments
- lib/dialyzer/test/small_SUITE_data/src/bs_segments.erl
> cerl: Fix crash on 'undefined' segment size

- lib/compiler/test/beam_bounds_SUITE.erl
- lib/compiler/test/beam_ssa_SUITE.erl
- lib/compiler/test/bs_bincomp_SUITE.erl
- lib/compiler/test/bs_match_SUITE.erl
- lib/compiler/test/guard_SUITE.erl
Most of the new test cases were found by erlfuzz.
> Cover more code in the compiler

- lib/compiler/src/beam_bounds.erl
- lib/compiler/test/beam_bounds_SUITE.erl
> beam_bounds: Fix 'bnot' bounds on mixed finite/infinite ranges

- lib/ssl/doc/src/using_ssl.xml
User guide addition about signature algorithms
> ssl: Add UG entry about signatue algorithm configuration

- lib/debugger/src/dbg_icmd.erl
- lib/debugger/test/int_break_SUITE.erl
> debugger: Fix broken `int:no_break(Mod)`

- erts/emulator/beam/jit/arm/instr_common.cpp
- erts/emulator/test/op_SUITE.erl
> Fix mis-evaluation of equality and non-equality tests

- system/doc/tutorial/complex6.erl
- system/doc/tutorial/debugging.xml
Fix #7371
Also some improvements to https://www.erlang.org/doc/tutorial/debugging.html
> Improve tutorial documentation

- lib/stdlib/src/zip.erl
- lib/stdlib/test/zip_SUITE.erl
> Handle seconds in `zip:dos_date_time_from_datetime/1`

- lib/kernel/src/file.erl
> file: export location/0 type

- lib/common_test/proper_ext/ct_proper_ext.erl
The `existing_atom` and `safe_atom` generators, and by extension also the `safe_any`, `safe_list`, `safe_tuple` and `safe_map` generators, behaved in non-deterministic ways when new atoms were registered and also when nodes connected or disconnected, resulting in different outputs when they were used lazily, for example as return values of generated functions.
This PR is related to / blocks #7454, #7453 and #7256.
> Fix common_test PropEr extension

- lib/compiler/src/beam_ssa_bool.erl
- lib/compiler/test/guard_SUITE.erl
> beam_ssa_bool: Fix miscompilation

- lib/ssl/doc/src/using_ssl.xml
So that you find keylog doc easier
> ssl: Doc enhancement

- lib/inets/src/http_client/httpc_request.erl
- lib/inets/src/http_lib/http_request.erl
- lib/inets/test/httpc_SUITE.erl
> inets: httpc - enhance error handling

- lib/ssl/src/ssl_gen_statem.erl
- lib/ssl/test/ssl_renegotiate_SUITE.erl
> ssl: Handle an active socket in pre TLS-1.3 renegotiation rejection

- lib/kernel/src/prim_tty.erl
Closes #7614 
Rebased #7615 against maint
> kernel: fix prim_tty xenl glitch

- erts/emulator/beam/erl_proc_sig_queue.c
The cleanup operation of not yet delivered signals to a terminated process yielded excessively.
> Avoid unnecessary yielding when cleaning up signals

- lib/stdlib/test/binary_property_test_SUITE.erl
- lib/stdlib/test/property_test/binary_prop.erl
This PR provides property-based tests for the functions in the `binary` module.
> Property-based tests for the `binary` module

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
> erl_lint: Don't emit spurious errors

- .github/workflows/main.yaml
GitHub actions released a new runner image yesterday
> Fix windows CI

- erts/emulator/beam/erl_bif_guard.c
> Fix abs(-0.0) to return 0.0 instead of -0.0

- lib/kernel/src/gen_tcp_socket.erl
Restructure the code to use 'if' for better clause reuse.
Handle when the option 'ifaddr' has got
a new sockaddr() map as value.
> Introduce a default state transition for "other" recv errors

- lib/common_test/src/ct_framework.erl
- lib/common_test/test/ct_misc_1_SUITE.erl
- lib/common_test/test/ct_misc_1_SUITE_data/bad_groups_SUITE.erl
Hi,
recreate https://github.com/erlang/otp/pull/7487 to true branch. touch @u3s
> ct: expand groups handle correct suite error

- lib/kernel/doc/src/inet.xml
Add some text in the doc of the gethostbyname function(s) about the use of the resolver.
OTP-18769
> [kernel|doc] Update use of the resolver

- lib/kernel/src/group.erl
- lib/stdlib/test/io_proto_SUITE.erl
When file is used to read from a group, we should return a translation error if the input stream contains unicode characters (as file expects latin1).
Closes #7591
> kernel: Fix group to return translation errors correctly

- lib/syntax_tools/src/erl_syntax.erl
- lib/syntax_tools/test/syntax_tools_SUITE.erl
This fixes/improves the position (really an `erl_anno` annotation) handing in `erl_syntax`.
I discovered today that reverting any `#wrapper` will throw away any modifications to the `pos`, which is fixed in two ways here. First off, make sure `set_pos` also update the inner `tree`. Secondly by always using `revert_root`.
I think either change will fix this, but I prefer having both, as it is nice to keep the `pos` in sync at all times.
While debugging this (by parsing `epp` with `epp` and comparing that with `erl_syntax:revert(erl_syntax_lib:annotate_bindings(...))`), I noticed that the list reverting was also throwing away `pos`/annotations. So I fixed that, mostly anyway. The remaining issues are hard to get around, but the changes reduces the diff.
> syntax_tools: Fix pos during reverting

- lib/inets/src/http_server/mod_alias.erl
Use a relative redirect with an absolute path to prevent whoever is running inets from having to configure the `ServerName` to match the network-reachable hostname of the server.
Fixes #7617.
> inets: Use relative redirects in mod_alias

- lib/ssl/src/ssl_cipher.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_handshake.erl
- lib/ssl/test/openssl_client_cert_SUITE.erl
- lib/ssl/test/tls_1_3_version_SUITE.erl
> ssl: Handle legacy scheme names

- lib/public_key/src/pubkey_cert.erl
- lib/public_key/test/public_key_SUITE.erl
- lib/ssl/src/ssl_certificate.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_handshake_1_3.erl
This PR adjust extended key usage extension. I will merge it  not from github (so I can solve merge conflict)  when ready as I want it based further back to be patched on OTP-25 track.
> Ingela/ssl/ext key usage check/otp 18739

- lib/dialyzer/src/erl_types.erl
- lib/dialyzer/test/opaque_SUITE_data/results/crash
- lib/dialyzer/test/opaque_SUITE_data/src/crash/crash_2.erl
> erl_types: Fix crash in contract checking

- lib/kernel/src/kernel.app.src
- lib/kernel/test/interactive_shell_SUITE.erl
- lib/stdlib/doc/src/shell.xml
- lib/stdlib/doc/src/stdlib_app.xml
- lib/stdlib/src/shell.erl
- lib/stdlib/src/stdlib.app.src
adds shell:multiline_prompt_func/1
also updates stdlib and kernel dependencies
> stdlib: add shell:multiline_prompt_func/1

- system/doc/reference_manual/processes.xml
I'm pretty sure the word used here should be "affecting": https://www.merriam-webster.com/grammar/affect-vs-effect-usage-difference
> Change "effecting" into "affecting"

- lib/ssl/src/ssl_gen_statem.erl
Boolean expression was inverted, so sni was never confirmed to the client.
Though I don't see it as a bug, re-factor the code so that *sni_fun* is only invoked once as per suggestion in the issue report.
Fixes #7795
> Fix sni hostname lookup

- lib/inets/src/http_client/httpc_handler.erl
- lib/inets/test/httpc_SUITE.erl
See #7802
On redirected and retried requests, the newly started httpc_handler may lose the ipfamily that was originally selected in the request. When sending a request over IPv6 using option `{ipfamily, inet6fb4}` and a redirect is returned by the server, the second request would end up wrongly connecting over IPv4 instead.
> inets: Copy ipfamily from state into requests & expand httpc IPv6 testing

- lib/runtime_tools/src/observer_backend.erl
Could crash if port had died.
Fixes #7735
> Fix port crash

- erts/emulator/nifs/common/prim_tty_nif.c
When writing large amounts of data that was not aligned to the size of the receiving stdout buffer the tty nif would continue to write the same content multiple times until the size aligned.
Closes #7838
> Fix tty windows large write

- lib/kernel/src/group.erl
- lib/kernel/src/prim_tty.erl
- lib/kernel/src/user_drv.erl
- lib/kernel/test/interactive_shell_SUITE.erl
- lib/ssh/src/ssh_cli.erl
- lib/stdlib/doc/src/stdlib_app.xml
- lib/stdlib/src/edlin.erl
- lib/stdlib/src/edlin_key.erl
Adds scrollable pager for large outputs for shell hotkeys.
> Paging in shell for autocompletion and search

- .github/actions/build-base-image/action.yaml
- .github/dockerfiles/Dockerfile.ubuntu-base
- .github/dockerfiles/init.sh
- .github/scripts/build-base-image.sh
- .github/scripts/init-pre-release.sh
- .github/scripts/restore-from-prebuilt.sh
- .github/scripts/sync-github-prs.es
- .github/scripts/sync-github-releases.sh
- .github/workflows/actions-updater.yaml
- .github/workflows/add-to-project.yaml
- .github/workflows/main.yaml
- .github/workflows/pr-comment.yaml
- .github/workflows/sync-github-prs.yaml
- .github/workflows/sync-github-releases.yaml
- .github/workflows/update-base.yaml
- scripts/build-otp-tar
This PR backports att GH actions changes in master to maint-26 and fixes various issues with the prebuilt-cache.
> gh: Fix prebuilt cache handling

- lib/inets/test/httpd_serve_SUITE.erl
The bug requiring this workaround was fixed by fc63402c4448fada630ee77ee3577115319487eb and b813bc0b09b44d9b5ada70f153904c435c4b4aa1.
> inets: Remove obsolete code from httpd_serve_SUITE

- lib/stdlib/doc/src/argparse.xml
- lib/stdlib/src/argparse.erl
- lib/stdlib/test/argparse_SUITE.erl
> Report arguments in the order given

- erts/emulator/beam/erl_nif_api_funcs.h
> Fix invalid conversion compilation error (#7903)

- lib/ssl/src/ssl_handshake.erl
- lib/ssl/test/tls_1_3_version_SUITE.erl
> ssl: Fix legacy name handling in certificate request too

- lib/ssl/doc/src/ssl.xml
- lib/ssl/doc/src/standards_compliance.xml
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_client_connection_1_3.erl
- lib/ssl/src/tls_dtls_connection.erl
- lib/ssl/src/tls_gen_connection_1_3.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/src/tls_server_connection_1_3.erl
- lib/ssl/src/tls_v1.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/tls_1_3_record_SUITE.erl
> ssl: Implement TLS-1.3 exporter

- system/doc/reference_manual/documentation.md
Discussed in #8030 
@garazdawi
> Documentation update

- lib/kernel/src/application_controller.erl
`application:get_key` would previously copy from ETS the entire appl record and then select a single field from it. This can be optimized to only select the specific field that's required with `ets:match`.
Especially for `application:get_key(X, env)` this would copy the appl record, completely discard it and lookup the environment which is stored separately. We still need to query separately to preserve the behaviour of returning `undefined` for unloaded applications.
> Optimize application:get_key to avoid full record copies

- HOWTO/DEVELOPMENT.md
Fixes to grammatical error and a broken cross reference.
> Development documentation fixes

- lib/ssl/doc/src/ssl.xml
Add missing documentation update.
> ssl: Correct OTP-26 documentation

- erts/doc/docs.exs
- erts/doc/guides/alt_dist.md
- erts/doc/guides/driver.md
- erts/doc/guides/erl_ext_dist.md
- erts/doc/guides/inet_cfg.md
- erts/doc/guides/match_spec.md
- erts/doc/guides/tty.md
- erts/doc/references/driver_entry.md
- erts/doc/references/epmd_cmd.md
- erts/doc/references/erl_cmd.md
- erts/doc/references/escript_cmd.md
- erts/doc/references/run_erl_cmd.md
- erts/doc/references/start_cmd.md
- erts/doc/references/start_erl_cmd.md
- erts/doc/references/werl_cmd.md
- erts/doc/src/erlang_port_info.md
- erts/doc/src/erlang_system_info.md
- erts/preloaded/src/erlang.erl
- lib/kernel/src/code.erl
- lib/stdlib/src/escript.erl
- system/doc/reference_manual/typespec.md
Create sections for all functions in the Erlang module so that they can more easily be found when exploring.
> Polish erlang module docs

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/src/beam_ssa_type.erl
- lib/compiler/test/record_SUITE.erl
Example:
-record(foo, {a,b,c,d,e}).
update(N) ->
R0 = #foo{},
R1 = R0#foo{a=N},
R2 = R1#foo{b=2},
R2#foo{c=3}.
With this pull request, the initial creation of the record and subsequent record updates will be combined into a single tuple creation instruction.
> Combine creation of a record with subsequent record updates

- lib/compiler/src/beam_types.erl
- lib/compiler/test/beam_type_SUITE.erl
> beam_types: Fix another +0.0/-0.0 issue

- erts/emulator/beam/erl_bif_trace.c
- erts/emulator/test/trace_call_memory_SUITE.erl
- lib/tools/src/tprof.erl
- lib/tools/test/tprof_SUITE.erl
Fix so that profiling works when module is loaded while profiling is turned on.
Another issue I found was that `hprof:enable_trace` is run in the calling process, which means that I cannot use `erpc:call` to start the profiling session without wrapping everything in a process. I will probably move the call to `erlang:trace/3` to the hprof process unless @max-au has some reason to keep it where it is?
> tprof: Fix memory tracing to work for modules loaded while profiling

- lib/tools/src/tprof.erl
- lib/tools/test/tprof_SUITE.erl
Prior to this patch, the length of the total
value being measured was not taken into account
into the layout. This commit addresses it and
also removes outdated comments and redundant
variables.
Closes #8139.
> Consider total when computing tprof layout width

- lib/ssh/doc/references/ssh_app.md
- lib/ssh/src/ssh.hrl
- lib/ssh/src/ssh_transport.erl
- default order of algorithms is adjusted
- related docs are updated and fixed
> ssh: prefer more secure algorithms

- lib/kernel/src/logger_simple_h.erl
- lib/kernel/test/logger_simple_h_SUITE.erl
We only want to replay info messages in the default logger when they happen. If we print them in the simple logger we end up with duplicate log messages and also if the default logger is file based, we print things to stdout no matter what.
closes #8117
> logger: Don't print stdinfo msg to stdout in simple logger

- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/src/beam_ssa_ss.erl
Closes #8132, but not #8140 as that is something else.
> Fix compiler slowdown

- lib/ssh/src/ssh_transport.erl
- lib/ssh/test/ssh_protocol_SUITE.erl
- lib/ssh/test/ssh_test_lib.erl
- lib/ssh/test/ssh_to_openssh_SUITE.erl
- emit "KEX strict" message as debug
- related test adjustments
> ssh: reduce KEX strict message verbosity

- erts/emulator/beam/erl_process_dump.c
> erts: Fix dumping of persistent term funs

- lib/common_test/internal_doc/ct_notes.md
- lib/common_test/src/ct_logs.erl
- lib/common_test/src/test_server_ctrl.erl
This change adds common test's suite execution time to index.html page.
Fixes: #7972
> Michal/common test/time in index/otp 18981

- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/test/code_SUITE.erl
> [erts] Fix signal wakeup issue

- lib/ssl/src/ssl.app.src
- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_handshake.erl
- lib/ssl/src/tls_handshake_1_3.erl
- lib/ssl/test/ssl_api_SUITE.erl
Add certificate policy configuration option
> Ingela/ssl/cert policies/otp 19027

- lib/tftp/src/tftp.erl
- lib/tftp/src/tftp_engine.erl
with auto-generated doc parts.
> tftp: add function specifications for open APIs

- lib/ssl/src/ssl.erl
- lib/ssl/test/ssl_api_SUITE.erl
Double check that ssl:update_options work as expected.
> Add another option test

- lib/compiler/src/beam_ssa_codegen.erl
- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/bs_match_SUITE.erl
> Fix failing binary match

- lib/asn1/src/asn1rtt_jer.erl
- lib/asn1/test/asn1_SUITE.erl
> asn1: Fix compilation error when BER and JER are combined

- lib/diameter/doc/src/diameter.xml
- lib/diameter/src/base/diameter.erl
- lib/diameter/src/base/diameter_config.erl
- lib/diameter/src/base/diameter_service.erl
- lib/diameter/test/diameter_traffic_SUITE.erl
Add an option, bins_info, for the service. When service_info/1 is called,
shall binaries info be collected.
> Bins info in service info

- lib/ssl/src/dtls_packet_demux.erl
- lib/ssl/src/dtls_socket.erl
- lib/ssl/src/ssl.erl
- lib/ssl/test/dtls_api_SUITE.erl
Fix error and ipv6 handling.
Fixes #7955 and #7951
> SSL Fix DTSL issues

- lib/kernel/doc/guides/socket_usage.md
- lib/kernel/src/socket.erl
Add a simple 'socket' usage example to the socket user guide.
> Socket Usage Example

- lib/compiler/src/beam_ssa_destructive_update.erl
- lib/compiler/test/beam_ssa_check_SUITE.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_abort0.erl
- lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_abort1.erl
Fix bug reported in #8281 together with some fixes to typos and improved debugging printouts.
> Avoid infinite loops in destructive update pass

- lib/eldap/src/eldap.erl
> eldap: add specifications for open APIs

- lib/stdlib/src/epp.erl
- lib/stdlib/test/epp_SUITE.erl
> epp: Fix use of `maybe` in macro argument

- erts/preloaded/src/Makefile
> erts: Fix update preloaded of prim_eval

- lib/crypto/src/crypto.erl
Form some more groups and warn for legacy functions that could be insecure
> crypto: Form more groups and warn for legacy functions

- lib/ssl/src/ssl.erl
> ssl: Enhance equiv doc

- erts/emulator/beam/jit/arm/beam_asm.hpp
- erts/emulator/test/beam_SUITE.erl
- erts/emulator/test/beam_SUITE_data/beam_register_cache.S
> arm: Add missing clobber of register cache when SUPER_TMP is used

- erts/doc/src/erlang.xml
> erts: Add warning on BadBatBut attack to open_port/2 documentation

- lib/asn1/src/asn1rtt_jer.erl
Consider this ASN.1 module:
TT DEFINITIONS AUTOMATIC TAGS ::=
BEGIN
S1 ::= SEQUENCE {
nisse INTEGER,
arne INTEGER,
kalle INTEGER,
fredrik INTEGER
}
END
When encoding the `S1` SEQUENCE to JER (JSON encoding rules) using one of the pre-releases of Erlang/OTP 27 that includes the new `json` module, the order of the keys and value in the definition of `S1` would not be retained:
1> asn1ct:compile('TT', [jer]).
ok
2> io:format("~ts\n", [element(2, 'TT':encode('S1', {'S1',1,2,3,4}))]).
{"arne":2,"fredrik":4,"kalle":3,"nisse":1}
ok
While technically not a bug, because the order is not documented, it is a change from how Erlang/OTP 26 and earlier did the JSON encoding, and some use cases that depended on that order could break. Also, it can be helpful for debugging to keep the order.
Therefore, …
> asn1: Retain the definition order in the JER encoding

- lib/ssl/src/ssl_handshake.erl
> ssl: Enhance ALERT logs to help understand what causes the alert.

- lib/public_key/src/pubkey_cert.erl
> public_key: Correct match_name function for dnsNames

- lib/stdlib/src/shell_docs_markdown.erl
- lib/stdlib/test/shell_docs_markdown_SUITE.erl
This can be used, for example, to discard Mermaid diagrams when printing documentation in the shell.
PS: We are considering using this module in Elixir to convert our Markdown to HTML and then render that. I do understand this module is private and we will deal with the consequences of using a private API, but I believe it is better if we can share the rendering stack. During this process, I noticed that there are two features that we needed for now. One is the ability to distinguish the language to discard Mermaid diagrams. To deal with this, I emitting the same HTML as CommonMark. The other part is to properly render tables. Do you folks plan to deal with tables or will you rather keep them as code? Thank you!
> Add class annotation to HTML from fenced blocks

- lib/stdlib/src/json.erl
Thank you for this excellent module!!
> Correct typo in docs: invalid_sequence -> unexpected_sequence

- lib/ssh/src/ssh_connection.erl
- fixes race condition between connection closing and window adjustment
> ssh: don't adjust window if connection seems closed

- lib/compiler/src/beam_ssa_type.erl
- system/doc/efficiency_guide/maps.md
Using the map syntax instead of `maps:put/3` is slightly more efficient in itself, but also reduces register shuffling and can open up for combining multiple adjacent map update operations into a single update operation.
> Inline safe calls to maps:put/3

- lib/tftp/doc/guides/getting_started.md
- lib/tftp/doc/guides/introduction.md
- lib/tftp/src/tftp.erl
- lib/tftp/src/tftp_engine.erl
- lib/tftp/src/tftp_logger.erl
- lib/tftp/test/tftp_SUITE.erl
Polish tftp docs and remove legacy dependencies
> Ingela/tftp polish/otp 19114

- lib/stdlib/src/edlin_context.erl
- lib/stdlib/test/edlin_context_SUITE.erl
Distinguish between tuple and record
Solves GH-8626
> stdlib: fix completion bug

- lib/stdlib/src/gen_statem.erl
- lib/stdlib/test/gen_statem_SUITE.erl
> Use the pre cached callback_mode value for logger

- erts/emulator/beam/beam_types.h
- erts/emulator/test/trace_sessions.erl
- erts/test/otp_SUITE.erl
- lib/compiler/internal_doc/cerl-notes.md
- lib/dialyzer/test/indent_SUITE_data/src/record_send_test.erl
- lib/dialyzer/test/r9c_SUITE_data/src/asn1/asn1rt_per.erl
- lib/stdlib/uc_spec/README-UPDATE.txt
- lib/xmerl/test/xmerl_xsd_Sun2002-01-16_SUITE.erl
> Fix typos and improve language

- lib/ftp/src/ftp_internal.erl
> ftp: Solve possible race condition

- lib/common_test/doc/Makefile
- lib/common_test/src/ct.erl
- lib/common_test/src/ct_cover.erl
- lib/common_test/src/ct_ftp.erl
- lib/common_test/src/ct_hooks.erl
- lib/common_test/src/ct_master.erl
- lib/common_test/src/ct_property_test.erl
- lib/common_test/src/ct_rpc.erl
- lib/common_test/src/ct_slave.erl
- lib/common_test/src/ct_snmp.erl
- lib/common_test/src/ct_ssh.erl
- lib/common_test/src/ct_suite.erl
- lib/common_test/src/ct_telnet.erl
- lib/common_test/src/ct_testspec.erl
- lib/common_test/src/unix_telnet.erl
- lib/ssh/src/ssh_connection.erl
This polishes the documentation of common test further. Hopefully this is the last missing bit.
> Michal/common test/docs continuation

- lib/stdlib/src/json.erl
- lib/stdlib/test/json_SUITE.erl
To aid debugging or storing a readable file, some sort of formatter is needed.
@michalmuskala
> Add a formatter to json

- lib/jinterface/doc/guides/jinterface_users_guide.md
Stupid copy & paste didn't work 😅
> Fix a syntax error in example Java code

- erts/doc/guides/match_spec.md
- erts/emulator/beam/erl_db_util.c
- erts/emulator/test/trace_session_SUITE.erl
> Fix enable process trace flags with match spec in new API

- lib/crypto/c_src/algorithms.c
> Fix crypto:strong_rand_bytes on Ubuntu pro FIPS

- erts/preloaded/src/erlang.erl
> Fixed small typo in hibernate/3 doc

- lib/compiler/src/beam_ssa_opt.erl
- lib/compiler/test/beam_ssa_SUITE.erl
> beam_ssa_opt: Intersect CSE candidates on failure path

- lib/tools/src/cover.erl
- lib/tools/test/cover_SUITE.erl
> cover: Fix lines wrongly reported as uncovered

- system/doc/reference_manual/expressions.md
I'm not familiar with the word "succient" and have to think the intended word here is "succinct".
> doc: Change succient to succinct

- .github/workflows/osv-scanner-scheduled.yml
- lib/compiler/scripts/smoke-build/mix.lock
- lib/compiler/scripts/smoke-mix.exs
Adds vulnerability scanning to PRs and cron job
> github: add OSV automated vulnerability checking

- lib/dialyzer/src/erl_bif_types.erl
- lib/dialyzer/test/small_SUITE_data/results/logical_processors
- lib/dialyzer/test/small_SUITE_data/src/logical_processors.erl
> dialyzer: update erlang:system_info logical_processors type

- lib/compiler/src/compile.erl
- lib/compiler/test/compile_SUITE.erl
- lib/compiler/test/compile_SUITE_data/embedded_line_coverage.erl
> Make option line_coverage work when given in the compile() attribute

- lib/crypto/c_src/algorithms.c
> Fix deadlock race in crypto:supports(curves)

- .github/workflows/main.yaml
- scripts/scan-code.escript
- scripts/scan-code/template.txt
Adds a compliance check for new files
> github: add license compliance checks per PR

- .github/workflows/upload-windows-zip.yaml
- erts/etc/win32/INSTALL.txt
- lib/asn1/test/asn1_SUITE_data/SwCDR.asn1config
- lib/asn1/test/test_exclusive_decode_rest.erl
- lib/compiler/test/beam_doc_SUITE_data/behaviours.erl
- lib/compiler/test/beam_doc_SUITE_data/source_annotations.erl
- lib/compiler/test/beam_doc_SUITE_data/source_path.erl
- lib/stdlib/test/erl_lint_SUITE_data/bad_behaviour3.erl
- lib/stdlib/test/escript_SUITE_data/bypass_unicode_conversion
These license changes are to files for OTP-28
> otp: adds licenses to files that require it

- lib/dialyzer/src/dialyzer.hrl
- lib/dialyzer/src/dialyzer_contracts.erl
- lib/dialyzer/src/dialyzer_dataflow.erl
- lib/dialyzer/src/dialyzer_options.erl
- lib/dialyzer/test/opaque_SUITE_data/src/para/para6.erl
- lib/dialyzer/test/opaque_SUITE_data/src/para/para7.erl
Fix https://github.com/erlang/otp/issues/9140.
> dialyzer: fix issues related to opaques

- lib/ssh/src/ssh_system_sup.erl
- remove Role argument from start_link function
- try to remove {ok, _ChildPid, _Info} clause
> ssh: refactor ssh_system_sup

- README.md
[The list from erlang-punch](https://github.com/erlang-punch/awesome-erlang) is a fork of the David Robakowski's; the David Robakowski list has not been updated since 2018, whereas the erlang-punch list is actively maintained.
Cc: @niamtokik
> `README.md`: use the Awesome-Erlang list from erlang-punch

- lib/stdlib/src/epp.erl
- lib/stdlib/test/epp_SUITE.erl
> epp: Correct stringification of non-latin1 atoms

- lib/stdlib/src/edlin_type_suggestion.erl
> stdlib: cache code:get_docs calls when completing types in the shell

- erts/emulator/internal_doc/GarbageCollection.md
Noticed a minor typo in the garbage collection docs. This PR corrects it.
> Fix typo in GarbageCollection.md

- lib/stdlib/src/calendar.erl
- lib/stdlib/test/calendar_SUITE.erl
> Fix `calendar:rfc3339_to_system_time` handling of fractional seconds

- lib/kernel/src/group.erl
- lib/stdlib/test/io_proto_SUITE.erl
> erts: Fix reply to invalid requests in group

- lib/stdlib/src/erl_lint.erl
- lib/stdlib/test/erl_lint_SUITE.erl
> Revert "stdlib: Add warning for inlined nifs without loading"

- CONTRIBUTING.md
- README.md
Adds license inquiry information to the public
> otp: add license inquiry information

- lib/public_key/src/pubkey_cert.erl
Consider keyCertSign to compatible with extended key usage for TLS client/server auth in CAs
closes #9208
> public_key: Adjust certificate key usage compatible check

- lib/kernel/src/socket.erl
This PR fixes erroneous type specs introduced in #8986
> socket: fix typespecs

- lib/stdlib/src/gen_server.erl
As discussed with @RaimoNiskanen in #9287. I may have gone a little over the top, though... :sweat_smile:
> Restructure `gen_server` functions and calls

- scripts/scan-code.escript
inadvertently #9316 change the format of the scan-code escript that produces sarif files.
This PR makes the sarif generation to work again.
It also adds type specs to document the expected input/return types
> otp: fix broken sarif generation

- .gitignore
> Gitignore armv8l compiler outputs

- erts/doc/references/erlc_cmd.md
> doc: adjust ERLC_EMULATOR documentation after PR-8937

- lib/stdlib/src/gb_sets.erl
- lib/stdlib/src/ordsets.erl
- lib/stdlib/src/sets.erl
- lib/stdlib/test/sets_SUITE.erl
Ensure that the first sentence describing each function makes sense by itself when shown in the Summary part of the documentation.
Add examples for all functions.
While at it, also remove comments for documented functions, and remove out-commented code, and do some other minor clean ups.
> Polish documentation for the sets modules

- lib/stdlib/src/binary.erl
- lib/stdlib/src/gb_sets.erl
- lib/stdlib/src/lists.erl
- lib/stdlib/src/ordsets.erl
- lib/stdlib/src/sets.erl
- lib/stdlib/src/shell_docs_test.erl
- lib/stdlib/test/sets_SUITE.erl
* Support testing of exceptions.
* Print clearer information when a doctest fails.
* Print clearer information about functions that lack doctests.
> Enhance doctests

- lib/ssl/src/ssl_handshake.erl
Might add some more refactoring commits before merge, but so I do not forget.
> Remove dead code

- lib/ssl/test/ssl_api_SUITE.erl
- lib/stdlib/src/gen_statem.erl
- lib/stdlib/src/stdlib.app.src
- lib/stdlib/test/gen_statem_SUITE.erl
Fixes small flaws in `gen_statem`'s hibernation handling, and stops using selective receive when cancelling time-outs.
Initiated by PR #9287.
> `gen_statem` fixes

- erts/emulator/beam/erl_proc_sig_queue.c
- erts/emulator/test/signal_SUITE.erl
- erts/emulator/test/trace_SUITE.erl
> Priority message fixes

- lib/stdlib/src/digraph_utils.erl
They contain useful examples and algorithms
to make the operations easier to understand.
> Add wikipedia links to digraph_utils

- lib/stdlib/src/gen_server.erl
- lib/stdlib/test/gen_server_SUITE.erl
#9287 introduced a bug such that a `system` message would cancel (instead of restart) a "plain" timeout.
> Fix `gen_server` plain timeouts being canceled by `system` messages

- lib/ssl/src/ssl_crl_cache.erl
- lib/ssl/test/make_certs.erl
- lib/ssl/test/openssl_stapling_SUITE.erl
- lib/ssl/test/ssl_crl_SUITE.erl
> ssl: Use unique identifier for CRL db

- .github/scripts/otp-compliance.es
Adds dependencies `DOCUMENTATION_OF` and `TEST_OF` to the SBOM to separate running code from documentation and tests. ideally, all code outside of documentation and tests have licenses and copyrights, while we know there is some NOASSERTION for some tests and documentation.
> add DOCUMENTATION_OF and TEST_OF to SBOM

- lib/ssl/src/ssl_logger.erl
- lib/ssl/src/tls_gen_connection_1_3.erl
- lib/ssl/test/ssl_key_update_SUITE.erl
Fix that each keylog item should be one line
> ssl: Correct TLS-1.3 traffic keylog item

- .github/workflows/main.yaml
The changes output is a list of things that has changed, so we need to match on != `[]`.
> gh: Fix skipping of c code (again)

- lib/ssh/src/ssh_message.erl
> ssh: be less strict decoding SSH_MSG_IGNORE

- lib/kernel/src/logger.erl
- lib/kernel/test/logger_SUITE.erl
Fixed stuff discussed in #9436 and few more things that I noticed during tests.
Changes:
1. Added documentation about `simple` handler in `logger:reconfigure/1`. Should it be mentioned anywhere else? Perhaps in some guide?
2. Differences between `logger:add_handlers/1` and `logger:add_handler/3`
1. Default `filters` and `filter_default` were not applied to `default` through `add_handler/3`, but were through `add_handlers/1` - this is pushed down into `add_handler/3`.
2. `simple` handler wasn't removed through `add_handler/3`, but was through `add_handlers/1`. This is also pushed down into `add_handler/3`.
3. `simple` handler in `logger:reconfigure/0` is removed before other handlers are removed. That ensures that no log events are lost while removing previous handlers and ensures that …
> fix: simple handler

- .github/scripts/otp-compliance.es
- .github/workflows/main.yaml
Adds NTIA minimum requirements checker and format the output of tests, so that it is easy to spot which test failed.
> adds ntia minimum requirements checker

- erts/test/erlexec_SUITE.erl
> erts: Fix erlexec long path test in docker

- make/ex_doc.exs
> Fix mermaid after ex_doc upgrade and bumb its version

- lib/compiler/src/beam_ssa_alias.erl
- lib/compiler/test/core_alias_SUITE.erl
Fix https://github.com/erlang/otp/issues/9715.
> compiler: Fix bug with unloaded nifs in alias analysis

- lib/wx/api_gen/gl_gen_erl.erl
- lib/wx/src/gen/gl.erl
Use correct variable, gl nif was never loaded
> wx: build fixup

- .github/scripts/sync-github-releases.sh
Using variables as input into curl json is a bad idea, so we create a file on disk instead and use that to patch the body of the release.
closes #9856
> gh: Fix sync of descriptions with strange bash quotings

- lib/crypto/c_src/algorithms.c
- lib/crypto/c_src/algorithms.h
- lib/crypto/c_src/atoms.c
- lib/crypto/c_src/atoms.h
- lib/crypto/c_src/bn.c
- lib/crypto/c_src/bn.h
- lib/crypto/c_src/cipher.c
- lib/crypto/c_src/common.h
- lib/crypto/c_src/crypto.c
- lib/crypto/c_src/evp.c
- lib/crypto/c_src/evp.h
- lib/crypto/c_src/openssl_config.h
- lib/crypto/c_src/pkey.c
- lib/crypto/c_src/pkey.h
- lib/crypto/src/crypto.erl
- lib/crypto/test/crypto_SUITE.erl
> crypto: Add Quantum Safe algorithms ML-DSA and ML-KEM

- lib/kernel/doc/guides/socket_usage.md
- lib/kernel/src/socket.erl
For all functions (in the socket module) that can take the 'nowait' argument,
add a small section in the documentation describing all the possible values of CompletionStatus.
> CompletionStatus doc improvements

- lib/ssl/src/ssl.erl
- lib/ssl/src/ssl_config.erl
- lib/ssl/src/ssl_pem_cache.erl
- lib/ssl/test/ssl_api_SUITE.erl
- lib/ssl/test/ssl_api_SUITE_data/cert.pem
- lib/ssl/test/ssl_api_SUITE_data/enc_key.pem
- lib/ssl/test/ssl_pem_cache_SUITE.erl
> Ingela/ssl/early fail certfile/otp 19706

- lib/ssl/src/dtls_socket.erl
- lib/ssl/test/dtls_api_SUITE.erl
> Correct sockname handling for DTLS

- lib/inets/examples/server_root/cgi-bin/printenv.bat
- lib/inets/examples/server_root/cgi-bin/printenv.sh
- lib/inets/src/http_server/httpd_script_env.erl
- lib/inets/test/httpd_SUITE.erl
This PR fixes CVE-2016-1000107.
Closes #6223 and #3392
> Fix for httpd CGI scripts

- .github/scripts/create-openvex-pr.sh
Create a PR even if no PR exists
> create a PR for OpenVEX is none is found
