erlang/otp

lib/inets/doc/src/http_uri.xml
lib/inets/src/http_lib/http_uri.erl
lib/inets/test/uri_SUITE.erl

This fixes a bug in httpc where redirection URIs could lead to bad requests if they contained fragments.

Properly parse URI fragments

---

lib/os_mon/c_src/memsup.c

Some of the structs and functions needed by memsup.c are in vmmeter.h on OpenBSD, too.

Fix compile breakage on OpenBSD

---

erts/emulator/hipe/hipe_arm_bifs.m4
erts/emulator/hipe/hipe_arm_glue.S

HiPE on ARM is currently severely broken if the rest of the VM is
compiled to run in Thumb mode -- calling native code quickly ends
up executing code in the wrong mode and crashing the VM.  This is
a problem on e.g. Ubuntu which configures its system GCC to generate
Thumb by default.  It can also be triggered by overriding CC or
CFLAGS when compiling the VM.
There were three issues that caused the breakage:
1. Assembly-coded functions in hipe_arm_glue.S weren't explicitly
tagged as functions, preventing the linker from generating the
correct mode-switching call instructions for calls from C to
these functions.
Fixed by tagging those symbols as functions.
2. A few BIF wrappers were so simple that they performed tailcalls
to the C BIFs.  This fails to switch mode when C is in Thumb.
Fixed …

HiPE: fix ARM/Thumb interworking

---

lib/hipe/ppc/hipe_rtl_to_ppc.erl
lib/hipe/rtl/hipe_rtl.erl
lib/hipe/sparc/hipe_rtl_to_sparc.erl
lib/hipe/x86/hipe_rtl_to_x86.erl

The following test case crashes the HiPE compiler on all targets except ARM:
==snip==
-module(trivial_13).
-export([test/0]).
test() -> return_it(42).
return_it(X) -> R = (2 * X) / 2, round(R).
==snip==
This actually triggers two independent bugs:
RTL produces an #fconv{} instruction with an immediate operand, but the backends unconditionally access the operand as a temporary. This results in broken representation in the backends and eventually they crash. In this case, the bug is in the backends.
The backends must check for immediate operands in #fconv{} and translate them accordingly for their respective targets.
With the above fixed the backends still crash, generally with complaints about inconsistent and/or incomplete register allocation. This happens because …

HiPE fconv and fmove fixes

---

lib/inets/src/http_client/httpc_cookie.erl
lib/inets/test/httpc_SUITE.erl

Parsing invalid 'Set-Cookie' header would make httpc crash.
This commit filters invalid 'Set-Cookie' headers so that httpc wouldn't try parse them.

httpc: Avoid parsing invalid 'Set-Cookie' headers

---

lib/mnesia/doc/src/mnesia.xml
lib/mnesia/src/mnesia_controller.erl
lib/mnesia/src/mnesia_dumper.erl
lib/mnesia/src/mnesia_loader.erl
lib/mnesia/src/mnesia_monitor.erl

Setting the new Mnesia parameter 'dump_disc_copies_at_startup' to
'false' will completely disable the DCD dumping while tables are being
loaded. If it is set to 'true' (the default), the same test will now
be performed as for normal dumps, i.e., using the 'dc_dump_limit'
parameter. Previously, the test performed at load time was different
from the one used at runtime, and caused a lot of unnecessary dumping
which slowed down the startup.
If a DCD dump is desired on-demand, use the function
mnesia_controller:snapshot_dcd(Tables). Tables must be a list of
tables that have a local disc_copy, otherwise an error will be
returned. Once the operation actually executes, any table that doesn't
have a local disc_copy is ignored.
Specifically, the dump_log worker record has been changed to allow an …

Make Mnesia DCD dump behaviour available via configuration and API

---

lib/mnesia/doc/src/Mnesia_chap5.xmlsrc
lib/mnesia/doc/src/mnesia.xml

Return values for mnesia:(un)subscribe/1 was missing in documentation.

  Fix xml doc return value mnesia:(un)subscribe

---

lib/mnesia/doc/src/mnesia.xml

{index, [2]} refers to #person.name rather than #person.address, which
caused a little confusion in #erlang today.
{index, [4]} is the correct "hard coded" field for #person.address.

Fix index for #person.address in create_table/2

---

lib/common_test/src/ct_cover.erl
lib/common_test/test/ct_cover_SUITE.erl
lib/common_test/test/ct_cover_SUITE_data/cover_SUITE.erl

It seems like the commit 5a3c4668908254ee930c8db2e5cf9741945f9b2b also
broke the incl_dirs option and friends when given as relative paths.
When a cover spec contains a relative path it is looked-up in the
directory with the test results, not in the .cover file directory.

[ct_cover] Fix paths of incl_dirs in cover spec

---

lib/eldap/src/eldap.erl

Previously, it was impossible to set anon_auth to true. Making it
difficult to anonymously bind:
1> {ok, Conn} = eldap:open(["localhost"], [{anon_auth, true}]).
{ok,<0.34.0>}
2> eldap:simple_bind(Conn, "", "").
{error,anonymous_auth}
With this change:
1> {ok, Conn} = eldap:open(["localhost"], [{anon_auth, true}]).
{ok,<0.34.0>}
2> eldap:simple_bind(Conn, "", "").
ok
NB: Users could previously work around this by calling simple_bind as
follows:
eldap:simple_bind(Conn, anon, anon)

Correctly process anon_auth option for eldap:open()

---

lib/edoc/src/edoc_extract.erl
lib/syntax_tools/src/erl_prettypr.erl
lib/syntax_tools/src/erl_syntax.erl
lib/syntax_tools/src/erl_syntax_lib.erl
lib/syntax_tools/src/erl_tidy.erl
lib/syntax_tools/src/igor.erl

Mnemosyne rule syntax is no longer supported in Erlang. This removes the corresponding support in syntax tools.

Remove mnemosyne rules support from syntax_tools

---

lib/kernel/src/gen_udp.erl

It's documented but not exported, that got me confused.

Export type gen_udp:socket/0.

---

lib/stdlib/src/erl_lint.erl
lib/stdlib/test/erl_lint_SUITE.erl

The returned variable table when linting a map expression shouldn't include variables that didn't appear in the expression.
@alco

Properly lint map expressions in erl_lint

---

lib/stdlib/src/erl_lint.erl

Given any Vt1 and Vt2 values, vtmerge(vtnew(Vt1, Vt2), vtold(Vt1, Vt2)) is always equal to Vt1.

Remove a few superfluous vt operations in erl_lint

---

lib/stdlib/doc/src/re.xml

Behaviour of character types \d, \w and \s has always been to not match characters with value above 255, not 128, i.e. they are limited to ISO-Latin-1 and not ASCII.

Fix documentation about character types in unicode mode

---

lib/kernel/doc/src/inet.xml

The changes should be pretty straightforward. Let me know if I have change anything for this to be merged.

Fix typos in inet:getstat/1,2 documentation

---

lib/stdlib/src/ets.erl

The standard_input may be set to binary mode via `io:getopts/2`
and in such cases `ets:i/0` and `ets:i/1` get stuck as
they are unable to match new lines in binaries.
This is similar to previous changes seen in commits 2db2f977598dab05dc125acdc478c375cb66ddb8 and 4525bc59822acf0dfffa1edc64125c180d29e59e.

Support binary standard input in ets:i/1

---

erts/emulator/beam/beam_load.c
erts/emulator/beam/big.c
erts/emulator/beam/erl_bits.c
erts/emulator/beam/external.c
erts/emulator/test/big_SUITE.erl

Bignums are artifically restricted in size.  Arithmetic and logical
operations check the sizes of resulting bignums, and turn oversize
results into system_limit exceptions.
However, this check is not performed when bignums are constructed by
binary matching.  The consequence is that such matchings can construct
oversize bignums that satisfy is_integer/1 yet don't work.  Performing
arithmetic such as Term - 0 fails with a system_limit exception.  Worse,
performing a logical operation such as Term band Term results in [].
The latter occurs because the size checking (e.g. in erts_band()) is
a simple ASSERT(is_not_nil(...)) on the result of the bignum operation,
which internally is [] (NIL) in the case of oversize results.  However,
ASSERT is a no-op in release builds, so the error goes …

don't create oversize bignums in binary matching

---

erts/emulator/hipe/hipe_bif0.c

The hipe_mfa_info_table lock is currently a mutex, causing
unnecessary contention and serialization of lookups for
apply-like constructs.
- change the lock from a mutex to an rwmutex
- split hipe_get_na_nofail_locked into a "try" path which
only needs a read-lock, and a "slow" path which requires
a write-lock
- reimplement hipe_get_na_nofail (used by apply ops etc) to
first call the "try" path with a read lock, and if that
fails the "slow" path with a write lock
- reimplement hipe_get_na_nofail_locked (used by maintenance
code) to call the "try" path and then optionally the "slow"
path, but without taking locks since its caller already has
the write lock
- adjust remaining lock ops to take/release full write-lock
- change hipe_mfa_get_trampoline to call get_locked not put_locked,
allowing …

hipe: change mfa_info_table lock to rwmutex

---

lib/stdlib/doc/src/zip.xml
lib/stdlib/src/zip.erl
lib/stdlib/test/zip_SUITE.erl

The case was discovered where a parent process would exit before closing
the zip file. The result was that a port would be left open
indefinitely, as the small zip server would not detect this condition.
By comparison, the file module will close the associated port when the
parent exits for any reason. This change would make the zip module more
consistent with the semantics of similar modules.
This change is breaking for any callers expecting to pass the handle to
another process for processing (assuming it exits).
With this in mind, it may need a bit more thought with regards to:
1. Is this the best way to cope with a parent process exiting?
2. Should an equivalent of `gen_tcp:controlling_process/2` to deal with
migrating an open zip to another process?
3. If backwards compatibility is …

Prevent zip:zip_open/1,2 from leaking ports

---

erts/doc/src/zlib.xml
erts/preloaded/src/zlib.erl
lib/kernel/test/zlib_SUITE.erl

Commit 7e8f5a776cbfa376e03369d058a90c8dd9f217fc (importing R11B-3)
updated zlib, which had changed what values it accepts for window
bits from 9-15 to 8-15.
From deflate.c:
``` c
-        windowBits < 9 || windowBits > 15 || level < 0 || level > 9 ||
-   strategy < 0 || strategy > Z_HUFFMAN_ONLY) {
+        windowBits < 8 || windowBits > 15 || level < 0 || level > 9 ||
+        strategy < 0 || strategy > Z_FIXED) {
return Z_STREAM_ERROR;
}
+    if (windowBits == 8) windowBits = 9;  /* until 256-byte window bug fixed */
```
In inflate.c 8 was already an accepted value.
This commit updates OTP to also accept the values 8 and -8.
----------------------------------
This PR makes the zlib interface closer to the original.
The 8 value as you can see is set to 9 by zlib. They have a bug …

Update zlib:zwindowbits/0 type to accept 8 and -8

---

lib/eldap/doc/src/eldap.xml

Prior to this commit the eldap docs mistakenly referenced an atom of
`inifinity` for a possible timeout value. This commit corrects the
timeout value to `infinity`.

fix `infinity` typo in eldap docs

---

erts/emulator/drivers/common/efile_drv.c

All uses of these macros were removed in
commit c3a615aa2da09bc3a0575e973959f800460a63de.

Remove unused time macros from efile_drv

---

lib/inets/src/http_client/httpc_cookie.erl

Looks like previous spec of this function was just a copy-paste of the previous one

Minor comment fix

---

erts/preloaded/src/zlib.erl

Didn't add zmethod() because it can't be configured and so it is not very useful to have outside this module. However the four I add can very well be arguments to functions or configuration options and so it is interesting to have those types exported.

Export useful types from zlib module

---

.gitignore
lib/tools/emacs/erlang.el

The tag completion code was changed in GNU Emacs 23.1 in a way that
broke erlang.el tag completion.  This commit fix that for Emacs 23.1 and
later.
Add progress report while building completion table.
Add completion of module_info/0 for all modules.
Add lib/tools/emacs/*.elc to .gitignore.

Fix tags completion in erlang.el for GNU Emacs 23+

---

erts/emulator/beam/io.c
erts/emulator/test/port_bif_SUITE.erl

This variable hold the values returned by erlang:port_info/1 and shouldn't be static.
@Licenser

Fix a race condition when calling port_info

---

lib/jinterface/doc/src/jinterface_users_guide.xml
lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractConnection.java
lib/jinterface/java_src/com/ericsson/otp/erlang/AbstractNode.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpConnection.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpCookedConnection.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpEpmd.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpLocalNode.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpNode.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpOutputStream.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpPeer.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpSelf.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpServerSocketTransport.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpServerTransport.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpSocketTransport.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpSocketTransportFactory.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpTransport.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpTransportFactory.java
lib/jinterface/java_src/com/ericsson/otp/erlang/java_files
lib/jinterface/test/jinterface_SUITE.erl
lib/jinterface/test/jinterface_SUITE_data/Makefile.src
lib/jinterface/test/jinterface_SUITE_data/TransportFactoryTest.java
lib/jinterface/test/jitu.erl

This change makes possible to implement custom transport(s) in Java node participating in distributive Erlang system. One use case may be creating ssh-tunneling.

Jinterface transport factory

---

lib/jinterface/java_src/com/ericsson/otp/erlang/OtpErlangList.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpErlangMap.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpErlangObject.java
lib/jinterface/java_src/com/ericsson/otp/erlang/OtpErlangTuple.java
lib/jinterface/test/jinterface_SUITE.erl
lib/jinterface/test/jinterface_SUITE_data/CoreMatchBind.java
lib/jinterface/test/jinterface_SUITE_data/Makefile.src
lib/jinterface/test/jitu.erl

The proposed change facilitates implementing pattern matching and variable binding in the JInterface library. Particular implementations may vary, but proposed change provides low level interface base methods. Changes are backward compatible. Test cases added.

Jinterface generic match and bind methods

---

lib/test_server/doc/src/example_chapter.xml
lib/test_server/doc/src/test_server.xml

Undocument the line macro in test_server

---

lib/eunit/include/eunit.hrl
lib/eunit/src/eunit.erl
lib/eunit/src/eunit_data.erl
lib/eunit/src/eunit_internal.hrl
lib/eunit/src/eunit_lib.erl
lib/eunit/src/eunit_proc.erl
lib/eunit/src/eunit_surefire.erl
lib/eunit/src/eunit_tty.erl
lib/eunit/test/Makefile
lib/eunit/test/eunit_SUITE.erl
lib/eunit/test/tlatin.erl
lib/eunit/test/tutf8.erl

The most critical part is eunit_surefire, because the generated XML
must be correct UTF-8, otherwise tools will refuse to work with it.

OTP-11660: make eunit unicode safe

---

lib/stdlib/doc/src/c.xml
lib/stdlib/src/c.erl
lib/stdlib/src/shell_default.erl

Inspired by http://erlang.org/pipermail/erlang-questions/2010-March/050078.html

Add uptime() shell command

---

erts/emulator/sys/unix/erl_child_setup.c

The Android support in erl_child_setup.c is broken:
1. The close fd loop compares an fd (integer i) with the address of the function
__system_properties_fd rather than the value of calling that function.
2. This function is locally defined, but its name starts with two underscores
which is reserved for the implementation.
3. This function is not used outside of this file, so should be static.
4. This function performs a fair amount of work (calls getenv and atoi), which
would be repeated for each and every fd in the [from,to] range.
5. This function contains an unsed local variable 's'.
Fixed by dropping the __ prefix, making the function static, dropping the unused
local variable, and rewriting the close fd loop to call the function at most once.

erl_child_setup.c: fix Android breakage

---

lib/jinterface/java_src/com/ericsson/otp/erlang/OtpSelf.java

This gives an error when building the docs.

Remove extra @param in javadoc

---

lib/stdlib/src/erl_anno.erl

Compilation on Erlang 18.0-rc2 is about 10% slower than in Erlang 17.
After some debugging, we have noticed that linting is on average 30%
to 50% slower being the main responsible for the performance reduction.
Later profiling revealed is_filename/1 to be the biggest culprit. The change
in this commit brings compilation times to about the same times as Erlang 17.
Note this commit doesn't change the compiler behaviour compared to Erlang
17 because we didn't sanity check the value given to the file annotation in the
past. I would say checking the filename is not worth it if it means compilation
becomes 10% slower on average. After all, there are many places in the
compiler where it will fail if we give it a malformed tree, I wouldn't then special
case file annotation.

Speed up linting by not traversing filenames in erl_anno

---

lib/kernel/src/application_controller.erl

It just struck me to check if this ETS table was configured for concurrent accesses, and sure enough, it wasn't. I think that read_concurrency (but not write_concurrency) should be a good match for the typical access pattern in an Erlang/OTP system.

Use read_concurrency for application environment

---

erts/emulator/beam/erl_node_tables.c
erts/etc/ose/run_erl.c

I'd really like a pair of eyes on this one, since my C is still rusty, but I think I've verified everything to be correct. Essentially this is a semantic search over the source code base for these kinds of errors, and I found three errors, where I manually corrected 2 of them, but I don't know the context fully, so I may have made a mistake.
One fix is in the OSE code, the other two pertains to buffer sizes in `erts_snprintf()` calls in the erl_node_tables.c code.

Correct usage of sizeof() for pointer types.

---

lib/hipe/cerl/cerl_pmatch.erl

The cerl_pmatch module performs pattern matching compilation at the
level of Core Erlang.  Functions that were not needed by the HiPE
compiler were ifdef-ed out.  However, these functions may come handy
to other users; in particular a new testing tool currently under
development needs access to these functions.
While at it, added specs for these exported functions and also
strengthened the spec of another one.

Allow use of complete interface of cerl_pmatch module

---

lib/stdlib/src/erl_lint.erl

This is a follow up to commit b5ee5c6.
Similar to function calls, we also need to annotate used types
on call site since this information is used later on when showing
undefined type errors.
Notice we don't need to annotate the type export because
it is an attribute and those are always properly annotated.

Annotate used types in erl_lint

---

erts/emulator/drivers/common/inet_drv.c
erts/preloaded/src/prim_inet.erl
lib/kernel/doc/src/gen_tcp.xml
lib/kernel/test/gen_tcp_api_SUITE.erl

If the driver queue is empty, or the user is requesting a 'read'
shutdown, then the shutdown() syscall is performed synchronously, as
per the old version of shutdown/2.
However, if the user is requesting a 'write' or 'read_write' shutdown,
and there is data in the driver queue for the socket, then the
shutdown() syscall is delayed and handled asynchronously when the
driver queue is written out.
This version of shutdown solves a number of issues with the old
version. The two main solutions it offers are:
* It doesn't block when the TCP peer is idle or slow. This is the
expected behaviour when shutdown() is called: the caller needs
to be able to continue reading from the socket, not be prevented
from doing so.
* It doesn't truncate the output. The current version of
gen_tcp:shutdown/2 will …

Fix gen_tcp:shutdown/2 by making it asynchronous

---

lib/eunit/src/eunit_server.erl
lib/eunit/src/eunit_surefire.erl
lib/eunit/vsn.mk

Previously forgotten contribution by Andreas Amsenius:
Improve surefire xml <testcase> element
Remove the 'description' attribute. It is not generated by Apache
Ant or Maven Surefire and probably ignored by all other Surefire
tools. Confirmed for Jenkins.
Add testcase description (if there is one) to the 'name' attribute.
Change format of 'name' attribute to look more like the output from
running eunit with verbose. Line number and arity was quite obscure
and arity is not useful as it is always 0.

Eunit 2.2.10

---

lib/inets/src/http_client/httpc_handler.erl

httpc_handler should respond with proper {stop, Reason, State}
message when sending request from keep-alive queue fails

inets: proper stop for httpc_handler keep-alive queue failure

---

lib/xmerl/src/xmerl.erl
lib/xmerl/src/xmerl_eventp.erl
lib/xmerl/src/xmerl_otpsgml.erl
lib/xmerl/src/xmerl_regexp.erl
lib/xmerl/src/xmerl_sax_old_dom.erl
lib/xmerl/src/xmerl_sax_simple_dom.erl
lib/xmerl/src/xmerl_scan.erl
lib/xmerl/src/xmerl_ucs.erl
lib/xmerl/src/xmerl_validate.erl
lib/xmerl/src/xmerl_xml.erl
lib/xmerl/src/xmerl_xpath.erl
lib/xmerl/src/xmerl_xpath_pred.erl
lib/xmerl/src/xmerl_xsd.erl
lib/xmerl/src/xmerl_xsd_type.erl

Replace sloppy calls to io:format() in xmerl to use error_logger or debug
macros instead, as appropriate.

Stop xmerl printing to stdout

---

lib/hipe/main/hipe.erl
lib/kernel/src/code.erl
lib/kernel/src/code_server.erl
lib/kernel/src/hipe_unified_loader.erl
lib/kernel/test/code_SUITE.erl

Make code_server be responsible for finding the architecture and deciding whether to try to load native code, in order to avoid repeated calls to system_info(hipe_architecture) and clumsy uses of try/catch to test if hipe is enabled.

Move architecture knowledge out of hipe loader

---

lib/observer/src/observer_tv_wx.erl

Avoid refreshing the list of tables every refresh interval
(by default 10 secs) if the content did not change.
Because of the refresh the list was scrolled to the begining
and current selection was lost which could be quite anoying.

Don't refresh observer table view if there was no change

---

erts/doc/src/erl_nif.xml

In the documentation for erl_nif, in the map iterator example,
the iterator argument was forgotten in the call to function
enif_map_iterator_create. This is now fixed.

Add forgotten argument to example in erl_nif doc

---

lib/hipe/main/hipe.erl
lib/hipe/rtl/hipe_tagscheme.erl

Shut off three dialyzer warnings (two of them were introduced recently by merging a pull request) and simplify some code in the process.

HiPE no dialyzer warnings

---

lib/stdlib/doc/src/binary.xml
lib/stdlib/src/binary.erl
lib/stdlib/test/binary_module_SUITE.erl
lib/stdlib/test/binref.erl

As its name suggest, this option can be used to remove _ALL_ empty parts of the result of a call to binary:split/3.
```erlang
1> binary:split(<<"  1  2  3  ">>, <<$\s>>, [global]).
[<<>>,<<>>,<<"1">>,<<>>,<<"2">>,<<>>,<<"3">>,<<>>,<<>>]
2> binary:split(<<"  1  2  3  ">>, <<$\s>>, [global,trim]).
[<<>>,<<>>,<<"1">>,<<>>,<<"2">>,<<>>,<<"3">>]
3> binary:split(<<"  1  2  3  ">>, <<$\s>>, [global,remove_empty_parts]).
[<<"1">>,<<"2">>,<<"3">>]
```
This could be done with a simple list comprehension on the result, but I think it is a need common enough to justify this patch.

Add 'remove_empty_parts' option to binary:split/3

---

lib/public_key/doc/src/public_key.xml

Line number references are with respect to sources
in public_key.erl
Changes:
- pkix_sign    replaced public with private (L510)
(Certificates are signed by private keys)
- pki_asn1_type() added 'CertificateList'   (L73)
- pkix_sign_types added ecdsa               (L404)
- pkix_verify     added ec_public_key()     (L530)
- pkix_is_issuer  added 'CertificateList'   (L569)

Updated documentation to match implementation

---

lib/stdlib/doc/src/ets.xml

Minor typo in online docs. Tested in release 18:
58> TabId2 = ets:new(newtable, [named_table]).
60> ets:first(newtable).
'$end_of_table'
61> ets:first(newtable,2).
** exception error: undefined function ets:first/2

Fix function reference (no first/2 in ets)

---

lib/eunit/src/eunit_tty.erl

When having 1 test message reads, **Test passed.**
when having 5 tests, **All 5 tests passed.**
but when having only 2 tests, **All 2 tests passed.** sounds a bit odd.
Improved to say: **2 tests passed.** when dealing with only two tests.

Tests passed : little improvements

---

erts/emulator/beam/big.c
erts/emulator/test/num_bif_SUITE.erl

erlang:binary_to_integer/1 and /2 fail to detect invalid
input consisting of a single + or - sign but nothing else.
For an input like <<"+">> they return 0, while list_to_integer/1
correctly signals a badarg for "+".
Fixed by checking if the input is empty after the initial +/-
sign processing.
Added a test case which fails without this fix but passes with it.
Thanks to "niku" for reporting the issue.

erts: fix binary_to_integer boundary case

---

erts/emulator/beam/erl_nif_api_funcs.h

When compiling a nif module with `-Wall` and `enif_make_pid` is contained in a function like this...
```
inline ERL_NIF_TERM foo(ErlNifEnv *env, const ErlNifPid *pid)
{
return enif_make_pid(env, pid);
}
```
... the compile will produce this warning:
```
In file included from nifpptest.cpp:11:0:
../nifpp.h:394:13: warning: unused parameter ‘env’ [-Wunused-parameter]
```
This happens because `enif_make_pid` is implemented as a macro that does not use the `env` parameter.  This pull request adjusts the `enif_make_pid` macro to refer to the `env` param to make the warning go away.
This problem was observed while [cleaning up warnings on nifpp](https://github.com/goertzenator/nifpp/pull/5).

fix unused parameter warning in enif_make_pid

---

erts/doc/src/erlang.xml

Trying to reproduce the example of `list_to_bitstring/1` brings errors and/or different results (tested with R18):
http://www.erlang.org/doc/man/erlang.html#list_to_bitstring-1
This PR modifies the example in a way that works.

Typos in documentation example of list_to_bitstring/1

---

.travis.yml

Build takes around 20 minutes to finish (this means 30 more minutes can be spent checking things).
This will build then run the test suite (on a Docker image of Ubuntu).
Right now tests a ran but their output is not checked for correctness.
I need some insight into how I could fix that.
Anyway, I think this is a step towards opening OTP development to the community.
And activating @erlang's Travis CI account is free!

travis-ci: basic continuous integration with Travis CI

---

lib/eldap/src/eldap.erl

While at it, do a minor cleanup using is_boolean/1

Eliminate dialyzer warnings for unmatched_returns

---

erts/emulator/hipe/hipe_native_bif.c

These ifdef-ed lines were once upon a time needed, but the recent
changes in the time mechanism of OTP render them unused and result
in a warning on architectures which are not 64-bit.

Take out unused code that results in a gcc warning

---

lib/tools/emacs/erlang.el

In the Emacs Erlang mode, typing "->" will usually automatically add a
newline, which is usually what you want when writing a function, but
not when writing a type spec.  Therefore, there is a check for not
adding the newline when the current line starts with -spec or -type.
This change adds -callback to that check, since it is usually written
the same way as type specs.

Don't add newline after arrow on -callback lines

---

lib/observer/src/observer_sys_wx.erl

Several initialisms (eg, ERTS, ETS, SMP) are used as headings.  They were being capitalized incorrectly,

fix capitalization of headings

---

HOWTO/INSTALL.md

wxWidgets does not have a branch named `WX_3_0_branch`, but has
`WX_3_0_BRANCH` Trying to clone with `--branch` set to the lowercase
name fails. Fix branch name to `WX_3_0_BRANCH`.

Fix osx install wxWidgets instructions

---

lib/hipe/rtl/hipe_rtl_binary_construct.erl
lib/hipe/test/bs_SUITE_data/bs_construct.erl

copy_offset_int_big was assuming (Offset + Size - 1) (Tmp9 in the first
BB) would not underflow. It was also unconditionally reading and writing
the binary even when Size was zero, unlike copy_int_little, which is the
only other case of bs_put_integer that does not have a short-circuit on
Size = 0.
This was causing segfaults when constructing binaries starting with a
zero-length integer field, because a logical right shift was used to
compute an offset in bytes (which became 0x1fffffffffffffff) to read in
the binary.
Tests, taken from the emulator bs_construct_SUITE, were also added.
The complete credit for the report and the fix goes to Magnus Lång.

hipe: Fix corner case of Size = 0 in bs_put_integer

---

erts/preloaded/src/erlang.erl
lib/dialyzer/test/small_SUITE_data/results/fun_arity
lib/dialyzer/test/small_SUITE_data/src/fun_arity.erl
lib/hipe/cerl/erl_bif_types.erl

Please refer to commit message for details.
Pull request is based on the `maint` branch as per [guidelines in the wiki](https://github.com/erlang/otp/wiki/Submitting-patches#branching-out). I am happy to rebase to another branch if you prefer. (Actually I would prefer the patch to go in a 17.5.6.x release - I tested that the code changes work also on OTP 17.5.6.1.)
Further to this pull request, I would be glad if you provided me with hints on how to teach Dialyzer to:
1. Detect undefined funs `fun M:F/A` (literal M, F and A would be enough) - see [test](https://github.com/erlang/otp/blob/OTP-17.5.6.1/lib/dialyzer/test/small_SUITE_data/src/non_existing.erl#L12) ([not enforced](https://github.com/erlang/otp/blob/OTP-17.5.6.1/lib/dialyzer/test/small_SUITE_data/results/non_existing) by …

Teach Dialyzer arity of funs with literal arity

---

system/doc/efficiency_guide/binaryhandling.xml

- at appending when allocating new binary object its size will be
double (the old size + size of data to be appended)
not just double the old size
- correct some unused byte counts
...but I might be wrong

Very minor fixes to binary handling documentation

---

system/doc/tutorial/ei.c

Not sure why it was 17 there, especially considering the explanations above have the same lines with 3 instead. So I put 3 in the end snippet too.

Fix weird strncmp length in erl_interface example

---

lib/kernel/src/inet_db.erl

Don't let `inet_res:getbyname` and `inet_res:gethostbyname` calls return `{error, nxdomain}` if the host name capitalization in the DNS response differs from the request, like in this example:
1> inet_res:gethostbyname("erlang.org").
{ok,{hostent,"erlang.org",[],inet,4,[{192,121,151,106}]}}
2> inet_res:gethostbyname("Erlang.ORG").
{error,nxdomain}
This PR partly reverts commit 8152505ea3793037984a7f3349ac95cc20c4e44c.  Up to that commit, only the [initial lookup of a given host name was case-sensitive][1].  Once the result was cached, subsequent lookups were case-insensitive.  That commit changed the cache access to be [case][2]-[sensitive][3] as well.  This PR makes sure all lookups are performed in a case-insensitive manner.
[1]: …

inet_res: Make host name lookups case-insensitive

---

system/doc/reference_manual/processes.xml

erlang:fault no longer exists, so don't mention it in the reference manual.
Also fix minor markup issue in following paragraph.

Remove mention of erlang:fault

---

erts/emulator/sys/common/erl_poll.h

The presence of this symbol is libc-specific. In particular, it is absent from [musl][1]. The correct solution is to use uint32_t.
[1]: http://www.musl-libc.org/

Fix erroneous use of __uint32_t

---

lib/jinterface/java_src/com/ericsson/otp/erlang/OtpInputStream.java

Calling ```OtpInputStream.read_any()```  on a stream containing an external function term resulted in 
```
com.ericsson.otp.erlang.OtpErlangDecodeException: Uknown data type: 113
at com.ericsson.otp.erlang.OtpInputStream.read_any(OtpInputStream.java:1247)
```

jinterface: OtpInputStream: support external funs in read_any

---

erts/etc/common/ct_run.c
erts/etc/common/dialyzer.c
erts/etc/common/erlc.c
erts/etc/common/escript.c
erts/etc/common/typer.c

`ct_run.c`, `erlc.c`, `escript.c` and `typer.c` do not preserve space characters in the emulator path. Thus, if a path containing space is passed via environment variables, such as `ESCRIPT_EMULATOR`, or if `get_default_emulator(progname)` returns a path with space, the execution of the programs fail. This patch fixes all occurrences found with `grep push_words -R $ERL_TOP`.
**Reproducing the error**
The following example breaks the old implementation in `escript`:
cd /tmp
mkdir escript_bug
cd escript_bug/
mkdir path\ with\ space
cp /usr/bin/erl path\ with\ space/
cd path\ with\ space/
touch test.escript
cd ..
ESCRIPT_EMULATOR='/tmp/escript_bug/path with space/erl' escript "path with space/test.escript"
escript: Error 2 executing '/tmp/escript_bug/path'.
**Expected**
The example with the …

Fix erroneous splitting of emulator path

---

erts/etc/common/heart.c

The "if" referred to in the comment was removed in commit 70c9312c4b.

Remove obsolete comment in heart.c

---

lib/crypto/doc/src/crypto.xml
lib/ssh/doc/src/using_ssh.xml
lib/stdlib/doc/src/rand.xml
lib/stdlib/doc/src/random.xml

This pull request makes changes to the documentation to advise users against using crypto:rand_bytes for cryptographic purposes, and recommending crypto:strong_rand_bytes instead.
crypto:rand_bytes uses a deprecated function as a PRNG.
According to https://www.openssl.org/docs/manmaster/crypto/RAND_bytes.html, the Openssl function RAND_pseudo_bytes() has been deprecated, and Openssl advise users to use it for non-cryptographic purposes only. crypto:rand_bytes uses RAND_pseudo_bytes(), and so crypto:rand_bytes should probably either use a different PRNG or it should not be used for cryptographic purposes.

Updated documentation recommending against using crypto:rand_bytes

---

lib/inets/src/http_client/httpc_handler.erl
lib/inets/test/httpc_SUITE.erl

Without this fix, httpc:request/1 crashes the httpc_handler when an invalid chunked length header is encountered:
=ERROR REPORT==== 14-Nov-2015::17:19:30 ===
** Generic server <0.651.0> terminating
** Last message in was {tcp,#Port<0.5714>,
<<"HTTP/1.1 200 ok\r\nTransfer-Encoding:chunked\r\n\r\nåäö\r\n">>}
** When Server state == {state,
[...]
** Reason for termination ==
** {bad_return_value,{error,{chunk_size,"åäö"}}}
This is a fixup for commit 77acb47.

inets: Terminate really gracefully when an invalid chunked length header is encountered

---

lib/inets/src/http_lib/http_chunk.erl
lib/inets/test/http_format_SUITE.erl

Before 77acb47 http:request/1 could parse server responses with whitespace after the HTTP chunk size (some embedded legacy devices still do this).
This patch restores this functionality.

inets: Allow whitespace after HTTP chunk size again

---

lib/ssl/src/inet_tls_dist.erl
lib/ssl/src/ssl_dist_sup.erl

Change `ssl_dist_sup` to be considered as a supervisor with infinite shutdown time.
Change the `ssl_connection_dist` instance of `tls_connection_sup` to have infinite shutdown time.
This avoids spurious error messages when shutting down a node that uses distribution over TLS.

Adjust shutdown strategies for distribution over TLS

---

lib/ssl/src/ssl_internal.hrl
lib/ssl/src/ssl_manager.erl
lib/ssl/src/ssl_session.erl

The previous commit, merged here: https://github.com/erlang/otp/pull/386  fixed the macro only in one place. I moved the macro to the header file, which is included in both files. As far as I understand, with this bug, the server_id function was filtering out valid sessions, and as a result new sessions were created.  
By the way, I wonder if 24h is a sane default. I encountered an issue similar to this one:  https://github.com/ninenines/gun/issues/68. When I changed the session_lifetime option to 10 minutes, the memory stopped "leaking". I was making https requests to a service deployed on heroku. Unfortunately, I don't have the configuration details, but my guess is the server side has a much smaller session_lifetime.
As a result, when session resumption fails the session is not removed …

fix incorrect number of seconds in the 24h_in_sec macro

---

lib/ssl/src/ssl_tls_dist_proxy.erl

The `duplicate_name` error returned from `erl_epmd:register_node` elicits a
particularly precise error message from `net_kernel`, so let's pass it
along to our caller.
Not doing this for the other things that could go wrong here, since for
those having the line number will likely aid debugging.

In ssl_tls_dist_proxy, pass along EPMD registration errors

---

lib/ssl/src/ssl_tls_dist_proxy.erl
lib/ssl/test/ssl_dist_SUITE.erl

On Linux, not using this option leads to occasional latency of 40 ms,
the default delay for Nagle's algorithm.  Let's ensure packets flow
without delays by disabling that.
To reproduce this, first create a certificate and a private key:
```
openssl req \
-new \
-newkey rsa:4096 \
-days 365 \
-nodes \
-x509 \
-subj "/CN=foo" \
-keyout erldist.key \
-out erldist.cert
```
Set ERL_FLAGS to enable distribution over TLS:
```
export ERL_FLAGS="-pa $ERL_TOP/lib/ssl/ebin/ -proto_dist inet_tls \
-ssl_dist_opt server_certfile erldist.cert server_keyfile erldist.key"
```
Start two nodes:
```
erl -sname foo@localhost
erl -sname bar@localhost
```
Make a sequence of RPC calls from one node to the other:
```
Node = foo@localhost.
[element(1, timer:tc(rpc, call, [Node, erlang, self, []]))
|| _ <- …
```

In ssl_tls_dist_proxy, use nodelay for all sockets

---

lib/ssl/src/ssl_connection.erl

Starting an SSL connection with a nonexistent keyfile will obviously
return an error:
> ssl:connect("www.google.com", 443, [{keyfile, "nonexistent"}]).
{error,{options,{keyfile,"nonexistent",{error,enoent}}}}
But it also generates an error report with the following backtrace:
** Reason for termination =
** {badarg,[{ets,select_delete,
[undefined,[{{{undefined,'_','_'},'_'},[],[true]}]],
[]},
{ets,match_delete,2,[{file,"ets.erl"},{line,700}]},
{ssl_pkix_db,remove_certs,2,[{file,"ssl_pkix_db.erl"},{line,243}]},
{ssl_connection,terminate,3,
[{file,"ssl_connection.erl"},{line,941}]},
{tls_connection,terminate,3,
[{file,"tls_connection.erl"},{line,335}]},
{gen_fsm,terminate,7,[{file,"gen_fsm.erl"},{line,610}]},
{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,532}]}, …

Avoid crash for SSL connections with nonexistent keyfile

---

lib/kernel/src/file_io_server.erl
lib/kernel/test/file_SUITE.erl

When it called the "file:position", it subtract the size that was read into the buffer, and returns the value.
However, it has been discarded buffer and correct position is lost, if "file:postion" returns error.
So...
e.g.
```erlang
%% data ... <<"abcdefghijklmnopqrstuvwxyz">> (size: 26Bytes)
1> {ok, Fd} = file:open("data", [read, binary]).
{ok, <0.38.0>}
2> file:read(Fd, 5).
{ok, <<"abcde">>}
3> file:position(Fd, {bof, -1}).
{error, einval}
4> file:position(Fd, cur).
{ok, 27} %% skip !!
5> file:read(Fd, 1).
eof
```
I fix this.

Fix file:position (not raw mode)

---

lib/ssh/doc/src/ssh.xml
lib/ssh/src/ssh.erl
lib/ssh/test/Makefile
lib/ssh/test/ssh_basic_SUITE.erl
lib/ssh/test/ssh_key_cb.erl
lib/ssh/test/ssh_key_cb_options.erl

This patch allows extra callback options to be passed to the module
implementing the SSH callback module behaviour.
A module implementing the SSH key callback API is used to customize
the handling of public key. This patch allows extra callback options
to be passed to the module implementing the SSH callback module
behaviour.
The key_cb option has been changed:
{key_cb, atom()} -> {key_cb, key_cb()}
Where:
key_cb() :: atom() | {atom(), list()}
The callback options, if specified, is made available to the callback
module via the options passed to it under the key 'key_cb_private'.
More details and some backgorund is available here[1].
[1]: http://erlang.org/pipermail/erlang-patches/2015-November/004800.html

Support SSH key callback module options

---

lib/ssl/src/ssl_cipher.erl

TLS hash_sign algorithms may have proprietary values see
http://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml
We should add callbacks to let applications handle them.
But for now we do not want to crash if they are present and
let other algorithms be negotiated.

ssl: Do not crash on proprietary hash_sign algorithms

---

lib/ssl/src/ssl.erl
lib/ssl/test/ssl_basic_SUITE.erl

In Erlang R16B03-1, I've been passing raw options to `ssl:listen` as
follows, and it's been working fine:
% The constants are defined elsewhere.
LOpts = [{raw, ?IPPROTO_TCP, ?TCP_MAXSEG, <<MSS:32/native>>} | ...],
{ok, LSocket} = ssl:listen(0, LOpts)
In Erlang 17.3, this fails with
`{option_not_a_key_value_tuple,{raw,6,2,<<64,2,0,0>>}}`
I originally reported this in
http://erlang.org/pipermail/erlang-questions/2014-October/081226.html
I need to pass *this particular* raw option to `ssl:listen`, because it needs to be applied when the socket is first opened -- between `inet:open` and `prim_inet:listen` -- it cannot be applied later by `setopts`. This means that it needs to be done by `inet_tcp:listen/2` -- well, actually by `inet:open/8`, but...
Otherwise it's racey -- a client could …

Pass 'raw' options through ssl:listen/1

---

lib/jinterface/java_src/com/ericsson/otp/erlang/OtpErlangMap.java

The implementation sorted keys differently for different Java versions
(probably due to different hashing algorithms), so we switch it to use
LinkedHashMap where the order is deterministic.

Improve sorting order of keys in a map

---

erts/emulator/hipe/hipe_x86_signal.c

This pull request includes a fix of running HiPE on FreeBSD.
* Add FreeBSD sigaction code for HiPE. This is based on the Darwin (OS X) code and more detailed testing needed. FreeBSD libc is not musl, so this code is needed. See #893  for the code in OTP 18.2.

OTP 18.2 HiPE fix for FreeBSD 10.2-STABLE

---

erts/emulator/beam/erl_message.c

Please refer to commit message for details.
I tested this patch trying to build using command `./otp_build setup --enable-vm-probes --with-dynamic-trace=dtrace`. The patch fixes the build, and the built `erl` command looks working. I did not perform more in-depth test but this looks like a typo in the recent change in the file.

Fix compilation with `--enable-vm-probes`

---

lib/stdlib/src/erl_eval.erl
lib/stdlib/test/erl_eval_SUITE.erl

Prior to this patch, the following code would not eval:
X = key,
(fun(#{X := value}) -> true end)(#{X => value})
That's because the key evaluation was using the new
list of bindings introduced on every anonymous fun.
Since keys only match on values defined prior to the
pattern and do not introduce any new binding, we must
use the full and original list of binding.
The example above works fine in compiled code but
fails when code is evaluated.

Use full list of bindings when matching on map keys

---

erts/epmd/src/epmd_srv.c

This happens only during processing ALIVE2 request. reply() already
performs the same delay as in the deleted code.

Don't wait for twice the delay_write timeout

---

erts/doc/src/erlang.xml
erts/emulator/beam/atom.names
erts/emulator/beam/erl_bif_info.c
erts/emulator/beam/erl_gc.c
erts/emulator/beam/erl_gc.h
erts/emulator/beam/erl_trace.c
erts/emulator/test/process_SUITE.erl
erts/preloaded/src/erlang.erl

This info request returns greater details about the current gc state. For some reason this information was previously only available as trace messages.
Suggestions on a better name than garbage_collection_info would be greatly appreciated.

erts: Add garbage_collection_info to process_info/2

---

erts/emulator/drivers/common/efile_drv.c

Compiling OTP 18.2.1 with gcc-5.3 shows the following warning:
drivers/common/efile_drv.c:1538:23: warning: logical not is only applied to the left hand side of comparison [-Wlogical-not-parentheses]
The code in question is:
if (! (status =
erts_gzwrite((ErtsGzFile)d->fd,
iov[i].iov_base,
iov[i].iov_len)) == iov[i].iov_len) {
d->errInfo.posix_errno =
d->errInfo.os_errno = errno; /* XXX Correct? */
break;
}
If we hoist the assignment out of the if for clarity, it becomes:
status = erts_gzwrite(..., iov[i].iov_len);
if (! status == iov[i].iov_len) { ...; break; }
iov_len is > 0 here, and status will equal iov_len if erts_gzwrite
succeeded, but will be less than iov_len if an error occurred.
"! status" is 0 or 1, which can only equal iov_len if iov_len is 1 and
erts_gzwrite detected an error …

efile_drv: logic error in compressed file write

---

lib/ssl/src/ssl_tls_dist_proxy.erl
lib/ssl/test/ssl_dist_SUITE.erl

The option `inet_dist_connect_options` was missed in #897. With this change, all the options for plain TCP distribution are also supported for TLS distribution.
Also remove calls to deprecated functions in the test suite.

TLS distribution: allow specifying connect options

---

lib/inets/src/http_client/httpc.erl
lib/inets/src/http_client/httpc_request.erl
lib/inets/src/http_server/httpd_request.erl
lib/inets/src/http_server/mod_cgi.erl
lib/inets/src/http_server/mod_esi.erl
lib/inets/test/httpc_SUITE.erl

It is technically a new feature, but it really just loosens the restriction of acceptable methods to allow "PATCH", in compliance with the RFC5789.
I have adapted the test that existed for POST and manually tested the client agains an existing web service. It worked quite straightforwardly so I believe it is correct, but anyone that has a global understanding of the inets package should review it.

inets: Add PATCH method to client and server

---

lib/dialyzer/src/dialyzer_analysis_callgraph.erl
lib/dialyzer/src/dialyzer_cl.erl
lib/dialyzer/src/dialyzer_plt.erl
lib/dialyzer/test/plt_SUITE.erl

If a behaviour module contains an non-exported function with the same name as
one of the behaviour's callbacks, the callback info was inadvertently deleted
from the PLT as the dialyzer_plt:delete_list/2 function was cleaning up the
callback table. This bug was reported by Brujo Benavides.
Fixes ERL-72 bug report.

Fix inadvertent deletion of callback info in Dialyzer

---

lib/ssl/src/ssl_tls_dist_proxy.erl

There is no reason for the socket on the erts side of the proxy to
accept connections from other hosts, so let's bind it to 127.0.0.1.
This will probably conflict with some of the other pull requests related to TLS distribution; let me know if you want me to rebase it.

TLS distribution: bind erts socket to localhost

---

erts/epmd/src/epmd_srv.c
erts/epmd/test/epmd_SUITE.erl

In the following (rare) case down node will be always registered in epmd:
- client connects to epmd and sends ALIVE2 request
- epmd reads this request and starts to process it
- during that time client socket closes in such way that subsequent
write(2) in epmd will result in error
- at this point we have node that was registered in database, but as
the connection struct has no 'keep' flag set, the do_read() closes
connection and removes it from select fdset - and so there is no way
for this node to be cleaned up later.
We've seen several epmd instances in such state on our production
systems. And while I'm not sure what was the exact sequence of events
that leads to failed write(2), issue could be easily reproduced using
SO_LINGER socket option.

Prevent down nodes going undetected in epmd

---

lib/ssl/src/ssl_handshake.erl
lib/ssl/test/ssl_crl_SUITE.erl

If a certificate doesn't contain a CRL Distribution Points extension, and the relevant CRL is not in the cache, and the `crl_check` option is _not_ set to `best_effort`, the revocation check should fail.
As far as I can tell, the algorithm described in [section 6.3 of RFC 5280](https://tools.ietf.org/html/rfc5280#section-6.3) would give the result "UNDETERMINED" if there are no defined distribution points and the CRL is not otherwise available. The documentation for the `best_effort` setting for `crl_check` says:
> if certificate revocation status can not be determined it will be accepted as valid.
which suggests that for the other settings, certificates should _not_ be accepted if the certificate revocation status could not be determined.

Be suspicious of certificates without CRL distribution points

---

lib/ssl/doc/src/ssl.xml
lib/ssl/src/ssl.erl
lib/ssl/test/ssl_certificate_verify_SUITE.erl

When establishing a TLS connection with `{verify, verify_none}`, if the
server has a certificate with a critical extension, for example a
"Netscape Cert Type" extension, certificate verification would fail,
which is surprising given that the name of the option suggests that no
verification would be performed.
With this change, certificate extensions marked as critical are
ignored when using `verify_none`.

ssl: with verify_none, accept critical extensions

---

lib/kernel/src/gen_tcp.erl

When handling a gen_tcp socket, it's handy to be able to give it its proper type
and have dialyzer be able to validate it, rather than falling back on using
port(). The gen_udp equivalent is already exported.

Export gen_tcp:socket() type

---

lib/stdlib/src/maps.erl

Inspired by the analogous elixir implementations, this PR improves the performance of `maps:with` and `maps:without`, particularly in the case of large maps.
The current implementation is roughly O(N*M) where N is the number of items to be removed, and M is the number of items in the map. This does not include the cost of `maps:from_list` or `maps:to_list`. This leads to pretty horrifying execution times on large maps.
The new implementation is O(N) where N is the number of items to be removed. For each N there's the cost of removing a key from a map, and while I don't know that off hand, in practice that turns out to be a vast improvement for all map sizes I tested.
Examples:
Map size: 1,000,000. Keys to remove: 1,000.
Old: 4,312.239 ms
New: 3.141 ms.
Map size: 1,000. Keys to remove: …

improved maps:with and maps:without algorithm

---

erts/doc/src/erl_nif.xml
erts/emulator/beam/beam_load.c
erts/emulator/beam/erl_bif_unique.c
erts/emulator/beam/erl_bif_unique.h
erts/emulator/beam/erl_nif.c
erts/emulator/beam/erl_nif.h
erts/emulator/beam/erl_nif_api_funcs.h
erts/emulator/beam/erl_port.h
erts/emulator/beam/erl_port_task.c
erts/emulator/beam/erl_port_task.h
erts/emulator/beam/erl_trace.c
erts/emulator/beam/external.c
erts/emulator/beam/external.h
erts/emulator/beam/io.c
erts/emulator/test/nif_SUITE.erl
erts/emulator/test/nif_SUITE_data/Makefile.src
erts/emulator/test/nif_SUITE_data/echo_drv.c
erts/emulator/test/nif_SUITE_data/nif_SUITE.c

This PR adds a couple of new NIF function that are needed in order to create the new tracer modules to be added in 19.0.
The functions added are:
* enif_now_time
* enif_cpu_time
* enif_make_unique_integer
* enif_is_process_alive
* enif_is_port_alive
* enif_term_to_binary
* enif_binary_to_term
* enif_port_command

Extends NIF api

---

lib/crypto/c_src/crypto.c
lib/crypto/doc/src/crypto.xml
lib/crypto/src/crypto.erl
lib/crypto/test/crypto_SUITE.erl

This commit enables AES-GCM encryption/decryption to change the tag
length between 1 to 16 bytes.
[old spec](http://csrc.nist.gov/groups/ST/toolkit/BCM/documents/proposedmodes/gcm/gcm-spec.pdf), which crypto module refers to, says that the tag length can be any value between 0 and 128, whereas [new spec](http://csrc.nist.gov/groups/ST/toolkit/BCM/documents/proposedmodes/gcm/gcm-revised-spec.pdf) says between 64 and 128.
For now, this implementation allows values between 1 and 16 bytes(it means between 8 and 128), based on the openssl's implementation(https://github.com/openssl/openssl/blob/master/crypto/evp/e_aes.c#L1350-L1355).
Use case: [quic](https://docs.google.com/document/d/1g5nIXAIkN_Y-7XJW5K45IblHd_L2f5LTaDUDwvZ5L6g/edit) uses 12-byte tag.

crypto: Enable AES-GCM tag length to change

---

erts/emulator/beam/bif.tab
erts/emulator/beam/erl_map.c
erts/emulator/beam/erl_map.h
erts/emulator/beam/erl_nif.c
erts/emulator/test/map_SUITE.erl
lib/stdlib/doc/src/maps.xml
lib/stdlib/src/maps.erl
lib/stdlib/test/maps_SUITE.erl

Adds the functions `maps:take/2` and `maps:update_with/3,4` to the maps module:
```erlang
-spec take(Key,Map1) -> {Value,Map2} | error when
Key :: term(),
Map1 :: map(),
Value :: term(),
Map2 :: map().
```
`maps:take/2` removes a Key and the value associated to it from a Map and returns a tuple with the removed Value and a new Map without the association. If the Key does not exist `error` is returned.
This is the equivalent of doing a `maps:find/2` and then `maps:remove/2` but `maps:take/2` should be faster.
```erlang
-spec update_with(Key,Fun,Map1) -> Map2 when
Key :: term(),
Map1 :: map(),
Map2 :: map(),
Fun :: fun((Value1 :: term()) -> Value2 :: term()).
-spec update_with(Key,Fun,Init,Map1) -> Map2 when
Key :: term(),
Map1 :: Map1,
Map2 :: Map2,
Fun :: fun((Value1 :: term()) -> Value2 …
```

Maps API additions

---

lib/os_mon/src/cpu_sup.erl

The documentation correctly states that the Busy and NonBusy components
in the return value of cpu_sup:util/1 are not tuples but list of tuples:
"If the detailed option is given, this is a *list* of {State, Share}
tuples"

Fix type spec for cpu_sup:util/1

---

lib/stdlib/doc/src/lists.xml
lib/stdlib/src/lists.erl
lib/stdlib/test/lists_SUITE.erl

Add a call which works much like string:join/2 but for arbitrary lists. Provide
the function itself, lifted from Haskells Data.List standard library, provide
documentation and provide tests for the function.
* The addition is fairly simple, and I think it should find its way into Erlang/OTP since there are so many people who write this exact function. I've known to be getting it wrong in the past in certain projects of mine.
* The name `join` is what I ended up with, giving the discussion on erlang-questions@. The reason, I believe, Haskell uses the name `intersperse` has to do with the fact that in Haskell, people tend to avoid adding the module part. So the name must be quite unique, which join isn't. For Erlang, on the other hand, we have the ability to prefix with the module, so a …

Implement lists:join/2

---

erts/emulator/beam/erl_process.h

It was recently observed that the LLVM backend for HiPE was broken,
generating code that crashes the VM.
It turns out that this was caused by LLVM hard-coding an offset into the
Erlang PCB, which became incorrect as of commit 3ac08f9b, that
introduced a new member into the PCB before the HiPE-specific state,
changing its offsets.
For now, until a proper fix is implemented, we move this new member to
after the HiPE-specific state, allowing the LLVM backend to work once
more.
This is the most reasonable first step towards fixing this
problem, as older LLVM versions tend to stick around because of
API breaks in major releases. Thus, a fix to LLVM only would take some
time to propagate to all affected users.

Fix HiPE LLVM backend in R19

---

lib/jinterface/java_src/pom.xml.src

http://bugs.erlang.org/browse/ERL-67
These are a few changes to the (otherwise unused) pom.xml for jinterface, so that it actually works for building the library with Maven.

jinterface: updated pom.xml.src (ERL-67)

---

lib/kernel/src/dist_util.erl

Add descriptive shutdown reasons when an incoming distribution
connection is rejected because it is not on the "allowed" list or
because it has an incorrect cookie.  These error reasons can be seen
after calling `net_kernel:verbose(1)`.
Distinguishing these failures is valuable, because the log message
printed is otherwise identical.
This is in addition to the error reasons introduced in #980.

Error reasons for more distribution errors

---

lib/os_mon/c_src/ferrule.c
lib/os_mon/c_src/mod_syslog.c

The combination of the use of the exit() function without including
stdlib.h,  together with the option -Werror=implicit-function-declaration
causes the compilation (and the 'make') to fail on SUN/SPARC with gcc 4.9.3.

Fix compilation on SUN/SPARC by including <stdlib.h>

---

lib/hipe/test/bs_SUITE_data/bs_match_compiler.erl
lib/hipe/test/hipe_testsuite_driver.erl

Taken from the OTP test suites and changed accordingly for HiPE.
Used to be problematic in the tests that matched against a segment
of 'bad_size'.  This was corrected in the BEAM compiler for OTP 19.

One more test suite for binary pattern matching

---

lib/stdlib/src/otp_internal.erl
lib/stdlib/test/erl_lint_SUITE.erl

In current deprecated warnings such as `crypto:rand_bytes/1 is deprecated and will be
removed in in a future release; use crypto:strong_rand_bytes/1`, the word "in" is duplicated.

Fix deprecated warnings

---

lib/dialyzer/src/dialyzer_contracts.erl
lib/hipe/cerl/erl_types.erl

and do the following changes:
in erl_types: export the type and an appropriate constructor for it
in dialyzer_contracts: perform all necessary code modifications to
fix all dialyzer warnings
Although no warnings are reported by dialyzer, it's quite possible that
these are not the only places where the opacity of the var_table() data
structure is violated. But I decided to leave these places for a better
version of dialyzer to discover...

Declare the erl_types:var_table() type as opaque

---

lib/eldap/src/eldap.erl
lib/eldap/test/eldap_basic_SUITE.erl

If underlying tcp connection is closed and LDAP operation returned tcp error, client applications tend to close ldap handle with eldap:close.
This will cause do_unbind to throw gen_tcp_error, which is not handled and will be sent to linked process as {nocatch, {gen_tcp_error, ...}}.
gen_tcp_error should be ignored during close, because socket will be closing anyway.
Discovered in RabbitMQ ldap authorisation backend
rabbitmq/rabbitmq-auth-backend-ldap#30

Ignore tcp errors during close request to eldap

---

erts/emulator/beam/binary.c
erts/emulator/beam/erl_message.h
erts/emulator/beam/erl_nif.c
erts/emulator/beam/erl_process.h
erts/emulator/beam/erl_unicode.c
erts/emulator/beam/global.h

This fixes several VM malfunction issues we've seen recently at Klarna.  The root cause is that parts of the VM use 32-bit integers to represent counts and byte offsets on 64-bit machines.  Sometimes these small integers overflow causing wraparound, sometimes larger integers are assigned to them causing truncation.  The effects we've observed include segmentation faults and failed attempts to allocate huge amounts of memory (many orders of magnitude more than we have) -- a sign of wraparound or memory corruption.
The patches also include a fix to not crash the VM on attempts to pass large messages between processes.  In OTP 18 there was an explicit check for that in erts_alloc_message_heap_state(), but that check seems to have been removed in OTP 19.  However, the other parts of that …

Otp 19 erts integer truncation bugs

---

lib/eunit/doc/overview.edoc
lib/eunit/include/eunit.hrl

Add a macro which works much like ?debugVal, but doesn't truncate terms to
print.

eunit: Add ?debugValAll macro

---

lib/compiler/src/cerl.erl

Specs of various *_arity functions in this module used different types
(integer(), non_neg_integer(), byte()) to refer to the type arity().

cerl: Use arity() consistently

---

lib/public_key/priv/generate
make/make_emakefile

Followup to https://github.com/erlang/otp/pull/1023
- make/make_emakefile is fixed because otherwise `./otp_build tests`
fails early.
- And grep showed that there is only one other file that also should be
fixed - lib/public_key/priv/generate

Fix program paths used in build process

---

lib/eunit/doc/overview.edoc
lib/eunit/include/eunit.hrl

Also make the default depth for debugVal/1 possible to override
by defining the macro EUNIT_DEBUG_VAL_DEPTH.

Replace suggested debugValAll/1 macro with debugVal/2

---

lib/kernel/doc/src/inet.xml
lib/kernel/src/inet.erl

This makes the implementation text of inet:gethostbyname/1 identical to
that of inet_res:gethostbyname/1. I also copied over the doc note about
this resolver option.

Make inet:gethostbyname respect resolver option `inet6`

---

lib/hipe/icode/Makefile
lib/hipe/icode/hipe_icode_call_elim.erl
lib/hipe/main/hipe.app.src
lib/hipe/main/hipe.erl
lib/hipe/main/hipe_main.erl
lib/hipe/test/Makefile
lib/hipe/test/hipe_testsuite_driver.erl
lib/hipe/test/opt_verify_SUITE.erl
lib/hipe/test/opt_verify_SUITE_data/call_elim_test.erl
lib/hipe/test/opt_verify_SUITE_data/call_elim_test_branches_no_opt_poss.erl
lib/hipe/test/opt_verify_SUITE_data/call_elim_test_branches_opt_poss.erl

HiPE uses the built-in functions from the `maps` module to implement the map syntax. With the addition of more sophisticated map types in the `erl_types` type system, HiPE can sometimes conclude at compile time what the result of calls to `maps:is_key/2` will be, but is unable to eliminate the call since the type system does not express freedom from side effects. This patch adds an optimisation pass that hard-codes BIFs that are side-effect free under certain conditions and eliminates calls to them when their results are known.
The optimisation is written to be easily extensible to eliminate more BIFs.

HiPE: Add optimisation that eliminates redundant maps:is_key/2 calls

---

erts/doc/src/erl.xml
erts/doc/src/init.xml
erts/emulator/test/distribution_SUITE.erl
erts/etc/common/erlexec.c
lib/kernel/src/inet_tcp_dist.erl
lib/kernel/src/net_adm.erl
lib/ssl/src/inet_tls_dist.erl
lib/ssl/src/ssl_tls_dist_proxy.erl

These two patches make it possible to use an alternative to EPMD.
The first patch adds an option, `-start_epmd`, which defaults to `true`, the current behaviour. If set to `false`, epmd will not be started when the Erlang node is started. Unlike the existing undocumented option `-no_epmd`, this option does not disable the epmd process in `erl_distribution`.
The second patch ensures that the `-epmd_module` option is heeded consistently. That makes it possible to use a custom module to look up and register node names.

EPMD options

---

lib/ssl/doc/src/ssl.xml
lib/ssl/src/dtls_connection.erl
lib/ssl/src/ssl.erl
lib/ssl/src/ssl_internal.hrl
lib/ssl/src/ssl_record.erl
lib/ssl/src/ssl_record.hrl
lib/ssl/src/tls_connection.erl
lib/ssl/test/ssl_basic_SUITE.erl

This PR adds a new ssloption that allows one to select the content splitting method (1/n-1 or 0/n) used by SSLv3 and TLSv1.0 connections or disable content splitting entirely.
Documentation updates and tests are included in the patch.

ssl: Add BEAST mitigation selection option

---

lib/hipe/llvm/hipe_llvm.erl
lib/hipe/llvm/hipe_rtl_to_llvm.erl

As previously discussed in #1038, LLVM hard-codes offsets into the ERTS PCB in order to do dynamic stack allocation, and this is undesirable due to placing restrictions on how new properties may be added to the PCB without breaking ErLLVM. This PR implements the HiPE side of the fix to this problem, which is to convey this information to LLVM as part of the IR generated by HiPE.
The corresponding code for LLVM is currently pending review at [reviews.llvm.org/D20363](http://reviews.llvm.org/D20363).

ErLLVM: Convey ERTS-internal structure offsets to LLVM as named metadata

---

lib/compiler/src/rec_env.erl

Since we have converted other parts of the compiler to use maps, I noticed rec_env.erl still used dictionaries and I converted them to maps. A great opportunity to use the new maps:take/2 to avoid multiple lookups too.

Convert dict() to map() in rec_env.erl

---

lib/ssl/doc/src/ssl.xml

PR #1041 added a formatting error to the ssl application documentation. This commit fixes it.

Move misplaced period in ssl documentation

---

lib/compiler/doc/src/compile.xml
lib/compiler/src/compile.erl
lib/compiler/test/compile_SUITE.erl

retrieve the value of the environment variable `ERL_COMPILER_OPTIONS`
in the same manner as used by `file/2`, `forms/2` and `output_generated/2`
for rebar3 we do a check that the compile options as generated by rebar3 match
the options used to compile existing beam files and (potentially) skip them if true. adding
this function allows us to ensure that rebar3's processing of `ERL_COMPILER_OPTIONS`
matches the processing done by `file/2`
see erlang/rebar3#1184

Compiler: new function env_compiler_options/0

---

lib/observer/src/observer_procinfo.erl
lib/sasl/test/release_handler_SUITE.erl
lib/stdlib/src/supervisor.erl
lib/stdlib/test/supervisor_SUITE.erl

The previous implementation of supervisor:get_callback_module/1
used sys:get_status/1 to get the supervisor inner state and
retrieve the callback module. Such implementation forbids any
other supervisor implementation that has an internal state
different than the #state{} record in supervisor.erl.
This patch allows supervisors to return the callback module
as part of the sys:get_status/1 data, no longer coupling the
callback module implementation with the inner #state{} record.
Notice we have kept the clause matching the previous
sys:get_status/1 reply for backwards compatibility purposes.

Return callback module in supervisor format_status

---

lib/dialyzer/src/dialyzer_dataflow.erl
lib/dialyzer/test/small_SUITE_data/results/higher_order_discrepancy
lib/dialyzer/test/small_SUITE_data/src/higher_order_discrepancy.erl
lib/dialyzer/test/user_SUITE_data/results/wpc_hlines
lib/dialyzer/test/user_SUITE_data/src/wpc_hlines.erl

Dialyzer's "dataflow" module is using information from the callgraph to
determine which functions may be called at a particular call-site. Unfortunately
this information can include functions that are certainly not among the possible
choices. We don't want to emit warnings in such cases, so a "reasonable"
compromise is to stay silent if there are many possible funs and at least one of
them can succeed.
Bug reported by @dgud, test shrunk down by @margnus1.

Fix a bug in Dialyzer related to call-site analysis

---

lib/xmerl/src/xmerl_xpath_scan.erl
lib/xmerl/src/xmerl_xsd.erl

A slightly stronger version of Dialyzer discovered that various clauses
in the code of `xmerl` are unreachable.  This code was commented out;
There is little reason to have code bloat that simply causes confusion.
An alternative change would be to simply delete this code.

xmerl: Comment out unreachable clauses

---

lib/compiler/src/compile.erl

When the compiler fails to write an output file, it used to just print
"error writing file".  With this change, it also prints the error
reason:
$ echo "-module(foo)." > foo.erl
$ chmod -w .
$ erlc foo.erl
/tmp/bar/foo.bea#: error writing file: permission denied
There's one more place in compile.erl where `write_error` is returned, on line 1213 next to the `%% Couldn't write to output Makefile` comment. I'm not sure what to do with it — it seems to be incorrect, as it assumes that `io:fwrite` is going to raise an exception on error, or for some reason wants to ignore errors. If that part is changed as well, the non-tuple `write_error` clause for `format_error/1` could be deleted.

Show error reason when compiler cannot write file

---

lib/dialyzer/test/map_SUITE_data/src/mand_remote_val/a.erl
lib/dialyzer/test/map_SUITE_data/src/mand_remote_val/b.erl
lib/hipe/cerl/erl_types.erl

`t_map/3` previously required callers to perform normalisation of
`X:=none()` pairs, but as `t_from_form/5` would sometimes fail to do so,
this requirement is relaxed.
This caused a dialyzer crash when using remote types as values of
mandatory pairs with singleton keys.
Bug (ERL-177) reported and shrunk by Luke Imhoff.
This PR was previously #1114, but was rebased from maint to maint-19.

erl_types: Fix map type parsing bug (ERL-177)

---

lib/stdlib/src/ets.erl

`ets:match_object/1` and `ets:match_object/3` return list of matches.

Fix return value spec for ets:match_object

---

erts/emulator/hipe/hipe_amd64_asm.m4
erts/emulator/hipe/hipe_amd64_bifs.m4
erts/emulator/hipe/hipe_amd64_glue.S
erts/emulator/hipe/hipe_arm_asm.m4
erts/emulator/hipe/hipe_arm_bifs.m4
erts/emulator/hipe/hipe_arm_glue.S
erts/emulator/hipe/hipe_bif_list.m4
erts/emulator/hipe/hipe_gc.c
erts/emulator/hipe/hipe_mkliterals.c
erts/emulator/hipe/hipe_ppc_bifs.m4
erts/emulator/hipe/hipe_process.h
erts/emulator/hipe/hipe_sparc_bifs.m4
erts/emulator/hipe/hipe_x86_bifs.m4

The trap frame allocation wrappers occasionally call the garbage
collector, even though built-in functions are not supposed to.
On non-{x86,amd64} platforms, HiPE was optimising the BIF wrapper
interface on the basis that BIFs do not GC. So, when
`hipe_reserve_beam_trap_frame` called the garbage collector, the state in
the PCB was stale and corruption happened.
Now, these particular BIFs are reclassified as GC BIFs.
This bug has been causing Dialyzer crashes on ARM (and presumably all other non-intel platforms).
Unfortunately I know of no deterministic way of triggering the bug, although building a big PLT on ARM will always crash in one way or another. Instead I have added a mechanism to detect this whole class of bugs via an assertion on amd64 and ARM platforms. The assertion does …

HiPE: Fix bug in trap frame allocation wrappers 

---

erts/configure.in

Call AC_CHECK_LIB before calling AC_CHECK_FUNCS to check for functions in libsctp.
Otherwise AC_CHECK_FUNCS will not link with libsctp to see if function exists.

Check libsctp for sctp funcs in configure.in

---

lib/kernel/src/code_server.erl

Fix the problem when adding code paths hanging from root like "/myproject/ebin".
Fix [ERL-194](https://bugs.erlang.org/browse/ERL-194)

Fix code_server crash when adding some code paths ERL-194

---

lib/kernel/src/erl_epmd.erl

`select_best_version` has the duplicated case.

Remove a duplicated pattern matching in erl_epmd.erl

---

lib/kernel/src/erl_epmd.erl
lib/kernel/src/inet_tcp_dist.erl
lib/ssl/src/ssl_tls_dist_proxy.erl

it seems that despite of setting up address family value (inet6_tcp, inet_tcp), inet_tcp_dist always uses basic erl_epmd:register_node/2 which uses 'inet' family. Let's fix that.
With this patch inet_tcp_dist  will try using inet6 loopback address if a user adds "-proto_dist inet6_tcp" command line switch. This allows Erlang distribution to work if IPv4 loopback was disabled in EPMD.
See also PR #1075.
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>

Respect -proto_dist switch while connecting to/registering at EPMD

---

erts/emulator/beam/beam_bif_load.c
erts/emulator/beam/erl_gc.c
erts/emulator/hipe/hipe_gc.c
erts/emulator/hipe/hipe_risc_gc.h
erts/emulator/hipe/hipe_stack.h
erts/emulator/hipe/hipe_x86_gc.h
erts/emulator/test/Makefile
erts/emulator/test/hipe_SUITE.erl
erts/emulator/test/hipe_SUITE_data/literals.erl
erts/emulator/test/hipe_SUITE_data/ref_cell.erl

Because `check_process_code` neglected checking the HiPE stack for
references to the literal area, such references would survive the purge
and subsequent deletion of a module and its literal area. These dangling
references would then cause incorrect behaviour or even hard crashes of
the VM.
By simply adding a scan of the HiPE stack to `check_process_code` and
`erts_garbage_collect_literals`, this problem is fixed.
In order to support full stack walks without deleting the graylimit
trap, a new stack walking interface function,
`nstack_walk_init_sdesc_ignore_trap()` was introduced.
A new test suite for the emulator, `hipe_SUITE`, was introduced to hold the
test for this issue, as it does not really belong in the HiPE application.

emulator: Sweep HiPE stack for literals on purge

---

lib/tools/src/fprof.erl

Avoid errors with gc_start and gc_end while fprof:profile/1
Ex:
fprof:profile({file, "/home/tihon/full.trace"}).
Reading trace data...
..................................................
.................................................,
..................................................
.........
End of erroneous trace!
{error,{incorrect_trace_data,fprof,1708,
[{trace_ts,<7595.8871.1>,gc_start,
[{old_heap_block_size,1598},
{heap_block_size,233},
{mbuf_size,26},
{recent_size,25},
{stack_size,19},
{old_heap_size,1169},
{heap_size,214},
{bin_vheap_size,78},
{bin_vheap_block_size,46422},
{bin_old_vheap_size,178},
{bin_old_vheap_block_size,46422}],
{1469,730152,117381}}]}}
And other:
fprof:profile({file, "/home/tihon/full.trace"}).
Reading trace data... …

fix gc_start\end bug

---

lib/inets/src/http_server/httpd_conf.erl
lib/inets/test/inets_sup_SUITE.erl

`inets:start/2` fails when using the legacy option `inet6fb4` with a configuration proplist. It is not translated to `inet` [as documented](http://erlang.org/doc/man/httpd.html).
{ipfamily, inet | inet6}
Default is inet, legacy option inet6fb4 no longer makes sense
and will be translated to inet.
This breaks existing code that relies on the documented behavior.
This commit fixes the issue by translating `inet6fb4` everywhere it is encountered in `httpd_conf:validate_properties/1`. This fixes JIRA issue ERL-200.

Fix httpd_conf:validate_properties/1 for ipfamily

---

lib/odbc/configure.in

Change ODBC configure.in script to recognize OS X El Capitan (Darwin v15.x)

Make ODBC configure handle OS X El Capitan

---

lib/dialyzer/src/dialyzer.erl

Let it handle `dial_warning()` input as well, to match what `format_warning/2` expects.

Improve format_warning/1 spec

---

lib/crypto/c_src/crypto.c

The size of `algo_cipher` has to be increased, to allow holding all possible ciphers.
backtrace: https://gist.github.com/zbrdge/3283483599df146672fc061942391c42
https://github.com/voidlinux/void-packages/issues/4548

Fix segfault in crypto by increasing algo_cipher array

---

configure.in
erts/configure.in
lib/debugger/doc/src/Makefile
lib/diameter/src/Makefile
lib/gs/doc/src/Makefile
lib/ic/doc/src/Makefile
lib/jinterface/doc/src/Makefile
make/emd2exml.in
make/make_emakefile.in
make/otp.mk.in

One more followup to https://github.com/erlang/otp/pull/1056 and
https://github.com/erlang/otp/pull/1023
This time it's about `/usr/bin/env` and `/bin/cp`:
- `/usr/bin/env` in `diameterc` was used to find the bootstrapped
`escript` executable. Changed it to exlpicit call to `escript` in
Makefile.
- `/usr/bin/env` and `/bin/cp` were referenced in documentation
build/install process. Now full paths to this tools are injected using
autoconf magic.

Don't make assumptions about build tools paths

---

lib/syntax_tools/src/merl_tests.erl
lib/syntax_tools/src/merl_transform.erl
lib/syntax_tools/test/merl_SUITE.erl

This can happen when a syntactically incorrect text is passed to a
merl:qquote/2,/3 call.
The parse transform optimizes calls to some functions in merl by
converting strings into templates at compile time. If this evaluation
fails (in eval_call/4 - for example because of a sytanx error in the
parsed text) the original function call should be kept unchanged.
However in case of qquote/3 the call is converted into a combination of
quote/2 and subst/2, but upon failure the original qquote/3 call is
substituted into the wrong place. E.g.:
this expression
`merl:qquote(Pos, Text, Env)`
is first converted to
`merl:subst(merl:quote(Pos, Text), Env)`
then if evaluating the quote call fails into
`merl:subst(merl:qquote(Pos, Text, Env), Env)`
and the expansion is run again on the internal qquote/3 …

Fix infinite loop in merl_transform

---

lib/ssh/src/ssh_connection_handler.erl
lib/ssl/src/dtls_connection.erl
lib/ssl/src/tls_connection.erl
lib/stdlib/doc/src/gen_statem.xml
lib/stdlib/src/gen_statem.erl
lib/stdlib/test/gen_statem_SUITE.erl
lib/tools/doc/src/erlang_mode.xml
lib/tools/emacs/erlang-skels.el
system/doc/design_principles/statem.xml

This is an alternative pull request instead of #1133 after feedback from @antipax.
This pull request also concerns the new `gen_statem` behaviour from #960 but uses `Module:callback_mode/0` to select Callback Mode instead of covertly checking if `Module:handle_event/4` is exported making the selection more explicit and the difference from #960 smaller than for #1133.

gen_statem M:callback_mode/0 (OTP-13752)

---

lib/hipe/amd64/hipe_amd64_ra_sse2_postconditions.erl
lib/hipe/arm/hipe_arm_registers.erl
lib/hipe/arm/hipe_rtl_to_arm.erl
lib/hipe/ppc/hipe_ppc.erl
lib/hipe/ppc/hipe_ppc_assemble.erl
lib/hipe/sparc/hipe_sparc_registers.erl
lib/hipe/x86/hipe_x86_postpass.erl

These are fixes to various backend bugs exposed by a branch of mine where I fix the `o0` and `o1` flags. However, as I expect the OTP team would like that PR to be on the master branch, I have extracted these fixes, which are the ones that fix miscompilation-type bugs, to be submitted to maint instead, as at least some of these bugs should still be reproducible with default compiler flags.
As such, I have no test cases included in this PR. Instead, tests that expose these bugs will be included in the optimisation level PR to master. I hope that it will suffice.

HiPE backend miscompilation bugs

---

erts/configure.in
erts/doc/src/zlib.xml
erts/emulator/drivers/common/zlib_drv.c
erts/preloaded/src/zlib.erl
lib/kernel/test/zlib_SUITE.erl

zlib already exposes a stream method for this - `inflateGetDictionary` - only the final glue was missing.

zlib: support extraction of inflation dictionary

---

lib/kernel/src/code_server.erl

When printing the error term from on_load, insert a newline because the
term is never short and will produce hard to read/copy output that is
just hanging off to the right.

Print on_load error in a more useful style

---

erts/start_scripts/Makefile

At least on macOS (OS X), /usr/bin/install does not seem to be
thread-safe when creating directories. That is, if several
invocations of /usr/bin/install attempts to create the same
directory, one or more of the invocations may fail with an
error, causing the build to fail.
Avoid the problem by turning off parallel make for the
Makefile in erts/start_scripts.
Reported-by: https://bugs.erlang.org/browse/ERL-250

Turn off parallel make for start scripts Makefile

---

erts/doc/src/erlang.xml

There is a small mistake in the documentation:
> erlang:make_tuple(5, [], [{2,ignored},{5,zz},{2,aa}]).
{{[],aa,[],[],zz}
Should be:
> erlang:make_tuple(5, [], [{2,ignored},{5,zz},{2,aa}]).
{[],aa,[],[],zz}

Typo in documentation fixed

---

system/doc/tutorial/c_port.xmlsrc

The original code is at http://erlang.org/doc/tutorial/c_port.html

doc: Fix code format in tutorial/c_port

---

lib/eunit/include/eunit.hrl

When asserts were moved out to a separate header file, the automatic
enabling of asserts when testing stopped working.

Ensure asserts are enabled in eunit.hrl

---

erts/doc/src/erl_nif.xml
erts/doc/src/erl_tracer.xml
erts/emulator/test/alloc_SUITE_data/testcase_driver.h
erts/emulator/test/dirty_nif_SUITE_data/dirty_nif_SUITE.c
erts/emulator/test/mtx_SUITE_data/mtx_SUITE.c
erts/emulator/test/nif_SUITE_data/nif_SUITE.c
erts/emulator/test/nif_SUITE_data/nif_mod.c
erts/emulator/test/nif_SUITE_data/testcase_driver.h
erts/emulator/test/nif_SUITE_data/tester.c
erts/emulator/test/trace_call_time_SUITE_data/trace_nif.c
erts/emulator/test/trace_nif_SUITE_data/trace_nif.c
erts/emulator/test/tracer_SUITE_data/tracer_test.c
erts/example/matrix_nif.c
lib/asn1/c_src/asn1_erl_nif.c
lib/crypto/c_src/crypto.c
lib/crypto/c_src/crypto_callback.c
lib/kernel/test/gen_tcp_api_SUITE_data/gen_tcp_api_SUITE.c
lib/runtime_tools/c_src/dyntrace.c
lib/runtime_tools/test/dbg_SUITE_data/dbg_SUITE.c
system/doc/tutorial/complex6_nif.c

Anywhere but the beam sources we shouldn't `#include "erl_nif.h"`, because
what `"erl_nif.h"` does is: (1) fail to find it outside of `-I` dirs, (2)
then treat it as if it was written like `<erl_nif.h>`. Using `<erl_nif.h>`
skips (1).
More information can be found in 6.10.2 of the C standard.
Because the examples use `"erl_nif.h"`, NIF projects in the Erlang
ecosystem copy this verbatim and make the same mistake.

Use more correct delimiters for erl_nif.h include

---

lib/inets/src/http_client/httpc_response.erl
lib/inets/test/httpc_SUITE.erl

- The behavior of httpc:request when autoredirect = true is not correct
according to the latest update in RFC-7231. This patch corrects the
autoredirect behavior.

Update behavior of httpc:request to match RFC-7231

---

lib/ssh/src/ssh_cli.erl
lib/ssh/test/ssh_basic_SUITE.erl

When user defined SSH shell REPL process exits with reason normal SSH channel callback module should report successful exit status to the SSH client.
This provides simple way for SSH clients to check for successful completion of executed commands.

Fix SSH custom REPL exit status

---

lib/stdlib/src/supervisor.erl

When a simple_one_for_one supervisor is shutting down, and a child
exits with an exit reason of the form {shutdown, Term}, handle it as
if the exit reason were 'shutdown', without printing an error report.
This makes the behaviour of wait_dynamic_children match that of
do_restart.
This fixes [ERL-163](https://bugs.erlang.org/browse/ERL-163).

Don't report error for shutdown exit tuple

---

lib/kernel/src/file.erl

Previously, this function would turn any input into a single binary
before writing. This meant it could not take advantage of the `writev`
system call if it was given a list of binaries and told to write with
`raw` mode.
To see this, start an erlang shell on the parent commit, and also
start [this dtrace script](https://github.com/evanmiller/tracewrite) like this:
sudo dtrace -s tracewrite.d -p $(pgrep beam)
In the erlang shell, run the following:
```erlang
file:write_file("/tmp/tmp.txt", [<<97,98>>, <<98,97>>], [raw]).
```
In the dtrace output, you will see that the system call used is `write`.
Now repeat with this commit, and you will see that `writev` is used.
This is a very small change, but looks bigger because of whitespace
differences. See …

Ensure that file:write_file/3 can use `writev` if given `raw` mode

---

lib/compiler/src/sys_core_fold.erl
lib/compiler/src/v3_core.erl
lib/compiler/src/v3_kernel.erl
lib/dialyzer/src/dialyzer_dataflow.erl
lib/dialyzer/test/small_SUITE_data/results/fun_arity

The previous variable names can be generated by
projects like LFE and Elixir, leading to possible
conflicts. Using a character like @ as the leading
reduces the chance of conflicts.

Use @ in variable names generated by core and kernel

---

erts/doc/src/erlang.xml

Added an example showing the usage of binary_to_term/1 in the docs.

Add example to binary_to_term/1 docs

---

lib/crypto/c_src/crypto.c
lib/crypto/test/old_crypto_SUITE.erl
lib/public_key/test/pbe_SUITE.erl

When OpenSSL has been configured with the "no-rc2" option, the header
file rc2.h doesn't exist, and neither does the function EVP_rc2_cbc.
Let's handle those by checking whether OPENSSL_NO_RC2 is defined.
Also update pbe_SUITE, which uses RC2-CBC in one of the tests.
`crypto_SUITE` still works, since it checks whether the algorithm it's going to test is supported, but `old_crypto_SUITE` fails if OpenSSL doesn't support RC2. Should I update that test suite as well?

Fix compilation when OpenSSL doesn't support RC2

---

lib/crypto/c_src/crypto.c
lib/crypto/test/old_crypto_SUITE.erl
lib/ssl/src/ssl_cipher.erl

mostly the same as #1163 but for RC4 support.
SSL/TLS is affected as well. The SSL test suites might need some additional changes as they assume that RC4 is always a valid stream cipher.

OpenSSL without rc4

---

lib/edoc/doc/overview.edoc

Documentation for the tags params and returns where missing from the user guide/overview document.. This change will add them.

Add documentation for missing edoc tags

---

lib/tools/emacs/erlang.el

Erlang source files do not require a final newline. Thus,
require-final-newline is a personal setting and should not be configured
in the major mode. Setting it here will also negatively impact helpers
like ethan-wspace.

erlang-mode: do not configure require-final-newline

---

lib/compiler/src/beam_block.erl
lib/compiler/src/beam_flatten.erl
lib/compiler/src/beam_split.erl
lib/compiler/src/beam_utils.erl
lib/compiler/test/beam_block_SUITE.erl

c2035ebb8b restricted the get_map_elements instruction so that it
could only occur at the beginning of a block. It turns out to
also be unsafe.
Therefore, never put get_map_elements instruction in blocks.
ERL-266

beam_block: Avoid unsafe inclusion of get_map_elements in blocks

---

system/doc/reference_manual/typespec.xml

In 8ce35b287fb50a6845fccf6a13c672aae303dc91 automatic insertion of `undefined` for record fields without initializers was removed, but this was not noted in the documentation. Add a warning about this change using similar verbiage as the original docs.

Fix reference to automatic `undefined` field declared types.

---

lib/mnesia/src/mnesia.erl
lib/mnesia/test/mnesia_trans_access_test.erl

I think the problem this PR fixes is best explained via the use case behind it. I have a web app implementing paginated search results using `mnesia:select/4`:
```erlang
{Rows1, C1} = mnesia:activity(async_dirty, fun mnesia:select/4, [Tab, MatchSpec, NObjects, read]),
draw_table(Rows1),
%% and when the user clicks next:
{Rows2, C2} = mnesia:activity(async_dirty, fun mnesia:select/1, [C1]),
draw_table(Rows2),
%% and so on
```
Unfortunately this doesn't work when the `mnesia:select/1` call is done from a different process (which is typical for web apps). It crashes with `{aborted,wrong_transaction}`, because the activity id for `async_dirty` contains the pid, so it will only match in the same process.
I understand this check is important for transactional contexts: reusing a continuation in …

Add mnesia:repair_continuation for continuing a select in a new activity

---

lib/inets/doc/src/httpc.xml
lib/inets/src/http_client/httpc_handler.erl
lib/inets/src/http_client/httpc_internal.hrl
lib/inets/src/http_client/httpc_manager.erl
lib/inets/src/http_lib/http_internal.hrl
lib/inets/src/http_server/httpd_request_handler.erl

This supersedes PR #1185 (submitted by @KrzysiekJ) that changed
all occurrences of ref() with reference() in inets files.
However, there is little point in having these types only in comments.
So, these types are now exposed as type declarations for the record
fields they appear.  While at it, uncommented more commented out type
declarations and declared types for records defined in the affected
modules and header files.
Some type-unfriendly and obsolete code related to supporting code
ungrades with a really old OTP release was also removed.

Replace ref() with reference() in inets files

---

lib/inets/src/ftp/ftp_response.erl
lib/inets/test/ftp_format_SUITE.erl

Fixes a bug that makes the ftp client end up in bad state if there is a multi line response from the server and the response number is in the message being sent.
The response:
230-User usr-230 is logged in
230 OK. Current directory is /
should yield `{ok, BothRows, <<>>}` but actually returns `{ok, FirstRow, SecondRow}`. The reason for this is that the parser looks for the status code but doesn't validate that it's at the beginning of a line.

Multiple lines response bug inets ftp 

---

lib/stdlib/src/ms_transform.erl
lib/stdlib/test/ms_transform_SUITE.erl

Running 'dbg:fun2ms(fun([]) -> return_trace() end' resulted in an error
"dbg:fun2ms requires fun with single variable or list parameter"
But the empty list is actually a list and it is a valid value as a
match-spec head (matching on arity-0 functions).
Although its practical use is questionable this commit eliminates a
small limitation of ms_transform which is not present in the match-spec
grammar.

dbg:fun2ms: allow empty list as head

---

lib/erl_interface/src/connect/ei_connect.c

Closes issue discussed here:
http://erlang.org/pipermail/erlang-questions/2016-October/090592.html

ei_connect_xinit shall mask creation to two lowest bits.

---

erts/emulator/hipe/hipe_bif0.c
lib/hipe/cerl/erl_bif_types.erl
lib/kernel/src/hipe_unified_loader.erl

by changing the return value of  `hipe_bifs:add_ref/2`.

Cleanup and simplify some HiPE loader code

---

lib/tools/emacs/erlang.el

Having a consistent whitespace usage in the source makes it easier for
future contributors to send patches. This commit does the following:
* Replace tabs with spaces
* Kill trailing whitespace
* Disable indent-tabs-mode for erlang.el to prevent tabs from creeping
in
P.S. `erlang.el` is extremely outdated and odd looking compared to idiomatic Emacs major modes. I'd be willing to update it to match modern practices if there's some interest in having a modern `erlang-mode` for Emacs. This is the first step of the process - I simply can't stand messed up whitespace.

Fix all whitespace-related issues in erlang.el

---

lib/inets/src/ftp/ftp.erl
lib/inets/src/ftp/ftp_progress.erl

Clean up the code of files under `lib/inets/src/ftp` to eliminate dialyzer warnings and make the code check for possible errors that may occur rather than just ignoring them.
The latter may cause test case failures in case there are tests that create erroneous situations but do not check for them.

ftp dialyzer fixes

---

lib/compiler/src/sys_core_fold.erl

83199af0263 refactored sys_core_fold to break out the code for the
inline_lists_funcs option to its own module. Unfortunately, it also
accidentally turned off compile-time evaluation of calls to BIFs with
wholly or partial constant arguments.
For example, the code for the following funtion gets much worse
when inline_list_funcs is used:
b() ->
R0 = #r{},
R1 = setelement(1+2, R0, "deux"),
R2 = setelement(1+3, R1, "trois"),
R3 = setelement(1+5, R2, "cinq"),
R4 = setelement(1+2, R3, "DEUX"),
R4.
ERL-285

Don't let inline_list_funcs degrade optimizations

---

lib/kernel/doc/src/file.xml

In commit 3d70cee4034e, this text was changed to suggest that a list of Unix-specific permission bits would follow, but no such list was added. Let's revert back to the previous wording, so people won't look for a list that isn't there.
NB: I'm not sure that this statement is actually true. If the list of permission bits is in fact complete, this piece of text should just be removed.

Clarify permission bits in file.xml

---

erts/doc/src/erl_driver.xml

Minor typographical error corrections for the http://erlang.org/doc/man/erl_driver.html documentation page.

Fix typos in erl_driver.xml

---

lib/ssl/doc/src/ssl_distribution.xml

Correct "...an exra distribution..." to "...an extra distribution...".

Correct spelling error in ssl_distribution.xml

---

lib/tools/src/fprof.erl

fprof did not handle this trace event. Sending to a non existing
process should not be much different from sending to an existing
process, so duplicate that logic.

handle send_to_non_existing_process trace event in fprof

---

HOWTO/INSTALL.md

**(new pull request for maint branch instead of master)**
Document the existence of the otp_build update_primary command, to verify that the bootstrap beam files match the source files.
https://bugs.erlang.org/browse/ERL-288

Add otp_build update_primary to HOWTO INSTALL

---

lib/stdlib/doc/src/proc_lib.xml
lib/stdlib/src/proc_lib.erl
lib/stdlib/test/gen_statem_SUITE.erl
lib/stdlib/test/proc_lib_SUITE.erl

This is a small and heavy change. I can do any documentation changes after the PR is approved.
This makes proc_lib behaves like a normal process as far
as exceptions are concerned.
Before this commit, the following difference could be
observed:
```
6> spawn_link(fun() -> ssl:send(a,b) end).
<0.43.0>
7> flush().
Shell got {'EXIT',<0.43.0>,
{function_clause,
[{ssl,send,[a,b],[{file,"..."},{line,275}]}]}}
ok
8> proc_lib:spawn_link(fun() -> ssl:send(a,b) end).
<0.46.0>
9> flush().
Shell got {'EXIT',<0.46.0>,function_clause}
```
After this commit, we get the following instead:
```
3> flush().
Shell got {'EXIT',<0.61.0>,
{function_clause,
[{ssl,send,[a,b],[{file,"..."},{line,275}]},
{proc_lib,init_p,3,[{file,"..."},{line,232}]}]}}
```
The stacktrace will show minor differences of course
but the …

Propagate exceptions fully when using proc_lib

---

lib/ssl/doc/src/ssl.xml
lib/ssl/src/ssl.erl
lib/ssl/src/ssl_connection.erl
lib/ssl/src/ssl_handshake.erl
lib/ssl/src/ssl_internal.hrl
lib/ssl/src/tls_handshake.erl
lib/ssl/src/tls_v1.erl
lib/ssl/test/ssl_ECC_SUITE.erl
lib/ssl/test/ssl_basic_SUITE.erl

As per RFC 4492 Sec 5.1, the preferred order of selection of named
curves is based on client preferences.
Currently, the SSL application only picks entries according to the
absolute order of entries as tracked in a hardcoded list in code.
This patch changes things so that the client-specified order is
preferred. It also allows a mode where the server can be configured to
override the client's preferred order with its own, although the chosen
ECC must still be within both lists.
Currently, this PR still lacks tests. As seen in https://github.com/erlang/otp/pull/1179, there are no good
tests for this feature as of today, so we'll have to figure that one out.
For now, I've run the existing tests with the default config to confirm
nothing broke, and ran additional manual tests by inspecting …

Add ECC curve selection order config in TLS server

---

lib/mnesia/doc/src/Mnesia_chap3.xmlsrc
lib/mnesia/src/Makefile
lib/mnesia/src/mnesia.app.src
lib/mnesia/src/mnesia.erl
lib/mnesia/src/mnesia_app.erl
lib/mnesia/src/mnesia_sup.erl

To separate concerns and reduce confusion, avoid implementing two
behaviours in a single module. Make a single start_link() helper in
mnesia_sup and remove the unused mnesia_sup:start() utility function.

Make a separate application module for Mnesia

---

lib/hipe/icode/hipe_beam_to_icode.erl
lib/hipe/icode/hipe_icode_primops.erl
lib/hipe/rtl/hipe_rtl_binary.erl
lib/hipe/rtl/hipe_rtl_binary_match.erl
lib/hipe/test/bs_SUITE_data/bs_pmatch_bugs.erl

This fixes a HiPE bug reported on erlang-questions on 2/11/2016.
The BEAM to ICode translation of the `bs_match_string` instruction,
written long ago for binaries (i.e., with byte-sized strings), tried
to do a clever translation of even bit-sized strings using a HiPE
primop that took a Size argument expressed in bytes.
ICode is not really the place to do such a thing, and moreover there
is really no reason for the HiPE primop not to take a Size argument
expressed in bits instead.  This commit changes the Size argument
to be in bits, postpones the translation of the `bs_match_string` primop
until RTL and does a proper translation using bit-sized quantities there.
Fixed in a pair-programming/debugging session with @margnus1.

hipe: bs_match_string bug fix

---

lib/kernel/doc/src/gen_tcp.xml
lib/kernel/doc/src/gen_udp.xml
lib/kernel/src/gen_sctp.erl
lib/kernel/src/gen_tcp.erl
lib/kernel/src/gen_udp.erl

Both for gen_tcp and gen_udp controlling_process/2 can return badarg if
erlang:port_connect/2 fails with badarg. This can easily happen if the
new owner is not alive but in some race condition also when the socket
is closed right before port_connect/2 (and after the previous socket
function)
This commit documents this behaviour.
Probably the same is true for gen_sctp but I did not test that case.
It's maybe worth consideration to unify return values as currently
`{error, closed}`, `{error, einval}` and `{error, badarg}` can all be returned
depending on when exactly the socket is closed.

controlling_process can return {error, badarg}

---

lib/sasl/src/systools_make.erl
lib/sasl/test/systools_SUITE.erl

The default value for `mod` if it is not specified in the `.app` file is `[]`. But if the value is set to that default in the `.app` file it return the error, `Missing parameter in .app file: mod`. This patch makes it accept the default value as a valid configuration.

accept default value of 'mod' in .app as valid

---

lib/hipe/llvm/hipe_llvm_main.erl
lib/hipe/llvm/hipe_rtl_to_llvm.erl

This PR contains two fixes to ErLLVM.
One is a workaround to an LLVM bug (present as of 3.9), which fixes ERL-292.
One is a bug fix to ErLLVM itself, which caused LLVM to assume atoms were "aligned", and optimise away type tests. This can be reproduced with LLVM 3.7 and newer.
Both of these issues can be tested for by simply running the HiPE test suite with LLVM 3.9 present in $PATH.

ErLLVM: Fix issues with LLVM 3.7 and 3.9

---

erts/configure.in
erts/emulator/Makefile.in

This is an attempt to fix https://bugs.erlang.org/browse/ERL-294
by letting configure disable position independent executable (PIE) if
* PIE is enabled by default
* and hipe is enabled
* and architecture is x86_64 (amd64)
I encourage stake holders to test this before we merge into maint for OTP-19.2.

Disable -fPIE for HiPE on x86_64

---

lib/odbc/configure.in

Update to look for -lodbc as well as default to /usr/local as you will need to brew install libiodbc or brew install unixodbc.
Also if you are still having issues it might be because cpp isn't looking in the /usr/local/include folder for includes. If so run: xcode-select --install
Fixes: https://bugs.erlang.org/browse/ERL-121

Fix ODBC Support On Mac

---

lib/stdlib/src/sets.erl

Functions sets:add_element/2 and sets:del_element/2 modify for best performance.
Change sets:add_element/2. Function updates bucket in a set only when no such element in this bucket.
Change sets:del_element/2. Function updates bucket in a set only when element exists in this bucket.
This change makes sets more productivity. For example, in my synthetic test function union/2 becomes faster in ~219 times
Code of test:
```
-module(set_test).
-export([test/0]).
test() ->
io:format("generating data...~n"),
Set1 = generate_set(0, 999999),
Set2 = generate_set(0, 999999),
io:format("starting test...~n"),
{Time1, R1} = timer:tc(sets, union, [Set1, Set2]),
io:format("time old sets: ~p~n", [Time1]),
{Time2, R2} = timer:tc(sets2, union, [Set1, Set2]),
io:format("time new sets: ~p~n", [Time2]), …
```

Boost add_element and del_element functions in sets

---

lib/stdlib/doc/src/rand.xml
lib/stdlib/src/rand.erl
lib/stdlib/test/rand_SUITE.erl

Jump functions returns the state after performing jump calculation to a rand module internal state, which is equivalent to perform a large number of calls of calculating new states for XorShift*/+ algorithms. This PR adds jump functions for exsplus and exs1024 algorithms, and two
wrapper functions `rand:jump/0` and `rand:jump/1`, which has the random number state in the process dictionary and in the function argument, respectively.  The wrapper functions will cause error with reason `not_implemented` if the jump function for the algorithm is not implemented, such as in case of the exs64 algorithm.
(This explanation is updated as `rand:jump/0` is added to the original proposal)

Add rand:jump/{0,1} functions

---

lib/mnesia/src/mnesia_lib.erl
lib/mnesia/test/ext_test.erl

Continuations returned from mnesia_ext backends were originally wrapped with
the backend module, but that was a remnant of the earliest implementation,
and is not actually needed, since Mnesia already knows what the table
storage type is when it applies the continuation. When mnesia_ext was ported
to OTP 19, the wrapper got changed to use the table type alias instead of
the module, which triggered an error in the mnesia_eleveldb backend. This
patch removes the wrapping completely.

Don't wrap continuations from mnesia_ext backends

---

lib/stdlib/doc/src/supervisor.xml
system/doc/design_principles/sup_princ.xml

Additional details on the behavior of supervisors when reaching maximum restart intensity, as stated by @rvirding at [Medium](https://medium.com/@rvirding/actually-this-is-not-weird-but-quite-logical-ddeb7c902017#.oc8sqh44b)

Expand on the behavior of supervisors

---

.travis.yml

Travis has crashed several times because of the memory limit
of 2Gb has been exceeded. Try to fix that by analyzing fewer
applications.

Attempt to save memory by dialyzing fewer applications

---

lib/stdlib/doc/src/orddict.xml
lib/stdlib/doc/src/ordsets.xml

Right now the exact order of elements is not specified, yet many
programs rely on the ordering being the obvious one - erlang term order.
It is only beneficial to make this an explicit part of the
documentation.

Document the ordering used in ordsets and orddicts

---

lib/kernel/doc/src/rpc.xml

If `{yield,nb_yield}()` is called from a different pid from which `rpc:async_call()` was made, it will never yield.  
This is a documentation fix, as requested in https://bugs.erlang.org/browse/ERL-302

document `{yield/nb_yield}()` limitation

---

lib/hipe/icode/hipe_icode_call_elim.erl
lib/hipe/main/hipe.erl
lib/hipe/main/hipe.hrl.src
lib/hipe/test/maps_SUITE_data/maps_redundant_branch_is_key.erl

It will now print the MFA/module being compiled, and pretty-print the backtrace with
`lib:format_stacktrace/4`.
Additionally, the `error_msg/2` macro in `hipe.hrl` will now respect the
`HIPE_LOGGING` define, since messages produced by this macro just before
runtime shutdown were sometimes lost (since `code_server:error_msg/2` is
asynchronous).

HiPE: Better crash message for internal errors and fix icode_call_elim crash

---

lib/kernel/doc/src/inet.xml

Documentation for the `priority` option is found twice in the inet docs. This commit removes the least interesting of the two.
Other location: https://github.com/essen/otp/blob/d1301e814920bde89dec4acfab58d0f2600e2b78/lib/kernel/doc/src/inet.xml#L1074

Remove duplicate docs for the priority inet option

---

.travis.yml

We were somewhat conservative in how many applications we tried
to analyze. Now that the current set of applications seems to work
fine, be brave and try some more applications. Note the other
applications are not free from "unmatched return" warnings.

Travis: Generate dialyzer warnings for more applications

---

lib/stdlib/doc/src/assert_hrl.xml
lib/stdlib/include/assert.hrl

For all assert macros in assert.hrl, add corresponding versions with an
additional last Comment argument, assumed to be chardata. If an
exception occurs, it will contain an entry {comment, Comment}, which a
reporting tool may pretty-print for better readability.
Note: I chose to duplicate code rather than resort to complicated nested macros or run-time conditionals. The normal asserts have not changed and do not contain the {comment,...} tuple to avoid compatibility issues.

Add comment-versions of assert macros

---

erts/preloaded/src/Makefile
lib/asn1/test/Makefile
lib/common_test/src/unix_telnet.erl
lib/compiler/doc/src/compile.xml
lib/crypto/src/Makefile
lib/debugger/src/Makefile
lib/diameter/test/diameter_capx_SUITE.erl
lib/eunit/src/Makefile
lib/observer/src/cdv_wx.erl
lib/os_mon/src/Makefile
lib/otp_mibs/src/Makefile
lib/parsetools/src/Makefile
lib/stdlib/src/erl_lint.erl
lib/stdlib/test/epp_SUITE.erl
lib/stdlib/test/erl_lint_SUITE.erl
lib/stdlib/test/qlc_SUITE.erl
lib/stdlib/test/shell_SUITE.erl
lib/tools/emacs/erlang-flymake.el

I think it's time to start warning for the use of export_all by default. This should never be left in the code by mistake, as it often ends up being. If you use it in production, you should know about it and suppress warnings explicitly.
Also, fix up some leftovers from when warn_obsolete_guard got enabled by default, in particular the documentation.

Default compiler flags

---

lib/mnesia/src/mnesia.erl

The result from mnesia_schema:get_table_properties(Tab) is sorted, but this map operation breaks the ordering, so it should be sorted again.

Preserve key order in mnesia:table_info

---

lib/inets/src/http_client/httpc_handler.erl

Previously errors from TLS tunnel requests were sent to the same httpc_handler process which exits after sending the error to itself and the error is lost. This caused the process initiating the request to hang forever since the request timeout is not started until the first non-tunneled request is sent.
It is safe to set `from` to the calling process since messages will only be sent when errors occur.
I cannot create tests for this since I am unable to setup the proxy software (on macOS) needed to run the tests.

Report errors from TLS tunnel request to correct process

---

lib/compiler/doc/src/compile.xml
lib/compiler/src/beam_asm.erl
lib/compiler/test/compile_SUITE.erl

Add the option `deterministic` to make it easier to
achieve reproducible builds.
This option omits the {options,...} and {source,...} tuples in
M:module_info(compile), because those options may contain absolute
paths.
The author of ERL-310 suggested that only compiler options that
may contain absolute paths (such as {i,...}) should be excluded. But I
find it confusing to keep only some options.
Alternatives considered: Always omitting this information. Since this
information has been available for a long time, that would probably
break some workflows. As an example that some people care about
{source,...}, 2d785c07fbf9 made it possible to give a compiler option
to set {source,...}.
ERL-310

Add option 'deterministic' for reproducible builds

---

erts/emulator/hipe/hipe_bif0.c

Commit 8bb80fe76f5b by @sverker replaced the `__arm__` macro used to test for the arm
architecture in `hipe_bif0` with the `arm` macro, which is not universally
available. As this replacement is not motivated in the commit message,
nor replicated in any other file that uses the `__arm__` macro, this
seems to be an accident, and this PR reverts the replacement.
When compiled in an environment without the `arm` macro, upgrading hipe
code would occasionally not patch relocations to the new module due to
being out of range for a shortjump, and a trampoline not being provided
to do a longjump. Since this type of relocation patches are not expected
to be able to fail, there is no error handling and aside from a
`hipe_redirect_to_module: patch failed` message, code upgrade would
proceed and lead …

erts: Fix missing HiPE trampolines on arm (master only)

---

lib/stdlib/src/gen_server.erl
lib/stdlib/test/gen_server_SUITE.erl

When a gen_server crashes it is in many cases helpful to know in which
context its client made its call.

Printout the client stacktrace when a gen_server crashes

---

.travis.yml
erts/emulator/test/emulator_smoke.spec
scripts/run-smoke-tests

Travis CI already runs some tests suites, but the result of tests were not checked. In fact, two test cases always failed.
This pull request omits three problematic test cases from the smoke test spec, two of which always failed when run in Travis CI. The second commit adds a check of the test case logs to ensure that Travis CI fails if any of the test cases fail.

Make sure that Travis fails when test cases fail

---

lib/stdlib/src/escript.erl
lib/stdlib/test/escript_SUITE.erl
lib/stdlib/test/escript_SUITE_data/two_lines

The current implementation assumes that escripts all have at least
three lines. But according to the escript documentation, comments
on the second line and emulator flags on the third line are all
optional. Thus escripts with only two lines -- shebang on the
first line and code on the second line -- will not run. This commit
fixes the problem by rearranging the escript header parsing logic,
and recognize the escript body on the second line if the header only
contains a line of shebang.
Issue: [https://bugs.erlang.org/browse/ERL-314](https://bugs.erlang.org/browse/ERL-314)

Allow escripts with only two lines

---

.dir-locals.el

Add a .dir-locals.el file, which applies indentation-related settings
when editing any file in the project with Emacs.
Inspired by #1278, which recommends certain Emacs settings to comply with the coding standard. Let's have those settings apply automatically.

Add project-wide Emacs settings file

---

lib/stdlib/doc/src/dict.xml
lib/stdlib/doc/src/gb_trees.xml
lib/stdlib/doc/src/orddict.xml
lib/stdlib/src/dict.erl
lib/stdlib/src/gb_trees.erl
lib/stdlib/src/orddict.erl
lib/stdlib/test/dict_SUITE.erl
lib/stdlib/test/dict_test_lib.erl

Similar to maps:take/2, add take/2 to the other dictionary
modules in STDLIB:
orddict:take(Key, Dict) -> {Val,NewDict} | 'error'.
dict:take(Key, Dict) -> {Val,NewDict} | 'error'.
gb_trees:take(Key, Dict) -> {Val,NewDict}.
For gb_trees also add:
gb_trees:take_any(Key, Dict) -> {Val,NewDict} | 'error'.
gb_trees already has delete() and delete_any(), so we will
follow that design pattern.
Suggested by Boris Bochkaryov in https://github.com/erlang/otp/pull/1209.

Add take/2 to all dictionary modules

---

lib/compiler/src/compile.erl

Rewrite `compile` so that it does not keep the code from two compiler passes in memory at once. The main reason is to help dialyzer reduce memory usage, but it could possibly also improve performance when compiling huge files.

Reduce memory consumption during compilation

---

erts/etc/common/heart.c
lib/kernel/doc/src/heart.xml
lib/kernel/src/heart.erl
lib/sasl/test/release_handler_SUITE_data/start
lib/sasl/test/release_handler_SUITE_data/start_client

Hardware watchdog support was removed from heart in R13A, but there were
still some vestiges in the code and the documentation.
- Remove mentions of the HW_WD_DISABLE variable, as it's no longer used.
- Remove the HEART_BEAT_BOOT_DELAY variable, as it was only used for the
hardware watchdog.

Remove vestiges of watchdog support in heart

---

erts/doc/src/erlang.xml
erts/emulator/beam/erl_bif_info.c
erts/emulator/test/process_SUITE.erl

The BIF process_info(Pid, current_stacktrace) truncates the
stacktrace. The old behavior was to truncate long stacktraces to max
8 items. And this was hard coded. Now it is truncated to the value of
system_flag(backtrace_depth) instead. The backtrace_depth defaults to
8, but is configurable.

Make depth of current_stacktrace configurable

---

system/doc/tutorial/c_portdriver.xmlsrc

Generated shared library without `.so` suffix on Linux and by name of `exampledrv` will fail to load.

Fix wrong shared library name in Interoperability Tutorial

---

lib/crypto/c_src/crypto.c
lib/crypto/test/crypto_SUITE.erl

This commit reactivates chacha20_poly1305 and fixes the imprementation
for the released OpenSSL 1.1.0 or later.

crypto: Support chacha20_poly1305

---

lib/dialyzer/test/small_SUITE_data/results/chars
lib/dialyzer/test/small_SUITE_data/src/chars.erl
lib/hipe/cerl/erl_types.erl
lib/stdlib/src/erl_eval.erl
lib/stdlib/src/erl_parse.yrl

Characters ($char) can be used in constant pattern expressions. They
can also be used in types and contracts.

stdlib: Allow characters in types and constant patterns

---

system/doc/efficiency_guide/binaryhandling.xml
system/doc/efficiency_guide/commoncaveats.xml
system/doc/efficiency_guide/functions.xml
system/doc/efficiency_guide/introduction.xml
system/doc/efficiency_guide/listhandling.xml
system/doc/efficiency_guide/processes.xml

Many sections last had a major update for the R12 release. Since R12 was released some time ago, we can stop pretending that everything released in R12 is brand new.

Remove obsolete information from the Efficiency Guide

---

lib/kernel/doc/src/code.xml
lib/kernel/doc/src/config.xml
lib/kernel/doc/src/seq_trace.xml
lib/stdlib/doc/src/ets.xml
lib/stdlib/doc/src/gen_fsm.xml
lib/stdlib/doc/src/gen_server.xml

In the documentation for Kernel and STDLIB, I have removed references to OTP R12B and earlier releases. Exceptions: I have kept the references in the documentations `global` and `error_logger` documentation because there still exist options to revert to a previous behavior.

Kernel/STDLIB: Remove references to OTP R12B and earlier

---

system/doc/reference_manual/character_set.xml
system/doc/reference_manual/data_types.xml
system/doc/reference_manual/errors.xml
system/doc/reference_manual/expressions.xml
system/doc/reference_manual/introduction.xml
system/doc/reference_manual/macros.xml
system/doc/reference_manual/records.xml

Stop mentioning when a change occurred if it occurred before R13A.

Reference Manual: Remove references to OTP releases before R13A

---

lib/compiler/src/sys_core_fold.erl

Code with huge literal case expressions such as the following would compile very slowly:
case "Very long literal string (thousands of characters)..." of
.
.
.
end.

Improve compilation speed for huge literal case expressions

---

.travis.yml

Now that dialyzer has been optimized for memory usage, it should be possible to run dialyzer in one go and not run out of memory.

Travis: Simplify running of dialyzer

---

lib/xmerl/src/xmerl_scan.erl
lib/xmerl/test/xmerl_SUITE.erl

With the `default_attrs` option set to `true`, xmerl_scan was replacing the attributes for each element with the default attributes, discarding any attributes which were explicitly set.
The new behaviour appends the default attributes, keeping the explicit attributes intact.
The new test I've added for this change tests two documents to ensure both attributes exist in each case:
```xml
<!DOCTYPE doc [<!ATTLIST doc b CDATA "default">]>
<doc a="explicit"/>
```
```xml
<!DOCTYPE doc [<!ATTLIST doc b CDATA "default">]>
<doc b="also explicit" a="explicit"/>
```
Prior to this change, the `a` attribute was not included in the parsed structure.

Include explicit attrs when default_attrs=true

---

lib/compiler/src/Makefile
lib/compiler/src/beam_a.erl
lib/compiler/src/beam_asm.erl
lib/compiler/src/beam_block.erl
lib/compiler/src/beam_bs.erl
lib/compiler/src/beam_bsm.erl
lib/compiler/src/beam_clean.erl
lib/compiler/src/beam_dead.erl
lib/compiler/src/beam_dict.erl
lib/compiler/src/beam_except.erl
lib/compiler/src/beam_flatten.erl
lib/compiler/src/beam_jump.erl
lib/compiler/src/beam_listing.erl
lib/compiler/src/beam_peep.erl
lib/compiler/src/beam_receive.erl
lib/compiler/src/beam_reorder.erl
lib/compiler/src/beam_split.erl
lib/compiler/src/beam_trim.erl
lib/compiler/src/beam_type.erl
lib/compiler/src/beam_utils.erl
lib/compiler/src/beam_validator.erl
lib/compiler/src/beam_z.erl
lib/compiler/src/cerl.erl
lib/compiler/src/compile.erl
lib/compiler/src/core_scan.erl
lib/compiler/src/sys_pre_attributes.erl
lib/compiler/src/v3_codegen.erl
lib/compiler/src/v3_kernel_pp.erl
lib/compiler/src/v3_life.erl
lib/compiler/src/v3_life.hrl

All exported functions now have specs. Also, except for the records in `core_parse.hrl` and `v3_kernel.hrl`, all record fields now have types.

Add types and specs for all compiler modules

---

lib/ssh/src/ssh_sftpd_file_api.erl

The `State` seems to have been included twice in 91acfc.

ssh: Correct ssh_sftpd_file_api dialzyer spec

---

lib/crypto/src/crypto.erl

Fix https://bugs.erlang.org/browse/ERL-336.

Add a missing aes_gcm -spec clause to crypto:block_encrypt/4

---

README.md

The README stated that in order to contribute I should search 
> for issues with the status *Contribution Needed*
Browsing https://bugs.erlang.org/ it seems the status got renamed to "Help Wanted."
This PR updates the README accordingly.

Fix JIRA issue status for wanted contributions

---

lib/observer/src/cdv_detail_wx.erl
lib/observer/src/observer_app_wx.erl
lib/observer/src/observer_lib.erl
lib/observer/src/observer_port_wx.erl
lib/observer/src/observer_procinfo.erl
lib/observer/src/observer_tv_wx.erl
lib/observer/src/observer_wx.erl
lib/observer/test/observer_SUITE.erl

- start erl
- run observer:start()
- Click the “Applications” tab
- Double click on the “standard_error” process in the kernel application supervisor graph
- Click on a #Port<..> under links
- Observer crash

Fix observer application crash

---

system/doc/design_principles/sup_princ.xml

The question "what values should I use for intensity/period in my supervisor" has been asked by both beginners and experienced people for a couple of decades, and it's always been hard to give a good answer. The Erlang documentation has nothing much helpful to say about this important choice. In this patch, I have tried to summarize how I think about these things nowadays, and make it accessible even for beginners. The OTP Design Principles section on Supervisor Maximum Restart Intensity seemed the best place for it.
Comments welcome.

Add restart intensity howto section to design principles doc

---

erts/doc/src/erl_ext_dist.xml
erts/doc/src/erlang.xml
erts/emulator/beam/atom.c
erts/emulator/beam/atom.h
erts/emulator/beam/beam_load.c
erts/emulator/beam/bif.c
erts/emulator/beam/erl_unicode.c
erts/emulator/beam/global.h
erts/emulator/beam/utils.c
erts/emulator/test/bif_SUITE.erl
erts/emulator/test/code_SUITE.erl
lib/compiler/src/beam_asm.erl
lib/compiler/src/beam_dict.erl
lib/compiler/src/compile.erl
lib/compiler/test/compile_SUITE.erl
lib/compiler/test/compile_SUITE_data/simple.erl
lib/compiler/test/lc_SUITE.erl
lib/kernel/test/code_SUITE.erl
lib/stdlib/src/beam_lib.erl
lib/stdlib/test/beam_lib_SUITE.erl
lib/stdlib/test/erl_scan_SUITE.erl

The new chunk stores atoms encoded in UTF-8.
This is still work in progress and the following tasks are still pending:
1. add a new function, used by both erts_atom_put and binary_to_atom, that properly encodes the two kinds of errors so we can act accordingly
2. change binary_to_atom to only raise badarg and no longer raise on system_limit
3. compute the size in the `binary_to_atom` BIF and continue raising a system limit error (effectively traversing the binary twice)
Thoughts? Any other options? Once this is changed, the docs shall be properly updated.
Feedback request:
1. `beam_lib` has been modified to support a new 'utf8_atoms' chunk that maps to the new "AtU8" chunk. This means accessing the old "Atom" chunk can now be missing although it is straight-forward to handle it with a …

Add new AtU8 beam chunk

---

erts/emulator/beam/atom.names
erts/emulator/beam/bif.c
erts/emulator/beam/bif.tab
erts/emulator/beam/break.c
erts/emulator/beam/erl_bif_os.c
erts/emulator/beam/erl_init.c
erts/emulator/beam/global.h
erts/emulator/beam/register.c
erts/emulator/beam/sys.h
erts/emulator/sys/common/erl_poll.c
erts/emulator/sys/unix/sys.c
erts/emulator/sys/win32/sys.c
erts/emulator/test/Makefile
erts/emulator/test/os_signal_SUITE.erl
erts/emulator/test/os_signal_SUITE_data/Makefile.src
erts/emulator/test/os_signal_SUITE_data/os_signal_nif.c
lib/kernel/doc/src/kernel_app.xml
lib/kernel/doc/src/os.xml
lib/kernel/src/Makefile
lib/kernel/src/erl_signal_handler.erl
lib/kernel/src/kernel.app.src
lib/kernel/src/kernel.erl
lib/kernel/src/os.erl

In todays Erlang runtime system OS signals cannot be handled by an Erlang developer. Some signals are used internally by `erts`, for instance
* `SIGUSR1` is used to generate crashdumps,
* `SIGUSR2` is used to halt threads in a crashdump,
* `SIGQUIT` is used to halt Erlang immediately,
* `SIGINT` is used for a break-handler which is only intended to be used for debugging and
* `SIGTERM` (from 19.3) will halt Erlang via init:stop/0.
With this PR a `gen_event` server, `erl_signal_server`, is started to handle enabled signals from the operating system. A default handler is installed to mimic the previous behavior of above signals except for `SIGINT`. The break-handler still uses `SIGINT` internally.
Subscribable signals with this PR are: `SIGHUP`, `SIGILL`, `SIGABRT`, `SIGALRM`, `SIGTERM`, …

RFC: Signal Service for OS Signals

---

lib/kernel/src/file.erl

… file:path_open.
Problem description:
If for erlc use flag -I with some file (not a directory), compiler stops to search with {error, enotdir}.
Need to continue search in all pathes with option -I.

file: match enoent and enotdir in path_open

---

lib/kernel/src/error_logger.erl
lib/kernel/src/rpc.erl
lib/kernel/test/error_logger_SUITE.erl
lib/kernel/test/rpc_SUITE.erl

Performance for processes that receive huge amounts of
messages can be increased by storing the incoming messages
outside the heap (that avoids copying the message in a
garbage collection).
Two OTP processes that are known to receive many messages
are 'rex' (used by 'rpc') and 'error_logger'.

Store messages for 'rex' and 'error_logger' off heap

---

lib/tools/emacs/erlang-start.el
lib/tools/emacs/erlang-test.el
lib/tools/emacs/erlang.el

Only the xref front-end introduced in Emacs 25 consider arity.  It is
not implemented for older emacsen.
Look for manual page files in lib/erlang/man in erlang-root-dir.  Also
do not give up in erlang-man-module when not finding the manual page
file.  Call manual-entry as a fallback.
Do not bother to populate menu-bar with man pages when menu-bar-mode
is nil.
Add erlang extensions also to dired-omit-extensions.
Remove some support for Emacs 18 and 19.

Emacs: Consider arity when jumping to definitions

---

erts/test/system_smoke.spec

For the benefit of Travis CI, include more test cases from
otp_SUITE in the smoke test. That will avoid having to run
a pull request through the daily builds to find those kind
of minor issues.

Include more otp_SUITE tests cases in the smoke test

---

.travis.yml
scripts/build-otp

The huge log files are problematic. Add shell scripts that
captures the log output to a temporary file and only display
the log file if an error occurs.

Reduce size of the log file for Travis CI

---

lib/observer/src/cdv_bin_cb.erl

In the observer UI, when inspecting state, the error given when attempting to convert a bad term contains a spelling mistake.

Fix observer term conversion error spelling

---

lib/hipe/main/hipe.erl
lib/kernel/doc/src/kernel_app.xml
lib/stdlib/doc/src/c.xml
lib/stdlib/doc/src/filelib.xml
lib/stdlib/doc/src/filename.xml
lib/stdlib/doc/src/shell.xml
lib/stdlib/src/c.erl
lib/stdlib/src/filelib.erl
lib/stdlib/src/filename.erl
lib/stdlib/src/otp_internal.erl
lib/stdlib/src/shell_default.erl
lib/stdlib/test/filelib_SUITE.erl
lib/stdlib/test/filename_SUITE.erl
lib/stdlib/test/shell_SUITE.erl
lib/syntax_tools/src/igor.erl

(This is a much-reworked version of functionality that we've been using at Klarna for many years.)
This extends the shell function c/1 and c/2 so that if the argument is a module name instead of a file name, it automatically locates the .beam file and the corresponding source file, and then recompiles the module using the same compiler options (plus any options passed to c/2). If compilation fails, the old beam file is preserved. Also adds c(Mod, Opts, Filter), where the Filter argument allows you to remove old compiler options before the new options are added.

Extend shell c(...) to find and recompile modules

---

lib/compiler/doc/src/compile.xml
lib/compiler/src/beam_asm.erl
lib/compiler/src/compile.erl
lib/compiler/test/compile_SUITE.erl

This allow languages such as Elixir and LFE to attach
extra chunks to the .beam file without having to parse
the beam file after compilation.
This commit also cleans up the interface to beam_asm,
allowing chunks to be passed from the compiler without
a need to change beam_asm API on every new chunk.

Add extra_chunks option to compile

---

lib/stdlib/src/erl_expand_records.erl

I was also planning to skip the pass altogether if no records were defined
however the current pass is also expanding imports, therefore we need
to always run it.

Use maps instead of dict in erl_expand_records

---

lib/stdlib/src/io_lib_format.erl
lib/stdlib/test/io_SUITE.erl

26b59dfe67e introduced support for arbitrary Unicode characters in
atoms. After this commit, it is possible to print any atom with
a "~s" format string:
1> io:format("~s\n", ['спутник']).
спутник
Note that the same text as a string will fail:
2> io:format("~s\n", ["спутник"]).
in function  io:format/3
called as io:format(<0.53.0>,"~s\n",
[[1089,1087,1091,1090,1085,1080,1082]])
Being more permissive for atoms is probably beneficial for io:format/2.
However, for io_lib:format/2, the new behavior breaks this guarantee
in the documentation for io_lib:format/2:
If and only if the Unicode translation modifier is used in
the format string (that is, ~ts or ~tc), the resulting list
can contain characters beyond the ISO Latin-1 character range
(that is, numbers > …

Make "~s" fail for Unicode atoms

---

lib/ssh/src/ssh_sftpd.erl
lib/ssh/test/ssh_sftpd_SUITE.erl

Relative path handling fixed to allow opening a file
by a path relative to the current working directory.

Fix relative path handling in sftpd

---

lib/ssh/src/ssh_sftpd.erl
lib/ssh/test/ssh_sftpd_SUITE.erl

The SFTPD server should use root_dir and cwd when resolving
file paths, if both are provided. The root directory should
be used for resolving absolute file names, and cwd should
be used for resolving relative paths.

Consider root_dir and cwd in ssh_sftpd, if both are provided

---

lib/erl_interface/doc/src/erl_call.xml

In the efficiency guide, note that support for "tuple funs" was
removed in R16B.
Remove use of tuple fun from erl_call documentation.  It seems like
fun math:sqrt/1 isn't parsed correctly by erl_call, so I replaced the
example with a simpler one that doesn't require a fun.

Documentation: tuple funs are unsupported

---

system/doc/reference_manual/introduction.xml

I don't see why this should point to `process_flag/2`. Let's make it not
do that.

Documentation: fix link to erlang(3) man page

---

lib/ssl/doc/src/ssl_session_cache_api.xml

The size/1 callback was added as a non-optional callback in
42b8a29dbae1d626f32bc16dd81a129caf741138 but wasn't added to the
documentation for the ssl_session_cache_api behavior.
Signed-off-by: Steven Danna <steve@chef.io>

Document ssl_session_cache_api's size/1 callback

---

erts/doc/src/erl_nif.xml
erts/emulator/beam/erl_alloc.c
erts/emulator/beam/erl_alloc.types
erts/emulator/beam/erl_driver.h
erts/emulator/beam/erl_drv_nif.h
erts/emulator/beam/erl_nif.c
erts/emulator/beam/erl_nif.h
erts/emulator/beam/erl_nif_api_funcs.h
erts/emulator/beam/global.h
erts/emulator/sys/common/erl_check_io.c
erts/emulator/sys/common/erl_check_io.h
erts/emulator/sys/common/erl_poll.c
erts/emulator/sys/unix/sys.c
erts/emulator/test/nif_SUITE.erl
erts/emulator/test/nif_SUITE_data/nif_SUITE.c

Function `enif_select()` is a new way for NIFs to wait for asynchronous notifications
when file descriptors become ready for either read or write operations.
Similar to `driver_select()` but for NIFs, with no need for dedicated threads
(custom, async or dirty) to do the waiting.
In short a NIF calls `enif_select()` for a file descriptor
then returns to Erlang to wait for a `ready_input` or `ready_output` message
then makes a NIF call to continue read or write.
**The purpose of this PR is mainly for people to try it out and give some early feedback on the API.**
For usage documentation see `erl_nif.xml` or the nif_SUITE:select test case code in this PR.
I have also done two example usages in this separate branch https://github.com/sverker/otp/commits/sverker/enif_select-examples:
* …

enif_select() for asynchronous IO notifications

---

lib/stdlib/doc/src/filename.xml
lib/stdlib/src/filename.erl
lib/stdlib/test/filename_SUITE.erl

Add safe_relative_path/1 to guard against directory traversal
attacks. It either returns a shorter path without any ".." or
"." components, or 'unsafe' if an ".." component would climb
up above the root of the relative path. Here are a few
examples:
```
safe_relative_path("a/b/..") => "a"
safe_relative_path("a/..") => ""
safe_relative_path("a/../..") => unsafe
safe_relative_path("/absolute/path") => unsafe
```
The returned path can be used directly or combined with an
absolute path using filename:join/2.

filename: Add safe_relative_path/1

---

erts/emulator/beam/erl_process.h
erts/emulator/hipe/hipe_mode_switch.c
lib/hipe/llvm/hipe_llvm.erl
lib/hipe/main/hipe.erl

LLVM<3.9 hard-codes an ERTS-internal PCB offset that was going to be changed in R19. Workarounds were implemented (see #1038) while LLVM was generalised so that the PCB offset did not need to be hard-coded. That generalisation was released with LLVM 3.9 (see https://reviews.llvm.org/D20363), and with this PR, those workarounds are dropped, removing ErLLVM support for LLVM<3.9 in R20.

ErLLVM: Drop support for LLVM<3.9 in R20

---

lib/ssh/doc/src/using_ssh.xml

In the SSH User's Guide, section 2.8 'Creating a Subsystem' uses
behaviour(ssh_subsystem) but should use behaviour(ssh_daemon_channel).
The renaming was updated in the Reference Manual but never reflected
in the User's Guide.

Documentation: use behaviour(ssh_daemon_channel)

---

lib/asn1/doc/src/asn1_getting_started.xml
lib/asn1/src/asn1ct_constructed_per.erl
lib/asn1/src/asn1ct_gen.erl
lib/asn1/src/asn1ct_imm.erl
lib/asn1/src/asn1rtt_per_common.erl
lib/asn1/test/asn1_SUITE_data/Prim.asn1
lib/asn1/test/ber_decode_error.erl
lib/asn1/test/testChoPrim.erl
lib/asn1/test/testInfObjectClass.erl
lib/asn1/test/testPrim.erl

The generated encode/2 and decode/2 functions can return cryptic error messages. Consider this ASN.1 spec:
T DEFINITIONS AUTOMATIC TAGS ::=
BEGIN
S ::= SEQUENCE {
b BOOLEAN,
i INTEGER (1..100),
j INTEGER (0..7),
s OCTET STRING
}
END
In OTP 19, the error terms will look like this:
Eshell V8.2  (abort with ^G)
1> asn1ct:compile('T', [ber]).
ok
2> rr('T').
['S']
3> 'T':encode('S', #'S'{}).
{error,{asn1,{encode_boolean,undefined}}}
4> 'T':encode('S', #'S'{b=false}).
{error,{asn1,{encode_integer,undefined}}}
5> 'T':encode('S', #'S'{b=false,i=7,j=0}).
{error,{asn1,function_clause}}
Some error terms are clearer than other. In the first error term, it is clear that the error refers to the 'b' field, since there is only one BOOLEAN in 'S'. The second error term could refer to either 'i' or 'j'. …

Better error descriptions for ASN.1 encoding/decoding failures

---

erts/preloaded/src/erlang.erl
lib/asn1/src/asn1ct_check.erl
lib/asn1/test/asn1_SUITE_data/testobj.erl
lib/dialyzer/test/r9c_SUITE_data/src/inets/httpd_response.erl
lib/inets/doc/src/notes.xml
lib/inets/src/http_client/httpc_response.erl
lib/inets/test/httpd_1_1.erl
lib/orber/src/cdr_encode.erl
lib/stdlib/doc/src/notes.xml

In the docs for [erlang:statistics/1](http://erlang.org/doc/man/erlang.html#statistics-1), I noticed a typo in `RunQueueLenght`. Searching the code base revealed a few more places where this typo was made.  I fixed them all in this PR.
Note that I don't have an erlang dev environment set up so I haven't tried running anything with these changes, but since it was a mechanical find/replace in my text editor it should be ok, I think :).

Fix typos: lenght -> length

---

lib/dialyzer/src/dialyzer_plt.erl
lib/observer/src/observer_wx.erl
lib/tools/examples/xref_examples.erl

Fix for [ERL-161](https://bugs.erlang.org/browse/ERL-161).
Use `init:get_argument(home)` to find the location of the home directory. That will work on all platforms (including Windows).
Note that the run-time system will fail to start if `HOME` (or the equivalent on Windows) is not set. Therefore, it can be assumed that `init:get_argument(home)` will not fail.
This PR updates dialyzer, observer, and an xref example in tools. Other uses of `os:getenv("HOME")` are either harmless or appropriate.

Use a portable way to lookup the home directory

---

lib/tools/doc/src/make.xml
lib/tools/src/make.erl
lib/tools/test/make_SUITE.erl

This allows build scripts to use emake without needing to generate
an Emakefile before running make:all/0,1 or make:file/1,2.
Please see original Pull Request #77, which I didnt get round to
finishing before it was closed, and I deleted my previous otp fork.

tools: Allow Emake options to be passed in explicitly

---

scripts/build-otp

Travis CI will kill build jobs that have not produced output for
10 minutes.
The OTP build was never killed because of inactivity before 74796de9c7739
(which started to capture the output in a temporary file). After that
commit, now and then a build would be killed because it did not finish
in 10 minutes.
Update the build script to periodically print a ".", but only if the
size of the log file has changed. That way, if there is a real hanging
during the build, Travis CI will still kill the build.

Travis CI: Avoid that builds gets killed for inactivity

---

.travis.yml
scripts/Dockerfile.32
scripts/Dockerfile.32.ubuntu
scripts/Dockerfile.64
scripts/Dockerfile.64.ubuntu
scripts/build-docker-otp
scripts/build-otp
scripts/run-smoke-tests

* Run the smoke test for both the SMP and non-SMP run-time systems.
* Build and run smoke test Erlang/OTP on a 32-bit Ubuntu distribution using Docker.
* Only use 4 parallel `make` jobs to conserve memory (Travis will kill jobs that run out of memory).

Extend Travis CI to test more configurations

---

lib/crypto/c_src/crypto.c
lib/crypto/doc/src/crypto.xml
lib/crypto/src/crypto.erl
lib/crypto/test/crypto_SUITE.erl

This adds support for RSA key generation using `generate_key(rsa, {bits, e})` (see the [ERL-165](https://bugs.erlang.org/browse/ERL-165) bug comments section).
Key generation is slow, so this relies on being able to schedule the computation using `ERL_NIF_DIRTY_JOB_CPU_BOUND`. The test case should be automatically skipped if dirty schedulers aren't available.
I've tested this on an erlang linked against openssl 1.0.1, but it should work with 0.9.8 and 1.1.0 as well.

Add RSA key generation [ERL-165]

---

lib/eunit/doc/overview.edoc

A pair of small fixes for the EUnit documentation.

Fix small typos

---

lib/compiler/src/beam_type.erl
lib/compiler/test/beam_type_SUITE.erl

Code such as the following:
-record(x, {a}).
f(R, N0) ->
N = N0 / 100,
if element(1, R#x.a) =:= 0 ->
N
end.
would fail to compile with the following message:
m: function f/2+19:
Instruction: {fmove,{fr,0},{x,1}}
Error:       {uninitialized_reg,{fr,0}}:
This bug was introduced in 348b5e6bee2f.
Basically, the beam_type pass placed the fmove instruction in the
wrong place. Instructions that store to floating point registers and
instructions that read from floating point registers are supposed to
be in the same basic block.
Fix the problem by flushing all floating points instruction
before a call the pseudo-BIF is_record/3, thus making sure that
the fmove instruction is placed in the correct block.
Here is an annotated listing of the …

beam_type: Avoid an internal consistency check failure

---

lib/stdlib/src/otp_internal.erl

The following calls:
- `otp_internal:obsolete(rpc, safe_multi_server_call, 2).`
- `otp_internal:obsolete(rpc, safe_multi_server_call, 3).`
throw an unhandled exception.
The return value of `obsolete_1/3` is amended to match the relevant pattern of `obsolete/3`.
This bug was found using [CutEr](https://github.com/aggelgian/cuter).

Fix unhandled exceptions in otp_internal module

---

lib/parsetools/doc/src/yecc.xml

All yecc declarations must end in a dot (`.`). The code example for the
Header declaration doesn't include a trailing dot while all other code
examples do. This change adds that dot for consistency and to avoid any
potential confusion on the part of the reader.

Include ending dot in yecc's Header code example

---

erts/doc/src/erts_alloc.xml

The unit should be explicitly documented as
kilobytes to avoid ambiguity.

Fix sbct documentation

---

lib/eunit/src/eunit_surefire.erl

The surefire reports get called `TEXT-file_"foo.app".xml`, which creates all sorts of problems in the shell. I suggest that double quotes are removed like the single ones.

use normal file names for eunit reports

---

lib/stdlib/doc/src/unicode_usage.xml
lib/stdlib/src/erl_lint.erl
lib/stdlib/test/erl_lint_SUITE.erl
system/doc/reference_manual/character_set.xml

In OTP 20, all Unicode characters are allowed in atoms.
However, we have decided that we will not allow non-latin1
characters in module names in OTP 20. This restriction may
be lifted in a future major release of OTP.
Enforce the restriction in erl_lint, so that it will be a
compilation error to have a module name containing non-latin1
characters. That means that tools such as debugger, xref,
dialyzer, syntax_tools, and so on, do not have to be modified
to handle non-latin1 module names.

Don't allow module names with non-latin1 characters

---

.travis.yml

HiPE is tested when running dialyzer in the 64-bit build. To avoid
running out of memory or time, dialyzer is not run in the 32-bit
build job.
Do a smoke test of HiPE by letting dialyzer create a small PLT.
We could catch more bugs by using `configure --enable-native-libs`,
but I am worried that the build would not finish in 50 minutes
(the time limit for a Travis job).

Smoke test HiPE in the 32-bit build

---

lib/tools/src/tools.app.src

Commit d8ff1e3 removed cover_web and therefore
tools no longer depends on inets.

Remove inets from runtime dependencies in tools

---

lib/hipe/regalloc/hipe_coalescing_regalloc.erl
lib/hipe/regalloc/hipe_graph_coloring_regalloc.erl
lib/hipe/regalloc/hipe_optimistic_regalloc.erl

The register allocators accept a low-water mark called `SpillLimit`
which indicates which temporaries they must not spill. However, it
turns out they do not agree with `hipe_regalloc_loop`, which provides
`SpillLimit`, on whether it is an inclusive or exclusive bound.
This caused the register allocators to occasionally spill the first
"unspillable" temporary. This caused a failure in a newly added
assertion, added by #1380, when hipe-compiling `dets_v9` on x86.

HiPE: Fix off-by-one bug in register allocators

---

lib/hipe/arm/hipe_arm_assemble.erl
lib/hipe/llvm/hipe_llvm_merge.erl
lib/hipe/misc/hipe_consttab.erl
lib/hipe/misc/hipe_pack_constants.erl
lib/hipe/ppc/hipe_ppc_assemble.erl
lib/hipe/sparc/hipe_sparc_assemble.erl
lib/hipe/x86/hipe_x86_assemble.erl

The first commit (Fix alignment of byte-sized constants) fixes a behavior seen on NetBSD/amd64 reported as ERL-376.  The other two commits cleanup the code that handles the constant table by removing code that is no longer used.

hipe: Fix alignment of byte-sized constants

---

lib/hipe/cerl/erl_bif_types.erl
lib/hipe/icode/hipe_icode_range.erl
lib/hipe/test/basic_SUITE_data/basic_bugs_hipe.erl

HiPE's range analysis would not update the arguments of a callee when the result of the call was ignored, leading to an infinite loop in the following code, ending up in the second clause even when `N=0`:
```erlang
-module(test).
-export([f/0]).
f() ->
g(4).
g(0) ->
io:format("called with N=0! We should STOP!~n");
g(N) ->
io:format("called with N=~B~n", [N]),
receive after 250 -> ok end,
g(N - 1),
io:format("call with N=~B exiting normally~n", [N]).
```
Bug reported as [ERL-278](https://bugs.erlang.org/browse/ERL-278) by Rich Neswold.
Also: Sneak in a fix for suboptimal range analysis of the `rem` operator: the ranges would be one number too large: for example, the call `rem(any(), 9)` would result in `-9..9`, when `-8..8` would be the desired output.

HiPE: Fix ERL-278: Fix range analysis miscompilation bug

---

erts/configure.in

Some linkers, for example on Gentoo Hardened, do not accept the -no-pie
flag but require the -fno-PIE flag instead.
Plus some white-space clean-up.

Improve no-pie solution from bug report ERL-294

---

erts/emulator/beam/erl_mtrace.c
erts/emulator/drivers/common/inet_drv.c
lib/erl_interface/src/connect/ei_connect.c
lib/erl_interface/src/prog/erl_call.c
lib/ic/test/c_client_erl_server_SUITE_data/c_client.c
lib/ic/test/c_client_erl_server_proto_SUITE_data/c_client.c
lib/ic/test/c_client_erl_server_proto_tmo_SUITE_data/c_client.c
lib/ic/test/erl_client_c_server_SUITE_data/c_server.c
lib/ic/test/erl_client_c_server_proto_SUITE_data/c_server.c

Some OSes allow hostname to be 64 characters  (linux) whereas others allow 255 characters (mac). Erlang runs fine on mac with 255 characters hostname. However, on linux, it crashes if the hostname to be 64 characters. This patch fixes the issue. Further, it tries to unify the hostname handling at different places.

ERL-61: Fixes the issue where kernel crashes if the hostname is 64 characters

---

lib/asn1/src/asn1rt_nif.erl
lib/crypto/src/crypto.erl
lib/runtime_tools/src/dyntrace.erl

This is a poor man's solution that allows to build and test the
Erlang/OTP system with all files compiled to native code simply
by setting the ERL_COMPILER_OPTS environment variable.
Better solutions, like automatically setting the no_native option
whenever the compiler sees an on_load attribute, obviously exist
but require more time to implement.

Add a no_native option to modules with an on_load

---

erts/emulator/beam/bif.tab
erts/emulator/beam/erl_db.c
erts/emulator/beam/erl_db.h
erts/emulator/beam/erl_db_hash.c
erts/emulator/beam/erl_db_tree.c
erts/emulator/beam/erl_db_util.c
erts/emulator/beam/erl_db_util.h
lib/stdlib/doc/src/ets.xml
lib/stdlib/src/ets.erl
lib/stdlib/test/ets_SUITE.erl

This change introduces a new BIF, _ets:compare_insert/3_, for sets and ordered sets, which conditions object insertion based on what's in the table matching what we expect (in other words, a sort of compare-exchange for optimistic, atomic updates.)
As for the erl_db_util.h / DbTableMethod interface: I'm not sure whether having '_db_compare_put_' is better than simply extending the signature and functionality of '_db_put_', but that's fairly easy to change.
Supersedes #1074

ETS: Allow for conditional insertions

---

lib/crypto/c_src/crypto.c
lib/crypto/doc/src/crypto.xml
lib/crypto/src/crypto.erl
lib/crypto/test/crypto_SUITE.erl
lib/stdlib/doc/src/rand.xml
lib/stdlib/src/rand.erl

This PR proposes two new additions to the crypto module, both named `strong_rand_uniform,` for effortless generation of cryptographically secure numbers:
crypto:strong_rand_uniform/0: generates floats on the open interval ]0.0, 1.0[
crypto:strong_rand_uniform/1: generates integers on an arbitrary closed interval [1, N]
These follow the same interfaces as `rand:uniform/0` and `rand:uniform/1`, and both use OpenSSL's `BN_rand_range` method.
Generated floating point values are limited to an effective entropy of up to 51 bits but are expected to be uniformly distributed between 0.0 and 1.0.
Supersedes #1363.

Support generation of strong random numbers

---

lib/crypto/c_src/crypto.c
lib/crypto/src/crypto.erl
lib/crypto/test/crypto_SUITE.erl

Demonstrate and fix a bug with AES CFB 128 for certain key sizes introduced
with the Erlang 19.0 release. The code in the `block_crypt_nif` function
in the crypto.c source file incorrectly calls `aes_cfb_8_crypt` when the
specified cipher is `aes_cfb8` *or* `aes_cfb128` and the key size is 24 or
32. The `aes_cfb_8_crypt` function calls the` AES_cfb8_encrypt` function
from the openssl interface, but this is incorrect when the cipher is
`aes_cfb128`.
Unfortunately the test cases in the crypto test suite are insufficient
to detect an issue like this because it exercises the encryption and
decryption roundtrip using the same incorrect underlying function. The
problem was observed when trying to update an application to Erlang 19
that attempted to decrypt data that was encrypted using …

Crypto AES CFB 128 bugfix

---

lib/observer/doc/src/etop.xml
lib/observer/doc/src/observer.xml

My editor also killed some whitespaces at the ends of lines 😉

fix docs typo: details

---

lib/common_test/src/ct_slave.erl

This change makes how `ct_slave` handles a nodename passed by the user the same as those passed to `net_kernel` or `-sname`/`-name`. Meaning if the host is part of the nodename it is used as the host instead of appending the resolved host from the system.
Before:
``` erlang
(a@127.0.0.1)1> ct_slave:start('b@127.0.0.1').
{error,boot_timeout,'b@127.0.0.1@fanon'}
```
After:
``` erlang
(a@127.0.0.1)1> ct_slave:start('b@127.0.0.1').
{ok,'b@127.0.0.1'}
```

handle ct_slave nodename in the same way as net_kernel

---

erts/epmd/src/epmd_cli.c

Living nodes will make `epmd -kill` fail, but there's no way to tell
except by looking at the commands output. With this change, the exit
code will be 1 to indicate failure.

Don't exit 0 if killing epmd is impossible because there's living nodes

---

erts/configure.in
lib/hipe/llvm/Makefile
lib/hipe/llvm/hipe_llvm_main.erl

For some reason, when the `--enable-m32-build` configure flag was introduced, it was made to imply `--disable-hipe`. However, there is no reason for this, as a fully working HiPE-enabled VM will be built even with `--enable-m32-build`.
The only exception is ErLLVM, which would effectively be targeting a 64-bit machine, and thus be nonfunctional. By having it explicitly tell `llc` which architecture it's supposed to be compiling for, ErLLVM now works even when running a 32-bit VM on a 64-bit OS.

Allow HiPE-enabled VMs to be built with --enable-m32-build

---

erts/emulator/beam/bif.tab
erts/emulator/beam/erl_bif_re.c
lib/stdlib/doc/src/re.xml
lib/stdlib/src/re.erl
lib/stdlib/test/re_SUITE.erl

This modification is only to let to know to the Erlang coder what is the PCRE version in use compiled inside of the BEAM machine and in use by re module in a binary way:
```
> re:version().
<<"8.02 2010-03-19">>
```

Add re:version/0

---

configure.in

This fixes a mistake in 6d8c39229 where a few `enable_hipe=no` that makes the build fail when building with both `--enable-native-libs` and `--enable-m32-build` slipped through.

HiPE: Fix --enable-native-libs --enable-m32-build

---

.travis.yml
scripts/run-dialyzer

Having it in a script allows it to be called from other tools then travis-ci.

Move travis dialyzer logic to script file

---

lib/compiler/src/beam_validator.erl
lib/compiler/test/beam_type_SUITE.erl

Fixes https://bugs.erlang.org/browse/ERL-406

Make beam_validator track type formation for binary operations

---

erts/emulator/drivers/common/inet_drv.c
erts/preloaded/src/prim_inet.erl
lib/kernel/doc/src/inet.xml
lib/kernel/src/inet.erl
lib/kernel/src/inet_int.hrl
lib/kernel/test/inet_SUITE.erl
lib/runtime_tools/src/observer_backend.erl

bind to device is needed to properly support VRF-Lite under Linux (see [VRF] for details).
This is a first draft to solicit comments. Documentation and tests are missing.
Is a change/feature like this acceptable?
Are the changes generally in the right place?
[VRF]: https://www.kernel.org/doc/Documentation/networking/vrf.txt

implement SO_BINDTODEVICE for inet protocols

---

erts/emulator/sys/common/erl_mseg.c

The power-of-two cache in erl_mseg.c only handles segment up to 2GB in size.  Attempts to allocate larger segment (a valid operation) cause the SIZE_TO_CACHE_AREA_IDX() macro to return bogus negative values, resulting in out-of-bounds indexing in ->cache_powered_node[].
The simplest fix is to just not cache power-of-two segments > 2GB, which is what this patch does.
It might be possible to put such segments on ->cache_unpowered_node instead, but the logic in cache_bless_segment() looks like it really doesn't want powers-of-two segments there, so I opted not to.
Longer-term, the LOG2() and CACHE_AREAS macros need updating for 64-bit environments.

erl_mseg.c: don't use invalid indices in - > cache_powered_node[]

---

HOWTO/INSTALL.md
configure.in
erts/Makefile
erts/configure.in
erts/doc/src/erl.xml
erts/emulator/Makefile.in
erts/emulator/test/scheduler_SUITE.erl
erts/emulator/test/smoke_test_SUITE.erl
erts/emulator/test/statistics_SUITE.erl
erts/etc/common/erlexec.c
lib/hipe/rtl/Makefile
make/emd2exml.in
make/otp.mk.in
scripts/build-otp

This pr changes the default builds to not include the non-smp aka plain emulator when built. Instead you have to supply the `--enable-plain-emulator` configure option in order for it to be built.
The non-smp emulators (threaded and non-threaded) are also deprecated and a warning is printed when they are enabled.
The non-smp emulators will be removed in OTP-21.

Deprecate the non-smp emulators

---

lib/tools/emacs/erlang.el

This commit removes some compatibility for old GNU Emacs releases
and XEmacs. erlang-mode didn't really work on them for a while now,
so this is just a cleanup, nothing actually changes.
It's part of the ongoing effort to clean up and modernize the codebase
of erlang-mode.

Drop some legacy Emacs compatibility code

---

CONTRIBUTING.md

When a branch named 'maint' or 'master' is merged, the commit
message for the merge will be confusing.

Add a piece of advice against naming branches 'maint' or 'master'

---

erts/preloaded/src/add_abstract_code
lib/compiler/doc/src/compile.xml
lib/compiler/src/compile.erl
lib/compiler/src/v3_core.erl
lib/compiler/src/v3_kernel.erl
lib/compiler/test/compilation_SUITE.erl
lib/compiler/test/compile_SUITE.erl
lib/dialyzer/src/dialyzer_analysis_callgraph.erl
lib/dialyzer/src/dialyzer_plt.erl
lib/dialyzer/src/dialyzer_utils.erl
lib/dialyzer/src/typer.erl
lib/stdlib/doc/src/beam_lib.xml
lib/stdlib/src/Makefile
lib/stdlib/src/beam_lib.erl
lib/stdlib/src/erl_abstract_code.erl
lib/stdlib/src/stdlib.app.src
lib/stdlib/test/beam_lib_SUITE.erl

Many tools in the Erlang ecosystem expect the Erlang Abstract Code chunk to exist or, if it doesn't exist, it automatically generates one from the source code, if it can find the source. This restricts the usage of the tooling for some languages and leads to code duplication in different tools.
To solve this issue for languages that compile directly to Core, such as LFE, I have earlier proposed a chunk that stores Core AST. However, even if we add such chunk, I could see the following problems:
1. Storing the Core AST chunk still does not provide a feature where chunks are calculated on the fly from the source if the chunk is not present
2. Adding a new chunk could potentially make the situation worse because tools in the future may work directly on those new chunks, forcing compilers to …

Introduce new "Dbgi" chunk

---

lib/xmerl/src/xmerl_scan.erl
lib/xmerl/test/xmerl_SUITE.erl

Improves accumulator fun in `xmerl_scan` so that only one `#xmlText` record is returned for strings which have character references (e.g. `&#246;`). 
Today:
```
> xmerl_scan:string("<name>Jimmy Z&#246;ger</name>").
{{xmlElement,name,name,[],
{xmlNamespace,[],[]},
[],1,[],
[{xmlText,[{name,1}],1,[],"Jimmy Z",text},
{xmlText,[{name,1}],2,[],"öger",text}],
[],"/Users/jyzr/",undeclared},
[]}
```
As I see it, only one `#xmlText` record should be in the content of the `#xmlElement`. If there's a reason for the current behaviour, please enlighten me :)
I have not run the suites locally, hopefully there's a bot which will help me.

Improves accumulator fun in xmerl_scan

---

lib/tools/emacs/erlang.el

Fix loading of byte-compiled erlang.elc on Emacs 25
and the erlang shell.

Restore Emacs 25 support

---

erts/etc/common/ct_run.c
erts/etc/common/dialyzer.c
erts/etc/common/erlc.c
erts/etc/common/erlexec.c
erts/etc/common/escript.c
erts/etc/common/typer.c

Allows ps and htop to display the invoking program/script name
instead of beam[.smp] on unix(es).

Rename argv[0] from beam to invoking program name

---

erts/emulator/sys/common/erl_mseg.c

The macro previously named 'LOG2' is in fact computing the LSB (not the MSB)
of its input, and can only be used to compute log2(n) when n is is a power
of 2, that is, when its LSB is also its MSB.

Rename macro and add clarifying comment

---

system/doc/reference_manual/data_types.xml

see http://erlang.org/doc/reference_manual/data_types.html#id77115
```erlang
17> binary_to_float(<<"7.000e+00>>").
7.0
```

system/doc/reference_manual/: fix a typo

---

lib/compiler/src/beam_asm.erl

The undocumented compiler option 'slim' is used when compiling
the primary bootstrap. The purpose is to make the bootstrap smaller
and to avoid unnecessary churn in the git repository. That is,
the BEAM file should be different only if the actual code in the
file is different, and not if it has merely been re-compiled on
a different computer.
Two commits have fattened the 'slim' option. In 36f7087ae0f,
extra chunks are included even in slim BEAM files. In dfb899c0229f7,
the "Dbgi" were added as an extra chunk, causing it to be included
in slim files.
Make 'slim' slim again by only including the essential chunks and
the attribute chunk (as was the case before the {extra,...} option
was added).

Make 'slim' slim again

---

lib/inets/src/http_server/httpd_util.erl
lib/inets/test/httpd_basic_SUITE.erl

Rebased to master as requested in   #1404.
It causes a case-clause error, as the calender:local_time_to_universal_time_dst/1
can return an empty list, which is not currently handled.
When called with an invalid DST time:
1> httpd_util:rfc1123_date({{2017, 03, 26},{1, 0, 0}}).
** exception error: no case clause matching []
in function  httpd_util:rfc1123_date/1 (httpd_util.erl, line 334)
To alleviate this, simply add a clause to handle the empty list and return the
original time in the expected rfc1123 format. This is the approach of other
modules which make use of the calender:local_time_to_universal_time_dst/1
function. The formatted date is then returned without error:
2> httpd_util:rfc1123_date({{2017, 03, 26},{1, 0, 0}}).
"Sun, 26 Mar 2017 01:00:00 GMT"

Error when a non-DST time is passed to the httpd_util:rfc1123_date/1 function

---

erts/emulator/beam/beam_emu.c
erts/emulator/test/hipe_SUITE.erl
erts/emulator/test/hipe_SUITE_data/trycatch_1.erl
erts/emulator/test/hipe_SUITE_data/trycatch_2.erl
erts/emulator/test/hipe_SUITE_data/trycatch_3.erl

p->fvalue will be set by BIFs that generate exceptions (such as throw/1), and it will not be cleared before another exception is generated. Potentially, p->fvalue may contain a huge term (e.g. after throw(HugeTerm)) which will be kept in the heap.
We can shorten the lifetime of f->value by clearing it in the instructions that handle catches: catch_end and try_end. That is safe because BEAM code will never access p->fvalue. If BEAM code needs to rethrow an exception it will use a reference to the value passed in an X register.
The reason that p->fvalue must not be cleared already in handle_error() is that native code trap handlers will use it. (See the comment before handle_error() and the comment at the end of handle_error() in beam_emu.c for some more information about exception …

Mend p->fvalue leak

---

lib/kernel/src/kernel.erl

'modeules' -> 'modules'
Introduced in 3edc6dbf8f150bb6ba7c800ed5cc379771f8b279 (present in 20.0-rc1, but
not in the 19 release series).

Fix typo in child spec for file_server

---

lib/compiler/src/v3_kernel_pp.erl
lib/compiler/test/compile_SUITE.erl

This PR improves the coverage for UTF8 function names in compile_SUITE. Someone [reported on the mailing list](http://erlang.org/pipermail/erlang-questions/2017-May/092290.html) the feature no longer works. The test pass as of ffa80a41370025ed2fb95967e731f13cc7e45e4f but I still need to run it on latest master.
UPDATE: the test also passes on machine after rebuilding on current master.

Add a test for utf8 function names

---

lib/compiler/doc/src/compile.xml

By default, warnings for obsolete guards are turned on. Correct the description to make that clear.

Correct description of nowarn_obsolete_guard

---

lib/common_test/src/ct_run.erl
lib/common_test/src/ct_util.erl
lib/snmp/src/agent/snmp_generic.erl
lib/stdlib/src/qlc.erl

In the future (not OTP 20), `erlang:get_stacktrace/0` will probably only work inside a the `catch` block of a `try` expression. 
Fix a few modules to use `try` instead of `catch`, and move the call of the `erlang:get_stackrace/0` into the `try` expression.

Make calls to get_stacktrace/0 future-proof

---

lib/ssl/src/ssl_connection.erl

`ct` isn't always available in production environments.

removed ct:pal call in ssl_connection

---

lib/stdlib/doc/src/gen_event.xml
lib/stdlib/doc/src/gen_server.xml
lib/stdlib/doc/src/gen_statem.xml
lib/stdlib/src/gen.erl
lib/stdlib/src/gen_event.erl
lib/stdlib/src/gen_fsm.erl
lib/stdlib/src/gen_server.erl
lib/stdlib/src/gen_statem.erl
lib/stdlib/test/dummy_h.erl
lib/stdlib/test/gen_event_SUITE.erl
lib/stdlib/test/gen_fsm_SUITE.erl
lib/stdlib/test/gen_server_SUITE.erl
lib/stdlib/test/gen_statem_SUITE.erl

There are a lot of implementations of gen_server, gen_event, gen_fsm in our projects. A lot of them has have small message flow, and at present time we are doing 'hibernate' all of them manually.
So, we decided implement auto-hibernation functionality in the gen_server, gen_event, gen_fsm. In case of no any messages in gen_server, gen_event, gen_fsm during AutoHibernateTimeout milliseconds, process goes into hibernation automatically.
We think than described functionality will be useful for other developers. By default auto-hibernation functionality disable, so default behaviour for gen_server, gen_event, gen_fsm doesn't change.
We have make changed in gen_server, gen_fsm, gen_event modules. There is add unit tests for realized functionality, description for auto_hibernate_timeout option.

Auto-hibernation functionality for gen_server, gen_fsm, gen_event

---

erts/emulator/beam/big.c
erts/emulator/beam/big.h
erts/emulator/beam/erl_alloc.c
erts/emulator/beam/erl_alloc.h
erts/emulator/beam/erl_cpu_topology.c
erts/emulator/beam/erl_cpu_topology.h
erts/emulator/beam/erl_db_util.c
erts/emulator/beam/erl_gc.c
erts/emulator/beam/erl_init.c
erts/emulator/beam/erl_port_task.c
erts/emulator/beam/erl_port_task.h
erts/emulator/beam/erl_process.c
erts/emulator/beam/erl_process.h
erts/emulator/beam/global.h

The functions have been found using: https://github.com/caolanm/callcatcher

erts: Remove old unused functions

---

erts/emulator/beam/erl_nif_api_funcs.h

Looks like the underlying `Drv` type was used here instead of the `Nif` `typedef`.  The documentation and implementation for `enif_[de]monitor_process()` both use `ErlNifMonitor`.

enif_monitor_process() typo

---

erts/Makefile
erts/configure.in
erts/doc/src/erl.xml
erts/etc/common/erlexec.c
erts/etc/unix/Makefile
erts/start_scripts/Makefile
lib/tools/doc/src/lcnt_chapter.xml
lib/tools/test/lcnt_SUITE.erl
make/otp.mk.in
make/otp_subdir.mk

This PR makes it easier to run the lock-counting emulator in a production system.
There is a new behavior for this `configure` option:
./configure --enable-lock-counter
The option used to make the default emulator a lock-counting emulator. It will now build an additional emulator. `make install` will install both the standard emulator and the lock-counting emulator.
Start the lock-counting emulator like this:
erl -emu_type lcnt
The `emu_type` option can be used to start any special emulator that have been built in the `erts/emulator` directory. That is, `erl -emu_type debug` will start the emulator that has been built like this:
(cd erts/emulator && make debug)
On Windows only, `erl -debug` would start the debug-compiled emulator. That option has been removed, since `-emu_type debug` can …

Simplify building a lock-counting emulator

---

lib/tools/doc/src/lcnt.xml
lib/tools/doc/src/lcnt_chapter.xml

We generally avoid abbreviations such as "e.g." and "i.e." in
the documentation. We write "Erlang", not "erlang" (except when
referring to the erlang module).

Fix a few minor issues in the lcnt documentation

---

lib/kernel/doc/src/disk_log.xml
lib/kernel/doc/src/kernel_app.xml
lib/kernel/src/Makefile
lib/kernel/src/disk_log.erl
lib/kernel/src/disk_log.hrl
lib/kernel/src/disk_log_1.erl
lib/kernel/src/group.erl
lib/kernel/src/group_history.erl
lib/kernel/src/kernel.app.src
lib/kernel/test/disk_log_SUITE.erl

This patch adds a mechanism by which shell history gets stored
persistently on disk and gets loaded whenever a new shell session
begins.
The log files are added to the user's cache directory, with multiple
files in it, although the location is configurable.
All Erlang instances on a given host will share the same log file.
There are two hook points in group.erl that are used: when instantiating
the buffer, where we fetch from disk, and when adding a line to the
buffer (gets stored).
This allows all shell instances to use the same base set of lines when
loaded, but to keep their history separate after the fact. As lines are
added as you go, a new shell session (with ^G -> s -> c) will have
access to previous sessions' lines.
The implementation makes use of the disk_log library with a …

Shell history storage

---

lib/crypto/c_src/crypto.c

This could be a merge conflict issue after merging https://github.com/erlang/otp/commit/0a1feff48388c8430f5eebd1531f769605601fab

Remove duplicate aes_gcm from a list of ciphers

---

lib/stdlib/src/escript.erl
lib/stdlib/src/proc_lib.erl

Call `erlang:get_stacktrace` as soon as possible after an expression has been caught. Don't call other functions before calling `erlang:get_stacktrace`, since they may change the stacktrace.

Call get_stacktrace/0 in a safer way

---

system/doc/programming_examples/bit_syntax.xml

Add a link to the Reference Manual from the example page
When doing a Google search for "bit syntax", you could end up on the programming examples page about bit syntax. The example page has some reference material, but is far from complete.
Therefore, add a link to the page about bit syntax in the Reference Manual.
https://bugs.erlang.org/browse/ERL-387
There is also no longer need to mention what was changed in R12B.

Improve bit syntax example page

---

lib/kernel/doc/src/inet.xml

* IPv6 address FFFF::192.168.42.2 is an invalid form as an IPv4-mapped address.
This should be fixed as ::FFFF:192.168.42.2.
The assigned address block is ::ffff:0:0/96.
See RFC6890 Table 20 in the Section 2.2.2 for the further details.
And for this IPv4-mapped address use *only*,
the 32bit LSB of the IPv6 address can be written
with the respective IPv4 address.
See RFC4291 Section 2.2 Form 3 for the further details.

inet.xml: fix invalid IPv4-mapped-address examples

---

lib/stdlib/doc/src/string.xml
lib/stdlib/src/string.erl
lib/stdlib/src/unicode.erl
lib/stdlib/test/string_SUITE.erl
lib/stdlib/test/unicode_SUITE.erl
lib/stdlib/test/unicode_util_SUITE.erl
lib/stdlib/uc_spec/gen_unicode_mod.escript

Prior to this patch, the normalization functions in the
unicode module would raise a function clause error for
non-utf8 binaries.
This patch changes it so it returns {error, SoFar, Invalid}
as characters_to_binary and characters_to_list does in
the unicode module.
Note string:next_codepoint/1 and string:next_grapheme had
to be changed accordingly and also return an error tuple.
/cc @dgud

Return error tuple on unicode normalization functions

---

lib/compiler/src/compile.erl
lib/compiler/test/beam_validator_SUITE.erl
lib/compiler/test/compile_SUITE.erl

`compile:forms/1,2` is documented to return:
{ok,ModuleName,BinaryOrCode}
However, if one of the options 'from_core', 'from_asm', or
'from_beam' is given, ModuleName will be returned as [].
A worse problem is that is that if one those options are
combined with the 'native' option, compilation will crash.
Correct `compile:forms/1,2` to pick up the module name from
the forms provided (either Core Erlang, Beam assembly code,
or a Beam file).
Reported here: https://bugs.erlang.org/browse/ERL-417

Correct handling of module name in compile:forms/1,2

---

erts/etc/common/escript.c

Erlang system found in PATH was used even when explicitly pointing out
the escript binary in another Erlang system.

Fix erlang system lookup from escript bug introduced in PR #1293

---

lib/stdlib/src/erl_tar.erl
lib/stdlib/src/erl_tar.hrl
lib/stdlib/test/tar_SUITE.erl

Since aa0c4b0df7cdc, erl_tar would write the local time (instead of
the POSIX time) into the tar header for the archived files. When
extracting the tar file, the extracted file could be set to a future
time (depending on the time zone).
We could do a minimal fix, but this seems to be a good time
to rewrite the time handling to use the new features that
allow file info to be read and written in the POSIX time
format.
First reported here: https://github.com/erlang/rebar3/issues/1554

erl_tar: Fix handling of date and time

---

lib/crypto/c_src/crypto.c

The fix in #1393 had a backwards equality check for encrypt/decrypt. Because this is a chained cipher, the first 16 bytes end up getting 'encrypted' anyway, but after the first block, things go off the rails.
cc @IngelaAndin @kellymclaughlin

Fix backwards equality check in aes cfb128 function

---

lib/ssl/src/tls_connection.erl
lib/ssl/test/ssl_basic_SUITE.erl

The commit 8b10920 (OTP 19.3.1) fixed the non-delivery of final TLS record in {active, once}, but this causes the ssl_closed message to be lost when the TCP connection closes before ssl:close/1. The patch restores the behavior of OTP 18.
This is the second part to fix https://bugs.erlang.org/browse/ERL-420

Fix non-delivery of ssl_closed message in active once

---

erts/doc/src/erl_tracer.xml

After "Move tracer SecondTraceTerm to Opts map" in commit 115f0ba7
getting the receipient has to be done on a bit different way.

Update erl_msg_tracer example

---

erts/doc/src/erl_nif.xml
erts/emulator/beam/erl_nif.c
erts/emulator/beam/erl_nif_api_funcs.h
erts/emulator/test/dirty_nif_SUITE.erl
erts/emulator/test/dirty_nif_SUITE_data/Makefile.src
erts/emulator/test/dirty_nif_SUITE_data/dirty_nif_SUITE.c
erts/emulator/test/dirty_nif_SUITE_data/echo_drv.c
erts/emulator/test/nif_SUITE.erl
erts/emulator/test/nif_SUITE_data/nif_SUITE.c

There are cases when a NIF needs to send a message, using `enif_send()`, to a long-lived process with a registered name.
A common use-case is logging, where asynchronous fire-and-forget messages are the norm.
There can also be cases where a yielding or dirty NIF or background thread may request a callback from a service with additional information it needs to complete its operation, yielding or waiting (with suitable timeouts, etc) until its state has been updated through the NIF module's API.
NIFs can only send messages to pids, and the lack of name resolution leaves a complicated dance between separate monitoring processes and the NIF as the only way to keep a NIF informed of the whereabouts of such long-lived processes.
Providing a reliable, built-in facility for NIFs to resolve …

Add enif_whereis() function

---

lib/compiler/src/Makefile
lib/compiler/src/compile.erl
lib/compiler/src/compiler.app.src
lib/compiler/src/sys_core_bsm.erl
lib/compiler/src/sys_core_fold.erl
lib/compiler/test/bs_match_SUITE.erl
lib/compiler/test/compile_SUITE.erl
lib/compiler/test/misc_SUITE.erl
lib/compiler/test/warnings_SUITE.erl

As part of sys_core_fold, variables involved in bit syntax
matching would be annotated when it would be safe for a later
pass to do the delayed sub-binary creation optimization.
An implicit assumption regarding the annotation was that the
code must not be further optimized. That assumption was broken
in 05130e48555891, which introduced a fixpoint iteration
(applying the optimizations until there were no more changes).
That means that a variable could be annotated as safe for
reusing the match context in one iteration, but a later iteration
could rewrite the code in a way that would make the optimization
unsafe.
One way to fix this would be to clear all reuse_for_context
annotations before each iteration. But that would be wasteful.
Instead I chose to fix the problem by moving out the …

Fix unsafe bit syntax matching optimization

---

erts/configure.in
erts/emulator/beam/sys.h

We have made porting Erlang to the e2k platform (Elbrus: https://en.wikipedia.org/wiki/Elbrus-8S). This platform is uses the lcc (v1.21.18) compiler, based on the old stripped-down version of the gcc (4.8.0). Because gcc is truncated, some built-in functions do not work correctly, for example __builtin_choose_expr. In this pull request I propose a solution for this error.

Support e2k platform

---

erts/etc/common/escript.c

Fixes build warning:
```
escript.c:587:1: warning: 'push_words' defined but not used [-Wunused-function]
push_words(char* src)
^~~~~~~~~~
```

escript.c: remove dead code

---

erts/emulator/beam/beam_emu.c
lib/compiler/src/v3_core.erl
lib/compiler/test/compile_SUITE.erl

Tuple calls is the ability to invoke a function on a tuple
as first argument:
1> Var = dict:new().
{dict,0,16,16,8,80,48,
{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}
2> Var:size().
0
This behaviour is considered by most to be undesired and confusing,
especially when it comes to errors. For example, imagine you invoke
"Mod:new()" where a Mod is an atom and you accidentally pass {ok, dict}.
It raises:
{undef,[{ok,new,[{ok,dict}],[]},...]}
As it attempts to invoke ok:new/1, which is really hard to debug
as there is no call to new/1 on the source code.
Furthemore, this behaviour is implemented at the VM level, which
imposes such semantics on all languages running on BEAM.
Since we cannot remove the behaviour above, this proposal …

Make tuple calls opt-in

---

erts/configure.in

On macOS, it was not possible to start crypto after running
observer. (ERL_251)
On the beta of macOS 10.13 (High Sierra), crypto does not work
at all. (ERL-439)
The problem is that the use of the -flat_namespace option when
linking dynamic drivers such as the one for crypto. With that
option, all function names must be unique among all linked
libraries and frameworks, or the wrong function could be called.
Resolve the problem by using the two-level namespace as recommended by
Apple. We need to use the -bundle_loader option to point out beam.smp
when building all drivers and NIF libraries.
https://bugs.erlang.org/browse/ERL-251
https://bugs.erlang.org/browse/ERL-439

macOS: Fix problems loading crypto

---

lib/kernel/src/erl_epmd.erl

This mirrors the behavior of inet:gethostbyname when no family or
timeout is supplied.

Fix erl_epmd:port_please when using IPv6

---

erts/emulator/beam/beam_debug.c
erts/emulator/beam/beam_emu.c
erts/emulator/beam/beam_load.c
erts/emulator/beam/ops.tab

Optimise construction of maps when all keys are literals but building a literal tuple in the loader. This benefits especially small maps since they basically consist of two tuples - one for the keys and one for the values.
This change should benefit especially Elixir, because of the record replacement - structs are always built with all literal keys. 
The change effectively means significantly reducing memory use (almost by a half) of programs using maps to replace records.

Introduce new_map_lit operation in the loader

---

bootstrap/lib/compiler/ebin/compiler.app
lib/compiler/src/Makefile
lib/compiler/src/compile.erl
lib/compiler/src/compiler.app.src
lib/compiler/src/sys_core_alias.erl
lib/compiler/test/Makefile
lib/compiler/test/core_alias_SUITE.erl
lib/compiler/test/misc_SUITE.erl

Introduce a new core pass called sys_core_alias
The goal of this pass is to find values that are built from patterns and generate aliases for those values to remove pressure from the GC. For example, this code:
``` erlang
example({ok, Val}) ->
{ok, Val}.
```
shall become:
``` erlang
example({ok, Val} = Tuple) ->
Tuple.
```
Currently this pass aliases tuple and cons nodes made of literals, variables and other cons. The tuple/cons may appear anywhere in the pattern and it will be aliased if used later on.
Notice a tuple/cons made only of literals is not aliased as it may be part of the literal pool.
This is a WIP and tests are still pending.

Introduce a new core pass called sys_core_alias

---

lib/ssh/src/ssh_io.erl

Enables the `ssh_io` module to also accept binary values when reading `standard_io` instead of getting stuck in the receive clause.

Add support for binary input in ssh_io

---

erts/emulator/beam/beam_emu.c
erts/emulator/test/exception_SUITE.erl
lib/compiler/test/trycatch_SUITE.erl

The goal of this change is to improve debugging of emulator calls. For example, the following code
rem(1, y)
will error with atom `badarith` when y is 0 and the stacktrace has no entry for `erlang:rem/2`, making such cases very hard to debug. This patch makes it so the stacktrace includes `erlang:rem(1, 0)`.
The following emulator BIFs have been changed so far:
* band/2
* bor/2
* bsl/2
* bsr/2
* bxor/2
* div/2
* int_div/2
* rem/2
* sminus/2
* splus/2
* stimes/2
I would like to do this change to other emulator operations, such as tuple operations and system limit errors that happen in the functions above, but before I would like to verify that this patch is sound.
I would also appreciate some feedback on the code. Currently I had to sprinkle `if (Arg(0) != 0) goto jump_f;` because we can …

Add stacktrace entries to BIF calls from emulator

---

erts/emulator/beam/sys.h

The VM uses pointers with type tags in their lowest few bits, expecting core types such as Eterm and Uint to be sufficiently aligned by default.  This works on most platforms, except on those where the alignment of word-sized integers and pointers is less than their size.  Linux on the M68K is a prime example: it's a 32-bit platform that only aligns to 16-bit boundaries by default.
Fixed by adjusting the declarations of the VM's core types to explicitly enforce the minimal alignment the VM expects of these types.  This has no effect on platforms that use stricter alignment than that.

erts: ensure alignment of VM core types

---

lib/inets/src/http_server/mod_log.erl

The status code provided by other modules was being
ignored and 200 (OK) was logged for all responses.
Issue ERL-443.

Log actual http status code of response.

---

lib/os_mon/src/disksup.erl
lib/os_mon/test/disksup_SUITE.erl

`os_mon:disksup` parser for df output is rewritten to take remaining data after last column as the mount path.
POSIX fix includes solaris, linux, dragonfly, freebsd, openbsd, netbsd, sunos and SUSv3 fix covers OSX (Darwin).
Missing sample outputs for other systems like: irix and win32, possibly problem does not exist on Win32

Fixes ERL-343 parsing 'df' output by os_mon:disksup on POSIX and SUSv3 systems

---

lib/ssl/src/dtls_udp_listener.erl
lib/ssl/src/ssl_connection.erl

While trying out #1518 I found a typo which proliferated through some of the `ssl` library modules. At this point it probably doesn't do any harm, but making it consistent with the module name (`dtls_udp_listener`) and the spellchecker can't do either.

Fix a proliferated typo in ssl

---

lib/ssl/src/ssl.erl
lib/ssl/src/ssl_connection.erl

Current implementation expects Seed to be a list.
Correct type specification to match.
Issue ERL-442.

Correct type specification in ssl:prf/5

---

lib/compiler/src/sys_core_fold.erl
lib/compiler/test/core_SUITE.erl
lib/compiler/test/core_SUITE_data/non_variable_apply.core

The sys_core_fold pass would do an unsafe "optimization" when an
apply operation did not have a variable in the function position
as in the following example:
```
> cat test1.core
module 'test1' ['test1'/2]
attributes []
'i'/1 =
fun (_f) -> _f
'test1'/2 =
fun (_f, _x) ->
apply apply 'i'/1 (_f) (_x)
end
> erlc test1.core
no_file: Warning: invalid function call
```
Reported-by: Mikael Pettersson

sys_core_fold: Fix unsafe optimization of non-variable apply

---

lib/stdlib/src/otp_internal.erl

When compiling a gen_fsm written before gen_statem was introduced, the deprecation warnings do not seem on point:
* it is suggested to replace calls to `gen_fsm:start_link/3` with `gen_statem:start/3` even though gen_fsm.xml suggests `start_link`
* `gen_fsm:send_event/2` with `gen_statem:cast/1` instead of `/2` (`/1` does not even exist)

gen_fsm-depre-20: fix gen_fsm deprecation recommendations after 20.0

---

lib/observer/src/observer_lib.erl
lib/observer/src/observer_sys_wx.erl
lib/runtime_tools/src/observer_backend.erl

Add other two panels: first one: 'System limits' and second one 'Limit Statistics'
Show infomations as atom_limit,process_limit,port_limit and counts.
The result is:

Add more information to the Observer

---

lib/compiler/src/beam_clean.erl
lib/compiler/src/beam_jump.erl
lib/compiler/src/beam_utils.erl

This is especially useful after inlining a function with a case.
Today the compiler would most probably be able to unify all the leafs of the
case during the sharing optimisation, but it would fail to unify the pattern
matching itself.
Naively running the optimisation multiple times wouldn't be able to find the
common code either, because it would differ in jump/fail targets of various
instructions.
To remedy this, after doing each sharing pass we traverse the code backwards
when reversing and update all the jump targets with the new targets that were
discovered during the unification pass. This allows running the optimisation
until fixpoint and makes sure all sharing opportunities will be discovered.
This optimisation also helps with the Elixir's `with/else` construct.
Introduce …

Run the sharing optimisation in beam_jump until fixpoint

---

lib/compiler/src/sys_core_fold.erl
lib/compiler/test/core_fold_SUITE.erl

In general, a 'case' expression will force a stack frame.
However, for an one-armed 'case':
```
case Expr of
Pat1 ->
DoSomething;
Pat2 ->
erlang:error(bad)
end.
```
at the end of a function there is no need to allocate a
stack frame
In sys_core_fold there is an optimization that takes advantage
of this by rewriting code such as:
```
case Expr of
Pat1 ->
DoSomething;
Pat2 ->
erlang:error(bad)
end,
MoreCode.
```
to:
```
case Expr of
Pat1 ->
DoSomething,
MoreCode;
Pat2 ->
erlang:error(bad)
end.
```
However, that optimization would not be applied if there
were more than one failing clause such as in this code:
```
case Expr of
Pat1 ->
DoSomething,
MoreCode;
Pat2 ->
erlang:error(bad);
_ ->
erlang:error(case_clause)
end.
```
Generalize the optimization to handle any number of failing
clauses at …

Generalize optimization of "one-armed" cases

---

system/doc/design_principles/des_princ.xml
system/doc/design_principles/statem.xml

Fixed some broken doc links.
Question: Do we want to put some other text in the introduction to the example?

Fix broken doc links to gen_fsm design princ

---

erts/emulator/drivers/unix/ttsl_drv.c

The ANSI support doesn't work properly with edlin, the issue can be noticed when you try to use the history of the shell and the prompt prefix has ANSI (https://github.com/elixir-lang/elixir/issues/6448). The problem is that when a `\e` character appears, it handles it like a new line, dropping the buffer before it.
The solution is to always add the `\e` to the buffer like a regular character and handle it when writing the buffer instead.

Fix ANSI support in the console

---

lib/ssh/src/ssh_sftp.erl
lib/ssh/test/ssh_sftp_SUITE.erl

Previously, a hard-coded atom (read_write) has been used as file owner access permission
in response to ssh_sftp:read_file_info/2 function. With this fix, the actual value of
file owner access permission is added to the returning record. That value is calculated
from file mode value.

Fix file owner access permission in ssh_sftp module

---

lib/tools/emacs/erlang.el

The default target is changed to be just the name at point when
xref-find-references is invoked.  Previously the default was the same
as for xref-find-definitions.  This included arity and other things
that do not make sense for xref-find-references.

Emacs: Fix default target for xref-find-references

---

lib/os_mon/src/disksup.erl

On macOS 10.13 (High Sierra), disksup cannot grab information
for any disks that use the new APFS file system. The reason
is that the invocation of /bin/df explicitly limits the
type of file systems to show:
/bin/df -i -k -t ufs,hfs
Add 'apfs' to also look at disks with APFS:
/bin/df -i -k -t ufs,hfs,apfs
That also works on older versions of macOS.
An alternative solution would be to use the -l flag to only
show local file systems. However, that would mean that USB
memory sticks would also show up, and it might not be desirable
to monitor them.
https://bugs.erlang.org/browse/ERL-461

Fix disksup:get_disksup_data() for High Sierra

---

erts/test/system_smoke.spec

The ethread_SUITE is unlikely to ever find a real bug
introduced in a pull request, but it frequently times
out when run by Travis CI.

Remove time-consuming ethread_SUITE from smoke tests

---

lib/compiler/test/compilation_SUITE_data/opt_crash.erl
lib/kernel/doc/src/inet_res.xml
lib/observer/src/observer_traceoptions_wx.erl
lib/reltool/src/reltool_mod_win.erl
lib/stdlib/src/erl_pp.erl
lib/wx/examples/demo/demo.erl

There are still some query residues used as a keyword. Remove them.
query was no longer a keyword since the commit 0dc3a29744bed0b7f483ad72e19773dc0982ea50 2012-11-19.

Remove query keyword residues

---

lib/compiler/src/beam_peep.erl
lib/compiler/test/match_SUITE.erl

When cleaning selects, it might happen we're left with only one pair. In such
case convert to a regular test + jump.
---
I run the stdlib, compiler & emulator suites without failures.

Enhance optimisations in beam_peep

---

erts/emulator/test/port_SUITE.erl

This test case was introduced in 5a42fa760c, but was never added to the list of test cases to execute.
Also, the commit fixes cleaning up the modified OS environment setting to prevent problems with later test cases using the `echo_drv` too.

Execute the dropped_commands test case in port_SUITE

---

lib/compiler/src/beam_validator.erl

beam_validator could fail issue a diagnostic when a register
that was supposed to be a match context was not guaranteed to
be a match context.
The bug was in merging of types. Merging of a match context with
another term would result in a match context. That is wrong. Merging
should produce a more general type, not a narrower type. Also, the
valid slots in two match contexts should be combined with 'band', not
'bor'.

Make handling of match contexts stricter

---

lib/stdlib/doc/src/ets.xml

I was staring at the examples on the website and trying to figure out why both commands are the same but the output is different. 
```erlang
4> ets:fun2ms(fun({M,N}) when N > X, is_atomm(M) -> M end).
Error: fun containing local Erlang function calls
('is_atomm' called in guard) cannot be translated into match_spec
{error,transform_error}
5> ets:fun2ms(fun({M,N}) when N > X, is_atom(M) -> M end).
[{{'$1','$2'},[{'>','$2',{const,3}},{is_atom,'$1'}],['$1']}]
```
The extra `m` was not obvious at all, maybe this will make it easier to understand the example.

Changes confusing example of a bad guard in ets:fun2ms

---

lib/compiler/src/v3_codegen.erl
lib/compiler/test/bs_match_SUITE.erl

The compiler could sometimes emit unnecessary 'move'
instructions in the code for binary matching, for
example for this function:
```
escape(<<Byte, Rest/bits>>, Pos) when Byte >= 127 ->
escape(Rest, Pos + 1);
escape(<<Byte, Rest/bits>>, Pos) ->
escape(Rest, Pos + Byte);
escape(<<_Rest/bits>>, Pos) ->
Pos.
```
The generated code would look like this:
```
{function, escape, 2, 2}.
{label,1}.
{line,[{location,"t.erl",17}]}.
{func_info,{atom,t},{atom,escape},2}.
{label,2}.
{test,bs_start_match2,{f,1},2,[{x,0},0],{x,0}}.
{test,bs_get_integer2,
{f,4},
2,
[{x,0},
{integer,8},
1,
{field_flags,[{anno,[17,{file,"t.erl"}]},unsigned,big]}],
{x,2}}.
{'%',{bin_opt,[17,{file,"t.erl"}]}}.
{move,{x,0},{x,3}}.                              %% UNECESSARY!
{test,is_ge,{f,3},[{x,2},{integer,127}]}. …
```

Eliminate unnecessary 'move' instructions

---

erts/emulator/beam/beam_load.c

Duplicate literals in the literal pool is a waste of memory.
Also, having unique literals can simplify some loader optimizations,
because we can known that if two literal indices are distinct, the
values must be distcint too.

De-duplicate bignums in the literal pool

---

lib/dialyzer/test/behaviour_SUITE_data/results/gen_server_incorrect_args
lib/stdlib/doc/src/gen_server.xml
lib/stdlib/src/gen_server.erl
lib/stdlib/test/erl_internal_SUITE.erl
lib/stdlib/test/gen_server_SUITE.erl
lib/stdlib/test/gen_server_SUITE_data/oc_server.erl

If the gen_server process needs to perform an action immediately
after initialization or to break the execution of a callback into
multiple steps, it can return {continue, term()} in place of the
time-out or hibernation value, which will immediately invoke the
handle_continue/2 callback with the given term.
This provides a more accessible approach to after initialization
compared to proc_lib+enter_loop that is also guaranteed to be
safe.
It also allows callbacks that need to do lengthy or stateful work
to checkpoint the state throughout multiple iterations. This can
be useful, for example, when implementing behaviours on top of
gen_server.
This is continuation of PR #1429.

Add {continue, Term} and handle_continue/2 to gen_server

---

lib/stdlib/src/erl_lint.erl
lib/stdlib/test/erl_lint_SUITE.erl

There could be a false warning for `erlang:get_stacktrace/0`
being outside a try block when it was actually inside a try
block.
https://bugs.erlang.org/browse/ERL-478

Eliminate incorrect get_stacktrace/0 warning

---

Makefile.in
erts/Makefile
erts/aclocal.m4
erts/configure.in
erts/emulator/Makefile.in
erts/emulator/test/estone_SUITE.erl
make/otp.mk.in
make/output.mk.in

Using PGO to guide gcc/clang to make "better" decisions about how to compile the main emulator loop and (for now) erl_process.c.
It is not possible to use PGO in a cross-compilation environment.
This change makes the estone benchmark rise by a about 3%, which is not all that much. However, individual benchmarks in estone and others have seen up to a 50% increase in performance due to this change.
Together with the other changes we are doing to the main emulator loop this brings the total estone performance gain to 10% compared to what is currently in main. While this in no way translates to 10% better performance in applications, it is a nice step in the right direction. This is just one of many other improvements we have planned.

Add support for building a pgo beam_emu

---

erts/emulator/beam/erl_alloc.types
erts/emulator/beam/erl_bif_binary.c

Affects `binary:matches/2`, `binary:matches/3`, and `binary:split/3` when global flag enabled. Binary find state is kept in memory between traps instead of serializing and restoring inefficiently.
A performance issue was first reported at elixir-lang/elixir#6148 where @waj noticed that for the same large binary, a single global `binary:split/3` was considerably slower than multiple `binary:split/2` calls.  `binary:matches/2` and `binary:matches/3` are also affected.
Using tail recursion with multiple calls to `binary:split/2` is much more performant.  For example, in [this benchmark](https://gist.github.com/potatosalad/4b7117679c048bfda23b4e2b8382e448), a ~128MB binary with 1KB "parts" separated by 1 byte when using `binary:split/3` with global flag enabled is ~80x slower than tail …

stdlib: Improved BIF for binary matches and split.

---

erts/emulator/beam/ops.tab
lib/compiler/src/beam_utils.erl
lib/compiler/test/guard_SUITE.erl

* In both loader and compiler, make sure constants are always the second
operand - many passes of the compiler assume that's always the case.
* In loader rewrite is_eq_exact with different arguments to unconditional jump,
with same arguments skip the instruction.
* In loader rewrite is_ne_exact with same arguments to unconditional jump,
with different arguments skip the instruction.
* All of the above allow to replace is_eq_exact_fss with is_eq_exact_fyy and
is_ne_exact_fss with is_ne_exact_fSS as those are the only possibilities left.

Optimise equality comparisons

---

erts/emulator/drivers/unix/ttsl_drv.c
lib/stdlib/src/edlin.erl

This fixes the issue with the function `move_cursor` described in #1536 and that causes the bug described in elixir-lang/elixir#6504, and also fixes wide chars handling.
The function `cp_pos_to_col` maps the current position in the buffer to the correct column on the screen, but it didn't handle ANSI escape codes. Since the ANSI escape codes aren't visible, the `cp_pos_to_col` now skips them when executing the calculations using `ansi_escape_width`. This new function only considers color escape codes, but also handles invalid codes.
The function `del_chars` used to first delete the buffer and than write down the new buffer cleaning the line and moving the cursor back, the problem in that is that when you clean the buffer you lose the size of the old characters and, if you have wide chars, …

Consider ANSI escape codes on cp_pos_to_col

---

erts/doc/src/erlang.xml

The following code could fail in the call to list_existing_atom/1:
```
String = atom_to_list(some_atom),
Atom = list_to_existing_atom(String)
```
because the compiler will rewrite the code to:
```
String = "some_atom",
Atom = list_to_existing_atom(String)
```
If some_atom is not used in another place, it will not exist.
The compiler could be updated to preserve the atom in this simple case,
but it would be hard to make sure that the compiler never loses atoms
that exist in the source text. It also difficult to imagine a
real world use case where this would be a problem. If an atom is
mentioned only in a way that the compiler can optimize away, is there
really any need to create the atom at all in list_to_existing_atom/1?
Therefore, it is better to place the responsibility that the atom …

Document that the compiler may optimize away atoms

---

lib/compiler/doc/src/compile.xml
lib/compiler/src/beam_asm.erl
lib/compiler/src/compile.erl
lib/compiler/test/compile_SUITE.erl

This allows compilers built on top of the compile module
to attach external compilation metadata to the compile_info
chunk.
For example, Erlang uses this chunk to store the compiler
version. Elixir and LFE may augment this by also adding
their own compiler versions, which can be useful when
debugging.
The deterministic option does not affect the user supplied
compile_info. It is therefore the responsibility of external
compilers to guarantee any added information does not violate
the determinsitic option, if such option is supported.
Finally, this code moves the building of the compile_info
options to the compile module instead of beam_asm, moving
all of the option mangling code to a single place.

Add compile_info option to compile

---

lib/mnesia/doc/src/Mnesia_chap5.xmlsrc

In the Table Fragmentation documentation section, note that the
functions first/1, next/2, prev/2 and last/1 return elements in an
undefined order for fragmented tables.
Also remove superfluous "the".

Mnesia: note first, next, prev and last vs fragmented tables

---

lib/stdlib/src/pool.erl

This PR corrects some typos in the pool module code doc.

Fix doc typos in pool module

---

lib/public_key/doc/src/public_key_records.xml
lib/public_key/src/public_key.erl
lib/public_key/test/public_key_SUITE.erl
lib/public_key/test/public_key_SUITE_data/ec_key2.pem

- type spec ecpk_parameters() added to represent DER-encodable ecpkParameters
- type spec ecpk_parameters_api() added to represent ecpkParameters provided by the user through public_key
API functions
- API is now more generous in its input, and more strict in its output.
- update to public key records documentation
- add tests, including tests against EC key with explicit curve parameters
- also fixes ERL-480
Note: ssl tests aren't working well on my system.  I get a number of failures on `maint` and on this branch.

fix ERL-481 ecpkParameters representation

---

lib/compiler/src/beam_validator.erl
lib/compiler/test/bs_match_SUITE.erl

4c31fd0b9665 made the merging of match contexts stricter;
in fact, a little bit too strict.
Two match contexts with different number of slots would
be downgraded to the 'term' type. The correct way is to
keep the match context but set the number of slots to the
lowest number of slots of the two match contexts.
https://bugs.erlang.org/browse/ERL-490

Fix incorrect internal consistency failure for binary matching code

---

erts/emulator/beam/macros.tab
erts/emulator/test/exception_SUITE.erl
erts/emulator/utils/beam_makeops

Sometimes the line number in a stack trace could be wrong,
for example for this code:
t() ->
Res = id(x), %<== Wrong line number.
Res + 1.
id(I) -> I.
The line number pointed out in the stack trace would be the
line before the line where the exception occurred.
The reason is the way the increment instruction instruction
is implemented:
OpCase(i_increment_rWtd):
{
increment_reg_val = r(0);
}
I -= 1;
goto increment__execute;
OpCase(i_increment_xWtd):
{
increment_reg_val = xb(I[1]);
}
goto increment__execute;
increment__execute:
/* Common code for increment */
.
.
.
(The implementation in OTP 20 is similar, but hand-coded directly
in beam_emu.c instead of generated.)
The instruction i_increment_rWtd decrements the instruction pointer (I)
before jumping to the common code. That means that I …

Point out the correct line number in stack traces

---

lib/stdlib/doc/src/filelib.xml
lib/stdlib/src/filelib.erl
lib/stdlib/test/filelib_SUITE.erl

Allow characters with special meaning to be escaped using
\ (which must be writen as \\\\ in a string). That allows
matching of filenames containing characters that are special
in wildcards.
This is an incompatible change, but note that the use of backslashes in wildcards would already work differently on Windows and Unix. Take for example this call:
filelib:wildcard("a\\b")
On Windows, filelib:wildcard/1 would look for a directory named "a", and a file or directory named "b" inside it.
On Unix, `filelib:wildcard/1` would look for a file named "a\\b".
With this commit applied, filelib:wildcard/1 will look for a file named "ab" on both Windows and Unix.
https://bugs.erlang.org/browse/ERL-451

Implement escaping of special characters in wildcards

---

lib/crypto/doc/src/crypto.xml
lib/crypto/doc/src/crypto_app.xml
lib/crypto/src/crypto.app.src
lib/crypto/src/crypto.erl
lib/stdlib/test/rand_SUITE.erl

This pull request adds functions `rand_seed_alg(Alg)` and `rand_seed_alg_s(Alg)` to the `crypto` module.
The new functions take an algorithm name where the name `crypto` names the previously existing algorithm implemented in `rand_seed()` and `rand_seed_s()`, and the new algorithm name `crypto_cache` implements an algorithm that fetches bytes from the same source as `strong_rand_bytes(N)` but caches them for speed and returns a random 56 bit (also for speed) word at the time.
This algorithm gives a decent speed for generating cryptographically secure random numbers.  The test case `rand_SUITE:measure/1` indicates (amortized) only about 60% to 100% slower than the default PRNG in the `rand` module, while the previous `crypto` algorithm (in `rand_seed()`) is about 4 to 15 _times_ slower …

Rand plugin for cached strong crypto bytes

---

lib/stdlib/doc/src/gen_statem.xml
lib/stdlib/src/gen_statem.erl

I would like community feedback on a changing a corner case for timeouts in `gen_statem:call(Server, Request, Timeout)` for OTP 21.0.
The `Timeout == {clean_timeout,infinity}` today means `{dirty_timeout,infinity}` i.e does not use a proxy process.  This was intended as an optimization.
But since in the event of network problems such as the connection going down and up the monitor set before sending `Request` may trigger causing the client call to fail, but the `Request` may actually have arrived at the server, which may reply so we get an unhandled late reply in the inbox.  Very rarely.
I think that giving the programmer the possibility to use a proxy process even for infinity timeout simplifies the semantics and may be found useful.
The behaviour for `Timeout == infinity` will still …

Change gen_statem:call(_, _, {clean_timeout,infinity}) to use proxy

---

lib/hipe/test/basic_SUITE_data/basic_exceptions.erl

that checks the construction of exception information.  The test is
taken from the compiler SUITE but part of it (the one that constructs
exceptions which differ between BEAM and HiPE) is commented out.
Related to the discussion of #1596.

hipe: Extend the basic_SUITE with one more test

---

erts/emulator/test/exception_SUITE.erl

when/if compiling this file to native code to check its exception
behaviour.  Related to the discussion in #1596.

Explicitly disable HiPE's range analysis

---

erts/emulator/beam/instrs.tab
erts/emulator/beam/ops.tab
lib/compiler/src/beam_receive.erl
lib/compiler/src/beam_utils.erl
lib/compiler/src/sys_core_fold.erl
lib/hipe/icode/hipe_beam_to_icode.erl

This PR contains several improvements to catch and try/catch. The commit message for each commit gives more details. Here are the highlights:
* A catch that ignores its return value such as this code:
```
catch side_effect(),
...
```
will no longer build a stack trace.
* There are several minor optimizations, both in the compiler and run-time system, for try/catch.
* The optimization of receive that can avoid rescanning the entire message queue will now work for this code:
Ref = make_ref(),
try
side_effect()
catch _:_ ->
ok
end,
receive
%% Clauses that all match Ref.
.
.
.
end
(try/catch used to prevent the optimization.)

(Slightly) optimize catch and try/catch

---

lib/stdlib/doc/src/rand.xml
lib/stdlib/src/rand.erl
lib/stdlib/test/rand_SUITE.erl

This pull request implements `rand:uniform_nz/0` and `rand:uniform_nz_s/1`.
These new functions return an uniformly distributed random float in the range ]0.0;1.0] that is the half open unity interval not including zero but including one.  The interesting property of this implementation is that for all generated floats all bits are random regardless of the exponent of the float, and they are still uniformly distributed.
The existing function `rand:uniform/0` generates values on the form N * 2^-53 so they all have the same distance to the closest possible value.  But with this function that distance decreases towards 0.0 as does the probability for a specific value, hence uniformity is preserved.
This is done by iteratively generating more bits until there are 53 random bits counting from …

Implement uniform floats with decreasing distance towards 0.0

---

lib/stdlib/src/filename.erl
lib/stdlib/test/filename_SUITE.erl

Previously : https://github.com/erlang/otp/pull/1591
``` erlang
> filename:join("\\\\", "foo").
"/foo"
> filename:split("\\\\foo").
["/","foo"]
```
``` erlang
> filename:join("\\\\", "foo").
"//test"
> filename:split("\\\\foo").
["//","test"]
```
As per instructions https://github.com/erlang/otp/pull/1591#issuecomment-336933567
A clean PR with single commit

fix win32 share filename join/split

---

lib/stdlib/src/base64.erl

Reimplement base64:decode/1, for the List input case, to be 2x to 3x faster (3x for longer inputs).
The speedup comes from:
1. Avoiding extra scan of the input by merging the pre-processing step (whitespace removal) into the conversion loop.
2. Accumulating the output into a binary in the right order.
3. Appending a number of octets at a time rather than 6 bits at a time as decode(Binary) does.
4. Using bit-syntax to append a sequence of bit-fields (making up a number of octets) rather than manually combining them and calculating the octet values.
This reimplementation also checks the tail of the input more carefully, similar to the decode(Binary) code.
Similar improvements could be implemented in the other variants, but this case is the one that hurt us the most.
Implemented by Mikael …

base64:decode(List) optimized reimplementation

---

erts/emulator/drivers/common/inet_drv.c

gen_sctp:connect_init/4 could return error even though the OS had
initiated the connection. 
I.e. connect returned "in progress".
Then an error could come from packet_inet_output() which is checking the socket
and return error if peer_sock returned any error.
The misleading here is that from erlang you don't think the connect is still ongoing.
And you will receive a sctp_assoc_change message later on.
What problem did the code in packet_inet_output solve? What am I breaking when not calling it?
Remove the code in packet_inet_output?
Does it make sense to have INET_STATE_CONNECTING, INET_STATE_CONNECTED on a 1<->M SCTP socket?

SCTP connect could return error even if the connect is ongoing 

---

erts/emulator/hipe/hipe_amd64_bifs.m4
erts/emulator/hipe/hipe_bif0.tab
erts/emulator/hipe/hipe_bif_list.m4
erts/emulator/hipe/hipe_native_bif.c
erts/emulator/hipe/hipe_native_bif.h
erts/emulator/hipe/hipe_primops.h
lib/hipe/main/hipe.app.src
lib/hipe/rtl/hipe_rtl_binary_construct.erl

This is a x86_64-only fix for hipe compiled code running binary constructions like
`<<X/utf32>>`
The **problem** is the generated code calls bif/primop `hipe_bs_validate_unicode` before it writes to the binary. But `hipe_bs_validate_unicode` may trigger GC in which case the binary data is written to the old deallocated heap and the constructed binary on the new heap will contain random bytes.
My **solution** is to introduce a new bif wrapper `nogc_bif_interface_1` for `hipe_bs_validate_unicode` that never triggers GC. So far I've only done it for x86_64.
To write test code that reliably **reproduces** the scenario where `hipe_bs_validate_unicode` will trigger GC is not trivial. Instead I did a commit where `hipe_bs_validate_unicode` always trigger GC. Remove the top revert-commit, …

Fix hipe bug in binary <<X/utf32>> construction

---

erts/emulator/hipe/hipe_debug.c

When the code switches from printf() to erts_printf() the output
becomes garbled.  Fixed by fflush()ing stdout first.
Fixed formatting of the "H E A P" banner for 64-bit systems.

fix output formatting in hipe_bifs:show_heap/1

---

lib/compiler/internal_doc/cerl-notes.md
lib/compiler/src/cerl_clauses.erl

I recently tried to add some additional optimizations for
matching of maps, but found out that the inliner will need
some updates to be able to handle those optimizations.
Add `lib/compiler/internal_doc/cerl-notes.md` to document what
I've learned.

Add some internal documentation about cerl_clauses

---

lib/hipe/doc/src/hipe_app.xml

Two new sections in HiPE application docs about known limitations.
I thought there also were some semantic differences regarding `andalso` and `orelse`, but I could not provoke any.
@kostis @mikpe @margnus1

Document HiPE limitations

---

lib/compiler/src/beam_asm.erl
lib/compiler/test/compile_SUITE.erl
lib/compiler/test/compile_SUITE_data/deterministic_module.erl

The compiler option 'deterministic' was only recognized when given
as an option to the compiler, not when it was specified in a
`-compile()` attribute in the source file.
https://bugs.erlang.org/browse/ERL-498

Recognize 'deterministic' when given in a -compile() attribute

---

erts/emulator/beam/beam_emu.c
erts/emulator/beam/beam_load.c
erts/emulator/beam/macros.tab
erts/emulator/beam/map_instrs.tab
erts/emulator/beam/ops.tab
erts/emulator/internal_doc/beam_makeops.md
erts/emulator/utils/beam_makeops

This PR adds internal documentation for the `beam_makeops` script, which is used when building the Erlang compiler and Erlang runtime system. I try to explain all about generic and specific instructions, transformation rules, and the new macro-based system for implementing BEAM instructions.
There are also a few commits with minor clean ups of issues found while writing the document.

Add internal documentation for the beam_makeops script

---

lib/mnesia/src/mnesia.erl

A very minor typing fix. `mnesia:transform_table` is, per the docs, able to take `ignore` as a value for the `Fun` parameter. Currently using this feature causes a dialyzer warning. This change resolves that.

Add ignore option to transform_table fun

---

erts/emulator/beam/erl_term.h
erts/emulator/hipe/hipe_bif_list.m4
erts/emulator/hipe/hipe_mkliterals.c
erts/emulator/hipe/hipe_native_bif.c
erts/emulator/hipe/hipe_native_bif.h
lib/hipe/icode/hipe_beam_to_icode.erl
lib/hipe/icode/hipe_icode.erl
lib/hipe/icode/hipe_icode.hrl
lib/hipe/icode/hipe_icode_liveness.erl
lib/hipe/icode/hipe_icode_pp.erl
lib/hipe/main/hipe.app.src
lib/hipe/main/hipe.erl
lib/hipe/main/hipe_main.erl
lib/hipe/rtl/Makefile
lib/hipe/rtl/hipe_rtl.erl
lib/hipe/rtl/hipe_rtl_binary_construct.erl
lib/hipe/rtl/hipe_rtl_binary_match.erl
lib/hipe/rtl/hipe_rtl_cleanup_const.erl
lib/hipe/rtl/hipe_rtl_lcm.erl
lib/hipe/rtl/hipe_rtl_varmap.erl
lib/hipe/rtl/hipe_rtl_verify_gcsafe.erl
lib/hipe/rtl/hipe_tagscheme.erl
lib/hipe/ssa/hipe_ssa.inc
lib/hipe/test/hipe_testsuite_driver.erl

This PR adds support for tagged literals to HiPE. Tagged literals is one of the mechanisms the Erlang VM can use to identify what data is literal, and what is dynamically allocated. Adding this support will allow HiPE to be used on platforms where this mechanism is used.
I expect the performace to be worse when using literal tagging as the generated code is uglier. The bad code does however give the optimisers some room to stretch their legs, for once. As a result of this, two previously unknown bugs in the Lazy Code Motion optimiser were exposed and fixed.
To be able to reliably reproduce these bugs (as they rely on the garbage collector to hit at the wrong time) the test for these bugs is in the form of a validation pass that is run on the intermediary code as part of the HiPE test …

HiPE: Support for literal tag, tests and bugfixes

---

erts/doc/src/erlang.xml
erts/emulator/beam/external.c
erts/emulator/test/binary_SUITE.erl
erts/preloaded/src/erlang.erl
lib/kernel/test/erl_distribution_wb_SUITE.erl

Make `binary_to_term(Bin, [used])` return `{Term, Used}`
where `Used` is the number of bytes actually consumed from `Bin`.
Needed to maintain existing tests in lib/kernel/test/erl_distribution_wb_SUITE.erl,
but seems like a generally useful feature to either assert correct length of the binary or to access additional trailing information.

Add 'used' option for binary_to_term/2

---

lib/sasl/test/release_handler_SUITE.erl
lib/stdlib/src/supervisor.erl
lib/stdlib/test/supervisor_1.erl
lib/stdlib/test/supervisor_SUITE.erl
lib/stdlib/test/supervisor_deadlock.erl

This is based on [PR-1467](https://github.com/erlang/otp/pull/1467), but re-implemented upon a refactored version of `supervisor`. The refactoring is included in this PR.
For the time being, I have chosen not to remove the child ID from the child record (as suggested in the original PR), since that would only save one word per child and the current solutions gives a bit cleaner code.

Refactor supervisor, and store children in a map instead of a list

---

erts/emulator/beam/beam_emu.c
erts/emulator/beam/erl_message.h
erts/emulator/beam/msg_instrs.tab
erts/emulator/beam/ops.tab
erts/emulator/test/receive_SUITE.erl

The receive optimization that avoids scanning the entire message
queue could be unsafe when an exception was caught in the middle
of a recursive call to a function that does a receive.
Magnus Lång described the problem like this:
"If a recv_mark is executed, but the corresponding recv_set is bypassed
because of an exception, the receive queue marker remains. If a
function using this optimisation calls itself between recv_mark and
recv_set, and the inner function is abnormally exited between its
recv_mark and recv_set, but the exception is caught without unwinding
the outer call, the outer call will use the mark left by the inner
call and risk a deadlock."
There does not seem to be any way to fix this problem in the compiler,
except by disabling the optimization if there is any function …

Fix broken receive mark after an exception

---

lib/stdlib/doc/src/uri_string.xml
lib/stdlib/src/uri_string.erl
lib/stdlib/test/uri_string_SUITE.erl

This pull request is a continuation of #1551 with new functions for handling form-urlencoded query strings based on the [HTML5](https://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm) specification:
- `compose_query/1`
```erlang
1> uri_string:compose_query([{"foo bar","1"},{"city","örebro"}]).
"foo+bar=1&city=%C3%B6rebro"
2> uri_string:compose_query([{<<"foo bar">>,<<"1">>},
2> {<<"city">>,<<"örebro"/utf8>>}]).
<<"foo+bar=1&city=%C3%B6rebro">>
```
- `compose_query/2`
```erlang
1> uri_string:compose_query([{"foo bar","1"},{"city","örebro"}],
1> [{encoding, latin1}]).
"foo+bar=1&city=%F6rebro"
2> uri_string:compose_query([{<<"foo bar">>,<<"1">>},
2> {<<"city">>,<<"東京"/utf8>>}], [{encoding, latin1}]).
<<"foo+bar=1&city=%26%2326481%3B%26%2320140%3B">>
``` …

Extend uri_string module (compose_query and dissect_query)

---

erts/emulator/beam/beam_load.c
erts/emulator/beam/erl_gc.c
erts/emulator/test/code_SUITE.erl

When compiling Erlang source code, the literal area for the
module can only contain data types that have a literal
syntax.
However, it is possible to sneak in other data types
(such as references) in the literal pool by compiling from
abstract or assembly code. Those "fake literals" would work
fine, but would crash the runtime system when the module containing
the literals was purged.
Although fake literals are not officially supported, the
runtime should not crash when attempting to use them.
Therefore, fix the garbage collection of literals and releasing
of literal areas.
https://bugs.erlang.org/browse/ERL-508

Fix purging of modules with "fake literals"

---

lib/stdlib/doc/src/ets.xml

Just something I noticed when reading the docs, not really that big a deal.

Minor grammar tweak in ETS documentation

---

erts/emulator/beam/atom.h
erts/emulator/beam/index.c

When setting maximum atom table size using `+t` option, there will be a integer overflow for a large size.
```
$ erl +t2147482625
ll_alloc: Cannot allocate 18446744073692774400 bytes of memory (of type "atom_tab").
```
The overflow is caused by the arithmetic operations on `int` type in the following line in [index.c](https://github.com/erlang/otp/blob/OTP-20.1.5/erts/emulator/beam/index.c#L61)
Uint base_size = ((limit+INDEX_PAGE_SIZE-1)/INDEX_PAGE_SIZE)*sizeof(IndexSlot*);
We can use above example `2147482625` to illustrate how the overflow occurs.
```
expression                      decimal value   binary value (32 bits)              note
INDEX_PAGE_SIZE                 1024            0b00000000000000000000010000000000  defined in index.h
limit                           2147482625 …
```

Fix integer overflow when set a large maximum value for atom table

---

lib/mnesia/src/mnesia.erl

The create_option() type in mnesia lacks the ```user_properties``` field
which is used by mnesia in various places.
How to reproduce the issue:
The following minimal project where ```{user_properties, []}``` is included in ```mnesia:create_table/2``` options demonstrates the Dialyzer warning in OTP-20:
https://github.com/aboroska/dialyzer-mnesia-test2
Run ```rebar3 dialyzer``` and under OTP-20 Dialyzers warns:
src/t2.erl
13: Function test/0 has no local return
This fix eliminates the warning.
The type ```proplists:proplist()``` seems appropriate. See for example the following line where it is accessed:
https://github.com/erlang/otp/blob/master/lib/mnesia/src/mnesia_bup.erl#L106

Fix type create_option() in mnesia

---

erts/emulator/hipe/hipe_debug.c
erts/emulator/hipe/hipe_risc_stack.c
erts/emulator/hipe/hipe_x86_stack.c

Fix formatting in hipe_bifs:show_pcb/1, hipe_bifs:show_estack/1,
and hipe_bifs:show_nstack/1.
fflush(stdout) before switching from printf() to erts_printf() to
avoid garbled output.
Adjust field lengths to work on both 64- and 32-bit systems.
Tested on Linux/x86_64 (64-bit) and Linux/ARMv7 (32-bit).

fix output formatting in several HiPE debug BIFs

---

lib/stdlib/src/gen.erl

`hibernate_after` is a supported option and included in the documentation but wasn't added to the type spec.

add hibernate_after to the gen options type spec

---

lib/compiler/src/beam_dead.erl
lib/compiler/src/core_lint.erl
lib/compiler/src/sys_core_fold.erl
lib/compiler/src/v3_codegen.erl
lib/compiler/src/v3_core.erl
lib/compiler/src/v3_kernel.erl
lib/compiler/test/match_SUITE.erl
lib/compiler/test/receive_SUITE.erl

A `case` or `if` that does not occur last in a function always forces a stack frame function for the function.
This PR suppresses the allocation of stack frames when they are not strictly needed. That will eliminate shuffling of registers to and from the stack, and may give later passes more opportunities for optimization.
https://bugs.erlang.org/browse/ERL-514

Avoid excessive stack frame allocation

---

erts/doc/src/erlc.xml
erts/test/erlc_SUITE.erl
lib/compiler/doc/src/compile.xml
lib/compiler/src/compile.erl
lib/stdlib/src/erl_compile.erl

The compile option makedep_side_effect, erlc -MMD, instructs
the compiler to emit dependencies and continue to compile
as normal.

Add -MMD option to erlc

---

lib/compiler/src/beam_block.erl
lib/compiler/src/beam_record.erl
lib/compiler/src/beam_utils.erl
lib/compiler/src/v3_codegen.erl
lib/compiler/test/beam_utils_SUITE.erl

`v3_codegen` currently wraps a stack frame around each clause in a function (unless the clause is simple without any `case` or other complex constructions).
f({a,X}) ->
A = abs(X),
case A of
0 ->
{result,"0"};
_ ->
{result,integer_to_list(A)}
end;
f(_) ->
error.
The first clause needs a stack frame because there is a function call to `integer_to_list/1` not in the tail position. `v3_codegen` currently wraps the entire first clause in stack frame.
We can delay the creation of the stack frame, and create a stack frame in each arm of the `case` (if needed):
f({a,X}) ->
A = abs(X),
case A of
0 ->
%% Don't create a stack frame here.
{result,"0"};
_ ->
%% Create a stack frame here.
{result,integer_to_list(A)}
end;
f(_) ->
error.
There are pros and cons of this approach. …

Delay creation of stack frames

---

lib/jinterface/java_src/pom.xml.src

The Java 9 module system requires a module name to be defined. If none is provided, a default one is used derived from the JAR name, but that one is not very unique and can create problems. The recommended module name is the longest common package name for the source code included.
The only change made is to JAR metadata, so it would be safe to merge in the maint branch too, if deemed necessary.

jinterface: add package name for Java 9

---

README.md

The README.md file contains a currently-broken link to the wiki, and the instruction I _could_ find on the wiki only point to CONTRIBUTING.md, so that seems like the right place to point here. Should this be merged on a `maint` branch or on a master branch?

Fix link to the contribution guide in README.md

---

erts/emulator/hipe/hipe_bif_list.m4
erts/emulator/hipe/hipe_mkliterals.c
erts/emulator/hipe/hipe_native_bif.c
erts/emulator/hipe/hipe_native_bif.h
lib/hipe/main/hipe.app.src
lib/hipe/rtl/hipe_rtl_binary_construct.erl

According to discussion in https://github.com/erlang/otp/pull/1642
I also added a PRIMOP_ABI_VSN version number as a way to detect incompatible changes like this in load time.
@margnus1

Fix GC bug for HiPE primop bs_put_utf8

---

lib/compiler/src/beam_utils.erl

Handle a few more instructions in `beam_utils`. That will allow
`beam_reorder` to reorder more instructions, delaying more `get_tuple_element`
instructions and reducing register shuffling in receive clauses.

Reduce register shuffling in receive clauses

---

lib/compiler/src/beam_type.erl
lib/compiler/test/beam_type_SUITE.erl

The type optimizations for `is_record` and `test_arity` checked whether the arity was equal to the size stored in the type information, which is incorrect since said size is the *minimum* size of the tuple (as determined by previous instructions) and not its exact size.
These optimizations will be fixed on the `master` branch later on.
https://bugs.erlang.org/browse/ERL-549

Remove unsafe is_record/test_arity optimizations

---

lib/compiler/src/beam_type.erl
lib/compiler/src/beam_validator.erl

beam_validator did not verify that the Y registers were initialized
before executing the following instructions that could cause a GC:
bs_append/8
bs_init2/6
bs_init_bits/6
gc_bif1/5
gc_bif2/6
gc_bif3/7
test_heap/2
That means that, for example, an incorrect optimization that replaced
an 'allocate_zero' instruction with an 'allocate' instruction when it
was not safe, would not be rejected by beam_validtor, but would
instead cause a crash or other undefined behavior at runtime.

beam_validator: Strengthen validation of GC instructions

---

lib/compiler/src/beam_block.erl
lib/compiler/src/beam_type.erl
lib/compiler/src/beam_utils.erl

Doing a more thorough analysis of how Y registers are used, try to used the slightly cheaper `allocate` instruction instead of `allocate_zero`.

Optimize allocation of stack frames

---

lib/compiler/src/beam_a.erl
lib/compiler/src/beam_block.erl
lib/compiler/src/beam_record.erl
lib/compiler/src/beam_type.erl
lib/compiler/src/beam_utils.erl

The annotations in the optimizing passes currently looks like this:
{'%live',NumRegistersUsed,RegistersUsedBitmap}
{'%def',RegistersDefinedBitmap}
(NumRegistersUsed is no longer used.)
When I attempted to extend some optimizations, I found that I had to
add additional clauses to tolerate/handle both types of
annotations. That problem would only get worse if any more annotations
are added in the future.
To simplify annotation handling, this commit wraps both types of
annotations in a `{'%anno',_}` tuple:
{'%anno',{used,RegistersUsedBitmap}}
{'%anno',{def,RegistersDefinedBitmap}}
The `'%live'` annotation has been renamed to `used` to make it somewhat
clearer what it means, and the unused NumRegistersUsed part of the
old annotation has been removed.
Alternatives considered: My first attempt …

Refactor '%live' and '%def' annotations

---

lib/compiler/src/sys_core_fold.erl
lib/compiler/test/core_fold_SUITE.erl

This pull request includes a few simplifications and clean ups of sys_core_fold. There is also an added optimization of `case` statements that export variables, such as:
```
foo(N) ->
case N of
1 ->
Res = one;
2 ->
Res = two
end,
{ok,Res}.
```

Clean up and improve sys_core_fold optimizations

---

lib/compiler/src/beam_block.erl
lib/compiler/src/beam_bsm.erl
lib/compiler/src/beam_utils.erl
lib/compiler/src/compile.erl

The main part of this pull request is running `beam_block` a second time when other optimizations have been applied. There is also an optimization of consecutive calls to `element/2` in guards. See the individual commit messages for more details.

Run beam_block a second time

---

lib/kernel/doc/src/inet.xml
lib/kernel/src/inet.erl

I couldn't find documentation for `inet:i` which is mentioned in [Erlang Programming](http://shop.oreilly.com/product/9780596518189.do) (page 333) and decided to contribute some.

Add documentation and typespecs for inet:i

---

erts/doc/src/erlang.xml

This PR fixes a broken link to erlang:trace/3 in the documentation.

Fix a broken erlang:trace/3 link in doc

---

lib/compiler/src/sys_core_bsm.erl
lib/compiler/test/bs_match_SUITE.erl

Argument order can prevent the delayed sub binary creation.
Here is an example directly from the Efficiency Guide:
non_opt_eq([H|T1], <<H,T2/binary>>) ->
non_opt_eq(T1, T2);
non_opt_eq([_|_], <<_,_/binary>>) ->
false;
non_opt_eq([], <<>>) ->
true.
When compiling with the `bin_opt_info` option, there will be a
suggestion to change the argument order.
It turns out `sys_core_bsm` can itself change the order, not the
order of the arguments of themselves, but the order in which
the arguments are matched. Here is how it can be rewritten in
pseudo Core Erlang code:
non_opt_eq(Arg1, Arg2) ->
case < Arg2,Arg1 > of
< <<H1,T2/binary>>, [H2|T1] > when H1 =:= H2 ->
non_opt_eq(T1, T2);
< <<_,T2/binary>ffff>, [_|T1] > ->
false;
< <<>>, [] >> ->
true
end.
When rewritten like this, the `bs_start_match2` …

sys_core_bsm: Rearrange arguments to enable delayed sub binary creation

---

lib/hipe/llvm/hipe_llvm.erl

The BEAM compiler chooses not to perform tailcall optimisations for some
calls in tail position, for example to some built-in functions. However,
when the ErLLVM HiPE backend is used, LLVM may choose to perform
tailcall optimisation on these calls, breaking the expected semantics.
To preserve the precise semantics exhibited by BEAM, the `notail`
marker, present in LLVM since version 3.8, is added to call instructions
that BEAM has not turned into tail calls, which inhibits LLVM from
performing tail-call optimisation in turn.
This change affects #1682, which adds some new tests to the HiPE
test suite that are sensitive to this difference in semantics.

ErLLVM: Preserve precise BEAM tailcall semantics

---

erts/emulator/sys/common/erl_sys_common_misc.c
erts/emulator/test/num_bif_SUITE.erl
erts/lib_src/common/erl_printf_format.c

Example:
```
1> float_to_list(0.145, [{decimals,1}]).
"0.2"
```
For a random float with decimals, about 5.5% risk of an invalid rounding up.

Fix rounding bug in float_to_list/2

---

lib/compiler/src/beam_block.erl
lib/compiler/src/beam_validator.erl
lib/compiler/test/beam_block_SUITE.erl
lib/compiler/test/beam_validator_SUITE.erl
lib/compiler/test/beam_validator_SUITE_data/bad_tuples.S

This pull request implements local common sub expression elimination (CSE).
It turns out to be more beneficial than I initially expected, because compilation of records and binary construction can create common sub expression that are not visible in the original source code (see the commit message for an example).

Do local common sub expression elimination (CSE)

---

lib/hipe/main/hipe_main.erl
lib/hipe/rtl/hipe_rtl_verify_gcsafe.erl

An extra sanity check introduced earlier by @margnus1 in #1621.

Make hipe compile option verify_gcsafe the default

---

lib/runtime_tools/doc/src/Makefile
lib/runtime_tools/doc/src/ref_man.xml
lib/runtime_tools/doc/src/scheduler.xml
lib/runtime_tools/doc/src/specs.xml
lib/runtime_tools/src/Makefile
lib/runtime_tools/src/runtime_tools.app.src
lib/runtime_tools/src/scheduler.erl
lib/runtime_tools/test/Makefile
lib/runtime_tools/test/scheduler_SUITE.erl

A utility module to make it easier to measure **scheduler utilization**
instead of direct calls to `erlang:statistics(scheduler_wall_time)`.
Example usage (from my idle system with 4 normal schedulers and 4 dirty-cpu schedulers):
- Measure during 2 seconds
```
1> scheduler:utilization(2).
[{total,1.4415967283315043e-5,"0.0%"},
{weighted,4.805322427771681e-6,"0.0%"},
{normal,1,2.0007111643316946e-5,"0.0%"},
{normal,2,2.0146275669164254e-5,"0.0%"},
{normal,3,2.1926912581686335e-5,"0.0%"},
{normal,4,5.324709367537587e-5,"0.0%"},
{cpu,5,0.0,"0.0%"},
{cpu,6,0.0,"0.0%"},
{cpu,7,0.0,"0.0%"},
{cpu,8,0.0,"0.0%"}]
```
- or take samples "manually"
```
2> T0 = scheduler:wall_time().
{scheduler_wall_time,[{normal,1,40787,58457},
{normal,2,21092,51683},
{normal,3,17112,48889},
{normal,4,27168,98477}, …
```

runtime_tools: Add scheduler module

---

lib/compiler/src/beam_block.erl
lib/compiler/test/beam_block_SUITE.erl

1a029efd1ad47f started to run the beam_block pass a second time.
Since it is run after introduction of the optimized floating point
instructions, it must handle those instructions correctly.
In particular, it must be careful when hoisting allocation
instructions. For example, the following code:
{test_heap,{alloc,[{words,0},{floats,1}]},5}.
.
.
.
{fmove,{fr,2},{x,0}}.
{allocate_zero,1,4}.
must not be rewritten to:
{test_heap,{alloc,[{words,0},{floats,1}]},5}.
.
.
.
{allocate_zero,1,4}.
{fmove,{fr,2},{x,0}}.
because beam_validator will not consider it safe. (The code may
actually be safe depending on what the code between the two allocation
instructions do.)
https://bugs.erlang.org/browse/ERL-555

Fix incorrect handling of floating point instructions

---

erts/emulator/beam/instrs.tab
erts/emulator/beam/ops.tab
lib/compiler/src/beam_a.erl
lib/compiler/src/beam_block.erl
lib/compiler/src/beam_disasm.erl
lib/compiler/src/beam_flatten.erl
lib/compiler/src/beam_type.erl
lib/compiler/src/beam_utils.erl
lib/compiler/src/beam_validator.erl
lib/compiler/src/beam_z.erl
lib/compiler/src/compile.erl
lib/compiler/src/genop.tab
lib/compiler/src/v3_codegen.erl
lib/compiler/test/compile_SUITE.erl
lib/compiler/test/compile_SUITE_data/big.erl
lib/hipe/icode/hipe_beam_to_icode.erl

Instructions that produce more than one result complicate
optimizations. `get_list/3` is one of two instructions that
produce multiple results (`get_map_elements/3` is the other).
Introduce the `get_hd/2` and `get_tl/2` instructions
that return the head and tail of a cons cell, respectively,
and use it internally in all optimization passes.
For efficiency, we still want to use `get_list/3` if both
head and tail are used, so we will translate matching pairs
of `get_hd` and `get_tl` back to get_list instructions.

Eliminate get_list/3 internally in the compiler

---

erts/doc/src/erl.xml
erts/preloaded/src/init.erl
lib/kernel/doc/src/code.xml

This patch rewords the docs related to the runtime system mode.
It addresses two things:
* Makes clear that embedded mode disables autoloading.
* Explains which modules are eager loaded in embedded mode.
Looking for a balance between being accurate and concise, I have taken these compromises:
* The descriptions do not mention the code path. The documentation of `-pa` and friends and the concept of code path itself is enough contextual information.
* The descriptions of interactive mode do not mention what `init` lazy loads, except in the documentation of `init` itself (and still there, there is only a vague one-liner). I believe interactive mode for readers of `erl` or `code` docs is mostly about being able to autoload anything in the code path, and the fact that init skips some …

Reword docs related to the runtime system mode

---

erts/emulator/beam/erl_alloc.h
erts/emulator/beam/erl_msacc.h
erts/emulator/beam/erl_process.h
erts/emulator/beam/global.h

When building OTP on PowerPC/RTEMS platform which have small data area with short addressing, we had to fix the section declaration of multiple variables and add missing explicit extern storage class.

Fix the build on targets with small data area

---

lib/ssl/doc/src/ssl.xml
lib/ssl/doc/src/using_ssl.xml
lib/ssl/src/dtls_v1.erl
lib/ssl/src/ssl.erl
lib/ssl/src/ssl_cipher.erl
lib/ssl/test/ssl_basic_SUITE.erl
lib/ssl/test/ssl_test_lib.erl

Changes cipher suites to be maps instead of tuples to make handling of the sets of algorithms that a cipher suite represent easier.  Will handle tuples as input for backwards compatibility. 
Also use a more logical default value for mac in AEAD suites.
Also add new API functions to make customization  of cipher suites easier, requiring less effort  for the user.  This will also mean some old cipher_suite functions will become deprecated in 21.

Ingela/ssl/add ciphers to default/otp 14760

---

lib/ssl/src/ssl_connection.erl

ssl: Add the unexpected message to `#alert{}` in `handle_common_event()`, instead of passing it to `handle_own_alert()` after wrapping it in a tuple with `StateName` (i.e. `{StateName, Msg}`).
The `StateName` is passed to `handle_normal_shutdown()` and to `alert_user()`. The latter has a clause matching it against `connection`. Unfortunately, when the argument was in fact `{StateName, Msg}`, another clause was executed which dropped the `active` flag value and forced it to `false`, even if the state was actually `connection`. It meant that later in `send_or_reply()`, the alert was not propagated to the user, even though it should (`active` set to `true` or `once`).
Now that `handle_common_event()` always passes the actual `StateName`, the problem is fixed.

ssl: Add the unexpected message to #alert{}

---

lib/compiler/src/beam_validator.erl

Strengthen beam_validator to check that the stack is initialized
when an instruction with an {f,0} operand is executed.
For example, the following code sequence:
{allocate,0,1}.
{bif,element,{f,0},[{integer,1},{x,0}],{x,0}}.
should not be accepted because the stack may be scanned if
element/2 fails. That could cause a crash or other undefined
behavior if garbage on the stack looks like a catch tag.

Check that the stack is initialized when an exception may occur

---

lib/compiler/src/beam_block.erl
lib/compiler/src/beam_clean.erl
lib/compiler/src/beam_flatten.erl
lib/compiler/src/beam_split.erl

I was so happy that the commit (1a029efd1ad47f) that ran `beam_block` a second time improved the code in so many modules, that I didn't think of logical next step: to combine adjacent blocks before running  `beam_block` the second time.
It turns that combining blocks provide many opportunities for optimizations, eliminating register shuffling in many modules and doing more common sub expression elimination in the `wx` application.

Combine blocks when running beam_block the second time

---

erts/emulator/beam/utils.c

This commit brings the perform of a non-strict equality check of
binaries into the same range as strict ones.
Currently, these checks can be significantly slower because they go
through the general comparison code which doesn't have an optimization
to check the size before comparing contents in the case that it's
checking equality.
--
Hopefully I've got this right, there were two things that were unclear to me from the contribution guidelines.
Firstly, this isn't really a bug fix or an enhancement (in the way it's described), so I wasn't sure what the testing requirement is. In any case, I've run the complete test suite before and after the change and the results are the same either way.
Secondly, the whitespace in this file is unusual to me, it's a mixture of tabs and spaces on the same …

Optimize non-strict equality check of binaries differing in size

---

erts/emulator/beam/bif.tab
erts/emulator/beam/erl_db.c
lib/stdlib/doc/src/ets.xml
lib/stdlib/src/ets.erl
lib/stdlib/test/ets_SUITE.erl

This PR adds a function for resolving the tid() of named ETS tables, analogous to `erlang:whereis/1`.
http://erlang.org/pipermail/erlang-questions/2018-January/094616.html

Add ets:whereis/1 for resolving table names -> tid()

---

lib/dialyzer/src/dialyzer_plt.erl
lib/stdlib/src/beam_lib.erl

The previous mechanism was based on the core file which
meant that for every module in the PLT, we had to fetch
its .beam file, retrieve Erlang AST, compile that down
to core, serialize it into a binary and then get its MD5.
In a project with stdlib, kernel, elixir and a small
application in the PLT,  relying on beam_lib sped up
--check_plt from 10s to 0.8s.
Other workflows, such as checking and adding new modules
to a PLT, have also seen improvements in the range of 2x
to 3x.

Compute MD5s in dialyzer using the .beam file

---

lib/snmp/doc/src/snmp_impl_example_agent.xml

The EX1-MIB cannot be compiled because of the missing IMPORT of "experimental".
The other instances EX1-MIB.mib (otp/lib/snmp/examples/ex1, otp/lib/snmp/test/snmp_test_data) are correct. 
While at this I also synchronized the indenting (whitespaces) with the other EX1-MIB.mib,
so the documentation is a bit more visually pleasing.

Fix example MIB in the documentation

---

lib/hipe/icode/hipe_icode_inline_bifs.erl

I tried running HiPE tests and they all pass, but I'm not really sure they actually hit the code and I'm not sure how to run regular compiler tests, but leveraging HiPE.

Inline more type test BIFs in HiPE

---

lib/stdlib/src/string.erl
lib/stdlib/test/string_SUITE.erl

The `string:prefix` function will result in function clause exception in `string:prefix_1` if the second argument is an empty binary. So, `string:prefix(<<"abc">>, <<>>)` will not match any function clauses. This PR fixes this issue.

ERL-558 Add the missing function clause for string:prefix

---

lib/sasl/doc/src/release_handler.xml
lib/sasl/doc/src/systools.xml
lib/sasl/src/systools_make.erl
lib/sasl/test/systools_SUITE.erl
system/doc/design_principles/release_structure.xml
system/doc/system_principles/create_target.xmlsrc

The run scripts generated by rebar3 (relx) support replacing environment variable in `sys.config` and `vm.args`. A common issue people encounter with this is they attempt like:
```
{port, ${PORT}}
```
This fails because it is not a valid Erlang term file, so `systools:make_tar` will fail. So only strings or single quoted atoms are able to be used.
This patch adds a option to `make_tar` that tells it not to try to consult the `sys.config` file and to just include it as is.
I realized I still need to add it to the docs of `systools:make_tar`, but is this an acceptable feature?

add option to not check sys.config file when building tarball

---

lib/inets/doc/src/http_uri.xml
lib/inets/src/http_lib/http_uri.erl

From the `http_uri` module documentation it may be intended that the listed types are exported by the module, and I have seen at least a couple of projects using those types as exported ([example](https://github.com/for-GET/jesse/blob/1.5.0/src/jesse.erl#L80)). I think it makes sense, hence this PR.
I consider this more a bug fix that a new feature, hence I based on `maint`. If you prefer I base on `master`, please let me know and I will be happy to do so.
-----
BTW I have not understood the `marker`s in the documentation e.g. https://github.com/erlang/otp/blob/OTP-20.2.4/lib/inets/doc/src/http_uri.xml#L78

Export types documented for http_uri module

---

erts/doc/src/erlang.xml
erts/doc/src/notes.xml
erts/preloaded/src/erlang.erl

Attempt to make the system_info docs easier to navigate by grouping items of similar themes together in the documentation.

Cleanup erlang:system_info docs

---

erts/emulator/sys/unix/erl_child_setup.c

Some container environments send SIGTERM to all processes when terminating. We don't want erl_child_setup to terminate in these cases as that will prevent beam from properly cleaning up.
See also https://bugs.erlang.org/browse/ERL-576

Ignore SIGTERM in erl_child_setup

---

lib/stdlib/doc/src/io.xml

The documentation did not mention that the +pc flag affects the detection of lists as strings, and was generally lacking details about what the t modifier does for ~p.

Improve documentation of io:format ~p when Unicode is involved

---

lib/debugger/src/dbg_ieval.erl
lib/debugger/test/int_eval_SUITE.erl
lib/debugger/test/int_eval_SUITE_data/my_int_eval_module.erl

Prior to this change, calls inside binaries were
treated as top level which would cause the `Fun(Arg)`
call inside `<<Fun(Arg)/binary>>` to return an internal
dbg_ieval tuple and ultimately error with badarg.

Do not treat binaries as top level in dbg_ieval

---

lib/stdlib/src/io_lib_format.erl
lib/stdlib/test/io_SUITE.erl

When the scan_format/unscan_format stuff was included in OTP, it was slightly modified from the original implementation. At some point this detail was lost: you can specify a pad character but use default precision by having an empty precision field.

Make io_lib:unscan_format/1 work with pad char and default precision

---

lib/stdlib/doc/src/io.xml
lib/stdlib/src/erl_lint.erl
lib/stdlib/src/io_lib_format.erl
lib/stdlib/test/io_SUITE.erl

Currently, the t and l modifiers are not allowed at the same time. This means that unicode atoms cannot be printed at the same time as suppressing detection of printable lists:
``` 
13> io:fwrite("~lp~n", [{[666],list_to_atom([666])}]).
{[666],'\x{29A}'}
14> io:fwrite("~tp~n", [{[666],list_to_atom([666])}]).
{"ʚ",'ʚ'}
```
with this patch, you can also do:
```
15> io:fwrite("~ltp~n", [{[666],list_to_atom([666])}]).
{[666],'ʚ'}
```
Note: the erl_lint:extract_sequence() function could probably be completely rewritten in a simpler and nicer way using the io_lib:scan_format() functionality, but I don't have time for such things right now.

Allow multiple modifier characters in io:format control sequences

---

lib/compiler/src/beam_asm.erl
lib/dialyzer/src/dialyzer_contracts.erl
lib/dialyzer/test/small_SUITE_data/results/chars
lib/dialyzer/test/small_SUITE_data/results/extra_range
lib/dialyzer/test/small_SUITE_data/src/chars.erl
lib/dialyzer/test/small_SUITE_data/src/extra_range.erl

This fixes a problem where Dialyzer did not warn about the following situation, because it discarded information unnecessarily:
```
-spec f(integer()) -> ook | error.
f(1) -> ok;
f(2) -> error.
t(X) when is_integer(X) ->
ok = f(X).  % quietly accepted
```
If the spec was simply missing an entry, you got a warning even without this fix:
```
-spec f(integer()) -> error.  % forgot to mention that 'ok' is valid
f(1) -> ok;
f(2) -> error.
t(X) when is_integer(X) ->
ok = f(X).  % warns about invalid match
```
The extraneous information in the first case simply made Dialyzer forget that there was any spec at all.

Dialyzer should not throw away spec information because of overspec

---

erts/doc/src/erts_alloc.xml
erts/emulator/beam/erl_alloc.c
erts/emulator/beam/erl_alloc_util.c
erts/emulator/beam/erl_alloc_util.h
erts/emulator/sys/common/erl_mmap.c
erts/emulator/sys/common/erl_mmap.h
erts/emulator/sys/common/erl_mseg.c
erts/emulator/sys/common/erl_mseg.h

Thanks to @bhuztez  and #1669 
no longer any need to hog lots of low virtual memory for HiPE code allocations on x86_64.

Remove low memory need for HiPE on x86_64

---

lib/inets/src/http_lib/http_uri.erl
lib/inets/test/uri_SUITE.erl

I noticed this following work on #1724 .
I ran tests for inets app:
```
Testing tests.inets_test: TEST COMPLETE, 238 ok, 0 failed, 319 skipped of 557 test cases
```

inets: fix scheme validation in http_uri:parse when binary URI

---

erts/doc/src/match_spec.xml

I was running this code in shell and expected it to take default `self()` meta tracer,
and start tracing `erlang:put/2`.
```
F = fun F() -> timer:sleep(5000), erlang:get(unique_field), erlang:put(unique_field, 123), F() end.
erlang:trace_pattern({erlang, put, 2}, [{['$1', '_'], [{'==', '$1', unique_field}], []}], [global]).
erlang:trace_pattern({erlang, get, 1}, [{['_'], [], [{trace, [], [call, timestamp]}]}], [meta]).
Pid = spawn(F).
```
But tracing didn't start:
```
6> flush().
Shell got {trace_ts,<0.70.0>,call,
{erlang,get,[unique_field]},
{1521,118606,753838}}
Shell got {trace_ts,<0.70.0>,call,
{erlang,get,[unique_field]},
{1521,118611,754798}}
Shell got {trace_ts,<0.70.0>,call,
{erlang,get,[unique_field]},
{1521,118616,755705}}
ok
7> erlang:trace_info(Pid, flags).
{flags,[]}
``` …

Tracing MatchSpec docs update

---

erts/doc/src/erlang.xml
erts/emulator/beam/erl_bif_info.c
lib/common_test/src/test_server_ctrl.erl
lib/dialyzer/test/r9c_SUITE_data/src/mnesia/mnesia_tm.erl
lib/mnesia/src/mnesia_tm.erl
lib/stdlib/src/c.erl

process_info/1 retrieves a number of properties related to a process,
including the list of messages in its mailbox.  This is potentially
unsafe if the target process has a large number of queued messages:
- there is no a priori upper bound on the amount of memory being
allocated to hold that list, and
- the loop to retrieve the messages is uninterruptible, so the
Erlang scheduler where this executes blocks for the duration
We've seen process_info/1 bring down heavily loaded nodes on more
than one occasion.  At least once it appeared to have blocked the
Erlang heart process from executing, causing the external heart to
kill the VM.
Consequently this removes 'messages' from the list of process_info
tags to retrieve for process_info/1.  Note that process_info/1 still
retrieves …

make erlang:process_info/1 not retrieve messages

---

lib/kernel/src/code.erl

This checks if the module is already loaded using erlang:module_loaded
before calling the code server. This should improve performance of the
call significantly since the case where module is already loaded is the
common one.
The change shouldn't cause any problems. It's worth noting that
code:ensure_modules_loaded already does a similar check.

Short-circuit code:ensure_loaded for already-loaded modules

---

lib/stdlib/doc/src/lists.xml
lib/stdlib/src/lists.erl
lib/stdlib/test/lists_SUITE.erl

This is essentially PR 102, https://github.com/erlang/otp/pull/102.
The OTP Technical Board decided to change the name of the function to
search/2.

stdlib: Add function lists:search/2

---

lib/kernel/src/group.erl

For out system we have made configuration console over ssh by erlang. The configuration system have next process' tree: 
`ssh_channel_sup -> ssh_cli -> group -> our_shell`
_our_shell_ receive message from ssh by `io:get_line("")` and by programming logic should stop after some timeout. We kill _our_shell_ process to stop after timeout, but _group_ doesn't receive 'EXIT' signal, _ssh_cli_ continue wait data from SSH. The SSH connection continue alive indefinitely.
Current fix is allow to handle 'EXIT' siglan on from _out_shell_ in _group_ and stop group correctry (after _group_ stopped, _ssh_cli_ stopped by monitor and SSH connection closed succsssfully).

kernel: in the group added processing of 'EXIT' signal from shell

---

lib/compiler/src/v3_core.erl
lib/compiler/test/lc_SUITE.erl

When a generator in a list comprehension was given some
other term than a list, the wrong line could be pointed
out in the exception. Here is an example:
bad_generator() ->
[I ||               %%This line would be pointed out.
I <- not_a_list].
https://bugs.erlang.org/browse/ERL-572

Point out the correct line in an exception for a bad generator

---

erts/emulator/beam/dist.c
erts/emulator/beam/dist.h
erts/emulator/beam/erl_bif_trace.c
erts/emulator/beam/erl_db_util.c
erts/emulator/beam/erl_message.c
erts/emulator/beam/erl_proc_sig_queue.c
erts/emulator/beam/erl_process.h
erts/emulator/beam/erlang_dtrace.d
erts/emulator/beam/msg_instrs.tab
erts/emulator/beam/sys.h
lib/kernel/doc/src/seq_trace.xml
lib/kernel/include/dist.hrl
lib/kernel/src/dist_util.erl
lib/kernel/src/seq_trace.erl
lib/kernel/test/seq_trace_SUITE.erl

This PR allows the use of any term as a `seq_trace` token label, making it easier to use this functionality in concert with tracing libraries like OpenCensus and OpenTracing that use very large identifiers.
This also fixes a crash when a label that did not fit into an immediate on a 32-bit emulator was sent from a 64-bit emulator to a 32-bit one.
http://erlang.org/pipermail/erlang-questions/2018-January/094638.html
@tsloughter

Lift the type restrictions on seq_trace token labels

---

lib/compiler/src/beam_utils.erl
lib/compiler/test/beam_utils_SUITE.erl

beam_record would make an unsafe optimization for the
not_used_p/4 function added to beam_utils_SUITE in this
commit. The bug is in beam_utils, which would falsely
report that {x,4} was unused when it in fact was used.
The bug was in the function not_used/1. The purpose of
not_used/1 is to return a 'not_used' result unless the
actual result is 'used'. Unfortunately it was not
implemented in that way. It would let a 'transparent'
result slip through, which the caller in this case would
convert to 'killed' (because the register was killed on
all other paths).
Reported-by: Richard Carlsson

Fix unsafe optimization of record test

---

system/doc/getting_started/conc_prog.xml

The `server_node()` function in the sample code was referring to `messenger@bill`, while the commands that follow use `messenger@super` as node name.
Making both names consistent make it easier for newbies to test the code. (Well, I think)

Doc: use that node name between code and commands

---

erts/emulator/beam/erl_process_dump.c

63e1c58d27ab (PR #1725) started to compile external funs
as literals.
This commit updates the dumping of literal areas to dump
external fun literals to the crash dump.

Support dumping of external fun literals to a crash dump

---

lib/compiler/src/beam_validator.erl
lib/compiler/test/beam_validator_SUITE.erl
lib/compiler/test/beam_validator_SUITE_data/receive_stacked.S
lib/compiler/test/beam_validator_SUITE_data/receive_stacked.erl

Waiting messages for a process may be stored in a queue
outside of any heap or heap fragment belonging to the process.
This is an optimization added in a recent major release to
avoid garbage collection messages again and again if there
is a long message queue.
Until such message has been matched and accepted by
the remove_message/0 instruction, the message must not be
included in the root set for a garbage collection, as that
would corrput the message. The loop_rec/2 instruction explicitly
turns off garbage collection of the process as long messages
are being matched.
However, if the compiler were to put references to a message
outside of the heap in an Y register (on the stack) and there
happened to be a GC when the process had been scheduled out,
the message would be corrupted and the …

Check that messages outside of the heap are not corrupted

---

lib/stdlib/doc/src/timer.xml

It was switched to monotnic_time from timestamp 3 years ago
in d927209aa36fe370eb4ecf0a081923b0b951458b
(hope I got the formatting right copied it from another place where monotonic_time was references)
Thanks for Erlang/OTP :green_heart:

Reflect actual timer:tc behaviour in documentation

---

lib/kernel/doc/src/heart.xml

The timestamp code in heart uses monotonic time so it is immune to NTP
changes.

Remove note about heart rebooting on NTP updates

---

lib/inets/doc/src/httpc.xml
lib/inets/src/http_client/httpc_handler.erl
lib/inets/src/http_client/httpc_response.erl
lib/inets/test/httpc_SUITE.erl

I experienced intermittent `socket_closed_remotely` errors in tests using httpc as client. I managed to reproduce re-attempting same request multiple times (sometimes failing after a few hundred requests, sometimes after a handful of requests). I traced the HTTP and TCP traffic while reproducing symptom, and I narrowed the trace down to a `Connection: close` by the server not being honoured by httpc. I then wrote an isolated test for httpc - in this PR - confirming my diagnosis. I wrote a patch for httpc and tested it (with the httpc_SUITE).
I noticed there are some hits searching on the Web for `socket_closed_remotely` using httpc, and the relevant reference is https://bugs.erlang.org/browse/ERL-473 . Though, even if symptom is the same, I am not sure this is the same issue.
I am basing …

Teach httpc to honour server connection close

---

erts/emulator/sys/common/erl_sys_common_misc.c
erts/emulator/test/num_bif_SUITE.erl

to better conform with io_lib:format("~.*f", [D,F])
- float_to_list/2 with option 'decimals' was introduced in R16. The incentive was to get something much faster than io_lib:format.
- float_to_list/2 has never conformed fully with io_lib:format.
- Prior to OTP-20.3 it had a pretty bad rounding-up bug where for example
`float_to_list(0.145, [{decimals,1}])` returned `"0.2"`.
This PR tries to get it even closer to io_lib:format. For example `float_to_list(123.215, [{decimals,2}])` is now `"123.22"` as it should be and not `"123.21"`.
There are however still cases when it differs from io_lib:format:
```
1> float_to_list(6.3741255667210375, [{decimals,15}]).
"6.374125566721038"
2> io_lib:format("~.15f", [6.3741255667210375]).
["6.374125566721037"]
```
I don't know why it gets it wrong here, …

Improve float_to_list(F, [{decimals,D}])

---

lib/ssh/doc/src/ssh.xml

`ssh_server_key_api` was missed instead`ssh_client_key_api` mentioned two times.

Fix typo in ssh key_cb type description

---

erts/doc/src/match_spec.xml

This removes the matchspec instructions `is_seq_trace` and `get_tcw/0`
from the documentation for table-oriented matchspecs.
This is likely correct as both are already documented under "Functions
Allowed Only for Tracing", despite appearing in the list of possible
options for table specs.
The following observations further back this change up:
```erl
erlang:match_spec_test([whatever], [{'_', [], [{is_seq_trace}]}], trace).
%=> {ok,true,[],[]}
erlang:match_spec_test({whatever}, [{'_', [], [{is_seq_trace}]}], table).
%=> {error,[{error,"Special form 'is_seq_trace' used in wrong dialect."}]}
erlang:match_spec_test([whatever], [{'_', [], [{get_tcw}]}], trace).
%=> {ok,true,[],[]}
erlang:match_spec_test({whatever}, [{'_', [], [{get_tcw}]}], table).
%=> {error,[{error,"Function get_tcw/0 cannot …
```

Remove trace-specific terms from docs for table-oriented matchspecs

---

erts/emulator/beam/bif.c
erts/emulator/test/exception_SUITE.erl

It is allowed to set the backtrace depth to 0, but when
an exception is catched the stacktrace will still contain
one element:
1> erlang:system_flag(backtrace_depth, 0).
8
2> catch error(badarg).
{'EXIT',{badarg,[{shell,apply_fun,3,
[{file,"shell.erl"},{line,908}]}]}}
However, when an exception is raised using `erlang:raise/3`, there
will be no elements in the stacktrace:
3> catch erlang:raise(error, badarg, [{fake,name,[arg],[]}]).
{'EXIT',{badarg,[]}}
Since the `error_handler` module uses `erlang:raise/3` to
raise an exception when an undefined function is called,
there will not be any stacktrace when calling an undefined
function:
4> catch undef_module:undef_name(some_argument).
{'EXIT',{undef,[]}}
Fix this inconsistency by changing `erlang:raise/3` so that
it always includes one …

Make stacktraces consistent when backtrace_depth is 0

---

erts/emulator/beam/utils.c

Sending a large term to the error logger has two problems related
to the size and sign of the variables used to represent lengths:
- the API functions (erts_send_error_term_to_logger() et al) perform
an unchecked narrowing conversion from size_t to int when passing
dsbufp->str_len to the internal functions; this may both truncate
the length and make it negative
- do_send_term_to_logger() and do_send_to_logger() multiply the
int-typed length by 2 before widening it to Uint and adding a few
more values; the intermediate product may overflow causing loss
of high bits and a change of sign; if the intermediate product is
negative the final size will be an extremely large positive value
The end result is that the computed buffer size can be arbitrarily
wrong, either too small or too large. …

fix integer truncation bugs in error logger path

---

lib/erl_interface/src/legacy/erl_marshal.c

Compiling OTP-20.3.4 with GCC-7 generates the following warning:
CC     /tmp/otp_src_20.3.4/lib/erl_interface/obj.st/x86_64-unknown-linux-gnu/erl_marshal.o
legacy/erl_marshal.c: In function 'erl_init_marshal':
legacy/erl_marshal.c:110:5: warning: 'memset' used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]
memset(cmp_array, 0, CMP_ARRAY_SIZE);
^~~~~~
CMP_ARRAY_SIZE (256) is the number of elements in that array, but the
elements are not char but enum, which is 4 bytes on e.g. x86-64.
This results in 3/4 of the array not being correctly initialized.
Idiomatic C is to pass sizeof cmp_array to memset(), so that's what I did.

erl_interface: fix bad memset

---

erts/configure.in

This is part of the closed #1762 by @perhedeland.
I have not done any testing on FreeBSD which was the aim of #1762.
But it's still correct to remove the config test for `MAP_NORESERVE`
and instead test for `mprotect` which is what is actually used for hipe code allocation
on all hardware now.

Remove config test of MAP_NORESERVE for hipe on x86_64

---

lib/compiler/src/sys_core_fold.erl
lib/compiler/test/fun_SUITE.erl

Rewrite calls such as:
(fun erlang:abs/1)(-42)
to:
erlang:abs(-42)
While we are at it, also add rewriting of `apply/2` with a fixed
number of arguments to a direct call of the fun. For example:
apply(F, [A,B])
would be rewritten to:
F(A, B)
https://bugs.erlang.org/browse/ERL-614

Rewrite a call of a literal external fun to a direct call

---

lib/stdlib/doc/src/sys.xml
lib/stdlib/src/sys.erl
lib/stdlib/test/sys_SUITE.erl
system/doc/design_principles/spec_proc.xml

Currently, in sys:stat/2, the message out only count for system events with format `{out,
Msg, To}`. However, the gen_server:reply/5 will call sys:handle_debug/4
with format `{out, Reply, To, State}`. That will make the message out
count fail to pattern matching.
Here's the bug repro step:
```
-module(foo).
-behavior(gen_server).
-export([init/1, handle_call/3, handle_cast/2, handle_info/2]).
init(_) -> {ok, []}.
handle_call(_, _, State) -> {reply, ok, State}.
handle_cast(_, State) -> {noreply, State}.
handle_info(_, State) -> {noreply, State}.
```
```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Eshell V9.2  (abort with ^G)
1> {ok, Pid} = gen_server:start(foo, [], []).
{ok,<0.66.0>}
2> sys:trace(Pid, true).
ok
3> …
```

[stdlib/sys.erl] Fix sys module's debug statistics not including the out message count when using gen_server:call/2.

---

lib/stdlib/doc/src/sys.xml
lib/stdlib/src/sys.erl
lib/stdlib/test/sys_SUITE.erl

Hi. We can install one function with state `undefined` more times beacuse of [here](https://github.com/erlang/otp/blob/OTP-20.3.2/lib/stdlib/src/sys.erl#L586). Read detailed explanation in [my other PR](https://github.com/erlang/otp/pull/1763).  
This backward compatible PR fixes above bug and supports installing one debug function several times.  
Code snippet:  
```erl
% Get state of 'kernel_sup' process:
1> GetDbgFuncs = fun() -> {_, _, _, [_, _, _, X|_]} = sys:get_status(kernel_sup), X end.
#Fun<erl_eval.20.13309239>
2> GetDbgFuncs().
[]
3> State = undefined.
undefined
%% Always return 'undefined' as state:
4> DbgFunc = fun(_, _, _) -> State end.
#Fun<erl_eval.18.13309239>
%% Old functionality:
5> sys:install(kernel_sup, {DbgFunc, State}).
ok
6> GetDbgFuncs(). …
```

[stdlib/sys]: install one debug function more times

---

lib/sasl/doc/src/appup.xml

It should be explicitly stated that the application will not actually be
restarted, depending on how it was originally started, even if it is
currently running.

Add a bit of documentation about restart_application

---

lib/hipe/cerl/erl_types.erl
lib/hipe/test/Makefile
lib/hipe/test/erl_types_SUITE.erl

The existing `test/0` function in `erl_types` was not being run in the OTP test suite, and it had not been updated to match the implementation in the module (`maps` vs. `dict`). This commit removes the macros that excluded some functions, exports the functions now included in the module, and extracts the test into a new `common_test` suite, `erl_types_SUITE`.

Move erl_types test into a common_test suite

---

lib/compiler/src/cerl_trees.erl
lib/edoc/src/edoc_doclet.erl
lib/kernel/src/hipe_unified_loader.erl

See https://github.com/erszcz/docsh/issues/23 for an explanation about how the files were found.
This PR doesn't add any meaningful documentation, it only makes `edoc:get_doc(File, [])` on the files in question not result in an error anymore.

Fix syntactic issues in EDoc comments across some libs

---

erts/doc/src/Makefile
erts/doc/src/alt_disco.xml
erts/doc/src/part.xml
erts/emulator/test/distribution_SUITE.erl
lib/kernel/doc/src/Makefile
lib/kernel/doc/src/erl_epmd.xml
lib/kernel/doc/src/ref_man.xml
lib/kernel/doc/src/specs.xml
lib/kernel/src/erl_epmd.erl
lib/kernel/src/inet_tcp_dist.erl
lib/ssl/src/inet_tls_dist.erl

This makes it possible to create a custom integration with a
key-value store for example. The key would then point to the
actual address. You would have to write your own epmd module
to make use of that feature.
I have not contributed to erlang/otp before so it's kind of new to me. I have read the contributing guidelines, but I'm not sure if this change requires any of the mentioned steps (except for documentation which I will fix, if this PR is even 'considerable'). Please let me know if I'm missing or not understanding something there.
Having said that I also have "my own" tcp dist and epmd module that implements something alike here (although in Elixir): https://github.com/tverlaan/inet_tcp_dist/

epmd: allow alternative to dns resolving for nodename

---

erts/emulator/beam/erl_nif.c
erts/emulator/test/nif_SUITE.erl
erts/emulator/test/nif_SUITE_data/nif_SUITE.c

Causes heap corruption if non-immediate was built in same environment before `enif_binary_to_term`.

Fix bug in enif_binary_to_term for immediates

---

lib/dialyzer/src/dialyzer_dataflow.erl
lib/dialyzer/test/small_SUITE_data/results/unused_funs
lib/dialyzer/test/small_SUITE_data/src/unused_funs.erl

Warnings are not generated for funs residing in dead code.
In particular, warnings like "The created fun has no local return" are
no longer generated for funs declared in clauses or functions that
cannot be run.

dialyzer: Do not emit warnings for unreachable funs

---

lib/ssl/src/Makefile
lib/ssl/src/dtls_connection.erl
lib/ssl/src/dtls_listener_sup.erl
lib/ssl/src/dtls_packet_demux.erl
lib/ssl/src/dtls_socket.erl
lib/ssl/src/ssl.app.src
lib/ssl/src/ssl.erl
lib/ssl/src/ssl_connection_sup.erl
lib/ssl/src/ssl_internal.hrl

We want to prepare the code for more advanced DTLS usage and possibility
to run over SCTP. First assumption was that the demultiplexer process
"dtls listener" was needed for UDP only and SCTP could be made more TLS
like. However the assumption seems not to hold. This commit prepares
for customization possibilities.

ssl: Generalize DTLS packet multiplexing

---

lib/dialyzer/src/dialyzer.erl
lib/dialyzer/src/dialyzer_contracts.erl
lib/dialyzer/src/typer.erl
lib/dialyzer/test/overspecs_SUITE_data/dialyzer_options
lib/dialyzer/test/overspecs_SUITE_data/results/iodata
lib/dialyzer/test/overspecs_SUITE_data/results/iolist
lib/dialyzer/test/overspecs_SUITE_data/src/iodata.erl
lib/dialyzer/test/overspecs_SUITE_data/src/iolist.erl
lib/dialyzer/test/specdiffs_SUITE_data/dialyzer_options
lib/dialyzer/test/specdiffs_SUITE_data/results/iodata
lib/dialyzer/test/specdiffs_SUITE_data/results/iolist
lib/dialyzer/test/specdiffs_SUITE_data/src/iodata.erl
lib/dialyzer/test/specdiffs_SUITE_data/src/iolist.erl

The -Woverspecs (-Wspecdiffs) option generates warnings in a few more
cases. The refinement is analogous to the test that -Wunderspecs
already does: it checks if the contract has nothing in common with
some element (see erl_types:t_elements/1) of the success typing.
See also https://github.com/erlang/otp/pull/1722.

dialyzer: Refine the test for overspecified functions

---

erts/emulator/beam/erl_port_task.c

erts_port_task_schedule() has a label "fail" where it calls abort_signal_task().  It doesn't check the type of the port first, meaning it may do the call for non-ERTS_PORT_TASK_PROC_SIG ports, and in those cases abort_signal_task() calls through an uninitialized function pointer, causing a segfault.
This fix checks the type before allowing the call, which seems to cure the problem.
See https://bugs.erlang.org/browse/ERL-621 for background.
I am also concerned about the abort_nosuspend_task() call, but don't have a test case showing a malfunction there.

do not call abort_signal_task() with invalid data

---

lib/stdlib/doc/src/io.xml
lib/stdlib/src/io_lib_pretty.erl
lib/stdlib/test/io_SUITE.erl

See also https://bugs.erlang.org/browse/ERL-607.
A zero field width used to insert line breaks "everywhere", but with
this patch no line breaks are inserted.

stdlib: Make pP insert no line breaks with field width zero

---

lib/stdlib/test/maps_SUITE.erl

As part of writing some new QuickCheck model for maps iterators, I've run into the following inconsistency:
In Release 20.0:
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V9.3  (abort with ^G)
1> maps:with([], {0, <<>>, 97}).
** exception error: {badmap,{0,<<>>,97}}
in function  maps:with/2
called as maps:with([],{0,<<>>,97})
2> 
```
Whereas in gfefb15c, we have:
```
Erlang/OTP 21 [RELEASE CANDIDATE 1] [erts-9.3.1] [source-b873e5cd6d] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Eshell V9.3.1  (abort with ^G)
1> maps:with([], {0, <<>>, 97}).
in function  maps:with/2
called as maps:with([],{0,<<>>,97})
2> 
```
The difference is in the error return.
The "map" `{0, <<>>, …

Maps inconsistency from 20.0 to OTP-21.0-rc1-84-gfefb15c576

---

erts/etc/common/escript.c

Since commit 385b18de6fd72672ed7d6736b30f56d6691d4433, the emulator path was not copied anymore before pushing it to the args vector (before it was done within the `push_words` function. Since on Windows `free_env_val` is not a NOP as it is on Unix systems, the string is freed and afterwards used, leading to strange errors like this:
escript: Error executing 'àyI': 2
This is fixed by removing the `free_env_val` call.

Fix use-after-free on Windows in escript

---

HOWTO/INSTALL-RASPBERRYPI3.md
xcomp/erl-xcomp-armv8-rpi3-linux-gnueabihf.conf

This PR adds a new how-to describing the steps to cross compile Erlang/OTP to Raspberry Pi 3 on macOS. It is an attempt to describe all the steps in one document, starting from building the cross compiler toolchain for ARM.

Add how-to for cross compilation to Raspberry Pi 3

---

erts/doc/src/erlang.xml
lib/kernel/doc/src/application.xml
lib/kernel/src/application_master.erl
system/doc/design_principles/applications.xml

I think it is not obvious for the reader of the code why do application masters become group leader of their applications.
You can kind of infer it if you read a lot, connect the dots, and allow yourself to conclude that this is the intention despite it does not seem motivated by I/O... but if you are told right away, you not only get the picture upfront, but also have official confimation rather than leaving yourself with a conjecture :).
The comment itself comes in part from my own research, and also from feedback from @ferd in the mailing list (thanks again!).

Explain why the AM becomes group leader

---

lib/hipe/rtl/hipe_rtl_lcm.erl
lib/hipe/test/basic_SUITE_data/basic_issues_hipe.erl

Some change in the BEAM compiler resulted in the creation of basic
blocks that differed from those previously created by the compiler.
As a result, the lazy code motion pass of RTL crashed when compiling
some of the new code.
Crashes were privately reported by @richcarl.

Fix a crash in HiPE's lazy code motion pass

---

lib/kernel/doc/src/config.xml
lib/kernel/src/application_controller.erl
lib/kernel/test/application_SUITE.erl

Included config files relative to sys.config dir
Change the way included config files are searched in sys.config.
Search first relative to sys.config directory, then relative
to current working directory, for backward compatibility.
This permit same result when using a sys.config file in a release
or starting manually a node with -config.
Credit to Siri Hansen for test case.

 Included config files relative to sys.config directory

---

lib/stdlib/src/uri_string.erl
lib/stdlib/test/uri_string_SUITE.erl

I ran into this while looking to see what parts of elli (https://github.com/elli-lib/elli) could now be replaced with calls to OTP-21 modules and discovered `uri_string`'s query string support doesn't allow for keys without values.

uri_string: support key without value in query string

---

lib/compiler/src/beam_jump.erl

This is an alternative to #1832.
The optimisation relies on special-casing the common pattern of
"renaming" a label by direct jump to another label. The change makes
beam_jump recognise couple more opportunities for optimisation.
The optimisation additionally avoids superfluous list concatenations by
only flattening the accumulator at the very end.

Optimise beam_jump

---

lib/compiler/src/erl_bifs.erl
lib/compiler/src/sys_core_fold.erl
lib/compiler/test/core_fold_SUITE.erl

This can often appear in code after inlining some higher-order
functions.
* mark is_function/2 as pure
* track function types in sys_core_fold
* use those types to eval is_function/1,2 at compile-time when possible

Fold is_function/1,2 during compilation

---

erts/doc/src/erlang.xml

Minor documentation issue I noticed when studying up.

Add missing bracket to erlang:spawn_opt/4 docs priority tuple option

---

system/doc/design_principles/statem.xml

* consistently use var name `Button` instead of `Digit`
* remove unnecessary calls to `do_lock` and `do_unlock`
* fix compile and logic errors

fix some errors in code samples for gen_statem behaviour

---

lib/compiler/src/beam_type.erl
lib/compiler/test/beam_type_SUITE.erl

beam_type assumed that the operand for the bs_context_to_binary
instruction must be a binary. That is not correct;
bs_context_to_binary accepts anything. Based on the incorrect
assumption, beam_type would remove other test instructions.
The bug was introduced in eee8655788d2, which was supposed
to be just a refactoring commit.
https://bugs.erlang.org/browse/ERL-655

beam_type: Fix unsafe optimization

---

lib/compiler/src/beam_validator.erl
lib/compiler/test/map_SUITE.erl

Code such as that the following:
Val = map_get(a, Map),
Map#{a:=z}   %Could be any map update
would incorrectly cause an internal consistency check failure:
Instruction: {put_map_exact,{f,0},{x,0},{x,0},1,{list,[{atom,a},{atom,z}]}}
Error:       {bad_type,{needed,map},{actual,term}}:
Update beam_validator so that it understands that the second
argument for `map_get/2` is a map.

Fix internal compiler error for map_get/2

---

lib/inets/src/http_client/httpc_response.erl

According to the code in httpc.erl, [the pquery parameter in the
`#request` record should start with a question mark](https://github.com/erlang/otp/blob/bc22321f10c1ad71fb7e28275a8e6ed26a34d4ab/lib/inets/src/http_client/httpc.erl#L545-L552). However, when
a server returned a 403 response, the Location header was parsed
and the question mark was not added to the beginning of the query
string. This ultimately causes the redirect to fail, as instead of
redirecting to "/path?query", httpc redirected to "/pathquery".
Note: this PR copies the query string code from httpc.erl to
httpc_response.erl. Maybe we should move those to a separate
module but I am not familiar enough with the codebase to say
if this is desirable OR even if we have such a place. Feedback
is welcome.

Include question mark in query string on redirect

---

lib/inets/src/http_client/httpc_response.erl
lib/inets/test/httpc_SUITE.erl

When handling 301 redirects from http -> https on Erlang 21.0.1, the
following error is encountered:
```
8> Options = [].
9> httpc:request(head, {"http://rhye.org", []}, Options, []).
{error,{shutdown,{{error,{badmatch,443}},
[{httpc_response,resolve_uri,7,
[{file,"/usr/local/lib/erlang/lib/inets-7.0/src/http_client/httpc_response.erl"},
{line,431}]},
{httpc_response,redirect,2,
[{file,"/usr/local/lib/erlang/lib/inets-7.0/src/http_client/httpc_response.erl"},
{line,396}]},
{httpc_handler,handle_response,1,
[{file,"httpc_handler.erl"},{line,1052}]},
{httpc_handler,handle_info,2,
[{file,"httpc_handler.erl"},{line,283}]},
{gen_server,try_dispatch,4,
[{file,"gen_server.erl"},{line,637}]},
{gen_server,handle_msg,6,
[{file,"gen_server.erl"},{line,711}]},
{proc_lib,init_p_do_apply,3, …
```

httpc 301 redirect: Do not assert scheme ports are equal

---

lib/ssl/doc/src/ssl.xml
lib/ssl/src/dtls_connection.erl
lib/ssl/src/ssl_connection.erl
lib/ssl/src/tls_connection.erl
lib/ssl/test/ssl_basic_SUITE.erl

When doing ssl:controlling_process on a ssl socket that has not
performed the TLS/DTLS handshake that call will succeed even though
the documentation stated otherwise. However if some other ssl option
was incorrect the call would hang. Now {error, closed} will be
returned in the latter case, which is logical independent on if it
should succeed or not in the former case. The former case will continue
to succeed, as it is not dependent of the TLS/DTLS connection being
established, and the documentation is altered slightly to not
explicitly disallow it. If the TLS/DTLS connection later fails and
the socket mode is active, the new controlling process will be
notified as expected.

ssl: Improve error handling

---

lib/kernel/doc/src/net_kernel.xml
lib/kernel/src/net_kernel.erl
lib/kernel/test/erl_distribution_SUITE.erl

to be no-op and return true
as it always has before OTP-21.0.
https://bugs.erlang.org/browse/ERL-643

Fix net_kernel:connect_node/1 to local node

---

make/make_emakefile.in

`asdf` and similar tools do not play well when an absolute path to a shim is used in make_emakefile. 
Without `/usr/bin/env` preprended the following behavior is encountered:
```shell
gmake[2]: Entering directory '/Users/starbelly/devel/erlang/otp/lib/crypto/test'
/Users/starbelly/devel/erlang/otp/make/make_emakefile +debug_info +nowarn_export_all -o. \
blowfish_SUITE crypto_SUITE engine_SUITE > Emakefile
/Users/starbelly/devel/erlang/otp/make/make_emakefile: line 4: use: command not found
/Users/starbelly/devel/erlang/otp/make/make_emakefile: line 6: my: command not found
/Users/starbelly/devel/erlang/otp/make/make_emakefile: line 7: my: command not found
/Users/starbelly/devel/erlang/otp/make/make_emakefile: line 8: my: command not found …
```

Preprend PERL with /usr/bin/env

---

erts/doc/src/erlang.xml
erts/emulator/beam/beam_load.c
erts/emulator/beam/break.c
erts/emulator/beam/erl_init.c
erts/emulator/beam/erl_process_dump.c
erts/emulator/test/code_SUITE.erl
erts/emulator/test/code_SUITE_data/literals.erl
erts/emulator/test/fun_SUITE.erl
lib/stdlib/test/lists_SUITE.erl

This intorduces a similar optimisation for normal funs
to what was introduced for external funs in #1725.
It is possible to allocate the fun as a literal, if it does not capture
the environemt (i.e. it does not close over any variables).
Unfortunately it's not possible to do this in the compiler due to
problems with representation of such functions in the `.beam` files.
Fortunately, we can do this in the loader.
Simple evaluation shows that functions that don't capture the
enviornment consistute over 60% of all funs in the source code of
Erlang/OTP itself.
The only downside is that we lose a meningful value in the `pid` field
of the fun. The goal of this field, beyond debugging, was to be
able to identify the original node of a function. To be able to still do
this, the functions that are …

Optimise creation of anonymous functions

---

lib/compiler/src/v3_core.erl
lib/compiler/test/bs_bincomp_SUITE.erl

Code like the following would crash the compiler, as it generated illegal code to determine the size of the produced binary.
```erlang
test(Binary) ->
<< <<X>> || <<S, X:S>> <= Binary >>.
```
https://bugs.erlang.org/browse/ERL-665

Fix a crash when compiling variable-sized binary comprehensions

---

lib/mnesia/src/mnesia.erl

I have this code: 
`{ok, _} = mnesia:change_config(extra_db_nodes, [Node])`
The dialyzer in OTP 21 started giving the next error:
`The pattern {'ok', _} can never match the type {'error',_}`
Based on the code it seems dialyzer is right and typespec is wrong

fix return type of mnesia:change_config

---

lib/dialyzer/test/small_SUITE_data/results/maps_sum
lib/stdlib/doc/src/maps.xml
lib/stdlib/src/maps.erl

* improve performance primarily by using direct pattern matching instead of `maps:find/2`;
* refine types in hopes to improve dialyzer analysis for code using maps.

Refactor maps.erl

---

erts/emulator/sys/win32/erl_poll.c

This bug was introduced in 988f5f5e8061ce2. The aux_thread needs to be poked as it is the thread that handles all break actions.
Reported in http://erlang.org/pipermail/erlang-questions/2018-July/095902.html and https://bugs.erlang.org/browse/ERL-672

erts: Fix bug where break would not trigger on windows

---

erts/emulator/beam/erl_alloc.c

ErtsAllocatorState_t instances need to be at least 8-byte aligned, but the code doesn't ensure that.  GCC hides the issue by over-aligning global variables, but Clang does not do that, causing alignment errors in 32-bit builds.  Fixed by adding an alignment directive to the type definition.
Although the alignment check only requires 8-byte alignment, the type definition appears to want cache line alignment, so I used that.
See ERL-677 for background.

erl_alloc: align ErtsAllocatorState_t

---

erts/emulator/drivers/common/inet_drv.c
lib/kernel/doc/src/inet.xml
lib/kernel/test/gen_udp_SUITE.erl

This PR fixed the performance issues found in the erlang-questions discussion here: http://erlang.org/pipermail/erlang-questions/2018-May/095494.html
The PR does two things:
* Fixes a performance bug when the inet UDP implementation gets EAGAIN from recvmsg
* Limits the max user-space buffer size of UDP to the theoretical max MTU

Fix inet driver realloc bug

---

erts/emulator/beam/beam_bif_load.c
erts/emulator/beam/beam_debug.c
erts/emulator/beam/bif.c
erts/emulator/beam/dist.c
erts/emulator/beam/erl_db.c
erts/emulator/beam/erl_message.c
erts/emulator/beam/erl_message.h
erts/emulator/beam/erl_nif.c
erts/emulator/beam/erl_proc_sig_queue.c
erts/emulator/beam/erl_process.c
erts/emulator/beam/io.c
erts/emulator/sys/common/erl_check_io.c
erts/emulator/test/nif_SUITE.erl
lib/kernel/test/seq_trace_SUITE.erl

A lot of erts internal messages used behind APIs to create non-blocking calls, e.g. port_command, would cause the seq_trace token to be cleared from the caller when it should not. This commit fixes that and adds asserts that makes sure that all messages sent have to correct token set.
Fixes: https://bugs.erlang.org/browse/ERL-602

Fix seq_trace to not clear token for system messages

---

lib/tools/priv/styles.css
lib/tools/src/Makefile
lib/tools/src/cover.erl

The idea behind this PR is to improve the current HTML page produced by the `cover` tool, here is an example of the result:

Improve Cover HTML page

---

lib/kernel/doc/src/kernel_app.xml

The doc says the default kernel logger_level is [info](https://github.com/erlang/otp/blob/OTP-21.0.3/lib/kernel/doc/src/kernel_app.xml#L195), it should be [notice](https://github.com/erlang/otp/blob/OTP-21.0.3/lib/kernel/src/kernel.app.src#L143).
```
% erl
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Eshell V10.0.3  (abort with ^G)
1> application:get_env(kernel,logger_level).
{ok,notice}
```
Also the doc says the logger_level can include [all|none](https://github.com/erlang/otp/blob/OTP-21.0.3/lib/kernel/doc/src/kernel_app.xml#L191), however it crashes the beam now.
```
%  erl -kernel logger_level all
2018-07-15 09:40:22.934138 Invalid logger config: ~p
{logger_level,all}
2018-07-15 09:40:22.934813 std_info …
```

Fix kernel_app doc logger_level defaults

---

lib/common_test/doc/src/ct.xml

Even when `ct:sleep/1` accepts `Millisecs` as floats, `ct:timetrap/1` does not.
If you try to use it in a test, you get the following error:
```erlang
{invalid_time_format,0.1}
```
This PR replaces #1868.

Update documentation for ct:timetrap/1

---

lib/compiler/src/sys_core_fold.erl

This allows taking advantage of further optimisations, like the
raw_raise instruction for code that can't upgrade (yet) to the
new stacktrace syntax for compatibility reasons.
The rewrite is only done when it is safe - when the get_stacktrace
call is the very first thing the handler does.

Rewrite erlang:get_stacktrace calls to primop when safe

---

system/doc/reference_manual/expressions.xml

As explained by @psyeugenic on Slack:
> empty list `[]` is regarded as a separate type from `list()`, `[]` < `list()`
> i.e. nil is `[]`

Add clarification on nil type

---

lib/compiler/src/sys_core_fold.erl
lib/compiler/test/core_SUITE.erl
lib/compiler/test/core_SUITE_data/fun_letrec_effect.core
lib/compiler/test/core_fold_SUITE.erl

When an expression is only used for its side effects, we try to
remove everything that doesn't tie into a side-effect, but we
went a bit too far when we applied the optimization to funs
defined in such a context. Consider the following:
do letrec 'f'/0 = fun () -> ... whatever ...
in call 'side':'effect'(apply 'f'/0())
'ok'
When f/0 is optimized under the assumption that its return value
is unused, side:effect/1 will be fed the result of the last
side-effecting expression in f/0 instead of its actual result.
https://bugs.erlang.org/browse/ERL-658
Co-authored-by: Björn Gustavsson <bjorn@erlang.org>

Fix side-effect optimization when compiling from Core Erlang

---

erts/emulator/beam/utils.c
erts/emulator/test/ref_SUITE.erl

This tests & fixes the ref ordering described in ERL-690
#Ref ordering is broken in all versions since at least R13B03 (the earliest in github). It does work in R12B03.
The comparison takes the difference of two Uint32 and casts it to Sint32 which is the wrong thing to do. For example, 2200000000 - 1 is positive, but sadly (Sint32)(22000000000-1) is negative.
The scary thing here is that it can make terms "invisible" in ets or Mnesia ram_copies or disc_copies tables.
`
W2s = [610350147,899574699,2994196869,686384822,2397690439, 923302211],
ExtRefBase = <<131,114,0,3,100,0,3,110,64,98,3>>,
ExtRefs = [<<ExtRefBase/binary, 1:32, W2:32, 0:32>> || W2 <- W2s],
Refs = [binary_to_term(Bin) || Bin <- ExtRefs],
Ets = ets:new(refbug, [ordered_set]),
ets:insert(Ets, [{Ref,Ref} || Ref <- Refs]),
0 = …

Ref ordering fix (ERL-690)

---

system/doc/reference_manual/expressions.xml

Follow up of https://github.com/erlang/otp/pull/1909

Document how utf8 atoms are ordered

---

HOWTO/INSTALL.md

Since OTP-20.0, the gs application has been removed.
Please refer to OTP-13703 in the following link
http://erlang.org/download/otp_src_20.0-rc1.readme for further info.

No need X Windows' headers and libraries to build Erlang since v20.0

---

lib/common_test/src/ct_release_test.erl
lib/common_test/src/ct_util.erl
lib/common_test/src/cth_log_redirect.erl

This PR fixes most of the unmatched return Dialyzer warnings in `common_test`.
The only one remaining is:
<pre>
ct_release_test.erl:531: Expression produces a value of type 'ok' | {'error',_} | {'ok',[{string(),binary()}]}, but this value is unmatched
</pre>
that somebody with more familiarity with the code should handle.

Fix some unmatched_return warnings

---

lib/mnesia/src/mnesia.erl
lib/mnesia/test/mnesia_isolation_test.erl

Fix a bug, when delete_object was deleting the record if it was written
in the same transaction even if it was written to a different value.
To verify:
```erlang
%% Create a set table
mnesia:create_table(foo, []).
%% Write and delete_object in transaction
mnesia:transaction(fun() ->
mnesia:write({foo, bar, one}),
mnesia:delete_object({foo, bar, not_one})
end).
{atomic, [{foo, bar, one}]} = mnesia:transaction(fun() -> mnesia:read(foo, bar) end).
```
Added a section to isolation tests to check for non-matching delete_object
requests.

Fix delete_object and write convergence in transaction.

---

lib/compiler/src/genop.tab

remove_message just remove messages without writing to any register.
Compiler is already generating code like:
{get_tuple_element,{x,0},1,{x,0}}.
remove_message.
{jump,{f,6}}
That clearly uses x0 for other purposes.

remove_message does not store any pointer to x0

---

erts/emulator/sys/unix/sys_drivers.c

Fixes: https://bugs.erlang.org/browse/ERL-692

erts: Delete fd from poll-set when closing fd_driver port

---

lib/compiler/src/beam_utils.erl
lib/compiler/test/receive_SUITE.erl

The compiler would crash when compiling a function with two
receive statements.
https://bugs.erlang.org/browse/ERL-703

Fix compiler crash when compiling double receives

---

make/emd2exml.in

DTRACE.xml and SYSTEMTRAP.xml set encoding to utf8 instead of utf-8
and make xmerl_scan:file/1,2 fail parsing them
(cherry picked from commit faded6e1cdceb049d2d9bc995b6c981d58709315)

fix generated encoding for xml files generated with emd2exml

---

erts/emulator/beam/erl_bif_binary.c
lib/stdlib/test/stdlib.spec
lib/stdlib/test/stdlib_bench_SUITE.erl

The idea is to use `memchr` on the first lookup for `binary:match/2` and also after every match on `binary:matches/2`.
This speeds up binary matching and binary splitting by 4x in some cases and by 70x in other scenarios (when the last character in the needle does not occur in the subject).
The reason to use memchr is that it is highly specialized in most modern operating systems, often implemented in assembly and using SIMD instructions.
The implementation uses the reduction count to figure out how many bytes should be read with memchr.
Huge thanks to @k0kubun to pointing me towards SIMD and memchr. And thanks to @citizen428 for the pairing.
PS: I know the OTP team is busy this week so feel free to let this sit for a while. :)

Optimize binary match from 10% up to 70x

---

lib/tools/emacs/erlang.el

These allow for the alignment of maps and records with the Emacs `align` command.
I think this may be a better, more 'emacsy' way of doing things than this:
https://github.com/erlang/otp/pull/1707

Add Erlang alignment regexps

---

erts/doc/src/time_correction.xml

you can see it here: http://erlang.org/doc/apps/erts/time_correction.html#support-of-both-new-and-old-otp-releases

erts/time_correction.xml: remove extra closing parenthesis

---

erts/emulator/beam/bif.c
erts/emulator/beam/dist.c
erts/emulator/beam/dist.h

There is a check for dist message size. If it exceeds INT_MAX, BEAM exits (sigabrt). 
While it could've been a case of absurdly large message 10 years ago, nowadays it's quite possible to have a data structure of this size. However it is questionable if the message should be sent or not. My suggestion would be to reject sending these messages (but do not crash entire VM).
Fixes this:
https://bugs.erlang.org/browse/ERL-484

Prevent BEAM crash when message being sent via dist is larger than 2Gb

---

erts/emulator/beam/erl_bif_binary.c

The single byte lookups always rely on `memchr` and
never really use the good and bad shifts arrays.
My benchmarks show this makes compile_pattern roughly twice
faster for single bytes. It also uses 256 bytes less memory.
Another alternative approach would be to introduce a complete separate
structure that does the single byte implementation but I personally find the
current approach simpler.
Follow up to #1803, fully closes https://bugs.erlang.org/browse/ERL-374.

Do not allocate good and bad shifts for single byte lookups

---

system/doc/reference_manual/typespec.xml

I'm not sure about the language of "must evaluate to".
Maybe "is an expression which has positive integer value" or "is a positive integer or an expression evaluating to a positive integer value" is better or clearer?

Document allowed integer ops in types

---

lib/kernel/doc/src/logger_chapter.xml

The doc says the default kernel logger_level is info, it should be notice.
Please refer to commit 0d52b992c30eff8604e5a5363510fea38c712263 for more info.

Fix kernel_app doc logger_level default from info to notice

---

lib/compiler/src/v3_core.erl
lib/dialyzer/test/small_SUITE_data/results/left_assoc
lib/dialyzer/test/small_SUITE_data/src/left_assoc.erl

See also https://bugs.erlang.org/browse/ERL-680.
The right associative short circuit expressions 'andalso' and 'orelse'
are expanded by the Compiler (see v3_core) into 'case' expressions. If
parentheses are used to enforce left associativeness, variables are
introduced, and the time needed by Dialyzer increases exponentially.
Rather than trying to fix Dialyzer itself, v3_core now rewrites
repeated use of 'andalso' ('orelse') into right associative
expressions before creating the 'case' expressions.

dialyzer: Improve handling of complex guards

---

lib/stdlib/src/ms_transform.erl

It can also return errors and warnings.

Fix type spec of ms_transform:parse_trans/2

---

erts/emulator/sys/common/erl_sys_common_misc.c
erts/emulator/test/num_bif_SUITE.erl

Presently it's deleting 0's in the non-fractional part of the number in this edge case:
```erlang
1> float_to_list(10.0, [{decimals, 0}, compact]).
"1"
2> float_to_list(1000.0, [{decimals, 0}, compact]).
"1"
```

Fix bug in compact representation of float_to_list/2

---

lib/erl_interface/src/legacy/erl_marshal.c
lib/erl_interface/test/erl_ext_SUITE_data/ext_test.c

erl_compare_ext() eventually calls cmp_exe2() for compound terms, and that function doesn't consider the tail for lists.
This means erl_compare_ext() considers the external representation of these two terms to be equal:
```
[a|b]
[a|c]
```
But it gets worse! These terms are also considered equal:
```
{<<1,2,3>>, [901,902], 224}
{<<1,2,3>>, [901,902], 228}
```

Erl compare ext lists bug (ERL-705)

---

lib/ssl/src/ssl_api.hrl

This fixes [ERL-721](https://bugs.erlang.org/browse/ERL-721)
Dialyzer would complain when using the `key` option of `ssl_option()`, e.g. for `ssl:listen/2`
I'm not sure if this can be tested (with a unit test). I built it locally and tested with my own project that Dialyzer would no longer complain.

Fixed ssl_options typespec for key

---

lib/tools/emacs/erlang.el

erlang-mode crashes with the following error:
`Symbol’s value as variable is void: align-rules-list`
caused by #1728

erlang-mode: fix void variable align-rules-list error

---

lib/compiler/src/beam_ssa.erl
lib/compiler/src/beam_ssa_codegen.erl
lib/compiler/src/beam_ssa_dead.erl
lib/compiler/src/beam_ssa_opt.erl
lib/compiler/src/beam_ssa_pp.erl
lib/compiler/src/beam_ssa_pre_codegen.erl
lib/compiler/src/beam_ssa_recv.erl
lib/compiler/src/beam_ssa_type.erl

When we first set out to rewrite the assembly passes in SSA format we weren't sure whether we'd want to be able to add annotations to variables. To play it safe we used variable names everywhere instead of the whole `#b_var{}` record so it would be trivial to add the field later on, but at the cost of having to pack and unpack the name pretty often.
It turns out we didn't need these annotations in the end, so this PR cleans things up.

Clean up variable-related cruft in new SSA passes

---

lib/compiler/src/beam_validator.erl
lib/compiler/test/beam_validator_SUITE.erl

`hd/1` and friends only tracked types for their direct inputs, failing validation for legal code that used an aliased register.
https://bugs.erlang.org/browse/ERL-735

beam_validator: Use set_aliased_type in more operations

---

lib/compiler/src/beam_a.erl
lib/compiler/src/beam_block.erl
lib/compiler/src/beam_clean.erl
lib/compiler/src/beam_flatten.erl
lib/compiler/src/beam_ssa_codegen.erl
lib/compiler/src/beam_ssa_pre_codegen.erl
lib/compiler/src/beam_utils.erl
lib/compiler/src/beam_validator.erl

This pull request introduces several minor cleanups, bug fixes, and improvements in the compiler. See the individual commit messages for details.

Minor cleanups and bug fixes of the compiler

---

lib/compiler/src/beam_bsm.erl
lib/compiler/src/sys_core_bsm.erl
lib/compiler/test/bs_match_SUITE.erl

2e40d8d1c51a attempted fix a bug in binary matching, but it only
fixed the bug for the minimized test case.
This commit removes the previous fix and fixes the bug in a more
effective way. See the comments in the new code in `sys_core_bsm`
for an explanation.
This commit restores the optimizations in string.erl and dets_v9.erl
that the previous fix disabled.
I have not found any code where this commit will disable optimizations
when they are actually safe. There are some changes to the code
in ssl_cipher.erl in that some bs_start_match2 instruction did not
reuse the binary register for the match context, but the delayed
sub binary optimizations was never applied to the code in the first
place.
https://bugs.erlang.org/browse/ERL-689

Fix rare bug in binary matching (again)

---

lib/compiler/doc/src/compile.xml
lib/compiler/src/compile.erl
lib/dialyzer/src/dialyzer_utils.erl

By default, all code is compiled in a separate process
which is terminated at the end of compilation. However,
some tools, like Dialyzer or compilers for other BEAM languages,
may already manage their own worker processes and spawning
an extra process may slow the compilation down.
In such scenarios, you can pass this option to stop the
compiler from spawning an additional process.
This is particularly important for compilers emitting core code
as the annotation in core may end-up allocating a lot of memory
when copied to a new process.
This generalizes commit 657760e18087b0cdbaecc5e96e46f6f66bc9497a.
Thanks to @bjorng for helping me find the root cause for the
higher memory usage and slower compilation times.

Introduce the no_spawn_compiler_process option

---

erts/doc/src/match_spec.xml
lib/stdlib/src/ms_transform.erl

It is already allowed in match-specs.

Document bit_size in match-specs and allow in fun2ms

---

lib/compiler/doc/src/compile.xml
lib/compiler/src/compile.erl
lib/compiler/test/compile_SUITE.erl
lib/stdlib/doc/src/epp.xml
lib/stdlib/src/epp.erl
lib/stdlib/test/epp_SUITE.erl
lib/stdlib/test/epp_SUITE_data/source_name.erl

When pre-processing a file, `epp` will automatically insert `-file()` attributes to let the compiler know what file an expression belongs to. This information is then used in error reports and stack traces.
The current behavior is that the pre-processor will always use the path as passed to `erlc` for these attributes, so the only way to prevent leaking information about the build environment is to invoke `erlc` in the folder the source file resides in.
This PR aims to remedy that. When the `+source` flag is given the pre-processor will use that instead of the actual file path for these attributes. It also fixes a related bug in the `+deterministic` flag.
https://bugs.erlang.org/browse/ERL-706

Allow changing source paths presented in stack traces

---

erts/emulator/test/smoke_test_SUITE.erl
lib/common_test/src/ct.erl
lib/common_test/test/ct_config_SUITE.erl
lib/common_test/test_server/ts_install.erl
lib/observer/src/cdv_wx.erl
lib/xmerl/src/xmerl_sax_parser_base.erlsrc

Hello!
Let's use os:getenv/2 even more instead of the following code:
```erlang
case os:getenv(SomeEnv) of
false -> DefaultVal;
Val -> Val
end.
```

Use os:getenv/2 where possible

---

lib/stdlib/doc/src/rand.xml
lib/stdlib/src/rand.erl
lib/stdlib/test/rand_SUITE.erl

The field of Pseudo Random Generators is advancing...
After criticism about low randomness for the low bits, the 2018 paper [Scrambled Linear Pseudorandom Number Generators](http://vigna.di.unimi.it/ftp/papers/ScrambledLinear.pdf) by the people that have created the algorithms already in the `rand` module, introduces a new scrambling function named _StarStar_ (\*\*). This scrambler removes the artifacts in the low bits that are inherent in the Xorshift, Xoroshiro and Xoshiro generators.
This pull request suggests combining the _StarStar_ scrambler (mult 5, rotl 7, mult 9) with the previous default algorithm that did not require 58-bit rotation to get Xorshift116**/`exsss`.
The scrambler slows down the fast generator somewhat so the combination is slightly slower (about 10%) than the …

Xorshift116** as new default 'rand' algorithm

---

lib/compiler/src/beam_utils.erl
lib/compiler/test/bs_match_SUITE.erl

The `bs_start_match2` instruction wasn't handled in `beam_utils:anno_defs/1`, breaking optimizations that relied on said helper function.
https://bugs.erlang.org/browse/ERL-753

beam_utils: Handle bs_start_match2 in anno_defs

---

lib/eldap/test/make_certs.erl
lib/ssl/doc/src/ssl.xml
lib/ssl/src/dtls_handshake.erl
lib/ssl/src/ssl.erl
lib/ssl/src/ssl_connection.erl
lib/ssl/src/ssl_handshake.erl
lib/ssl/src/tls_handshake.erl
lib/ssl/test/make_certs.erl
lib/ssl/test/ssl_basic_SUITE.erl
lib/ssl/test/ssl_handshake_SUITE.erl

Implement handling of the signature algorithms extension described by RFC 8446. This pull request updates the behavior of legacy TLS versions to align them with RFC 8446 (TLS 1.3) and RFC 5246 (TLS 1.2).

Implement Signature Algorithms (TLS 1.3)

---

erts/emulator/zlib/zlib.mk

When building Erlang on a system that uses the Musl C library, it's
possible to get the following error:
In file included from zlib/adler32.c:11:0:
zlib/zutil.h:172:39: error: "_LFS64_LARGEFILE" is not defined [-Werror=undef]
(!defined(_LARGEFILE64_SOURCE) || _LFS64_LARGEFILE-0 == 0)
^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
On the same systems, zlib is built without `-Werror=undef` so do the
same when building it with Erlang.
Signed-off-by: Frank Hunleth <fhunleth@troodon-software.com>

Allow undefined macros when building zlib

---

lib/kernel/src/net_kernel.erl

Passing -sname '' or -sname '@bar' to erl would result in an obscure
error message "Protocol 'inet_tcp': register/listen error: epmd_close"
because the check for valid names did not disallow the empty string.

Do not allow an empty string as node name

---

lib/kernel/doc/src/logger.xml
lib/kernel/doc/src/logger_chapter.xml
lib/kernel/doc/src/logger_disk_log_h.xml
lib/kernel/doc/src/logger_std_h.xml
lib/kernel/src/logger.erl
lib/kernel/src/logger_disk_log_h.erl
lib/kernel/src/logger_h_common.erl
lib/kernel/src/logger_server.erl
lib/kernel/src/logger_std_h.erl
lib/kernel/test/logger_SUITE.erl
lib/kernel/test/logger_disk_log_h_SUITE.erl
lib/kernel/test/logger_std_h_SUITE.erl

The existing functions logger:set_handler_config/2 and logger:update_handler_config/2 are both used for changing the configuration for a handler. The difference between them is in how they affect configuration parameters that are not specified in the input data:
* set_handler_config/2 resets unspecified parameters to their default values
* update_handler_config/2 leaves unspecified parameters unchanged.
This is all well, for all parameters except the 'config' key, which points out data that is specific to the handler implementation. For example, for the built-in handler logger_std_h, the config key is associated with a map that in turn can contain up to around 12 different associations. Logger itself has no knowledge of this data structure, and therefore calls the handler callback …

Relay set/update indicator to handler callback changing_config

---

lib/compiler/src/beam_jump.erl
lib/compiler/test/beam_jump_SUITE.erl

The `beam_jump` pass could eliminate `move` instructions when it was
not safe to do so. See the new test case `unsafe_move_elimination/1`
for an example.
Reported-by: Michał Muskała

Make the move elimination optimization in beam_jump safe

---

lib/hipe/main/hipe.erl
lib/stdlib/doc/src/beam_lib.xml
lib/stdlib/src/beam_lib.erl

The type `beam()` in the `beam_lib` module is confusing:
-type beam() :: module() | file:filename() | binary().
It says that the module name can be used to identify the BEAM module
to be accessed, but passing in the module name only works if the BEAM
file is located in the current working directory because the module
is not searched for in the code path.
The reason that is allowed to pass in the module name as an atom is
for backward compatibility. A long time ago, atoms instead of strings
were used as filenames. For that reason, `filename` and `file` still
accept atoms as filenames (although the practice is frown
upon). `beam_lib` accepts an atom as the filename for the same reason.
To make it less confusing, change the type to:
-type beam() :: file:filename() | binary() | atom().
Also, …

beam_lib: Clarify the beam() type in code and documentation

---

erts/emulator/beam/bif.c
erts/emulator/beam/erl_gc.c
erts/emulator/test/code_SUITE.erl

When a module has been purged from memory, any literals belonging
to that module will be copied to all processes that hold references
to them.
The max heap size limit would be ignored in the garbage collection
initiated when copying literals to a process. If the max heap size
was exceeded, the process would typically be terminated in the
following garbage collection.
Since the process would be killed anyway later, kill the process
before copying a literal that would make it exceed its max heap
size.
While at it, also fix a potential bug in `erlang:garbage_collect/0`.
If it was found that the max heap sized had been exceeded while
executing `erlang:garbage_collect/0`, the process would enter a
kind of zombie state instead of being properly terminated.

Honor the max heap size when copying literals after purging

---

lib/observer/src/crashdump_viewer.erl
lib/observer/test/crashdump_helper.erl

Literal maps with complex keys such as:
#{"one"=>1,"two"=>2,"three"=>3,"four"=>4}.
would produce a crash dump that `crashdump_viewer` was unable
to read.
https://bugs.erlang.org/browse/ERL-722

Eliminate crash in crashdump_viewer reading some literal maps

---

lib/hipe/main/hipe.erl
lib/hipe/test/hipe_testsuite_driver.erl
lib/kernel/test/code_SUITE.erl

The previous check whether ErLLVM could be enabled and/or tested simply
checked whether a suitable version of the LLVM tool chain was present
in the path. Obviously this is not enough: there should also be a check
that we are running in an architecture on which the ErLLVM compiler
has been ported. Fix the function that provides this functionality and
also rename it in order to more appropriately describe what it does.
In principle, this change introduces a backwards incompatibility as the
function is one of those exported by the `hipe' module, but this
function was not documented and the chances that it has been used
somewhere else that the test suite are pretty low (if not zero).

HiPE: Fix check for when ErLLVM is available

---

.gitignore
lib/hipe/llvm/hipe_llvm_main.erl

Upstream this patch from FreeBSD Ports:
https://svnweb.freebsd.org/ports/head/lang/erlang-runtime21/files/patch-lib_hipe_llvm_hipe__llvm__main.erl?revision=473434&view=markup

hipe_llvm_main: fix tmpfs dir on FreeBSD

---

lib/kernel/src/inet_tcp_dist.erl
lib/ssl/src/inet_tls_dist.erl

I came across a bug that happened because of a mis-match in the function signature expected when implementing a custom `EpmdModule`.
If the optional function `address_please` isn't implemented, it defaults to `inet:getaddr/3`. The bug arises when that function is called, since it's 3rd argument is of the wrong type. It is expecting a timeout value but gets an `AddressFamily`
This causes a crash that looks like:
```erlang
{
:badarg,
[
{:erlang, :start_timer, [:inet, #PID<0.17713.363>, :inet], []},
{:inet, :start_timer, 1, [file: 'inet.erl', line: 1763]},
{:inet, :getaddr, 3, [file: 'inet.erl', line: 591]},
{:inet_tcp_dist, :do_setup, 7, [file: 'inet_tcp_dist.erl', line: 289]}
]
}
```
The fix here is to just call the built-in `erl_epmd` of the function which just calls the 2-arity version …

Fix the default implementation of address_please

---

erts/etc/unix/run_erl.c

The check in place to compile for BSD and macOS can be extended to let Erlang also compile successfully on Solaris (11.4).

Fix run_erl.c so it compiles on Solaris

---

lib/hipe/main/hipe.erl

There was a lot of confusion between file vs. module names in the
function specification of the hipe module (as also discovered by #1992)
and this PR cleans up and fixes them.

hipe: Cleanup and fix specs of the hipe module

---

lib/stdlib/doc/src/gen_event.xml

It returns `ok`, instead of `noreply`.

Fix docs on gen_event optional callback

---

lib/ssh/doc/src/ssh_sftp.xml

```erlang
Position = integer()
```
Parameter doesn't exist in `read/3,4`

fix extra parameter in <type>

---

erts/emulator/beam/atom.c
erts/emulator/beam/erl_alloc.types
erts/emulator/beam/erl_bif_lists.c
erts/emulator/beam/erl_utils.h
erts/emulator/beam/external.c
erts/emulator/beam/utils.c
lib/stdlib/doc/src/lists.xml
lib/stdlib/test/lists_SUITE.erl
system/doc/efficiency_guide/commoncaveats.xml
system/doc/efficiency_guide/retired_myths.xml

@kvakvs had to pause his work on #1993 so this PR takes over where he left off. I've refactored it to make state handling easier to follow, and started using a tree instead of an array for the removal set, decreasing run-time complexity from `n*n` to `n*log(n)`.
Other than that it's pretty much the same, and it should still be relatively easy to backport.

Optimize list subtraction (A -- B) and make it yield on large inputs

---

lib/compiler/src/beam_except.erl
lib/compiler/test/beam_except_SUITE.erl

The `beam_except` pass replaces some calls to `erlang:error/1` or
`erlang:error/2` with specialized instructions in order to reduce the
size of the BEAM code.
In functions that do binary matching, `beam_except` would fail to
translate the instructions that generate a `function_clause`
exception. Here is an example:
bsum(<<H:16,T/binary>>, Acc) ->
bsum(T, Acc+H);
bsum(<<>>, Acc) ->
Acc.
The BEAM code that generates the `function_clause` exception looks
like this:
{label,4}.
{test_heap,2,3}.
{put_list,{x,1},nil,{x,1}}.
%% The following two instructions prevents the translation.
{bs_set_position,{x,2},{x,0}}.
{bs_get_tail,{x,2},{x,0},3}.
{test_heap,2,2}.
{put_list,{x,0},{x,1},{x,1}}.
{move,{atom,function_clause},{x,0}}.
{line,...}.
{call_ext,2,{extfunc,erlang,error,2}}.
Make the translation …

beam_except: Generalize translation to func_info instructions

---

lib/compiler/src/beam_jump.erl
lib/compiler/test/beam_jump_SUITE.erl

`beam_jump` could remove a `put_tuple` instruction when the
tuple would not be used, but it would leave the following
`put` instructions. Make sure they are removed.
https://bugs.erlang.org/browse/ERL-759

Fix bug when beam_jump removes put_tuple instructions

---

erts/epmd/src/epmd.c

-systemd option help is currently shown in "Interactive options" section.
The option is not interactive one.
Fixes: b7c95eabf601 ("Add systemd socket activation for epmd")
Signed-off-by: Matwey V. Kornilov <matwey.kornilov@gmail.com>

epmd: Move -systemd position in -help output

---

lib/compiler/src/beam_ssa_dead.erl
lib/compiler/src/beam_ssa_pre_codegen.erl
lib/compiler/src/beam_ssa_type.erl

@kostis noticed that the compiler on the `master` was much slower than the compiler in OTP 21 when compiling this module:
https://github.com/aggelgian/cuter/blob/master/src/cuter_binlib.erl
This pull request eliminates three bottlenecks in the compiler and reduces the compilation time from about three and half minutes down to about half a minute on my computer. See the individual commit messages for  details.

Speed up the compiler

---

lib/compiler/src/beam_utils.erl
lib/compiler/test/beam_utils_SUITE.erl

There could be an internal consistency failure when using `is_function/2`,
because an optimization did not take into account that `is_function/2` can fail.
https://bugs.erlang.org/browse/ERL-778

Fix internal consistency failure for is_function/2

---

lib/stdlib/src/erl_lint.erl
lib/stdlib/test/erl_lint_SUITE.erl

An external fun could inadvertently suppress warnings for
unused variables, such as in this example:
bug() ->
BugVar = foo(),
if true ->
fun m:f/1
end.
There would be no warning that `BugVar` was unused.
The bug was introduced in ff432e262e652, which was the commit
that extended external funs to allow variables.
https://bugs.erlang.org/browse/ERL-762

Fix inadvertently suppressed warning for unused variable

---

scripts/diffable

If Elixir is installed along the the Erlang/OTP repository, produce
diff-friendly output for the Elixir standard library.

scripts/diffable: Optionally compile the Elixir standard library

---

lib/reltool/src/reltool_utils.erl
lib/reltool/test/reltool_server_SUITE.erl

Without this patch reltool would also try to split strings like "C:\foo" into ["C","\foo"].

Make reltool correctly handle Windows 'ERL_LIBS'

---

erts/emulator/beam/erl_gc.c
lib/kernel/test/seq_trace_SUITE.erl

A copy has to be made of the message as there is a trace token. There was a bug where the actual
message was incorrectly modified even if it was a literal.

erts: Fix copy of literal msg during gc

---

lib/compiler/src/sys_core_fold.erl
lib/compiler/test/trycatch_SUITE.erl

The `sys_core_fold` pass of the compiler would optimize
away the building of the stacktrace in code such as:
try
...
catch
C:R:Stk ->
erlang:raise(C, {R,Stk}, Stk)
end
That optimization is unsafe and would cause a crash in a later compiler
pass.

Fix unsafe optimization of stack trace building

---

lib/compiler/src/beam_ssa_pre_codegen.erl
lib/compiler/test/beam_ssa_SUITE.erl

The following function:
is_two_tuple(Arg) ->
case is_tuple(Arg) of
false -> false;
true -> tuple_size(Arg) == 2
end.
would cause an internal consistency failure:
Instruction: {bif,tuple_size,{f,0},[{x,0}],{z,0}}
Error:       {invalid_store,{z,0},{integer,[]}}:

beam_ssa_pre_codegen: Fix an internal consistency failure

---

erts/configure.in
erts/emulator/beam/erl_afit_alloc.c
erts/emulator/beam/erl_alloc_util.c
erts/emulator/beam/erl_alloc_util.h
erts/emulator/beam/erl_ao_firstfit_alloc.c
erts/emulator/beam/erl_bestfit_alloc.c
erts/emulator/beam/erl_goodfit_alloc.c
erts/emulator/sys/common/erl_mmap.h
erts/emulator/sys/win32/sys.c

This PR lets the OS reclaim the physical memory associated with free blocks in pooled carriers, reducing the impact of long-lived awkward allocations. A small allocated block will still keep a huge carrier alive, but the unused parts of the carrier will now be available to the OS.
(This is based on #1946 by @kvakvs.)

Mark free blocks in pooled carriers as unused

---

configure.src

The parallel configure implemented in d4b4567 would rm -f the
SKIP-APPLICATIONS file before it was consumed at the end of the
configure script. This reverses the solution by instead first building
the list of skip applications in memory and only then writing them to
the SKIP-APPLICATIONS file.

Fix --without-APP config option

---

erts/emulator/beam/big.c
erts/emulator/test/big_SUITE.erl

The multiplication of two bignums is specially optimized when the two
operands have the same address, because squaring can be done more
efficiently than multiplication of two arbitrary integers.  That is,
expressions such as `I * I` will calculated by squaring the value of
`I`.
The optimized function for squaring would read one word beyond the
end of the bignum in the last iteration of a loop. The garbage
value would never be used. In almost all circumstances that would
be harmless. Only if the read word happened to fall on the start
of an unmapped page would the runtime crash. That is unlikely
to happen because most bignums are stored on a process heap, and
since the stack is located at the other end of the block that the
heap is located in, the word beyond the end of bignum is …

Fix reading beyond end of bignum in integer squaring

---

erts/emulator/beam/arith_instrs.tab
erts/emulator/beam/beam_debug.c
erts/emulator/beam/beam_emu.c
erts/emulator/beam/beam_load.c
erts/emulator/beam/bif.tab
erts/emulator/beam/bif_instrs.tab
erts/emulator/beam/erl_arith.c
erts/emulator/beam/erl_bif_binary.c
erts/emulator/beam/erl_bif_guard.c
erts/emulator/beam/erl_binary.h
erts/emulator/beam/erl_map.c
erts/emulator/beam/erl_vm.h
erts/emulator/beam/ops.tab
erts/emulator/utils/beam_makeops

This pull request simplifies the implementation of the "GC BIFs" so that they no longer need to do a garbage collection, removing duplicate code for all GC BIFs in the runtime system, as well as reducing the size of the loaded BEAM code by using shorter instructions calling those BIFs.
See the commit messages for more details.
This pull request intentionally does not update the compiler. Emitting `bif` instructions instead of `gc_bif` instructions does not seem improve the code quality. However, by adding some additional optimizations, it seems that some register shuffling code could be avoided by using plain `bif` instructions, but that will be subject of a future investigation and possible pull request.

Simplify implementation of GC BIFs

---

erts/emulator/beam/instrs.tab

Dispatching a function and return never use the next instruction.
It's unlikely for raw_raise to use the next instruction.

Add missing annotations in instrs.tab

---

erts/emulator/beam/erl_bif_atomics.c
erts/emulator/test/atomics_SUITE.erl

Due to comparison as a signed integer, when getting an unsigned atomic
in the range 2^63-1..2^64-1 (when the most significant bit was set), the
heap could get corrupted when the integer was retrieved: hsz would get
set to zero, but the code proceeded to build a bignum.
```erlang
% ./bin/erl
Erlang/OTP 21 [erts-10.2] [source-3825199794] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Eshell V10.2  (abort with ^G)
1> A = atomics:new(1,[{signed,false}]).
#Ref<0.2526256236.2769682438.210844>
2> atomics:info(A).
#{max => 18446744073709551615,memory => 48,min => 0,size => 1}
3> atomics:put(A,1,18446744073709551615).
ok
4> atomics:get(A,1).
{value,{value,{value,{value,{value,{value,{value,{value,{value,{value,{value,{value,{value,{value,{value,...},
[...]},
[{'A',...}]}, …
```

erts: Fix possible heap corruption getting atomics

---

lib/observer/src/cdv_html_wx.erl

Observer makes use of cdv_html_wx but does not start cdv_wx first which
made it crash when trying to send a message to cdv_wx. This fix makes
the send operation more defensive.
https://bugs.erlang.org/browse/ERL-810

Observer: fix crash bug when expanding term

---

lib/ssh/src/ssh_sftpd.erl

Some SFTP client's have been discover to claim one version of the
protocol and send messages in a different version.
In the spirit of Postel's law, we can for SSH_FXP_STAT, ignore the
differences in the protocol, as we are not doing anything with the flags
anyway.
I looked through the test cases and there where no tests for different versions of retrieve_attributes, so this change will just improve code coverage with the existing tests. Hope this is ok.

ERL-822 Fix sftpd interop for SSH_FXP_STAT

---

erts/emulator/beam/bif_instrs.tab
erts/emulator/beam/ops.tab

This allows bif1/2/3 to share the main part of the code.
The price is that we always need to copy all three temporary registers
when error handling in bodies, but that should be infrequent.
Additionally it makes it a bit harder to read the disasembly since now
the arguments to BIFs are in the reverse order.

Use microops for BIFs

---

lib/compiler/doc/src/compile.xml
lib/stdlib/src/erl_lint.erl
lib/stdlib/test/erl_lint_SUITE.erl

Before OTP 22, the option `{nowarn_deprecated_function,MFAs}` was only
recognized when given in the file with the attribute
`-compile()`. (The option `{nowarn_unused_function,FAs}`
was incorrectly documented to only work in a file, but it also
worked when given in the option list.) Starting from OTP 22, all
options that can be given in the file can also be given in the option
list.

Make all compiler options work in the option list

---

erts/doc/src/erl_nif.xml
erts/emulator/beam/erl_drv_nif.h
erts/emulator/beam/erl_message.c
erts/emulator/beam/erl_nif.c
erts/emulator/beam/erl_nif.h
erts/emulator/beam/erl_nif_api_funcs.h
erts/emulator/beam/global.h
erts/emulator/sys/common/erl_check_io.c
erts/emulator/sys/common/erl_check_io.h
erts/emulator/test/nif_SUITE.erl
erts/emulator/test/nif_SUITE_data/nif_SUITE.c

The existing NIF function `enif_select` sends messages on the predefined format
`{select, Obj, Ref, ready_input | ready_output}`.
This PR adds a way to instead supply your own custom message that will be sent unaltered when the subscribed event happens. This is done with two new API functions (macros):
`enif_select_read(env, event, obj, pid, msg, msg_env)`
`enif_select_write(env, event, obj, pid, msg, msg_env)`

Custom message format for enif_select

---

lib/stdlib/src/ms_transform.erl

Before this patch the following call resulted in the below error
```
1> dbg:fun2ms(fun(_) -> m:f() end).
Error: Unknown error code {122,m,f}
```
Now it is properly formatted as
```
1> dbg:fun2ms(fun(_) -> m:f() end).
Error: fun containing the remote function call 'm:f/0' (called in body) cannot be translated into match_spec
```
I couldn't find any tests for exact error codes and formatting in `ms_transform_SUITE`. Let me know if I should add one.

Fix remote-call error in ms_transform

---

lib/ssl/src/ssl_connection.erl

They produce crashes like the following occasionally:
``` erlang
** Reason for termination = error:{bad_return_from_state_function,
{stop,connection,
{state,client,
{#Ref<0.341079929.3670802433.158048>,
<0.446.0>},
gen_tcp,tls_connection,tcp,tcp_closed,
```
Not sure how to reproduce reliably to write a test.
I also changed the stop Reason to mirror what is done on other socket errors, instead of having a reason that will produce logs.

ssl: Fix two invalid gen_statem returns

---

erts/doc/src/atomics.xml
erts/doc/src/counters.xml

Since ETS is the main mutable storage for Erlang,
developers may expect atomics and counters to
behave similarly to ETS when it comes to process
ownership and clean-up, so I decided to clarify the
behaviour.

Document cleanup semantics for atomics and counters

---

lib/runtime_tools/examples/dist.systemtap
lib/runtime_tools/examples/driver1.systemtap
lib/runtime_tools/examples/function-calls.systemtap
lib/runtime_tools/examples/garbage-collection.systemtap
lib/runtime_tools/examples/memory1.systemtap
lib/runtime_tools/examples/messages.systemtap
lib/runtime_tools/examples/port1.systemtap
lib/runtime_tools/examples/process-scheduling.systemtap
lib/runtime_tools/examples/spawn-exit.systemtap
lib/runtime_tools/examples/user-probe-n.systemtap
lib/runtime_tools/examples/user-probe.systemtap

- Update all scripts to use the beam.smp emulator, since the non-SMP one
is gone
- Fix some scripts that had been copied directly from dtrace and were
invalid either for functions or for probe names
- Removed a driver__event probe check since it appears to not exist
I'm not aware of any tests for these, but I did a manual check for all of them,
aside from `lib/runtime_tools/examples/user-probe-n.systemtap` which I could
load without error, but have no idea how to trigger. Only `user-probe.systemtap`
appears to be triggerable through the `dyntrace` module, through the
`user_trace-i4s4` probe.

Update and fix systemtap trace example scripts

---

lib/stdlib/src/erl_parse.yrl

The error in the type was discovered during the development of https://github.com/josefs/Gradualizer .
Due to the lack of a type checker, I'm unable to provide a test case for the type. Dialyzer obviously didn't catch this one.

Correction of type abstract_expr -> abstract_expr() in erl_parse

---

lib/stdlib/src/erl_parse.yrl

- Add literal character to `erl_parse:abstract_type/0` type
This is allowed since 19.3 (commit 6d238032) and documented since commit
744fb920.
- Fix `erl_parse:af_fun_type()`
`af_function_type()` already contains the `{'type', anno(), 'fun', ...}`
tuple so it does not have to be wrapped again.
- Fix `erl_parse:af_constraint()`
Add missing list wrapper.

Fixes in erl_parse:abstract_type/0 type

---

lib/compiler/src/beam_type.erl
lib/compiler/test/beam_type_SUITE.erl

The compiler would crash when compiling code such as:
(A / B) band 16#ff
The type for the expression would be `none`, but `beam_type:verified_type/1`
did not handle `none`.
https://bugs.erlang.org/browse/ERL-829

beam_type: Eliminate compiler crash when arithmetic expression fails

---

lib/compiler/src/beam_validator.erl
lib/compiler/test/beam_validator_SUITE.erl

Needed because of the optimizations in 48f20bd589fa69.
https://bugs.erlang.org/browse/ERL-832

Make the beam_validator smarter (again)

---

lib/common_test/src/ct_config.erl

Variable Key is the input parameter and it will never match to the "Key" result of make_crypto_key/1 
In current case we'll always receive bad match when using encrypt_config_file and decrypt_config_file functions.

Fix encrypt_config_file and decrypt_config_file

---

erts/doc/src/erlang.xml
erts/preloaded/src/erlang.erl

If a process is executing native-compiled code, process_info(Pid,
current_function) may return the atom undefined instead of an MFA.

Document that current_function can be undefined

---

.gitignore
erts/emulator/test/exception_SUITE.erl
lib/compiler/src/Makefile
lib/compiler/src/beam_ssa_bsm.erl
lib/compiler/src/beam_ssa_codegen.erl
lib/compiler/src/beam_ssa_opt.erl
lib/compiler/src/beam_ssa_opt.hrl
lib/compiler/src/beam_ssa_pre_codegen.erl
lib/compiler/src/beam_ssa_type.erl
lib/compiler/src/beam_validator.erl
lib/compiler/src/compile.erl
lib/compiler/test/Makefile
lib/compiler/test/apply_SUITE.erl
lib/compiler/test/compile_SUITE.erl
lib/compiler/test/float_SUITE.erl
lib/compiler/test/receive_SUITE.erl
lib/compiler/test/test_lib.erl

The current type pass works on a per-function level and assumes that every argument and return value could be anything, which means they have to be type-checked before they're used. This is a bit inefficient as most functions always return something of the same type, and their argument types seldom differ.
This PR makes the type pass track the return and argument types of local functions, letting us eliminate many redundant type checks.
```erlang
example1() ->
%% We no longer check that this is a 2-tuple before extracting A & B
{A, B} = returns_2_tuple(), 
A + B.
returns_2_tuple() ->
{a:a(), b:b()}.
-record(a, {n=0}).
example2() ->
loop(lists:seq(1, 20), #a{}).
%% Record type is no longer checked on each iteration
loop([I | Is], #a{n=N}=St) ->
loop(Is, St#a{n=N+I});
loop([], St) ->
St. …
```

Apply type optimizations across local function calls

---

lib/compiler/src/beam_ssa_pre_codegen.erl

Consider this function and its corresponding BEAM code:
foo(Map, Key) ->
Val = case Map of
#{Key:=Val0} -> Val0;
_ -> default
end,
bar(1, 2, Val).
{label,2}.
{test,is_map,{f,3},[{x,0}]}.
{get_map_elements,{f,3},{x,0},{list,[{x,1},{x,0}]}}.
^^^^^
{jump,{f,4}}.
{label,3}.
{move,{atom,default},{x,0}}.
^^^^^
{label,4}.
{move,{integer,2},{x,1}}.
{move,{x,0},{x,2}}.
^^^^^
{move,{integer,1},{x,0}}.
{call_only,3,{f,6}}.
Note that the value of the variable `Val` will first be
placed in `{x,0}` and then moved to `{x,2}` where it needs
to be when calling the `bar/3` function.
The reason for the extra `move` instruction is that the
register allocator picks the lowest numbered available register
when choosing a register to put a variable in. In this case,
`{x,0}` will be chosen.
If we only could give …

Reduce redundant moves and register shuffling

---

lib/tools/priv/styles.css
lib/tools/src/cover.erl

Prior to #1807 , uncovered lines could be found by searching for " 0.." in the HTML page generated by cover:analyse_to_file/1,2. The pull request removed the two dots after the number of hits, which made it much harder to find the uncovered lines.
This PR introduces a sad face, :-( , instead of the single 0 character, which should make the search easier.
Other suggestions for the uncovered marker has been
* "---" (discarded because many modules contain comment lines consisting of dashes)
* "-0-" 
* ".0."
* "uncov"
* "uncovered"
I did go for the sad face because, next after the discarded "---", I thought it looked the best. But I'm willing to change it to any of the above, or other suggestion, that gets more votes (please comment).

Searchable uncovered lines in HTML output from cover

---

lib/mnesia/src/mnesia.erl

Do not read from (set | order_set) source table if the content is
already in the transactional context (i.e., a previous write/delete).

Mnesia should always use the local context if available

---

lib/compiler/src/beam_ssa_dead.erl
lib/compiler/src/beam_ssa_opt.erl

The compiler would compile the `idna_mapping.erl` and `idna_table.erl` modules in https://github.com/benoitc/erlang-idna very slowly.
This pull request makes the compiler compile those files about 10 times faster.

Speed up the compiler when compiling the idna package

---

lib/ssl/src/tls_connection.erl

Could cause connection processes not terminate when they should

ssl: Correct check for delayed close due to undliverd data

---

lib/compiler/src/v3_core.erl
lib/compiler/test/warnings_SUITE.erl

There would be a bogus warning when compiling the following
function with the `tuple_calls` option:
dispatch(X) ->
(list_to_atom("prefix_" ++ atom_to_list(suffix))):doit(X).
The warning would look like this:
no_file: this expression will fail with a 'badarg' exception
https://bugs.erlang.org/browse/ERL-838

Eliminate bogus warning when using tuple calls

---

lib/kernel/src/erl_epmd.erl

It accepts both atoms and strings for the node and host name,
plus IP tuples for the host name.
Noticed the missing spec while debugging Dialyzer warnings in RabbitMQ. It's been using strings for both arguments for some time. The docs seem to generate their spec from the code so no changes needed there.

Fix spec for erl_epmd:port_please

---

lib/compiler/src/beam_except.erl
lib/compiler/test/beam_except_SUITE.erl

Fix a bug where the number of live registers in a `bs_get_tail`
instruction was too low.
Consider this example:
-export([bs_get_tail/2]).
bs_get_tail(Bin, Config) ->
bs_get_tail_1(Bin, 0, 0, Config).
bs_get_tail_1(<<_:32, Rest/binary>>, Z1, Z2, F1) ->
{Rest,Z1,Z2,F1}.
`beam_validator` would emit the following diagnostics:
t: function bs_get_tail_1/4+2:
Instruction: {func_info,{atom,t},{atom,bs_get_tail_1},4}
Error:       {uninitialized_reg,{x,3}}:
Here is the part of the code that generates the `function_clause`
exception before the optimization:
{test_heap,6,4}.
{put_list,{x,3},nil,{x,2}}.
{put_list,{integer,0},{x,2},{x,2}}.
{put_list,{integer,0},{x,2},{x,2}}.
{bs_set_position,{x,1},{x,0}}.
{bs_get_tail,{x,1},{x,0},3}.     %3 …

Fix internal consistency failure caused by beam_except

---

erts/etc/unix/Makefile
erts/etc/unix/cerl.src
erts/etc/unix/etp-commands.in
erts/etc/unix/etp-rr-run-until-beam.py

This PR adds more support for [rr](https://rr-project.org/) into cerl and etp. The cerl commands added are:
* cerl -rr ps [-a] ...
* cerl -rr replay [-p PID] ...
These commands are especially usefull when debugging distributed applications using rr.
Example usage:
Start an rr session and create an child node that we make call `erlang:display(hello)`
```
> cerl -rr -sname test
rr: Saving execution to trace directory `/home/eluklar/.local/share/rr/beam.smp-60'.
Erlang/OTP 21 [erts-10.2.3] [source-aef5f4dcfe] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
Eshell V10.2.3  (abort with ^G)
(test@elxd3291v0k)1> erlang:open_port({spawn,"cerl -sname test1"},[]).
#Port<0.9>
(test@elxd3291v0k)2> rpc:call(test1@elxd3291v0k, erlang, display, [hello]).
true
(test@elxd3291v0k)3> flush().
Shell …
```

Expand rr support in cerl and etp

---

lib/compiler/src/beam_ssa_opt.erl
lib/compiler/src/beam_ssa_pre_codegen.erl
lib/compiler/src/beam_ssa_type.erl
lib/compiler/src/beam_validator.erl
lib/compiler/test/match_SUITE.erl

Prior to PR #2100 there wasn't much point to keeping track of tuple element types; they were only known
when we had inserted or extracted values from a tuple, and in neither case was it likely that we'd extract the same values again.
It makes a lot more sense to do so now that type optimizations are applied across local calls; if we return or pass a tuple it's very likely that its elements will be extracted soon after, and knowing their types lets us eliminate more type checks.

Keep track of tuple elements in type optimization pass

---

lib/compiler/src/beam_ssa.erl
lib/compiler/src/beam_ssa_bsm.erl
lib/compiler/src/beam_ssa_opt.erl
lib/compiler/src/beam_ssa_pre_codegen.erl

The ssa_opt_sink optimization of beam_ssa_opt could get very slow
for certain huge functions. 9a190cae9bd7 partly addressed this issue
by terminating the optimization early if there happened to be no
`get_tuple_element` instructions at all in the function.
This commit addresses the issue more directly by making the dominator
calculation in `beam_ssa:dominators/1` more efficient. The same
algorithm as before is used, but it is implemented in a more efficient
way based on the ideas in "A Simple, Fast Dominance Algorithm"
(http://www.hipersoft.rice.edu/grads/publications/dom14.pdf).
As well as being more efficient, the new implementation also gives
an explicit representation of the dominator tree, which makes it
possible to simplify and optimize the `ssa_opt_sink` optimization.

Optimize ssa_opt_sink for huge functions

---

lib/compiler/src/beam_ssa_type.erl
lib/debugger/test/int_eval_SUITE.erl
lib/stdlib/test/erl_eval_SUITE.erl

Consider this pseudo code:
f(...) ->
Val = case Expr of
... ->
... ;
... ->
... ;
... ->
my_abort(something_went_wrong)
end,
%% Here follows code that uses Val.
.
.
.
my_abort(Reason) ->
throw({error,Reason}).
The first two clauses in the case will probably provide some
information about the type of the variable `Var`, information
that would be useful for optimizing the code that follows the
case.
However, the third clause would ruin everything. The call
to `my_abort/1` could return anything, and thus `Val` could
also have any type.
294d66a295f6 introduced module-level type analysis, which will in
general keep track of the return type of a local function
call. However, it does not improve the optimization for this specific
function. When a function never returns, that is, when its type is …

beam_ssa_type: Propagate the 'none' type from calls

---

lib/reltool/doc/src/reltool.xml
lib/reltool/doc/src/reltool_examples.xml
lib/reltool/src/reltool.hrl
lib/reltool/src/reltool_server.erl
lib/reltool/src/reltool_target.erl
lib/reltool/test/reltool_server_SUITE.erl

This adds a rel tuple to the reltool release specific configuration format
as {rel, Name, Vsn, RelApps, Opts} to support the use of
{rel, Name, Vsn, RelApps, [{load_dot_erlang, false}]} for preventing
the insertion of {apply,{c,erlangrc,[]}} into the release script file
and the release boot file.
This change makes it possible to prevent releases generated with reltool
from attempting to load a ${HOME}/.erlang file which is desirable for
production deployment of Erlang, to have greater control of what BEAM
evaluates.  The ${HOME}/.erlang file lacks visibility and its location on
the filesystem separate from where the release lives means it can be
misused in a way that lacks visibility.

reltool: Add load_dot_erlang rel option

---

lib/stdlib/src/calendar.erl
lib/stdlib/test/calendar_SUITE.erl

This patch improves the performance of calendar:gregorian_days_to_date/1
by changing the algorithm for finding the year to log-logarithmic.
The old implementation has linear complexity, which makes function
too slow for large values.
For example:
There is an API that allows you to create events for future dates.
There are users of this API who, for some reasons, choose dates
very far in the future. In such conditions, function works very slow.
New implementation based on interpolation search, takes 1 or 2
iterations at most cases and free from such a flaw.
A unit test was also developed to illustrate the speed of a function
at large values.

Optimize calendar:gregorian_days_to_date/1

---

lib/common_test/src/ct_cover.erl
lib/common_test/src/ct_run.erl
lib/common_test/src/ct_util.hrl
lib/compiler/test/compiler.cover
lib/tools/doc/src/cover.xml
lib/tools/src/cover.erl
lib/tools/test/cover_SUITE.erl

Use `counters:add/3` instead of `ets:update_counter/3`
for counting the number of times a line is executed.
This makes the compiler test suite with coverage enabled
run more than twice as fast (on my computer, in about
5 minutes down from more than 11 minutes).

Use the counters module to speed up cover

---

erts/doc/src/erl.xml
erts/emulator/beam/beam_emu.c
erts/emulator/beam/erl_init.c
erts/emulator/beam/erl_vm.h
erts/etc/common/erlexec.c

Since the +tuple_calls compiler option is not available in versions before OTP 21, and tuple call support was dropped from the emulator in OTP 21, there is currently no upgrade path for existing BEAM code that relies on "tuple calls" (dispatch on parameterized modules) which has been compiled under OTP 20 or earlier. This patch makes it possible to run such modules on OTP 21, allowing them to be recompiled later with the +tuple_calls option. The functionality is only available if the new emulator option "+ztma true" is given, otherwise the behaviour is unchanged from previous releases of OTP 21.

Optional tuple calls

---

erts/emulator/beam/erl_bif_binary.c
lib/stdlib/test/binary_module_SUITE.erl

The bug could be seen by running the test that is added by this commit
in a valgrind enabled emulator.

Fix bug in binary:encode_unsigned causing a read of uninitialized memory

---

erts/doc/src/erl.xml
erts/emulator/beam/beam_emu.c
erts/emulator/beam/erl_init.c
erts/emulator/beam/erl_vm.h
erts/etc/common/erlexec.c

This pull request (to be included in OTP 22.0) removes the support for optional tuple calls that will be introduced in OTP 21.3 (#2113).

Remove support for optional tuple calls

---

lib/dialyzer/src/dialyzer_codeserver.erl
lib/dialyzer/src/dialyzer_contracts.erl
lib/dialyzer/src/dialyzer_utils.erl
lib/dialyzer/test/small_SUITE_data/results/spec_other_module
lib/dialyzer/test/small_SUITE_data/src/spec_other_module.erl

See also https://bugs.erlang.org/browse/ERL-845.
Fix a bug that caused Dialyzer to crash when analyzing a contract with
a module name differing from the analyzed module's name. The bug was
introduced in Erlang/OTP 18.

dialyzer: Fix a bug regarding contracts

---

erts/emulator/beam/external.c

Optimizations and more fare yielding
when long byte lists are encoded in external format (term_to_binary).

Improve term_to_binary for list strings

---

lib/common_test/test_server/configure.in
otp_build

Otherwise sed cannot process `lib/common_test/test_server/configure.in`
when run under UTF-8 locale.  That file uses m4’s `changequote(«, »)`, in latin-1.

Fix a particular sed invocation in otp_build

---

lib/compiler/src/beam_ssa_type.erl
lib/compiler/src/beam_validator.erl

This commit lets the compiler know about the return
type of some of the functions in the `lists` module.
Knowing about the return will allow the compiler to emit
fewer type test instructions, and also fewer instructions
for throwing `case_clause` or `badmatch` exceptions, thus
producing slightly faster and more compact code.
This change makes the `lists` module a part of the language, but it
could be argued that it already is because several functions
(e.g. `member/2` and `keymember/3`) are implemented in as BIFs in the
runtime system. Therefore, a user cannot simply change the
`lists` module and expect everything to continue working as before.
The compiler will now know the return types for the following
functions:
all/2
any/2
keymember/3
member/2
prefix/2
suffix/2
dropwhile/2 …

beam_ssa_type: Use types from some 'lists' functions

---

lib/stdlib/doc/src/ets.xml

The phrasing "no process can access the ETS table in the middle of the
operation" implies that the entire table is looked during
the operation, which is not true if `write_concurrency`
is enabled.

Clarify the atomic guarantees for ets:update_counter()

---

erts/doc/src/erl_nif.xml
erts/emulator/beam/erl_nif.c
erts/emulator/beam/erl_nif_api_funcs.h
erts/emulator/sys/common/erl_check_io.c
erts/emulator/test/nif_SUITE.erl
erts/emulator/test/nif_SUITE_data/nif_SUITE.c

To set and check a "NULL" value for ErlNifPid.

Add enif_set_pid_undefined & enif_is_pid_undefined

---

lib/kernel/src/gen_tcp.erl
lib/kernel/src/gen_udp.erl

gen_tcp: Update connect/3, accept/1, and recv/3 specs
* `connect/3` can return `{error, timeout}`
* `accept/1` cannot return `{error, timeout}`
* `recv/3` can return `{error, timeout}`
gen_udp: Update open/1-2 and recv/3 specs
* `open/1-2` can return `{error, system_limit}`
* `recv/3` can return `{error, timeout}`

gen_tcp, gen_udp: Update specs

---

erts/emulator/beam/erl_ao_firstfit_alloc.c
erts/emulator/beam/erl_bestfit_alloc.c

LIST_NEXT and LIST_PREV causes macro redefinitions from other include files.
beam/erl_ao_firstfit_alloc.c:103:9: warning: 'LIST_NEXT' macro redefined [-Wmacro-redefined]
^
/usr/include/sys/queue.h:507:9: note: previous definition is here
^
1 warning generated.
beam/erl_bestfit_alloc.c:125:9: warning: 'LIST_NEXT' macro redefined [-Wmacro-redefined]
^
/usr/include/sys/queue.h:507:9: note: previous definition is here
^

erts: Fix macro redefinition

---

lib/stdlib/src/gen_statem.erl

Currently, a user of gen_statem cannot use gen_statem types
related to naming & starting in their behaviour implementations
As an example, we cannot do:
```erlang
-spec start_link(Options) -> gen_statem:start_ret() when
Options :: some_complex_thing().
start_link(Options) ->
gen_statem:start_link(?MODULE, [Opts], []).
```
As dialyzer, if configured to complain about unknown types, will
warn that the type `gen_statem:start_ret()` is unknown.
Likewise, for the same reason, we cannot do:
```erlang
-spec do_call_to_gen_statem(ServerRef) -> Reply when
ServerRef :: gen_statem:server_ref(),
Reply :: term().
do_call_to_gen_statem(ServerRef) ->
gen_statem:call(ServerRef, do_thing).
```
This fixes that by exporting the appropriate types

gen_statem exports types related to starting & naming

---

erts/emulator/beam/bif.c
erts/emulator/beam/erl_alloc.types
erts/emulator/beam/erl_dirty_bif.tab
erts/emulator/test/binary_SUITE.erl
erts/emulator/test/emulator_bench.spec

The iolist_size/1 function did not yield even if the input list was
very long and a call to the function did only consume a single
reduction. This commit fixes these problems.

Make iolist_size/1 yield

---

erts/doc/src/erl.xml
lib/common_test/test_server/ts_install.erl
lib/erl_interface/src/prog/erl_start.c
lib/inets/examples/httpd_load_test/hdlt_slave.erl
lib/mnesia/examples/bench/README
lib/stdlib/doc/src/slave.xml
lib/stdlib/src/slave.erl

How about moving away from "rsh" for starting slave nodes etc? On some distros, rsh is a link to ssh, so it kind of works anysay, but I'm not sure if this is something that should be relied on. Better to make ssh the official default, I think. I have updated all relevant places I could find.
I also discovered that test_server checks for an undocumented environment variable ERL_RSH. The only use of this that I could find in the wild was tsung.

Use ssh as the default remote shell

---

lib/compiler/src/beam_ssa_dead.erl

@josevalim pointed out that the `beam_ssa_dead` sub pass took almost all of the time in `beam_ssa_opt` when compiling `lib/elixir/unicode/tokenizer.ex`.
This pull request reduces the time approximately by half, down from almost 2 seconds to under 1 second on my computer.
There are more details in the individual commit messages.

Optimize the beam_ssa_dead sub pass

---

erts/emulator/beam/beam_load.c
erts/emulator/beam/instrs.tab
erts/emulator/beam/ops.tab
erts/emulator/internal_doc/CountingInstructions.md
lib/compiler/src/beam_ssa_opt.erl

This pull request "tunes" the BEAM instructions to better suit the code generated by the new SSA-based compiler. I have based it on instruction frequencies when Dialyzer builds a small PLT.
The topmost commit adds a new internal document that describes how to count instructions.

Tune BEAM instructions for the new compiler (part 1)

---

lib/compiler/src/beam_kernel_to_ssa.erl
lib/compiler/src/v3_kernel.erl

The advantage of moving it up is that it reduces the
size of the code emitted by v3_kernel, speeding
v3_kernel itself and beam_kernel_to_ssa pass.

Move size=all binary clause pruning to v3_kernel

---

lib/kernel/doc/src/application.xml
lib/kernel/src/application.erl
lib/kernel/src/application_controller.erl
lib/kernel/test/application_SUITE.erl

It is equivalent to calling application:set_env/4 on
each application individually, except it is more efficient.
When given duplicate apps or duplicate keys, set_env/1
and set_env/2 will warn. The warning will also be emitted
during boot:
$ erl -config dupkeys.config -s erlang halt
2019-02-27 11:16:02.653100 application: ~ts; duplicate parameter: ~ts~n
kernel
key1
=WARNING REPORT==== 27-Feb-2019::11:16:02.653100 ===
application: kernel; duplicate parameter: key1
$ erl -config dupapps.config -s erlang halt
2019-02-27 11:16:02.653100 duplicate application config: ~ts
kernel
=WARNING REPORT==== 27-Feb-2019::11:16:02.653100 ===
duplicate application config: kernel
Prior to this patch, the behaviour was unspecified,
and duplicate keys and duplicate apps would behave
different depending on the …

Add application:set_env/1 and application:set_env/2
