lib/inets/doc/src/http_server.xml, lib/inets/src/http_server/httpd.erl, lib/inets/test/Makefile, lib/inets/test/httpd_serve_SUITE.erl, lib/inets/test/httpd_serve_SUITE_data/aaa/info.txt, lib/inets/test/httpd_serve_SUITE_data/index.html, lib/inets/test/httpd_serve_SUITE_data/sample_file.html, lib/inets/test/httpd_serve_SUITE_data/subdir/index.html
Often times people want to quickly have a directory index of some folder
to either view directly or share on the local network. For instance, in
Python, `python3 -m http.server` implements a simple server
accomplishing exactly this.
`httpd` has the needed functionality to do this, but did not define a
command-line entrypoint. Users who wanted to quickly serve files with
Erlang needed hacks like shown here:
https://gist.github.com/willurd/5720255#erlang.
This commit adds support for the following forms of hosting a simple
directory listing with support for `index.html` and basic mimetypes,
with the following commands:
erl -S httpd
erl -S httpd serve
erl -S httpd serve path/to/dir
The original suggestion cropped up here:
https://erlangforums.com/t/httpc-httpd-improvements/2622/8
=> inets: Implement simple command-line serving via httpd

erts/emulator/beam/jit/arm/instr_bs.cpp, erts/emulator/test/bs_construct_SUITE.erl
=> jit: Don't create heap binaries for non-binary bitstrings

lib/compiler/src/beam_ssa_type.erl, lib/compiler/test/beam_type_SUITE.erl
=> beam_ssa_type: Fix bugs relating to subtraction in type inference

HOWTO/INSTALL-WIN32.md, HOWTO/INSTALL.md, lib/wx/c_src/Makefile.in, lib/wx/configure, lib/wx/configure.ac
The dynamic libraries for the `wx` application would fail to build with the new linker in Xcode 15 for macOS. One workaround is to force the old linker to be used, but that will stop working when the the old linker is eventually retired.
It turns out that `wx` uses a very old way to create dynamic libraries. Essentially it asks the linker to accept that there are references to undefined symbols, trusting that they will be defined when the dynamic library is loaded. That is done using the following options:
-bundle -flat_namespace -undefined suppress
The option `-undefined suppress` is deprecated by the new linker and it will consider undefined symbols to be an error.
A more modern approaph to creating dynamic libraries is to use the the `-bundle_loader` option to point out an executable …
=> Fix link problem with Xcode 15

lib/compiler/src/beam_ssa_alias.erl
The implementation of the `beam_ssa_alias` pass in OTP 26 can become extremly slow for modules containing huge functions. The `master` branch (for the OTP 27 release next year) already contains a much better implementation that handles huge functions. That implementation is also very different, so we don't want to back-port it to OTP 26.
To make the compiler in OTP 26 usable for huge functions, add a heuristic that disables the alias analysis pass for functions exceeding a certain number of blocks.
Fixes #7667
=> Skip beam_ssa_alias for modules with huge functions

erts/doc/src/erlang.xml, erts/emulator/beam/dist.c, lib/ssl/test/inet_epmd_cryptcookie_inet_ktls.erl, lib/ssl/test/ssl_dist_bench_SUITE.erl
Currently dist input_handler can only be set if dist control is a pid. However, in some case we might want to intercept incoming traffic and do some security check. Allowing dist input_handler to be added in port case would let us achieve this without sacrificing performance while using kTLS in dist. This change won't have impact on any current usage of input_handler.
After this change, if we set socket option to {deliver, term} after handshake, all data will be send to the port owner, and port owner can make dist_ctrl_put_data after validation.
We can also make it work for {deliver, port} socket option, but need a bit more change in driver_output2 in io.c
=> [RFC] Allow dist input_handler to be added if the dist control is an internal port

lib/eunit/src/eunit.erl, lib/eunit/src/eunit_proc.erl, lib/eunit/test/eunit_SUITE.erl
Add an option to `eunit:test(..., Options)`:
{scale_timeouts, N}
Motivation: I ran a bunch of tests on an s390 qemu guest on an x86_64 host to test some NIF code on big endian. This executed much slower, and some of the unit tests timed out. The default eunit timeout is 5 seconds. One can increase it, for example by using a test generator with a `{timeout, Seconds, TestOrTests}` and change xyz_test/0 to xyz_test/1. But this becomes tedious when there are many tests. And to commit such a change to the test code just to accommodate for an unusually slow host doesn't seem like an attractive way to go. Being able to scale the timeouts seems like a good middle ground.
Note that eunit can already read the `$EUNIT` environment var for one-off runs from the command line with increased timeouts.
I …
=> eunit: Add possibility to scale timeouts

erts/emulator/sys/win32/sys.c
This is needed for cmd.exe to have the correct settings after it has been terminated by Ctrl-C. Powershell does not need this, but it does not hurt either.
Closes #7548
Closes #7621
=> erts: Restore console at exit on Windows

lib/inets/test/httpc_SUITE.erl, lib/inets/test/httpd_SUITE.erl, lib/inets/test/httpd_bench_SUITE.erl, lib/inets/test/httpd_test_lib.erl, lib/inets/test/inets_socketwrap_SUITE.erl, lib/inets/test/inets_test_lib.erl
The motivation here is to rely on the Common Test HTML logs to store and contain these logs and keep the terminal clean of output that cannot be attributed to specific running test cases, allowing Common Test to supply wanted logging information on the terminal.
Related to #7375.
=> inets: Do not print test progress logs to terminal

lib/stdlib/doc/src/shell.xml, lib/stdlib/src/shell.erl
If you bind a variable to a value that is very large, you may want to free up that memory when you don't need that variable anymore. You can call history(0) and f(), but you would have to wait for the shell process to do garbage collection or force it to free up that memory. This change makes the shell do garbage collection after history is called with a value lower than the currently configured saved history.
```
1> history(20).
10
2> history(0). %% Will trigger gc for the shell process
```
=> stdlib: garbage collect when saved shell history is reduced.

lib/inets/src/inets_app/inets.erl
With this PR, the inets app starts the ssl and its dependencies by default.
This is a good standard nowadays, preventing redirects from http to https to break, so that it is easier to start and one does not need to start ssl and crypto manually.
Closes https://github.com/erlang/otp/issues/7580
=> inets: start ssl and dependencies by default 

lib/kernel/src/code.erl
This patch improvements code server performance
on escripts by caching its ebin directories, avoiding
several archive lookups when loading modules.
=> Cache ebins found in escripts

erts/emulator/beam/erl_bif_info.c, erts/emulator/beam/erl_gc.c, erts/emulator/beam/erl_process.h
This commit externs the current_stacktrace function and use it in erl_gc when doing max heap event log. This is especially useful when debugging a process that has been killed by the heap limit.
I'm not sure if this is the right way doing it, but here is how it will look like:
```
./bin/erl +hmax 1000000
Erlang/OTP 27 [DEVELOPMENT] [erts-14.0.2] [source-05c52ba036] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
1> lists:seq(1,1000000).
=ERROR REPORT==== 25-Aug-2023::14:41:56.256793 ===
Process:            <0.85.0>
Context:            maximum heap size reached
Max Heap Size:      1000000
Total Heap Size:    1029719
Kill:               true
Error Logger:       true
Message Queue Len:  0
GC Info: …
```
=> Add stacktrace in max heap size log

lib/ssh/src/ssh_cli.erl, lib/ssh/test/ssh_connection_SUITE.erl
`group.erl` now sends `put_expand_no_trim` when entering a history search. `ssh_cli` does not support that message and so when entering a search when SSH is the underlying driver, the expanded result would not be displayed even though the search functionality would still technically work.
This adds support for that `put_expand_no_trim` message when using SSH
I look through the tests and not entirely sure where I would put this. I'm happy to write that if there is any direction of how others might want it tested. In the meantime, this is my quick manual setup to test it works:
**Start the Daemon**
```erlang
%% Create System host key
Priv = public_key:generate_key({rsa, 2048, 65537}).
PemEntry = public_key:pem_entry_encode(:"RSAPrivateKey", Priv).
Pem = public_key:pem_encode([PemEntry]).
ok …
```
=> Fix SSH reverse search with CTRL+R

.github/workflows/actions-updater.yaml
PR #6920 introduced a github actions updater, but it seems like it never actually worked. This PR should make it work....
=> gh: Fix actions updater

.github/workflows/main.yaml
This PR makes it possible to force all tests to be run by adding the label `full-build-and-check` to a PR.
It also schedules a full build and check at 1 AM UTC for the master branch so that we can see if any tests fail on the master branch.
See #7304 for an earlier attempt at this.
=> Run all tests with label

erts/emulator/beam/erl_db_util.c, lib/stdlib/test/ets_SUITE.erl
If the body of a matchspec would return a map with a variable ('$1', '$_' etc) as one of the keys or values and the variable was not an immidiate, the term would not be copied to the receiving processes heap. This would later corrupt the term in the table as the GC could place move markers in it.
Also fixed an issue with the stack-estimation logic for when such a map was encountered.
=> Fix ets match map copy bug

system/doc/reference_manual/data_types.xml, system/doc/reference_manual/expressions.xml
This PR attempts to document the term equivalence operators, whose behavior is [set to change slightly in OTP 27](https://erlangforums.com/t/in-erlang-otp-27-0-0-will-no-longer-be-exactly-equal-to-0-0/2586). It's a pretty subtle (and quite pedantic) change so I'd really appreciate all the feedback I can get, especially from the community at large.
=> otp: Explain the term equivalence operators

erts/emulator/asan/asan_logs_to_html, lib/common_test/src/test_server_ctrl.erl, lib/erl_docgen/priv/dtd/book.dtd, lib/eunit/doc/overview.edoc, lib/xmerl/doc/examples/sdocbook2xhtml.erl, lib/xmerl/doc/src/xmerl_examples.html, lib/xmerl/doc/src/xmerl_xs_examples.html, lib/xmerl/src/xmerl.erl, lib/xmerl/src/xmerl_scan.erl
Following #7643, this removes all remains of (deprecated HTML element) `tt` from Erlang/OTP.
I'm opening it as a draft to signal I'll later rebase this on top of `maint`, since it contains changes from the aforementioned PR: I just wanna make sure CI passes and there's no obvious issues.
Also:
- I ran `make xmllint` and saw no issues (there's lots of warnings but eventually it exits with `0`)
- I ran `make dialyzer` and saw no issues
=> `code` instead of `tt`

lib/stdlib/src/epp.erl, lib/stdlib/test/epp_SUITE.erl, system/doc/reference_manual/macros.xml
[EEP 44](https://www.erlang.org/eeps/eep-0044#built-in-functions-in--if-elif) suggested extensions to the preprocessor.
In OTP 19, the `-error` and `-warning` directives were implemented.
In OTP 21, the `-if` and `-elif` directives were implemented. These directive evaluate a condition that syntactically looks like a guard expression. Semantically, however, there were a few differences compared to standard guard expressions.
One difference was that there were more built-in functions available, such as `defined(Name)` to test whether `Name` is a defined macro. Ultimately, of the suggested built-in functions, only `defined(Name)` was actually implemented (but it was not documented).
Another difference was that calls to unknown functions would not cause a compilation error, but would merely …
=> Preprocessor: Fail compilation for unknown functions

erts/emulator/beam/erl_term.h, erts/emulator/beam/erl_term_hashing.c, erts/emulator/beam/erl_utils.h, erts/emulator/beam/utils.c, erts/emulator/test/bs_match_misc_SUITE.erl, erts/emulator/test/float_SUITE.erl, erts/emulator/test/hash_SUITE.erl, erts/emulator/test/num_bif_SUITE.erl, erts/emulator/test/op_SUITE.erl, lib/compiler/src/beam_ssa_type.erl, lib/compiler/test/float_SUITE.erl, lib/stdlib/test/io_SUITE.erl, lib/stdlib/test/math_SUITE.erl
This is a follow-up of https://github.com/erlang/otp/pull/7552, implementing the actual change in behavior.
https://erlangforums.com/t/in-erlang-otp-27-0-0-will-no-longer-be-exactly-equal-to-0-0/2586
=> erts: Fix term equivalence comparisons on floating-point zero

lib/kernel/src/logger_simple_h.erl, lib/kernel/test/logger_simple_h_SUITE.erl
When debugging the start of kernel it is nice to be able to see the log messages of the different kernel services. So we change so that simple handler will print progress report messages if the log level is debug or higher.
=> logger: Print kernel progress if level is debug

lib/common_test/src/ct_framework.erl, lib/common_test/src/ct_logs.erl, lib/common_test/src/ct_master.erl, lib/common_test/src/ct_run.erl, lib/common_test/src/ct_util.erl
Via @u3s comment in https://github.com/erlang/otp/pull/7428#issuecomment-1682615350. 
This is not the prettiest solution. The problem is that most of `ct_logs` header formatting had no idea that the custom style sheet was a thing, and neither did most of the sites calling it.
=> ct: Correctly handle custom stylesheets in results

lib/eldap/src/eldap.app.src
Discovered via https://github.com/elixir-lang/elixir/issues/12985
In recent elixir (1.15.x) the compiler does code pruning to avoid loading not needed modules. Since eldap needs asn1 but is not declared into its applications, eldap fails to work in recent elixir due to asn1 modules not included at runtime.
=> Add missing asn1 application in eldap.app.src

erts/emulator/sys/common/erl_mseg.c
and other machines where the page size is larger than 16kb.
```
PowerPC> erl -emu_type debug
sys/common/erl_mseg.c:1401:erts_mseg_init() Assertion failed: ((1 << (14)) % sysconf(_SC_PAGESIZE)) == 0
```
=> Fix failing debug assert on PowerPC

lib/kernel/src/code.erl
If a code path directory has too many .beam files,
then `list_dir/1` becomes a quite expensive operation.
With this commit, code:where_is_file/2 and
code:which/1 attempt to directly find a file,
instead of listing the directory.
=> Avoid listing code path directories

lib/compiler/src/compile.erl, scripts/diffable
This is a set of patches which extends the per-pass timing reporting infrastructure in the compiler to allow `scripts/diffable` to produce a cumulative timing report for all modules compiled by the script.
=> Diffable: Cumulative timing report

lib/ssl/test/ssl_test_lib.erl
wsl.exe is not find from on cmd.exe (x32) since it is in the the 64bits path.
Run the 64bits cmd to find the wsl instead.
=> Fix finding openssl on windows x32

erts/emulator/test/driver_SUITE_data/sys_info_drv_impl.c
Hi
Have to pass either a string literal or format string to sprintf() when compiling with -Wformat -Wformat-security -Werror=format-security flags
gcc build command:
```
x86_64-poky-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fcanon-prefix-map  -fmacro-prefix-map=/build/tmp/work/core2-64-poky-linux/erlang/26.1.2/git=/usr/src/debug/erlang/26.1.2-r0  -fdebug-prefix-map=/build/tmp/work/core2-64-poky-linux/erlang/26.1.2/git=/usr/src/debug/erlang/26.1.2-r0  -fmacro-prefix-map=/build/tmp/work/core2-64-poky-linux/erlang/26.1.2/git=/usr/src/debug/erlang/26.1.2-r0  -fdebug-prefix-map=/build/tmp/work/core2-64-poky-linux/erlang/26.1.2/git=/usr/src/debug/erlang/26.1.2-r0  -fdebug-prefix-map=/build/tmp/work/core2-64-poky-linux/erlang/26.1. …
```
=> Fix for -Werror=format-security

lib/wx/c_src/Makefile.in, lib/wx/configure, lib/wx/configure.ac
* This fix solves wx build error of OTP-25.3.2.7 on macOS 14.0 running Apple Silicon (M2 Pro) with Xcode 15.
* This fix is a backport of the fix for OTP-18768 in OTP-26.1.1.
* Reference: https://github.com/erlang/otp/pull/7670
=> Fix macOS wx build error on OTP-25.3.2.7

lib/debugger/src/debugger.app.src, lib/et/src/et.app.src, lib/observer/src/observer.app.src, lib/reltool/src/reltool.app.src
Erlang/OTP 24 added support for optional applications,
this pull request lists them to some apps in order to
exercise the tooling.
If no bugs are found, we could list the optional applications
for more apps in the future.
=> List optional applications for wx apps

lib/crypto/c_src/Makefile.in, lib/crypto/c_src/dss.c, lib/crypto/c_src/openssl_config.h
Engine support was earlier disabled in `crypto` for OpenSSL3.* as we had some problems getting it to work. Those problems are probably fixed now in OTP-26.1 by #7392, but the disabled engine was left behind.
=> Enable engine support for OpenSSL versions >= 3.0

lib/stdlib/src/shell.erl, lib/stdlib/test/shell_SUITE.erl
Allow local func v(), in a restricted shell
Prevent crash when writing a faulty attribute like '1> -hej.'
closes https://github.com/erlang/otp/issues/7765
=> shell bug fixes

lib/stdlib/src/edlin_context.erl, lib/stdlib/src/edlin_expand.erl, lib/stdlib/test/edlin_expand_SUITE.erl, lib/stdlib/test/edlin_expand_SUITE_data/complete_function_parameter.erl
Fix so that the autocompletion doesn't suggest closing parenthesis
since this often times interfere with any module matches in
parameters of functions.
Fix so that functions with almost the same name or differenct cases
doesn't get removed from autocompletion suggestions.
Fix so that nested tuples doesn't crash the autocompletion
closes https://github.com/erlang/otp/issues/7723, https://github.com/erlang/otp/issues/7708
=> Fix autocompletion

lib/kernel/src/group.erl, lib/kernel/src/prim_tty.erl, lib/kernel/test/interactive_shell_SUITE.erl, lib/stdlib/doc/src/shell.xml, lib/stdlib/src/edlin.erl, lib/stdlib/src/shell.erl, lib/stdlib/test/shell_SUITE.erl
Both shell:default_multiline_prompt/1 and
shell:inverted_space_prompt/1 have been exported.
shell:prompt_width/1 is now also available as a
helper function for custom prompt implementations.
=> Export multiline prompt functions

lib/kernel/test/interactive_shell_SUITE.erl, lib/kernel/test/interactive_shell_SUITE_data/valid_keymap.config, lib/stdlib/src/edlin_key.erl
stdlib: fix shell keyboard configuration errors
Fix so that ctrl+h, ctrl+backspace generate backward_delete_char
Fix overriding of keyboard shortcuts
closes https://github.com/erlang/otp/issues/7749 , https://github.com/erlang/otp/issues/7776
=> Fix keyboard configuration bugs

lib/inets/test/httpd_serve_SUITE.erl
- follow-up of PR-7299
- `0.0.0.0` does not seem to work on Windows machines the way it does on Linux
=> inets: fix httpd_serve_SUITE on Windows

lib/public_key/asn1/Makefile, lib/public_key/asn1/OTP-PKIX.asn1, lib/public_key/doc/src/public_key.xml, lib/public_key/doc/src/public_key_app.xml, lib/public_key/include/public_key.hrl, lib/public_key/src/Makefile, lib/public_key/src/pubkey_cert.erl, lib/public_key/src/pubkey_policy_tree.erl, lib/public_key/src/public_key.app.src, lib/public_key/src/public_key.erl, lib/public_key/test/pkits_SUITE.erl, lib/public_key/test/pubkey_cert_SUITE.erl
=> Ingela/public key/policies/otp 17844

lib/public_key/src/pubkey_os_cacerts.erl, lib/public_key/test/public_key_SUITE.erl
Previously it was either one or the other, so the latest commit with Solaris fixes didn't work.
=> Fix mixing loading from file or all files in a dir

lib/mnesia/src/mnesia_dumper.erl, lib/mnesia/test/mnesia_evil_backup.erl
Remove the disk_delete_indecies in the restore op, it could fail if called during startup and it will be done in create_table op later anyway.
Fixes #7766
=> Fix restore disk_only with index

lib/kernel/src/pg.erl
Typo introduced in #7659 may may cause pg to crash when 'DOWN' monitor message is in the queue while explicit leave is processed earlier.
Closes #7807
=> [pg] Fix typo potentially leading to crash

erts/emulator/beam/external.c
Magic binaries might have data outside their actual Binary struct so we shouldn't try to assert about where their data is here.
Encountered this while testing a NIF that generates magic binaries via `enif_make_resource_binary` with `-emu_type debug`.
=> beam/external: don't blow assert on encounter with a magic binary

lib/ssl/src/ssl.erl
The type `signature_algs/0` is already a list, so the return type for `signature_algs/2` should just be `signature_algs/0`.
Additionally, export the type since it's used in a spec of an exported function and it's already documented.
=> ssl: Fix typespec for signature_algs/2 and export signature_algs/0 type

lib/public_key/src/public_key.erl
To reproduce see:
https://github.com/erlang/otp/issues/7811
In our case the error is when calling from elixir:
"TLS :client: In state :certify at tls_dtls_connection.erl:705 generated CLIENT ALERT: Fatal - Handshake Failure\n - :malformed_handshake_data".
Only when fips mode enabled.
=> Fix #7811, SSL not working on FIPS enabled OTP 26.1 

erts/doc/src/alt_dist.xml
Thank you for working on OTP, I've been thoroughly enjoying it for the past few months.
I have other more extensive typo fixes that I'm working through https://github.com/erlang/otp/compare/maint..ivanov:otp:pi/doc-fix-typos-and-repeated-words?diff=unified , but wanted to start off with this changeset that brought me here today to begin with. The other changeset is currently up to 50 files, and I'm only about a 10th of the way through.
=> typo fixes in alt_dist.xml

lib/common_test/doc/src/config_file_chapter.xml, lib/common_test/doc/src/ct.xml, lib/common_test/doc/src/ct_suite.xml, lib/common_test/doc/src/dependencies_chapter.xml, lib/common_test/doc/src/example_chapter.xml, lib/common_test/doc/src/write_test_chapter.xml
Per dcda9b507bf and review of #7806, usage of CT's `?config` macro is no longer recommended. Replace the documentation referencing it with `proplists:get_value`, which works the same way and can take an optional third argument for the default return value.
=> ct: Remove documentation for deprecated ?config

lib/kernel/src/group.erl, lib/ssh/src/ssh_cli.erl, lib/stdlib/src/edlin.erl
=> ssh: support dumb terminals in ssh client

system/doc/design_principles/sup_princ.xml
line 492:
missing "," 
line 536: I think "indata" is not correct.
line 570:
Of course, only one of them could be used: either "the important exception" or "an important exception". But "one important exception" is better than both of them. https://ludwig.guru/s/important+exception
=> Fix Typos in Supervision Principles Docs

lib/compiler/test/mc_SUITE.erl, lib/stdlib/src/erl_expand_records.erl
When attempting to match part of a record in the key of a map generator, the entire record would be matched.
Example:
-module(t).
-export([test/0]).
-record(r, {a,b}).
f(Map) ->
[V || #r{a=N} := V <- Map, is_integer(N)].
test() ->
f(#{#r{a=1} => 1, #r{a=2,b=42} => 2}).
It would be expected that `t:test()` would return `[1,2]`, but it returned `[1]` because the entire record was matched, instead of just field `a`. Therefore, only the first record `#r{a=1,b=undefined}` would match.
Fixes #7875
=> Fix partial record matching in map generator

lib/stdlib/doc/src/gb_sets.xml, lib/stdlib/doc/src/gb_trees.xml, lib/stdlib/src/gb_sets.erl, lib/stdlib/src/gb_trees.erl, lib/stdlib/test/gb_sets_property_test_SUITE.erl, lib/stdlib/test/property_test/gb_sets_prop.erl
Provide some common operations that is available for BSTs.
API follows java TreeSet / TreeMap
=> Add higher/lower search functions in gb_trees and gb_sets

erts/doc/src/erl_cmd.xml, erts/etc/common/erlexec.c, lib/inets/src/http_server/httpd.erl, lib/inets/test/httpd_serve_SUITE.erl
Since the primary intended usecase for -S is command-line scripts such as the new "httpd serve", automatically add the "-noshell" flag to simplify noninteractive use.
Remove a leading newline from the httpd serve startup output that was used to separate it from the shell prompt.
As suggested in #7470.
=> erl: Set -noshell when -S is used

lib/stdlib/doc/src/string.xml, lib/stdlib/src/string.erl, lib/stdlib/test/string_SUITE.erl
Calculate word similarity, can for example be used to provide potential alternatives in error messages.
Replaces #7863
=> Add string:jaro_similarity/2

erts/emulator/drivers/common/inet_drv.c
Fix for issue #7736
An unnecessary conversion `htonl` is applied to an option `mreq4.imr_ifindex`. Remove it.
=> inet_drv.c: mreq4.imr_ifindex value fix #7736

lib/common_test/src/ct_property_test.erl
While I have no clue what the `{set, {var, _}, {call, M, F, Args}}` part is all about (@HansN, maybe you can shed some light on this, `git blame` says this was done by you, albeit ~9 years ago :sweat_smile:), this fails with a `try_clause` exception if a property fails on input that is a non-empty list, like eg `[1, 2, 3]`. `Tool:counterexample()` will then return `[[1, 2, 3]]`, for which `lists:last(hd([[1, 2, 3]]))` will return `3`, for which there is no matching clause in the `try`.
=> Fix `ct_property_test` result handling for failing properties

lib/common_test/doc/src/ct_hooks_chapter.xml, lib/common_test/src/cth_log_redirect.erl, lib/common_test/test/ct_hooks_SUITE.erl
In addition to the existing way of logging to both the CT HTML logs and console, allow users to completely replace the standard logging handler with the log redirect hook, effectively silencing console logging output during Common Test runs.
Mostly taken from #7375, with the caveat that "add" mode continues being the default, and no changes outside of the hook take place.
Additionally, group cth_log_redirect test cases together to allow for easier module verification.
As suggested in https://github.com/erlang/otp/pull/7375#issuecomment-1818801029
=> ct: Introduce replace mode to cth_log_redirect

erts/emulator/beam/beam_file.c, erts/emulator/beam/bif.c, erts/emulator/beam/erl_fun.c, erts/emulator/beam/erl_fun.h, erts/emulator/beam/erl_process_dump.c, erts/emulator/beam/export.c, erts/emulator/beam/export.h, erts/emulator/beam/external.c, erts/emulator/beam/global.h
By storing external funs in a dedicated literal area shared by all modules and keeping a reference to them in the export entry they refer to, they will no longer be tied to the lifetime of the module that created them. `make_fun/3` will also use this reference so that dynamic creation of an external fun also results in a shared literal. This opens up for optimizations in, for example, `gen_statem` where there will no longer be any drawbacks to caching the event function when in `state_functions` mode.
=> erts: Share external funs globally

erts/emulator/nifs/unix/unix_socket_syncio.c
The role should be reader and not writer, this probably is a result of a copy paste.
=> Fix typo in unix_socket_syncio.c

erts/emulator/nifs/common/prim_socket_nif.c
The return value of `prim_socket:cancel/3` changed in https://github.com/erlang/otp/commit/640c4a52c806d5a080f7e327d53cb8c6f022b4b0 from `select_sent|not_found` to `{error, select_sent|not_found}`. 
However, `socket` module keeps expecting that `prim_socket:cancel/3` returns `select_sent|not_found` (without `{error, _}`) as following code:
```erlang
%% From: https://github.com/erlang/otp/blob/OTP-26.0/lib/kernel/src/socket.erl#L4595-L4603
cancel(SockRef, Op, Handle) ->                                                                                                                                                                                
case prim_socket:cancel(SockRef, Op, Handle) of …
```
=> Fix a bug that prim_socket:cancel/3 could return `{error, select_sent|not_found}` while socket module expects `select_sent|not_found`

lib/inets/src/http_server/httpd_file.erl, lib/inets/test/httpd_SUITE.erl, lib/inets/test/inets_socketwrap_SUITE.erl
Change error code as 500 is perceived to be a more unexpected type of fault.
=> inets: Do not consider file errors as "500 - Internal server error"

lib/ssl/src/ssl_handshake.erl, lib/ssl/src/ssl_pkix_db.erl
During high load, we observe lock contention on this ETS table:
```
> lcnt:inspect(db_tab, [{print, [id, colls, ratio, duration]}]).
id  #collisions  collisions [%]  duration [%]
--- ------------ --------------- -------------
ssl_otp_cacertificate_db         7827         12.5136      616.1264
ssl_otp_ca_file_ref           30          0.2561        0.0026
```
ets:select is more efficient than using ets:foldl and in practice reduces the contention that we see here.
Separately I plan to also issue another PR to add read_concurrency to the ETS table which has also helped reduce the incidence of this.
=> Optimize pkix_db cert selection

lib/inets/src/http_client/httpc.erl
BodyFormat should be `string | binary` if possible `{body_format, BodyFormat}` are `{body_format, string}` and `{body_format, binary}`.
=> Fix BodyFormat of spec

lib/stdlib/src/erl_stdlib_errors.erl
In the previous PRs #6197 and #7590, the `replace/3,4` functions in the `re` and `binary` modules were changed to also accept a function as third (replacement) parameters. However, the error message formatting facility in `erl_stdlib_errors` was not adapted, and in the case that an invalid parameter (like and atom for instance) is passed in, it would say that argument 3 is not a binary/iodata, whereas functions would also be possible.
This PR corrects the error reporting such that, if an invalid term is given as replacement, it will say that argument 3 is not a valid replacement.
EDIT: Fix for the `re` part has been moved into #7925 to be merged into `maint`.
=> Fix error message for invalid replacement args in `binary:replace/3,4`

lib/compiler/src/beam_types.erl, lib/compiler/test/beam_type_SUITE.erl
=> compiler: Fix some vestigial +0.0/-0.0 issues

lib/ssl/src/ssl.erl, lib/ssl/src/ssl_cipher.erl, lib/ssl/test/ssl_api_SUITE.erl, lib/ssl/test/tls_api_SUITE.erl
When running a ssl server the user must provide cert and key or use an anonymous cipher in tlsv1.2. Otherwise no connection will succeed.
Add an option check so that this is detected earlier, and gives the user an appropriate error instead of just failing each connection attempt.
To keep backwards compatibility the check is only done in handshake, since it is allowed to use an empty (or minimal) option list in ssl:listen/2 and provide the options in handshake later.
Solves #7493
=> ssl: Error server options when no certs

lib/inets/test/http_test_lib.erl
With the parallel tests recently introduced into httpc_SUITE, multiple clients may be waiting to be accepted (`gen_tcp:accept`) by the test server spawned in `http_test_lib` at once. On Linux, if the backlog is full, clients wait for a while before timing out. On FreeBSD however, the connection is instantly rejected with `ECONNRESET`, causing most tests in the parallel groups to fail simultaneously.
Increase the backlog from the default 5 to 100 to queue up excess requests on FreeBSD the same way as on Linux.
As brought up in #7899
=> inets: Fix httpc parallel tests failing on FreeBSD

lib/compiler/src/beam_block.erl, lib/compiler/src/beam_clean.erl, lib/compiler/src/beam_flatten.erl, lib/compiler/src/beam_trim.erl
When a simple instruction such as building a tuple or calling a non-garbage-collecting BIF is followed by a `swap` instruction, it is sometimes possible to replace the `swap` instruction with a `move` placed **before** the other instruction.
Here is an example of a guard BIF call:
{bif,self,{f,0},[],{x,2}}.
{swap,{x,1},{x,2}}.
which can be rewritten like so:
{move,{x,1},{x,2}}.
{bif,self,{f,0},[],{x,1}}.
The `make_fun3` instruction for creating a fun is frequently followed by a `swap` instruction:
{make_fun3, ...}.
{swap,{x,0},{x,2}}.
which can be replaced with a `move` instruction:
{move,{x,0},{x,2}}.
{make_fun3, ...}.
This optimization is worthwhile because a `move` instruction is generally cheaper than a `swap` instruction.
=> compiler: Rewrite swap to move

lib/inets/test/httpd_serve_SUITE.erl
The test previously tried to connect via 0.0.0.0 and ::, which may not work depending on the network configuration. Since this to seems to be a Linux specific feature that was relied on on the original machine used to implement this feature, and it so far has caused problems with multipel platforms, change the code to simply always convert into 127.0.0.1 and ::1 on systems except from Linux to prevent compatibility issues. (Converting for any host would fail CI for Linux).
Tested on Debian, FreeBSD and OpenBSD :-)
=> inets: Fix httpd_serve_SUITE failing on OpenBSD

lib/kernel/src/erl_erts_errors.erl
Before this patch, it would say:
1> erlang:phash2(nil, 0).
in function  erlang:phash2/2
called as erlang:phash2(nil,0)
*** argument 1: out of range
=> Fix error message for erlang:phash*/2

erts/emulator/beam/jit/arm/instr_select.cpp, erts/emulator/test/beam_SUITE.erl
Fixes [this bug](https://elixirforum.com/t/weird-limit-in-number-of-function-clauses-when-running-on-aarch64/59513) reported on the Elixir forum.
=> erts: Fix large select instructions on ARM

lib/kernel/src/Makefile
This has come up here: https://github.com/erlang/otp/pull/7755#issuecomment-1786825281
=> Avoid mixed usage of ebin directories on build

lib/kernel/src/code.erl, lib/kernel/src/code_server.erl, lib/kernel/test/code_SUITE.erl
The first regression is not attempt to
load code if mode is embedded.
Erlang/OTP 25 only attempted to perform
code loading if the mode was interactive:
https://github.com/erlang/otp/blob/maint-25/lib/kernel/src/code_server.erl#L301
This check was removed in #6736 as part of
the decentralization. However, we received
reports of increased cpu/memory usage in
Erlang/OTP 26.1 in a code that was calling
code:ensure_loaded/1 on a hot path. The
underlying code was fixed but, given #7503
added the server back into the equation for
ensure_loaded we can add the mode check
back to preserve Erlang/OTP 25 behaviour.
The second regression would cause the caller
process to deadlock if attempting to load a
file with invalid .beam more than once.
Closes #7721.
Closes #7725.
=> Fix regressions in code:ensure_loaded/1

erts/doc/src/erl_nif.xml, erts/emulator/beam/erl_nif.c, erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Fix function declaration mismatch warning with gcc-13/14:
```
beam/erl_nif.c:1476:8: warning: conflicting types for 'enif_binary_to_term' due to enum/integer mismatch; have 'size_t(ErlNifEnv *, const unsigned char *, size_t,  ERL_NIF_TERM *, ErlNifBinaryToTerm)' {aka 'long unsigned int(struct enif_environment_t *, const unsigned char *, long unsigned int,  long unsigned int *, ErlNifBinaryToTerm)'} [-Wenum-int-mismatch]
1476 | size_t enif_binary_to_term(ErlNifEnv *dst_env,
|        ^~~~~~~~~~~~~~~~~~~
In file included from beam/erl_nif.c:44:
beam/erl_nif_api_funcs.h:174:31: note: previous declaration of 'enif_binary_to_term' with type 'size_t(ErlNifEnv *, const unsigned char *, size_t,  ERL_NIF_TERM *, unsigned int)' {aka 'long unsigned int(struct enif_environment_t *, const unsigned char …
```
=> Fix enif_binary_to_term function declaration mismatch warning

erts/emulator/beam/bif.tab, erts/emulator/beam/erl_db.c, lib/stdlib/doc/src/ets.xml, lib/stdlib/src/erl_stdlib_errors.erl, lib/stdlib/src/ets.erl, lib/stdlib/test/ets_SUITE.erl
This PR adds a new function `update_element/4` to the `ets` module which accepts a default object as additional argument. It works the same as `update_element/3` if the given key exists in the given table; However, if no object with the given key exists, it inserts the given default object under that key, performs the update operation on it, and unconditionally returns `true`. In that sense, `update_element/4` is for `update_element/3` what `update_counter/4` is for `update_counter/3`.
=> Add `ets:update_element/4` to accept a default object

erts/emulator/beam/jit/asm_load.c
If a module was prepared for loading, but the loading never finished, the memory allocated for coverage information could leak. This bug was introduced in 141a287d2cd293c0d0a4f94edfb3852f5e110ca3.
=> Eliminate memory leak in the native coverage feature

lib/kernel/src/group.erl
We can do this because we know that the list will contains valid unicode code points so there is no need to validate it again. This speeds up reading standard_io a lot.
Solves #7924
=> kernel: Short-circuit when casting from list to list

erts/emulator/beam/jit/arm/beam_asm.hpp, erts/emulator/beam/jit/arm/beam_asm_global.hpp.pl, erts/emulator/beam/jit/arm/instr_arith.cpp, erts/emulator/beam/jit/arm/instr_bs.cpp, erts/emulator/beam/jit/arm/instr_call.cpp, erts/emulator/beam/jit/arm/instr_common.cpp, erts/emulator/beam/jit/arm/ops.tab, erts/emulator/beam/jit/beam_jit_args.hpp, erts/emulator/beam/jit/beam_jit_common.cpp, erts/emulator/beam/jit/beam_jit_common.hpp, erts/emulator/beam/jit/x86/beam_asm.hpp, erts/emulator/beam/jit/x86/beam_asm_global.hpp.pl, erts/emulator/beam/jit/x86/instr_arith.cpp, erts/emulator/beam/jit/x86/instr_bs.cpp, erts/emulator/beam/jit/x86/instr_common.cpp, erts/emulator/test/bs_match_bin_SUITE.erl, erts/emulator/test/op_SUITE.erl
Take better advantage of type information and known constant operands to enhance code generation. Also take advantage of the bit manipulation instructions for AArch64 to enhance code generation for the binary syntax.
=> Do some minor enhancements of the code generation in the JIT

lib/stdlib/test/ets_SUITE.erl
This PR fixes warnings regarding matching on `0.0` and a usage of the deprecated `erlang:phash/2` function in the current `ets_SUITE`.
=> Fix warnings in `ets` test suite

erts/emulator/beam/time.c, erts/emulator/sys/common/erl_poll.c, erts/emulator/sys/win32/erl_poll.c, erts/emulator/test/timer_bif_SUITE.erl, erts/include/internal/erl_errno.h, erts/lib_src/pthread/ethr_event.c, erts/lib_src/win/ethr_event.c
32-bit runtime systems on most Unix like platforms could crash if a BIF timer was set with a huge timeout of more than 68 years into the future. In order for the crash to occur, the huge timer (at a later time than when it was set) had to become the nearest active timer set on the specific scheduler on which it was set. This could not happen on a system with only one scheduler since there would always be shorter timers in the system.
Setting a timer larger than 49 days on Windows could under rare circumstances cause the timeout to be delayed.
=> Fix timeout overflow

lib/kernel/src/group.erl, lib/kernel/test/interactive_shell_SUITE.erl, lib/stdlib/doc/src/shell.xml, lib/stdlib/doc/src/stdlib_app.xml, lib/stdlib/src/edlin.erl, lib/stdlib/src/edlin_key.erl, lib/stdlib/src/shell.erl
Adds an option for users to provide a formatter for submitted shell statements.
=> stdlib: add auto formatting to the shell

lib/parsetools/src/yecc.erl, lib/parsetools/test/yecc_SUITE.erl
We do this so that tools that want to know what the source of a generated file is, can look at the -file of the -module attribute.
=> yecc: Emit .yrl file around -module attribute

lib/stdlib/src/timer.erl
The current implementation of the `timer` module uses the default protection level of `protected` for its internal "bookkeeping" `ets` table. However, since the timer server process is the only one using this table, `private` is a better choice because operations can then skip any otherwise necessary locking.
=> Optimize the `timer`module by using a private table

erts/preloaded/src/erl_prim_loader.erl, lib/kernel/src/code.erl, lib/kernel/src/code_server.erl, lib/stdlib/src/escript.erl
The previous code called code, which then called the code server,
but none of those calls rely directly on the code server (or its state).
=> Remove indirection on set primary archive

erts/configure, erts/emulator/sys/unix/sys_time.c, make/autoconf/otp.m4
A workaround to avoid breaking "micro level process accounting on /proc/self" broke the build on Yocto. As this is a really ancient
workaround (pre-2009) and the comment is unclear about what actually breaks, we'll try removing it to see if this is still a problem.
=> otp: Fix build on Yocto

make/test_target_script.sh
- adjust error message reported by test_target_script.sh
- "make test" is expected to work nowadays
=> make: remove not needed error message part

lib/crypto/c_src/openssl_config.h
Fix the following build failure without DES:
```
cipher.c:51:42: error: 'EVP_des_ede3_cbc' undeclared here (not in a function); did you mean 'SN_des_ede3_cbc'?
51 |     {{"des_ede3_cbc"}, "des-ede3-cbc", {&EVP_des_ede3_cbc}, 0, 0},
|                                          ^~~~~~~~~~~~~~~~
|                                          SN_des_ede3_cbc
```
Fixes:
- http://autobuild.buildroot.org/results/1aace0ee738f8ec4aa2c9a739fc7535c3b6bf884
=> lib/crypto/c_src/openssl_config.h: fix build without DES

lib/ssl/src/ssl_config.erl, lib/ssl/test/ssl_api_SUITE.erl, lib/ssl/test/ssl_api_SUITE_data/dHParam-invalid.pem
The fallback after "dh" ssl option was undefined was to get "dh" from
ssl options again. This is clearly wrong and now changed to the
documented fallback "dhfile" ssl option.
Add test for passing an invalid dhparams file to server ssl options.
=> ssl: Get dhfile ssl option

lib/xmerl/doc/src/xmerl_ug.xmlsrc, lib/xmerl/src/Makefile, lib/xmerl/src/xmerl.app.src, lib/xmerl/src/xmerl_xml_indent.erl, lib/xmerl/test/xmerl_SUITE.erl
The indent module was added to provide out of the box indented output instead of the standard xmerl_xml-module.
The code is based on the Elixir xmerl_xml_indent-package. That package can be found on hex.pm.
The documentation was updated to mention the module and its use using the motorcycle-example.
Test-cases have been added to the xmerl-SUITE as requested by OTP-maintenance team.
This pull-request supersedes #6180 and should hopefully pass all the tests.
=> add xmerl_xml_indent-module

erts/emulator/beam/bif.tab, erts/emulator/beam/erl_db.c, erts/emulator/beam/erl_db_catree.c, erts/emulator/beam/erl_db_hash.c, erts/emulator/beam/erl_db_tree.c, erts/emulator/beam/erl_db_tree_util.h, erts/emulator/beam/erl_db_util.h, lib/stdlib/doc/src/ets.xml, lib/stdlib/src/erl_stdlib_errors.erl, lib/stdlib/src/ets.erl, lib/stdlib/test/Makefile, lib/stdlib/test/ets_SUITE.erl, lib/stdlib/test/ets_property_test_SUITE.erl, lib/stdlib/test/property_test/ets_prop.erl
A common use case for ets:next is to read the next object stored in key order. This currently requires an ets:next followed by an ets:lookup for the object . Combining them in one call makes the overall operation much faster by getting rid of the second call to fetch the value. I also saw similar pattern being used in ets:foldl, so we can get speed up there as well by using this in ets:foldl .
Here is a very simple benchmark using erlperf: https://gist.github.com/mittalanshul/819e4d8d95cf993b3d31a36c3d72ac9c
There are a few problems with the PR as of now:
1. The way I passed the function pointers in erl_db code makes the code much cleaner, but will also negate any benefits that were being obtained by inlining (which I am not sure how much they were)
2. The ets_suite test uses a somewhat …
=> add ets:first/next/last/prev_lookup

system/doc/programming_examples/list_comprehensions.xml
Actually, I just wanted to add a missing word, but then went on to make the description a little more elaborate and hopefully clearer. The nested list structure may seem a little too much, but I think this way the explanation is more structured.
=> Improve list comprehensions quicksort example

lib/ssl/doc/src/ssl_crl_cache.xml, lib/ssl/src/ssl_crl_cache.erl
Update so that all API functions uses specs
=> ssl: Add missing specs for API functions

system/doc/reference_manual/features.xml
Based on the change note, I think that it's not clear that you need to pass that option if you want to use it in shell.
Nitpick, hope it doesn't annoy anyone :D
=> features docs update

erts/configure, erts/configure.ac
On Ubuntu 20.04 and later gcc adds -fcf-protection=full by default, which cannot be used together with -mbranch-protect. So we set -fcf-protection=none so that we can use -mbranch-protect.
=> erts: Fix spectre mitigation configure test

lib/kernel/src/file_io_server.erl, lib/stdlib/src/io_lib.erl, lib/stdlib/test/io_proto_SUITE.erl
Before this fix if a get_until function would return data when eof is seen, the result would not be correctly converted to a binary when returned.
closes #4992
=> stdlib: Fix io_lib:get_until to return binaries at eof

erts/emulator/beam/beam_bif_load.c, erts/emulator/beam/jit/arm/beam_asm.hpp, erts/emulator/beam/jit/arm/beam_asm_global.cpp, erts/emulator/beam/jit/asm_load.c, erts/emulator/beam/jit/beam_asm.h, erts/emulator/beam/jit/beam_jit_common.cpp, erts/emulator/beam/jit/beam_jit_main.cpp, erts/emulator/beam/jit/beam_jit_metadata.cpp, erts/emulator/beam/jit/x86/beam_asm.hpp, erts/emulator/beam/jit/x86/beam_asm_global.cpp, erts/emulator/beam/module.h
This resolves some random crashes when stepping backwards under `rr` (but sadly not all).
=> jit: Unregister unloaded code with GDB integration

lib/odbc/doc/specs/.gitignore, lib/odbc/doc/src/Makefile, lib/odbc/doc/src/odbc.xml, lib/odbc/doc/src/specs.xml, lib/odbc/src/odbc.erl
=> odbc: Add missing API specs

lib/stdlib/src/gen_event.erl, lib/stdlib/src/gen_fsm.erl, lib/stdlib/src/gen_server.erl, lib/stdlib/src/gen_statem.erl, lib/stdlib/test/gen_event_SUITE.erl, lib/stdlib/test/gen_fsm_SUITE.erl, lib/stdlib/test/gen_server_SUITE.erl, lib/stdlib/test/gen_statem_SUITE.erl
The #7720 added process labels and the `proc_lib:set_label/1` and `get_label/1` functions. This PR includes a process label printout in crash message printouts from gen_statems, gen_servers, gen_events and gen_fsms, to make it easier to identify the crashing process.
Below is an example of what it may look like for a gen_statem. The "Process label" on the second line is new.
```
** State machine <0.1386.0> terminating
** Process label = {some_label, ...}
** When server state  = #{...}
** Reason for termination = error:...
** Callback modules = [...]
** Callback mode = state_functions
```
If no label has been set, then that process label line will not be included, and the printout will look like it did before this commit.
=> stdlib: Include process label in gen_statem, gen_server, gent_event, gen_fsm crash messages

lib/stdlib/doc/src/argparse.xml, lib/stdlib/test/argparse_SUITE.erl
The second argument must not be a string as-is. Add a testcase to
validate that it throws a validation error.
=> argparse: Correct argparse tuple help docs

lib/tools/doc/src/Makefile, lib/tools/doc/src/ref_man.xml, lib/tools/doc/src/specs.xml, lib/tools/doc/src/tprof.xml, lib/tools/src/Makefile, lib/tools/src/tprof.erl, lib/tools/test/Makefile, lib/tools/test/tprof_SUITE.erl, system/doc/efficiency_guide/profiling.xml, system/doc/general_info/upcoming_incompatibilities.xml
Instead of having 4 profilers with 4 different APIs, this pull request unifies call, time, and memory profiling under a single module.
The goal is to eventually deprecate and remove cprof and eprof and have only two profiling modules: `fprof` and `tprof`, which are understandably different as they provide different functionalities and measurements.
Here is the new tprof in practice:
```
1> tprof:profile(base64, encode, [crypto:strong_rand_bytes(1024000)]).
FUNCTION                                         CALLS  [    %]
rpc:module_info/1                                    1  [ 0.00]
inet_config:module_info/1                            1  [ 0.00]
io_lib_format:module_info/1                          1  [ 0.00]
kernel_config:module_info/1                          1  [ 0.00] …
```
=> Rename hprof to tprof

lib/wx/configure, lib/wx/configure.ac
The PR is intended to fix the issues described in https://github.com/erlang/otp/issues/7940#issuecomment-1885106629, which manifest on Linux.
=> Fix configuration and build of wxWidgets driver when PIE is present

lib/inets/src/http_client/httpc_handler.erl, lib/inets/src/http_server/httpd_request_handler.erl
=> inets: Use proc_lib:set_label

erts/doc/src/erl_prim_loader.xml, erts/preloaded/src/erl_prim_loader.erl, lib/debugger/src/int.erl, lib/kernel/src/application_controller.erl, lib/kernel/src/code.erl, lib/kernel/src/code_server.erl, lib/kernel/src/erl_boot_server.erl, lib/kernel/src/inet_config.erl, lib/kernel/src/inet_db.erl, lib/reltool/src/reltool_utils.erl, lib/sasl/src/release_handler_1.erl, lib/ssl/src/ssl_dist_sup.erl, lib/stdlib/src/shell.erl, lib/stdlib/test/escript_SUITE_data/archive_script/archive_script_main.erl, lib/stdlib/test/escript_SUITE_data/archive_script/archive_script_main2.erl, lib/stdlib/test/escript_SUITE_data/archive_script_file_access/archive_script_file_access.erl
This reduces the amount of work on the code server
and erl_prim_loader, by loading data on the client
whenever possible. This speeds up compilation of
Livebook from 7.2s to 6.9s (roughly 4%) and should
keep fewer binary references around.
This is done by introducing `erl_prim_loader:read_file/1`,
which stays closer to Erlang's file reading semantics
and does not rely on `erl_prim_loader` code paths.
`erl_prim_loader:get_file/1` and `erl_prim_loader:get_path/0`
should be considered deprecated.
Future work should fully remove the concept of paths
from `erl_prim_loader` and move them into `init`.
=> Read .beam files from cached paths in the client

lib/kernel/src/application_controller.erl
This field is not set or read. It seems that the restart_type is stored in the running field of the controller's state.
=> Remove unused field from appl record in application_controller

erts/emulator/beam/jit/arm/beam_asm.hpp, erts/emulator/beam/jit/arm/beam_asm_module.cpp, erts/emulator/beam/jit/arm/instr_arith.cpp, erts/emulator/beam/jit/arm/instr_bif.cpp, erts/emulator/beam/jit/arm/instr_bs.cpp, erts/emulator/beam/jit/arm/instr_common.cpp, erts/emulator/beam/jit/arm/instr_guard_bifs.cpp, erts/emulator/beam/jit/arm/instr_map.cpp, erts/emulator/beam/jit/arm/instr_msg.cpp, erts/emulator/beam/jit/arm/instr_select.cpp, erts/emulator/beam/jit/arm/ops.tab, erts/emulator/beam/jit/arm/predicates.tab, erts/emulator/beam/jit/beam_jit_common.hpp, erts/emulator/beam/jit/beam_jit_register_cache.hpp, erts/emulator/beam/jit/x86/beam_asm.hpp, erts/emulator/beam/jit/x86/beam_asm_module.cpp, erts/emulator/beam/jit/x86/instr_arith.cpp, erts/emulator/beam/jit/x86/instr_common.cpp, erts/emulator/beam/jit/x86/instr_float.cpp, erts/emulator/beam/jit/x86/instr_fun.cpp, erts/emulator/beam/jit/x86/instr_guard_bifs.cpp
This pull request improves the caching mechanism introduced in #6298.
For x86_64, 170,752 loads of BEAM registers from memory are now eliminated, compared to 115,998 loads before this PR.
For AArch64/ARM64, 21,109 load of BEAM registers are now eliminated, compared to 15,098 loads before this PR. (The six first X registers are kept in CPU registers, and therefore the caching only applies to Y registers and `{x,6}` and above.)
=> Improve caching of BEAM registers

lib/edoc/src/Makefile, lib/edoc/src/edoc.app.src, lib/edoc/src/edoc_html_to_markdown.erl, lib/edoc/src/edoc_layout.erl, lib/edoc/src/edoc_layout_chunks.erl, lib/edoc/src/edoc_refs.erl, lib/edoc/src/edoc_types.erl, lib/edoc/test/eep48_SUITE.erl, lib/edoc/test/eep48_SUITE_data/eep48_links.erl, lib/stdlib/src/shell_docs.erl
* Fix `{@type ... }` macro to work for EEP-48 doc chunks
* Change `@hidden` to mean `hidden` in EEP-48 doc chunks
* Add a EEP-48 to Markdown converter. This means that since we can convert (most) edoc to EEP-48, we now can convert edoc to Markdown.
=> Various edoc fixes and improvements

lib/kernel/src/code_server.erl
Since the code_server state already holds a reference to the code_server table that is meticulously passed around, we can look up the direct reference with `ets:whereis`, rather than passing the name around. ETS operations with a refrence are faster than with the name.
Additionally, for the `code_names` table, we can make it private and unnamed completely, since it's only used directly from the server, there's no access to it from outside the process.
=> Optimise ETS usage in code_server

lib/kernel/src/code_server.erl
The previous implementation would always build
(and reverse) the code paths whenever looking
up a module, even when all paths were cached.
The new implementation uses a map with unique
integers and we only update the cache when
it is stale.
This was a suggestion by @michalmuskala.
=> Produce less garbage on module lookup

lib/kernel/src/code_server.erl, lib/kernel/test/code_SUITE.erl
This address an issue where paths added via -pa/-pz could never be effectively removed.
Closes #6692.
=> Remove erl_prim_loader fallback on module lookup

lib/ssl/src/dtls_record.erl
I guess this seldom has an practical meaning (this code will only be executed with very using very old cryptolibs), but correct should be correct. 
Closes #8079
=> ssl: Correct default value

lib/common_test/src/Makefile, lib/common_test/src/common_test.app.src, lib/common_test/src/cte_track.erl, lib/inets/test/inets.spec, lib/ssh/test/ssh.spec, lib/ssl/test/ssl_gh.spec
- event handling module for tracking CT execution progress
- displays terminal test summary at the end of execution (suitable for reading GH action test run result without HTML)
- in `live`, `live_details` mode of operation also puts summary of not OK results in terminal during execution
- progress data prepared by `cte_track` can also be redirected to a file with `file` option containing a path
- if some test result is not OK, GH action executing OTP tests is typically:
- too big and unreadable
- not displaying any summary at the end
- also sometimes, there is too little info in terminal and having some notification about test progress might be wanted
- provide CT with `cte_track` event handler in any way of your choice
- for GH actions by modifying related test spec, add this: …
=> ct: cte_track event handler

lib/dialyzer/src/dialyzer_cl_parse.erl
Documents the warning flag `unknown`, to be consistent with documenting all warning flags in the `warn_option()` type.
=> dialyzer: document warning flag unknown

lib/kernel/src/group.erl
Elixir (and our documentation) return `{done, eof, []}` and not `{done, eof eof}` when an eof is indicated. `Group` did not handle this and crashed.
=> kernel: Fix group get_until to allow eof only in result

lib/compiler/src/compile.erl
Change the compiler option processing order so that options given in the `compile()` attribute takes precedence over options given to the compiler, which in turn takes precedence over options given in the environment.
This order makes most sense, as each module might need customized options.
Fixes #6979
=> Make options in the `-compile` attribute take precedence

erts/doc/references/erl_nif.md, erts/emulator/beam/code_ix.c, erts/emulator/beam/erl_nif.c, erts/emulator/beam/erl_nif.h, erts/emulator/beam/erl_process.c, erts/emulator/beam/erl_process.h, erts/emulator/test/nif_SUITE.erl, erts/emulator/test/nif_SUITE_data/nif_mod.c, erts/emulator/test/nif_SUITE_data/nif_mod.erl, erts/emulator/test/nif_SUITE_data/nif_mod.h, lib/crypto/c_src/crypto.c
- Add an optional `unload_thread` callback to be called by every scheduler thread in order to release thread specific data when a NIF module is purged.
- Let crypto use `unload_thread` to call OPENSSL_thread_stop() to not leak thread specific data.
- Fix unload-load race to ensure all unload callbacks and dlclose() have returned before we allow reloading the same NIF module again.
=> Various improvements to NIF/crypto upgrade and unload

erts/emulator/beam/erl_bif_port.c, erts/emulator/beam/global.h, erts/emulator/beam/io.c, erts/emulator/sys/unix/sys_drivers.c, erts/emulator/sys/win32/sys.c, erts/emulator/test/binary_SUITE.erl, erts/emulator/test/fun_SUITE.erl, erts/emulator/test/port_SUITE.erl
This PR removes all code related to Vanilla Drivers port creation, add tests to validate that both Atoms and Strings as 1st argument on `open_port/2` should raise badarg error.
The changes in this PR resolves #6725 so that ports could only be used with tuple args and file manipulation as the way vanilla drivers used to do should be accomplished through [File module](https://www.erlang.org/doc/man/file.html)
=> Remove Vanilla Drivers

lib/kernel/src/gen_udp.erl
=> Fix typos in docs for `gen_udp:connect/2,3`

lib/crypto/src/crypto.erl, lib/inets/doc/notes.md, lib/inets/src/http_client/httpc.erl, lib/kernel/src/gen_sctp.erl, lib/mnesia/doc/guides/mnesia_chap4.md, lib/observer/doc/guides/etop_ug.md, lib/odbc/doc/guides/databases.md, lib/ssh/doc/guides/introduction.md, lib/ssh/src/ssh.erl, lib/ssh/src/ssh_client_channel.erl, lib/ssh/src/ssh_client_key_api.erl, lib/ssh/src/ssh_connection.erl, lib/ssh/src/ssh_sftp.erl, lib/ssl/src/ssl.erl, lib/syntax_tools/src/erl_syntax_lib.erl
Bullet lists as the first item in a tag list was incorrectly converted by placing the first item as a header to the tag list.
Also links with [] in the name were properly escaped.
=> otp: Fix links and lists after markdown convertion

lib/tools/src/tprof.erl
The correct column name is `measurement`
=> Fix tprof example (docs)

system/doc/reference_manual/reference_manual.md
Since it's part of `maybe` expressions, its use as an unquoted atom fails to compile on OTP 27.0-rc1 with a default setup.
=> Docs: list 'else' as a reserved word

lib/compiler/src/beam_ssa_alias.erl, lib/compiler/src/beam_ssa_ss.erl, lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Even if we don't know anything about the callee, we can skip marking
arguments as aliased, if they are killed by the call - since we'll
never use them again. This allows the optimisation to apply in
many more cases.
Closes #8106
=> Make alias analysis less conservative with calls

lib/compiler/src/beam_ssa_destructive_update.erl, lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_checks.erl
This patch fixes bugs in the destructive update pass where it crashed when nested updates of a tuple and/or a tuple embedded in a pair occurred.
Closes #8124
=> compiler: Handle nested tuple updates in destructive update pass

erts/preloaded/src/Makefile
Hi,
When building with the flag '--enable-deterministic-build', I got the following errors:
```
| cd erts/preloaded/src && \                                                                                
|   ERL_TOP=/build/tmp/work/core2-64-poky-linux/erlang/27.0-rc1/git PATH=/build/tmp/work/core2-64-poky-linux/erlang/27.0-rc1/git/bootstrap/bin:"${PATH}" \
|       make opt ERL_COMPILE_WARNINGS_AS_ERRORS=yes                                                         
| make[1]: Entering directory '/build/tmp/work/core2-64-poky-linux/erlang/27.0-rc1/git/erts/preloaded/src'                                                                                                               
| erlc -W  -Werror +debug_info +deterministic -I/build/tmp/work/core2-64-poky-linux/erlang/27.0-rc1/git/lib/kerne …
```
=> Fix deterministic build for preloaded beams

lib/ssh/src/ssh_system_sup.erl
- don't start acceptor nor acceptor_sup for ssh client
=> ssh: do not start acceptor for client

lib/kernel/src/prim_tty.erl, lib/kernel/src/user_drv.erl
If the tty reader or writer crashes for some reason we should log that so that we can debug what has happened.
=> kernel: Log when tty reader/writer crashes

lib/ssl/src/ssl.erl, lib/ssl/src/ssl_gen_statem.erl, lib/ssl/test/ssl_api_SUITE.erl
Gives badarg earlier instead of strange crashes/error messages later.
Closes #8066
=> ssl: Add more guards to api functions

lib/stdlib/src/ets.erl, lib/stdlib/test/ets_SUITE.erl
This implements two optimisations for `ets:foldr` and `ets:foldl` functions.
* Using the new `ets:*_lookup` functions introduced in #6791 cuts the number of ETS operations in half
* Using `ets:whereis` on the table to resolve named table before the loop, speeds up the whole thing for named tables since resolving named tables is expensive on a system with a lot of tables.
This was measured with a simple benchmark:
```elixir
for i <- 1..10000 do
:ets.new(:"tab#{i}", [:named_table])
end
:ets.new(:test, [:named_table])
table = :ets.whereis(:test)
for i <- 1..10000 do
:ets.insert(:test, {i, i})
end
benches = %{
"foldl named" => fn -> :ets.foldl(fn x, acc -> [x | acc] end, [], :test) end,
"foldl ref" => fn -> :ets.foldl(fn x, acc -> [x | acc] end, [], table) end,
"foldr named" => fn -> …
```
=> Optimise ets:fold* functions

lib/crypto/c_src/algorithms.c, lib/crypto/c_src/check_openssl.cocci, lib/crypto/c_src/digest.c, lib/crypto/c_src/openssl_config.h, lib/crypto/doc/guides/algorithm_details.md, lib/crypto/src/crypto.erl, lib/crypto/test/crypto_SUITE.erl
This PR add support for [sm3](https://en.wikipedia.org/wiki/SM3_(hash_function)) hash algo in crypto app.
OpenSSL has supported sm3 since version 1.1.1, released almost 4 years ago.
I would like to get some guidance if the OTP Team would be interested in merging this, and i would like to implement 
**sm4** block cipher and 
**sm2** public key algo also.
=> Add support for sm3 hash algorithm

lib/compiler/src/beam_ssa_ss.erl
The alias analysis pass tracks the structure and aliasing status of values given as arguments and returned from functions. The information is kept in the graph provided by the beam_ssa_ss module and is built when the alias analysis processes instructions constructing terms. When a literal is given as an argument to a function, the graph is extended to have the same structure as if the literal was constructed programmatically.
To handle self-recursive functions which, for example builds a list, there is a cutoff which limits the depth to which the graph is constructed. This allows a fixpoint to be reached without implementing a solver for recurrence equations about the structure of the arguments, but also limits the size of the graph.
This patch corrects an omission in the …
=> compiler: beam_ssa_ss: Enforce cutoff for list literals

system/doc/reference_manual/ref_man_records.md
* Document the restriction about the expression for the default value of a record field.
* Document that record definitions can now be entered in the shell with the same syntax as in Erlang files.
=> Update documentation about records

lib/crypto/c_src/cipher.c, lib/crypto/c_src/openssl_config.h, lib/crypto/doc/guides/algorithm_details.md, lib/crypto/src/crypto.erl, lib/crypto/test/crypto_SUITE.erl
this PR add SM4 implementation according to GB/T 32907-2016. 
ISO accept SM4 in 2021, [Part 3: Block ciphers Amendment 1: SM4](https://www.iso.org/standard/81564.html).
openssl add SM4 support in version 1.1.1.
=> crypto: add support for SM4 block cipher algorithm

system/doc/top/src/otp_man_index.erl
Make the error clearer for when I make the same mistake next time.
=> Make a printout when env is misconfigured

lib/observer/src/ttb.erl
The node options `existing` and `new` is not handled in the code as the type and docs suggests.
=> Fix type and thus docs for ttb

lib/compiler/src/beam_z.erl, lib/compiler/test/bif_SUITE.erl
In rare circumstances, the compiler could do an unsafe rewrite of list matching operations. For example:
[PrevRow | _] = Rows,
[_ | PrevRowT] = PrevRow,
. . .
Provided that the type analysis pass had figured out that `Rows` is always a list of at least two elements, the compiler would essentially rewrite the code to:
[PrevRow | PrevRowT] = Rows,
. . .
Fixes #8187
=> Eliminate an unsafe optimization of list matching

erts/emulator/beam/beam_code.h, erts/emulator/beam/emu/ops.tab, erts/emulator/beam/erl_bif_coverage.c, erts/emulator/beam/jit/arm/beam_asm_module.cpp, erts/emulator/beam/jit/arm/ops.tab, erts/emulator/beam/jit/asm_load.c, erts/emulator/beam/jit/load.h, erts/emulator/beam/jit/x86/beam_asm_module.cpp, erts/emulator/beam/jit/x86/ops.tab, lib/compiler/src/beam_asm.erl, lib/compiler/src/beam_block.erl, lib/compiler/src/beam_disasm.erl, lib/compiler/src/beam_flatten.erl, lib/compiler/src/beam_ssa_codegen.erl, lib/compiler/src/beam_validator.erl, lib/compiler/src/genop.tab, lib/compiler/src/sys_coverage.erl, lib/compiler/src/v3_core.erl, lib/kernel/src/code.erl, lib/kernel/test/code_coverage_SUITE.erl, lib/tools/src/cover.erl, lib/tools/test/cover_SUITE.erl
This pull request fixes the bug reported in #8159.
It also eliminates a weird behavior when there are multiple functions on the same line. Consider this module:
-module(foo).
-export([bar/0, baz/0]).
bar() -> ok. baz() -> not_ok.
In Erlang/OTP 26, analysing on the line level would return two entries for line 4:
1> cover:compile_module(foo).
{ok,foo}
2> foo:bar().
ok
3> cover:analyse(foo, coverage, line).
{ok,[{{foo,4},{1,0}},{{foo,4},{0,1}}]}
4> cover:analyse(foo, calls, line).
{ok,[{{foo,4},1},{{foo,4},0}]}
This has been changed to coalesce all information about each line to a single entry in the resulting list:
1> cover:compile_module(foo).
{ok,foo}
2> foo:bar().
ok
3> cover:analyse(foo, coverage, line).
{ok,[{{foo,4},{1,0}}]}
4> cover:analyse(foo, calls, line).
{ok,[{{foo,4},1}]} …
=> Correct coverage for functions on the same line

lib/compiler/src/beam_doc.erl, lib/compiler/src/compile.erl, lib/compiler/test/beam_doc_SUITE.erl, lib/compiler/test/beam_doc_SUITE_data/no_doc_attributes.erl, lib/compiler/test/beam_doc_SUITE_data/user_defined_type.erl
If a module does not have any -doc attributes, it is not clear if we use EEP-59 or not in the system. So for edoc_*_chunks to work properly we should not emit any doc chunk as otherwise anyone using edoc will always have to pass no_docs to the compiler.
This was discovered while working on getting [rebar3_ex_doc](https://github.com/starbelly/rebar3_ex_doc/pull/83) to work with Erlang/OTP 27.
=> compiler: Do not emit doc chunk if no -doc features are used

lib/compiler/src/beam_types.erl
This fixes a function clause error when using `beam_disasm:file/1` on a beam file with a type table version 2 from OTP 27:
```erl
> beam_disasm:file("./erts/ebin/erlang.beam").
{error,beam_disasm,
{internal,{function_clause,[{beam_types,convert_ext_26,
[<<>>,<<15,255,0,1,0,32,16,32,0,0,0,0,0,0,0,2,...>>],
[{file,"beam_types.erl"},{line,1488}]},
{beam_disasm,beam_disasm_types,1,
[{file,"beam_disasm.erl"},{line,271}]},
{beam_disasm,process_chunks,1,
[{file,"beam_disasm.erl"},{line,197}]},
{beam_disasm,file,1,[{file,"beam_disasm.erl"},{line,176}]},
{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,907}]},
{shell,exprs,7,[{file,"shell.erl"},{line,1656}]},
{shell,eval_exprs,7,[{file,"shell.erl"},{line,1612}]},
{shell,eval_loop,4,[{file,"shell.erl"},{line,1597}]}]}}}
```
=> beam_types: Add base case for convert_ext_26/2 recursion

erts/doc/references/erl_driver.md, erts/doc/references/erl_nif.md, lib/erl_interface/doc/references/ei.md, lib/erl_interface/doc/references/ei_connect.md, lib/erl_interface/doc/references/ei_global.md
The since versions in C APIs was lost when translating from XML. This commit re-adds it.
=> erts,ei: Add since versions to C apis

erts/configure, erts/configure.ac
5c9581eb409f5e disabled the JIT on Intel Macs because of annoying popups on macOS Sonoma. The previous major version, macOS Ventura, does not have the popup problem. Therefore, this commit makes it possible to explicitly enable the JIT for Intel Macs. Here is how:
./configure --enable-jit
=> Allow explicit enabling the JIT on Intel Macs

lib/stdlib/src/supervisor.erl
Prompted by [discussions on the Erlang Forum](https://erlangforums.com/t/args-in-gen-init-1/3169), I took a look at the `supervisor` documentation and found some ways to improve it (or so I hope). However, this PR does not really improve the issue that lead to the confusion as discussed in the linked Forum post, as the roots for this lie deeper.
I'll put some more inline comments on what I did any why.
=> Improve `supervisor` specs and docs

lib/compiler/src/beam_ssa.erl, lib/compiler/src/beam_ssa_bool.erl, lib/compiler/src/beam_ssa_opt.erl
The code for nested record access is hugely expanded by the `erl_expand_records` pass, which can cause the `beam_ssa_opt:cse/1` pass to become really slow. To a lesser extent, the `beam_ssa_bool` pass can also get slower.
This pull request tries to mitigate the issue like so:
* The `beam_ssa_bool` and `beam_ssa_opt:cse/1` passes will now evaluate guard BIFs with literal arguments. That will save compilation time by quickly discarding unreachable blocks.
* In `beam_ssa_opt:cse/1`, the handling of the maps that keep track of expressions previously has been optimized.
Closes #8203
=> Mitigate slow compilation for nested record access in guards

lib/stdlib/src/erl_expand_records.erl, lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_expand_records_SUITE.erl
=> Eliminate crash for nested guards in record initialization

erts/doc/guides/time_correction.md
Except in this particular section, the functions are being referenced as module:function/arity.
=> Update time_correction.md to match function reference styles

lib/compiler/src/beam_ssa_codegen.erl, lib/compiler/src/beam_ssa_opt.erl, lib/compiler/src/beam_ssa_type.erl, lib/compiler/test/bs_match_SUITE.erl
Consider this module:
-module(test).
-export([test/1]).
test(Bin) when is_binary(Bin) ->
test1(Bin).
test1(<<_, Rest/binary>>) -> test1(Rest);
test1(<<>>) -> ok.
The only way the first clause of `test1/1` can fail is when the input binary is empty. Therefore, testing for an empty binary in the second clause is redundant. The compiler still generates a test for an empty binary and code to raise a `function_clause` exception if the binary is not empty. Because an exception can be raised, the compiler also needs to insert a book-keeping instruction (`bs_set_position`) into the code for the first clause. That extra instruction has a measurable impact on performance.
This commit eliminates the test for an empty binary and the extra `bs_set_position` instruction when it is safe to do so.
Thanks …
=> Eliminate redundant test for empty binary

lib/tools/doc/guides/erlang_mode_chapter.md
Since OTP 25, the erlang installer's default folder changed from 'erl-<Vsn>'  to 'Erlang OTP'
=> Update 'Setup on Windows' in erlang_mode_chapter.md

lib/tools/emacs/erlang.el
Replace old and broken rules for align.el with stuff that actually works. Map C-c a to align-current.
=> Define proper rules for align.el in erlang-mode

lib/compiler/src/beam_ssa_opt.erl, lib/compiler/src/beam_ssa_type.erl, lib/compiler/test/bs_match_SUITE.erl
Consider:
f(<<_:8>>) ->
ok;
f(A) ->
try
<< (ok) || <<_:ok>> <= A>>
after
ok
end.
The type analysis pass would falsely assume that the binary generator `A` would always fail, which would cause the generation of unsafe code.
=> Make type pass realize that optimization is safe

lib/runtime_tools/src/appmon_info.erl, lib/runtime_tools/src/observer_backend.erl, lib/stdlib/src/c.erl
Don't crash when a list is not a string, but a list of terms.
=> Handle process_labels set as list of terms

.gitignore, erts/emulator/beam/jit/arm/instr_bs.cpp, erts/emulator/test/Makefile, erts/emulator/test/bs_construct_SUITE.erl, erts/emulator/test/bs_construct_SUITE_data/otp_24_code_gh_8238.S, erts/emulator/test/bs_construct_SUITE_data/otp_24_code_gh_8238.erl
This pull request eliminates the crash introduced in OTP-26.2.3 on AArch64 when running code compiled for OTP 24. It also fixes another bit syntax bug that I found when I extended the test suite.
=> Fix two bit syntax bugs when running OTP-24 compiled code with the AArch64 JIT

lib/compiler/src/beam_ssa_pp.erl, lib/compiler/src/beam_types.erl, lib/compiler/test/beam_block_SUITE.erl, lib/compiler/test/beam_type_SUITE.erl, lib/compiler/test/beam_validator_SUITE.erl, lib/compiler/test/compilation_SUITE.erl, lib/compiler/test/compilation_SUITE_data/use_nifs.erl, lib/compiler/test/compile_SUITE.erl, lib/compiler/test/guard_SUITE.erl
This pull request extends the test suite for the compiler application to cover more lines. Most of the added tests were found with the help of [erlfuzz](https://github.com/WhatsApp/erlfuzz).
In addition, minor bugs in the pretty-printing of SSA code and the BEAM disassembler were fixed.
=> Improve the coverage of the compiler application

lib/ssh/src/ssh_xfer.erl, lib/ssh/test/ssh_sftp_SUITE.erl
- adds missing list_to_integer conversion upon decoding
- fix version typo
- enhanced tests
- closes #7897
- closes #7895
=> ssh: fix decode uid, gid

erts/emulator/Makefile.in, erts/emulator/beam/erl_db.c, erts/emulator/beam/erl_map.c, erts/emulator/beam/utils.c
When building emulator with several targets, like
`$> make opt debug`
it could sometimes fail with corrupted generated files under `erts/emulator/$TARGET/`
as the result of interleaved output from parallel running make instances.
Store all generated files under the `erts/emulator/$TARGET/$TYPE/$FLAVOR/` specific directories.
=> Fix race bugs in emulator Makefile

lib/ssl/src/ssl_certificate.erl, lib/ssl/src/ssl_handshake.erl, lib/ssl/src/tls_dtls_client_connection.erl, lib/ssl/src/tls_dtls_gen_connection.erl, lib/ssl/src/tls_dtls_server_connection.erl, lib/ssl/src/tls_handshake_1_3.erl, lib/ssl/src/tls_server_connection_1_3.erl
Asn.1 errors was not handled in all places, catch the decoding of the DerCerts.
Also while at it change usage to handle 'combined_cert()' to only decode the certs once, improves performance.
Fixes #8058
=> Handle asn1 decode errors

.github/scripts/pr-comment.js
The PR comment posted by the github action contains some relative links such as [/erlang/otp/blob/master/CONTRIBUTING.md](/erlang/otp/blob/master/CONTRIBUTING.md) that work as expected when viewed from the GitHub interface, but they don't work at all when followed from the triggered email notification.
Making the URLs absolute fixes the issue.
=> Fix pr-comment email links

.github/dockerfiles/Dockerfile.ubuntu-base
While waiting for a new tag of rebar3 we use the main branch as deprecation of code:lib_dir/2 causes the latest tagged release to fail.
=> gh: Use rebar3 main temporarily

lib/debugger/src/dbg_ieval.erl, lib/debugger/test/record_SUITE.erl
=> debugger: Fix incorrect evaluation of nested records in guard

system/doc/top/README.md
- fixes links to "Erlang Programming" and "Programming Erlang" books
=> docs: update book links

lib/crypto/configure, lib/crypto/configure.ac
Fix #8271
* `FIPS_mode_set` does not exists since OpenSSL 3.x
* The configure check with `AC_CHECK_FUNC` for `FIPS_mode_set` succeeds anyway on Linux as compiler accepts implicit declaration (with only a warning) and linker accepts undefined symbols as we build a shared lib.
* Checking for `FIPS_mode_set` was pointless as it was available even for non-fips builds of OpenSSL 1.x
On MacOS however, the check "works" and thereby hinders building Erlang/OTP with `--enabled-fips` for OpenSSL 3.x.
=> crypto: Remove incorrect configure check for FIPS_mode_set

lib/compiler/src/beam_ssa_bool.erl, lib/compiler/src/beam_ssa_opt.erl, lib/compiler/test/beam_ssa_SUITE.erl
This bug was introduced in 9e391fdbb021db44ce6e75f31553e9e07be04017.
Closes #8296
=> Eliminate internal error in `beam_ssa_opt:ssa_opt_tail_phis/1`

erts/emulator/beam/jit/arm/instr_common.cpp, erts/emulator/test/op_SUITE.erl
This bug was introduced in 8cd93d05c32a7fb5d4551d9b0202571a585afac3.
Closes #8325
=> AArch64: Fix test for empty map

lib/stdlib/src/epp.erl, lib/stdlib/src/erl_lint.erl, lib/stdlib/src/shell_default.erl
On a 64-bit computer, a character in a string occupies 8 bytes, while a character in a binary usually occupies a single byte. Save some memory by using binary literals instead of string literals in some modules that have many string literals, such as `erl_lint`.
=> STDLIB: Slightly reduce code size by using binary string literals

erts/doc/src/erlang.xml, erts/emulator/beam/erl_time_sup.c, erts/emulator/beam/sys.h, erts/emulator/sys/win32/sys_time.c
Fixed a more or less harmless bug that caused time correction of Erlang monotonic time to become slightly off on Windows platforms when `QueryPerformanceCounter()` was used as OS monotonic time source.
`erlang:system_info(os_monotonic_time_source)` now also returns information about *used resolution* which not always corresponds to the resolution of the OS monotonic time source.
=> Fix retrieval of OS monotonic time on Windows

lib/kernel/doc/guides/eep48_chapter.md, lib/kernel/src/code.erl
While at it, also polish the EEP 48 chapter that is referenced by `code:get_doc/1`.
As well as polishing the documentation for module `code`, I have also added a new summary section for native coverage.
=> Polish documentation for `code` after ExDoc migration

lib/ssl/src/dtls_packet_demux.erl
If connection get reset twice (in short time), the code could crash.
Fixes #8338
=> Fix dtls crash

lib/crypto/c_src/pbkdf2_hmac.c, lib/crypto/test/crypto_SUITE.erl
This is  rebase of original PR https://github.com/erlang/otp/pull/7770 on top of OTP-24.3.4
PBKDF2 functions are often meant to run for 100s of milliseconds at a time. Previously, they executed on the main schedulers, blocking them, and thus, were unsuitable for their purpose.
Update the function to use a direct call only if the iteration count is less than or equal to 100 [1] and the keylen is less than or equal to 64 [2].
Add a few extra tests for the sha256 variant, and some test cases for various invalid inputs.
[1] Based on `pbkdf2_hmac(sha256, <<"password">>, <<"salt">>, 100, 32)` running in about 75-200 micriseconds on a sampling of various architectures.
[2] 64 bytes is the length of the SHA512 HMAC, the size of the longest currently supported PBKDF2 hash function.
Fix: …
=> Prevent pbkdf2_hmac function from blocking VM schedulers

lib/dialyzer/test/r9c_SUITE_data/results/inets
The spec for `gen_tcp:send/2` was was extended in e19d8556041465.
=> Fix failing r9c_SUITE:inets/1

system/doc/design_principles/sup_princ.md
The operations of starting, restarting and manually terminating children block a supervisor process, which is something to consider when designing children to be used under a `simple_one_for_one` supervisor.
=> Mention blocking supervisor operations in Supervision Principles chapter

lib/kernel/src/inet.erl
Add a way to prevent port number to service name translation. This is done by add the show_ports "option".
OTP-19053
=> [kernel] Improve inet:i/0,1,2

lib/ssl/src/dtls_client_connection.erl, lib/ssl/src/dtls_gen_connection.erl, lib/ssl/src/dtls_packet_demux.erl, lib/ssl/src/dtls_server_connection.erl, lib/ssl/src/dtls_socket.erl, lib/ssl/src/ssl.erl, lib/ssl/test/tls_api_SUITE.erl
DSA is not available on OpenBSD, which causes the testcase to fail, so use ECDSA certs instead.
=> Fix failing test

lib/common_test/src/cte_track.erl, lib/public_key/src/pubkey_ocsp.erl, lib/public_key/src/public_key.erl, lib/public_key/test/public_key_SUITE.erl, lib/ssl/src/ssl_trace.erl, lib/ssl/src/tls_client_connection.erl
- don't include get_acceptable_response_types_extn
- ClientHello StatusRequest will have empty extensions unless OCSP nonce is requested
- see GH-8242
=> public_key: adjustments for OCSP interoperability

lib/kernel/src/inet_res.erl
Fixes #8303, as suggested by @Maria-12648430.
[Section 3.1.3](https://datatracker.ietf.org/doc/html/rfc8906#section-3.1.3) of [RFC 8906](https://datatracker.ietf.org/doc/html/rfc8906) suggests that DNS servers that do not understand a flag should not copy it to the response. Further, section [3.1.3.1](https://datatracker.ietf.org/doc/html/rfc8906#section-3.1.3.1) suggests that non-recursive servers should respond as if the RD flag was not set.
=> `inet_res`: relax RD flag query/response check

erts/emulator/beam/erl_time_sup.c
=> erts: Fix overflow when calculating monotonic start_offset

erts/lib_src/common/erl_misc_utils.c
=> erts: Read child cgroup instead of root when using cgroup v2

lib/ssl/src/ssl_certificate.erl, lib/ssl/test/ssl_cert_SUITE.erl
Include also end entity cert when selecting issuers for cert_auth extension check
Closes #8356
=> ssl: Fix cert_auth check

lib/xmerl/src/xmerl_sax_parser.erl
remove the function stream/3 which is not used external
=> xmerl: change the export function list

lib/debugger/doc/guides/introduction.md, lib/debugger/src/dbg_ieval.erl, lib/debugger/src/debugger.app.src
The debugger uses tracing in the implementation of `receive`. Run `receive` trace in its own session to avoid disturbing the user's use of tracing.
=> debugger: Run tracing in a separate session

erts/configure, lib/crypto/configure, make/autoconf/otp.m4, make/configure
Closes #8377 
In #8377, Lukas was kind enough to explain to me how to contribute this documentation myself. I added `EX_DOC` to https://github.com/erlang/otp/blob/master/make/autoconf/otp.m4#L85-L130 and ran `./otp_build update_configure --no-commit`. 
I am not very familiar with configuring autoconf, happy to make any changes necessary.
The new documentation,
```
$ ./configure --help
...
Some influential environment variables:
...
EX_DOC      Path to ex_doc executable
...
```
=> Add EX_DOC to m4 influential environment variables

erts/emulator/beam/code_ix.h
`op_i_func_info_IaaI`, and perhaps a few others, indirectly rely on the arity being stored as a word. Since declaring the field as a byte doesn't actually save anything because of tail padding, we'll change it back to `Uint`.
Fixes #8410
=> erts: Change arity type back to Uint

lib/tools/doc/references/erlang.el.md, lib/tools/emacs/erlang.el
Uses C-c C-a for align-current instead of erlang-align-arrows as before. The code for align-arrows is dropped. It was limited to just arrows, and arguably it did the wrong thing across function definitions. Drops the C-c a binding again (was not following Emacs standards). 
Also modernize define-key calls to use the (kbd "...") macro to avoid mistakes in definitions, making M-<tab> bindings work again.
=> Replace erlang-align-arrows with align-current

erts/doc/src/erlang_system_info.md, lib/compiler/src/beam_doc.erl, lib/compiler/src/cerl.erl, lib/stdlib/src/Makefile, lib/stdlib/src/shell_docs.erl, lib/stdlib/src/shell_docs_markdown.erl, lib/stdlib/src/stdlib.app.src, lib/stdlib/test/Makefile, lib/stdlib/test/shell_docs_SUITE.erl, lib/stdlib/test/shell_docs_markdown_SUITE.erl
conversor from markdown to `erlang+html`. `shell_docs` needs documentation in `erlang+html` format, so that it can render the documentation attributes correctly in the shell. documentation attributes are written in markdown and, with this `erlang+html` conversion tool, `shell_docs` can interpret documentation attributes.
=> stdlib: markdown conversor to erlang+html

system/doc/general_info/deprecations_27.md, system/doc/general_info/scheduled_for_removal_28.md
Archives is an experimental feature. Its mere presence makes its hard or impossible to improve the time for starting `erl`.
Warn for the removal of archives for the purpose of holding a single application and including those archives in the code path.
Using a single archive in an Escript is **not** deprecated.
=> archives: Formally deprecate and schedule for removal

lib/dialyzer/src/dialyzer_dataflow.erl, lib/dialyzer/test/small_SUITE_data/src/bs_utf8.erl
=> dialyzer: Fix type inference for UTF-8 segments

lib/kernel/src/application_controller.erl, lib/kernel/src/group.erl, lib/kernel/src/group_history.erl, lib/kernel/src/kernel.app.src, lib/kernel/test/application_SUITE.erl, lib/kernel/test/application_SUITE_data/deadlock/deadlock.erl, lib/sasl/test/release_handler_SUITE.erl
If a process in an application calls any blocking `application` API call with infinite timeout and is trapping exits, there is a risk that it will deadlock the shutdown of the node. So we update application_controller to respond to calls while terminating so that the caller will crash and the system can be shutdown as it should.
=> Fix potential deadlock during system shutdown

lib/kernel/src/trace.erl, lib/tools/src/tprof.erl, lib/tools/test/tprof_SUITE.erl
This PR is based on #8330 and adds trace session support to tprof.
tprof now has one global server that uses a single trace session and the temporary servers used by `tprof:profile` create their own sessions, thus allowing the global server and ad-hoc profiling to be used together.
I have not fixed the tprof API to allow running multiple named servers as I don't think it is very likely that it will be used like that.
=> Update tprof to use trace sessions

erts/emulator/test/trace_session_SUITE.erl, lib/kernel/src/trace.erl, lib/observer/src/etop.erl, lib/observer/src/etop_defs.hrl, lib/observer/src/etop_tr.erl, lib/observer/src/observer.app.src, lib/runtime_tools/src/dbg.erl, lib/runtime_tools/src/runtime_tools.app.src, lib/runtime_tools/test/dbg_SUITE.erl
This PR moves all `dbg` functionality to use a trace session instead of relying on the global session.
In addition it also adds a a new `dbg:session/1,2` API that can be used to create new `dbg` session that are isolated from eachother.
As a proof of concept the `etop` application has been converted to use the new sessions so that it now is possible to run multiple `etop` and `dbg` at the same time in a system without them interfeering with eachother.
=> Migrate dbg and etop to use trace sessions

lib/kernel/src/prim_tty.erl
On OSs with old libc, the wcwidth will return -1 for most/all emoji characters even if they are known to be wide characters. So we add a check that if -1 is returned for something that is known to be wide, we return 2 in size instead of 0.
=> kernel: Fix broken wcwidth for wide chars

lib/compiler/src/cerl.erl
Set the since version for all map functions in module `cerl` to OTP 17, which is the release in which maps were introduced.
=> cerl: Fix since versions

HOWTO/DOCUMENTATION.md, HOWTO/INSTALL.md, lib/wx/api_gen/README, lib/wx/doc/guides/chapter.md, lib/wx/doc/notes.md, lib/wx/examples/demo/demo.erl, lib/wx/examples/demo/ex_button.erl, lib/wx/examples/demo/ex_notificationMessage.erl, lib/wx/examples/demo/ex_webview.erl, lib/wx/examples/simple/menu.erl, lib/wx/examples/simple/minimal.erl, lib/wx/src/wx.erl
wxErlang was the old name for the `wx` application. In most places in Erlang/OTP, it is called Wx or `wx`.
=> howtos: Change wxErlang to Wx

lib/xmerl/doc/examples/xmerl_test.erl, lib/xmerl/include/xmerl.hrl, lib/xmerl/src/xmerl_sax_parser.erl, lib/xmerl/src/xmerl_sax_parser.hrl, lib/xmerl/src/xmerl_scan.erl, lib/xmerl/test/xmerl_SUITE.erl, lib/xmerl/test/xmerl_sax_SUITE.erl, lib/xmerl/test/xmerl_sax_std_SUITE.erl, lib/xmerl/test/xmerl_std_SUITE.erl
The default values in xmerl permitted XXE vulnerabilities and are therefore changed to more restrictive ones.
- xmerl_scan: default value for allow_entities is now 'false'
- xmerl_sax_parser: default value for external_entities is now 'none'
=> Xmerl: Changed default values to disable XXE vulnerabilities

lib/mnesia/doc/guides/mnesia_app_a.md, lib/mnesia/doc/guides/mnesia_app_b.md, lib/mnesia/doc/guides/mnesia_app_c.md, lib/mnesia/doc/guides/mnesia_chap2.md, lib/mnesia/doc/guides/mnesia_chap3.md, lib/mnesia/doc/guides/mnesia_chap4.md, lib/mnesia/doc/guides/mnesia_chap5.md, lib/mnesia/doc/guides/mnesia_chap7.md, lib/mnesia/src/mnesia.erl
This PR updates the mnesia documentation (specifically the user's guide) to:
- Remove any leading whitespace in code blocks (both on top and on the left) that was not present in the previous documentation. I believe this was added accidentally during conversion from XML due to the indent.
- Do not link to the deprecated `mnesia_registry` module in "see also"
- Ensure any references to functions are wrapped in code blocks
- Be more consistent with whitespace in code examples
=> Fix small inconsistencies in mnesia documentation after documentation move

lib/edoc/test/edoc_SUITE.erl
xmerl is no longer using edoc for documentation and is therefore removed as test data for edoc.
=> Remove usage of xmerl as test data for edoc

lib/inets/doc/docs.exs, lib/inets/doc/guides/http_client.md, lib/inets/doc/guides/http_server.md, lib/inets/doc/guides/inets_services.md, lib/inets/src/http_client/httpc.erl, lib/inets/src/http_lib/http_uri.erl, lib/inets/src/http_server/httpd.erl, lib/inets/src/http_server/httpd_socket.erl, lib/inets/src/http_server/httpd_util.erl, lib/inets/src/http_server/mod_alias.erl, lib/inets/src/http_server/mod_auth.erl, lib/inets/src/http_server/mod_esi.erl, lib/inets/src/http_server/mod_security.erl, lib/inets/src/inets_app/inets.erl
This PR:
- removes whitespace from codeblocks in the User's Guide, similar to 70789d145fe9
- adjust whitespace in codeblocks to be more consistent
- use line continuation character from newer Erlang shells in interactive examples
- removes function specifications from the first line of function docstrings
- fixes documentation build warnings due to broken links to `gen_tcp`
- use more readable section headers (shorten them, match their casing to the rest of the sidebar, remove "See also" from the table of contents on the sidebar)
- group modules on the sidebar based on their functionality
and adds the `ipfamily` to the result of `httpd:info`, which is returned when testing this locally.
---
I saw that the deadline for OTP 27 is tomorrow, so if you want to have this in the release but spot …
=> inets: Implement fixes and small improvements for new documentation

lib/ssl/src/ssl_gen_statem.erl
The current generation of process labels from the given `Host` breaks the ability to use local sockets (as can be easily seen from how I fixed it), specifically in `ssl:connect`. While the ability to use local sockets is not officially supported and poses a rare edge case, I see no reason not to keep supporting it ATM, certainly not for the reason of generating a label.
This PR also improves the label generated for IPv6 addresses. In the current implementation, it would be generated as a string of dot-separated decimals ("IPv4-style"), instead of as a string of colon-separated hexadecimals (the usual representation of IPv6 addresses).
=> `ssl`: Fix creation of process labels

lib/common_test/doc/guides/basics_chapter.md, lib/common_test/doc/guides/config_file_chapter.md, lib/common_test/doc/guides/cover_chapter.md, lib/common_test/doc/guides/ct_hooks_chapter.md, lib/common_test/doc/guides/ct_master_chapter.md, lib/common_test/doc/guides/dependencies_chapter.md, lib/common_test/doc/guides/event_handler_chapter.md, lib/common_test/doc/guides/example_chapter.md, lib/common_test/doc/guides/getting_started_chapter.md, lib/common_test/doc/guides/run_test_chapter.md, lib/common_test/doc/guides/write_test_chapter.md, lib/common_test/src/ct_cover.erl, lib/common_test/src/ct_ftp.erl, lib/common_test/src/ct_master.erl, lib/common_test/src/ct_property_test.erl, lib/common_test/src/ct_rpc.erl, lib/common_test/src/ct_snmp.erl, lib/common_test/src/ct_ssh.erl, lib/common_test/src/ct_telnet.erl, lib/common_test/src/ct_testspec.erl, lib/common_test/src/unix_telnet.erl
This PR removes whitespace from codeblocks in the User's Guide (as with 70789d1 & 495b045) and removes redundant function signatures from docstrings.
=> ct: Implement fixes for new documentation

lib/ssh/src/ssh_connection.erl, lib/ssh/test/ssh_connection_SUITE.erl
=> ssh: auto adjust window in client

lib/diameter/src/base/diameter_traffic.erl, lib/diameter/test/diameter_traffic_SUITE.erl
In case of requests in the format of #diameter_packet{}, pick_peer functionality is working incorrectly as the current implementation cannot find Destination-Host in the request. Added a clause to handle #diameter_packet.
=> diameter: modify diameter_traffic:pick_peer/4 to be able to handle requests of type: #diameter_packet{}

lib/ssl/src/ssl_certificate.erl, lib/ssl/src/ssl_handshake.erl, lib/ssl/test/ssl_cert_SUITE.erl
Make it easier to distinguish between a invalid signature and unsupported signature
Closes #8466
=> ssl: Enhance alert handling

lib/kernel/src/prim_tty.erl
The reader updates the Unicode state right before checking the input's encoding, but the assertion that encoding errors are only possible when using utf8 was done against the original state.
Sorry for not writing any test cases, but this is a trivial bugfix for a hard to reproduce race condition.
=> Fix assertion in prim_tty

erts/etc/common/erlexec.c
We cut the arguments to man at the first --
so that things in ERL_ZFLAGS don't end up as
arguments to man.
closes #8477
=> erts: Fix erl -man lookup

erts/emulator/beam/jit/arm/beam_asm_global.cpp, erts/emulator/beam/jit/arm/beam_asm_module.cpp
Hi, this PR changed some designated initializers back to list initializers (available from C++11) as designated initializers are available from C++20, [aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization); and we're requiring C++17 as the minimum when compiling for Windows.
https://github.com/erlang/otp/blob/40568b0d940be77a93d3a3b00cf9d7134cde0dc4/erts/etc/win32/wsl_tools/vc/cc.sh#L192
It didn't cause compile-time errors for i386/x86_64 Windows as these lines are intended for ARM64 JIT (and currently that's Linux and macOS only). Attempt to compile these lines using msvc for ARM64 targets will yield the following errors:
```
CXX    obj/win32/opt/jit/beam_asm_global.o
beam\jit\arm\beam_asm_global.cpp(77): error C7555: use of designated …
```
=> use C++11 list initializers

system/doc/reference_manual/macros.md
Explicitly mention that ?OTP_RELEASE returns the release running the compiler.
=> Clarify what the pre-defined macros return

lib/ssl/src/tls_record.erl
Will make TLS-1.3 work with fips
=> ssl: Support check should check minimum support

lib/stdlib/src/maps.erl
Previously, we were wrapping the combiner function without an actual need. We also use this opportunity to remove an unused argument.
=> Optimize maps:merge_with/3 for maps of equal size

lib/odbc/doc/guides/getting_started.md, lib/odbc/doc/guides/introduction.md, lib/odbc/src/odbc.erl
=> odbc: polish docs

lib/ssh/test/ssh_connection_SUITE.erl
- verify logger events generated during execution
=> ssh: refactor ssh_connection_SUITE

erts/emulator/beam/erl_process.c
Trivial PR, just removing dead code in erl_process.c
=> Remove dead macro ERTS_FOREACH_OP_RUNQ

lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
Given a module such as this:
-module(test).
-export([pattern/1]).
pattern(#{foo => bar}) -> ok.
We presently report an error as:
test.erl:4:15: illegal pattern
%    4| pattern(#{foo => bar}) -> ok.
%     |               ^
Since we have information in `erl_lint` on the bad pattern being a map field update, we can be a bit more helpful by extending the error with a hint instructing the user that `:=` is most likely wanted instead:
test.erl:4:15: illegal pattern, did you mean to use `:=`?
%    4| pattern(#{foo => bar}) -> ok.
%     |               ^
=> Improve illegal pattern error for accidental map associations

erts/emulator/test/float_SUITE_data/fp_drv.c, erts/emulator/test/port_SUITE_data/dead_port.c, erts/emulator/test/signal_SUITE_data/unlink_signal_drv.c
Hi,
When building Erlang/OTP 27 with GCC 14.1.0, I got some compilations errors.
Thanks.
=> Fix errors for gcc 14

lib/xmerl/src/xmerl_sax_parser.erl, lib/xmerl/test/xmerl_sax_SUITE.erl
Add missing error return type resulted from file:open.
=> Fix xmerl_sax_parser:file/2 spec

lib/compiler/src/cerl.erl
Adds two missing closing quotes in `lib/compiler/src/cerl.erl` docstrings (which were causing problems for the Emacs mode's fontification of the file)
=> Add closing quotes in cerl.erl docstrings

lib/compiler/src/beam_ssa_destructive_update.erl
121c858342e44405d08bd030a3967388e2b02a01 should be reviewed by @bjorng as the original author.
=> Correct some errors in compiler source comments

lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
Singleton type variables in an union type do not make sense from Dialyzer's point of view. The following example is ill-typed:
```erlang
-spec run_test(Opts) -> term()
when Opts :: {join_specs, Bool} | {test, Bool}.
```
But this cannot be ever checked by Dialyzer as the type variable `Bool` is in a union and used a single time. Dialyzer cannot check that the `Bool` set of values passed to `join_specs` will be the same set of values as the ones passed in the `Bool` type variable in the `test` branch. Thus, an error follows.
=> stdlib: turn singleton type var warning into error

erts/emulator/beam/export.c
=> Remove locking in export_table_sz() during crash dump

lib/kernel/src/erl_erts_errors.erl
=> Fix `is_process_alive` error message for non-local pids

lib/tools/src/tprof.erl
It is possible that `code:all_loaded()` returns modules that are unloaded right before `trace:info` is made. Skip such modules when collecting trace.
Fixes #8483
=> [tprof] Skip just unloaded modules

lib/tools/src/tprof.erl, lib/tools/test/tprof_SUITE.erl
When running in server mode and profiling all, the function pause/restart/continue would crash as they received the atom 'all' as an interator.
closes #8472
=> fprof: Fix crash when using pause/restart/continue when profiling all

lib/edoc/doc/notes.md, lib/edoc/src/edoc_doclet_markdown.erl, system/doc/reference_manual/documentation.md
This PR fixes the below warning during doc generation:
```   
warning: documentation references "e:system/documentation.md" but it is invalid
└─ notes.md: (file)
```
This also includes some Markdown and indentation issues as well.
=> Fix invalid link in edoc notes and Markdown

lib/tools/src/fprof.erl
I'm not sure how to save the "options" part. Simply removing the "s" from "adds" and "makes" seems reasonable, but the following sentence refers to "the option" in singular. But I'm not too happy with the parenthesis either.
=> fprof: Fix documentation typos

lib/stdlib/src/string.erl
I think reordering the paragraphs like this is better. The example concerns the usage of the `jaro_similarity` function, not how the distance value can be calculated from the similarity value.
=> Clarify docs for `string:jaro_similarity/2`

.github/dockerfiles/Dockerfile.ubuntu-base, .github/workflows/main.yaml
This change allows running full `otp_build_check` in docker dev environment, without this you need to do `otp_build_check --no-format-check` (or install clang-format yourself).
I think this is fine to do, it depends on following packages (showing only clang related):
- clang-format-10
- libclang-cpp10
So full clang binaries are not installed, @garazdawi can I do that?
=> Add clang-format to build tools

lib/compiler/src/beam_ssa_type.erl
In #8564, Frej Drejhammar noticed that the following comment was misleading:
%% One or more arguments have been simplified to literal values.
It turns out that the entire clause in which the comment is located is not needed. Removing the `arg_types` annotation is unnecessary, since it will be added back in the next iteration of the `beam_ssa_type` pass.
This commit removes the unnecessary clause, as well as strengthening and explaining the invariants maintained by `opt_anno_types/2`.
=> Refactor type annotation handling for clarity

erts/emulator/beam/break.c, erts/emulator/beam/erl_process.c
=> Remove locking in erts_schedulers_state() during crash dump

erts/emulator/beam/break.c, erts/emulator/beam/erl_db.c, erts/emulator/beam/erl_db.h, erts/emulator/beam/erl_db_catree.c, erts/emulator/beam/erl_db_catree.h, erts/emulator/beam/erl_db_hash.c, erts/emulator/beam/erl_db_hash.h, erts/emulator/beam/erl_db_tree.c, erts/emulator/beam/erl_db_tree_util.h, erts/emulator/beam/erl_db_util.c, erts/emulator/beam/erl_db_util.h, erts/emulator/beam/erl_flxctr.c, erts/emulator/beam/erl_flxctr.h, erts/emulator/beam/erl_init.c, erts/emulator/beam/erl_node_tables.c
Fix #8198
The PR also includes a commit that introduces C99 type `bool` with values `true` and `false` in the ETS code base.
=> Lift 32-bit limit of ETS hash table size limit

lib/ssl/src/tls_server_connection_1_3.erl, lib/ssl/test/ssl_api_SUITE.erl
Options supplied based on SNI did not properly override listen options for TLS-1.3 connections.
=> ssl: Correct Option handling in TLS-1.3

.gitignore, erts/configure, erts/configure.ac, lib/common_test/doc/Makefile, lib/tftp/src/tftp.erl, make/doc.mk, make/ex_doc.exs, make/ex_doc_wrapper, make/ex_doc_wrapper.in, system/doc/top/.gitignore
This PR adds a mechanism to scan the stderr output from ex_doc for warnings and if found fail the build.
=> Add warnings as errors for ex_doc

lib/stdlib/src/erl_lint.erl, lib/stdlib/src/erl_stdlib_errors.erl, lib/stdlib/test/erl_lint_SUITE.erl, lib/stdlib/test/erl_lint_SUITE_data/format.erl, lib/stdlib/test/io_SUITE.erl
Fixes #8568.
This PR introduces a new function `erl_lint:check_format_string/2`, where the second argument can be used to decide if the check should be strict (`true`, the default) or relaxed (`false`).
Strict checking, which is the same as in the current implementation, will check and complain about repeated (eg `~ttp`), conflicting (eg `~kKp`) or non-applicable (eg `~kb`) modifiers in formatting sequences. Those do not cause errors, though, so while it is ok for linting to check and warn about them, it will cause wrong error messages.
Relaxed checking omits the above checks and only reports erroneous format sequences (eg `~q`). Relaxed checking is used by `erl_stdlib_errors` to print out error reasons.
=> Fix error messages from `io:format` and related functions

lib/compiler/src/beam_core_to_ssa.erl, lib/compiler/test/warnings_SUITE.erl
The compiler can emit so-called *opportunistic warnings*, which are warnings emitted when the compiler notices something suspicious during optimization or code generation. The trouble with opportunistic warnings is that there is no guarantee that the compiler will notice all kind of suspicious code. For example, the compiler in Erlang/OTP 27 and earlier would not emit any warnings for the following functions:
mm_1(#{}) ->
a;
mm_1(#{first := First}) ->
{b,First}.
mm_2(#{first := First}) ->
{b,First};
mm_2(#{first := First, second := Second}) ->
{c,First,Second}.
Since it is easy to arrange clauses in the wrong order and put the matching for any map before other map patterns, it seems worthwhile to catch at least some of the map patterns that will shadow subsequent patterns.
With this pull …
=> Add opportunistic warnings for shadowed map patterns

erts/emulator/beam/erl_time_sup.c
When *no time warp mode* was enabled, a smaller Erlang monotonic time could be read than a previously read time, i.e., breaking the monotonic property. The runtime system will abort when detecting an issue like this since OTP 24.3.4.17 and OTP 25.0.
=> Fix monotonicity of Erlang monotonic time

erts/emulator/beam/erl_bif_trace.c, erts/emulator/test/trace_session_SUITE.erl
Fix #8614
The meta tracer was the calling process instead of the session tracer.
=> Fix bug in meta tracing with session

erts/emulator/beam/beam_load.c, erts/emulator/beam/erl_message.c
The runtime system could crash when attempting to load obsolete or damaged BEAM files (for example, loading code compiled by Erlang/OTP 23 in Erlang/OTP 27).
=> Survive loading damaged or obsolete BEAM files

lib/compiler/src/beam_ssa_alias.erl, lib/compiler/src/beam_ssa_ss.erl
Cleanups which update the alias analysis pass modules. The changes removes the explicit version argument to `sets:new()` and friends as the maps-based implementation is now the default. They also remove dead code, which brings up the test coverage to 100% for the `beam_ssa_alias` and `beam_ssa_ss modules`. No functional changes.
=> Alias analysis cleanups

lib/compiler/src/beam_ssa_destructive_update.erl, lib/compiler/src/beam_ssa_ss.erl, lib/compiler/test/beam_ssa_check_SUITE.erl, lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl, lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_abort1.erl, lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_abort2.erl, lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_abort3.erl, lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_checks.erl
Fix a bug in the alias analysis pass which led to missed optimization opportunities and improve the destructive update pass to use types in order to avoid unnecessary aborts. More details in the individual commit messages.
=> Use type information to improve destructive update pass

lib/compiler/src/beam_ssa_opt.erl, lib/compiler/test/bs_bincomp_SUITE.erl
The common sub expression (CSE) optimization could cause a call to a guard BIF to be inserted into the middle of a sequence of binary syntax matching instructions, which in turn could cause unsafe `bs_match` (BEAM) instructions to be emitted.
Resolves #8617
=> Fix unsafe code generation for binary matching

erts/emulator/beam/erl_alloc_util.c
When setting modification marker on the `prev` field of a carrier to delete from a pool, we back off and wait for the content of the field to receive expected value if it did not have that from the beginning. Due to a copy-paste bug; when this happened, we waited on a completely different memory location which caused the scheduler thread doing this to get stuck forever. This is obviously a very rare scenario, since this bug has been present for 11 years without being reported.
=> Fix cpool_delete()

lib/common_test/src/ct_groups.erl, lib/common_test/src/test_server_ctrl.erl, lib/common_test/test/ct_groups_search_SUITE.erl, lib/common_test/test/ct_misc_1_SUITE.erl, lib/common_test/test/ct_misc_1_SUITE_data/empty_group_SUITE.erl
The logic to trim empty test cases was moved from the find groups function (which will now also return groups with no testcases) to the expand groups function. Groups with no testcases will not be run (e.g. their init_per_group and end_per_group functions will not be called), but no error will be thrown as previously.
Fixes #4362.
=> ct: Allow empty groups in test suites

lib/crypto/src/crypto.app.src, lib/crypto/src/crypto.erl
Fix #8582.
To enable FIPS mode, crypto application config parameter `fips_mode` must be `true`.
However, the application must first be loaded for the config to be accessible when module crypto is invoked.
If application crypto is not loaded, module crypto will use default `fips_mode` as `false` which may come as a surprise if erl was started with command line `-crypto fips_mode true`.
Issue this warning if the underlying OpenSSL lib supports FIPS but the crypto application has not been loaded:
```
=WARNING REPORT==== 17-Jun-2024::17:34:17.238651 ===
Module 'crypto' loaded without application 'crypto' being loaded.
Without application config 'fips_mode' loaded, FIPS mode is disabled by default.
```
=> crypto: Warning if FIPS supported but application 'crypto' not loaded

lib/ssl/src/dtls_handshake.erl, lib/ssl/src/ssl.erl, lib/ssl/src/ssl_handshake.erl, lib/ssl/src/tls_handshake.erl, lib/ssl/src/tls_handshake_1_3.erl, lib/ssl/test/ssl_api_SUITE.erl, lib/ssl/test/ssl_cert_SUITE.erl, lib/ssl/test/ssl_test_lib.erl
Smoother upgrade path, allow certs to still use sha1 but not protocol signatures.
=> Ingela/ssl/default cert sign/gh 8588/otp 19152

lib/ssl/src/ssl.erl, lib/ssl/src/ssl_cipher_format.erl
Doc conversion for OTP-27 caused an internal value to become documented.
=> ssl: Remove documentation of internal value

lib/kernel/src/logger_olp.erl
`logger_otp` would call back to `persistent_term:put` on each iteration even when the mode wouldn't actually change. Even though `persistent_term:put` guards against changing value to the same avoiding the most expensive operations, it still aquires some locks and does potentially other fairly expensive work. We can avoid this with a simple check in `logger_olp` to try and update the value only if it has actually changed.
=> [logger_olp] Avoid repeated calls to persistent_term:put

erts/emulator/beam/erl_alloc_util.c, erts/emulator/beam/erl_alloc_util.h
The number of carriers in a shared pool (`allctr->cpool.stat.no_carriers`) was decremented every time a call to `instrument:allocations` or `instrument:carriers` yielded while traversing the pool.
Also make sure to not free or re-insert a yield cursor (dummy carrier) into shared carrier pool until thread progress has passed.
=> Fix incorrect carrier count statistics after using instrument module

erts/emulator/beam/erl_bif_trace.c, erts/emulator/beam/erl_process.c, erts/emulator/beam/erl_trace.c, erts/emulator/beam/erl_trace.h, erts/emulator/beam/io.c
Fast skip in spawn/open_port if no session is tracing new processes/ports.
=> Optimize process and port creation without tracing

lib/inets/src/http_server/httpd.erl
This PR:
- reformats all configuration properties into codeblocks
- uses proper headings for all categories of settings
- fixes indentation of the record data information
and removes the `ets_table` type in favour of `ets:tid` itself, as it was only used once.
=> inets: Small fixes for httpd documentation

lib/inets/src/http_client/httpc_request.erl, lib/inets/test/httpc_SUITE.erl
According to RFC3986 section-3.2.1, the valid characters for the userinfo component are as follows:
userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )
This does not include the "@" character, which must be percent-encoded when it appears in the userinfo component of a URL.
The Basic authentication scheme, as defined in RFC7617, does not restrict the use of any characters except for the colon (":") character in the user id. The colon should not be percent-encoded, it is just not a valid part of the user id.
When the userinfo component from the URL is converted into a Basic Authorization header, then the string is correctly validated, but is not decoded. This means that the percent-encoded characters end up in the Authorization header, which the servers are expected to interpet …
=> httpc: Fix percent-encoding of userinfo in URLs

lib/ssh/src/ssh_connection_handler.erl
We should start monitoring ConnPid before `gen_statem:cast(ConnPid, socket_control)`. It's possible that ConnPid is closed when handling the `socket_control` cast. If we are unlucky, ConnPid is closed before we start monitoring leading to a `noproc` being returned from the monitor instead of the actual error. 
I had a planned to write a small unit test to test my changes but without meck it will be difficult..
=> ssh: start monitor ConnPid before casting socket_control

erts/doc/references/erlc_cmd.md
* Documentation is [inconsistent with `erlc` arguments](https://www.erlang.org/doc/apps/erts/erlc_cmd.html#generally-useful-flags)
* Made the change `s/WError/Werror/`
```shell
-Werror        make all warnings into errors
```
=> Fixed typo in `erlc` documentation

system/doc/reference_manual/expressions.md
If `a()` would return `-1` as the text says instead of `{ok,-1}`, the conditional match operator at `{ok, A} ?= a()` would fail, not the match operator at `true = A >= 0` as the text says.
=> Fix typo in `maybe` expression documentation

lib/compiler/src/Makefile
Since the module implementing the alias analysis pass was first introduced, its dependencies have been wrongly specified in the makefile.
=> compiler: Fix erroneous makefile dependency

lib/compiler/test/random_code_SUITE.erl
The compiler's random_code test suite always fails when running with a debug emulator due to a `timeout_value` exit. A `timeout_value` exit appears to be triggered when a timer is given a timeout that is either miss-formed or out of range. Checking the relevant part of `random_code_SUITE`, it appears that the timeout is calculated in milliseconds, but it is given to `ct:timetrap/1` as a timeout in seconds.
Although not sure about the exact failure mechanism, changing the calculation to produce a timeout in seconds, allows the test-suite to successfully complete both with an `opt` and `debug` build of the emulator.
=> compiler tests: Correct bad timetrap limit

lib/compiler/test/beam_ssa_check_SUITE_data/private_append.erl
Add `transformable34/0` to the exports. Back when (79ca4ba31bc5 "Make alias analysis less conservative with calls") was merged, no one noticed (including me) that the added test was not added to the list of exports, and therefore never actually run.
=> compiler alias analysis: Enable forgotten test case

lib/crypto/src/crypto.erl, lib/public_key/src/public_key.erl, lib/stdlib/src/otp_internal.erl, system/doc/general_info/DEPRECATIONS
OTB: Decided to revert deprecation of crypto and public_key functions using legacy RSA encryption. Reason is that there exists other paddings than rsa-pcks1-padding that can still have valid uses cases, and that rsa-pkcs1-padding use case can be used for offline reasons or with mitigated OpenSSL versions and is then likely secure, we leave it up to the user if they want to trust OpenSSL implementation.
I rephrased the warnings and still recommend against using this functions with rsa-pkcs1-padding, we want to be secure by default and let it be the users responsibility to ensure that if they use the algorithm it will be secure for their setup.
Note that best practices for the web-socket protocol using these functions (and that is the main reason for reverting) explicitly recommends to only …
=> Ingela/crypto/public key/deprecation revert/otp 19163

erts/emulator/beam/erl_fun.c
While the erts_fun_table is protected by a read-write lock, when ensuring a fun, the runtime always acquires a writer lock allowing it to insert if the lookup fails.  This has the undesirable effect of serializing the insertions even in the degenerate case where the fun is already present and the table does not need to be modified.
This change uses a reader lock initially to offer more concurrency in the case where the fun is present, which can be a common case for applications that repeatedly transmit essentially the same fun objects between nodes.  If the lookup fails, the code behaves as it did before and falls back to acquiring a writer lock and doing a lookup and insert as needed.
=> Improve the concurrency of erts_fun_table insertions

erts/preloaded/src/zlib.erl, lib/crypto/src/crypto.erl, lib/ssl/src/ssl.erl
No such function - ```ssl_handshake```. Obviously the intention was to refer to ```handshake```
=> ssl: help message refers to nonexistent function

lib/runtime_tools/src/dbg.erl, lib/runtime_tools/test/dbg_SUITE.erl
dbg uses the new trace sessions and stores them in the main dbg server on the node that's doing the tracing. However, trace sessions are reference-counted NIF resources - this means that when the last reference is GC'ed on the node that owns the resource, the resouce is destroyed.
In case of dbg, this meant that as soon as the first GC happened on the relay process, the session would be destroyed and tracing would silently stop. Furthermore, any subsequent requests to amend trace patterns, etc would fail for the remote nodes with badarg in trace module's functions.
This fixes the issue by making the relay process hold onto the session reference for as long as the process is active. This solves the issue.
The amended test fails before applying this change and succeeds after.
=> Fix dbg for remote nodes

lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
For errors that can easily be caused by typos, we now check distances to possible fixes and suggest it if it is close enough.
Two example error messages (function `baz/1` and variable `State` are defined): 
```
function bar/1 undefined, did you mean baz/1?
variable 'Stat' is unbound, did you mean 'State'?
```
Error types that are extended by this change: `bad_inline`, `undefined_nif`, `bad_nowarn_unused_function`, `undefined_on_load`, `undefined_function`, `undefined_record`, `undefined_field`, `unbound_var`.
=> compiler: Improve error messages with jaro_similarity

lib/public_key/src/pubkey_os_cacerts.erl
Fixes an exception thrown when running "mix setup" on Elixir 1.18.0-dev:
** (EXIT from #PID<0.93.0>) an exception was raised:
** (MatchError) no match of right hand side value:
{:error, {:enotsup, {:unix, :dragonfly}}}
=> Fix pubkey_os_cacerts:load() on DragonFly

erts/etc/win32/nsis/Makefile, erts/etc/win32/nsis/erlang20.nsi, erts/etc/win32/nsis/find_redist.sh
Hi, this PR prepares NSIS scripts for ARM64 windows and adds checks for the new vcredist filename format, [`vcredist.ARCH.exe`](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version).
=> Prepare NSIS scripts for ARM64 Windows

HOWTO/INSTALL.md, otp_build
adds the dependency `shasum` to check the checksum of ex_doc. 
this was necessary because OSX does not come with sha256sum nor sha1sum.
Closes #8656
=> doc: add shasum to check has on OSX

lib/public_key/src/pubkey_os_cacerts.erl
Could return undefined if no files where present.
Fixes #8604
=> Improve error handling

lib/kernel/src/erl_kernel_errors.erl, lib/kernel/test/code_coverage_SUITE.erl
If `code:get_coverage(cover_line_id, Module)` failed, the first argument would be unjustly blamed for the failure, instead of the second argument ("the atom does not refer to a loaded module" or "not loaded with coverage enabled").
=> Fix error information for `code:get_coverage/2`

erts/emulator/beam/erl_process.c
It was clearly wrong (copy of ERTS_EMPTY_RUNQ instead of checking ERTS_IS_RUNQ_EMPTY_***PORTS***_FLAGS), but mercifully it was unused, so let's just remove it rather than fixing it.
=> Remove dead macro ERTS_EMPTY_RUNQ_PORTS

lib/public_key/src/pubkey_cert.erl, lib/public_key/src/public_key.erl, lib/ssl/src/ssl.app.src, lib/ssl/src/ssl.erl, lib/ssl/src/ssl_handshake.erl
Enhance pkix_path_validation/3 callback so user fun can access both the encoded and decoded version of certificates.  Can enhance both efficiency and interoperability, the latter as many encoders make mistakes that there exists workarounds for in the decoder.
=> Ingela/ssl/public key/verify fun 4/otp 19169

make/ex_doc.exs
Submitting so this doesn't get forgotten.
If mermaid is synchronously loaded, a slow load can prevent the sidebar from displaying since it loads async and must wait for mermaid. Instead, load mermaid asynchronously and then call `mermaidLoaded()` when loading is finished. See elixir-lang/ex_doc#1941
Thanks to @vlad-ngn and @Benjamin-Philip for finding/triaging this bug.
Can someone with the toolchain set up test to make sure it works? It works in the Elixir docs, but I haven't tested it for Erlang docs.
=> Load mermaid asynchronously in docs

lib/compiler/src/beam_ssa_opt.erl, lib/compiler/test/beam_ssa_check_SUITE.erl, lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl, lib/compiler/test/beam_ssa_check_SUITE_data/no_reuse_hint.erl
Change the hint from `reuse` to `copy` when reusing clearly will not work.
=> compiler: Do strength reduction of the hint for update_record

lib/kernel/src/code.erl, lib/kernel/src/code_server.erl
`application:load/1` slows down as the number of directories in the code path increases because the call to `code:where_is_file/1` for the '.app' file must scan each directory for the app. The code_server maintains a cache of the contents of directories in the path depending on their `code:cache()` setting since https://github.com/erlang/otp/pull/6729 / https://github.com/erlang/otp/pull/8049. Re-using and updating that cache when searching for '.app' files in `application:load/1` can improve its runtime, especially when loading multiple applications.
~Internally to make this possible I've added a `code_server:where_is_file/1` function that the application_controller uses instead of `code:where_is_file/1`. This re-uses the code_server's existing cache helper functions to find the file and …
=> Use code_server path cache in code:where_is_file/1

lib/stdlib/src/shell_docs_markdown.erl, lib/stdlib/test/shell_docs_markdown_SUITE.erl
fixes the markdown produce by `shell_docs_markdown` which was producing incorrect markdown code for `Text (_Option._) Text`, where the italics (`_`) where not parsed correcly, producing incorrect format.
Closes #8738
=> stdlib: fix markdown parsing within parens

lib/stdlib/src/supervisor.erl
Before restarting a child, a supervisor must check if the restart limit is reached. This adds a penalty to the overall restart time, which should be kept low.
The current implementation does this check by traversing the list of restarts in order to filter out those that have expired. Then it essentially traverses the result list via `length` in order to check if it is over the intensity limit. This behavior is `2*O(n)` (?), with `n` being the number of past restarts within the period.
This PR introduces two optimizations:
* it checks whether the restart limit is reached _while_ it is traversing the restart list in order to remove expired restarts, thereby eliminating the need for an additional traversal via the call to `length`. Depending on the outcome, a restart is either allowed or …
=> Improve supervisor restart calculation

lib/os_mon/src/disksup.erl
HAMMER2 is the default file-system on DragonFly.
Running:
/bin/df -k -t ufs,hammer /
results in empty output (on my DragonFly system), while running:
/bin/df -k -t ufs,hammer,hammer2 /
results in:
Filesystem     1K-blocks     Used     Avail Capacity  Mounted on
dev/da0s1d     697244672 68285248 628959424    10%    /
=> os_mon - include HAMMER2-FS in df(1) for DragonFly

lib/stdlib/src/erl_stdlib_errors.erl
=> erl_stdlib_errors: Fix wonky error description for maps:update/3

lib/kernel/src/net_kernel.erl
Currently specifying multiple instances of `-proto_dist` ignores the flag altogether.
```
$ erl -name foo@::1 -proto_dist inet6_tcp
Erlang/OTP 28 [DEVELOPMENT] [erts-15.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Eshell V15.0.1 (press Ctrl+G to abort, type help(). for help)
(foo@::1)1> sys:get_state(erl_epmd).
{state,#Port<0.4>,62687,foo,inet6}
$ erl -name foo@::1 -proto_dist inet6_tcp -proto_dist inet6_tcp
Erlang/OTP 28 [DEVELOPMENT] [erts-15.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Eshell V15.0.1 (press Ctrl+G to abort, type help(). for help)
(foo@::1)1> sys:get_state(erl_epmd).
{state,#Port<0.4>,62693,foo,inet}
```
=> Respect -proto_dist flag when specified multiple times

lib/tools/src/cover.erl, lib/tools/test/cover_SUITE.erl
On platforms that support native coverage (introduced in Erlang/OTP 27), the `cover` module did not properly handle failed calls to `code:get_coverage/2`. The call to that function will fail if the module in question has been reloaded or unloaded.
For example, if `cover:export/1` was called and a module had been reloaded on a remote node (for example by `meck`), the `cover:export/1` call would never return.
Because the current API for `cover` has no good way to report this kind of error, we will fix the issue by logging the failed call using the `logger` module and otherwise ignore the failure. That implies that there will be no coverage information for modules that have been reloaded. That is compatible with the behavior of `cover` prior to Erlang/OTP 27.
Closes #8691
=> cover: Gracefully handle failures to collect coverage data

lib/stdlib/src/lists.erl
In case there is an interest, I'm proposing this optimization we added to elixir (https://github.com/elixir-lang/elixir/pull/13793), since the implementation and the expected improvement are the same. Feel free to close if you feel it is unnecessary.
This could especially generate important speedups ([1.5~3x](https://github.com/sabiwara/elixir_benches/commit/f5970d7a920784822cc4566a8eebdd9abcc952dd#diff-13fc229dfd6e6808b62ab13c29b0f362a124a8bb85106d4efc2159f527195a6bR60-R84)) for cases where `flatmap` is used as a `filtermap`, like [this](https://github.com/erlang/otp/blob/1afaa459eaae8d51585acc2a363dd2714b98c9c2/lib/stdlib/doc/src/qlc.md?plain=1#L324) or [this](https://github.com/erlang/otp/blob/1afaa459eaae8d51585acc2a363dd2714b98c9c2/lib/observer/src/crashdump_viewer.erl#L2035), but …
=> Optimize lists:flatmap/2 for filtering

lib/sasl/test/release_handler_SUITE.erl
Fixes https://github.com/erlang/otp/pull/8261#issuecomment-2310226879
=> Fix SASL test failing after #8261 was merged

erts/doc/references/erl_cmd.md, erts/doc/references/erlsrv_cmd.md, erts/doc/references/start_erl_cmd.md, lib/snmp/doc/references/snmpc_cmd.md, make/markdown_to_man.escript
While at it, also do a few other cosmetic improvements.
=> Properly render backslashes in man pages

erts/emulator/beam/emu/bs_instrs.tab, erts/emulator/beam/erl_bits.c, erts/emulator/beam/erl_bits.h, erts/emulator/beam/erl_nif.c, erts/emulator/beam/erl_term_hashing.c, erts/emulator/beam/jit/arm/instr_bs.cpp, erts/emulator/beam/jit/beam_jit_common.cpp, erts/emulator/beam/jit/beam_jit_common.hpp, erts/emulator/beam/jit/x86/instr_bs.cpp, erts/emulator/test/bs_construct_SUITE.erl
Refactor and clean up code for the construction of integer segments of dynamic size. See the description of each commit for more details.
=> Refactor the code for bit syntax construction

lib/stdlib/src/supervisor.erl, lib/stdlib/test/supervisor_SUITE.erl
=> stdlib: Do not progress report dynamically started supervisors

erts/emulator/beam/beam_bp.c, erts/emulator/beam/erl_bif_trace.c, erts/emulator/beam/erl_gc.c, erts/emulator/beam/erl_process.h
a1805974f864fe in #8539, a correction for an unsafe in-place update of a record, had the side effect of causing a major (fullsweep) garbage collection when GC has been temporarily disabled and then again enabled. Since many BIFs, such as `term_to_binary/1` and `iolist_to_binary/1`, may temporarily disable GC, this could lead to noticeable performance regressions.
This pull request ensures that it is again possible to do a minor collection when GC is being enabled.
=> Fix performance regression caused by a bug fix

lib/crypto/c_src/algorithms.c, lib/crypto/c_src/crypto.c, lib/crypto/c_src/openssl_config.h, lib/kernel/src/net_kernel.erl
Fix #8562
`crypto` built with `--enable-fips` will work with OpenSSL 3 without fips provider as long as fips mode is not enabled.
=> Crypto with --enable-fips accepts OpenSSL 3 lib without fips provider

lib/kernel/src/group.erl, lib/kernel/test/init_SUITE.erl
Loading of group_history synchornizes with kernel_sup in order to use disk_log. Doing that when in the user process can lead to a deadlock if logger (or anything really) tries to write to standard out at the same time. Normally the deadlock will solve itself when the kernel application is started, but if it should fail to start for some reason user is terminated before it can print anything and logger will print the log messages to standard error instead.
=> kernel: Don't load group history when in noshell mode

lib/kernel/src/group.erl, lib/kernel/src/prim_tty.erl, lib/kernel/test/interactive_shell_SUITE.erl, lib/stdlib/doc/src/stdlib_app.xml
When stdout is used as both a terminal and as the main logging mechanism, redrawing the prompt will cause a lot of ANSI characters to be printed to the log when the prompt is redrawn. So we add this options for systems that have a hard time migrating away. It is only available in Erlang/OTP 26 as a temporary measure as in the long run no system should be using stdout as a logging mechanism and terminal at the same time.
Supersedes #8644
=> kernel: Add possibility to disable prompt redrawing

erts/configure, erts/configure.ac
THP seems to be causing problems on 32-bit and 64-bit ARM hosts.  This change disables the test for THP on everything except 64-bit x86 hosts which are known to work.
=> Disable support for Linux THP on architectures other than amd64

lib/asn1/src/asn1ct.erl
=> asn1: Don't pass on the undec_rest option to the Erlang compiler

lib/stdlib/src/argparse.erl, lib/stdlib/test/argparse_SUITE.erl
When running this script:
```
#!/usr/bin/env escript
main(Args) ->
argparse:run(Args, cli(), #{progname => cmd}).
cli() ->
#{  
commands => #{
"sub-1" => #{
commands => #{
"sub-1-1" => #{
arguments => [#{name => arg}],
help => "Help of sub-1-1 command"
}
},
help => "Help of sub-1 command"
}
},
help => "Help of main command"
}.
```
with these commands:
* ```./cmd```
* ```./cmd sub-1```
* ```./cmd sub-1 sub-1-1```
after _Usage_ section I'm always getting:
```
Help of main command
```
like:
```
$ ./cmd sub-1
error: cmd sub-1: subcommand expected
Usage:
cmd sub-1 {sub-1-1}
Help of main command
Subcommands:
sub-1-1 Help of sub-1-1 command
```
This commit fixes that so sub-commands help is used when possible, like:
```
$ ./cmd sub-1 …
```
=> stdlib: Fix argparse:format_help for sub-commands

erts/emulator/beam/erl_bif_lists.c
Currently appending an empty list to another list causes the left-hand side list to be fully copied. We can skip the append operation when the right-hand side is nil since it shouldn't change the left-hand side list.
It looks like there are historical artifacts in the `++/2` implementation like its behavior on `[] ++ anything` so I'm not sure if I'm missing some context, but I wanted to propose this optimization since it seems needless to allocate for `List ++ []`. What do you think?
=> Add fast-lanes for '++'/2 and '--'/2 on nil arguments

lib/kernel/doc/kernel_app.md, lib/stdlib/doc/stdlib_app.md, lib/stdlib/src/shell_docs.erl, lib/stdlib/test/shell_docs_SUITE.erl
It may be hard to read the documentation rendered over the whole width of the screen.  The kernel configuration parameter is added to override this default behavior.
=> Add parameter to specify documentation width in the shell

erts/emulator/beam/break.c
When going to BREAK mode (by pressing Ctrl-c) and then aborting with dump (by pressing A), the generated `erl_crash.dump` before this change looked like this:
```erlang
=erl_crash_dump:0.5
Thu Sep  5 15:34:20 2024
Slogan: Crash dump requested by userSystem version: Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Taints:
Atoms: 10683
Calling Thread: erts_aux_1
=scheduler:1
…
```
…and after this change…
```erlang
=erl_crash_dump:0.5
Thu Sep  5 15:34:20 2024
Slogan: Crash dump requested by user
System version: Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Taints:
Atoms: 10683
Calling Thread: erts_aux_1
=scheduler:1
…
```
For reference, call dumps with other slogans look like this…
```erlang …
```
=> Add missing newline at the end of the slogan for Ctrl-c A

.github/scripts/sync-github-releases.sh, .github/workflows/upload-windows-zip.yaml, erts/etc/win32/INSTALL.txt
Follow-up on https://github.com/erlang/otp/pull/8729
The workflow can be triggered like this:
```
$ gh workflow run -R wojtekmach/otp upload-windows-zip.yaml -f version=27.0.1
```
Here's an example workflow run: https://github.com/wojtekmach/otp/actions/runs/10738249662
This command can be used to attach zips to already existing releases.
There is one caveat with these zip builds. They have a runtime dependency on vc_redist.exe (https://github.com/erlang/otp/issues/8531). This is not a problem for Windows exe installers as they ship with _that_ and run it as part of the installation. In my personal opinion this is not a deal breaker for Windows zip builds, whoever ends up using them just needs to be aware of this (and/or #8531 is addressed). The tool I'd like to use these Windows zip …
=> gh: Upload Windows build zip to GitHub releases

lib/kernel/src/group.erl, lib/kernel/test/interactive_shell_SUITE.erl, lib/stdlib/src/io.erl, lib/stdlib/src/shell.erl
This addresses the issue found [here](https://erlangforums.com/t/command-history-on-custom-elixir-cli-not-working-with-otp-26-but-was-with-otp-25/3950) and in #6896 by adding way for the shell to toggle whether an I/O 'get' request should be saved in history or not.
@josevalim things should continue work as always for Elixir, but I think it would be a good idea to check just in case. Maybe you want to do what we do and disable saving to history for any `get` commands run from within a shell session.
=> shell: Add more explicit handling of when to save shell history

lib/kernel/src/group.erl, lib/kernel/src/user_drv.erl, lib/kernel/test/interactive_shell_SUITE.erl, lib/stdlib/src/shell.erl
This PR prints a help message when the command in the shell does not complete within 5 seconds telling the user how to interrupt the current job.
=> Print hint for when shell is stuck

lib/stdlib/src/proc_lib.erl, lib/stdlib/test/proc_lib_SUITE.erl
When working with peer in #8537 I got a lot of errors where gen_server:stop would crash with reason `normal` as the peer process terminated with that reason just as gen_server:stop was called. I'm opening this PR to start a discussion to see if we want to make it so that if a process exits with the expected reason, though not was a result of the stop call, we should still consider it a successful shutdown?
=> stdlib: Fix proc_lib:stop when exit reason is expected reason

erts/emulator/beam/external.c, lib/stdlib/test/ets_SUITE.erl
The compression was a bit too good, converting ErlSubBits to ErlHeapBits whenever that resulted in a smaller result, breaking an assumption that ETS compressed tables made (`size_object(original) == size_object(decompressed)`).
This commit fixes it by not being as clever, naively encoding ErlSubBits and the likes as-is regardless of size.
(Edit: the PR currently lacks a test for this bug, but it's late and I want CI to run overnight, I'll add one tomorrow)
=> erts: Fix crash in ETS compressed tables

lib/compiler/src/beam_ssa_destructive_update.erl, lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_checks.erl
The initial value tracker in the destructive update pass could sometimes fail to ensure that a term which was destructively updated was forced onto the heap as it did not have a way to easily follow list tails. This patch corrects that error by ensuring that if the first element of a literal list is forced onto the heap, all elements of the list will be forced onto the heap.
=> compiler destructive update: Patch every element of a list

.github/workflows/main.yaml
Do not create releases on utility tags "patch-base-*".
=> Restrict github action releases on tags named "OTP-*"

erts/emulator/sys/unix/erl_child_setup.c, erts/emulator/sys/unix/sys.c, erts/emulator/sys/unix/sys_drivers.c
If stdout is not a tty, then it might be a program that does its own alterations of the tty which means that we should not touch it and leave restoration to that program.
Closes #8487
=> erts: Require both stdin and stdout to be ttys to restore

lib/public_key/src/public_key.erl
This type of runtime error hiding is not considered something that is part of the API that needs to be backwards compatible. This only hides the real error and does not help prevent bugs. This exceptions occur when input data is not correct and should be clearly reported when it occurs.
=> public_key: Do not hide crypto runtime exceptions

lib/tools/emacs/erlang.el
This adds support for automatically inserting the closing delimiter for triple-quoted string literals in the Emacs mode.
If `erlang-mode` and `electric-pair-mode` are enabled, it works as follows, if `|` is the cursor position and a double quote is inserted.
```
""|  ->  """|"""
```
This is accomplished by adding a function to `post-self-insert-hook` checking whenever `electric-pair-mode` is enabled and a third double quote is inserted, and then inserting three more.  The approach is taken from `python.el`, which has the same feature for Python's triple-quote strings.
=> Emacs: Add electric-pair-mode support for triple-quoted strings

lib/kernel/doc/guides/logger_chapter.md
Digging into the topic of logger overload protection I found it somewhat hard to follow and keep track of what all the systems do on a high level.
It probably doesn't solve this for everything, but I think providing a high level overview of the measures in place can help others to better understand the mechanisms and dive into the one they care the most about.
Thank you all so much for your work :green_heart:
=> Provide an overview of logger overload protection

lib/kernel/doc/guides/logger_chapter.md
Reading the docs my impression was that the reasons mentioned for burst mode protection do only apply to file-based logging or at least the examples only do.
Locking to the console is fairly common in cloud-based environments.
I have deactivated the burst mode protection (that had swallowed about 2/3s of our log messages) and the system is running fine without any impact on CPU or memory that I could spot.
So, this is part me wanting to clarify this in the doc but also part me checking in about my understanding of the interplay of this.
Thank you all so much for your work :green_heart:
=> Clarify burst mode protection and non file based logging

lib/kernel/doc/guides/logger_chapter.md
I think it's very helpful to have this documented, as I had been looking for it and while you can just try and search your logs for `:drop` having the concrete message as an example is helpful (and other people looking into this had asked me about it).
As per usual, thank you for your excellent work! :green_heart: 
edit: I was unsure whether this should go against `maint` or `master` - I decided for the latter but I'm happy to switch it around.
=> Add an example of the log message emitted when going to drop mode

lib/public_key/src/pubkey_cert.erl, lib/public_key/test/public_key_SUITE.erl
=> public_key: Correct argument order

lib/ssl/src/dtls_packet_demux.erl, lib/ssl/src/dtls_socket.erl, lib/ssl/src/inet_tls_dist.erl, lib/ssl/src/ssl.appup.src, lib/ssl/src/ssl.erl, lib/ssl/src/ssl_api.hrl, lib/ssl/src/ssl_gen_statem.erl, lib/ssl/src/ssl_internal.hrl, lib/ssl/src/tls_gen_connection.erl, lib/ssl/src/tls_socket.erl, lib/ssl/test/dtls_api_SUITE.erl, lib/ssl/test/ssl_api_SUITE.erl, lib/ssl/test/ssl_basic_SUITE.erl, lib/ssl/test/ssl_test_lib.erl, lib/ssl/test/tls_api_SUITE.erl
Backwards compatibility of this internal data structure is no longer needed and nowadays only makes it hard to understand the intent of the code. So this is a refactor long overdue.
=> ssl:  Refactor sslsocket to ease maintenance and extension

lib/stdlib/src/calendar.erl, lib/stdlib/test/Makefile, lib/stdlib/test/calendar_prop_SUITE.erl, lib/stdlib/test/property_test/calendar_prop.erl
Far too often I've found myself working with binaries, to then have to convert back and forth from and to lists before I can use the RFC3339 functionality. So I'm adding here support for them.
Some examples only in MongooseIM:
- https://github.com/esl/MongooseIM/blob/9c1cdf8b3e5d6507d67030282958f306271b88fe/src/offline/mod_offline.erl#L519
- https://github.com/esl/MongooseIM/blob/9c1cdf8b3e5d6507d67030282958f306271b88fe/src/mam/mod_mam_utils.erl#L170
---
And a bit of benchmarks, using good old benchee:
TL;DR: list_to_binary/binary_to_list back and forth is usually ~20% slower, all other variations of the old and new code are very similar, if not having a slightly bit better performance.
`old` means code from master, `string` and `binary` are the new versions that handle such types …
=> Introduce binary types to RFC3339 functions

lib/ssl/doc/guides/using_ssl.md
Mostly backticks for correctly rendering code snippets. 🙃
=> Small cosmetic fixes in "Using SSL" docs

erts/doc/references/erl_cmd.md, erts/preloaded/src/init.erl, lib/kernel/doc/kernel_app.md, lib/kernel/src/erl_epmd.erl, lib/kernel/src/net_kernel.erl, lib/observer/src/observer_wx.erl, system/doc/general_info/deprecations_27.md
This introduces `epmd_module` and `erl_epmd_listen_port` parameters for the kernel application. I updated the docs to deprecate `-epmd_module` and `-erl_epmd_port`, similarly to `-connect_all` in https://github.com/erlang/otp/commit/1d0fe6f71c320d2d1d19d9efd6dcba7b18bedca6.
The kernel application already has a lot of parameters related to distribution, so I believe semantically this makes sense.
For context, in [Livebook](https://github.com/livebook-dev/livebook) we started using a custom `epmd_module`. In Escript and Elixir releases, there are ways to set the `-epmd_module` flag, however there is no way to do that in development, other than setting `ERL_AFLAGS` env var. We already start distribution manually using `net_kernel:start/2`, so the idea is that now we could do …
=> Move -epmd_module and -erl_epmd_port into kernel parameters

erts/emulator/beam/erl_nif.c, erts/emulator/test/nif_SUITE.erl, erts/emulator/test/nif_SUITE_data/nif_mod.c, erts/emulator/test/nif_SUITE_data/nif_mod.erl
Affects only non-JIT beam.
Requires exotic case of loading NIF over Erlang function that is already traced by more than one trace session.
Caused beam VM crash.
=> Fix bug in NIF loading of function traced by multiple sessions

erts/etc/win32/wsl_tools/SetupWSLcross.bat
This PR is one of the smaller PRs separated from the original PR https://github.com/erlang/otp/pull/8142 that attempts to add initial support for ARM64 windows. 
In this PR,
- `SetupWSLcross.bat` can also accept either `arm64` or `amd64_arm64` (`x64_arm64`) for its first parameter
`arm64`, `amd64_arm64` and `x64_arm64` are the official values used in the `vcvarsall.bat` script, [vcvarsall syntax](https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#vcvarsall-syntax).
`arm64` means to set up the environment when compiling natively, whereas `amd64_arm64` and `x64_arm64` means to set up the cross-compiling environment on an amd64 host machine for the arm64 target machine.
- Updated relevant lines for setting the path for `cl.exe` 
When cross-compiling, e.g., …
=> added support for search and setup WSL for `[amd64_]arm64`

lib/stdlib/src/supervisor.erl
- handling race between orderly shutdown from supervisor termination + and worker termination
- make sure to report and correct error reason if possible
=> stdlib: supervisor unlink_flush improvement

lib/stdlib/src/re.erl, lib/stdlib/test/re_SUITE.erl
=> Fix behavior of `re:split/3` with `trim` option for empty subjects

lib/stdlib/src/ets.erl
This PR fixes a typo (a missing "is") in the docs for `ets:select_count`. I also removed the sentence which basically reads "like `select_delete` but without deleting", because I think that, while true, it is more confusing than helpful. I also reworded some parts of the description, also for `select_delete`, for better readability (IMO, that is :sweat_smile:).
=> Improve docs for `ets:select_count` and `ets:select_delete`

lib/dialyzer/src/dialyzer_cl.erl
=> dialyzer_cl: Stop printing unknown function/type warnings when suppressed

lib/compiler/src/Makefile, lib/compiler/src/beam_digraph.erl, lib/compiler/src/beam_ssa_alias.erl, lib/compiler/src/beam_ssa_alias_debug.hrl, lib/compiler/src/beam_ssa_check.erl, lib/compiler/src/beam_ssa_destructive_update.erl, lib/compiler/src/beam_ssa_ss.erl, lib/compiler/src/beam_ssa_type.erl, lib/compiler/test/beam_ssa_check_SUITE.erl, lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl, lib/compiler/test/beam_ssa_check_SUITE_data/no_info0.erl, lib/compiler/test/beam_ssa_check_SUITE_data/no_type_info.erl, lib/compiler/test/beam_ssa_check_SUITE_data/phis.erl, lib/compiler/test/beam_ssa_check_SUITE_data/sanity_checks.erl, lib/compiler/test/beam_ssa_check_SUITE_data/ss_depth_limit.erl, lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_checks.erl
This series of patches improves the performance of the alias analysis pass to roughly halve the time required for the analysis when measured by `scripts/diffable`.
The improvement comes from a combination of an improved strategy for deciding on which functions requiring repeated analysis when alias information changes, changes to the aliasing state database to reduce its size but increase its expressiveness, and an adaptive strategy for pruning aliasing state database states.
Outside of the alias analysis pass this PR extends the beam_digraph module with new functions for use by the pass, otherwise its changes are limited to the `beam_ssa_alias` and `beam_ssa_ss` modules. Where, apart from the improvement in performance, it also improves the debuggability by dumping the internal …
=> Speed up alias analysis

erts/emulator/beam/jit/arm/ops.tab, erts/emulator/beam/jit/x86/ops.tab, erts/emulator/test/tuple_SUITE.erl
=> Eliminate unsafe fusion of BEAM instructions

lib/compiler/src/beam_ssa_codegen.erl, lib/compiler/test/record_SUITE.erl
=> beam_ssa_codegen: Ensure that indexes are unique in update_record

Makefile.in, lib/common_test/test_server/configure, lib/common_test/test_server/configure.ac, make/app_targets.mk, make/test_target_script.sh
A few places have the executable name hard-coded to `make`. However, the Makefiles require GNU make, which is might be available as another name. For instance, on *BSD where make(1) is another implementation, GNU make is available ase `gmake`.
This was not a problem when building Erlang/OTP. But it was when running the tests.
The make variable `$(MAKE)` which always contain the name of (or path to) the make executable being used, is passed to the shell scripts. The shell scripts then use this variable, defaulting to `make` if necessary.
In `lib/common_test/test_server/configure.ac`, the order in which the make executable is detected is swapped: `gmake` is tried first, then `make`.
=> Take make(1) executable name from `$MAKE` environment variable

erts/emulator/beam/atom.names, erts/emulator/sys/unix/sys.c, erts/emulator/test/os_signal_SUITE.erl, lib/kernel/doc/kernel_app.md, lib/kernel/src/os.erl
This signal is emitted when the terminal window is resized to allow an application to redraw its content.
This signal is emitted when a user types Ctrl+T in a terminal. This is only supported by few operating systems such as *BSD and OSX.
By default, the operating system displays on stdout the system process PID, the system load and the duration the process is running. The signal allows the application to display more details about its status and progress.
=> Add `SIGWINCH` and `SIGINFO` support

erts/emulator/beam/emu/ops.tab, erts/emulator/beam/jit/arm/ops.tab, erts/emulator/beam/jit/x86/ops.tab, erts/emulator/internal_doc/beam_makeops.md, erts/emulator/utils/beam_makeops
This PR catches issues like #8875 by raising an error for unused variables in transformations.
=> erts: Disallow unused variables in ops.tab

lib/sasl/src/systools.erl
Corrects issue [8842](https://github.com/erlang/otp/issues/8842) by simply changing the order of the tuple elements in type spec for the ExtraFiles option of `sasl:make_tar/2`.
=> sasl: Fix type spec for extrafiles option in make_tar/2

lib/ssh/src/ssh.erl, lib/ssh/src/ssh_acceptor.erl, lib/ssh/src/ssh_app.erl, lib/ssh/src/ssh_connection_handler.erl, lib/ssh/src/ssh_info.erl, lib/ssh/src/ssh_tcpip_forward_acceptor.erl, lib/ssh/test/ssh_connection_SUITE.erl, lib/ssh/test/ssh_protocol_SUITE.erl
Fix for GH-8223 and also append `{active, false}` at the end of socket options.
Server supervision tree improvements are planned to be done in other PR.
=> Kuba/ssh/receive exit fix options construct fix/otp 19246/otp 19247

lib/kernel/src/group.erl, lib/kernel/src/prim_tty.erl, lib/kernel/test/interactive_shell_SUITE.erl
With this change, the stdout data, e.g. io:format/2, will always be drawn at the line before the prompt, triggering a redraw of the prompt. A buffer is kept so that we can track when the output reaches the column length of the tty, so we can put the cursor at the right position when the next stdout message should be drawn.
=> kernel: io to stdout shouldn't interfere with prompt

lib/ssl/src/ssl_cipher.erl, lib/ssl/src/ssl_handshake.erl, lib/ssl/src/tls_handshake.erl, lib/ssl/test/ssl_cert_SUITE.erl, lib/ssl/test/ssl_test_lib.erl, lib/ssl/test/tls_1_3_version_SUITE.erl
Revert back to original implementation for checking of legacy schemes as it was broken by refactor in OTP-26-2.1 and later only partly fixed as the refactor change how the code was interpreted. Now also add explicit test for these algorithms.
=> ssl: Revert checking of legacy schemes

lib/ssl/src/ssl_gen_statem.erl, lib/ssl/src/tls_gen_connection.erl
When making ssl application environment setting alert_timeout, to allow user to configure this value,
the own_alrt timeout handling became broken.
=> ssl: Correct own alert handling

lib/kernel/src/net_kernel.erl, lib/kernel/test/erl_distribution_SUITE.erl
Few changes:
1. `net_kernel:allowed/0` is speced and documented. Notice that it is already listed in "documented API exports", but for some reason docs were missing. I think it's a must to have it documented, because if you don't then the user can't figure out if `net_kernel:allow/1` was called in the past, therefore blocking nodes with the same cookie to connect (which I believe can be very frustrating and and to debug!). This is just a pure getter function, I see no threat exposing it.
2. `net_kernel:allow/1` was missing `ignored` value it can return. You'll get it if e.g. your node is started without (s)name. 
3. 2 small typos in comments
=> `net_kernel:allowed/0`, specs and docs

lib/kernel/src/group.erl, lib/kernel/test/interactive_shell_SUITE.erl, lib/stdlib/src/edlin.erl, lib/stdlib/src/edlin_key.erl
pressing ^[h once, give you 7 lines of help text,
pressing ^[h again, gives you as many lines that fits the current window height
=> stdlib: added key command to shell to improve help

lib/common_test/src/test_server.erl, lib/common_test/src/test_server_ctrl.erl
Fixed a bug where the sum of testcases' execution time in HTML logs is miscalculated.
=> OTP-19284 common_test: time sum fix

lib/ssl/src/tls_handshake.erl
Make sure assertion is on function clause only and not on selected version
closes #8908
=> ssl: Fix version assertion

lib/asn1/src/asn1ct_gen.erl, lib/asn1/test/Makefile, lib/asn1/test/asn1_SUITE.erl, lib/asn1/test/asn1_SUITE_data/SwCDR.asn1config, lib/asn1/test/test_exclusive_decode_rest.erl
Compiling an ASN.1 specification Module using the `+undec_rest` option causes the result of `Module:decode/2` to be `{ok, Value, Rest}`, however when combined with `+asn1config` option to create exclusive decode functions those are not effected by the `+undec_rest` option.
This commit fixes this so exclusive decode functions return the expected result when the `+undec_rest` option is provided.
=> asn1: Fix feature interaction with +undec_rest and +asn1config

lib/stdlib/src/json.erl
Was wrong, the purpose of that function is to take any term.
Fixes #8880
=> Fix spec for json:format/3

lib/stdlib/src/gen_fsm.erl
Missing parenthesis in the type specification for `Event` in `gen_fsm:send_all_state_event/2` had me fighting with `dialyzer` for quite some time.
=> stdlib: fix typo in typespec for gen_fsm:send_all_state_event/2

lib/mnesia/src/mnesia_dumper.erl, lib/mnesia/test/Makefile, lib/mnesia/test/mnesia_SUITE.erl, lib/mnesia/test/mnesia_external_backend_test.erl, lib/mnesia/test/mt.erl
Fix disc_copies table not being saved to disc when converting from ext backend.
Fixes: https://github.com/erlang/otp/issues/8706
=> Michal/mnesia/ext copies to disc copies conversion/otp 19292

erts/emulator/beam/atom.names, erts/emulator/sys/unix/sys.c, erts/emulator/test/os_signal_SUITE.erl, lib/kernel/doc/kernel_app.md, lib/kernel/src/os.erl
This signal is used after `SIGSTOP` or `SIGTSTP` to resume a system process. Shell job control relies on these signals.
=> Add support for `SIGCONT` system signal

lib/tools/src/tprof.erl
`tprof:format(IoDevice, ...)` would fail if `IoDevice` did not support unicode encoding.
Replace printed unicode character "μ" with an ASCII "u".
=> Remove demand of unicode support for tprof:format/2

erts/etc/win32/wsl_tools/vc/cc.sh
cl.exe can return an error code with LNK1561 error. This error is ok as the correct result is still printed, so we reset the RES variable so that cc.sh does not exit with an error reason.
=> erts: Fix cc.sh -MM on wsl 2

lib/os_mon/c_src/memsup.c, lib/os_mon/src/memsup.erl, lib/os_mon/test/memsup_SUITE.erl
Fixes #8759
* Use `available memory` (when available) to calculate how much memory a system has used. 
* Add `available_memory` to `memsup:get_system_memory_data/1` result on Apple.
Fixes are for Linux` and Apple.
=> os_mon: Fix use available mem for system_memory_high_watermark alarm

lib/kernel/src/logger.erl
Fix `logger:report/0` to mandate at least one element in the report. This fixes an issue with overlapping `spec` domains in all `logger` functions that use `logger:report/0`.
=> kernel: Fix logger overlapping domains

erts/emulator/beam/erl_global_literals.c, erts/emulator/sys/common/erl_mmap.c
The ptr given to erts_mem_guard needs to be aligned to a page boundary for memprotect to work. Also we need to unguard the memory before we update the heap_size.
=> erts: Fix global literal to correctly use erts_mem_guard

.github/dockerfiles/Dockerfile.ubuntu-base, .github/workflows/actions-updater.yaml, .github/workflows/main.yaml, lib/jinterface/prebuild.keep
Include a jdk-8 compiled version of jinterface in the prebuild to speed up the build process.
=> Include jinterface in prebuild

lib/asn1/test/asn1_test_lib.erl, lib/compiler/test/test_lib.erl
When running tests for the `asn1` and `compiler` applications on 32-bit systems, limit the number of concurrent processes that the `p_run/2` helper will spawn to a single process. This should make it less likely that virtual address space or memory is exhausted, especially on Windws, where only 2 GB of virtual address space is available.
=> tests: Limit the number of parallel processes on 32-bit systems

lib/eldap/src/eldap.erl
=> eldap: Add missing list indication to tls_start specs

system/doc/reference_manual/features.md
Minor fix in the documentation.
(I submitted this first as part of #8625 but after the decision to not implement EEP 70 as an experimental feature it can be broken out to its own PR.)
=> Update the status of the maybe_expr in the docs to "approved"

erts/emulator/drivers/win32/registry_drv.c
=> win32: Fix crash on zero-sized REG_SZ values

erts/etc/win32/wsl_tools/reg_query.sh, erts/etc/win32/wsl_tools/vc/cc.sh, erts/etc/win32/wsl_tools/vc/emu_cc.sh, make/autoconf/win64-arm64.config.cache.static, make/autoconf/win64-x64_arm64.config.cache.static, otp_build
This PR is one of the smaller PRs separated from the original PR https://github.com/erlang/otp/pull/8142 that attempts to add initial support for ARM64 windows.
I'm open to change `x64_arm64` to any alternative value(s) that can tell us we're cross-compiling. I'm also open to add `amd64_arm64` as an alias for `x64_arm64` if we'd like to make it consistent with Microsoft Visual Studio, please see [vcvarsall](https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#vcvarsall-syntax).
In this PR,
- `echo_env_wsl` now accepts a single argument `ARCH`, which can be one of `x64`, `arm64`, `x64_arm64` and `x86`
- `wsl_tools/vc/cc.sh` will set `LINKCMD="-MACHINE:${MACHINE}"` by default, where the value for `MACHINE` is:
- `x64` when `CONFIG_SUBTYPE` is `win64`
- …
=> added support for `arm64` and `x64_arm64` in `otp_build`

lib/kernel/src/inet_config.erl
Many RabbitMQ users provided atoms instead of strings as the `inetrc` file path because of an error in their documentation. This was tolerated by accident until atom filename support was removed from `erl_prim_loader`.
We did the latter for good reason, but tolerating this specifically in `inet_config` is no big deal.
-------
Fixes #8899. I figured that simply tolerating it was better than raising an error as it's difficult to present it in a way that makes sense, given how this argument is often provided on the command line.
=> inet_config: Tolerate atoms as `inetrc` kernel argument

lib/compiler/src/beam_ssa.erl
beam_ssa:split_blocks/4 does not split and create a new empty block if the predicate returns true for the first instruction in a block. As I have gotten tripped up on this for the second time, the first time was at least a year ago, note this in the function comment.
=> compiler: Note non-obvious behavior of beam_ssa:split_blocks/4

erts/emulator/beam/atom.c, erts/emulator/beam/beam_file.c, erts/emulator/beam/dist.c, erts/emulator/beam/erl_bif_info.c, erts/emulator/beam/erl_global_literals.c, erts/emulator/beam/erl_global_literals.h, erts/emulator/beam/export.c
~~Make the chunk writable before we adjust the 'end' of the area for correct crash dumping.~~
Refactor to let `chunk->area.end` be the end of area filled with literals (like all other `ErtsLiteralArea`), and thereby remove the need to patch the area end at crash dump.
=> Avoid SEGV in crash dump of global literals on debug target

erts/emulator/beam/jit/arm/instr_common.cpp
This PR is one of the smaller PRs separated from the original PR https://github.com/erlang/otp/pull/8142 that attempts to add initial support for ARM64 windows.
This PR fixes the following compiling errors on ARM64 Windows, and I copy-pasted the same lines from `erts/emulator/beam/jit/x86/instr_common.cpp` to here.
```
CXX    obj/win32/opt/jit/instr_common.o
beam\jit\arm\instr_common.cpp(3112): error C2039: 'perf_counter': is not a member of 'erts_sys_time_read_only_data__'
C:\src\erts\emulator\sys\win32\erl_win_sys.h(185): note: see declaration of 'erts_sys_time_read_only_data__'
beam\jit\arm\instr_common.cpp(3112): error C2672: 'BeamModuleAssembler::runtime_call': no matching overloaded function found
C:\src\erts\emulator\beam\jit\arm\beam_asm.hpp(1430): note: could be 'void …
```
=> win32(arm64): call the function pointer used by erts_sys_perf_counter

lib/ssl/src/ssl_gen_statem.erl, lib/ssl/test/ssl_trace_SUITE.erl, lib/ssl/test/tls_api_SUITE.erl
Fix bug  also in older version of  OTP when shutdown happens from the supervisor. 
Solution will be piggybacked on other patches to OTP 26 and 25  eventually.
=> Ingela/ssl/handle terminate alert/otp 19311

lib/kernel/src/code.erl, lib/kernel/src/code_server.erl, lib/kernel/test/code_SUITE.erl
Prior to this patch, the code server had two
internal queues, one to track module loading
and another to track on_load callbacks. This
pull requests refactors the code to have a
single queue, in order to fix bugs and improve
maintainability.
Closes #7466.
Closes #8510.
=> Refactor code server to use a single queue

lib/kernel/doc/guides/logger_chapter.md, lib/kernel/src/logger_formatter.erl, lib/ssh/src/ssh_client_channel.erl, lib/ssh/src/ssh_connection.erl, lib/ssh/src/ssh_server_channel.erl, lib/ssl/doc/ssl_app.md, lib/stdlib/src/dets.erl
Those were rendered as text, not as a link to a type.
=> fix: kernel logger guide md typos

erts/emulator/beam/beam_file.c, lib/compiler/src/beam_asm.erl, lib/compiler/src/beam_disasm.erl, lib/compiler/src/compile.erl, lib/stdlib/src/beam_lib.erl, lib/stdlib/test/beam_lib_SUITE.erl
See #8967 and #8940 for a discussion about why this is useful.
This pull request also makes it possible to read out the literal chunk decoded like so:
beam_lib:chunks(Beam, [literals])
Closes #8967
=> Don't compress the literal chunk in BEAM files

lib/crypto/c_src/digest.c, lib/crypto/c_src/digest.h, lib/crypto/c_src/hash.c, lib/crypto/test/crypto_SUITE.erl
=> Fix crypto:hash_final/1 for shake128/256 on OpenSSL >= 3.4

lib/ssh/src/ssh_connection.erl
- avoid code crash when exit signal is received for closed channel
- closing #8929
=> ssh: avoid crash upon exit-signal

lib/stdlib/src/json.erl, lib/stdlib/test/json_SUITE.erl
Support formatting key-value lists while preserve their ordering.
Closes #8882
=> Add json format functions for key-value lists

lib/public_key/src/pubkey_os_cacerts.erl, lib/public_key/src/public_key.erl, lib/public_key/test/public_key_SUITE.erl
This pull request allows setting a custom location for certificates via the application config.
Currently we are seeing a proliferation of env vars for reading certificates from in the Elixir community. Here are some examples:
* https://github.com/hexpm/hex/blob/eec7a266f6e1b1c754798ee9a9c17b4b6201fff2/lib/hex/state.ex#L111 
* https://github.com/elixir-lang/elixir_make/blob/67ef8c1e249d1562fee9247320a602908f0094c6/lib/elixir_make/downloader/httpc.ex#L53
* https://github.com/elixir-nx/bumblebee/blob/b01e0da989a39b594990f8023bebb3751663fb19/lib/bumblebee/utils/http.ex#L191
This means anyone using Elixir/Erlang behind a proxy needs to setup several env vars, carefully reading the docs of each package that may do external HTTP requests.
For this reason, I believe a solution upstream in Erlang …
=> Allow setting certificates via application config

lib/compiler/src/v3_core.erl, lib/compiler/test/bs_bincomp_SUITE.erl, lib/debugger/test/bs_bincomp_SUITE.erl, lib/stdlib/src/eval_bits.erl, lib/stdlib/test/erl_eval_SUITE.erl
When the pattern in a binary generator is of the form `X:Y/float`, the previous skip clause could never match. The skip pattern is changed to `_:Y/integer`, so that it can match as long as `Y` is valid.
Before:
1> BadFloat = <<-1:64>>, [X || <<X:64/float>> <= <<BadFloat/binary, 1.0:64/float>>].
[]
Now:
1> BadFloat = <<-1:64>>, [X || <<X:64/float>> <= <<BadFloat/binary, 1.0:64/float>>].
[1.0]
=> compiler: Fix skip clause for binary generators

erts/etc/common/dialyzer.c, erts/etc/common/erlc.c, erts/etc/common/typer.c, erts/test/erlc_SUITE.erl
Reapply https://github.com/erlang/otp/pull/849 which was reverted previously, without indication to why.
Should make it possible to run erlc, dialyzer and typer when they have been installed in a path with spaces.
Related issue https://github.com/erlang/otp/issues/8845
=> erts: Fix erroneous splitting of emulator path

erts/etc/unix/run_erl.c, erts/etc/unix/to_erl.c, lib/kernel/src/group.erl, lib/kernel/test/interactive_shell_SUITE.erl
When you connect with to_erl, the screen should
not be cleared. Instead the input line should be
redrawn. Changing ^L to ^[l achieves this.
=> erts: to_erl screen should not be cleared

lib/kernel/src/logger.erl
=> logger: Fix documentation equiv macro

lib/eldap/src/Makefile
Spec are fixed so warnings should be enabled.
=> eldap: Enable missing doc spec warnings

lib/stdlib/src/binary.erl, lib/stdlib/src/erl_stdlib_errors.erl, lib/stdlib/test/binary_module_SUITE.erl
=> Issue #8099: Add binary:join/2 to stdlib

erts/emulator/beam/erl_process.c, erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Fix #8983.
Calling `enif_whereis_pid` in NIF monitor `down` callback would cause lock order violation detected by lock checker in `debug` build.
Release main lock of the exiting process while calling NIF `down` callback.
=> Fix potential lock order conflict in NIF monitor down callbacks

erts/emulator/beam/erl_drv_nif.h, erts/emulator/beam/erl_nif.h
On windows nifs can be compiled with gcc/clang which means that __has_attribute(malloc) is defined. This was never intended to work so we disable it on Windows.
closes #9015
=> erts: Do not annotate nif API functions on windows

lib/compiler/src/v3_core.erl
`NomatchGuard` was only needed for strict binary generators to test for non-empty binaries. Now `TailPat` for strict binary generators is changed to an empty binary, and `TailClause` is moved before `NomatchClause` for this case. There is no need to have NomatchGuard anymore.
=> compiler: remove NomatchGuard from strict generators

lib/kernel/doc/kernel_app.md, lib/kernel/src/kernel.erl, lib/kernel/src/os.erl, lib/kernel/test/os_SUITE.erl, lib/kernel/test/os_SUITE_data/Makefile.src, lib/kernel/test/os_SUITE_data/sys_shell.c
=> Add the ERL_SYS_SHELL env variable to point to system shell for os:cmd()

lib/kernel/src/erpc.erl, lib/kernel/test/erpc_SUITE.erl
=> Introduce `erpc:call_opt/3,5`

lib/stdlib/src/supervisor.erl, lib/stdlib/test/supervisor_SUITE.erl
Sometimes I have the need to obtain the Pid of a certain supervisor child. This often happens when the children form a work unit of cooperating processes, wherein one needs to talk to another.
To obtain such a Pid, currently I have to use `which_children/1` to obtain a list of _all_ children, then filter out the one I need, which is boilerplate code repeated over and over.
This PR adds a function `which_child/2`, which can be used to obtain the same information as `which_children/1` does, but for a particular single child.
=> Add `supervisor:which_child/2`

lib/compiler/src/compile.erl, lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl, lib/stdlib/test/erl_lint_SUITE_data/bad_behaviour3.erl
This commit adds the following compiler options for suppressing warnings having to do with behaviours:
* nowarn_conflicting_behaviours
* nowarn_undefined_behaviour_func
* nowarn_undefined_behaviour
* nowarn_undefined_behaviour_callbacks
* nowarn_ill_defined_behaviour_callbacks
* nowarn_ill_defined_optional_callbacks
Closes #8985
=> Add options for silencing warnings for behaviours

lib/kernel/src/prim_tty.erl, lib/kernel/test/interactive_shell_SUITE.erl
When the first charaacter is a composing unicode character like ZWNJ ZWJ characters or U+0308 it binds with the last character that is part of the prompt and creates a grapheme cluster. In this case we need to split up the grapheme cluster and remove the composing character and keep the character that is part of the prompt.
=> kernel: fix bug with composing unicode character

lib/observer/src/cdv_mem_cb.erl, lib/observer/src/crashdump_viewer.erl, lib/observer/test/crashdump_viewer_SUITE.erl
When gathering info about the allocators (particularly the summaries), crashdump viewer filters "interesting allocator info". However recent crash dumps also contain allocator type in the key so for example "mbcs blocks[sys_alloc] size" did not match the expected "mbcs blocks size". This resulted in "blocks size" always showing "N/A" on the "Allocator Summary" page. This commit removes the part in square brackets when summing blocks size values for each allocator type.
Also the first column is made wider to fit the longer keys on the per allocator instance pages.
This PR can be considered just a bug report. My solution here is just a random quick fix and there might be a better one.
=> Crash dump viewer: ignore allocator type from blocks size keys

lib/dialyzer/src/dialyzer_dataflow.erl, lib/dialyzer/src/dialyzer_typesig.erl, lib/dialyzer/test/dialyzer_SUITE.erl
=> dialyzer: Support modules compiled with `line_coverage`

lib/stdlib/src/erl_anno.erl, lib/stdlib/test/erl_anno_SUITE.erl
See the discussion in https://github.com/erlang/otp/pull/8945#discussion_r1806260645.
Currently `erl_anno:end_location(Anno)` is inferred from `location` and `text` (if present). However, this means that in order to store a location range, we always need to store the whole text. This allows setting `end_location` of `Anno` directly.
With this change `erl_anno:end_location(Anno)` will first look for `end_location` set directly and then fallback to the inference if applicable.
=> Add erl_anno:set_end_location/2

erts/emulator/test/bif_SUITE.erl
The preloaded BEAM files in `$ERL_TOP/erts/preloaded/ebin` in the git repo longer contains debug information, causing three test cases to fail. However, BEAM files with debug information can be found in `$ERL_TOP/erts/ebin`.
Make sure that the test cases that need debug information pick up the correct BEAM files.
~The preloaded BEAM files in `$ERL_TOP/erts/preloaded/ebin` in the git repo longer contains debug information. That would cause three of the test cases to fail. Instead of failing, don't attempt to verify BIFs residing in preloaded modules when running the tests in a git repo.~
=> bif_SUITE: Fix failing test cases when run in a git repo

lib/kernel/src/group.erl, lib/kernel/src/prim_tty.erl, lib/kernel/src/user_drv.erl, lib/stdlib/test/escript_SUITE.erl, lib/stdlib/test/escript_SUITE_data/bypass_unicode_conversion
Group checks that user_drv is in raw output mode and latin1 encoding mode
if true then the request is sent as latin1 and outputted by user_drv as is
if false then the request is converted to a unicode binary before its sent to user_drv.
=> kernel: bypass unicode translation in group for latin1 putc_requests

erts/emulator/beam/bif.tab, lib/compiler/src/beam_ssa.erl, lib/compiler/src/beam_ssa_opt.erl, lib/compiler/src/beam_ssa_pre_codegen.erl, lib/compiler/test/beam_ssa_check_SUITE_data/non_throwing_bifs.erl, lib/compiler/test/bif_SUITE.erl
When put in a try, calling a guard bif with no side-effects is already optimized to remove the try/catch. However, there are bifs with side-effects that can be safely optimized in the same way in order to gain performance.
Example code:
try binary_to_atom(A, utf8)
catch _:_ -> []
end.
Before, SSA for the bif call after optimizations:
_6 = call (`erlang`:`binary_to_atom`/2), _0, `utf8`
_14 = succeeded:body _6
Now, SSA for the bif call after optimizations:
_6 = bif:binary_to_atom _0, `utf8`
_14 = succeeded:guard _6
Bifs that are optimized for try/catch in this change: `binary_to_atom/1`, `binary_to_atom/2`, `binary_to_existing_atom/1`, `binary_to_existing_atom/2`, `list_to_atom/1`, `list_to_existing_atom/1`.
=> compiler: Change some bifs to guard bifs in try/catch

scripts/scan-code.escript
It fails when there are no files given to it, since the "" is not dealt with correctly.
This commit fixes that.
=> gh: update compliance check file

erts/doc/notes.md, lib/compiler/doc/notes.md, lib/kernel/doc/notes.md, lib/ssl/doc/notes.md, lib/stdlib/doc/notes.md, lib/tools/doc/notes.md
ex_doc (or rather EarmarkParser) does not consider the whitespace between reference links significant so joins multiple references into a single link. Many MD standards seem to work this way, though the majority do not.
Anyway we need to fix this so that the links render properly, see https://github.com/RobertDober/earmark_parser/issues/159 for details on when/if this issue is solved.
=> Fix notes links

lib/ssl/src/ssl.erl
Small improvement discussed in https://github.com/erlang/otp/issues/9051
=> ssl: Document TLS alerts in ssl_error messages

erts/configure, lib/common_test/configure, lib/crypto/configure, lib/erl_interface/configure, lib/megaco/configure, lib/odbc/configure, lib/snmp/configure, lib/wx/configure, make/autoconf/otp.m4, make/configure
Sorry that due to a copy-paste error I set the wrong set of variables for ARM64 Windows under `AC_CANONICAL_TARGET` in the previous PR https://github.com/erlang/otp/pull/8734.
=> fix `target*` variables for ARM64 Windows

lib/stdlib/src/zip.erl, lib/stdlib/test/zip_SUITE.erl
=> Fix zip:extract/2 with keep_old_files to respect cwd

.github/workflows/license-scanner.yaml, scripts/licensedetection/licenses/apache-2.0-or-lgpl-2.1-or-later.LICENSE, scripts/scan-code.escript
Adds the checks on copyrights, and makes Apache the only accepted license.
Anything outside Apache should be flagged and approved in the Security panel.
=> gh: check copyrights and make Apache only approved

lib/eunit/src/eunit_test.erl, lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
=> erl_lint: Warn on remote-calling non-exported functions

lib/sasl/test/installer.erl
The PR #8744 instroduced a call to read_file_info that needs to be allowed for the testcase to pass.
=> sasl: Fix release_handler_SUITE:client1 trace allow list

lib/kernel/src/group.erl, lib/kernel/src/standard_error.erl, lib/kernel/test/standard_error_SUITE.erl, lib/stdlib/src/io.erl, lib/stdlib/test/io_proto_SUITE.erl
This API can be used to log what a user types in the shell, or what is written by application to stdout/stderr. Its main purpose is to allow applications that cannot be updated from using `io:format` for logging to end up as log messages.
=> Add logging support to group and standard_error

erts/configure.ac, erts/emulator/beam/erl_bits.c
At least gcc 14.2 at x86 platform correctly returns `sizeof(_Float16)` value, but then the compilation is failed as the following:
```
beam/erl_bits.c: In function ‘erts_bs_get_float_2’:
beam/erl_bits.c:485:9: error: invalid conversion from type ‘_Float16’ without option ‘-msse2’
485 |         f.fd = FP16_TO_FP64(f16);
|         ^
```
Add the new check in order to fix build at x86 platform. Please note, that the patch correctly check the compiler behaviour when
CFLAGS="-msse2" ./configure
is run.
=> erts: Improve Float16 type checking

lib/stdlib/src/edlin_context.erl, lib/stdlib/src/edlin_expand.erl, lib/stdlib/test/edlin_context_SUITE.erl
Fixes https://github.com/erlang/otp/issues/9071
=> stdlib: prevent shell from crashing when completing Var/ and Var(

lib/mnesia/src/mnesia_checkpoint.erl, lib/mnesia/test/mnesia_evil_coverage_test.erl
If a table is deleted just when a checkpoint is starting, the checkpoint creation could fail so that mnesia crashed.
=> Fix mnesia crash when checkpoint initialization fails

lib/mnesia/src/mnesia.erl
There was a wrongly named parameter in the documentation for the create_table function.
The code is now 
```erlang
-spec create_table(Name::table(), Opts::[create_option()]) -> t_result('ok').
create_table(Name, Arg) when is_list(Arg) ->
mnesia_schema:create_table([{name, Name}| Arg]);
create_table(Name, Arg) ->
{aborted, {badarg, Name, Arg}}.
```
So the documentation should be changed accordingly. It's the only occurency of `TabDef` I found.
=> Fix documentation in mnesia.erl

lib/public_key/src/pubkey_os_cacerts.erl
The systems root keychain contains well know root certificates, yet is non-modifiable. As such, internal CA certificates (both root and intermediate) tend to get installed into the systems keychain in the context of an private organization. Not loading certs from this keychain results in differing behavior from other tools (e.g., openssl, curl, etc.). This commit changes to that so that ssl in conjunction with public key just works in such environments.
Resolves #8813
=> Load certificates from systems keychain on darwin

lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
When a function is used with wrong arity, the compiler will try to suggest a defined function with the same name but a different arity. For example, given the following module:
-module(typos).
-export([t/0]).
bar(A) -> A.
bar(A,A,A) -> A.
bar(A,A,A,A) -> A.
t() -> bar(0, 0).
The compiler will emit the following message:
typo.erl:6:12: function bar/2 undefined, did you mean bar/1,3,4?
%   6|     t() -> bar(0, 0).
%    |            ^
Error types that are extended by this change: `bad_inline`, `undefined_nif`, `bad_nowarn_unused_function`, `bad_nowarn_bif_clash`, `undefined_function`.
Using a function with wrong arity has higher precedence than having a typo in the function name. If the compiler can find a defined function with the same name but a different arity, it will not suggest a …
=> compiler: Improve error messages for using a function with wrong arity

lib/compiler/src/beam_ssa.erl, lib/compiler/test/beam_ssa_check_SUITE.erl, lib/compiler/test/beam_ssa_check_SUITE_data/non_throwing_bifs.erl, lib/compiler/test/bif_SUITE.erl
This is a fix for [PR-9042](https://github.com/erlang/otp/pull/9042). `binary_to_atom/1` and `binary_to_existing_atom/1` now use the correct optimization. Tests for SSA in `non_throwing_bifs.erl` are fixed and added to the correct suite.
=> compiler: Fix optimization for binary_to_atom and tests

lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
This pull request simplifies some code in `erl_lint` and also enhances code coverage.
=> Clean up `erl_lint`

lib/stdlib/src/erl_scan.erl, lib/stdlib/test/erl_scan_SUITE.erl
In cases such as "123a45", the scanner did not report an error, instead
returning two tokens '123' and 'a45'. The splitting point depends on the
base, so e.g., "16#12fg34" was scanned as '16#12f' and 'g34'. This change
makes the scanner reject numbers immediately followed by a name character.
The first commit fixes a testcase error that silently ignored some listed cases.
=> Do not allow name characters immediately after a number

lib/dialyzer/src/erl_types.erl, lib/dialyzer/test/opaque_SUITE_data/src/union/union_nested_nominal.erl
Fix https://github.com/erlang/otp/issues/9131
=> dialyzer: fix crash with nominal types

lib/common_test/src/cth_surefire.erl
- avoid calling erlang:tl with an empty list
=> common_test: cth_surefire don't fail on group skip

lib/kernel/doc/references/app.md, lib/sasl/doc/references/appup.md, lib/sasl/src/release_handler.erl, lib/stdlib/src/gen_event.erl, lib/stdlib/src/gen_fsm.erl, lib/stdlib/src/gen_statem.erl, system/doc/reference_manual/modules.md, system/doc/system_principles/system_principles.md
Hello,
- here are commits for fixing redirection links
- it started from noticing that, in [`gen_statem`](https://www.erlang.org/doc/apps/stdlib/gen_statem), the Note didn't point to the _Design Principles_
- noticed the same pattern in other files.
```shell
lib/kernel/doc/kernel_app.md:50:manager (see [OTP Design Principles](`e:system:design_principles.md`) and
lib/kernel/doc/references/app.md:173:  information, see [OTP Design Principles](`e:system:applications.md`).
lib/kernel/doc/references/config.md:150:[OTP Design Principles](`e:system:design_principles.md`)
lib/kernel/src/application.erl:43:[OTP Design Principles](`e:system:design_principles.md`).
lib/kernel/src/application.erl:47:[OTP Design Principles](`e:system:design_principles.md`),
lib/kernel/src/error_logger.erl:38:[OTP …
```
=> fix redirection links in docs

lib/dialyzer/src/dialyzer_dataflow.erl
Fix https://github.com/erlang/otp/issues/9135. Dialyzer was slow because in `dialyzer_dataflow:handle_guard_call/5`, previous way of handling opaque warnings required one extra round of binding for guards. In Elixir source code, guards in the format of `when digit in ?0..?9` can be expanded to more than 10 guards during Dialyzer's analysis, which made the inefficiency more obvious.
=> dialyzer: Fix slow Dialyzer run on Elixir source code

lib/ssl/test/ssl_upgrade_SUITE.erl
Missed some things when keeping funs in config.
=> ssl: Fix testcase

lib/stdlib/src/argparse.erl, lib/stdlib/test/argparse_SUITE.erl
The documentation of `cmd_path()` states that it always starts with the progname. Indeed, `argparse:parse/{1,2}` returns a command path with the progname at the beginning.
However, if `argparse:help/2` is called with `#{command => CmdPath}` in the parser options with `CmdPath` starting with the progname, it crashes with a `badkey` exception because it expects the command path to only contain commands and sub-commands.
The patch drops the first element of the command path if it matches the progname.
This adds support for the correct values of `CmdPath` while retaining backward compatibility with callers that dropped the progname themselves to work around the issue.
=> argparse: Accept the progname in the command path

lib/ssl/test/ssl_trace_SUITE.erl
- reduce the strictness of code verifying trace profiles
- ct:pal and ct:comment instead of ct:fail
- I want that verification to be done
- but don't want it to stop someone from merging
- I can fix those myself later
- tc_check_profiles will still fail if one functions used in trace
- profile is not correct (non-existing function used in profile definition)
=> ssl: relax ssl_trace_SUITE

lib/kernel/doc/guides/eep48_chapter.md, system/doc/reference_manual/documentation.md
Also changed one item to keep order alphabetical.
For ExDoc, I propose that, if the group is used, it will still be prefixed by its type, such as "Functions" or "Types". For example, in Nx, you can imagine the functions below were tagged as: `group: "Aggregates"`, `group: "Backend"`, etc.
However, if you really want to override it, you can use the `groups_for_docs` configuration. Like done above, where "Guards" are getting its own group.
@garazdawi would these conventions suit Erlang?
=> Add group metadata to EEP48

lib/ssl/src/dtls_socket.erl, lib/ssl/src/ssl.erl, lib/ssl/src/ssl_gen_statem.erl, lib/ssl/src/ssl_trace.erl, lib/ssl/src/tls_socket.erl, lib/ssl/test/dtls_api_SUITE.erl, lib/ssl/test/ssl_trace_SUITE.erl
Removal of some code that is too generalizing making unnecessary module jumping so the code becomes harder to follow.
=> ssl: Remove unnecessary code generalization

lib/compiler/src/beam_validator.erl, lib/compiler/test/beam_validator_SUITE.erl, system/doc/efficiency_guide/system_limits.md
=> beam_validator: Reject functions with more than MAX_ARG arguments

lib/sasl/src/systools_make.erl, lib/sasl/test/systools_SUITE.erl
This commit changes the behaviour of `systools:make_tar/1,2` so that application upgrade (`.appup`) files for all applications are included in the release package.
To support just-in-time (JIT) creation of release upgrade specifications on a target system, using `systools:make_relup/3,4`, it is necessary to have the application upgrade files (`.appup`) installed.
See this community forum discussion thread on Day 1 or Day 2 (JIT) release specification creation:
[release-upgrade-specifications-day-1-or-day-2](https://erlangforums.com/t/release-upgrade-specifications-day-1-or-day-2/4013)
=> sasl: include appup files in release package

lib/dialyzer/test/indent_SUITE_data/src/map_galore.erl, lib/dialyzer/test/indent_SUITE_data/src/simple/is_rec.erl, lib/dialyzer/test/map_SUITE_data/src/map_galore.erl, lib/dialyzer/test/opaque_SUITE_data/src/simple/is_rec.erl, lib/dialyzer/test/options2_SUITE_data/src/kernel/global.erl, lib/dialyzer/test/r9c_SUITE_data/src/asn1/asn1ct_value.erl, lib/dialyzer/test/r9c_SUITE_data/src/mnesia/mnesia_lib.erl, lib/dialyzer/test/small_SUITE_data/src/false_false.erl
Hello,
If this change makes sens, I'll push subsequent ones on the same modification:
- below is the script used for that; [`random:uniform/1` is deprecated since OTP 19](https://www.erlang.org/doc/deprecations.html#functions-deprecated-in-otp-19)
- I signed the license agreement.
```shell
git grep -Pn 'random:uniform' | \
awk -F: '/lib\/dialyzer\/test/{ \
cmd = sprintf("sed -i -e '%ds/random:uniform/rand:uniform/' %s\n", $2,$1); \
system(cmd); \
close(cmd)
}'
```
=> lib/dialyzer/test: replace `random:uniform/1` by `rand:uniform/1`

lib/ssh/src/ssh_fsm_userauth_client.erl, lib/ssh/test/ssh_protocol_SUITE.erl
SSH servers can send userauth banners at any time during authentication and the erlang SSH client only accepted userauth banners in some limited circumstances.
Closes #9065
=> ssh: avoid protocol error on userauth banner

lib/crypto/c_src/algorithms.c, lib/crypto/c_src/atoms.c, lib/crypto/c_src/atoms.h, lib/crypto/c_src/eddsa.c, lib/crypto/c_src/evp.c, lib/crypto/c_src/openssl_config.h
This is an attempt to resolve https://github.com/erlang/otp/issues/9000
=> crypto: Make ed25519/x25519 available without ed448/x448

lib/tools/emacs/erlang.el, lib/tools/test/emacs_SUITE_data/comprehensions, lib/tools/test/emacs_SUITE_data/type_specs
Indent region could indent multiline strings.
Improve that by trying move outside of the string before parsing the function.
This aint perfect since we use emacs builtin knowledge if we are in a string or not, and that might falter with triple-qouted strings.
=> Improve strings with indent-region

lib/stdlib/src/argparse.erl, lib/stdlib/test/argparse_SUITE.erl
=> stdlib: Fix argparse:format_help/2 crash on 'hidden' command

lib/stdlib/src/digraph_utils.erl, lib/stdlib/test/digraph_utils_SUITE.erl
The previous `digraph_utils:preorder/1` and `digraph_utils:postorder/1` did not start the traversal from root nodes. This fix makes both traversals only start or restart from a root node in one of the components, or an arbitrary node if no root node can be visited. Since in the previous version, the search can start and restart from arbitrary nodes, this fix should not break backwards compatibility.
It is worth noting that the digraph does not have a notion of a left or right subtree. The result of both traversals may not be the same after relabelling vertices.
=> stdlib: Fix preorder and postorder traversals in `digraph_utils`

lib/common_test/src/cte_track.erl, lib/stdlib/test/gen_event_SUITE.erl, lib/stdlib/test/gen_server_SUITE.erl, lib/stdlib/test/gen_server_SUITE_data/format_status_server.erl, lib/stdlib/test/gen_statem_SUITE_data/format_status_statem.erl, lib/stdlib/test/io_proto_SUITE.erl, lib/stdlib/test/peer_SUITE.erl, lib/stdlib/test/rand_SUITE.erl, lib/stdlib/test/stdlib_gh.spec
- enable cte_track
- redirect logger events out of terminal output
=> stdlib: reduce test log on gh

lib/kernel/src/os.erl, lib/kernel/test/os_SUITE.erl
`exception_on_failure` makes os:cmd/2 fail when the command exits with a failure reason. Before this change the user had to check the output from the command to know if it failed or not, now an exception will be thrown instead.
I decided to not implement it as a different return value as that would change the return signature of os:cmd/2 depending on which options are passed which makes it a lot more difficult for static analysis tools to know what this function can return.
I'm not very happy with this new API, so if anyone has any better ideas on how this should work please suggest them!
=> os: Add exception_on_failure to os:cmd/2

lib/syntax_tools/src/erl_syntax_lib.erl, lib/syntax_tools/test/syntax_tools_SUITE.erl
`maybe_match_expr` and `else_expr` were not handled properly when annotating bindings. This was causing [problem with ELS](https://github.com/erlang-ls/erlang_ls/issues/1527) and this is currently preventing me to fix the issue. The problems were both false positive and false negative diagnostics.
This will probably cause problem in ELP too, so I'll kindly ping @robertoaloi @michalmuskala to take a look at this.
I didn't provide any test for this because it seems that `erl_syntax_lib` is not tested.
What one can do to test this PR is to [build Erlang-LS from this PR](https://github.com/erlang-ls/erlang_ls/pull/1531) and make sure that `els_diagnostics_SUITE:bound_var_in_pattern_maybe/1` testcase passes. Testcase tests for both false negatives and false positives.
What I'm not completely …
=> erl_syntax_lib: annotate `maybe_match_expr` and `else_expr` correctly

.github/workflows/main.yaml
Update gh actions to disable both systemd-coredump and apport.
=> gh: Ubuntu-24.04 uses systemd-coredump instead of apport by default

lib/ssh/src/ssh.hrl
=> ssh: fix callbacks_daemon_options() type spec

lib/kernel/src/inet.erl
Small change to improve readability because I could not understand the current version.
=> inet: Rephrase setopts docs

otp_build
shaNsum does not support --status on all platforms so we replace it with `> /dev/null`.
=> otp: Fix shaNsum of ex_doc+jit-reader on FreeBSD

lib/tools/src/eprof.erl
I was trying to use `eprof` but came across strange behaviour:
```erlang
(my_program@my_machine)1> f().
ok
% here I am just making sure no eprof process is running
(my_program@my_machine)2> TracerPid = case eprof:start() of
(my_program@my_machine)2>     {error, {already_started, TracerPid}} -> TracerPid;
(my_program@my_machine)2>     {ok, TracerPid} -> TracerPid
(my_program@my_machine)2> end,
(my_program@my_machine)2> exit(TracerPid, kill).
true
% I start eprof to rack all processes in the beam
(my_program@my_machine)3>
(my_program@my_machine)3> eprof:start_profiling(erlang:processes(), {'_', '_', '_'}, []).
% it return atom error
error
% here I just point out the OTP version
(my_program@my_machine)4> erlang:system_info(otp_release).
"24"
(my_program@my_machine)5>
```
but spec for `fun …
=> Extend error to match the fuction type spec

lib/stdlib/src/maps.erl
(Code not changed)
- Updated doc for maps:foreach/2 (renamed F to Fun, so docs text corresponds with -spec for foreach/2)
- Added example for maps:foreach/2
=> Updated doc for maps:foreach/2. Added example for maps:foreach/2.

lib/stdlib/src/erl_anno.erl, lib/syntax_tools/src/erl_syntax.erl
Corrects and improves a couple of previous fixes to the reverting functions in erl_syntax.
Also ensures that erl_anno:location/1 does not return undefined, which is not in the spec.
=> Syntax tools reversion fixes

lib/ssl/src/tls_server_connection_1_3.erl
The error occurs if more than one certificate is configured and the first certificate fails the check by the `tls_handshake_1_3:check_cert_sign_algo` function. The recursive call to the `select_server_cert_key_pair` function fails and as a result the TLS connection is not established.
=> ssl: Fix function_clause error in tls_server_connection_1_3:select_server_cert_key_pair function

erts/configure, erts/configure.ac
Fixes erlang/otp#9211
* Add headers (`stdlib.h`, `fcntl.h`) for `poll`
* Add `unistd.h` for `sbrk`
(cherry picked from commit e2604aa7a92b3bb7c1293afd12705c7ce9c952a4)
=> Make `poll()` test work with `gcc` 14

erts/emulator/beam/erl_bits.c, erts/emulator/beam/erl_bits.h, erts/emulator/beam/jit/arm/instr_bs.cpp, erts/emulator/beam/jit/beam_jit_common.cpp, erts/emulator/beam/jit/beam_jit_common.hpp, erts/emulator/beam/jit/x86/beam_asm.hpp, erts/emulator/beam/jit/x86/instr_bs.cpp
See the individual commit messages for details.
=> Slightly optimize bit syntax construction

lib/stdlib/src/dets.erl, lib/stdlib/src/ets.erl
Some quite old code in Ets and Dets would print messages to stdout when repairing tables or when fun2ms failed.
=> Ets and Dets code should not be printing to stdout

erts/emulator/drivers/common/inet_drv.c
With GCC 14 series the following error exists:
drivers/common/inet_drv.c: In function 'sctp_parse_async_event': drivers/common/inet_drv.c:3498:54: error: passing argument 4 of 'load_inet_get_address' from incompatible pointer type [-Wincompatible-pointer-types]
3498 |             i = load_inet_get_address(spec, i, desc, &sptr->spc_aaddr);
|                                                      ^~~~~~~~~~~~~~~~
|                                                      |
|                                                      struct __kernel_sockaddr_storage *
drivers/common/inet_drv.c:1941:38: note: expected 'struct sockaddr_storage *'
but argument is of type 'struct __kernel_sockaddr_storage *'
1941 |             struct sockaddr_storage* addr)
|             ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~ …
=> Fix incompatible pointer type 'struct sockaddr_storage *'

lib/tools/emacs/erlang-pkg.el
The information in `<name>-pkg.el` did not agree with the information in `<name>.el`.  This pull-requests addresses that be removing the outdated `<name>-pkg.el`.
While the end-user package manager `package.el` expects a file `<name>-pkg.el`, this should only be generate by the package archive (such as GNU ELPA and MELPA), instead of being tracked in the upstream repository.
The tools used maintain the various *ELPA, do *not* use `<name>-pkg.el` as a data *source*, they only generate it.
- `elpa-admin.el`, the tool used for GNU ELPA and NonGNU ELPA, does *not* use `<name>-pkg.el` as a data source and it never has.
- `package-build.el`, the tool used for Melpa, prefers `<name>.el` but *currently* falls back to get information missing from there from `<name>-pkg.el` instead. I am goint to …
=> Remove outdated lib/tools/emacs/erlang-pkg.el

lib/dialyzer/test/file_utils.erl, lib/dialyzer/test/small_SUITE_data/results/abs, lib/dialyzer/test/small_SUITE_data/src/abs.erl
We recently introduced license checking as best practices. New dialyzer tests are checked, and we need to be able to add the license and copyright to the expected results of a dialyzer test.
This commit removes the license and copyright comments in expected result file, so that it is not considered an expectation from the output of the test.
In case of existing programs, such as `abs`, one can add the license and copyright at the end of the test program file, and the license and copyright anywhere in the expected result (although it makes sense that it is the first lines).
This PR blocks #9295 (i.e., PR 9295 cannot be merged until this PR is merged).
=> dialyzer: remove license from expected result

lib/ssh/doc/notes.md
- credits were missing for CVE-2023-48795 patch
=> ssh: add missing Terrapin credits

lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
=> erl_lint: Fix edge cases in unknown export warnings

erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Starting with gcc-14, the emulator tests were failing to run due to gcc reporting an "incompatible pointer type" error in nif_SUITE.c. The fix is straighforward
=> Fix incompatible-pointer-type error in nif_SUITE.c

lib/stdlib/src/timer.erl
Since `timer:sleep/1` accepts timeouts greater than `16#ffffffff` since OTP 25, `timeout()` in the sense of "what is acceptable by `receive... after` is wrong.
=> Fix `timer:sleep/1` spec

erts/emulator/beam/erl_nif.c
Debug builds configured with static NIFs are currently not usable since they abort during startup.  The abort is caused by a check in erts_add_taint that makes sense once the runtime has started but might not be meaningful before the runtime has been started, notably during static NIF initialization.
This change adds an additional check that allows erts_add_taint to proceed when called during runtime initialization.  With this check, a debug with static NIFs can complete the startup process.
Resolves #9306
=> Relax invariants checked by erts_add_taint before initialization

erts/emulator/utils/make_version
This PR should partially address the issue reported in https://github.com/erlang/otp/issues/8767.
As described in #8767, ideally the following should return a triple like `x86_64-pc-windows`.
```erlang
1> erlang:system_info(system_architecture).
"x86_64-pc-windows"
```
As this is what's described in the [official docs](https://www.erlang.org/doc/man/erlang.html#system_info_system_architecture):
> ```
> system_architecture
>  Returns a string containing the processor and OS architecture the emulator is built for.
> ```
But changing this from `win32` to `x86_64-pc-windows` for AMD64 Windows and `i686-pc-windows` for 32-bit Windows could lead to a large blast radius -- I can imagine that many libraries would have to update their code.
However, it's still fixable for ARM64 Windows as there …
=> set proper triplets for Windows

lib/kernel/src/socket.erl
The type specs for `socker.erl` were improved in PR-8986, but they introduced a bug by omitting one of the overloaded specs. this commit fixes that.
closes #9180
=> kernel: fixes socket.erl type spec

lib/kernel/src/gen_tcp.erl
The term to be used should be "packet", not "package".
=> Fix `gen_tcp:send/2` docs

lib/ssl/src/ssl.app.src, lib/ssl/src/ssl_cipher.erl, lib/ssl/src/ssl_internal.hrl, lib/ssl/src/ssl_record.erl, lib/ssl/src/ssl_trace.erl, lib/ssl/src/tls_client_connection_1_3.erl, lib/ssl/src/tls_gen_connection.erl, lib/ssl/src/tls_gen_connection_1_3.erl, lib/ssl/src/tls_record.erl, lib/ssl/src/tls_record_1_3.erl, lib/ssl/src/tls_sender.erl, lib/ssl/src/tls_server_connection_1_3.erl, lib/ssl/test/Makefile, lib/ssl/test/openssl_session_ticket_SUITE.erl, lib/ssl/test/ssl_api_SUITE.erl, lib/ssl/test/ssl_bench_test_lib.erl, lib/ssl/test/ssl_cert_SUITE.erl, lib/ssl/test/ssl_cipher_SUITE.erl, lib/ssl/test/ssl_handshake_SUITE.erl, lib/ssl/test/ssl_mfl_SUITE.erl, lib/ssl/test/ssl_reject_SUITE.erl, lib/ssl/test/ssl_renegotiate_SUITE.erl, lib/ssl/test/ssl_session_SUITE.erl, lib/ssl/test/ssl_session_cache_api_SUITE.erl, lib/ssl/test/ssl_session_ticket_SUITE.erl, lib/ssl/test/ssl_test_lib.erl, lib/ssl/test/tls_server_session_ticket_SUITE.erl
=> Optimize tlsv1.3

.github/workflows/upload-windows-zip.yaml
Per https://github.com/erlang/otp/pull/8729#issuecomment-2298725210, erl.ini needs to be removed. However, there's another one, `erts-{vsn}\bin\erl.ini`:
```
$ curl -fsSLO https://github.com/erlang/otp/releases/download/OTP-27.2/otp_win64_27.2.zip
$ unzip -l otp_win64_27.2.zip | grep "erl.ini"
117  12-11-2024 12:09   erts-15.2/bin/erl.ini
3184  12-10-2024 21:23   lib/erts-15.2/ebin/erl_init.beam
2028  12-10-2024 21:23   lib/erts-15.2/src/erl_init.erl
```
Calling `erts-{vsn}\bin\erl.exe` will fail while the file is there and succeed otherwise:
```
PS C:\Users\wojtek> C:\Users\wojtek\.elixir-install\installs\otp\27.1.2\erts-15.1.2\bin\erl.exe
Could not load module D:\a\otp\otp\otp_win64_27.1.2\erts-15.1.2\bin\erlexec.dll.
PS C:\Users\wojtek> rm …
```
=> gh: Remove erts-{vsn}/bin/erl.ini before creating otp*.zip

lib/ssl/src/ssl_gen_statem.erl, lib/ssl/src/tls_client_connection_1_3.erl, lib/ssl/src/tls_gen_connection_1_3.erl, lib/ssl/src/tls_server_connection.erl, lib/ssl/src/tls_server_connection_1_3.erl
An initiated handshake should always be closed with an alert, elminate controlled shutdown that does not send alert.
=> ssl: Handle user initiated cancelation during handshake

lib/ssl/src/ssl.erl, lib/ssl/src/tls_server_connection.erl, lib/ssl/src/tls_server_connection_1_3.erl, lib/ssl/test/ssl_api_SUITE.erl
Also correct handshake environment handling so that {hanshake, hello} can be used in ssl:handshake as well as in ssl:listen
closes #9177
=> ssl: Postpone verifying of server options when {handshake, hello} is used

lib/edoc/src/Makefile, lib/edoc/src/edoc_data.erl, lib/edoc/src/edoc_doclet.erl, lib/edoc/src/edoc_extract.erl, lib/edoc/src/edoc_html_to_markdown.erl, lib/edoc/src/edoc_layout_chunks.erl, lib/edoc/src/edoc_lib.erl, lib/edoc/src/edoc_macros.erl, lib/edoc/src/edoc_run.erl, lib/edoc/src/edoc_scanner.erl, lib/edoc/src/edoc_tags.erl, lib/edoc/src/edoc_wiki.erl, lib/eunit/src/Makefile, lib/eunit/src/eunit_server.erl, lib/syntax_tools/src/Makefile, lib/syntax_tools/src/epp_dodger.erl, lib/syntax_tools/src/erl_comment_scan.erl, lib/syntax_tools/src/erl_prettypr.erl, lib/syntax_tools/src/erl_syntax.erl, lib/syntax_tools/src/erl_syntax_lib.erl
This deprecates uses of old catch expressions in "my" applications.
=> Deprecate old catches in edoc, eunit, and syntax_tools

lib/ssl/src/ssl_gen_statem.erl
Always sending alert when terminating is according to TLS protocol but as DTLS is by default over UDP there can be conercases that we do not want to result in a crassh but we can do nothing about.
=> ssl: Termination needs to be best effort, can fail for DTLS

lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
Fix https://github.com/erlang/otp/issues/9227. 2 issues with the previous code: One is that if only 1 NIF is inlined, the linter did not omit warnings no matter if it is loaded. The other is the missing `nif_inline` warning for NIFs that were not loaded.
=> stdlib: Add warning for inlined nifs without loading

lib/stdlib/src/erl_scan.erl, lib/stdlib/test/erl_scan_SUITE.erl, system/doc/reference_manual/data_types.md
Similar to based float literals in Ada and hex float literals in C 99, using Erlang's Base#Literal notation (inspired by Ada), for example, 2#0.10101#e8, or 16#fefe.fefe#e-16. The # before the exponent is required. The exponent, like the base, is always a decimal number.
These can be useful for code generators and other cases where you want to preserve an exact bit representation of a float.
Currently missing: documentation, io formatting, list_to_float/2 implementation.
Based on #9104, which improves pinpointing of errors in numerical literals.
=> Make scanner accept based floating point literals

lib/mnesia/examples/bench/bench_populate.erl
* follows from commit 7bf573cb7047321c6b0f169f77e7cb6640235157 (#9181)
* replacement is done everywhere, but in tests of `random` & `erl_lint`.
=> lib/{mnesia,stdlib}: replace `random` functions by `rand` functions

erts/config.h.in, erts/configure, erts/configure.ac, erts/emulator/beam/erl_time_sup.c, erts/emulator/sys/unix/erl_unix_sys.h, erts/emulator/sys/unix/sys_time.c, erts/emulator/sys/win32/erl_win_sys.h, erts/emulator/sys/win32/sys_time.c, erts/emulator/test/time_SUITE.erl, erts/etc/unix/cerl.src
With glibc 2.37, the behaviour of mktime was changed to no longer return an error if tm_isdst = 1 but the TZ actually does not have any dst data. For example if TZ=UTC.
Instead of trusting the timezone, and not assuming that dst is in effect, glibc decided to trust the caller and assume that dst is in effect. This means that Erlang and glibc now have different behaviours in this regard. So in order to keep backward compatability with how Erlang has always worked we instead check is the TZ has daylight handling at all, and if not we set isdst to 0.
The change was introduced by this commit: https://sourceware.org/git/?p=glibc.git;a=commit;h=83859e1115269cf56d21669361d4ddbe2687831c and a bug report was filed with glibc here: https://sourceware.org/bugzilla/show_bug.cgi?id=31144, but it seems …
=> Fix local_to_universal time without dst + TZ on Windows

lib/stdlib/src/zip.erl, lib/stdlib/test/zip_SUITE.erl
The permissions were set on extrected directories before the files within were extracted, making it impossible to create the files within. This commit delays all directory permissions to after all files/directories have been created so that they can all be set.
Closed #9332
=> stdlib: Fix zip:unzip on read-only directory with content

lib/odbc/configure.ac
iodbc has the same API and it migth be tricky to install both iodbc and unixodbc on the same machine.
Let allow to build erlang with iodbc as well.
=> lib/odbc: use iodbc when available

erts/etc/unix/cerl.src
Many BSD systems don't have a GNU make compatible 'make', instead we need to use 'gmake'. Also in testing environments the 'ERL_TOP' flags is not always set, so we compute it from cerl.
=> erts: Fix download of gdb tools on bsd

.elp.toml
The `.elp.toml` file, documented [here](https://whatsapp.github.io/erlang-language-platform/docs/get-started/configure-project/elp-toml/), allows the [ELP language server](https://whatsapp.github.io/erlang-language-platform/) to correctly discover the project. This is equivalent to the [`erlang_ls.config`](https://github.com/erlang/otp/blob/master/erlang_ls.config) file which is already present (for the [Erlang LS language server](https://erlang-ls.github.io/)).
=> Add .elp.toml file

lib/compiler/src/beam_ssa_pre_codegen.erl
do_try(F) ->
try
F()
catch
C:R:Stk ->
{'EXIT',C,R,Stk}
end.
The compiler in Erlang/OTP 27 generates the following code for the body of the function:
{allocate,3,1}.    % Allocate three Y registers.
{init_yregs,{list,[{y,0},{y,1}]}}.
{'try',{y,2},{f,3}}.
{call_fun,0}.
{try_end,{y,2}}.
{deallocate,3}.
return.
{label,3}.
{try_case,{y,2}}.
%% {y,2} is free, but is not being reused.
{move,{x,1},{y,0}}.
{move,{x,0},{y,1}}.
{move,{x,2},{x,0}}.
build_stacktrace.
{test_heap,5,1}.
{put_tuple2,{x,0},{list,[{atom,'EXIT'},{y,1},{y,0},{x,0}]}}.
{deallocate,3}.
return.
Note that a stackframe with three Y registers will be allocated. It would be sufficient to allocate two Y registers if `{y,2}` could be reused following the `{try_case,{y,2}}` instruction.
This commit extends an …
=> Improve register allocation for try ... catch constructs

lib/stdlib/src/erl_eval.erl, lib/stdlib/test/erl_eval_SUITE.erl
Fix https://github.com/erlang/otp/issues/9348
=> stdlib: Fix map comprehension result when a key value is replaced

erts/emulator/beam/erl_bif_binary.c, lib/stdlib/src/Makefile, lib/stdlib/src/binary.erl, lib/stdlib/src/lists.erl, lib/stdlib/src/maps.erl, lib/stdlib/src/shell_docs.erl, lib/stdlib/src/shell_docs_test.erl, lib/stdlib/src/stdlib.app.src, lib/stdlib/test/binary_module_SUITE.erl, lib/stdlib/test/lists_SUITE.erl, lib/stdlib/test/maps_SUITE.erl, lib/stdlib/test/shell_docs_SUITE.erl
This PR adds basic support for running doctests on documentation in Erlang/OTP. It is not yet made available for public use as the API may change, but we it can be used within Erlang/OTP to test documentation examples.
The syntax for writing doctests is like this:
````
```
> 1 + 2.
3
```
````
When something like the above is found in the docs, the expression will be run and tested against the return value. It is possible to write more complex things, but that it is the basic idea.
=> Add basic support for doctests

erts/emulator/beam/jit/arm/instr_guard_bifs.cpp, erts/emulator/beam/jit/x86/instr_guard_bifs.cpp, erts/emulator/test/guard_SUITE.erl
This will improve code in the `json` and `base64` modules.
=> Simplify range check for element/2 on a known literal tuple

lib/compiler/src/beam_ssa_alias.erl, lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
When the same variable occurs multiple times in the argument list to a call, that variable should become aliased.
This patch corrects the above described omission by renaming the current aa_alias_surviving_args/4 to aa_alias_surviving_phi_args/4 which we use for Phi-instructions and creating a new aa_alias_surviving_args/4 (for calls) which makes use of aa_alias_surviving_phi_args/4 but also does a second pass through the argument list to find repeated variables.
This patch is made against OTP-27.2.1 (the bug first appeared in OTP-27), the same functional change should also be pulled into master, where it doesn't apply cleanly. [This branch contains the same change](https://github.com/frej/otp/tree/frej/aa-bugfix), but rebased to the …
=> compiler alias analysis: Fix repeated argument bug

lib/stdlib/src/string.erl, lib/stdlib/test/string_SUITE.erl
=> stdlib: Fix jaro_similarity for matching strings of length 1

erts/etc/common/erlexec.c, erts/test/erlexec_SUITE.erl
Previously a finite 10240 buffer was used. Long paths can fail semi-silently, while long paths that already contain the erlang bindir at the end can cause a crash.
Reproducible with the following bash script:
```bash
#!/usr/bin/env bash
set -euo pipefail
ERL_PATH="$(erl -eval 'io:format("~s~n", [os:getenv("PATH")])' -s init stop -noshell)"
IFS=':' read -ra ERL_PATH_COMPONENTS <<< "$ERL_PATH"
BINDIR="${ERL_PATH_COMPONENTS[0]}"
OTHER_DIR="${ERL_PATH_COMPONENTS[1]}"
while [ ${#PATH} -lt 10240 ]; do
PATH="${PATH}:${OTHER_DIR}"
done
PATH="${PATH}:${PATH}:${BINDIR}"
erl -eval 'io:format("hello~n", [])' -s init stop -noshell
```
Output:
```
% ./repro.sh
./repro.sh: line 19: 98643 Bus error: 10           erl -eval 'io:format("hello~n", [])' -s init stop -noshell
```
=> Support long PATH values in erlexec

lib/stdlib/src/json.erl
Using characters rather than strings for curly brackets leads to faster downstream conversion of the generated iodata to binary.
```erlang
%% before
> json:encode(#{a => b}).
["{",[[34,<<"a">>,34],58,34,<<"b">>,34],[],"}"]
%% after
[123,[[34,<<"a">>,34],58,34,<<"b">>,34],[],125]
```
This quick benchmark encoding a couple of small objects consistently gives me ~10% speed improvements:
https://github.com/sabiwara/elixir_benches/commit/ccf6af580926a017f5b3cfb3686b9b62a08f9f47
I couldn't figure out if the use of strings here was intentional, but using characters seems more consistent with the rest of the module even disregarding performance consideration.
There might be other strings like [this one](https://github.com/erlang/otp/blob/0f854d92817eb0662fd04d6f6eda86694922d415/lib/stdlib/src/json …
=> Optimize json object encoding

.github/scripts/otp-compliance.es, .github/workflows/main.yaml, .ort.yml, .ort/config/config.yml
This PR adds SBOM generation to releases and SBoM attestation to the artifacts created by github actions.
It is heavily inspired by the work done in https://github.com/elixir-lang/elixir/pull/14241.
=> Add SBOM generation

.ort.yml
- Add missing wxWindows-free-doc license
-  fix dual license
- fix `lib/stdlib/uc_spec/**/*` using `detected_license` pattern matching, so that if we add new files, those will be scan for a license header and not default to a curation
- fixes `ryu/d2s.c` complex dual license
=> Add missing wxWindows-free-doc license and fix other licenses

erts/emulator/beam/erl_bits.c, erts/emulator/test/bs_construct_SUITE.erl
Commit b4c3fe1cbc54c2c3 (#9372) disabled an unsafe optimization when appending 0 bits to a binary.
This commit (combined with ff2ecfd258fac9d3 in #8697) reintroduces the optimization in a safe way with additional safe-guards and tests to ensure that it remains safe.
=> Renable optimization for appending 0 bits to a binary

erts/etc/win32/Install.c, lib/sasl/test/systools_SUITE.erl
The erl.ini file is no longer needed as Windows can figure out everything it needs by using the C API.
We keep support for it as they are convinient when running erlang in the source/bootstrap tree.
/cc @wojtekmach
=> erts: Remove erl.ini from Windows release

erts/configure, erts/configure.ac, erts/emulator/beam/bif.c, erts/emulator/beam/erl_db_tree.c, erts/emulator/beam/erl_nif.c, erts/emulator/beam/erl_proc_sig_queue.c, erts/emulator/beam/erl_rbtree.h, erts/emulator/beam/erl_trace.c
To improve performance of debug emulator with hopefully unreduced debuggability.
=> Build debug emulator with -Og instead of -O0

lib/debugger/src/int.erl
This PR changes the code used by `int:ni` to not crash when `load_binary` returns an error.
In case of local debugging the change is straightforward. The `extract_result` will get the result directly and the function will return `error`.
In case of distributed scenario the code will return success if any of the multicall results is a success. I'm not sure it is a best approach and if it will work 100% correct in distributed debugging scenario. Previous version would simply swallow all errors in distributed case.
Fixes https://github.com/erlang/otp/issues/7819
=> Handle load_binary result in debugger int:load

lib/ssl/src/ssl.erl, lib/ssl/src/ssl_gen_statem.erl, lib/ssl/test/ssl_sni_SUITE.erl
If sni_fun returns undefined we will attempt connection with original option values, if it returns unrecognized we end the connection with UNRECOGNIZED_NAME alert and if provided options fail option verification we will end the connection with a HANDSHAKE_FAILURE and an error log.
=> ssl: Improve error handling of sni_fun

system/doc/reference_manual/expressions.md
In link with https://erlangforums.com/t/bitstring-not-matching-as-expected/4479/4.
=> Clarify default type of matched values in bit strings

erts/emulator/beam/erl_bits.c, erts/emulator/test/bs_construct_SUITE.erl
Imagine that we execute the following code, where `X` and `Y` are integers:
```
A = <<0, X>>,
B = <<A/bits, Y:X>>.
```
The first line sets up `erts_current_bin`, `erts_bin_offset`, etc because it obviously should.
However, the second line does not do so if `X` is zero, as `build_size_in_bits` being zero short-circuits the relevant logic.
This leaves a dangling pointer that, when we execute `erts_new_bs_put_integer` on the second line, we can land in a code path that ostensibly does not modify the buffer, but may nevertheless do a dummy read/write that is masked off, which can race with a write to the same address on another scheduler. For example, this can occur if there is a garbage collection between `A` and `B`, where the old heap that `A` lived on is picked up by another process _on …
=> erts: Disable unsafe optimization in bs_append

lib/common_test/src/test_server_gl.erl
Heap grows a lot with large printouts and stays large, which causes problems when running in testcases in parallel, which keeps a lot of these processes around.
In my case the used memory went from 6.6GB to 500MB.
=> Reduce memory usage in io proxy process

lib/stdlib/src/zip.erl
The `zip` module has a typespec that is missing the `skip_directories` option in the `unzip/2` and `list_dir/2` functions.
This commit adds the missing option to the typespec, so dialyzer doesn't complain about it.
=> Fix Typespecs in zip module

lib/inets/src/http_server/httpd_instance_sup.erl, lib/inets/src/http_server/httpd_request_handler.erl
- when starting httpd, starting httpd_manager first
=> inets: fix httpd startup sequence

.github/scripts/build-base-image.sh
For some reason the prebuilt images never were cached, by changing to inline cache it works again.
=> gh: Update docker builds to use inline cache

lib/common_test/test_server/.gitignore
=> Fix `.gitignore` for common_test/test_server

erts/emulator/beam/erl_process.c, erts/emulator/beam/erl_process.h
This patch prevents non-scheduler threads from crashing the emulator.
Fixes #8208
=> Fix BEAM crash from from port/NIF thread

.formatter.exs, Makefile.in, erts/etc/win32/cygwin_tools/vc/cc.sh, erts/etc/win32/msys_tools/vc/cc.sh, erts/etc/win32/wsl_tools/vc/cc.sh, lib/compiler/scripts/smoke-mix.exs, lib/observer/doc/docs.exs, lib/ssh/doc/docs.exs, lib/stdlib/doc/docs.exs, make/ex_doc.exs, scripts/otp_check_html_links.exs
I was too lazy to break into multiple PRs. This formats all our elixir script files and makes sure the cc.sh respect both `-O0` and `-Og`.
=> Mix format and windows CC fixes

lib/crypto/c_src/crypto.c, lib/crypto/c_src/info.c, lib/crypto/src/crypto.erl, lib/crypto/test/crypto_SUITE.erl
The version of the fips provider may be different than rest of OpenSSL, as far from all OpenSSL versions have a *certified* fips provider.
Fix #9366
=> Add 'fips_provider_buildinfo' to crypto:info() map

lib/crypto/c_src/crypto.c, lib/crypto/c_src/mac.c, lib/crypto/c_src/mac.h
In the doc of EVP_MAC_fetch(), https://docs.openssl.org/3.0/man3/EVP_MAC
"The returned value must eventually be freed with EVP_MAC_free(3)."
This also ensures the same behaviour as in EVP_Q_mac which is used by NIF: crypto:mac/4.
note, without this fix there is no memory leak as openssl3 returns the same addr of 'mac' (for the same MAC type), the side effect is the refcnt keeps bumping but I think it still good to have this fix also consider the case where the libcrypto is used by other NIF.
update: 2nd thought, I think it may have the risk of refcnt overflow. 
update: yes. it causes refcnt overflow and triggers double free.
=> fix(crypto): mac_context_dtor should free MAC

erts/emulator/beam/dist.c, erts/emulator/beam/io.c, erts/emulator/beam/sys.h
=> erts: Suppress various NULL-pointer warnings

erts/emulator/beam/jit/arm/instr_bs.cpp, erts/emulator/beam/jit/arm/instr_common.cpp
This PR eliminates two crashes in the debug emulator for AArch64/ARM64.
=> Fix debug emulator bugs for AArch64

erts/emulator/nifs/common/zstd_nif.c, erts/emulator/zstd/zstd.mk, lib/stdlib/test/zstd_SUITE.erl
If we don't make a copy of the binary before referencing it in the dict and it is a heap binary, the binary will be released upon the next GC and the dict will segfault.
=> zstd: Fix copy of dict binary to environment

lib/ssl/src/ssl_config.erl, lib/ssl/src/tls_v1.erl
This fixes a bug handling default options when later setting of options changes the versions  option.  Some more commits enhancing socket options handling is also planned before finishing this PR.  And backporting of the bugfix to 27 track.
=> ssl: Handle defaults on version change

erts/emulator/beam/erl_process.c
In Erlang/OTP 22 functionality was added to yield after process "death" in order to send large error reasons for down/exit signals. This change meant that we not can be in state FREE, but the DELAYED_DEL_PROC is first set later, so the assert checking for it is incorrecy.
=> erts: Remove faulty assert checking for DELAYED_DEL_PROC flag

lib/xmerl/src/xmerl_eventp.erl, lib/xmerl/src/xmerl_regexp.erl, lib/xmerl/src/xmerl_sax_parser_base.erlsrc, lib/xmerl/src/xmerl_scan.erl, lib/xmerl/src/xmerl_simple.erl, lib/xmerl/src/xmerl_validate.erl, lib/xmerl/src/xmerl_xpath_pred.erl, lib/xmerl/src/xmerl_xsd.erl, lib/xmerl/src/xmerl_xsd_type.erl
- Rewrote some recursion when calling continuation fun to get more data.
- Remove all  old style catch calls
Fixes #9190
=> Fix a tail recursion bug

lib/asn1/doc/guides/asn1_getting_started.md, lib/asn1/src/asn1ct_gen_ber_bin_v2.erl, lib/asn1/src/asn1rtt_real_common.erl, lib/asn1/test/testPrim.erl
=> asn1: Fix several bugs in encoding and decoding of REALs

lib/stdlib/src/calendar.erl, lib/stdlib/test/calendar_prop_SUITE.erl, lib/stdlib/test/property_test/calendar_prop.erl
Added missing conversions.
Added proper tests. I've tried them locally with `proper`
I really hope it's not too late to get it into OTP 28...
Closes #8160
=> Feat: calendar:(universal/local)_time_to_system_time/1,2

lib/xmerl/src/xmerl.app.src
Was missing in the previous xmerl fix #9463
=> Fix updated runtime deps

lib/stdlib/scripts/update_deprecations
The script didn't produce results for an OTP release unless there was an MFA deprecated, scheduled for release, or removed for the release.
=> Fix update_deprecations script

lib/dialyzer/src/dialyzer.hrl, lib/dialyzer/src/dialyzer_cl_parse.erl, lib/dialyzer/src/dialyzer_options.erl, lib/dialyzer/test/opaque_SUITE_data/dialyzer_options, lib/dialyzer/test/overspecs_SUITE_data/dialyzer_options, lib/dialyzer/test/r9c_SUITE_data/dialyzer_options, lib/dialyzer/test/underspecs_SUITE_data/dialyzer_options, lib/dialyzer/test/user_SUITE_data/dialyzer_options, scripts/run-dialyzer
Fix https://github.com/erlang/otp/issues/9427
=> Turn on no_opaque_union option by default in Dialyzer

lib/mnesia/src/mnesia_controller.erl
During startup we postpone handling certain messages until after schema merge, they may be invalid and if so discard them.
For example the {i_have_tab, Tab, Node} where the table copy have been deleted on the Node, should not be handled.
=> mnesia: Discard old irrelevant msgs

lib/stdlib/src/lists.erl
Ensure that the first paragraph describing each function makes sense by itself when shown in the Summary part of the documentation.
Add examples to functions lacking examples.
While at it, also remove comments for documented functions, and remove out-commented code, and do some other minor clean ups.
=> Polish documentation for the lists module

lib/stdlib/src/erl_stdlib_errors.erl, lib/stdlib/src/json.erl, lib/stdlib/test/json_SUITE.erl
When printing errors include the position that the error occured at if included in the error.
=> Improve json decode error messages

erts/emulator/beam/erl_bif_re.c, lib/stdlib/test/re_SUITE.erl
=> erts: fix sub binary bug in erl_bif_re

lib/stdlib/src/erl_lint.erl, lib/stdlib/test/erl_lint_SUITE.erl
Fix https://github.com/erlang/otp/issues/9461
An invalid generator in a zip generator is excluded from the analysis for individual generators. If there is no valid generator in a zip generator, no analysis for generator is applied.
=> stdlib: Fix linter crash from invalid zip generators

erts/emulator/beam/erl_db.c, erts/emulator/beam/erl_db_util.h, lib/stdlib/src/ets.erl, lib/stdlib/test/ets_SUITE.erl
The current implementation of the `heir` option as given to `ets:new/2` and `ets:setopts/2` requires that a term is given as `HeirData` in a `{heir, HeirPid, HeirData}` 3-tuple, which will be sent in an `{'ETS-TRANSFER', ...}` message when the owner process dies and ownership passes to the heir process.
This is not always feasible, for example when the heir process is a supervisor which passes the table to a child process on (re-)starts. If the child process dies, the supervisor will receive an `'ETS-TRANSFER'` message, which it can't do anything with, and will just log it as an unexpected message.
This PR changes the behavior of `ets:new/2` and `ets:setopts/2` such that the `heir` option to also accepts a 2-tuple of the form `{heir, HeirPid}`, ie omitting the `HeirData`. If the owner …
=> `ets`: add ability to suppress heir/gift data

lib/compiler/test/beam_doc_SUITE.erl, lib/compiler/test/beam_doc_SUITE_data/cover_compiled.erl, lib/kernel/src/code.erl
This PR fixes a bug getting docs when a module is compiled by the cover module. Also, the `cover_compiled` error was [missing in the spec](https://github.com/erlang/otp/blob/master/lib/kernel/src/code.erl#L1848).
To reproduce, first compile the module via `cover:compile` and run `code:get_doc`.
Find this bug via the new `doctest`, for example:
````erlang
% src/otp_doctest
-module(otp_doctest).
-export([foo/0]).
-doc ~"""
```
> otp_doctest:foo().
bar % must fail
```
""".
foo() ->
foo.
````
```erlang
% rebar.config
{profiles, [
{test, [
{cover_enabled, true}
]}
]}.
```
```erlang
% test/otp_doctest_SUITE.erl
-module(otp_doctest_SUITE).
-behaviour(ct_suite).
-compile([export_all, nowarn_export_all]).
all() ->
[doctests].
doctests(Config) when is_list(Config) ->
shell_docs:test(otp_doctest, …
```
=> kernel: Fix `code:get_doc/1,2` when cover_compiled

erts/emulator/sys/win32/sys.c
On success, this function will return the result of CreateProcessW which upstream docs say will be "nonzero":
https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw#return-value
=> Fix documented return value

erts/emulator/beam/dist.h, erts/emulator/beam/external.c, erts/emulator/test/distribution_SUITE.erl
Cleans up a small spelling glitch.  Separate commits are put in order of increasing risk, as judged by an inexperienced eye.
=> spelling: "hopeful"

lib/stdlib/src/ets.erl
Note that the documentation already says that this function can return both boolean values, and it was the spec what was incomplete.
=> Return the right type from ets:update_element/4 spec

lib/stdlib/src/ets.erl
👋 
This PR adds the missing `{write_concurrency, auto}` tuple to `ets:info/1` return spec.
```erl
1> ets:info(ets:new(tab, [{write_concurrency, auto}])).
%> [{id,#Ref<0.1217228914.4266262529.13740>},
%> {decentralized_counters,true},
%> {read_concurrency,false},
%> {write_concurrency,auto}, % <--
%> {compressed,false},
%> {memory,1497},
%> {owner,<0.88.0>},
%> {heir,none},
%> {name,tab},
%> {size,0},
%> {node,nonode@nohost},
%> {named_table,false},
%> {type,set},
%> {keypos,1},
%> {protection,protected}]
```
=> Add write_concurrency auto to `ets:info/1` return spec

lib/tools/src/cover.erl
Before sending a message to the cover server, the `call` function checks if the server is running, starting it if it does not.
However, there is no locking/atomicity between the check and the start. If there is a concurrent call, the server might be started in parallel by another process and the `start()` call would return `{error, {already_started, _}}`. This causes the function to fail with a `badmatch` exception.
The code now accepts that the server is running after seeing the server as stopped and retrying the call.
=> cover: Fix a race condition in how the server is started as part of a call

erts/emulator/Makefile.in, erts/emulator/zstd/zstd.mk, erts/lib_src/Makefile.in
=> Fix having `-O2` in path to otp repo

lib/stdlib/src/ets.erl
These examples can be rendered as erlang :)
=> Rendering code snippets in docs as erlang instead of plain-text

lib/stdlib/src/dets.erl, lib/stdlib/src/dets_utils.erl, lib/stdlib/src/dets_v9.erl
Completes the work started in #9232.
=> dets: Update all error_logger calls to be logger calls

lib/inets/src/http_client/httpc.erl
The default `string` option converts messages from the client from binary to string. `binary` is the default, e.g. `test/httpc_SUITE.erl`, `receive_streamed_body`.
=> inets: Document asynchronous httpc request body format

lib/compiler/test/compile_SUITE.erl, lib/compiler/test/test_lib.erl
On 32-bit Windows systems, there is typically only 2 GiB of available virtual adress space. Some of our memory-hungry test cases (especially `compile_SUITE:core_roundtrip/1`) occasionally crash when the virtual address is exhausted.
In an attempt to reduce fragmentation of the allocated memory, change `test_lib:p_run/2` to not spawn any new processes on 32-bit systems, but instead run all tasks sequentially in single process.
=> compiler tests: Avoid running out of virtual address space

lib/stdlib/src/maps.erl
Ensure that the first sentence describing each function makes sense by itself when shown in the Summary part of the documentation.
Don't say the the order is arbitrary for functions that accept an ordered iterator.
Consistently mark examples using `## Examples`.
While at it, also remove comments for documented functions, and remove out-commented code, and do some other minor clean ups.
=> Polish documentation for the maps module

lib/kernel/doc/guides/socket_usage.md
Add a chapter to the socket usage guide, describing all the 'socket' configure options.
=> Add a configure chapter to the socket usage guide

lib/mnesia/test/mnesia_evil_coverage_test.erl
We're doing dirty writes with multiple nodes, and by default mnesia:dirty_write waits only for 1 node to complete. We must wait for all nodes to finish, and then check table size.
=> Fix race condition in mnesia_evil_coverage_test:table_info

lib/compiler/src/compile.erl
It's confusing/irritating that the MD5 of preloaded modules given by `m(Module).` doesn't match that given by `beam_lib:md5(Beam).`
The problem can be traced back to commit 435fce8 which introduces the enabled_features tuple in the Meta chunk - even if there are no enabled features.
Since `erts/emulator/utils/make_preload` doesn't include the Meta chunk the md5 sums don't match.
Assuming preloaded modules won't include features that aren't part of the standard Erlang release this PR fixes the problem by not including an empty enabled_features tuple in the Meta chunk.
=> Don't include enabled_features tuple when there are none

lib/stdlib/src/binary.erl, lib/stdlib/src/lists.erl, lib/stdlib/src/maps.erl, lib/stdlib/src/shell_docs_test.erl, lib/stdlib/src/zstd.erl
:warning: nested `case` does not spark joy and RegExp might be a better choice for this feature request!
This patch aims to formally begin the discussion here about feature parity between Erlang OTP doctest, and the library of the same name maintained by [williamthome](https://github.com/williamthome/doctest/)
Specifically this patch targets `>` vs `1>` syntax for declaring the start of a testable code line or set of lines, ex;
**Erlang OTP doctest**
````erlang
-doc """
This test is how we do with `erlang/otp` doctests
```
> true.
true
> totallyOkay.
totallyOkay
```
"""
woot() -> ok.
````
**williamthome doctest**
````erlang
-doc """
This test is how we do with `williamthome/doctest` (prior to version `0.10.0`)
```erlang
1> false.
false
2> thisIsFine.
thisIsFine
```
"""
muchJoy() -> ok. …
```
=> doctest allow int/line-number prefix

system/doc/tutorial/nif.md
Previously, a tab character was used, which doesn't syntax highlight correctly in hexdocs. This has been changed to use spaces instead.
Before:
After:
=> Fix whitespace in NIF tutorial for syntax highlighting

erts/preloaded/src/atomics.erl, erts/preloaded/src/counters.erl
Both `atomics` and `counters` modules describes `index from 1 to N`:
```
- Indexes into atomic arrays are one-based. An atomic array of arity N contains
N atomics with index from 1 to N.
```
```
- Indexes into counter arrays are one-based. A counter array of size N contains
N counters with index from 1 to N.
```
=> erts: Fix index type in `atomics` and `counters` modules

lib/ssh/src/ssh.hrl, lib/ssh/src/ssh_fsm_userauth_server.erl, lib/ssh/src/ssh_options.erl, lib/ssh/test/ssh_options_SUITE.erl, lib/ssh/test/ssh_protocol_SUITE.erl, lib/ssh/test/ssh_to_openssh_SUITE.erl
bannerfun/1 enables the server to send a SSH_MSG_USERAUTH_BANNER at the beginning of user authentication, immediately after receiving the first SSH_MSG_USERAUTH_BANNER
=> ssh: Add bannerfun to the server role

lib/stdlib/src/erl_error.erl, lib/stdlib/test/shell_SUITE.erl
Today, when printing an Erlang stacktrace, we return location information in a custom `(PATH, line LINE)` format. E.g.:
```
in function  lists:member/2
called as lists:member(1,not_a_list)
*** argument 2: not a list
in call from test:main/0 (test.erl, line 8)
```
A more common notation would be `/path/to/filename:line_number`, which is used in many programming tools and languages to specify a location in a file. This would also be in line with what the Erlang compiler returns:
```
erlc test.erl
test.erl:8:16: syntax error before:
%    8|   lists:member(1
%     |                ^
```
While the `PATH:NUMBER` does not seem to be an official standard, it's a widely adopted and understood convention across various development communities.
Switching to the new …
=> Use conventional FILE:LINE format for locations in stacktraces

lib/stdlib/src/gen_server.erl, lib/stdlib/src/stdlib.app.src, lib/stdlib/test/gen_server_SUITE.erl, lib/stdlib/test/supervisor_SUITE.erl
While working on something entirely different, it ocurred to me that timeouts in `gen_server` have some drawbacks and pitfalls.
When the return of `gen_server:init` or a `handle_*` callback contains a timeout, the next iteration will wait for a message for that time, and if no message arrives, instantly call `handle_info` with the message `timeout` (ie, not _sending_ itself a `timeout` message).
For one, this convolution of `handle_info` for message and timeout handling makes it impossible to distinguish an actual timeout from the message `timeout` having been received. This means that you either have to make sure that, if you are using timeouts, such a message will not be sent to your `gen_server` implementation, or live with possible premature "fake" timeouts.
For another, it is very …
=> Augment `gen_server` timeout handling

lib/stdlib/src/gen_server.erl
=> stdlib: Fix gen_server start documentation

lib/stdlib/src/math.erl
It turns out that different platforms produce slightly different values for `exp(1)`. Change the example to ensure it can't make the doctest fail.
=> math: Make the `exp/1` example portable

HOWTO/DOCUMENTATION.md
Based on other `since` tags and the linked comments, this looks like the correct syntax:
- https://github.com/erlang/otp/pull/9472#issuecomment-2708306874
- https://github.com/erlang/otp/pull/9515#issuecomment-2706116266
=> howto: Fix syntax for `since` tags & grammar

lib/kernel/src/inet_db.erl, lib/kernel/test/inet_SUITE.erl
Fixes a bug in CNAME loop detection. This bug can be exploited and leads to OOM.
=> kernel: Fix CNAME loop detection

lib/compiler/src/v3_core.erl, lib/compiler/test/zlc_SUITE.erl, lib/debugger/src/dbg_ieval.erl, lib/debugger/test/zlc_SUITE.erl, lib/stdlib/src/erl_eval.erl, lib/stdlib/test/erl_eval_SUITE.erl
Fix https://github.com/erlang/otp/issues/9435
A failed simultaneous binding from a strict generator and a relaxed generator always crash the comprehension. All bindings within a generator happen "at the same time" for user. Switching the order of generators within a zip generator cannot change the result of the comprehension.
=> compiler: Fix simultaneous binding of variables in zip generator

lib/stdlib/src/sys.erl
Link was `handle_system_message/6` and should be `handle_system_msg/6`
=> stdlib: update broken link in docs for sys:get_status/2

lib/kernel/src/code.erl
It says it expects `line_coverage`, but it should be `line`.
=> Fix the type of code:coverage_mode()

lib/stdlib/doc/src/sofs.md, lib/stdlib/src/sofs.erl, lib/stdlib/test/sofs_SUITE.erl
Ensure that the first paragraph describing each function makes sense by itself when shown in the Summary part of the documentation.
Add examples to functions lacking examples.
While at it, do some other minor clean ups.
=> Polish documentation for the sofs module

HOWTO/RELEASE-NOTES.md
The [text](https://github.com/erlang/otp/blob/5650226bc6474b05b4c28c3d1c7deffc87b14485/HOWTO/RELEASE-NOTES.md#bug-fixes) may be too concise. Additions and improvements are welcome.
=> Add release notes doc section about bug fixes

lib/stdlib/src/proc_lib.erl, lib/stdlib/test/proc_lib_SUITE.erl
If user set the initial_call to undefined or something else, the shells process list function 'i()' crashed.
=> Fix crash in initial_call

erts/doc/guides/alt_dist.md
`f_recv` handler takes 3 parameters not two. Fix documentation.
=> Fix signature of `f_recv` in alt_dist doc

erts/emulator/beam/emu/ops.tab, erts/emulator/beam/jit/arm/instr_common.cpp, erts/emulator/beam/jit/arm/ops.tab, erts/emulator/beam/jit/asm_load.c, erts/emulator/beam/jit/x86/instr_common.cpp, erts/emulator/beam/jit/x86/ops.tab, lib/compiler/src/beam_asm.erl, lib/compiler/src/beam_dict.erl, lib/compiler/src/beam_disasm.erl, lib/compiler/src/beam_flatten.erl, lib/compiler/src/beam_validator.erl, lib/compiler/src/genop.tab, lib/compiler/test/beam_debug_info_SUITE.erl
The `entry` form of the debug line was troublesome to handle in the loader. Include an atom in the instruction to indicate whether it is an entry or plain debug_line.
=> Extend the `debug_line_entry` instruction

lib/compiler/src/beam_ssa_destructive_update.erl, lib/compiler/test/beam_ssa_check_SUITE_data/tuple_inplace_checks.erl
Fix the compiler crash when the inner-most tuple in a nested tuple with 3 layers is updated.
=> compiler destructive update: Fix bug in nested patches

erts/emulator/test/bif_SUITE.erl, erts/preloaded/src/erlang.erl, system/doc/efficiency_guide/system_limits.md
Ensure that the first sentence describing each function makes sense by itself when shown in the Summary part of the documentation.
Add more examples.
While at it, also remove comments for documented functions, and remove out-commented code, and do some other minor clean ups
=> erlang: Polish documentation for the Term group of BIFs

lib/stdlib/src/gen_server.erl, lib/stdlib/test/gen_server_SUITE.erl
Mainly documentation for the new `gen_server` event time-outs, continuation of PR #9287.
I also added handling of time `infinity`, for completeness, because `gen_statem`'s event time-outs handles that, and also since all values allowed for legacy time-outs should work for the new event time-outs.
Test case for `Time = infinity` is still missing.
Please review the documentation, I am thinking of you; @juhlig and @Maria-12648430...
Related PRs: #9287 and #9615
=> Finish `gen_server` event time-outs

.github/scripts/otp-compliance.es, HOWTO/SBOM.md, erts/autoconf/vendor.info, erts/emulator/asmjit/vendor.info, erts/emulator/beam/vendor.info, erts/emulator/openssl/vendor.info, erts/emulator/pcre/vendor.info, erts/emulator/ryu/vendor.info, erts/emulator/zlib/vendor.info, erts/emulator/zstd/vendor.info, lib/common_test/priv/vendor.info, lib/common_test/test_server/vendor.info, lib/erl_interface/src/openssl/vendor.info, lib/stdlib/test/json_SUITE_data/vendor.info, lib/wx/vendor.info, make/autoconf/vendor.info
We check if purls are added in their corresponding `vendor.info` files.
If so, we generate an `externalRefs` field with the purl of the vendor library.
Usually, if the vendor has a specific way of being referred to, we should follow that.
Otherwise, we follow the [PURL Specification](https://github.com/package-url/purl-spec/blob/main/PURL-TYPES.rst)
=> add purls to all vendor libraries

lib/snmp/src/manager/snmpm.erl, lib/snmp/src/manager/snmpm_config.erl, lib/snmp/src/manager/snmpm_mpd.erl, lib/snmp/test/snmp_manager_SUITE.erl
SNMP manager
When receiving an (v3) inform (request), use EngineID and (just) Address to check if Engine is known
(do not include the port number).
Some agents send notifications using ephemeral ports (random port), so including this (the used port number) in the
check (if the engine is known) does not work.
=> Is EngineID known

lib/tools/emacs/erlang.el
As with `erlang-argument-indent`, the value should be either nil or an integer.
=> emacs: fix erlang-icr-indent definition

lib/ssh/src/ssh.hrl, lib/ssh/src/ssh_connection.erl, lib/ssh/src/ssh_options.erl, lib/ssh/test/ssh_to_openssh_SUITE.erl
allow/deny/log "direct-tcpip" channel open in daemon
=> ssh: tcpip_tunnel_in callback function

lib/stdlib/src/gen_statem.erl
"more effective" would mean that the simulation does entering and waking up from hibernation with greater effect than `hibernate`
=> Correct wording in `gen_statem` docs

.elp.toml
1. Some modules in sdtlib includes some headers from other directories and apps using a simple `-include` directive, causing ELP to fail resolving those inclusions. This diff provides corresponding customizations.
2. dialyzer uses VSN macro. Without a value ELP fails to correctly handle files using it, - specifying a dummy value `"DEFAULT_VSN"`.
3. The same is for `compiler` and `COMPILER_VSN`.
--- 
Testing.
There is a way to test whether ELP now understands the project - to run `eqwalizer` for all the modules.
I tested it in https://github.com/ilya-klyuchnikov/otp/tree/eqwalizer-main branch - which includes this plus 3 other small changes to make OTP repo eqwalizable. 
1. https://github.com/ilya-klyuchnikov/otp/commit/62769afa25e8ecf8cc538d00f6b3602300280012 - deleting …
=> .elp.toml - configuring ELP to resolve all files and macros in OTP libs

lib/xmerl/src/xmerl_xpath.erl, lib/xmerl/src/xmerl_xs.erl
- Corrected spec of xmerl_xs:value_of/1
- Also replaced '_' in the type specs of xmerl_xs:select/2 and xmerl_xpath:string/2/3 with a specified return value to improve documentation.
=> Correct faulty type spec

lib/compiler/src/Makefile, lib/compiler/src/cerl_inline.erl, lib/edoc/src/Makefile, lib/edoc/src/edoc_layout.erl, lib/eunit/src/Makefile, lib/syntax_tools/src/Makefile
`doc_layout` and `cerl_inline` are only two modules in OTP that have warnings "variable X is shadowed in ...".
Renaming variables so that there is no shadowing anymore.
- the practical reason - https://github.com/erlang/otp/pull/9674 - to make code better for tooling (ELP/eqWAlizer)
=> fix warnings "variable X is shadowed in ..."

.github/dockerfiles/.profile
The ssh tests do a ssh to localhost for compatability testing and we don't want to start these services again when they are run.
=> gh: Only do initialization once when testing

lib/tools/src/tprof.erl, lib/tools/test/tprof_SUITE.erl
👋 
`session_name` doesn't seem to be documented anywhere and without knowing about it it's not possible to create multiple trace sessions through `tprof`. Could it be that `session` was meant to be used?
---
(I haven't run tests, I'm still figuring out how to do it!)
=> Use `tprof` `session` name in `trace:session_create`

lib/stdlib/src/shell_docs.erl
Invoking help about function in module in Erlang shell raised exception in shell_docs:render_function/3.
The exception was due to a missing pattern match on the return value of `beam_lib:chunks/2`.
Split the function in two, one handling errors from `find_path/1`; the other handling the return value of `beam_lib:chunks/2`.
=> help in Erlang shell raised exception

lib/kernel/src/gen_sctp.erl
Make it clear that `{sctp_nodelay, true}` actually **turns off** the Nagle.
=> kernel: gen_sctp: clarify description for `sctp_nodelay`

erts/doc/references/erl_cmd.md, erts/emulator/beam/erl_init.c, erts/emulator/beam/jit/beam_asm.h, erts/emulator/beam/jit/beam_jit_main.cpp, erts/emulator/beam/jit/beam_jit_metadata.cpp, erts/emulator/test/jit_SUITE.erl
This adds support for a `+JPperfdirectory <directory>` cli arg which allows changing the location used for the `jit<pid>.dump` and `perf<pid>.map` files which prior to this always went into `/tmp`.
The motivation is so that a different mount from `/tmp` can be used.
Example usage:
```console
[ ~/otp/bin @issue/9500 ] $ mkdir /testdir
[ ~/otp/bin @issue/9500 ] $ ./erl -noinput -eval 'io:format("I am ~s~n", [os:getpid()]).' -s init stop +JPperf true +JPperfdirectory /testdir
I am 149279
[ ~/otp/bin @issue/9500 ] $ ls /testdir/
jit-149279.dump  perf-149279.map
```
Without it, they still go to `/tmp/`:
```console
[ ~/otp/bin @issue/9500 ] $ ./erl -noinput -eval 'io:format("I am ~s~n", [os:getpid()]).' -s init stop +JPperf true
I am 209905
[ ~/otp/bin @issue/9500 ] $ ls /tmp/*209905* …
```
=> Add support to `erl` for `+JPperfdirectory <directory>`

erts/doc/references/erl_nif.md, erts/emulator/Makefile.in, erts/emulator/utils/make_driver_tab
Extend the `--enable-static-nifs` `configure` option to allow two things
- Use a single `.a` archive for multiple NIF modules
- Specify the `<name_of_module>_nif_init` prefix directly instead of relying on the filename
Both of these simplify or enable usage of Rustler libraries in static builds (e.g. for usage on iOS):
- `cargo` makes it difficult to ensure that a `module.a` file is created while at the same time `module` is known at compile-time to generate the `module_nif_init` function
- Linking Rust's standard library into two `.a` archives and then linking these together into a single resulting binary is not supported
With this PR, two Rust libaries can be linked into a single static library (side-stepping the issue with the standard libary) and the symbol names can be chosen …
=> Extending static NIF configure options

lib/ssl/src/ssl_gen_statem.erl, lib/ssl/src/tls_record_1_3.erl
RFC 8446 section 6.2 states a pre-connection user_canceled alert should be followed by a close_notify alert. In these states, these alerts may be sent in the clear.
This PR fixes the handling of both alerts by:
1. Ignoring the alert level which is unused in TLS 1.3
2. Returning close_notify alert as well as user_canceled
This PR also lowers the logging level of the user_canceled alert since this is a perfectly valid client action which should not spam the server log.
=> Handle TLS 1.3 closure alerts consistently

erts/emulator/beam/erl_init.c, erts/test/erlexec_SUITE.erl
Code pattern and naming is copied from similar cases from this file.
Should we add some testcases for it? If yes, where exactly? (my first contribution to ERTS...)
Props to issue author for clues.
Fixes #9668
=> fix: erts +t, +P, +Q arg overflow

erts/emulator/beam/erl_gc.c, erts/emulator/test/trace_call_memory_SUITE.erl, lib/kernel/src/trace.erl
Tracing functions with `call_memory` could report arbitrarily incorrect values for consumed memory. Even negative values. This could happen if the traced process called BIFs that yielded while delaying garbage collection, like `binary_to_list/1`.
=> Fix bug in call_memory tracing when calling BIFs that delay GC

make/ex_doc_wrapper.in, make/fixup_doc_links.sh
Sometimes the otp_version.table version get out of sync with the version in lib/app/vsn.mk, so we use the vsn.mk values as they are the correct ones.
=> docs: Fix link vsn fixup to use .mk vsn values

.github/workflows/pr-comment.yaml
The PR comment workflow had stopped running since it used Ubuntu 20.04 LTS for some jobs, which was retired by GitHub Actions on 15th April:
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
This PR replaces Ubuntu 20.04 with the latest Ubuntu version at the time of running the workflow.
=> Fix PR Comment Workflow

erts/emulator/test/jit_SUITE.erl
Fixes test introduced in #9639
=> erts: Skip perfdir tests when perf not available

erts/test/erlexec_SUITE.erl
The testcases for testing long paths never worked properly on windows. This change merges the two tests into one and makes them work on windows.
Followup on #9331
=> erts: Fix erlexec long_path_env testcase

erts/preloaded/src/erlang.erl
Fix typo reasource → resource in https://github.com/erlang/otp/blob/10e20b1dbe39b056fab430e50b08cb4f3696ae87/erts/preloaded/src/erlang.erl#L8489
=> Fix typo reasource → resource in otp/erts/preloaded/src/erlang.erl

lib/common_test/src/ct.erl, lib/common_test/src/ct_gen_conn.erl, lib/common_test/src/ct_suite.erl, lib/common_test/src/ct_telnet.erl, lib/common_test/src/test_server.erl, lib/eldap/src/eldap.erl, lib/eunit/src/eunit_proc.erl, lib/inets/src/inets_app/inets_lib.erl, lib/kernel/src/gen_tcp.erl, lib/observer/src/ttb.erl, lib/odbc/src/odbc.erl, lib/os_mon/src/disksup.erl, lib/os_mon/src/memsup.erl, lib/ssh/src/ssh_agent.erl, lib/ssh/test/ssh_test_lib.erl, lib/stdlib/src/dets.hrl
As suggested in #9515. In some parts of the code, `pos_integer()` is currently used for timeouts, which can't be replaced with `timer:time()` as it is specified as `integer() >= 0`.
Locally tested by running dialyzer with updated preloaded code.
=> Use timer:time for non-negative timeout values

erts/emulator/beam/erl_process.c
This reverts commit d86d313ee6f62423208ac696986f45bad3350f6b.
The reverted commit frequently leaves one or more schedulers out of work when there actually is work to do.
The simplest example: We have two schedulers and two processes executing full time currently located on the same scheduler. Both processes will be left on the scheduler where they are currently located, instead of one of them being stolen by the scheduler that is out of work. This since the scheduler performing work will always be executing one process while the other process exist in the run queue, i.e, the run-queue length is always 1. The work stealing functionality will leave the system in this state until something else changes the state of the system.
=> Revert "Don't steal task when there is a single one"

erts/emulator/beam/beam_debug.c, erts/emulator/test/statistics_SUITE.erl
Failures while all dirty schedulers hogged resulted in timeout instead of failure
=> Fix scheduler_wall_time tests in statistics_SUITE

erts/configure, lib/crypto/configure, lib/erl_interface/configure, lib/megaco/configure, lib/odbc/configure, lib/wx/configure, make/autoconf/otp.m4, make/configure
Seen to cause notable performance regressions due to large stack allocated variables (#9759). Skip `-ftrivial-auto-var-init=zero` until we have purged the code base from all such large stack frames.
=> Remove -ftrivial-auto-var-init=zero as default OSSF compile option 

lib/diameter/src/base/diameter_types.erl, lib/diameter/test/diameter_codec_SUITE.erl, lib/diameter/test/diameter_codec_test.erl
This PR consists of two commits;
* [diameter: DiameterURI port defaults to 3868](https://github.com/erlang/otp/pull/9321/commits/50661d8bfe71cccddccfd466d4443a685b5a82e1)
This fixes the crash when decoding a DiameterURI without a port number. The crash always happens if an Diameter answer with an AVP of type DiameterURI without port number is decoded, since the `rfc` option cannot be specified when handling an answer.
* [diameter: DiameterURI transport defaults to tcp](https://github.com/erlang/otp/pull/9321/commits/d69f9353c7a28b78a465ee62e3417e5c0b007d6a)
When `rfc` is missing in the option, the transport part of the `diameter_uri` becomes an empty atom (''), which causes the diameter module to fail to re-encode the decoded AVP (because it won't match `diameter_types:'DiameterURI'/3` …
=> diameter: default port and transport for DiameterURI

.github/scripts/otp-compliance.es, .github/workflows/main.yaml
Uploads SBoM in SPDX 2.2 format to Github's dependency submission API. 
This lets Erlang/OTP receive Dependabot alerts for SPDX packages. In Erlang's case, this will allow us to track vulnerabilities in vendor dependencies. 
For this to work with Dependabot, we should include packages with semantic versioning, not commit hashes. Not all vendor libraries in the SBoM will be tracked, but most of them will (e.g., `asmjit` and `fp16` will not be tracked; `zlib`, `pcre`, `tcl`, `zstd`, `autoconf`, and `openssl` should be tracked, in theory, based on their `purl`).
=> adds dependabot alerts for vendor packages

lib/stdlib/src/io_lib.erl, lib/stdlib/src/io_lib_format.erl, lib/stdlib/src/io_lib_pretty.erl, lib/stdlib/src/string.erl, lib/stdlib/test/io_SUITE.erl
This can be used to directly create utf8 binaries instead of iolists.
Slightly slower for some usage input but the result uses a lot less memory on 64b systems.
=> Introduce bfwrite and bformat functions

erts/emulator/beam/external.c, erts/emulator/beam/external.h
Remove use of struct `ErtsDistExternal` which contains a large atom cache table (64kb). The atom cache is not even used by `binary_to_term` and just consumes native stack space. With compiler option `-ftrivial-auto-var-init=zero` it gets really bad as it zeroes all those 64kb for each call.
=> Optimize binary_to_term

lib/tools/src/tools.app.src
The tprof profiler is not present in the .app.src file. This causes that tprof is not part of the release and, as a result, possibly not available in an installed system. This PR just adds tprof to tools.app.src.
=> tprof added to tools.app.src

.github/scripts/sync-github-releases.sh, .github/workflows/sync-github-releases.yaml
The github markdown rendered for releases render newlines as `<br/>` so the release notes tend to look a bit strange. This change updated the sync tool to format all the bodies of all releases to look correct.
=> gh: Format all markdown release bodies

lib/eunit/src/eunit_serial.erl, lib/eunit/test/eunit_SUITE.erl
When running tests in parallel 'cancel' messages are sometimes picked up before the 'begin' message for the same test case, causing the cancelled test to be siliently ignored. This commit checks the eunit_serial inbox for such 'begin' message and makes sure the cancelled test is reported.
=> eunit: Ensure failed setup is not silently ignored

lib/xmerl/src/xmerl_sax_parser.erl, lib/xmerl/src/xmerl_sax_parser.hrl, lib/xmerl/src/xmerl_sax_parser_base.erlsrc, lib/xmerl/test/xmerl_sax_SUITE.erl, lib/xmerl/test/xmerl_sax_SUITE_data/two_messages_with_ws_between.xml
Add an option to discard whitespace before the xml tag when reading from a stream.
Also updated a bad error message.
=> Add option to discard whitespace before xml tag

erts/doc/guides/erl_ext_dist.md
In the documentation of `term_to_binary/2` `{minor_version, 2}` it is already clarified that "This is as of Erlang/OTP 26.0 the default. Atoms are unconditionally encoded using utf8."
=> Minor: Update docs about atom encoding format on External Term Format page

erts/emulator/test/nif_SUITE_data/nif_SUITE.c
Expected ErlNifPort instead ErlNifPid:
nif_SUITE.c:2866:43: error: passing argument 3 of 'enif_whereis_port' from incompatible pointer type [-Wincompatible-pointer-types]
=> erts: fix incompatible pointer type

erts/emulator/beam/beam_bif_load.c, erts/emulator/test/signal_SUITE.erl
Fixes https://github.com/erlang/otp/pull/9604#issuecomment-2791560906
=> erts: Check process registers during CLA check

lib/debugger/src/Makefile, lib/et/src/Makefile, lib/observer/src/Makefile, lib/reltool/src/Makefile, lib/wx/examples/demo/Makefile, lib/wx/examples/simple/Makefile, lib/wx/examples/sudoku/Makefile
The following applications:
- et
- observer
- debugger
- reltool
And also the wx/examples/[simple,demo,sudoku] depends on wx application in order to build properly.
When cross compiling Erlang/OTP [1], there are cases where the initial bootstrap system (which in most of the cases is just the same Erlang/OTP version but built for host) may not have Erlang wx application enabled. Thus when cross compiling the above applications will not able to found wx.hrl and wx behaviour files.
That is because the target build should look into ERL_TOP in order to see the missing dependencies.
Without the proper ERL_COMPILE_FLAGS the build will try to use from the host system, which in my case does not have wx enabled.
1: https://github.com/erlang/otp/blob/master/HOWTO/INSTALL-CROSS.md
=> Add missing wx dependencies

erts/emulator/beam/atom.names, erts/emulator/beam/bif.tab, erts/emulator/beam/erl_debugger.c, erts/emulator/beam/erl_term.h, erts/emulator/test/erl_debugger_SUITE.erl, lib/kernel/src/erl_debugger.erl
The `erl_debugger` module currently exposes a BIF to toggle line-breakpoints, but there was no mechanism to query the status. We add BIFs that, for a give module or for a given MFA, will return all lines that allow breakpoints being set and what their status is.
The main motivation is to allow the edb debugger to implement stepping-over and stepping-out without requiring the module to be available on disk, and compiled with `debug_info`.
=> erl_debugger: Add BIFs to list available line breakpoints and their status

erts/emulator/beam/external.c, erts/emulator/beam/external.h
Shrink `ErtsAtomTranslationTable` from 2048 to 255 slots. Only 255 slots can be used (0-254) as only one byte is used in distribution header for `NumberOfAtomCacheRefs` and in `ATOM_CACHE_REF` for `AtomCacheReferenceIndex`.
This will probably not be a significant performance gain as it will only affect the native stack frame size of `erts_net_message()`.
=> Shrink ErtsAtomTranslationTable to correct max size

lib/public_key/src/public_key.erl
Fix #9828 by renaming the internal function as suggested by @IngelaAndin.
=> Fix typo: fqnds/fqdns

erts/preloaded/src/erlang.erl
Corrected `backtrace_depths` to `backtrace_depth` in `system_flag/2` fn of `erts/preloaded/src/erlang.erl` and corresponding test data file `unknown_erlang_system_flag_2_func.txt`.
=> Fix typo in erts/erlang:system_flag/2 documentation comment

lib/compiler/src/beam_ssa_alias.erl, lib/compiler/test/beam_ssa_check_SUITE_data/alias.erl
Previously all bifs selected by the erl_internal:comp_op/2 predicate was erroneously considered safe from an aliasing perspective. This is not true as they, depending on the argument types, could access internal elements of a term which has been destructively updated. As this makes the destructive update visible, this is illegal and should not happen.
To fix this problem, we have to consider all comparison bifs as aliasing operations, thus avoiding the problem described above. Unfortunately this is a very pessimistic solution, and by making use of type information we can avoid forced aliasing when it can be determined that the comparison bif will be reduced to a simple tag test.
This is less conservative fix than the one presented in #9833.
Closes #9813.
=> compiler: Fix alias analysis bug (less conservative version of #9833)

.github/workflows/main.yaml, otp_build
If we build any other program, it will currently overwrite the optimized programs which is not what we want in a release as then they will all be debug instead of optimized.
=> otp: Only build and release debug emulator

lib/kernel/src/inet.erl
Ad basic info about default buffer sizes for (SCTP, TCP and UDP) sockets.
=> Document the default buffer sizes

lib/ssl/src/ssl_gen_statem.erl, lib/ssl/src/tls_handshake_1_3.erl, lib/ssl/test/tls_1_3_version_SUITE.erl
That is alerts that happens before any encryption is applied and there is no keys to log.
Also add missing maybe_keylog for server when path validation alert is issued for the client certificate chain.
=> ssl: hs_keylog callback properly handle alert in intial states

lib/eldap/src/eldap.erl
Hello! That is probably a typo. There is no actual need to wrap a filter into a tuple before negating.
=> eldap: fix typespec

lib/stdlib/src/zip.erl, lib/stdlib/test/zip_SUITE.erl
Before this change, if any operation failed on files within the archive only a generic badarg/enoent error would be returned. Now the filename and arguments used will be returned which makes it a lot easier to debug.
=> zip: Improve returned errors

.github/dockerfiles/Dockerfile.ubuntu-base, .github/scripts/build-base-image.sh
When building the base image for old releases we should include the old release - 2 and not the currently newest release -2.
=> gh: Use correct old erlang versions for testing

lib/public_key/doc/guides/public_key_records.md, lib/public_key/include/public_key.hrl, lib/public_key/src/pubkey_cert_records.erl, lib/public_key/src/public_key.erl
=> public_key: Add missing macros

lib/stdlib/doc/assets/tic-tac-toe.es, lib/stdlib/doc/guides/terminal_interface.md
The example code read `{ok, Chars} = io:get_chars(...)`, but [`io:get_chars/2`](https://www.erlang.org/doc/apps/stdlib/io.html#get_chars/2) returns string() | unicode:unicode_binary() or {error, _} | eof, so update the example.
=> stdlib: Fix terminal application example

lib/runtime_tools/src/dbg.erl
Consider following `dbg` getting started guide https://www.erlang.org/doc/apps/runtime_tools/dbg.html  
```erlang
1> dbg:tracer().  % Start the default trace message receiver
```
If performed over remsh (e.g. when debugging a production node), default tracer prints all its messages to `user` process on the main node. This leads to no data printed to the shell which started the tracer, making dbg unusable for novice remsh users.  
In this PR I make default tracer aware of remsh, and when remsh is detected, the output is sent to remote group_leader.  
For local calls behaviour stays as before -- default output is `user` process.
=> [dbg] make simple tracer() remsh-friendly

lib/crypto/c_src/digest.c, lib/crypto/c_src/openssl_config.h, lib/crypto/doc/guides/algorithm_details.md, lib/crypto/src/crypto.erl, lib/crypto/test/crypto_SUITE.erl
An updated version of https://github.com/erlang/otp/pull/7680/files
=> Add SHA2 512/224 and SHA2 512/256 truncated hashes

lib/stdlib/src/edlin_expand.erl, lib/stdlib/test/edlin_expand_SUITE.erl
What this code does is that it filters out all the keys that we are not able to autocomplete, leaving a list of atoms that we are able to autocomplete.
In the future we will support more key types other than atoms.
Closes #9837
=> stdlib: edlin_expand should not crash when trying to complete a map

lib/kernel/src/user_drv.erl, lib/kernel/test/interactive_shell_SUITE.erl, lib/stdlib/src/shell.erl
=> Remote shell should not terminate the remote node on EOF

lib/kernel/src/group.erl, lib/kernel/test/interactive_shell_SUITE.erl
When io:setopts is called without specifying line_history it would be set to a list, which would be interpreted as false.
closes #9863
=> kernel: Fix line_history to not be reset by io:setopts

lib/stdlib/src/shell.erl, lib/stdlib/test/shell_SUITE.erl
Now you can type `lists:map(fun is_atom/1, [])` or `lists:map(fun my_func/1, [])`, in the shell,
instead of `lists:map(fun erlang:is_atom/1, [])` or `lists:map(fun shell_default:my_func/1, [])`.
Closes #9771
=> stdlib: support 'fun f/a' expressions in the shell

lib/kernel/src/rpc.erl
The original wording included an incorrect double negation ("won't not"). While at it, rephrased the entire note for clarity.
=> Rephrase note for the rpc module

lib/asn1/src/asn1rt_nif.erl, lib/crypto/src/crypto.erl, lib/os_mon/src/os_mon.erl, lib/public_key/src/pubkey_os_cacerts.erl, lib/runtime_tools/src/dbg.erl, lib/runtime_tools/src/dyntrace.erl, lib/wx/api_gen/gl_gen_erl.erl, lib/wx/src/gen/gl.erl, lib/wx/src/wxe_util.erl
A recent change made erlang:system_info(system_architecture) return x86_64-pc-windows instead of win32 which broke all priv dir lookups on windows.
=> otp: Fix all nif/driver loading to use win32 for windows

lib/ssl/src/ssl_config.erl, lib/ssl/test/ssl_api_SUITE.erl
Relax the psk_identity validation to allow the client to provide an empty string.
=> ssl: Allow empty psk identity

lib/compiler/src/beam_ssa_check.erl, lib/compiler/src/beam_ssa_destructive_update.erl, lib/compiler/src/compile.erl, lib/compiler/test/beam_ssa_check_SUITE.erl, lib/compiler/test/beam_ssa_check_SUITE_data/phis.erl
Fix https://github.com/erlang/otp/issues/9987.
Previously, when patching multiple phi nodes with the same from-label, only one of them was used because we used `maps:from_list`.
=> compiler: Fix compiler crash with multiple phi patches

lib/public_key/doc/guides/public_key_records.md, lib/public_key/doc/public_key_app.md, lib/public_key/include/public_key.hrl, lib/public_key/src/pubkey_pbe.erl, lib/public_key/src/public_key.erl, lib/public_key/src/public_key_internal.hrl, lib/public_key/test/erl_make_certs.erl, lib/public_key/test/public_key_SUITE.erl
=> public_key: Adjust macros and records in public include and doc

lib/public_key/src/public_key.erl
=> public_key: Add TBSCertificate cluse to get_asn1_module

lib/ssh/src/ssh_sftpd.erl, lib/ssh/test/ssh_sftpd_SUITE.erl
- generate unique file handles
=> ssh: fix handle id generation

lib/kernel/src/erl_boot_server.erl, lib/kernel/test/erl_boot_server_SUITE.erl
Implements `start/2` and `start_link/2` for `erl_boot_server`, which accept a map with configuration options.
The map key `listen_port` allows the configuration of the boot server listening port. If an empty map is provided, or the `listen_port` is zero, the old behavior is kept, i.e. an ephemeral port is used.
Requested in issue #7365.
=> kernel: Add option for erl_boot_server listen port

lib/kernel/doc/guides/eep48_chapter.md
The current definitions are swapped: i.e. we are talking about the module annotation when talking about each entry and vice-versa.
=> Swap explanation of Anno in EEP48 docs

lib/stdlib/src/erl_parse.yrl
Those operators were "obviously" missing. Found when adding specs and type-checking `erl_expand_records`
=> erl_parse: fix binary_op() type

lib/public_key/asn1/EnrollmentMessageSyntax-2009.asn1, lib/public_key/asn1/Makefile, lib/public_key/asn1/PKIXCRMF-2009.asn1, lib/public_key/include/public_key.hrl, lib/public_key/src/public_key.app.src, lib/public_key/src/public_key.erl, lib/public_key/test/public_key_SUITE.erl
Add modern ASN-1 specs to be able to retain support for ExtensionRequest from legacy PKCS-9 spec.
This can open up for further support being added later.
Closes #10028
=> public_key: Add support for ExtensionRequest

lib/compiler/src/v3_core.erl, lib/compiler/test/zlc_SUITE.erl
Fix https://github.com/erlang/otp/issues/10002.
=> compiler: Fix crash when zip generator contains a map pattern

lib/sasl/test/release_handler_SUITE.erl, lib/stdlib/src/supervisor.erl
This PR intends to reduce the memory footprint of supervisors by purging the list of restarts if possible, before and after going into/coming out of scheduled hibernation (`hibernate_after`). Therefore, it checks if the latest restart is already outside of the period, and if so, discards the entire restarts list, as any other restart in it will be even older. I refrained from performing a "proper" cleanup, in the sense of keeping in-period and discarding out-of-period restarts, as this would involve a list traversal which could be expensive.
The reason for doing a purge before going into hibernation is in order to not carry unneeded data over into hibernation.
The reason for doing a purge when waking up from hibernation is that it is likely that enough time has passed and all previous …
=> Purge `supervisor` restarts

lib/compiler/src/beam_ssa_opt.erl, lib/compiler/src/beam_validator.erl, lib/compiler/test/bs_match_SUITE.erl
Success blocks were not adequately tracked, causing `bs_test_tail` instructions to be removed when they shouldn't have been.
Fixes GH-10047
=> beam_ssa_opt: Fix block tracking in bsm_shortcut

lib/kernel/src/inet.erl, lib/kernel/test/Makefile, lib/kernel/test/gen_tcp_api_SUITE.erl, lib/kernel/test/gen_udp_SUITE.erl, lib/kernel/test/kernel_test_lib.erl, lib/kernel/test/test_inet6_tcp.erl, lib/kernel/test/test_inet6_udp.erl, lib/kernel/test/test_inet_tcp.erl, lib/kernel/test/test_inet_udp.erl
The order of the options, should not effect selection of the callback module (when the module option has been provided).
=> Callback module selection for (gen_tcp) listen, connect and (gen_udp) open (OTP-19695)

lib/crypto/c_src/mac.c
Fix #10061.
The static linking was not the direct cause of the crash. The crash was caused by function `fini_mac_types()` indexing array `mac_types[]` beyond bounds which just happened to have benign values when OpenSSL was dynamically linked for some reason.
=> crypto: Fix segfault seen at init:restart with OpenSSL statically linked

.github/workflows/renovate-vendored-deps.yaml
Workflow `renovate-vendored-deps.yaml` couldn't find `github.event.pull_request.head.ref` when trying to checkout to the PR. Changed to `github.head_ref`
=> Add repository field in renovate-vendored-deps workflow for actions/checkout

erts/doc/references/erts_alloc.md, erts/emulator/beam/erl_alloc.c, erts/emulator/beam/erl_alloc_util.c, erts/emulator/beam/erl_alloc_util.h, erts/emulator/sys/common/erl_mmap.c, erts/emulator/sys/common/erl_mmap.h, erts/etc/common/erlexec.c
Introduce erl command line flag `+Mumadtn <bool>` causing `MADV_DONTNEED` to be passed to `madvise()` instead of `MADV_FREE`. Affects all alloc_util allocators where `+M<S>acful` has been enabled to mark unused memory pages as re-usable by the OS.
=> Optional MADV_DONTNEED

lib/diameter/src/transport/diameter_sctp.erl, lib/diameter/src/transport/diameter_tcp.erl, lib/diameter/test/diameter_transport_SUITE.erl
Diameter `message_cb` can return an updated callback that should be the one to be called for all subsequent events (`recv`, `send`, `ack`). When returning the new callback in response of a `send` event the subsequent `ack` event is notified with the old callback instead of the new one. This happens because the message is sent before parsing all the actions returned by the `send` callback.
=> diameter: Call message_cb 'ack' with updated callback

lib/kernel/src/inet_res.erl, lib/kernel/test/inet_res_SUITE.erl
This allows overriding of the OTP Kernel resolver options when calling `inet_res` functions directly.
=> Introduce option list for `inet res` functions

lib/mnesia/examples/bench/README, lib/mnesia/examples/bench/bench.erl, lib/mnesia/test/README
`slave` is removed from comments and private APIs as a unwelcome word.
New word is used for this, `follower`
As `slave` module is also deprecated, usage of `slave:start` in the tests is updated to `peer:start`
=> [mnesia] Slave module deprecation: Replace slave to peer in code and comments

erts/emulator/beam/beam_bp.c, erts/emulator/beam/beam_bp.h, erts/emulator/beam/erl_gc.c, erts/emulator/beam/erl_gc.h, erts/emulator/beam/erl_trace.c, erts/emulator/beam/erl_trace.h, erts/emulator/beam/jit/arm/beam_asm.hpp, erts/emulator/beam/jit/arm/instr_call.cpp, erts/emulator/beam/jit/arm/instr_trace.cpp, erts/emulator/beam/jit/x86/beam_asm.hpp, erts/emulator/beam/jit/x86/instr_call.cpp, erts/emulator/beam/jit/x86/instr_trace.cpp
Crash seen when running `trace_call_memory_SUITE` with `erl -emu_type debug +JPperf true`.
```
#2  0x0000559760782e7b in erl_assert_error
#3  0x0000559760700769 in erts_validate_stack
#4  0x0000559760700939 in copy_erlang_stack
#5  0x0000559760700d5f in do_minor
#6  0x0000559760701291 in minor_collection
#7  0x00005597607028e4 in garbage_collect
#8  0x000055976070348e in erts_gc_after_bif_call_lhf 
#9  0x00007f68d8000759 in global::call_light_bif_shared ()
```
=> Fix debug crash in erts_validate_stack()

.github/scripts/otp-compliance.es, .github/workflows/main.yaml, .github/workflows/osv-scanner-scheduled.yml, .github/workflows/reusable-vendor-vulnerability-scanner.yml, make/openvex.table, vex/otp-26.openvex.json, vex/otp-27.openvex.json
This PR makes the following contributions:
1. Verifies that OTP reported Github Securities exists in the published OpenVEX statements.
2. Open issues in the repo if vendor vulnerabilities are detected
The PR uses `gh` to fetch data from GH Securities, uses the OpenVEX statements from `vex` folder and looks for a specific branch, e.g., `otp-26`, to look into the `otp-26.openvex.json`. Then, it filters out anything that is not OTP related, that is, it keeps OpenVEX statements that follow the purl pattern `pkg:otp/APP-NAME@VERSION`, since these are OTP specific. It also only considers those OpenVEX statements whose status is `fixed` or `affected`. This is because GH Securities lists CVEs, so there is no knowledge of `under_investigation` nor of `not_affected`, thus, these are ignored.
The …
=> Verification of GH Securities included in OpenVEX statements

make/openvex.table, vex/otp-28.openvex.json
The Erlang/OTP vulnerability scanner detected a vulnerability in `pcre2`.
We are investigating if Erlang/OTP is impacted.
=> add openvex under_investigation pcre2 detected vulnerability

lib/crypto/src/crypto.erl
- Add warning for `crypto_one_time_aead/7` about tag length.
- Also clarify docs for `crypto_one_time_aead/6`.
=> crypto: Add warning for crypto_one_time_aead/7 about tag length

lib/syntax_tools/src/erl_syntax_lib.erl, lib/syntax_tools/test/syntax_tools_SUITE.erl
Fix https://github.com/erlang/otp/issues/10103. This fix is already in 28 as https://github.com/erlang/otp/pull/9782.
=> syntax_tools: Backport fix for annotating maybe to OTP-27

lib/ssl/src/tls_gen_connection.erl, lib/ssl/src/tls_record.erl, lib/ssl/src/tls_sender.erl
Optimization commit 28f7e80233718f9f42fe8863370f7e99ee14d22c broke max_fragment_length handling, that is the TLS sender lost its knowledge of the maximum fragment length.
Make TLS sender process aware of it in the cases it is negotiated, for default maximum we do not need to store it in the connection state.
Closes #10191
=> ssl: Correct connection state handling in TLS sender

.github/workflows/reusable-vendor-vulnerability-scanner.yml
app-id is not a secret, but the reusable workflow would need to add yet one more parameter for `uses` call in `maint.yml`, while the dispatch workflow and scheduled job perform an API query and runs in a different environment, so the app-id can be fetched as a `vars` from the repo variable.
to make the integration consistent, we will just make the app-id private and save passing one more argument.
Relates to https://github.com/erlang/otp/pull/10206
=> add app-id as a secret

.github/scripts/otp-compliance.es, .github/workflows/reusable-vendor-vulnerability-scanner.yml, make/openvex.table, vex/otp-28.openvex.json, vex/otp-29.openvex.json, vex/otp-29.openvex.json.license
Produce OpenVEX statements and scan vendor vulnerabilities of next release.
The reason for doing this before a release is to catch and state false positive vendor vulnerabilities. CVEs for a non-release OTP version cannot happen, but we can  already mention which vendor CVEs do not apply.
OTP-19781
=> fix scanner and vex statements for next release

lib/stdlib/src/erl_tar.erl, lib/stdlib/test/tar_SUITE.erl
The leading slash where previously dropped from absolute ustar filename prefixes:
```
> TestFileName1 = string:join(lists:duplicate(99, "a"), "").
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
> TestFileName2 = string:join(lists:duplicate(10, "a"), "").
"aaaaaaaaaa"
> TarTestFileName1 = filename:join("/tmp", TestFileName1).
"/tmp/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
> TarTestFileName2 = filename:join("/tmp", TestFileName2).
"/tmp/aaaaaaaaaa"
> [ok = file:write_file(TestFileName, "hello, world\n") || TestFileName <- [TarTestFileName1, TarTestFileName2]].
[ok, ok]
> erl_tar:create("/tmp/test.tar", [TarTestFileName1, TarTestFileName2]).
ok
>  erl_tar:table("/tmp/test.tar"). …
```
=> stdlib: keep leading slash in absolute ustar filename prefixes

lib/compiler/src/compile.erl, lib/compiler/test/compile_SUITE.erl
Also change extension produced by +to_exp flag to .abstr (the .E extension should only be for source listings).
Note that these flags are not documented; only the from_x flags are.
=> compiler: Add +to_abstr flag to match +from_abstr

erts/preloaded/src/init.erl
Replace verbose case expression with direct boolean assignment.
This makes the code more readable and slightly more efficient by eliminating intermediate variable and pattern matching overhead.
The behavior remains identical: prim_load=true when Mode==embedded, prim_load=false otherwise.
Refactored the `kernel_load_completed` clause in `eval_script/2` to use direct boolean assignment instead of a case expression.
- **Before**: 6-line case expression with intermediate variable `Es`
- **After**: Single line with `prim_load=(Mode == embedded)`
- **Readability**: The intent is immediately clear - `prim_load` directly reflects whether mode is embedded
- **Conciseness**: Reduces code from 6 lines to 2 lines
- **Performance**: Eliminates pattern matching overhead and intermediate record creation …
=> Refactor kernel_load_completed clause for conciseness

.github/scripts/build-macos-wxwidgets.sh, .github/workflows/main.yaml
Compile errors appear when building `wxWidgets` on MacOS using `.github/scripts/build-macos-wxwidgets.sh` with latest Clang 17.
1. Replaced via `sed`: `#include <fp.h>` to `#include <math.h>` in the `wxWidgets/src/png/pngpriv.h`
2. Commented out via `sed`: `#define fdopen`  in `wxWidgets/src/zlib/zutil.h`
3. Minor changes (addressing issues found in sh file by `shellcheck` tool).
The problem caused by the changes in standard library in Clang 17. Alternative solution is installing and using previous Clang 16 via Homebrew or somehow else.
=> Use wxwidgets 3.2.8.1 for CI MacOS build for it has fp.h problem fixed

erts/emulator/test/nif_SUITE_data/nif_SUITE.c, erts/emulator/test/port_SUITE_data/port_test.c, erts/emulator/test/port_bif_SUITE_data/port_test.c
GCC 15 complains about function prototypes without arguments:
| port_test.c: In function 'packet_loop':
| port_test.c:235:7: error: too many arguments to function 'ensure_buf_big_enough'; expected 0, have 1
|   235 |       ensure_buf_big_enough(port_data->header_size);
|       |       ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
| port_test.c:75:13: note: declared here
|    75 | static void ensure_buf_big_enough();
=> erts: fix static function prototypes

lib/stdlib/src/erl_anno.erl, lib/stdlib/test/erl_anno_SUITE.erl
Found while writing tests for https://github.com/ash-project/spark/pull/216
=> Fix `erl_anno:is_anno/1` for end location

erts/emulator/beam/erl_etp.c, erts/etc/unix/etp-commands.in
The Fun heap header word has evolved to not have just the size of the heap object in the arity field, but instead 3 different fields.  When this change was introduced, the ETP utility was not updated so it now prints Fun:s badly.
This is a fix for that...
=> Fix ETP new fun arity format

erts/emulator/beam/erl_proc_sig_queue.c, erts/emulator/test/dirty_bif_SUITE.erl
`erlang:suspend_process()` was broken when applied on processes that happened to be in a dirty-scheduler. The symptom was:
- `internal_error` would be returned when called synchronously
- `not_suspended` would be delivered when called asynchronously, even though the process was in fact suspended
When trying to suspend a processes in a dirty-scheduler, it is actually the dirty-scheduler who suspends the process, by calling `erts_proc_sig_handle_pending_suspend()`. This essentially activates all pending suspend monitors and finally sends all pending sync messages, by calling `sync_suspend_reply()`.
The problem is that when calling the latter, it is passing the process state *before* activating the monitors. In particular, the SUSPENDED flag is not set, what makes `sync_suspend_reply()` …
=> Fix suspend_process() issue on processes in dirty schedulers
